### ISSUE TITLE
配置之后,始终403,原因不明

### ISSUE THREAD

**Issue by eric21** [ssrpanel/ssrpanel#1]
环境:
debian 9.0
mysql 5.7.18
php 7.1.5

.env文件配置如下:
---------begin-----------
APP_NAME=Laravel
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=sspanel
DB_USERNAME=root
DB_PASSWORD=qfIP****nLv

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=b1a80******b60
MAIL_PASSWORD=036******308fe5
MAIL_ENCRYPTION=CRAM-MD5

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=

----------end----------
使用LNMP 1.4的phpmyadmin手动创建了sspanel数据库,导入了db.sql
SSR后端也配置的没问题。。
/usr/local/nginx/conf/nginx.cnf配置内容如下
-------------begin------------------
server
    {
        listen 80 default_server;
        #listen [::]:80 default_server ipv6only=on;
        server_name ss.****.com;
        index index.html index.htm index.php;
        root  /root/ssrpanel/public;

        #error_page   404   /404.html;

        # Deny access to PHP files in specific directory
        #location ~ /(wp-content|uploads|wp-includes|images)/.*\.php$ { deny all; }

        include enable-php.conf;

        location /nginx_status
        {
            stub_status on;
            access_log   off;
        }

        location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
        {
            expires      30d;
        }

        location ~ .*\.(js|css)?$
        {
            expires      12h;
        }

        location ~ /.well-known {
            allow all;
        }

        location ~ /\.
        {
            deny all;
        }

        access_log  /home/wwwlogs/access.log;
    }
include vhost/*.conf;
}
-------------end-----------------

执行php artisan key:generate所得的key，也添加到了/root/ssrpanel/config/app.php里面
已排除public目录权限问题，始终403，原因不明

**Comment by j0hnnie** [comment]
@eric21 不好意思，花了两周业余时间写完的，匆忙上线，有几个文件夹漏提了，明天补上
你可以手动 到 storage下创建 文件夹frameworks ，在frameworks 下创建 cache  sessions  views 三个文件夹，完了再chmod -R 777 storage 下

**Comment by ssrpanel** [comment]
@eric21 不好意思，花了两周业余时间写完的，匆忙上线，有几个文件夹漏提了，明天补上
你可以手动 到 storage下创建 文件夹frameworks ，在frameworks 下创建 cache sessions views 三个文件夹，完了再chmod -R 777 storage 下

**Comment by ssrpanel** [comment]
用lnmp时，记得把整个ssrpanel 文件夹 改用户组  chown -R www:www ssrpanel/

**Comment by ssrpanel** [comment]
@eric21 

nginx 配置文件内要带上 

location / {
    try_files $uri $uri/ /index.php$is_args$args;
}

**Comment by eric21** [comment]
好的，感谢回复。明天我再试试
