### ISSUE TITLE
关于现有续费，商品机制的一些建议

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/SSRPanel#100]
本人在观察与尝试后发现了些不合理的地方；

其实套餐的每月初清空这个有点不合理，我的想法是 按照类型来清空；以下是我自己对不同类型的理解。

流量型 套餐： 本套餐的目的是流量适中，但是可以用很久，且便宜。适合给不常fq的人，列：
     50GB /180天； 这个包的流量在满180后会自动清空；
      续费情况：1. 在流量用光或者账号到期的情况，再购买 25GB/50GB 等 流量型 套餐，会清空已用流量以及上限，将账号天数再加+180天； 
2. 在账号未到期，且流量为用完的情况下，再购买， 这个情况视为到期后的续费情况，在原套餐流量用光或者账号到期时 在重新添加新服务；

重点： 用户买了 流量型的 就无法再自行购买 套餐型 的流量；如果试图购买2个不同类型的套餐，出现警告语，并要求用户向管理请求更改， 这样防止有人来卡机制bug； 这点也需要配合用户设置界面的 付费方式 来进行辅助设置。

时间型 套餐：目前自然是给那些经常使用fq服务的人，
    列：20GB/30天； 这个包的流量在满30天会清空；
     续费情况：1. 在流量用光或者账号到期的情况，再购买时间套餐；清空已用流量以及上限再添加服务
2. 流量用光，账号未到期，再购买时间套餐 = 重新购买服务，也就是情况已用和上限，重新给服务
3. 在流量未用光，账号未到期， 视为续费，流量在套餐周期结束时自动清空一次，并给予下个月购买的套餐流量；时间+30天

补充： 这里的关键就是账号到期时，账号流量使用和上限都清空，SSR关闭； 用户续费也是一样，先清空再添加他续费的套餐类型已经流量/时间； SSR只会在账号未过期还有流量未到达上限，才会保持开启；只要已到达时间/流量上限 就立即关闭；

添加：
 1. 给不同套餐加入节点分组绑定机制；
比例：用户购买 普通套餐，会有3条线（按照现有的线路分组来），过期重置为没有线路或者到权限到X分组；
2. 节点分组机制 更改  ←这个配合1，使用效果更佳；
管理者可以设置一个分组 然后选择该分组内有那几条线路；

现有致命bug： 用户在知道/记录了 其他线路ip的情况；可以使用他套餐没有权限的线路（大前提是他的套餐 SSR没有关闭）；

**Comment by ZBrettonYe** [comment]
添加建议： 用户一个套餐过期后，重置已使用流量，总流量减去对应套餐的流量；

**Comment by ssrpanel** [comment]
已调整
