### ISSUE TITLE
感觉可以给公告加个展开收起按钮

### ISSUE THREAD

**Issue by zcz-nb928** [ssrpanel/SSRPanel#1000]
如图

![image](https://user-images.githubusercontent.com/42931911/46685508-3da85400-cc28-11e8-91b8-294779bb591a.png)
————————————————————————————————————————————
![image](https://user-images.githubusercontent.com/42931911/46685526-4436cb80-cc28-11e8-88fb-6d48c4861a80.png)

主要针对我这种啰嗦话多的人，公告栏能占用浏览器一半的高度（把所有事情都交代了）

这样子能节省一大部分空间，公告旁边有展开按钮，用户如果想看公告也会自己点一下。

最主要很省空间啊！！！

**Comment by hj-mb** [comment]
@zcz-nb928 你这不是自己写出来了吗 为什么不提pr

**Comment by zcz-nb928** [comment]
> @zcz-nb928 你这不是自己写出来了吗 为什么不提pr

github都没玩透，pr也不会提。感觉这个js动画也不是很难，所以就简单建议下。

**Comment by AGLcaicai** [comment]
讲道理。。我连公告在哪发都没找到

**Comment by zcz-nb928** [comment]
> 讲道理。。我连公告在哪发都没找到

在发表文章那，有文章和公告2种可以选

**Comment by AGLcaicai** [comment]
> > 讲道理。。我连公告在哪发都没找到
> 
> 在发表文章那，有文章和公告2种可以选

ok看到了，谢谢！

**Comment by ssrpanel** [comment]
marked稍后加
