### ISSUE TITLE
多个管理员权限设置

### ISSUE THREAD

**Issue by bickernwong** [ssrpanel/SSRPanel#1002]
如果我找两个小弟帮个忙开账户，我把他们的账号设置为管理员，那么能不能设定他们的权限，我想让他们只能看到他自己开的客户，不能看到其他管理员开的客户信息

**Comment by Hamishcn** [comment]
不能

**Comment by niyeyeqi** [comment]
你想只做平台？

**Comment by bickernwong** [comment]
> 你想只做平台？

我只提供服务器和做技术支持，让管理员们打头阵，这样自己会安全很多

**Comment by hj-mb** [comment]
@bickernwong 纯属想多

**Comment by ssrpanel** [comment]
不能，这个是分销系统
