### ISSUE TITLE
节点宕机ServerChan无提醒

### ISSUE THREAD

**Issue by AGLcaicai** [ssrpanel/SSRPanel#1003]
已经网站sckey和微信都已经绑定好了
![qq 20181010192941](https://user-images.githubusercontent.com/21209250/46733499-1bafdf80-ccc3-11e8-895c-acfa1c940ba6.png)
![qq 20181010192958](https://user-images.githubusercontent.com/21209250/46733500-1c487600-ccc3-11e8-9276-2a2a5e935444.png)
在线测试就可以收到提醒
![qq 20181010193129](https://user-images.githubusercontent.com/21209250/46733525-2c605580-ccc3-11e8-949c-5cfd3ba33824.png)
但是上午节点宕机了，没有提醒推送到我的微信

**Comment by cmmdwl** [comment]
我觉得，你可能需要试试在面板上ping下方糖

**Comment by AGLcaicai** [comment]
> 我觉得，你可能需要试试在面板上ping下方糖

server酱和pushbear可以ping通，但是方糖气球ftqq.com就不能ping通
![2](https://user-images.githubusercontent.com/21209250/46786908-e2ca4600-cd68-11e8-94bc-fd56d43f45fb.PNG)
![default](https://user-images.githubusercontent.com/21209250/46786915-e65dcd00-cd68-11e8-8107-b8c8b57ca218.PNG)

**Comment by ssrpanel** [comment]
面板自带ping功能，你用 http://demo.ssrpanel.com/api/ping 来检测，把域名换成你自己的

**Comment by ssrpanel** [comment]
ping是基于tcp，不是icmp

**Comment by AGLcaicai** [comment]
> ping是基于tcp，不是icmp
可以ping通，推送的配置那些都没问题
![default](https://user-images.githubusercontent.com/21209250/46804297-d78d0f80-cd94-11e8-8347-2c609622c305.PNG)
