### ISSUE TITLE
email-请求加一个套餐（流量包）过期提醒

### ISSUE THREAD

**Issue by zcz-nb928** [ssrpanel/SSRPanel#1004]
如题

注：整套逻辑建立在 套餐到期账号还没到期  的情况下
划重点：我们卖的是商品不是账号

**Comment by zcz-nb928** [comment]
希望大佬们能做一下这个，因为套餐到期和账号到期是两码事。并不是所有人都是初始有效期为0的

**Comment by zcz-nb928** [comment]
按照目前的商品逻辑，`账户有效期大于套餐有效期`的情况下，购买新套餐`不会重置账户有效期`。
所以情况会是：当初始账户有效期大于套餐时间或是很大，账户有效期是不会变了

举个栗子： 初始有效期为100天的人，购买了30天的套餐。30天后套餐过期，但因为账户还剩70天，所以不会发送邮件提醒。已经测试👇
![image](https://user-images.githubusercontent.com/42931911/46751213-701b8500-ccec-11e8-87c9-6f06a0582787.png)

我不知道在你们看来这有没有意义，只是个人觉得还是有点重要的
接受反驳，如有哪里没有考虑完整，接受友好提醒

**Comment by zcz-nb928** [comment]
同样的，之前提现更新成了 过期账号 不可提现。
（因为有些用户套餐到期了，账户有效期还有，他可能靠每日积分艰难度日）

建议再添加：账号里没有  有效套餐的用户，不可提现
@SheffieldLee

**Comment by SheffieldLee** [comment]
账户有效期设置那么长干嘛啊，我都是设置1天，你设置小点（3天内）这些问题都不会有。。。。太长了，容易滋生羊毛党，搞个脚本天天续命签到，到期了自动注册。你怕不怕

**Comment by zcz-nb928** [comment]
> 账户有效期设置那么长干嘛啊，我都是设置1天，你设置小点（3天内）这些问题都不会有。。。。太长了，容易滋生羊毛党，搞个脚本天天续命签到，到期了自动注册。你怕不怕

但是如果卖的是短期商品这些情况同样存在。
而且之后开启提号机，我认为应该也要有这个到期提醒。
毕竟我们卖的是商品，不是账号。这个针对的点不一样

**Comment by SheffieldLee** [comment]
商品到期提醒我会考虑增加，胖虎估计懒得写，我有空写一下

**Comment by zcz-nb928** [comment]
> 商品到期提醒我会考虑增加，胖虎估计懒得写，我有空写一下

谢谢大佬！~

**Comment by SheffieldLee** [comment]
主要我最近事太多了，慢了不要催哦

**Comment by ssrpanel** [comment]
还有，登录送积分，你可以范围 是1-2或者 1-10，每天登录给他送个10M流量。羊毛就羊毛，怎么了？
