### ISSUE TITLE
冲了2000，没有送的2000

### ISSUE THREAD

**Issue by zcz-nb928** [ssrpanel/SSRPanel#1005]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
@ssrpanel 

显示余额只有2000日元

**Comment by zcz-nb928** [comment]
![image](https://user-images.githubusercontent.com/42931911/46747567-3c3c6180-cce4-11e8-9ad2-3e2d619f0e17.png)
原来是给你2000😂

**Comment by cmmdwl** [comment]
没毛病啊，送给作者2000日元，就当赞助了吧

**Comment by zcz-nb928** [comment]
> 没毛病啊，送给作者2000日元，就当赞助了吧

哈哈，虽然和一开始以为的不一样，我也是愿意的。
但是希望胖虎能多看下建议和解答问题  比如我刚提的 #1004
（能进小群就更好了）

**Comment by ssrpanel** [comment]
![image](https://user-images.githubusercontent.com/30641000/46771050-70d00d80-cd24-11e8-9e0b-0843b0b33ed2.png)

**Comment by ssrpanel** [comment]
我看这个解释是 注册人和 我都有，难道是得等到消费掉2000日元

**Comment by ssrpanel** [comment]
我们会送给您和您的朋友礼券。。。这个解释特么的就是双方都有啊

**Comment by zcz-nb928** [comment]
> 我们会送给您和您的朋友礼券。。。这个解释特么的就是双方都有啊

hh,根据左右两边的介绍，我猜测是我充值2000，你可以直接拿2000日元。然后我要把这2000日元花完，我才可以获得礼品券，礼品券估计也挺特殊的，因为要刺激我下次消费
![image](https://user-images.githubusercontent.com/42931911/46777436-104fc900-cd42-11e8-927f-289b439a9fd5.png)

**Comment by ssrpanel** [comment]
2000日元合计才100多块

**Comment by ssrpanel** [comment]
@zcz-nb928 还真没有，我也没有2000日元，估计得等你消费完了我才有
