### ISSUE TITLE
代码改进建议-订单成功的处理

### ISSUE THREAD

**Issue by xsir317** [ssrpanel/SSRPanel#1006]
跟代码的时候看到 YzyController/tradePaid 方法里，做了“订单成功之后，更新订单状态、加流量，改账户过期时间，重新生成用户标签”的工作， 而在  UserController/buy 的余额购买成功的方法中，做了同样的事。

我认为这2块代码功能和场景几乎是一样的，是否可以将这2块代码提取为orderSuccess( ) 方法，这样甚至后台也能让管理员手动指定某订单为已到账（如果需要）。

**Comment by SheffieldLee** [comment]
你这个想法很不错，这两个方法一个是有赞一个是余额支付的。

**Comment by xsir317** [comment]
> 你这个想法很不错，这两个方法一个是有赞一个是余额支付的。

是的，在余额支付的时候和有赞支付回调的时候，都是“订单支付完毕，处理成功订单”的逻辑，所以应该完全是一样的。 这个逻辑应当提取出来。以后如果有别的手动补单、其他支付渠道成功回调、模拟测试到账功能等，都应当调用这个方法来实现到账。

**Comment by ssrpanel** [comment]
我知道啊，你看那个resource/system.blade.php 你估计会吐血。全都是重复的。不过复制黏贴的时候特别快
