### ISSUE TITLE
付费用户 与 非付费用户，首次使用网站判断

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/SSRPanel#1009]
（做个笔记，可能之后自己就来pr了）

目前想法：
- [x] 付费用户： iOS 账号密码变为可见，售后信息变为可见；
- [x] 非付费用户：导购，已经付费后权限说明；
- [ ] 首次使用网站：启动面板说明.js, 对面板功能进行粗略介绍；

判断想法：
付费/非付费
1. orderlist 里 除去未支付的订单，还有其他订单 即为付费用户，反之非付费；
2. 流量总额大于邀请赠送+注册默认， 即为付费，反之非付费；

首次使用：
最后一次使用时间为0；

**Comment by ZBrettonYe** [comment]
判断想法：
付费/非付费
1. orderlist 里 除去未支付的订单，还有其他订单 即为付费用户，反之非付费；
2. 流量总额大于邀请赠送+注册默认， 即为付费，反之非付费；

首次使用：
最后一次使用时间为0；

**Comment by zcz-nb928** [comment]
有个人，买了20块的服务然后总是要appleid，因为还有很多软件国区搜不到。
可是他已经过期好几个月了

**Comment by cmmdwl** [comment]
哪还要判断商品是否是免费的

**Comment by garhing** [comment]
![image](https://user-images.githubusercontent.com/37818717/47284366-af65a200-d619-11e8-8eb3-07f8079bba9e.png)
当用户产生使用流量即非初次使用，在index加个判断就行，控制器都不用管。

**Comment by garhing** [comment]
至于内容，不提pr自己可以随便来.如果提pr,像公告一样改改userController，加几行就OK了

**Comment by ZBrettonYe** [comment]
@garhing 所以首次使用网站的判断方法就是 非付费用户+ 已使用流量为0  这样来判断？

不知道panel支不支持cookies 来记录首次登陆

**Comment by ssrpanel** [comment]
已加
