### ISSUE TITLE
邮件发送问题

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#101]
更新下ISSUE,已经解决了.

参考此链接: https://stackoverflow.com/questions/30714229/laravel-smtp-driver-with-tls-encryption

smtp接口用587/tls加密,mail.php中增加下面语句即可.

  'stream' => [
        'ssl' => [
            'allow_self_signed' => true,
            'verify_peer' => false,
            'verify_peer_name' => false,
        ],
    ],

根据iredmail文档提示主要是需要php 禁用 ssl 证书有效性验证,(php5.6后强制要求验证证书有效性,增加上述上述语句就关闭了这个有效性验证)

**Comment by ZBrettonYe** [comment]
用Centos没有这个问题；Debian有，我昨天试来好几次

**Comment by 1021435278** [comment]
@ZBrettonYe @ssrpanel 

我的是CentOS 7,就出现这个问题.  

以前wordpress的smtp插件也有类似的问题, 我看了这个文章解决掉,但是laravel框架不熟悉,所以可能要各位指点下如何找到需要关闭的位置了.

https://evert.meulie.net/faqwd/unable-to-send-email-from-wordpress-via-smtp-php-5-6/

**Comment by ZBrettonYe** [comment]
@1021435278 我之前用Debian 以前用Centos使用成功过； 现在改回Centos 还是可以行的；Debian用宝塔感觉宝塔有不兼容的BUG；用Centos算了

**Comment by ssrpanel** [comment]
@1021435278  /config/mail.php ，找到 'encryption' 选项，把值改为ssl或者tls（取决于你的邮件服务器）

**Comment by ssrpanel** [comment]
@1021435278 https://docs.iredmail.org/use.a.bought.ssl.certificate-zh_CN.html

**Comment by ssrpanel** [comment]
@1021435278 直接用mail会一直发。那个测试的时候用的

**Comment by ssrpanel** [comment]
@1021435278 还有，tls是25端口 ，ssl 才是465，我估计你那个发信证书搞错了。

**Comment by 1021435278** [comment]
@ssrpanel 

ssl / 465,  ssl/587都测试过了,所有的可能性都测试过了, 有问题我才会提issue,否则帮忙继续看看?

**Comment by ssrpanel** [comment]
@1021435278 /config/mail.php ，找到 'encryption' 选项，把值改为null，不使用加密发邮件，试一下

**Comment by ssrpanel** [comment]
如果还不行，把php.ini里的open.ssl里的证书去掉，保存并重启php-fpm，再试一下，（配合上面那个 encryption=null）

**Comment by 1021435278** [comment]
@ssrpanel null需要25端口,现在主机商基本都屏蔽了25端口, 我测试看看.

**Comment by DanielZhang17** [comment]
我这边试了很多方法还是
Connection could not be established with host smtp-mail.outlook.com [Connection timed out #110]
上面那个也加了

**Comment by wangrong1994** [comment]
请问注册的时候提示激活邮件已发，可是没有收到，这是什么原因呢？config/mail.php里的 'username' 和'password'需要填吗？

**Comment by 828768** [comment]
@wangrong1994 [SSRpanel搭建相关设置问题](http://sobaigu.com/shadowsocks-ssrpanel-setting.html)

**Comment by Mr-Kwok** [comment]
> 请问注册的时候提示激活邮件已发，可是没有收到，这是什么原因呢？config / mail.php里的'用户名'和'密码'需要填吗？

我也是这个问题，你成功了吗？
