### ISSUE TITLE
节点宕机ServerChan无提醒

### ISSUE THREAD

**Issue by AGLcaicai** [ssrpanel/SSRPanel#1010]
面板可以ping通，推送的配置那些都没问题
![46804297-d78d0f80-cd94-11e8-8347-2c609622c305](https://user-images.githubusercontent.com/21209250/46843617-579f8d80-ce06-11e8-9eb4-46a03b78ced6.png)

**Comment by ssrpanel** [comment]
你最好看看serverchan后台

**Comment by AGLcaicai** [comment]
> 你最好看看serverchan后台

serverchan后台配置一切都正常，ssrpanel后台填的也是对应的sckey
