### ISSUE TITLE
安装php composer.phar install php artisan key:generate报错

### ISSUE THREAD

**Issue by zs910208565** [ssrpanel/SSRPanel#1013]
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize

In Connection.php line 647:
                                                                               
  SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'f  
  orge' (SQL: select * from `config`)                                          
                                                                               

In Connector.php line 68:
                                                                               
  SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'f  
  orge'                                                                        
                                                                               

Script php artisan optimize handling the post-install-cmd event returned with error code 1

**Comment by hj-mb** [comment]
弱智问题 建议关闭

**Comment by ssrpanel** [comment]
认真看项目首页

**Comment by ssrpanel** [comment]
别人fork的或者别人的教程，我不能做保证。按我项目首页里的步骤一步步的安装下去，绝对可以跑起来
