### ISSUE TITLE
购买流量，生成不了订单，无法支付

### ISSUE THREAD

**Issue by hais1992** [ssrpanel/SSRPanel#1015]
已更新至最新版，配置好有赞 和 有赞的回调、还有把所有的推送配置都勾上了。

![tim 20181015172245](https://user-images.githubusercontent.com/5223993/46942092-2ab9d780-d09f-11e8-9112-4d7ec40dc90f.png)

**Comment by ssrpanel** [comment]
翻一番close issues

**Comment by SRCOL** [comment]
确认回调都勾选了那就是文件夹权限问题：strange或者public/assets

**Comment by hais1992** [comment]
> 确认回调都勾选了那就是文件夹权限问题：strange或者public/assets

嗯嗯，是 public/assets 权限问题，多谢。
