### ISSUE TITLE
回馈提示时候要对用户友好点

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#1016]
<img width="1128" alt="1" src="https://user-images.githubusercontent.com/21263352/46959851-a16ec900-d0cf-11e8-8544-2292a5463fee.png">
<img width="1128" alt="2" src="https://user-images.githubusercontent.com/21263352/46959854-a3d12300-d0cf-11e8-8d05-360f481e24fc.png">
这个是我的测试，使用ipv6 访问 
然后不知道发生了啥，就成这样了。。

**Comment by cmmdwl** [comment]
检查框架log文件并没有发现异常错误

**Comment by cmmdwl** [comment]
建议，报错要在页面上提示，不要跳转到这样的页面

**Comment by hj-mb** [comment]
我有一个十分不解的疑问 你们为什么非要用ipv6

**Comment by cmmdwl** [comment]
面向未来啊·

**Comment by cmmdwl** [comment]
cmmdwl:
刚刚测试了一下，如果页面长时间不刷新，也会出现这种情况

**Comment by ssrpanel** [comment]
已修复
