### ISSUE TITLE
一键安装的小火箭

### ISSUE THREAD

**Issue by zcz-nb928** [ssrpanel/SSRPanel#1017]
一键安装好小火箭，打开要输入apple id   并且会一直停留在那个画面    
如果输入了已经购买过这个软件的id  ，他就闪退了

**Comment by ZBrettonYe** [comment]
小火箭的安装包，需要自己的安装包， 百度：ios抓包

**Comment by zcz-nb928** [comment]
> 小火箭的安装包，需要自己的安装包， 百度：ios抓包

谢谢！

**Comment by zcz-nb928** [comment]
> 小火箭的安装包，需要自己的安装包， 百度：ios抓包

那是不是在不同的用户端是需要同一个apple id的

**Comment by ssrpanel** [comment]
@zcz-nb928 用你自己的美区ID （已经购买了小火箭），然后你自己通过你这个美区ID下载小火箭，自己抓它这个ipa包，然后覆盖public/clients下的小火箭，然后改clients/ipa_list.list文件下的路径即可，用户在线安装的时候一定得用你这个抓出来的美区ID安装

**Comment by ssrpanel** [comment]
@zcz-nb928 否则100%闪退

**Comment by mzfqy** [comment]
解决了吗我也是10m和你一样的情况
