### ISSUE TITLE
新增管理员权限是不是太大了？

### ISSUE THREAD

**Issue by SRCOL** [ssrpanel/SSRPanel#1018]
这个问题很早就有了，一直忘了说；能直接修改ID为1（即系统默认管理员）的任何配置，权限跟默认管理员一样大。

**Comment by ZBrettonYe** [comment]
感觉问题问的怪怪的。 什么都看不懂。。。

**Comment by cmmdwl** [comment]
这不是多管理员面板，是单管理员面板，你要有兴趣可以提pr来搞多管理员权限的面板

**Comment by ssrpanel** [comment]
我正在给人定制带权限的，大部分人不会有这种需求的，因为有这种需求的，基本要做代理

**Comment by ssrpanel** [comment]
分销商系统

**Comment by SRCOL** [comment]
@cmmdwl 
没这个能力
@ssrpanel 
我是因为网站跟另一个人一起管理，万一他哪天发疯把我的帐号给改了。。。（虽然不是改不回来）

**Comment by ssrpanel** [comment]
@SRCOL 哈哈哈嗝
