### ISSUE TITLE
运行php composer.phar install出错

### ISSUE THREAD

**Issue by lyz913421** [ssrpanel/ssrpanel#102]
PHP已经是7.1.7
运行php composer.phar install后提示如下错误
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for intervention/image 2.4.1 -> satisfiable by intervention/image[2.4.1].
    - intervention/image 2.4.1 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
  Problem 2
    - intervention/image 2.4.1 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - mews/captcha 2.1.7 requires intervention/image ~2.2 -> satisfiable by intervention/image[2.4.1].
    - Installation request for mews/captcha 2.1.7 -> satisfiable by mews/captcha[2.1.7].

  To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/php/etc/php.ini
    - /usr/local/php/conf.d/002-zendguardloader.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by ZBrettonYe** [comment]
php 没安装fileinfo 插件

**Comment by ssrpanel** [comment]
@lyz913421 手动编译或者第三方面板安装gd、gd2、fileinfo插件
