### ISSUE TITLE
发邮件能否使用STARTTLS加密？

### ISSUE THREAD

**Issue by dovela** [ssrpanel/SSRPanel#1020]
ouelook的smtp需要用STARTTLS加密方式，只填写env文件的话就会报错，是我的设置问题吗？

Connection could not be established with host smtp.office365.com [Unable to find the socket transport "starttls" - did you forget to enable it when you configured PHP? #32630]

**Comment by ssrpanel** [comment]
这个没碰到过。

**Comment by ZBrettonYe** [comment]
填TLS试试
