### ISSUE TITLE
节点宕机后serverchan始终无提醒

### ISSUE THREAD

**Issue by AGLcaicai** [ssrpanel/SSRPanel#1021]
面板ping方糖是可以ping通的
![46804297-d78d0f80-cd94-11e8-8347-2c609622c305](https://user-images.githubusercontent.com/21209250/47205525-c063a880-d3b8-11e8-8252-3e676d20b445.PNG)
已经网站sckey和微信都已经绑定好了
![46733499-1bafdf80-ccc3-11e8-895c-acfa1c940ba6](https://user-images.githubusercontent.com/21209250/47205512-b477e680-d3b8-11e8-9b64-0ed84b36b642.png)
![46733500-1c487600-ccc3-11e8-9276-2a2a5e935444](https://user-images.githubusercontent.com/21209250/47205514-b6da4080-d3b8-11e8-8d01-0438fdec60a9.png)
但是下午节点宕机时，微信一直没收到提醒，但是测试发信的时候又可以收到

**Comment by ssrpanel** [comment]
。。。不晓得。看看有没有错误日志？
