### ISSUE TITLE
建议，代理封禁后提示用户购买可以解除封禁

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#1022]
建议，代理封禁后提示用户购买可以解除封禁

**Comment by SRCOL** [comment]
本来购买就是可以解除封禁的啊。。。。

**Comment by ssrpanel** [comment]
他说的是提示购买

**Comment by SRCOL** [comment]
尴尬。。。是我没看清，抱歉

**Comment by zcz-nb928** [comment]
我写的这样
![image](https://user-images.githubusercontent.com/42931911/47419512-f5a03a00-d7ae-11e8-99b6-c96d30e64ba8.png)
加个else就行，不过不知道怎么提pr

**Comment by littlesker** [comment]
这个功能可以，不然有的人还莫名其妙怎么不能用了！

**Comment by ssrpanel** [comment]
鸡肋需求，发公告写清楚即可
