### ISSUE TITLE
有兴趣集成V2ray么？

### ISSUE THREAD

**Issue by aiyahacke** [ssrpanel/SSRPanel#1025]
![0cf1ad38f1e15ba1005e2d75cb564211.png](http://tc.ffsky.net/images/2018/10/22/0cf1ad38f1e15ba1005e2d75cb564211.png)

Hello胖虎，有兴趣集成V2ray么？

**Comment by aiyahacke** [comment]
刚刚写好，测试了下没啥问题，控制V2Ray的节点端是用java写的

**Comment by cmmdwl** [comment]
提pr吧，肯定支持

**Comment by cmmdwl** [comment]
[`https://github.com/ssrpanel/SSRPanel/issues/300`](url)

**Comment by cmmdwl** [comment]
#300

**Comment by garhing** [comment]
不错不错，不是先提pr再拉群么

**Comment by ssrpanel** [comment]
@aiyahacke 求提PR

**Comment by ssrpanel** [comment]
群里聊
