### ISSUE TITLE
账号有效期无用

### ISSUE THREAD

**Issue by ppllpig** [ssrpanel/ssrpanel#103]
包月用户购买套餐或套餐用户还有流量的时候，账号到期直接导致SSR禁用，这两天几个人都是这样，得手动增加时间。一定要账号有效期么，还不如永久了！

**Comment by ZBrettonYe** [comment]
那就把套餐时间改的很大 不就好了，要永久的话

**Comment by ppllpig** [comment]
@ZBrettonYe 账号到期，即使套餐没到期，还是停用的

**Comment by ssrpanel** [comment]
@ppllpig 正常情况下，账号购买了套餐之后，套餐设定了有效期多少天，账号就会自动按这个天数加上去

**Comment by 1021435278** [comment]
这个问题我也遇到了, 账号创立时候尽量设定时间最少一年.

另外默认密码建议最少6-8位,否则扫描的太多了.

**Comment by ssrpanel** [comment]
@1021435278 
1.已使用流量大于等于可用流量，账号不可连接
2.账号SSR状态为禁用，账号不可连接

账号到期，套餐没到期？这不合理。正常情况不会出现这样的。因为账号假设有效期还有10天，这10天其SSR状态都是正常的，没有流量就连不上，有流量就可以连的上。这个时候他买了某个套餐，套餐里假设有10G流量，套餐设定为10天有效期，那么他此时的有效期应该是20天。10天后套餐到期了自动扣掉流量，怎么用户的有效期应该减10天。还剩10天。

**Comment by ssrpanel** [comment]
密码问题我已经改掉了，默认6位，去掉@符号了。因为单端口不允许特殊符号出现。
