### ISSUE TITLE
添加一个给全体用户更换uuid的功能

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#1031]

**Comment by ssrpanel** [comment]
有什么需求吗，v2ray我还没跑起来

**Comment by cmmdwl** [comment]
老用户没有uuid
更换uuid 可以解决识别问题

**Comment by ssrpanel** [comment]
已加
在ssrpanel目录下 执行：`php artisan upgradeUserVmess` ，会给没有生成过vmess_id的用户生成一个vmess_id
