### ISSUE TITLE
节点管理 里面的状态 3个数字什么含义啊??

### ISSUE THREAD

**Issue by pch18** [ssrpanel/SSRPanel#1035]
节点管理 里面的状态 3个数字什么含义啊??
![image](https://user-images.githubusercontent.com/19822708/47512327-e99f9f80-d8b6-11e8-8df2-f4584b774fd2.png)

**Comment by cmmdwl** [comment]
1分钟负载
5分钟负载
15分钟负载

**Comment by ssrpanel** [comment]
@cmmdwl
