### ISSUE TITLE
我发现被封禁的账号，所生成的邀请码，还能注册

### ISSUE THREAD

**Issue by vft9nesd** [ssrpanel/SSRPanel#1036]
有部分骚操作的人，用邀请码注册了一堆号，真是够骚的，然后我把它封了，发现还注册了一堆，原因是他之前生成的邀请码还有效。。。

**Comment by vft9nesd** [comment]
也怪我没有设置邮件验证吧，懒得设置，觉得影响注册体验呢。。

**Comment by cmmdwl** [comment]
不怪你，这个是正常的bug 到时候添加一个判断是否是被封号的邀请码注册

**Comment by vft9nesd** [comment]
@ssrpanel 又发现了一个可能的bug，那个骚操作的人，生成了一个邀请码，这一个邀请码注册了很多号，但该邀请码显示未使用~嘤嘤嘤
排除定时任务的问题，我自己生成邀请码测试，发现一切正常，注册之后正常显示已使用

**Comment by ssrpanel** [comment]
@vft9nesd 截图看看？包括使用记录和后台

**Comment by ssrpanel** [comment]
哦对了，你系统管理里要打开强制邀请码，如果不是强制邀请码，而是邀请码选填，那就会这样

**Comment by vft9nesd** [comment]
可能是小BUG吧，之前的版本，我没更新，还没有强制邀请码的选项呢
![image](https://user-images.githubusercontent.com/24932999/47830058-30b0f780-ddc5-11e8-8e23-ac21b1d07e4f.png)
这个人生成的这个邀请码注册了这么多，邀请码还是未使用的，直到过期才不能用
![image](https://user-images.githubusercontent.com/24932999/47830094-563e0100-ddc5-11e8-80b9-69107ce692e2.png)
唯独这个人的账号生成的邀请码没法失效，测试别的账号，邀请注册之后立马失效了，没有手动操作过数据库，定时任务也没问题。。
更新之后暂没发现这个问题，也不知道问题出在这个人身上，还是面板上。。

**Comment by ssrpanel** [comment]
新版本，可以允许邀请码重复选填，所以如果为打开强制邀请码，则邀请码可以重复注册貌似。

**Comment by ssrpanel** [comment]
fixed
