### ISSUE TITLE
服务器正常没有宕机，但是每个小时整点。所有服务器都会报一次宕机提醒。然后自动进入维护状态。

### ISSUE THREAD

**Issue by pch18** [ssrpanel/SSRPanel#1039]
服务器正常没有宕机，但是每个小时整点。所有服务器都会报一次宕机提醒。然后自动进入维护状态。
![00455f03-ae8c-4890-bec3-6d9f115d7d2c](https://user-images.githubusercontent.com/19822708/47545173-c6600900-d925-11e8-902f-bef26b1be528.jpeg)

**Comment by cmmdwl** [comment]
![4](https://user-images.githubusercontent.com/21263352/47544344-14224480-d919-11e8-859a-10aee543b127.png)
这个页面也提示宕机么？

**Comment by cmmdwl** [comment]
这个页面提示宕机说明节点与数据库通信不正常，服务器就会报宕机

**Comment by pch18** [comment]
这个界面没有显示宕机，有三个数字的。

**Comment by pch18** [comment]
后台是这样的，但是每个小时还是给我推送所有服务器的宕机信息
![270d97f4-02d7-462f-be53-2f33a4a1779c](https://user-images.githubusercontent.com/19822708/47545313-9b29e980-d926-11e8-86e8-c17769383d8b.jpeg)

**Comment by zcz-nb928** [comment]
我倒是出现了在那个页面提示宕机，然后服务器一切正常，也能连通数据库，后来是挨个reboot一下才好的

**Comment by ssrpanel** [comment]
1.节点服务器挂了（节点鸡的母鸡太垃圾，被抢资源了，导致你的节点机假死，再次强调，不要用OPENVZ）
2.节点服务器的SSR后端挂了（内存太小导致进程被自动杀死，母鸡太垃圾导致进程被自动杀死，单个节点太多人用，配置又不够，导致SSR进程被自动杀死，反正就是进程死了或者假死）
3.节点机和数据库连接不畅（很少，除非你把数据库放大陆，节点机放国外，线路又是NTT或者163那种垃圾线路，延迟太高了导致节点机每分钟上报数据到数据库的时候没有正常上报）

**Comment by perfect-network** [comment]
> 1.节点服务器挂了（节点鸡的母鸡太垃圾，被抢资源了，导致你的节点机假死，再次强调，不要用OPENVZ）
> 2.节点服务器的SSR后端挂了（内存太小导致进程被自动杀死，母鸡太垃圾导致进程被自动杀死，单个节点太多人用，配置又不够，导致SSR进程被自动杀死，反正就是进程死了或者假死）
> 3.节点机和数据库连接不畅（很少，除非你把数据库放大陆，节点机放国外，线路又是NTT或者163那种垃圾线路，延迟太高了导致节点机每分钟上报数据到数据库的时候没有正常上报）
呃呃，vultr 1G 节点到前端延迟0.5ms 时间同步，并且。。。上报CPU啥的正常
