### ISSUE TITLE
邮件投递记录错误

### ISSUE THREAD

**Issue by Live520** [ssrpanel/ssrpanel#104]
邮件发送，激活都正常的，但是邮件投递记录无法查看，点击就提示Whoops, looks like something went wrong.

**Comment by ZBrettonYe** [comment]
@Live520 出示一下，报错的截图

**Comment by Live520** [comment]
http://ww3.sinaimg.cn/large/0060lm7Tly1flhnv909sdj30um0mvwhg.jpg
麻烦查看下哈

**Comment by ssrpanel** [comment]
@Live520 好滴，我查证下，谢谢上报BUG

**Comment by Live520** [comment]
@ssrpanel 客气啦~~

**Comment by Live520** [comment]
@ssrpanel 已经知道问题所在了，在管理面板删除用户后，再去看邮件发送记录就会报错，要去数据库删除对应的数据就正常了，希望以后可以在删除用户的同时删除关联的其他数据库信息

**Comment by ssrpanel** [comment]
@Live520 其实我在新版本里把删除用户这个功能又去掉了。坑太多了。

强烈不建议删除用户，状态里改为禁止登陆、禁用即可
