### ISSUE TITLE
请问这是一个BUG吗？关于返利提现界面

### ISSUE THREAD

**Issue by lirongkiss** [ssrpanel/SSRPanel#1041]
如图：不管是客户端控制面板还是管理后台看到的提现金额没有小数点了。
![qq 20181026222801](https://user-images.githubusercontent.com/31896738/47573050-f5e73380-d96e-11e8-9461-133f2fdb4ffb.png)
![qq 20181026222844](https://user-images.githubusercontent.com/31896738/47573063-faabe780-d96e-11e8-946e-522a672edd5f.png)

**Comment by ssrpanel** [comment]
2.4 +0.8 = 3.2 ，显示320 是这个意思吗？

**Comment by lirongkiss** [comment]
是的，就是这个意思。

**Comment by ssrpanel** [comment]
貌似新版已经修复了，你这个版本太旧了
