### ISSUE TITLE
关于端口自动释放

### ISSUE THREAD

**Issue by alienxcn** [ssrpanel/SSRPanel#1042]
项目文件中，ssrpanel/app/Console/Commands/AutoJob.php line260

User::query()->where('id',$user->id)->update(['port'=>0]);

数据库表中，user表的port字段是唯一的，这时写入0值会抛出异常。这个应该怎么解决呢？

**Comment by ssrpanel** [comment]
user表的port早就移除了 唯一索引了。

**Comment by alienxcn** [comment]
嗯嗯，谢谢您。我去更新下数据库。
