### ISSUE TITLE
今晚升级后,管理员无法登陆进去了

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/SSRPanel#1043]
胖虎请问如何解决? 我看到这次更新是因为更新用户密码加密改为HASH了, 这种情况如何修复? 已经导入最新的sql了.

**Comment by cdlaimin** [comment]
如果正确安装完成后发现admin无法登陆，请到SSRPanel目录下执行如下命令：
php artisan upgradeUserPassword

admin的密码将被改为admin

**Comment by 1021435278** [comment]
@cdlaimin  试过了, 仍然不行.  请问进数据库直接修改密码,  admin这个密码对应sha加密是什么? 可否告知?

**Comment by zcz-nb928** [comment]
不仅是admin的密码，所有人的密码都被改为与用户名相同

**Comment by cdlaimin** [comment]
> 不仅是admin的密码，所有人的密码都被改为与用户名相同



> @cdlaimin 试过了, 仍然不行. 请问进数据库直接修改密码, admin这个密码对应HASH加密是什么? 可否告知?

$2y$10$PQfctfoHwwu37lkCnkmX2u1Msp3Ry4GVarMEiNGqG/hfTWHZJZXKG
这是123456789的

**Comment by 1021435278** [comment]
@cdlaimin 我的天, 真坑爹,这个..

我进数据库直接赋予一个用户为管理员,然后修改了可以了.

另外请教下,为什么现在用户中心看不到分配给他的节点信息了? 应该怎么做?

**Comment by LoveMyself666** [comment]
@cdlaimin 更新之后无法添加节点了是怎么回事？显示：添加失败：SQLSTATE[42S22]:Column not found : 1054 Unkbown column.................用户信息也编辑不了，按理说能进面板数据库连接是正常的呀？

**Comment by cdlaimin** [comment]
> @cdlaimin 更新之后无法添加节点了是怎么回事？显示：添加失败：SQLSTATE[42S22]:Column not found : 1054 Unkbown column.................用户信息也编辑不了，按理说能进面板数据库连接是正常的呀？

数据库是不是没更新啊。。。

**Comment by cdlaimin** [comment]
> @cdlaimin 我的天, 真坑爹,这个..
> 
> 我进数据库直接赋予一个用户为管理员,然后修改了可以了.
> 
> 另外请教下,为什么现在用户中心看不到分配给他的节点信息了? 应该怎么做?

不知啊 没遇到过

**Comment by 1021435278** [comment]
> > @cdlaimin 我的天, 真坑爹,这个..
> > 我进数据库直接赋予一个用户为管理员,然后修改了可以了.
> > 另外请教下,为什么现在用户中心看不到分配给他的节点信息了? 应该怎么做?
> 
> 不知啊 没遇到过

https://github.com/ssrpanel/SSRPanel/issues/1019 参考这个issue,里面有个人让我看以前的issue,我差不多抄了个遍还没有发现.
