### ISSUE TITLE
胖虎有个laravel项目迁移问题请教下(其它熟悉laravel项目的也可以指点下)

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/SSRPanel#1045]
有个laravel 5.5项目需要迁移服务器,我git拉到新机器后, composer update nothing 恢复开发/运行环境发现有错误, 具体出错截图后附,请问这个应该怎么解决?

![asd](https://user-images.githubusercontent.com/32491066/47619640-291af580-db1c-11e8-856b-45405281ffed.png)

**Comment by ssrpanel** [comment]
singnal 9，，，好像碰到过一次，你再执行一次php composer update应该就会消失的

**Comment by ssrpanel** [comment]
我记得这种情况多数跟环境有关

**Comment by 1021435278** [comment]
@ssrpanel  你说的对,但是这样升级后,开发和依赖环境会不会改变导致无法程序无法运行.

此外运行php composer update提示无此命令,  我是迁移后用composer update nothing 来恢复开发和运行环境的.
