### ISSUE TITLE
dalao出现这个报错是什么原因

### ISSUE THREAD

**Issue by victoryLV** [ssrpanel/SSRPanel#1046]
[root@izt4nh65rh3syhw8hgloflz ~]# java -jar ssrpanel-v2ray-0.0.2-SNAPSHOT.jar
Error: Unable to access jarfile ssrpanel-v2ray-0.0.2-SNAPSHOT.jar

**Comment by Supsfun** [comment]
我也是这个报错

**Comment by ssrpanel** [comment]
没有权限，注意给整个文件夹授权
chmod -R 755 XXXX

**Comment by ssrpanel** [comment]
包括 v2ray-core 和 ssrpanel-v2ray 控制台

**Comment by ssrpanel** [comment]
两个文件夹都给755 或者777 权限
