### ISSUE TITLE
api 文档改进

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/SSRPanel#1049]
# 登录API

参数名称 | 参数含义 | 类型与值
-- | -- | --
status | 登录是否成功 | 成功返回success，失败返回fail
message |  登录回馈信息 | 成功返回‘登录成功’，失败时返回失败理由
id | 用户ID | int(11)
username | 用户邮箱 | varchar(128)
port | 账号代理端口 | int(11)
passwd | 用户代理密码 | varchar(16)
vmess_id | V2ray用户ID | varchar(64)
transfer_enable | 可用流量 | bigint(20) 单位为字节,既 B
u | 已上传流量 | bigint(20) 单位为字节,既 B
d | 已下载流量 | bigint(20) 单位为字节,既 B
t | 最后使用时间 |int(11) 单位为 未知
enable | 代理状态 | tinyint(4) 1-开启，0-关闭
method |  加密方式 | varchar(30)
protocol | 协议 | varchar(30)
protocol_param | 协议参数 | varchar(30)
obfs | 混淆 | varchar(30)
obfs_param | 混淆参数 | varchar(255)
speed_limit_per_con | 单连接限速 | int(255) 单位KB
speed_limit_per_user | 单用户限速 | int(255) 单位KB
gender | 性别 | tinyint(4) 0-女，1-男
wechat | 微信 | varchar(30)
qq | QQ | varchar(20)
usage | 代理用途 | varchar(10) 1-手机，2-电脑，3-路由器，4-其他
pay_way | 付费方式 | tinyint(4) 0-免费，1-季付，2-月付，3-半年付，4-年付
balance | 账号余额 | int(11) 单位：分 
score | 积分 | int(11)
enable_time | 开通日期 | date 格式为 YYYY-MM-DD
expire_time | 过期时间 | date 格式为 YYYY-MM-DD
ban_time | 封禁到期时间 | int(11) 单位为 未知
remark | 备注 | text 
level | 等级：可定义名称 | tinyint(4) 
is_admin | 是否管理员 | tinyint(4) 0-否，1-是
reg_ip | 注册IP | varchar(20) 格式为标准ipv4
last_login | 最后使用时间 | int(11) 单位为 未知
referral_uid | 邀请人ID | int(11)
traffic_reset_day | 流量自动重置日 | tinyint(4) 0表示不重置
status | 账号状态 | tinyint(4) 1-禁用，0-未激活，1-正常
created_at | 账号注册日期 | datetime 格式为 yyyy-MM-dd HH:mm:ss
updated_at | 账号最近变动日期 | datetime 格式为 yyyy-MM-dd HH:mm:ss

**Comment by ssrpanel** [comment]
还有吗？有没有需要其他接口的

**Comment by ZBrettonYe** [comment]
获取节点列表带 ssr:// 的api
还有商店列表 以及 购买的api

**Comment by Losgif** [comment]
我自己写了一些API

**Comment by Losgif** [comment]
Mock 假数据呗

**Comment by Losgif** [comment]
有些代码改动挺多的, 而且Passport 啥的要运行命令
