### ISSUE TITLE
ssrpanel-v2ray-docker

### ISSUE THREAD

**Issue by kszym2002** [ssrpanel/SSRPanel#1050]
编辑了一份 在docker下方便运行v2ray节点的镜像 版本信息 0.0.2的 ssrpanel-v2ray 和 v2ray 3.50
[github](https://github.com/kszym2002/ssrpanel-v2ray-docker)

[docker hub](https://hub.docker.com/r/easonsummer/ssrpanel-v2ray-docker/)

注意
config.properties 这些值必须为下方所示 其他都可以随意调节
````
v2ray路径

v2ray.path=/root/v2

可执行文件名

v2ray.exec=v2ray
````
命令
````
docker run -d -v /你的config.json位置:/root/v2/config.json -v /你的config.properties位置:/root/v2/config.properties --network=host --log-opt max-size=10m --log-opt max-file=3 --restart=always easonsummer/ssrpanel-v2ray-docker
````

**Comment by ssrpanel** [comment]
docker不会用啊。吐血

**Comment by kszym2002** [comment]
https://bfv.tw/index.php/2018/10/30/搭建-ssrpanel-v2ray-docker/ 应该可以帮助到一些人 ^_^

**Comment by ssrpanel** [comment]
tg id 留下，我拉你进群

**Comment by ssrpanel** [comment]
@kszym2002 已收录至wiki

**Comment by kszym2002** [comment]
> tg id留下，我拉你进群
https://t.me/Easonsummer

**Comment by ssrpanel** [comment]
....
拉不了，隐私保护

**Comment by kszym2002** [comment]
> ....
> 拉不了，隐私保护

改好了 应该可以了

**Comment by ssrpanel** [comment]
不行，你加个知识星球，喊一声

**Comment by kszym2002** [comment]
> 不行，你加个知识星球，喊一声


好的 申请加入知识星球了
