### ISSUE TITLE
订阅获取的一直是【无可用节点或账号被封禁或订阅被封禁】，这个是什么原因呢？

### ISSUE THREAD

**Issue by aircross** [ssrpanel/SSRPanel#1051]
订阅获取的一直是【无可用节点或账号被封禁或订阅被封禁】，这个是什么原因呢？
已经购买了流量，也购买了套餐。但是订阅出来的就一直是提示这个
![_20181030155038](https://user-images.githubusercontent.com/7873408/47703546-96817000-dc5b-11e8-8642-ba2f467f1b63.png)

![_20181030155112](https://user-images.githubusercontent.com/7873408/47703561-a436f580-dc5b-11e8-8bc8-f5f35385caf5.png)

**Comment by ssrpanel** [comment]
1.商品要带标签、用户购买服务（商品）的时候会自动打上相同的标签。
2.查看用户的订阅是否被禁用（系统设置里有一个24小时内订阅次数限制，如果超过了就认为这个地址被分享了，滥用，自动封禁）

**Comment by aircross** [comment]
商品加了标签了，出现在用户的界面中了，但是还是订阅获取不到

**Comment by aircross** [comment]
> 1.商品要带标签、用户购买服务（商品）的时候会自动打上相同的标签。
> 2.查看用户的订阅是否被禁用（系统设置里有一个24小时内订阅次数限制，如果超过了就认为这个地址被分享了，滥用，自动封禁）

商品加了标签了，出现在用户的界面中了，但是还是订阅获取不到。订阅应该也没有被禁用，因为环境是我自己搭建来测试的。

**Comment by ZBrettonYe** [comment]
最快的方法，提供你的网站+管理员信息
