### ISSUE TITLE
我想在路由器里运行后端~

### ISSUE THREAD

**Issue by vft9nesd** [ssrpanel/SSRPanel#1054]
做校园网的。。自己的宽带，有公网ip，openwrt中运行server.py报错。。
如果能在路由器中运行，就省个服务器了
openwrt中有ssrserver插件，但是那个是本地的运行的，不会对接远程数据库，或者说是我不懂它~那个可以启动的
![image](https://user-images.githubusercontent.com/24932999/47807180-6b3f7380-dd76-11e8-86af-a40696982188.png)

**Comment by vft9nesd** [comment]
还要单端口多用户。。因为只有53能用嘛。。。
还有v2ray能否在openwrt中运行，网上能找到的基本都是v2ray的客户端，而不是server

**Comment by ssrpanel** [comment]
大佬已经在开发了

**Comment by ssrpanel** [comment]
在内部群里内测了

**Comment by vft9nesd** [comment]
! 小群吗~没钱进啊~

**Comment by vft9nesd** [comment]
我发现老版本的server能运行了，但是run.sh 缺少很多命令支持，padavan

**Comment by vft9nesd** [comment]
但是开启混淆协议的速度辣眼睛，原版协议还好，千兆上行，可以跑30m/s，7621的cpu。
chain_a能跑1m/s，aes128_sha1能跑5m/s
但因为我做校园网的，是需要单端口的，原版协议不支持混淆参数，只能用这个协议了，性能堪忧~

**Comment by vft9nesd** [comment]
是支持单端口的协议速度最快的只有aes128_sha1了，挺吃cpu的
