### ISSUE TITLE
胖虎大神。请问SSR控制面板里用户列表已开用户为什么无法删除？没有删除选项。和管理控制用户IP同时在线数量。单个IP用户不能让他分享使用、

### ISSUE THREAD

**Issue by shdijiouan** [ssrpanel/SSRPanel#1056]
胖虎大神。请问SSR控制面板里用户列表已开用户为什么无法删除？没有删除选项。和管理控制用户IP同时在线数量。单个IP用户不能让他分享使用、 限制客户的IP同时在线多个设备。

**Comment by vft9nesd** [comment]
user关联各种订单，优惠券等，删除要一并删掉相关的数据库信息，实现太复杂，也没什么必要，封禁即可，强迫症表示没办法。
 后端server配置中， "protocol_param": "#", // #号前面带上数字，则可以限制在线每个用户的最多在线设备数，仅限 auth_chain_a 协议下有效，例如： 3# 表示限制最多3个设备在线
