### ISSUE TITLE
建议 ipv4 地址可不填，可以直接解析域名

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#1058]
我的v2使用ws + cdn  填写地址时候被提示一定要填ipv4地址，但是不需要填写啊

**Comment by ssrpanel** [comment]
最好是填一下吧，因为一个节点必须有一个IPV4

**Comment by ssrpanel** [comment]
解析域名耗费php资源的，php里有一个叫gethostbyname，要是解析失败会卡很久

**Comment by vft9nesd** [comment]
服务器ip是ddns的，没法填怎么办~

**Comment by ssrpanel** [comment]
@vft9nesd 你都有钱买动态，没钱进群！！！坑。。动态我没玩过

**Comment by ssrpanel** [comment]
等我有钱买动态，玩过之后，我再改吧

**Comment by vft9nesd** [comment]
> @ vft9nesd你都有钱买动态，没钱进群!!!坑..动态我没玩过

动态的是电信的宽带。。嘤嘤嘤。。穷的要死啦
