### ISSUE TITLE
占用内存居高不下

### ISSUE THREAD

**Issue by ppllpig** [ssrpanel/ssrpanel#106]
1G的阿里云新加坡，今天全天占用内存800多，网速保持在1M/S以下，什么情况啊，ssr脚本的问题么，PYTHON进程占用700M内存了

**Comment by 1021435278** [comment]
这种问题就不要了拿出来提交isuse了, 浪费开发者精力.

**Comment by ZBrettonYe** [comment]
阿里云都这样

**Comment by ppllpig** [comment]
问题是没人在用内存也用这么多
https://ws1.sinaimg.cn/large/005HchDNgy1flig22oifej309i066glo.jpg
怎么重启PYTHON？

**Comment by ssrpanel** [comment]
@ppllpig 这。。。你先自己把aliyundun 干掉先

**Comment by ZBrettonYe** [comment]
@1021435278 reboot
