### ISSUE TITLE
报错“SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed:“

### ISSUE THREAD

**Issue by JadeVane** [ssrpanel/SSRPanel#1061]
原本用的挺好，然后更新了一下，发现网站打不开，显示
![image](https://user-images.githubusercontent.com/34258753/48118445-3e73ea80-e2a7-11e8-95b8-02a4fd6af099.png)
找来找去实在找不到问题所在，就直接删掉重装了，但是还是有问题
```
php composer.phar install
```
报错
![image](https://user-images.githubusercontent.com/34258753/48118281-cd343780-e2a6-11e8-8fac-b0d93ef1d439.png)
接着运行
```
php artisan key:generate
```
报错
![image](https://user-images.githubusercontent.com/34258753/48118298-da512680-e2a6-11e8-91f6-4e9335c9f2bb.png)
这是什么问题？

**Comment by JadeVane** [comment]
这是`.env`中数据库的配置：
```
DB_CONNECTION=mysql
DB_HOST=unix:/var/lib/mysql/mysql.sock
DB_PORT=3306
DB_DATABASE=ssrpanel
DB_USERNAME=ssrpanel
DB_PASSWORD=ssrpanel
DB_STRICT=false
```

**Comment by niyeyeqi** [comment]
应该是你数据库出现啥问题了

**Comment by SRCOL** [comment]
更新数据导入了没？

**Comment by JadeVane** [comment]
@niyeyeqi @SRCOL 确实知道是数据库的问题，所以才特地贴出来，数据库已经导入，而且应该是使用了socket方式连接出现问题，现在就是不知道问题怎么解决

**Comment by JadeVane** [comment]
这是目前`.env`的数据库配置：
```
DB_CONNECTION=mysql
DB_SOCKET=/var/lib/mysql/mysql.sock
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=ssrpanel
DB_USERNAME=ssrpanel
DB_PASSWORD=ssrpanel
DB_STRICT=false
```
在`config/database.php`中也加入了下面一行：
```
'unix_socket' => env('DB_SOCKET', '/var/lib/mysql/mysql.sock'),
```

**Comment by JadeVane** [comment]
@ssrpanel 确实是php的问题，改了一下连接mysql的路径就解决了，然后又冒出这个问题：
![image](https://user-images.githubusercontent.com/34258753/48298505-7bcfb680-e4f9-11e8-97c6-2111e9234d2d.png)
登陆总是提示密码错误，点击注册就跳出上面这个

**Comment by JadeVane** [comment]
解决了，thx
![image](https://user-images.githubusercontent.com/34258753/48298802-83458e80-e4fe-11e8-9a68-6d284753b469.png)

**Comment by cmmdwl** [comment]
看来我的教程还是有帮助的嘛

**Comment by JadeVane** [comment]
已解决，不是MySQL的socket连接问题，直接把数据库删掉，重建一个空的数据库再导入原先的数据表即可，不过还是不知道问题在哪

**Comment by ssrpanel** [comment]
@JadeVane 再次重申，每次更新完代码，看到sql/update这个目录下有sql更新，只要不是db.sql 而是带日期的，比如 20190202.sql这种，都要按时间顺序从小到大导入到数据库

**Comment by ntgeralt** [comment]
> @JadeVane 再次重申，每次更新完代码，看到sql/update这个目录下有sql更新，只要不是db.sql 而是带日期的，比如 20190202.sql这种，都要按时间顺序从小到大导入到数据库

我建议这个放wiki好，遇到这个坑搜索了半个多小时才解决...
