### ISSUE TITLE
手机端单端口报错：unexpected end of stream on connection{127.0.0.1:1082,proxy=DIRET

### ISSUE THREAD

**Issue by acdiost** [ssrpanel/SSRPanel#1063]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
你好，我已经翻完了！
在https://github.com/shadowsocksr-backup/shadowsocksr-android/issues/33  该连接下也未找到答案。
在不启用单端口的情况下是可以正常连接的。配置了单端口就会在测试连接的时候报这个错误！
配置复制的您的Wiki里的：
"additional_ports" : {
    "80": {
        "passwd": "pass",
        "method": "aes-256-cfb",
        "protocol": "auth_aes128_md5",
        "protocol_param": "",
        "obfs": "tls1.2_ticket_auth_compatible",
        "obfs_param": ""
    }
    }, // only works under multi-user mode

前端单端口也是相应的设置选择！修改成了80以及其他端口都无法在安卓（8.0）手机端（ssr3.4.0.8）运行

**Comment by ssrpanel** [comment]
你的配置信息是不是从面板里抄的？要从wiki里抄。。。。面板里有坑的

https://github.com/ssrpanel/SSRPanel/wiki/%E5%8D%95%E7%AB%AF%E5%8F%A3%E5%A4%9A%E7%94%A8%E6%88%B7%E7%9A%84%E5%9D%91

**Comment by acdiost** [comment]
你好，是按您的提示没有复制面板里内容呢！是从Wiki里的复制的。
以下是内容截图，还请过目。麻烦你了！谢谢。
![1user-config](https://user-images.githubusercontent.com/38416288/48260278-d8799580-e455-11e8-90df-68a0d74da725.png)
![2user-json 2](https://user-images.githubusercontent.com/38416288/48260284-dca5b300-e455-11e8-88f6-f0b707c294d2.png)
![3](https://user-images.githubusercontent.com/38416288/48260286-dfa0a380-e455-11e8-8ada-dfb86c9028a0.png)
![4](https://user-images.githubusercontent.com/38416288/48260289-e29b9400-e455-11e8-8017-0dfd5b920f8c.png)

**Comment by ssrpanel** [comment]
大哥，注释要去掉！！！！ 复制不要复制注释！！！

**Comment by ssrpanel** [comment]
json不支持注释的！！！那个注释是我打给你们看的

**Comment by acdiost** [comment]
感谢！我去试试。

**Comment by acdiost** [comment]
![default](https://user-images.githubusercontent.com/38416288/48314952-b1fd5b00-e60b-11e8-9cce-f215b447525f.PNG)
![1json](https://user-images.githubusercontent.com/38416288/48314953-b1fd5b00-e60b-11e8-9b43-e42d8e9aac80.PNG)
之前傻逼了。没有想起json无注释的！抱歉
按照您的提示，删除了所有注释。依然不行，又修改了几种协议、混淆还是不行。

**Comment by acdiost** [comment]
去掉单端口就又可以连接了

**Comment by acdiost** [comment]
你好 胖虎，添加有赞云支付时，进行在线支付报错：创建订单失败mkdir():permission  denied;

![image](https://user-images.githubusercontent.com/38416288/48353193-c738bf00-e6c9-11e8-97c1-fa226413b0b3.png)

后台日志：
![image](https://user-images.githubusercontent.com/38416288/48353233-e0da0680-e6c9-11e8-8c42-c90df77da4b8.png)
这个forge的用户是哪里来的呢？

还有一点，请问一下邮件的发送pop的设置功能有吗？我只找到一个营销管理中的群发，提示开发中！

**Comment by ntgeralt** [comment]
单端口是可以用的，建议你去找干净的模板，别删注释了

**Comment by acdiost** [comment]
> 单端口是可以用的，建议你去找干净的模板，别删注释了

感谢您的回复！
我是用的这个链接：git clone https://github.com/ssrpanel/ssrpanel.git安装的面板。
后端是git clone https://github.com/ssrpanel/shadowsocksr.git
反复重装了几次都没行！已经放弃了，现用的ss-panel-v3-mod_Uim还是很稳的。
对了，服务器是centos7.4的。不知道跟系统有关系没有。
