### ISSUE TITLE
防盗刷流量

### ISSUE THREAD

**Issue by bickernwong** [ssrpanel/SSRPanel#1064]
可不可以设置只有收费账号才能生成邀请码以防用户盗流量，取之不尽，用之不竭

**Comment by bickernwong** [comment]
当可用流量少于2G或者代理状态为禁用时，禁止使用生成邀请码功能。

**Comment by ssrpanel** [comment]
marked

**Comment by vft9nesd** [comment]
有道理~上次我好像因此翻车的，被疯狂注册

**Comment by ssrpanel** [comment]
marked

**Comment by ssrpanel** [comment]
需求鸡肋，放弃
邀请码可以选择只给用户生成1-3个，每个用户注册只送500M之类的，如果你碰上较真的用户，非得浪费时间注册10个邮箱互相邀请，就给他们吧
