### ISSUE TITLE
标签不显示或者显示不全，原因是left join时group id覆盖掉了node id

### ISSUE THREAD

**Issue by aiyahacke** [ssrpanel/SSRPanel#1065]
标签不显示或者显示不全，原因是left join时group id覆盖掉了node id

解决办法：
/www/wwwroot/ssrpanel/app/Http/Controllers/UserController.php

93行 DB::table('ss_node') 后面添加 ->selectRaw('ss_node.*')
182行 $node->node_id 修改为 $node->id

**Comment by aiyahacke** [comment]
还有，节点排序建议加入次要排序，这样在节点设置sort相同时刷新列表不会乱跳

/www/wwwroot/ssrpanel/app/Http/Controllers/UserController.php

98行 ->orderBy('sort', 'desc') 后添加 ->orderBy('ss_node.id', 'asc')

**Comment by aiyahacke** [comment]
额，不小心close了

**Comment by aiyahacke** [comment]
额，不小心close了

**Comment by ZBrettonYe** [comment]
nice,我都快忘了，这个BUG

**Comment by ssrpanel** [comment]
靠，我以为你提PR了。。

**Comment by ssrpanel** [comment]
我明天该一下吧。

**Comment by ssrpanel** [comment]
已修复
