### ISSUE TITLE
建议 留一个接口给服务器更新ip上报

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#1066]
搞到了一台动态ip的服务器，如果每一次换ip后服务器都能自己修改自己的节点信息就好了

**Comment by ssrpanel** [comment]
什么样的需求，我这两天在群里不是问 动态怎么玩吗。。求aff ，我买个玩看看，我得自己过一遍流程，才知道怎么做

**Comment by vft9nesd** [comment]
用cloudxns就好啦，秒解析。[脚本点这里](https://github.com/lixuy/CloudXNS-DDNS-with-BashShell/blob/master/cloudxns_ddns.sh)

**Comment by cmmdwl** [comment]
@vft9nesd 有cfcdn的么。感觉还是cf的比较好用

**Comment by vft9nesd** [comment]
@cmmdwl 有 我给你找找 不过实测那个解析挺慢的。 如果要用它的cdn，最近墙的原因比较复杂，很多都被阻断了

**Comment by vft9nesd** [comment]
https://opt.cn2qq.com/opt-script/script/Sh44_cloudflare.sh

**Comment by vft9nesd** [comment]
padavan抠出来的脚本，改掉nvram对应自己的email api即可

**Comment by vft9nesd** [comment]
https://github.com/joshuaavalon/SynologyCloudflareDDNS/blob/master/cloudflareddns.sh

**Comment by DanielZhang17** [comment]
我用cloudflare的DNS配合API没出过问题
