### ISSUE TITLE
数据库ssl

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#1067]
观察了一下，面板与数据库的链接似乎没有加密？
这不就等于裸奔了么？
建议预留一个加密
防止面板 节点 数据库分离导致明文密码被采集

**Comment by ssrpanel** [comment]
采集？？为何有这种担心？？

**Comment by cmmdwl** [comment]
数据库与面板如果没有加密是明文通信的，节点也是，如果加密下就更好了
