### ISSUE TITLE
ui建议 用户界面公告

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#1068]
就一个展开两字的开关在那贼奇怪不是吗？
写几个字都比啥也没有好啊
建议坐成（感谢使用…）这样，好看还能让人知道有没有换公告
也顺便建议下公告在用户没看过之前和更新公告好是默认展开的，当用户看过后，在记录一下然后收起来

**Comment by 329928** [comment]
觉得可以在“公告”后面加更新时间，不过文章好像只有发布时间...

**Comment by mlgexyz** [comment]
我自己现在改的是这样子，公告默认展开，软件下载默认收拢
![default](https://user-images.githubusercontent.com/21287731/48687501-afe35f80-ebfc-11e8-8fbf-79240de0e818.png)
![default](https://user-images.githubusercontent.com/21287731/48687532-ce495b00-ebfc-11e8-82d6-33b08548c791.png)

**Comment by ssrpanel** [comment]
还是的自己有动手能力比较好。
