### ISSUE TITLE
新手求助，节点可用，定时任务可用，但是一直显示宕机

### ISSUE THREAD

**Issue by aoerboquartz** [ssrpanel/SSRPanel#1069]
![image](https://user-images.githubusercontent.com/17606183/48311487-76e33380-e5db-11e8-9533-a3c954e5ae96.png)

这是日志

**Comment by aoerboquartz** [comment]
使用了两台服务器，一台服务器(centos 7)放置面板和数据库，另外一个机器(centos 6)放置节点，都已经做了校时

**Comment by aoerboquartz** [comment]
节点服务器 运行 python server.py 报
IPv6 support
Traceback (most recent call last):
  File "server.py", line 25, in <module>
    import db_transfer
  File "/root/shadowsocksr/db_transfer.py", line 13, in <module>
    from database import *
  File "/root/shadowsocksr/database/__init__.py", line 9, in <module>
    from peewee import *
ImportError: No module named peewee
请问是和这个有关系么？

**Comment by aoerboquartz** [comment]
节点 服务器 执行 pip install cymysql==0.9.4
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Requirement already satisfied: cymysql==0.9.4 in /usr/lib/python2.6/site-packages
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by aoerboquartz** [comment]
然后执行 python server.py
还是老样子

**Comment by ssrpanel** [comment]
ssr如果你不会装，就用最后一个released版

**Comment by aoerboquartz** [comment]
可是SSR 好使呀
