### ISSUE TITLE
胖虎，啥时候能增加限制设备数啊~~

### ISSUE THREAD

**Issue by ppllpig** [ssrpanel/ssrpanel#107]
即使有流量限制，无限分享也很容易被墙啊~~~

**Comment by ssrpanel** [comment]
这个我得再看看。。我已经咨询ssrr作者了，能不能在ssrr后端里加上这个功能，而不是通过第三方去限制

**Comment by 1021435278** [comment]
顺便让ssrr作者更新以下功能:

1. 增加内置的二维码扫描功能(而不是提示下载)
2. 增加可以删除节点功能. @ssrpanel
