### ISSUE TITLE
建议 服务器负载达到%80时，不提供订阅

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#1070]
这样应该可以轻微解决服务器被订阅爆掉的问题吧

**Comment by ssrpanel** [comment]
你的服务器太辣鸡了。。。至少得1G内存 的KVM 
如果面板+数据库在同一台机器上（没有再挂其他website），建议你上2G内存的KVM，又不贵，因为如果你的面板访问量大，php进程要吃资源，还有，CPU太辣鸡性能也不行。反正，这个东西不需要做，因为堆机器性能即可。

**Comment by ssrpanel** [comment]
建议你先看一下服务器为什么负载会过高，是因为php引起还是数据库，还是什么的
top一下，看一下cpu 内存 io

**Comment by cmmdwl** [comment]
呀，我的意思跟你想的不一样了@ssrpanel 我之的是节点。。。
