### ISSUE TITLE
免id一键安装shadowrocket

### ISSUE THREAD

**Issue by vft9nesd** [ssrpanel/SSRPanel#1071]
我不太确定是否真的可以免id，因为我的手机装过小火箭。
这是我抓的一个ipa包，在两个手机上测试都不需要id登录即可打开
ipa我放上来，谁有没装过小火箭的手机，帮测试一下
[一键安装方法参考这里](https://github.com/ssrpanel/SSRPanel/wiki/iOS%E5%85%8D%E5%88%87%E6%8D%A2%E8%B4%A6%E5%8F%B7%E5%9C%A8%E7%BA%BF%E5%AE%89%E8%A3%85Shadowrocket)
ipa包地址http://waaaa.test.upcdn.net/Shadowrocket.ipa

**Comment by vft9nesd** [comment]
这是旧版本的。2.1.10

**Comment by vft9nesd** [comment]
safair[点这里](http://itms-services://?action=download-manifest&url=http://waaaa.test.upcdn.net/ipa.plist)安装试试

**Comment by ssrpanel** [comment]
那是你手机不需要id而已，其他人还是要的，我们群里都交流过的。
