### ISSUE TITLE
v2ray后端运行时报错

### ISSUE THREAD

**Issue by Supeapple** [ssrpanel/SSRPanel#1073]
2018/11/13 16:41:11 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 获取用户流量失败
io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
想想请教下出现这个问题是什么原因导致的。

**Comment by vft9nesd** [comment]
2018/11/13 20:11:28 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason  
2018/11/13 20:11:28 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason  
2018/11/13 20:11:28 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason  
2018/11/13 20:11:28 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason  
2018/11/13 20:11:28 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeExcept

我是这个问题，顺便请教。。。

**Comment by 329928** [comment]
同上，昨天也是这个问题，centos7。5

**Comment by juzixs** [comment]
> 2018/11/13 20:11:28 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
> 2018/11/13 20:11:28 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
> 2018/11/13 20:11:28 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
> 2018/11/13 20:11:28 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
> 2018/11/13 20:11:28 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeExcept
> 
> 我是这个问题，顺便请教。。。

可能是ssrpanel老用户没有uuid
在ssrpanel目录下 执行：php artisan upgradeUserVmess ，会给没有生成过vmess_id的用户生成一个vmess_id

**Comment by 329928** [comment]
> > 2018/11/13 20:11:28 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
> > 2018/11/13 20:11:28 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
> > 2018/11/13 20:11:28 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
> > 2018/11/13 20:11:28 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
> > 2018/11/13 20:11:28 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeExcept
> > 我是这个问题，顺便请教。。。
> 
> 可能是ssrpanel老用户没有uuid
> 在ssrpanel目录下 执行：php artisan upgradeUserVmess ，会给没有生成过vmess_id的用户生成一个vmess_id

我是这个问题，老用户都有UUID，其他V2服务器没问题，

**Comment by 329928** [comment]
我的问题解决了，config.pxxxxx里面1.1.1.1改成127.0.0.1
不知道你是不是一样的问题，大佬已经进行更新了
