### ISSUE TITLE
有赞云支付无法使用

### ISSUE THREAD

**Issue by 13221253358** [ssrpanel/SSRPanel#1074]

**Comment by lybc** [comment]
我也有这个问题，配置成功了，购买服务时点在线支付返回页面不存在

![image](https://user-images.githubusercontent.com/9601872/48468820-f06f6180-e827-11e8-8e2d-b74b98e95899.png)

![image](https://user-images.githubusercontent.com/9601872/48468868-1137b700-e828-11e8-97f1-af87192f83d7.png)

![image](https://user-images.githubusercontent.com/9601872/48468898-29a7d180-e828-11e8-9e07-34afda76ea55.png)
