### ISSUE TITLE
/api/yzy返回HTTP 500错误

### ISSUE THREAD

**Issue by mlgexyz** [ssrpanel/SSRPanel#1078]
/storage/logs目录下的日志没有任何记录，500错误的情况和访问不存在的链接情况一样，调试不出来原因，似乎是页面不存在返回？

**Comment by mlgexyz** [comment]
把/app/Http/Controllers/Api/YzyController.php中的所有Log::info屏蔽了就行了，很奇怪的bug，希望开发者找到真正的原因并修复，tks

**Comment by mlch911** [comment]
我也是这个问题，困惑了好久，十分感谢！
