### ISSUE TITLE
Namesilo 功能就没有用

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/SSRPanel#1079]
在Namesilo买了域名，设置了api；

然后在节点添加里用了xxxx.xx.域名.xx 和 ipv4 ip；

过了20几分钟了，去namesilo后台看，什么都没变化；

**Comment by ZBrettonYe** [comment]
国际服 死个屁

国内服 不用备案也能用

**Comment by qq1403575689** [comment]
有私下联系方式吗。胖虎

**Comment by qq1403575689** [comment]
@ssrpanel

**Comment by Losgif** [comment]
本地改用1.1.1.1 8.8.8.8 dns服务器 几乎秒生效

**Comment by 1021435278** [comment]
> 
> 
> CF会解析到被墙IP上的
> 
> 那还不如试试阿里云的api

CF可以直接调API,更方便, 现在机场都套CF,很少套阿里云的, 阿里云多少还有黑洞, CF 随便D.

**Comment by 1021435278** [comment]
> 
> 
> 本地改用1.1.1.1 8.8.8.8 dns服务器 几乎秒生效

以前vultr可以修改/etc/resolv.conf改为自定义,最近好像修改后也无法生效,我还没发工单问过究竟怎么回事.

**Comment by Kris-ping** [comment]
> CF会解析到被墙IP上的
> 
> 那还不如试试阿里云的api

你可以安装个wordpress然后装个cloudflare插件,看看这个插件怎么调用cf,就可以很快应用到ssrpanel上了.

**Comment by vft9nesd** [comment]
cloudflare有个骚操作，把域名解析到1.1.1.1或者1.0.0.1上，具体百度

其实强烈推荐cloudxns虽需实名认证，但秒解析，自带监控，用了几年了，不喝茶

**Comment by vft9nesd** [comment]
CF秒生效针对的是8.8.8.8之类的DNS，但是国内DNS解析很慢，可又有几个人爱用谷歌dns呢，延迟高，又有几个小白懂得改呢。。。
之前用过一段时间cloudflare，生效之后基本稳定，但偶尔掉解析，ping域名查不到ip，必须换谷歌dns才可以

**Comment by qq1403575689** [comment]
有商业版吗 @ssrpanel

**Comment by ssrpanel** [comment]
@qq1403575689 要嘛你连wiki都不看，要嘛你你不舍得掏199
