### ISSUE TITLE
在线支付后，前台一直在报 支付成功，后台日志一直在报错

### ISSUE THREAD

**Issue by cdlaimin** [ssrpanel/SSRPanel#1080]
ErrorException: Empty row packet body 
和
ErrorException: Empty row packet body 
但是报的并不多 而且 加流量会重复 同一个订单成功后重复加了四次

**Comment by ssrpanel** [comment]
截图。你这么反馈问题，我都想直接关闭了

**Comment by cdlaimin** [comment]
@ssrpanel sorry 还不会上传截图 我已经找到问题所在了... 应该是我用了异地数据库的原因 数据库在上海 网站在东京 现在我把数据库重新加到东京 测试了下 没问题了............

**Comment by ssrpanel** [comment]
ctrl +c ， ctrl +v
