### ISSUE TITLE
哪位兄弟能建立个翻墙专用DNS, 然后把一些敏感网站慢慢提交加到数据库中? 避免政治事件喝茶?

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/SSRPanel#1081]
哪位兄弟能建立个翻墙专用DNS, 然后把一些敏感网站慢慢提交加到数据库中? 避免政治事件喝茶?

**Comment by cmmdwl** [comment]
linux的ip ban工具啊，话说我可以维护一个

**Comment by aoerboquartz** [comment]
想法不错嘛。

**Comment by DanielZhang17** [comment]
DNS 可以搞，不过政治事件很难避免，YouTube和Facebook上政治敏感的东西还是挺多的，DNS在这个上并没有什么用，一些专门搞事情的域名倒是可以拦截

**Comment by ssrpanel** [comment]
我想不明白，你们想干啥？

**Comment by ssrpanel** [comment]
你们这么搞，就越来越商业化了，太过于商业化，会被六扇门干的

**Comment by 1021435278** [comment]
> 
> 
> 我想不明白，你们想干啥？

建立干净的翻墙生态,避免殃及池鱼,这很简单. 
DNS/客户端.

**Comment by ssrpanel** [comment]
目前除了改ssr后端我不知道还有什么办法

**Comment by adhll** [comment]
其实要是面板加一个像魔改V3一样的审计功能就好了，DNS我觉得还是可以跳过的，意义不大

**Comment by vft9nesd** [comment]
后端host强制解析敏感地址到爱国网，维护一个host库就ok
