### ISSUE TITLE
建议订阅中添加v2ray节点而不是排除

### ISSUE THREAD

**Issue by alienxcn** [ssrpanel/SSRPanel#1082]
文件：/ssrpanel/app/Http/Controllers

// 生成v2ray scheme
              $v2ray_array = array("v" => "2", "ps" => $node['name'], "add" => $node['server'], "port" => $node['v2_port'], "id" => $user->vmess_id, "aid" => $node['v2_alter_id'], "net" => $node['v2_net'], "type" => $node['v2_type'], "host" => "", "path" => "", "tls" => "");
              $scheme .= 'vmess://' . base64url_encode(json_encode($v2ray_array)) . "\n";

**Comment by alienxcn** [comment]
应该是/ssrpanel/app/Http/Controllers/SubscribeController.php

**Comment by ssrpanel** [comment]
要独立出一个

**Comment by ssrpanel** [comment]
客户端支持ss 和 vmess混合订阅吗？

**Comment by alienxcn** [comment]
在iOS的shadowrocket上测试是OK的，直接将vmess的信息拼接到ssr的信息。（$scheme变量）

**Comment by ssrpanel** [comment]
> 在iOS的shadowrocket上测试是OK的，直接将vmess的信息拼接到ssr的信息。（$scheme变量）

目前已经混合了，但是这个坑会坑死所有非ios客户端的。
