### ISSUE TITLE
有赞这个操作是手续费翻倍了吧？

### ISSUE THREAD

**Issue by vft9nesd** [ssrpanel/SSRPanel#1088]
![image](https://user-images.githubusercontent.com/24932999/48895181-72423900-ee7f-11e8-8632-3530337b6339.png)

**Comment by ssrpanel** [comment]
我们早就知道了。

**Comment by vft9nesd** [comment]
我发现12月的订单，都没收手续费？

> 我们早就知道了。

**Comment by vft9nesd** [comment]
身份证的事，也没有要求啊，要求的话，不是还有几千套手持吗~
