### ISSUE TITLE
强制更新后出错 求大老板帮忙

### ISSUE THREAD

**Issue by banxianl08** [ssrpanel/SSRPanel#1089]
网页显示
![qq 20181123194619](https://user-images.githubusercontent.com/41246205/48941945-78581880-ef58-11e8-809e-ddb00a062c4c.png)

**Comment by banxianl08** [comment]
[root@tw ssrpanel]#  sh update.sh  
Fetching origin
HEAD is now at 24d0548 不允许用户自行更换加密方式、协议、混淆
Already up-to-date.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating optimized autoload files
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Context" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Context.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Context.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Description" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Description.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Description.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Location" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Location.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Location.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Serializer" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Serializer.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Serializer.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Tag" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Tag.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Tag.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Tag\AuthorTag" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Tag/AuthorTag.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Tag/AuthorTag.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Tag\CoversTag" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Tag/CoversTag.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Tag/CoversTag.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Tag\DeprecatedTag" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Tag/DeprecatedTag.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Tag/DeprecatedTag.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Tag\ExampleTag" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Tag/ExampleTag.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Tag/ExampleTag.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Tag\LinkTag" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Tag/LinkTag.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Tag/LinkTag.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Tag\MethodTag" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Tag/MethodTag.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Tag/MethodTag.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Tag\ParamTag" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Tag/ParamTag.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Tag/ParamTag.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Tag\PropertyReadTag" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Tag/PropertyReadTag.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Tag/PropertyReadTag.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Tag\PropertyTag" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Tag/PropertyTag.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Tag/PropertyTag.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Tag\PropertyWriteTag" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Tag/PropertyWriteTag.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Tag/PropertyWriteTag.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Tag\ReturnTag" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Tag/ReturnTag.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Tag/ReturnTag.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Tag\SeeTag" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Tag/SeeTag.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Tag/SeeTag.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Tag\SinceTag" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Tag/SinceTag.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Tag/SinceTag.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Tag\SourceTag" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Tag/SourceTag.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Tag/SourceTag.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Tag\ThrowsTag" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Tag/ThrowsTag.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Tag/ThrowsTag.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Tag\UsesTag" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Tag/UsesTag.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Tag/UsesTag.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Tag\VarTag" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Tag/VarTag.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Tag/VarTag.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Tag\VersionTag" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Tag/VersionTag.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Tag/VersionTag.php", the first will be used.
Warning: Ambiguous class resolution, "Barryvdh\Reflection\DocBlock\Type\Collection" was found in both "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection/DocBlock/Type/Collection.php" and "/www/wwwroot/ssrpanel/vendor/barryvdh/reflection-docblock/src/src/Barryvdh/Reflection/DocBlock/Type/Collection.php", the first will be used.
> Illuminate\Foundation\ComposerScripts::postInstall
PHP Warning:  Uncaught ErrorException: require(/www/wwwroot/ssrpanel/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php:66
Stack trace:
#0 /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php(66): Composer\Util\ErrorHandler::handle(2, 'require(/www/ww...', '/www/wwwroot/ss...', 66, Array)
#1 /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php(66): require()
#2 /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php(56): composerRequireacc0b0680f316a35c005c9298898a42e('667aeda72477189...', '/www/wwwroot/ss...')
#3 /www/wwwroot/ssrpanel/vendor/autoload.php(7): ComposerAutoloaderInitacc0b0680f316a35c005c9298898a42e::getLoader()
#4 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(17): require_once('/www/wwwroot/ss...')
#5 phar:///www/wwwroot/ssrpanel/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(292): Illuminate\Foundation\ComposerScrip in /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php on line 66

Warning: Uncaught ErrorException: require(/www/wwwroot/ssrpanel/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php:66
Stack trace:
#0 /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php(66): Composer\Util\ErrorHandler::handle(2, 'require(/www/ww...', '/www/wwwroot/ss...', 66, Array)
#1 /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php(66): require()
#2 /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php(56): composerRequireacc0b0680f316a35c005c9298898a42e('667aeda72477189...', '/www/wwwroot/ss...')
#3 /www/wwwroot/ssrpanel/vendor/autoload.php(7): ComposerAutoloaderInitacc0b0680f316a35c005c9298898a42e::getLoader()
#4 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(17): require_once('/www/wwwroot/ss...')
#5 phar:///www/wwwroot/ssrpanel/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(292): Illuminate\Foundation\ComposerScrip in /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  composerRequireacc0b0680f316a35c005c9298898a42e(): Failed opening required '/www/wwwroot/ssrpanel/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php' (include_path='.:/www/server/php/72/lib/php') in /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php on line 66

Fatal error: composerRequireacc0b0680f316a35c005c9298898a42e(): Failed opening required '/www/wwwroot/ssrpanel/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php' (include_path='.:/www/server/php/72/lib/php') in /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php on line 66
PHP Warning:  require(/www/wwwroot/ssrpanel/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php on line 66

Warning: require(/www/wwwroot/ssrpanel/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/www/wwwroot/ssrpanel/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php' (include_path='.:/www/server/php/72/lib/php') in /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/www/wwwroot/ssrpanel/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php' (include_path='.:/www/server/php/72/lib/php') in /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php on line 66
PHP Warning:  require(/www/wwwroot/ssrpanel/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php on line 66

Warning: require(/www/wwwroot/ssrpanel/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/www/wwwroot/ssrpanel/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php' (include_path='.:/www/server/php/72/lib/php') in /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/www/wwwroot/ssrpanel/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php' (include_path='.:/www/server/php/72/lib/php') in /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php on line 66
PHP Warning:  require(/www/wwwroot/ssrpanel/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php on line 66

Warning: require(/www/wwwroot/ssrpanel/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/www/wwwroot/ssrpanel/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php' (include_path='.:/www/server/php/72/lib/php') in /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/www/wwwroot/ssrpanel/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php' (include_path='.:/www/server/php/72/lib/php') in /www/wwwroot/ssrpanel/vendor/composer/autoload_real.php on line 66

**Comment by banxianl08** [comment]
求大佬解决啊， 运行半年了

**Comment by Supsfun** [comment]
> 求大佬解决啊，运行半年了

留tg

**Comment by banxianl08** [comment]
> > 求大佬解决啊，运行半年了
> 
> 留TG

banxianll

**Comment by ssrpanel** [comment]
php artisan view:clear
php artisan cache:clear
php composer.phar update
php composer.phar install
