### ISSUE TITLE
合并请求

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/ssrpanel#109]
对 作者 的code进行一些小细节修改

1.修改邮箱中ssrpanel 的显示 改为 用户设置的完整名；
2.修改用户界面中[ 服务套餐 ]为[ 购买服务]；
3.修改返利金额 由元 到 分；
4.修改管理界面中用户管理 付费分类 中添加 免费；

第3条改了数据库，没有更新添加对应的更新代码

**Comment by ssrpanel** [comment]
@ZBrettonYe 这个我看了，还是不合并的好，我按你的需求加功能便是。。因为还好有多地方要改。
尤其是金额问题，涉及换算。

**Comment by ssrpanel** [comment]
2.4.已改。。。1.我加个配置。。。3还得看看

**Comment by ssrpanel** [comment]
等待代码更新
