### ISSUE TITLE
建议改改ui

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#1099]
<img width="1043" alt="_20181128222012" src="https://user-images.githubusercontent.com/21263352/49159418-74186a80-f35f-11e8-94eb-1f4f2311bfc5.png">

**Comment by cmmdwl** [comment]
我自己做的比较烂，有哪位能根据页面样子做一个？
😂

**Comment by vft9nesd** [comment]
太丑了。。。

**Comment by hsulzz** [comment]
自己改啊 css这个不是很简单么-v-

**Comment by ssrpanel** [comment]
已分离，等待提交代码
