### ISSUE TITLE
验证邮件问题 - BUG

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#110]
# @ssrpanel 

如果验证邮件在规定时间内未阅读,那么再点击邮件里面确认连接的话, 会跳到控制中心出错页面, 可否改为404甚至空白页,见附图.

![a](https://user-images.githubusercontent.com/32491066/32874527-c767a02c-cacd-11e7-830a-d9ff063c7b2b.png)
![b](https://user-images.githubusercontent.com/32491066/32874528-c7c8c596-cacd-11e7-817a-797b759f08d3.png)

**Comment by ssrpanel** [comment]
已修复了

**Comment by ssrpanel** [comment]
等待更新代码
