### ISSUE TITLE
请大佬帮忙看看。

### ISSUE THREAD

**Issue by jiangjiang5733** [ssrpanel/SSRPanel#1102]
大佬你好，这两天突然出现的网站卡死（502）情况，vps重启之后恢复正常，但是过段时间又出现卡死情况，还请大佬有时间帮忙看看，感谢！
系统环境centos7，ssrpanel版本8.20，进入宝塔面板得知是cpu占用过高，在vps中运行top命令发现sql占用极高（80%以上）。
ssrpanel面板中系统运行日志中的-执行定时任务【自动化任务】，耗时649.2185秒。有的甚至上千秒（在网站卡死的情况下出现）
ssrpanel运行日志报错如下（）：

[2018-11-30 02:55:11] local.ERROR: PDOException: SQLSTATE[HY000] [2002] Connection refused in /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:68
Stack trace:
#0 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(68): PDO->__construct('mysql:host=127....', 'ssrpanel', 'fNcPAL3FG4zKWaY...', Array)
#1 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(44): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=127....', 'ssrpanel', 'fNcPAL3FG4zKWaY...', Array)
#2 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=127....', Array, Array)
#3 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(183): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#5 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(883): call_user_func(Object(Closure))
#6 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(248): Illuminate\Database\Connection->getPdo()
#7 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(234): Illuminate\Database\DatabaseManager->refreshPdoConnections('mysql')
#8 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(168): Illuminate\Database\DatabaseManager->reconnect('mysql')
#9 [internal function]: Illuminate\Database\DatabaseManager->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection))
#10 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(736): call_user_func(Object(Closure), Object(Illuminate\Database\MySqlConnection))
#11 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(718): Illuminate\Database\Connection->reconnect()
#12 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(700): Illuminate\Database\Connection->tryAgainIfCausedByLostConnection(Object(Illuminate\Database\QueryException), 'select count(di...', Array, Object(Closure))
#13 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(610): Illuminate\Database\Connection->handleQueryException(Object(Illuminate\Database\QueryException), 'select count(di...', Array, Object(Closure))
#14 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Illuminate\Database\Connection->run('select count(di...', Array, Object(Closure))
#15 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1705): Illuminate\Database\Connection->select('select count(di...', Array, true)
#16 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1690): Illuminate\Database\Query\Builder->runSelect()
#17 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2025): Illuminate\Database\Query\Builder->get(Array)
#18 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1953): Illuminate\Database\Query\Builder->aggregate('count', Array)
#19 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1251): Illuminate\Database\Query\Builder->count('request_ip')
#20 /www/wwwroot/xxx.com/ssrpanel/app/Console/Commands/AutoJob.php(100): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#21 /www/wwwroot/xxx.com/ssrpanel/app/Console/Commands/AutoJob.php(47): App\Console\Commands\AutoJob->blockSubscribe()
#22 [internal function]: App\Console\Commands\AutoJob->handle()
#23 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#24 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#25 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#26 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#27 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#28 /www/wwwroot/xxx.com/ssrpanel/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#29 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#30 /www/wwwroot/xxx.com/ssrpanel/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /www/wwwroot/xxx.com/ssrpanel/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\AutoJob), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /www/wwwroot/xxx.com/ssrpanel/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /www/wwwroot/xxx.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /www/wwwroot/xxx.com/ssrpanel/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 {main}

**Comment by ssrpanel** [comment]
打开日志自动清除功能，因为你的日志太多了（可能几百万甚至上千万条了），关联查询的时候卡主了

**Comment by jiangjiang5733** [comment]
> 打开日志自动清除功能，因为你的日志太多了（可能几百万甚至上千万条了），关联查询的时候卡主了
胖虎大佬你好，日志自动清除功能是一直都开启的，（log能查询近一个月的日志）。后面按照你的提示，手动把log全部删除了，但是依然执行自动化任务会长达600+秒
