### ISSUE TITLE
设置smtp邮件出错

### ISSUE THREAD

**Issue by Pinkpiglet** [ssrpanel/SSRPanel#1103]
Fatal error: Uncaught Error: Class 'Log' not found in /www/wwwroot/xxx/ssrpanel/app/Exceptions/Handler.php:51 Stack trace: #0 /www/wwwroot/xxx/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(326): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalThrowableError)) #1 /www/wwwroot/xxx/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(124): Illuminate\Foundation\Http\Kernel->renderException(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalThrowableError)) #2 /www/wwwroot/xxx/ssrpanel/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request)) #3 {main} thrown in /www/wwwroot/xxx/ssrpanel/app/Exceptions/Handler.php on line 51

**Comment by ssrpanel** [comment]
日志贴的不够全。
