### ISSUE TITLE
流量比例设置问题 - 概念问题

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#111]
@ssrpanel 

不明白这个流量比例是什么意思, 如果设置为1的话, 稍微几个用户就很快用不了,只能临时把数字搞得特别大.

具体这个在多节点/用户下如何设置,可否指点讲解下?

![a1](https://user-images.githubusercontent.com/32491066/32874641-7e76eafc-cace-11e7-968a-a57b998fecf3.png)

**Comment by ssrpanel** [comment]
上面不是写说明了吗？这个需要配置你SSR后端的那个node_rate 字段，貌似是在 user-config.json下面，面板那个是用来显示给用户看的

**Comment by 1021435278** [comment]
@ @ssrpanel 

解释还是不明白啊.   可否把ssr后端的git告知? 我去研究下.
