### ISSUE TITLE
bigint失真问题

### ISSUE THREAD

**Issue by CainGitHub** [ssrpanel/SSRPanel#1110]
创建或更新用户的时候，可用流量会因为mysql bigint类型失真，请问怎么统一处理不用代码一个个去改

**Comment by ssrpanel** [comment]
会失真吗？举例说明

**Comment by CainGitHub** [comment]
很高兴与你沟通，比如：页面输入1000GiB，后台收到转成1073741824000，存储到Mysql数据库变成了0；我改了下源码，存储的时候把transfer_enable改成字符串就没问题。我的环境是：CentOS7 64位、PHP71w 64位、MySQL5.7 64位。

**Comment by ssrpanel** [comment]
貌似没碰到过呢，不应该啊

**Comment by niyeyeqi** [comment]
这个人不会是外国友人吧？

**Comment by CainGitHub** [comment]
PHP 7.1.24 (cli) (built: Nov 11 2018 08:03:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies


mysql> show variables like '%version_%';
+-------------------------+------------------------------+
| Variable_name           | Value                        |
+-------------------------+------------------------------+
| slave_type_conversions  |                              |
| version_comment         | MySQL Community Server (GPL) |
| version_compile_machine | x86_64                       |
| version_compile_os      | Linux                        |
+-------------------------+------------------------------+

Linux vpn01 4.19.6-1.el7.elrepo.x86_64 #1 SMP Sat Dec 1 11:58:18 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

$data = [
'transfer_enable'      => "".toGB($transfer_enable).""
];  转成字符串格式存储就没有问题，php与mysql表示bigint的长度问题 ？

**Comment by ssrpanel** [comment]
是不是你数据库开了什么安全模式 之类的

**Comment by CainGitHub** [comment]
没有开安全模式哦

**Comment by ssrpanel** [comment]
php 是nts 吗 还是ts
