### ISSUE TITLE
最近有没有人跟我一样，服务器被墙的很频繁

### ISSUE THREAD

**Issue by chasenn** [ssrpanel/SSRPanel#1113]
rt。。。。

**Comment by chasenn** [comment]
我是443 单端口 严格模式 加密用的chacha20-ietf 协议 auth_aes128_md5 混淆 tls1.2_ticket_auth 前几天突然都被墙了，更换ip后两三天又被墙了。

**Comment by chasenn** [comment]
> 我记得很早之前胖虎就提示不要用tls混淆了

还有什么要注意的没，之前我一直都挺稳定，有一年左右没被墙。

**Comment by vft9nesd** [comment]
none+ chain_a+plain 从未被墙过

**Comment by chasenn** [comment]
> none+ chain_a+plain 从未被墙过

none是不加密？？？？还能这么操作？？？？？！！！！！
你是几个人用

**Comment by chasenn** [comment]
> 我现在都是转v2了



> 我现在都是转v2了

稳定嘛。

**Comment by dovela** [comment]
除了tls，用什么都可以，主流的还有rc4md5  sha1…v4 http…simple，楼上那个none的组合也很好

**Comment by vft9nesd** [comment]
无招胜有招知道嘛~甚至none+origin+plain我都试过，原版协议不吃cpu，带宽跑的贼快，我的日本vultr，联通直连100ms，none+ chain_a+plain 最多跑15m/s 换origin 跑60m/s ，反正可以换ip，爱墙墙去吧~

**Comment by ssrpanel** [comment]
除了tls
