### ISSUE TITLE
用户按照状态排序，像以前一样

### ISSUE THREAD

**Issue by vft9nesd** [ssrpanel/SSRPanel#1115]
以前好像封号的或者ssr禁用的 排在后面，现在没有以前好了

**Comment by vft9nesd** [comment]
有段时间没更新代码了，发现已禁用的账号依然排在前面，现在优化了吗？如果优化了请忽略这条~

**Comment by vft9nesd** [comment]
可以增加几个升降排序按钮，编号排序，有效期排序，ssr状态排序，账号状态排序  等等

**Comment by ssrpanel** [comment]
有空我再加查询条件
