### ISSUE TITLE
请求支持 TrimePay 支付网关

### ISSUE THREAD

**Issue by tonyzzzzzz** [ssrpanel/SSRPanel#1116]
本人为 TrimePay 站长，此支付网关支持 微信与支付宝。详细请联系我 TG @SARFT_Framework

官网地址: https://portal.trimepay.com
文档地址: https://docs.trimepay.com

**Comment by cmmdwl** [comment]
这个，你得自己写接口，就像以前那个易支付那样，胖虎不主动接个人支付网站的，

**Comment by cmmdwl** [comment]
或者你可以提一个pr

**Comment by tonyzzzzzz** [comment]
已推 PR

**Comment by ssrpanel** [comment]
已合并

**Comment by zhuxiaole** [comment]
已更新TrimePay，请问支付二维码上的提示，使用“微信、支付宝、qq”是在哪个文件里修改？

**Comment by ssrpanel** [comment]
已使用
