### ISSUE TITLE
qq邮箱绑自己的域名邮箱，贼装逼

### ISSUE THREAD

**Issue by vft9nesd** [ssrpanel/SSRPanel#1117]
需要有一个自己的域名，域名有一定的要求，但不用备案
假如自己的域名是abc.com，发出去的邮件是****@abc.com ，前面的****可以随便设置。
很装逼吧？

方法如下
登录qq邮箱，设置，账户，管理域名邮箱，创建域名邮箱
![image](https://user-images.githubusercontent.com/24932999/49587464-dd6f2d80-f99e-11e8-9c22-9a19167b7527.png)
有部分域名不支持，比如tk，top，如果没申请域名的，先到这里来填一下试试，如果不支持会说系统错误。
me域名是支持的，给一个namecheap的免费me域名注册地址  [点这里](https://nc.me/)，无限续订，无限免费，需要github学生包，有需要的自行百度。

域名输入之后，下一步，选其他提供商
![image](https://user-images.githubusercontent.com/24932999/49587862-178cff00-f9a0-11e8-9204-c5e2bfd3e930.png)
dns设置里添加如图记录，验证成功之后进入域名邮箱管理
![image](https://user-images.githubusercontent.com/24932999/49587951-69358980-f9a0-11e8-8b0a-a9806646e1fc.png)

点击成员管理，点击qq号之后的编辑
![image](https://user-images.githubusercontent.com/24932999/49588121-e9f48580-f9a0-11e8-9d84-5a7eec365d79.png)
账号即为邮箱前缀
完事
发邮件时候可选这个发信地址
stmp也可设置此邮件地址
效果如图
![image](https://user-images.githubusercontent.com/24932999/49588291-54a5c100-f9a1-11e8-94b8-6da9477f0225.png)

**Comment by cmmdwl** [comment]
缺点是如果有人找上门来，可以通过查询mx记录得知是指向qq的
然后如果有权限，腾讯里面直接可以查你来获得你的qq管理员号码
你确定？

**Comment by littlesker** [comment]
没有意义！

**Comment by ssrpanel** [comment]
其实没什么意义的，我用yandex
