### ISSUE TITLE
验证邮件过期问题

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#112]
如果验证邮件在规定时间内未阅读,那么再点击邮件里面确认连接的话, 会跳到控制中心出错页面, 可否改为404甚至空白页,见附图.

![a](https://user-images.githubusercontent.com/32491066/32900435-7136112e-cb28-11e7-9384-2683c98b305d.png)
![b](https://user-images.githubusercontent.com/32491066/32900438-71f96b7e-cb28-11e7-949b-7a3d53ad75d4.png)

**Comment by ssrpanel** [comment]
已修复，等待代码更新

**Comment by 1021435278** [comment]
等待更新....
