### ISSUE TITLE
继上一个登录response无返回的错误后我强制更新了然后报下面的错误：提示找不到view class

### ISSUE THREAD

**Issue by chasenn** [ssrpanel/SSRPanel#1122]
2018/12/07 09:45:19 [error] 2248#0: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ReflectionException: Class view does not exist in /www/wwwroot/enetlinker.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/Container.php:729
Stack trace:
#0 /www/wwwroot/enetlinker.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/Container.php(729): ReflectionClass->__construct('view')
#1 /www/wwwroot/enetlinker.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build('view')
#2 /www/wwwroot/enetlinker.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container->resolve('view')
#3 /www/wwwroot/enetlinker.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Container\Container->make('view')
#4 /www/wwwroot/enetlinker.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/Container.php(1172): Illuminate\Foundation\Application->make('view')
#5 /www/wwwroot/enetlinker.com/ssr...
PHP message: PHP Fatal error:  Uncaught ReflectionException: Class view does not exist in /www/wwwroot/enetlinker.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/Container.php:729
Stack trace:
#0 /www/wwwroot/enetlinker.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/Container.php(729): ReflectionClass->__construct('view')
#1 /www/wwwroot/enetlinker.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build('view')
#2 /www/wwwroot/enetlinker.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container->resolve('view')
#3 /www/wwwroot/enetlinker.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Container\Container->make('view')
#4 /www/wwwroot/enetlinker.com/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/Container.php(1172): Illuminate\Foundation

**Comment by chasenn** [comment]
不知道怎么就解决了

**Comment by ssrpanel** [comment]
应该是执行php composer.phar install的时候有些东西没处理好，在执行一次就好了
