### ISSUE TITLE
ErrorException: Undefined variable: node_daily_report 

### ISSUE THREAD

**Issue by planxx** [ssrpanel/SSRPanel#1127]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问

升级之后日志中出现“ErrorException: Undefined variable: node_daily_report ”错误，但是感觉没有那里功能异常。。。。

**Comment by ssrpanel** [comment]
你们都不看wiki的吗？每次git pull 都要导入

**Comment by planxx** [comment]
导入啥？导入数据库？导入了。。。

**Comment by planxx** [comment]
大佬，你可以自己测试一下，已经导入了最新的数据库了！而且，数据库中有这些字段，应该是前端页面的锅？
