### ISSUE TITLE
有赞云微商店依然可以用，可以申请人工认证

### ISSUE THREAD

**Issue by niyeyeqi** [ssrpanel/SSRPanel#1129]
![1](https://user-images.githubusercontent.com/31157068/49685529-a411fb80-fb1f-11e8-9e5d-bba76d523568.png)
![screenshot_20181208-192843](https://user-images.githubusercontent.com/31157068/49685528-a1afa180-fb1f-11e8-9628-f679b342dac7.png)

**Comment by niyeyeqi** [comment]
sfz这类东西可以百度或者必应能搜到

**Comment by niyeyeqi** [comment]
成功率几乎100%

**Comment by hj-mb** [comment]
手持

**Comment by ssrpanel** [comment]
具体内幕不说了。哈哈哈哈。。。估计你还没用到一定的层次。

**Comment by cmtomkan310** [comment]
@ssrpanel 说说内幕呗，让我们的损失少一点！

**Comment by vft9nesd** [comment]
google手持***第一条

**Comment by vft9nesd** [comment]
不知道哪个缺德的发出来的~~~
