### ISSUE TITLE
把网站从一个服务器搬到另一个服务器，数据库也搬了，系统配置404

### ISSUE THREAD

**Issue by 931512501** [ssrpanel/SSRPanel#1131]
搬迁数据后其他功能正常，访问系统配置时404，试过将update里面最后一个sql文件导入，依旧没用

**Comment by DanielZhang17** [comment]
检查权限

**Comment by 931512501** [comment]
检查stroge权限吗，权限是777

**Comment by 931512501** [comment]
是不是需要我把原来的网站也打包，新服务器上的panel是直接拉取的

**Comment by DanielZhang17** [comment]
你直接重装面板，数据库直接用应该就行

**Comment by GaHoKwan** [comment]
我也404，重装无效

**Comment by 931512501** [comment]
问题成功解决。方法如下:
清空数据库，清空网站，完全重装然后导入原始数据库，然后覆盖导入user开头的和sub开头的表，这样相当于重新建面板，但是用户数据都还有，节点再自行添加

**Comment by 931512501** [comment]
问题成功解决。方法如下:
清空数据库，清空网站，完全重装然后导入原始数据库，然后覆盖导入user开头的和sub开头的表，这样相当于重新建面板，但是用户数据都还有，节点再自行添加
