### ISSUE TITLE
管理后台和用户界面展示的支付方式不一致

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#1134]
问题现象如题。

操作场景：用户自助支付失败了，管理员对该账号进行充值，然后切换到该用户购买服务，使用余额支付。

管理后台显示：
![image](https://user-images.githubusercontent.com/6386202/49698028-608bc000-fbf9-11e8-9f8b-a9e8c76edcb3.png)

用户后台显示：
![image](https://user-images.githubusercontent.com/6386202/49698007-2d493100-fbf9-11e8-9dfd-e80ce10d9287.png)

**Comment by ssrpanel** [comment]
fixed
