### ISSUE TITLE
建议邮箱敏感词加一个白名单机制

### ISSUE THREAD

**Issue by lsbjkc** [ssrpanel/SSRPanel#1135]
只有在白名单中的邮箱才可以注册，避免大量临时邮箱的涌入

**Comment by ssrpanel** [comment]
已经着手开发

**Comment by ssrpanel** [comment]
考虑了一番，还是觉得是个鸡肋需求，丢弃

**Comment by 828768** [comment]
> 考虑了一番，还是觉得是个鸡肋需求，丢弃

这个不鸡肋啊，邮箱提供下拉选择，其他不让注册，保证了用户的真实性，也提高羊毛党的成本
