### ISSUE TITLE
被墙反馈列表

### ISSUE THREAD

**Issue by ssrpanel** [ssrpanel/SSRPanel#1138]
## 格式
- ISP | 国家 | IP | 月流量 | 加密方式 | 混淆 | 协议 | 协议参数

**Comment by thank243** [comment]
阿里云香港，单端口多用户，aes256cfb,authaes128sha1,tls1.2ticketauth.ssr作为反代，后面挂nginx继续反代v2ray。

**Comment by vft9nesd** [comment]
只要开tls的都被阻断过，过段时间又放出来了
最稳的是none+auth_chain_a+plain，十几台机器没被墙过（我不做飞机场，买vps是一种快感）

**Comment by 329928** [comment]
> 只要开tls的都被阻断过，过段时间又放出来了
> 最稳的是none+auth_chain_a+plain，十几台机器没被墙过（我不做飞机场，买vps是一种快感）

好巧，我刚从 none + auth_chain_a + tls 换到 + plain 
之前tls其实也没怎么被墙，但是感觉速度有点慢。
现在浏览网页偶尔出现拒绝连接的情况，再刷新一次又正常，这是被干扰了吗

**Comment by littlesker** [comment]
@ssrpanel 卸载了 使用一键卸载安骑士等监控，还用工具重装了centos 6.9系统

**Comment by vft9nesd** [comment]
> tls1.2_ticket_auth_compatible

去年都说tls可以被精准识别了→_→

**Comment by 329928** [comment]
> > tls1.2_ticket_auth_compatible
> 
> 去年都说tls可以被精准识别了→_→

讲真我一堆机子tls，比如onevps的新加坡，已经三个月了都没被墙

**Comment by RabiChannel** [comment]
枫叶主机两台，美国月流量几十G，香港月流三百不到。
conoha日本一台，流量十几G。
加密chacha20或aes192ctr，混淆 tls1.2，协议chain a没参数
10号中午十分钟三台鸡全被铁窗后了，24小时后放出来了
然后11中午放出来就5分钟又关进去了，两个钟又放出来
然后再连上，30秒又关进去了，现在只有发起连接就关进去
然而只阻断了TCP，KCP照样用，面板不能直接打开倒是有点头大

**Comment by idelin** [comment]
ISP | 国家 | IP | 月流量 | 加密方式 | 混淆 | 协议 | 协议参数
---|---|---|--- | ---| --- | --- | ---
conoha | jp | 133.130.96.18 | 10g+ | aes-256-cfb | plain | origin| null
linode | us | 23.239.22.17 | 10g+ | aes-256-cfb | plain | origin| null

**Comment by littlesker** [comment]
@lybc  据说rc4+roigin+plain

**Comment by vft9nesd** [comment]
我觉得吧，单端口好像能好点？如图海豚湾全部鸡鸡都是这个
![image](https://user-images.githubusercontent.com/24932999/50042066-7259e100-0099-11e9-8dc5-971d559b27d1.png)
可能我是因为单端口所以没被墙过，或者说是概率极低。。单端口好像很骚，可以研究一下

**Comment by ssrpanel** [comment]
热门商家IP段高危

**Comment by ssrpanel** [comment]
你们买过的，很可能是曾经进过墙的

**Comment by idelin** [comment]
> 你们买过的，很可能是曾经进过墙的

为什么那么说，最近很多这种情况

**Comment by vft9nesd** [comment]
逗比好像已经喝去tea了悠着点吧～

**Comment by ssrpanel** [comment]
> > 你们买过的，很可能是曾经进过墙的
> 
> 为什么那么说，最近很多这种情况

哈哈哈，因为我的5台无限流量的VPS，都没有被墙过，用了6个月了

**Comment by ssrpanel** [comment]
@vft9nesd 他那么传播几万人的群，迟早喝茶的

**Comment by idelin** [comment]
> > > 你们买过的，很可能是曾经进过墙的
> > 
> > 
> > 为什么那么说，最近很多这种情况
> 
> 哈哈哈，因为我的5台无限流量的VPS，都没有被墙过，用了6个月了

我之前用的两年的无限流量的都很稳，上周就被墙了==！不应该是以前被墙过的

**Comment by ssrpanel** [comment]
> a了悠着点吧～

这个你放心，1我没有大肆传播，2我的教程非那种一键挣钱型，需要有技术基础

**Comment by ssrpanel** [comment]
> > > > 你们买过的，很可能是曾经进过墙的
> > > 
> > > 
> > > 为什么那么说，最近很多这种情况
> > 
> > 
> > 哈哈哈，因为我的5台无限流量的VPS，都没有被墙过，用了6个月了
> 
> 我之前用的两年的无限流量的都很稳，上周就被墙了==！不应该是以前被墙过的

那我就不晓得了。

**Comment by idelin** [comment]
> 逗比好像已经喝去tea了悠着点吧～

这个喝茶很严重吗，我姐闺蜜老公搞这个搞了几年，被逮进去了，貌似已经判刑了...

**Comment by ssrpanel** [comment]
@idelin 那你还搞？

**Comment by vft9nesd** [comment]
仅仅指的是翻wall的吧？那些做手机免流的屁事都没有。。墙外一群听风就是雨的脑残，加上敏感期，翻车很正常🌚

**Comment by idelin** [comment]
> @idelin 那你还搞？

我就几个同事合租用啊，但是大家时间不太一样不好算钱我才想借用这个续费下，没有对外出售

**Comment by vft9nesd** [comment]
买vps的感觉就像吸x，停不下来怎么办。。胖虎你的vps是哪家的，三网优化如何

**Comment by ssrpanel** [comment]
自用要求不高，nathosts 动态
namesilo ddns + nathosts + hkt  三个月不到200块，可吃鸡，可奈非，ddns脚本我已经开源了，php写的

出售的话我就不说了，秘密

**Comment by vft9nesd** [comment]
啊哈

**Comment by Losgif** [comment]
HKT HGC HKBN WTT NTT CN2关键字
