### ISSUE TITLE
更新ssrpanel

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#114]
@ssrpanel 

胖虎请问,每次git你更新后, 我们在项目总直接运行git pull对应更新. 

但是如果项目总已经有数据库的话如何操作? git_fix.sh 和git pull / update.sh 具体如何操作可否写进Code文档中?

**Comment by ssrpanel** [comment]
备份config/database.php
执行一次 sh fix_git.sh
然后把备份的database.php覆盖回去
然后执行git pull
update.sh 会强制更新本地所有代码（包括你自己改的东西）
