### ISSUE TITLE
面板里面的

### ISSUE THREAD

**Issue by Goog686ii** [ssrpanel/SSRPanel#1147]
[图片]面板里面的 单连接限速和单用户限速新版本被写死，老版本是可以修改的，怎么解除 虎哥。

**Comment by Google688** [comment]
![tim 20181212150334](https://user-images.githubusercontent.com/38600824/49852465-1f74f500-fe1f-11e8-95d1-0fd48efacbdd.png)

**Comment by hj-mb** [comment]
实际无此功能

**Comment by samac08** [comment]
这个就算能改也没用 都是后端控制的
