### ISSUE TITLE
订单选错支付方式后系统不能自动关闭一直待付款

### ISSUE THREAD

**Issue by MrPangzhan** [ssrpanel/SSRPanel#1151]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问

订单选错支付方式后系统不能自动关闭一直待付款，目前用的TrimePay支付宝签约，微信没有签约。用户选择微信付款后就这样了。

建议TrimePay 只显示签约的支付方式。

**Comment by ssrpanel** [comment]
marked

**Comment by ssrpanel** [comment]
会不能自动关闭吗？看下日志有没有报错？
