### ISSUE TITLE
目前使用过程中已知的BUG

### ISSUE THREAD

**Issue by littlesker** [ssrpanel/SSRPanel#1156]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
1.这个issues也有过了，就是删除标签但是依然可以连接的bug
后端貌似是用用户代理信息（加密、协议、混淆）来的，

2.节点的代理信息（加密、协议、混淆）似乎形同虚设，
测试过程中没有看用到节点的代理信息（加密、协议、混淆），订阅什么的都是显示的是用户的代理信息（加密、协议、混淆），后端也是，以用户代理信息为主，来判断。这样就导致所有节点只能用一种加密和协议，除非给那个用户手动设置，但是这样其他节点又不能连接了

3.商品购买的问题（建议）
商品购买只给用户增加了标签，是否可以同时修改加密和协议，这样似乎能解决上面的问题

**Comment by hj-mb** [comment]
只回答第一个 不是bug 面板无标签限制连接的功能 只影响可见和订阅

**Comment by hj-mb** [comment]
换面板

**Comment by yongjie0203** [comment]
第一个问题 貌似需要相应ssr后端配合才行的吧，只是换面板解决不了问题

**Comment by littlesker** [comment]
@littlesker ：> 那个面板还比较好一点？ sspanel-v3-mod-uims？

**Comment by yongjie0203** [comment]
稍微改动下ssr后端就可以了 不用换面板

**Comment by littlesker** [comment]
@yongjie0203 后端代码看了下，想让后端获取数据库节点的代理信息，而不是获取用户的，代理没找到，

**Comment by yongjie0203** [comment]
db_transfer.py pull_db_users 部分关联个节点配置表，查询字段改成节点表的

**Comment by littlesker** [comment]
@yongjie0203 可以分享下吗？db_transfer.py 没找到怎么改

**Comment by littlesker** [comment]
@yongjie0203  在db_transfer.py  
205行
protocol = cfg.get('protocol', ServerPool.get_instance().config.get('protocol', 'origin'))
        method = cfg.get('method', ServerPool.get_instance().config.get('method', 'None'))
        obfs = cfg.get('obfs', ServerPool.get_instance().config.get('obfs', 'plain'))’

**Comment by nifengtang** [comment]
请问如何签到？
