### ISSUE TITLE
关于80单端口 http_simple填入混淆参数失效问题

### ISSUE THREAD

**Issue by ntgeralt** [ssrpanel/SSRPanel#1160]
你好，我发现个80单端口obfs_param填入内容无法正常工作的问题，反馈下：

sspanel搭建好，后端是根据《ShadowsocksR 后端安装教程 (萌新入门向)》搭建。
后端测试443单端口，客户端测试能通过上google；

之后问题来了，改80端口，重启服务

    "additional_ports" : {
    "80": {
        "passwd": "xxxxxxxxx",
        "method": "chacha20",
        "protocol": "auth_aes128_md5",
        "protocol_param": "#",
        "obfs": "http_simple",
        "obfs_param": "r34r34r3.1323.com"
    }
},

客户端也改成80端口，结果访问不了google；

之后我发现，混淆参数改为留空状态，则80单端口，又能正常能访问google。

请问是设置上是输入错什么内容了吗？请教一下如何解决这问题。

**Comment by kszym2002** [comment]
user-config.json中不要填入混淆参数   请在面板中填入

**Comment by ntgeralt** [comment]
测试发现 chain none   http_simple 在ios小火箭有问题。。。有时通有时完全不通
