### ISSUE TITLE
用户中心流量问题

### ISSUE THREAD

**Issue by tiandao877** [ssrpanel/SSRPanel#1161]
用户流量一直在走，可是在控制面板管理中心,已经好几天了,流量记录都没有变化
节点的流量也是,一直没有发生变化,
之前有过变化,不知道为什么就好久都没有变化了
求解

**Comment by samac08** [comment]
这个明显是定时任务的问题,仔细检查下吧 我以前也是这个问题困扰.自己解决了 我是lnmp搭建环境 Debian
仅供参考下: 
crontab -e -u www 加入如下命令（请自行修改自己php、ssrpanel的实际路径）：
* * * * * /usr/bin/php-fpm空格/home/wwwroot/自己目录/ssrpanel/artisan schedule:run >> /dev/null 2>&1
保存.
/etc/init.d/cron restart重启定时 一分钟后即可看到效果. 如果要看日志的话就打开系统的cron运行日志 /etc/rsyslog.conf 将 cron.* 行前的#去掉保存 .重启日志记录服务 systemctl restart rsyslog.service
然后cat 空格/var/log/syslog 即可看到运行日志 ...

**Comment by ssrpanel** [comment]
翻wiki，里面有lee-blog.com里的lee写的一堆教程，认真看
