### ISSUE TITLE
.env里新加重定向到https的默认值改成false吧

### ISSUE THREAD

**Issue by RabiChannel** [ssrpanel/SSRPanel#1162]
在新鸡儿上重新拉取了Code
配置完后发现http一直被重定向到https上
搞七搞八一个钟才注意到十几个小时前在.env里加了这个开关
默认值改成false应该会少一些issue问这个

**Comment by cmmdwl** [comment]
签个证书有多困难，况且苹果app下载还是需要https的

**Comment by ssrpanel** [comment]
请使用https，否则 ios系列下访问 一堆莫名其妙的 问题，而且https 是趋势，http容易被劫持
