### ISSUE TITLE
异常- 自动关闭超时未支付订单

### ISSUE THREAD

**Issue by SKEETCHAN** [ssrpanel/SSRPanel#1166]
尝试重新自动化任务没有奏效

info | local | 2018-12-17 20:09:02 | 【异常】自动关闭超时未支付订单：ErrorException: Trying to get property of non-object in /www/wwwroot/*****/SSRPanel/app/Console/Commands/AutoJob.php:500
-- | -- | -- | --
info | local | 2018-12-17 20:08:01 | 执行定时任务【自动检测节点状态】，耗时0.0023秒
info | local | 2018-12-17 20:08:01 | 执行定时任务【自动化任务】，耗时0.0183秒
info | local | 2018-12-17 20:08:01 | 【异常】自动关闭超时未支付订单：ErrorException: Trying to get property of non-object in /www/wwwroot/*****/app/Console/Commands/AutoJob.php:500
info | local | 2018-12-17 20:07:02 | 执行定时任务【自动检测节点状态】，耗时0.0024秒
info | local | 2018-12-17 20:07:02 | 执行定时任务【自动化任务】，耗时0.0185秒
info | local | 2018-12-17 20:07:02 | 【异常】自动关闭超时未支付订单：ErrorException: Trying to get property of non-object in /www/wwwroot/*****/SSRPanel/app/Console/Commands/AutoJob.php:500
info | local | 2018-12-17 20:06:01 | 执行定时任务【自动检测节点状态】，耗时0.0024秒
info | local | 2018-12-17 20:06:01 | 执行定时任务【自动化任务】，耗时0.0183秒
info | local | 2018-12-17 20:06:01 | 【异常】自动关闭超时未支付订单：ErrorException: Trying to get property of non-object in /www/wwwroot/*****/SSRPanel/app/Console/Commands/AutoJob.php:500

**Comment by SKEETCHAN** [comment]
`ErrorException: Trying to get property of non-object 
in /www/wwwroot/_______/SSRPanel/app/Console/Commands/AutoJob.php:500
Stack trace:
#0 /www/wwwroot/_______/SSRPanel/app/Console/Commands/AutoJob.php(500): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/www/wwwroot/ss...', 500, Array)
#1 /www/wwwroot/_______/SSRPanel/app/Console/Commands/AutoJob.php(74): App\Console\Commands\AutoJob->closeOrders()
#2 [internal function]: App\Console\Commands\AutoJob->handle()
#3 /www/wwwroot/_______/SSRPanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#4 /www/wwwroot/_______/SSRPanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 /www/wwwroot/_______/SSRPanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#6 /www/wwwroot/_______/SSRPanel/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#7 /www/wwwroot/_______/SSRPanel/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#8 /www/wwwroot/_______/SSRPanel/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#9 /www/wwwroot/_______/SSRPanel/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#10 /www/wwwroot/_______/SSRPanel/vendor/symfony/console/Application.php(953): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /www/wwwroot/_______/SSRPanel/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\AutoJob), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /www/wwwroot/_______/SSRPanel/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /www/wwwroot/_______/SSRPanel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /www/wwwroot/_______/SSRPanel/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 {main}`

**Comment by ssrpanel** [comment]
你手动过数据库，阎王爷都帮不了你
