### ISSUE TITLE
高级订阅的一个小问题

### ISSUE THREAD

**Issue by SRCOL** [ssrpanel/SSRPanel#1168]
启用高级订阅时：
“到期时间”与“可用流量”的群组名显示为“VPN”而不是设定好的
问题很小，就是看着不太舒服。。。但还是希望修复

**Comment by hj-mb** [comment]
可自己改

**Comment by yongjie0203** [comment]
放在通一个组可能会影响负载均衡的效率吧，毕竟这两个节点无法使用
