### ISSUE TITLE
php composer.phar install报错

### ISSUE THREAD

**Issue by DizzlyLee** [ssrpanel/SSRPanel#1169]
看了下错误信息，说我PHP版本是5.6，估计原因我这个机器上面挂的有其他PHP版本的网站。

装sspanel的时候，创建网站设置的版本是PHP7,1还是出现下面问题

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for cloudflare/sdk 1.1.1 -> satisfiable by cloudflare/sdk[1.1.1].
    - cloudflare/sdk 1.1.1 requires php >=7.0.0 -> your PHP version (5.6.30) does not satisfy that requirement.
  Problem 2
    - Installation request for doctrine/inflector 1.3.x-dev -> satisfiable by doctrine/inflector[1.3.x-dev].
    - doctrine/inflector 1.3.x-dev requires php ^7.1 -> your PHP version (5.6.30) does not satisfy that requirement.
  Problem 3
    - Installation request for php-http/guzzle6-adapter 1.2.x-dev -> satisfiable by php-http/guzzle6-adapter[1.2.x-dev].
    - php-http/guzzle6-adapter 1.2.x-dev requires php ^7.1 -> your PHP version (5.6.30) does not satisfy that requirement.
  Problem 4
    - Installation request for php-http/guzzle6-adapter dev-master -> satisfiable by php-http/guzzle6-adapter[dev-master].
    - php-http/guzzle6-adapter dev-master requires php ^7.1 -> your PHP version (5.6.30) does not satisfy that requirement.
  Problem 5
    - Installation request for symfony/contracts 1.0.x-dev -> satisfiable by symfony/contracts[1.0.x-dev].
    - symfony/contracts 1.0.x-dev requires php ^7.1.3 -> your PHP version (5.6.30) does not satisfy that requirement.
  Problem 6
    - Installation request for symfony/contracts dev-master -> satisfiable by symfony/contracts[dev-master].
    - symfony/contracts dev-master requires php ^7.1.3 -> your PHP version (5.6.30) does not satisfy that requirement.
  Problem 7
    - Installation request for symfony/finder 4.2.x-dev -> satisfiable by symfony/finder[4.2.x-dev].
    - symfony/finder 4.2.x-dev requires php ^7.1.3 -> your PHP version (5.6.30) does not satisfy that requirement.
  Problem 8
    - Installation request for symfony/finder dev-master -> satisfiable by symfony/finder[dev-master].
    - symfony/finder dev-master requires php ^7.1.3 -> your PHP version (5.6.30) does not satisfy that requirement.
  Problem 9
    - Installation request for symfony/http-foundation 4.2.x-dev -> satisfiable by symfony/http-foundation[4.2.x-dev].
    - symfony/http-foundation 4.2.x-dev requires php ^7.1.3 -> your PHP version (5.6.30) does not satisfy that requirement.
  Problem 10
    - Installation request for symfony/http-foundation dev-master -> satisfiable by symfony/http-foundation[dev-master].
    - symfony/http-foundation dev-master requires php ^7.1.3 -> your PHP version (5.6.30) does not satisfy that requirement.
  Problem 11
    - Installation request for symfony/intl 4.2.x-dev -> satisfiable by symfony/intl[4.2.x-dev].
    - symfony/intl 4.2.x-dev requires php ^7.1.3 -> your PHP version (5.6.30) does not satisfy that requirement.
  Problem 12
    - Installation request for symfony/intl dev-master -> satisfiable by symfony/intl[dev-master].
    - symfony/intl dev-master requires php ^7.1.3 -> your PHP version (5.6.30) does not satisfy that requirement.
  Problem 13
    - Installation request for symfony/options-resolver 4.2.x-dev -> satisfiable by symfony/options-resolver[4.2.x-dev].
    - symfony/options-resolver 4.2.x-dev requires php ^7.1.3 -> your PHP version (5.6.30) does not satisfy that requirement.
  Problem 14
    - Installation request for symfony/options-resolver dev-master -> satisfiable by symfony/options-resolver[dev-master].
    - symfony/options-resolver dev-master requires php ^7.1.3 -> your PHP version (5.6.30) does not satisfy that requirement.
  Problem 15
    - Installation request for symfony/translation 4.2.x-dev -> satisfiable by symfony/translation[4.2.x-dev].
    - symfony/translation 4.2.x-dev requires php ^7.1.3 -> your PHP version (5.6.30) does not satisfy that requirement.
  Problem 16
    - Installation request for symfony/translation dev-master -> satisfiable by symfony/translation[dev-master].
    - symfony/translation dev-master requires php ^7.1.3 -> your PHP version (5.6.30) does not satisfy that requirement.
  Problem 17
    - doctrine/inflector 1.3.x-dev requires php ^7.1 -> your PHP version (5.6.30) does not satisfy that requirement.
    - illuminate/support 5.2.x-dev requires doctrine/inflector ~1.0 -> satisfiable by doctrine/inflector[1.3.x-dev].
    - Installation request for illuminate/support 5.2.x-dev -> satisfiable by illuminate/support[5.2.x-dev].

![1](https://user-images.githubusercontent.com/45913397/50163163-d17a5880-031a-11e9-82eb-e4182943c67f.jpg)
![2](https://user-images.githubusercontent.com/45913397/50163165-d212ef00-031a-11e9-82dd-6bf1748332f7.jpg)

**Comment by DizzlyLee** [comment]
宝塔多做挂，给后人留下方案。已经解决，方式：将默认版本改成71
命令ln -sf /www/server/php/71/bin/php /usr/bin/php

**Comment by feikk** [comment]
非常感谢，我也用的宝塔，遇到这个问题。
