### ISSUE TITLE
胖虎最新升级翻车了!!!!

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#117]
@ssrpanel 

升级后,个人用户点小飞机图标, 订阅的代码飞到下面去了.

![123](https://user-images.githubusercontent.com/32491066/33029455-97334fee-ce53-11e7-96a8-f5f2500ba25c.png)

**Comment by ssrpanel** [comment]
再更新代码

**Comment by 1021435278** [comment]
具体更新的步骤是什么? 直接git pull , 之前数据库和 ./config/database.php要备份吗?
