### ISSUE TITLE
同一台机器后端安装报错

### ISSUE THREAD

**Issue by DizzlyLee** [ssrpanel/SSRPanel#1171]
Cannot uninstall 'requests'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
![qq 20181218234817](https://user-images.githubusercontent.com/45913397/50165239-7bf47a80-031f-11e9-8389-b2b9fb479a6a.jpg)

**Comment by DizzlyLee** [comment]
![qq 20181219003408](https://user-images.githubusercontent.com/45913397/50168197-d2fd4e00-0325-11e9-81c1-6db82b0b3321.jpg)
新问题，我换了个脚本安装。然后检查是这样的错误。检查后，发现更换默认的1025端口也是这样，ipv6也不是ture

**Comment by yongjie0203** [comment]
貌似端口被占用，杀掉占用端口的进程，重新启动

**Comment by DizzlyLee** [comment]
> 貌似端口被占用，杀掉占用端口的进程，重新启动

换端口也是一样的。35606这个是前端用户刚重置的端口
