### ISSUE TITLE
后端报错 [Errno 98] Address already in use 在线等

### ISSUE THREAD

**Issue by DizzlyLee** [ssrpanel/SSRPanel#1172]
是新装的，之前装过别人的一键脚本没成功（如果是这个原因不重装系统怎么卸载他的后端一键脚本），另外我重新手动安装过了。还是不行，以下是说明

1.端口没有占用，更换很多歌端口也是这样
2.没有开ipv6
3.服务器时间和本地一致 
4.user-config.json和config.json加密方式一致

已贴图，请各位大佬看看。

![qq 20181219022809](https://user-images.githubusercontent.com/45913397/50174699-ddbfdf00-0335-11e9-8d0f-98495ef08082.jpg)

**Comment by Losgif** [comment]
(怎么一个个基础知识啥都不明白都跑来github issue问问题？？？现在机场门槛这么低？？？)

你这个问题就是端口被占用，之前程序没有关闭

`sh
ps aux | grep python
`
找到之前运行未关闭的进程

`sh
kill $id
`

$id 自行替换

善用搜索引擎😑

**Comment by ssrpanel** [comment]
@Losgif 所以我都直接关闭的

**Comment by DizzlyLee** [comment]
> (怎么一个个基础知识啥都不明白都跑来github issue问问题？？？现在机场门槛这么低？？？)
> 
> 你这个问题就是端口被占用，之前程序没有关闭
> 
> `ps aux | grep python`
> 找到之前运行未关闭的进程
> 
> `kill $id`
> 
> $id 自行替换
> 
> 善用搜索引擎

哥，真的不是端口占用。重启，在前端更换端口都是没用的！！！


![qq 20181219121345](https://user-images.githubusercontent.com/45913397/50198691-9eba7980-0387-11e9-8759-00f6d5bc9917.jpg)

**Comment by DizzlyLee** [comment]
这个就是因为安装了别人的一键包造成的应该，求问不重做系统，怎么让别人的包删除？上面大佬给的方式ps aux | grep python，没什么用啊，没发现这里面有重复的ID。

@ssrpanel
