### ISSUE TITLE
大佬利用宝塔安装，个人中心报404，修改节点好报错

### ISSUE THREAD

**Issue by zhangyubushiyu** [ssrpanel/SSRPanel#1173]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
前端后端都在一个机器上，看了很多教程发现都是正常的。系统是CentOS Linux 7.6.1810，

个人中心打开就报404

修改节点点击提交的时候回弹框报错如下
“编辑失败：SQLSTATE[23000]:lntegrity constra int violation:1048 Column 'v2_host' cannot be null....后面就是各种字段的。
这个报错新的添加都没有问题。

求解

**Comment by zhangyubushiyu** [comment]
404 问题已经解决
将配置中的database.php-> mysql-> strict设为false就可以了

**Comment by zhangyubushiyu** [comment]
修改节点报错 重启mysql解决

**Comment by ssrpanel** [comment]
懵比树下懵逼猴，懵逼猴看的一脸懵逼
