### ISSUE TITLE
造了个轮子

### ISSUE THREAD

**Issue by mzfqy** [ssrpanel/SSRPanel#1176]
https://github.com/mzfqy/OneClickSsr-ssrpanel
一键安装ssrr后端
特性
自动释放内存
自动半夜重启服务器
进程守护每分钟检测

**Comment by ssrpanel** [comment]
感谢，你这个ssr是啥版本

**Comment by ssrpanel** [comment]
哈哈，你好猥琐，看到配置里的默认网址了

**Comment by ssrpanel** [comment]
给你丢wiki了，我稍后试试看

**Comment by mzfqy** [comment]
你的版本....我就改了个单端口配置.....写脚本改太麻烦了哈哈

**Comment by garhing** [comment]
starstarstar
