### ISSUE TITLE
最急需的功能清单,请参考.

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/SSRPanel#118]
@ssrpanel 
增加类似魔改那种审计和审计规则(见附图) ,除了正则外,同时可以在后台输入屏蔽的域名,直接封杀敏感网站- 重中之重.
后台增加封锁BT下载开关.
管理员管理中心首页增加待处理工单栏目.
可以后台手动给账号充值，而不是改余额.
发布或者回复工单则自动发邮件提醒,或者直接在邮件上回复工单(这个大部分IDC都支持,也很方便)

![123](https://user-images.githubusercontent.com/32491066/33029709-45490db2-ce54-11e7-8318-8fc392f93f32.png)

**Comment by 1021435278** [comment]
@ssrpanel

**Comment by ZBrettonYe** [comment]
发issue前 麻烦先看下作者的wiki页面，很多东西都已经列在开发项目里了。魔改那种审计和审计规则这些东西，前人都已经提及过了，详情请查询关闭了的issue。ssr后端的守护进程(基于CentOS) 有大大已经写过一键脚本。

**Comment by lyz913421** [comment]
麻烦看下wiki的相关教程

**Comment by ssrpanel** [comment]
那个守护进程我从来不用。。。

**Comment by 1021435278** [comment]
@ssrpanel 
我也准备作用crontab 做个计划任务了,不需要搞那么复杂.
