### ISSUE TITLE
来自完美主义者的微小建议

### ISSUE THREAD

**Issue by fyshaw** [ssrpanel/SSRPanel#1183]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问

一点微小建议
![img_2819](https://user-images.githubusercontent.com/46097804/50390635-7b6f4000-0774-11e9-9bd1-41c957d36bb7.jpg)
![img_2822](https://user-images.githubusercontent.com/46097804/50390636-7b6f4000-0774-11e9-96c1-47b9d44600fb.jpg)

自己写的超小白客户端使用教程
[ios.txt](https://github.com/ssrpanel/SSRPanel/files/2706597/ios.txt)
[mac.txt](https://github.com/ssrpanel/SSRPanel/files/2706598/mac.txt)
[win.txt](https://github.com/ssrpanel/SSRPanel/files/2706599/win.txt)

**Comment by ssrpanel** [comment]
已采纳，感谢提供教程，等待更新，tg号多少，拉你入小群
