### ISSUE TITLE
网站迁移后订阅及充值失效

### ISSUE THREAD

**Issue by WTFTWTM** [ssrpanel/SSRPanel#1184]
你好，我从Nginx将面板迁移到Apache 保留原本数据和SQL，但是迁移完成后订阅功能和充值功能均失效，其它功能正常。
这是日志文件：https://api.aliserver.net/error.log
这是网站配置：   https://api.aliserver.net/host.conf (已移除域名等相关信息)
能否告知是何原因造成？谢谢。

**Comment by ssrpanel** [comment]
无法打开。。。

**Comment by ssrpanel** [comment]
通常nginx转apache是由于url rewrite 导致，还有，请放弃apache，用nginx或者用tengine

**Comment by WTFTWTM** [comment]
> 通常nginx转apache是由于url rewrite 导致，还有，请放弃apache，用nginx或者用tengine

已删除整机资源重装Nginx  无法访问很正常
