### ISSUE TITLE
更新后系统设置404

### ISSUE THREAD

**Issue by kk2007yx** [ssrpanel/SSRPanel#1189]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
已经导入最新的sql，系统设置还是依然404，求助。

**Comment by ssrpanel** [comment]
贴日志啊

**Comment by kk2007yx** [comment]
购买商品也是404

**Comment by ssrpanel** [comment]
http://xxxxxxxxxxx.xx/logs 看日志

**Comment by kk2007yx** [comment]
ErrorException: Undefined index: is_trimepay   
请求导致异常的地址：https://user.zlcloud.tk/buy/17
请求导致异常的地址：https://user.zlcloud.tk/soft

**Comment by ssrpanel** [comment]
https://github.com/ssrpanel/SSRPanel/wiki/%E5%A6%82%E4%BD%95%E6%9B%B4%E6%96%B0%E4%BB%A3%E7%A0%81

**Comment by ssrpanel** [comment]
去看config表里的记录，一条条对下来，你会发现少了几条，然后去sql/update下找更新文件导入数据库把

**Comment by kk2007yx** [comment]
导入数据库这个错误正常吗？
Error
SQL query:


INSERT INTO `config` VALUES ('46', 'is_free_code', 0)
MySQL said: Documentation

#1062 - Duplicate entry '46' for key 'PRIMARY'

**Comment by kk2007yx** [comment]
已经解决啦，谢谢！

**Comment by cyanogenic** [comment]
> 已经解决啦，谢谢！

怎么好的呀，我出现了同样的问题，求告知

**Comment by kk2007yx** [comment]
> > 已经解决啦，谢谢！
> 
> 怎么好的呀，我出现了同样的问题，求告知

就按照作者说的那样 sql/update 里的 一条条手动导入 如果出现我发的那个错误说明已经存在  忽略就行，据我的经验 你导入你升级当天日期的 sql文件就可以了

**Comment by cyanogenic** [comment]
> > > 已经解决啦，谢谢！
> > 
> > 
> > 怎么好的呀，我出现了同样的问题，求告知
> 
> 就按照作者说的那样 sql/update 里的 一条条手动导入 如果出现我发的那个错误说明已经存在 忽略就行，据我的经验 你导入你升级当天日期的 sql文件就可以了

多谢啦

**Comment by ssrpanel** [comment]
> 导入数据库这个错误正常吗？
> Error
> SQL query:
> 
> INSERT INTO `config` VALUES ('46', 'is_free_code', 0)
> MySQL said: Documentation
> 
> #1062 - Duplicate entry '46' for key 'PRIMARY'

特喵的，你这个是有多久没更新了，
