### ISSUE TITLE
好像是一个不错的支付，但跑不了路~

### ISSUE THREAD

**Issue by vft9nesd** [ssrpanel/SSRPanel#1192]
http://xpay.exrick.cn/
https://github.com/Exrick/xpay
https://www.bilibili.com/video/av23121122/
支付宝微信免签直接到账~不需要监控设备
跑路是别想了。。

**Comment by SRCOL** [comment]
东西是好东西，但是安全与否先不说，手动审核挺麻烦的呀。。

**Comment by mzfqy** [comment]
手动。。。

**Comment by mzfqy** [comment]
https://codepay.fateqq.com/help/BkyNe9_tl.html
这个可以

**Comment by vft9nesd** [comment]
这个好像有全自动版本呢不需要手动审核～
码支付需要一台电脑24小时监控

**Comment by vft9nesd** [comment]
码支付属于监控类支付，监控类比较多，什么安卓手机了，xposed，弹窗监控，网页监控，都需要额外的设备，比较麻烦

**Comment by mzfqy** [comment]
挂机宝之类的几块钱一个月就可以挂了

**Comment by ssrpanel** [comment]
那种需要监控的开个外挂在那盯着的那种到个人账户的，难道不会被风控吗？

**Comment by mzfqy** [comment]
发卡网挂了半年没毛病

**Comment by vft9nesd** [comment]
泡芙云的支付方式好像很骚啊，哪位大佬有空研究一下？

**Comment by vft9nesd** [comment]
叫个派付通什么的

**Comment by yongjie0203** [comment]
貌似是 https://nihaopay.com

**Comment by vft9nesd** [comment]
如何？

**Comment by yongjie0203** [comment]
费率 2.9% t+4 到账，不晓得是否需要公司资质

**Comment by vft9nesd** [comment]
那泡芙云有吗(ﾉﾟ▽ﾟ)ﾉ实测还不如海豚湾厉害
