### ISSUE TITLE
Trimepay支付成功，回调报错！而且日志不停的报错，一直刷！

### ISSUE THREAD

**Issue by cmtomkan310** [ssrpanel/SSRPanel#1193]
![image](https://user-images.githubusercontent.com/38905231/50427789-2a358c80-08eb-11e9-88a6-ab67d2397f6e.png)

**Comment by cmtomkan310** [comment]
没人有这个问题吗？

**Comment by cmtomkan310** [comment]
![image](https://user-images.githubusercontent.com/38905231/50538561-60556380-0bac-11e9-8801-b78015c3abb3.png)

**Comment by cmtomkan310** [comment]
![image](https://user-images.githubusercontent.com/38905231/50538612-de196f00-0bac-11e9-987b-a86ae0f87f24.png)

**Comment by cmtomkan310** [comment]
这个应该很清楚了吧！订单号对的上，已经付款成功，但是后台还是报错！

**Comment by 329928** [comment]
同，解决了吗。
我暂时用回有赞云了，等问题解决

**Comment by DreamSeekerKaiser** [comment]
你们的支付渠道怎么匿名收款的啊
