### ISSUE TITLE
更新后节点正常，客户端节点显示不全

### ISSUE THREAD

**Issue by kk2007yx** [ssrpanel/SSRPanel#1194]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
昨天更新，一切正常，但就是节点显示不全，我有8个节点，但客户端只有5个，更新多次还是一样，单独扫码添加也是毫无反应，pc客户端也是一样。

**Comment by mzfqy** [comment]
系统设置里面有显示订阅节点的数量
