### ISSUE TITLE
有赞云微小店不能授权有赞云了

### ISSUE THREAD

**Issue by littlesker** [ssrpanel/SSRPanel#1197]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
之前有一个有赞云应用，手贱给删了，然后再也不能申请了，必须有赞云店铺才行

**Comment by JMVoid** [comment]
全面凉了。就算前面有店铺，没有实名也不能创建应用的。就算创建过会失效的。建议关了issue吧

**Comment by littlesker** [comment]
@JMVoid 是啊，我就说怎么不能支付回调，然后就准备重新创建，然后就凉凉了！

**Comment by cmtomkan310** [comment]
换Trimepay吧！感觉还可以！

**Comment by mzfqy** [comment]
希望增加码支付。。

**Comment by yongjie0203** [comment]
我这边一直在用有赞微小店，今天还可以成功支付。登录有赞云无法管理之前创建的应用。必须验证邮箱和实名制。不清楚以后会怎么样。

**Comment by cmtomkan310** [comment]
有赞体现太慢，3天

**Comment by 13221253358** [comment]
Trimepay支付不能截图扫码支付，免费大大更新下Trimepay版本

**Comment by ssrpanel** [comment]
那就实名呗。怕啥？

**Comment by ssrpanel** [comment]
我早就在tg频道里发过消息了，N天以前
