### ISSUE TITLE
统计问题

### ISSUE THREAD

**Issue by samac08** [ssrpanel/SSRPanel#1200]
更新到最新版本后 发现节点那里使用统计,节点的月统计都无数据了0. 日小时统计数据都正常.定时任务也正常没有问题,
1. 节点总量统计数据为0字节 2. 单节点查看里面小时统计数据也正常,月统计无数据  3.30日及总消耗总数据也没有+数据  ,4. 控制中心总消耗的统计数据应该=流量日志里面的总合计吧.这个应该没问题的. 用户那个统计还有比例问题,并不是实际的消耗.不纠结了. 
备注: 用户流量使用记录也是正常的 并且小时统计也是正常的 排除不统计当天问题不止一天了
<img src="https://s1.ax1x.com/2018/12/27/FRpObQ.png" alt="FRpObQ.png" border="0">
<img src="https://s1.ax1x.com/2018/12/27/FRpLDg.png" alt="FRpLDg.png" border="0">
<img src="https://s1.ax1x.com/2018/12/27/FRC8yT.png" alt="FRC8yT.png" border="0" />
<img src="https://s1.ax1x.com/2018/12/27/FRpHv8.png" alt="FRpHv8.png" border="0">

**Comment by ssrpanel** [comment]
先看/logs 系统日志，盯一会看日志刷不刷，如果不刷肯定是定时任务挂了，检查一下文件夹权限，是不是更新了之后用户组变了

**Comment by samac08** [comment]
log都是正常的 显示正常的定时日志, 确认过所有有可能的问题无解. 现在重新纯净部署了一下 明天再观察下结果

**Comment by samac08** [comment]
> 先看/logs 系统日志，盯一会看日志刷不刷，如果不刷肯定是定时任务挂了，检查一下文件夹权限，是不是更新了之后用户组变了
虎哥 现在已经正常了, 可是又发现新问题了 流量日志所有V2都是按1比例计算的流量.  节点及数据库设置的比例都是正常的 .ssr方面设置比例 .流量比例计算正常 . 还有是在流量记录里面查看的.

**Comment by ssrpanel** [comment]
v2得配置v2得后端

**Comment by samac08** [comment]
> v2得配置v2得后端
虎哥 V2 后端比例也是没有问题的; 所有的配置都保持比例一致  V2就是按照1计算的 ssr就非常正常

**Comment by samac08** [comment]
> v2得配置v2得后端
虎哥可以看下这个图片 
<a href="https://imgchr.com/i/FWnhuj"><img src="https://s1.ax1x.com/2018/12/28/FWnhuj.md.png" alt="FWnhuj.png" border="0" /></a>

**Comment by samac08** [comment]
> v2得配置v2得后端

V2流量比例1 有结论了吗 虎哥 是哪里问题?
