### ISSUE TITLE
ui 遮挡 修复下吧  (更多)下拉菜单

### ISSUE THREAD

**Issue by samac08** [ssrpanel/SSRPanel#1203]
所有 更多 下拉菜单都有遮挡 最后两行基本不可见 或完全遮挡

**Comment by SRCOL** [comment]
手机版正常。。。电脑版就。。。。

**Comment by vft9nesd** [comment]
![image](https://user-images.githubusercontent.com/24932999/50539926-6c98eb00-0bc3-11e9-8ebd-7342e6be905c.png)
蓝搜~
最下方的节点  甚至删不掉
![image](https://user-images.githubusercontent.com/24932999/50539929-8afee680-0bc3-11e9-8424-04d31c70a92e.png)
手机同样如此。。

**Comment by vft9nesd** [comment]
@lordlezehaf

**Comment by ssrpanel** [comment]
修复了，但是在手机下貌似有坑

**Comment by ssrpanel** [comment]
前端弱势啊。。。

**Comment by vft9nesd** [comment]
![image](https://user-images.githubusercontent.com/24932999/50633128-2ce84f80-0f85-11e9-888d-39e7bf1b0b9d.png)

safari正常。。嘿嘿。。页面整体左移

而pc端chrome拉窄窗口，就不行了，点开扩展菜单，页面不能自适应了

**Comment by ssrpanel** [comment]
有前端大佬帮忙解决吗？我前端很弱

**Comment by ssrpanel** [comment]
我想办法换个方案
