### ISSUE TITLE
新首页界面改进

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/ssrpanel#121]
首先赞美一下胖虎的审美；其次说明一下这次修改以后存在的问题；
1.节点ip使用的是网址，也就导致了ip这一条很长；每一个节点框框大小不一后，变的很丑；
2. 节点数量多的话，不会显示全部节点；

大概这样：http://awesomescreenshot.com/09c6eh5cf0

建议：
1. 取消节点ip显示，只显示名称（本来显示那么多看不懂的数字就不美观）；
2.对于机场拥有过多的节点，一页没有显示全部节点；通过限制一页显示数量 ，设立分页。来完善
fa-chevron-left   ←翻页         fa-chevron-right →翻页
3.希望胖虎能适当的将右侧信息空格缩小一点，这样可以留给节点卡片更大的空间，突出重点；

4.还有一点是，胖虎大大好像少做了节点的结算比例显示 这一信息；

**Comment by ssrpanel** [comment]
@ZBrettonYe 我曹。这个涉及css样式，我得改一下。。小屏幕才会酱紫，

**Comment by ZBrettonYe** [comment]
应该不是屏幕的关系，我用的是17寸的屏. 我觉得是我服务器地址用的是网址的问题. 不过我20个节点并没有显示全

**Comment by ZBrettonYe** [comment]
机场有过多的节点，一页没有显示全部节点；因此希望限制一页显示 3x3，设立分页。
通过 下面2个小图标显示
fa-chevron-left 
fa-chevron-right
还是希望胖虎能适当的将右侧信息缩小一点，然后建节点卡片在放大一点，突出重点；

还有一点是，胖虎好像少做了节点的结算比例显示 这一信息；

**Comment by ZBrettonYe** [comment]
个人‘微修’的界面：http://awesomescreenshot.com/0606eh9bd7

大概体现一下，同时感觉左侧列表有点太短了.... 需要适当的放大

**Comment by ZBrettonYe** [comment]
@ssrpanel 有2页的节点，只显示了一页；还有一页不显示了，这个bug很尴尬

**Comment by ZBrettonYe** [comment]
节点列表中的排序 并没有影响到首页上的排序；难道我把数据库玩坏了？

**Comment by ssrpanel** [comment]
@ZBrettonYe 改了一下，那个结算比例不知道应该放在哪个位置比较好。你git pull一下先

**Comment by ssrpanel** [comment]
排序也修正了

**Comment by ZBrettonYe** [comment]
好看多了：http://awesomescreenshot.com/0e36eiih2c
顺便说一下，胖虎桑你用的国旗图标右半透明的白色码；如果需要我可以提供我现在自己在用的图标；

**Comment by ssrpanel** [comment]
@ZBrettonYe 发出来一份啊。

**Comment by ZBrettonYe** [comment]
@ssrpanel http://pan.baidu.com/s/1kUCyXPd
