### ISSUE TITLE
建议数据库里流量记录只记录有流量的

### ISSUE THREAD

**Issue by thaizxj** [ssrpanel/SSRPanel#1210]
才不到一星期这个表就已经高达200多M，打开表后发现记录的是所有用户，不管有没有用都记录了
![nu1gyxp3qs 6bpv1 9b tw](https://user-images.githubusercontent.com/46080660/50543925-eca16e00-0c20-11e9-9fc4-46e759464a24.png)

**Comment by thaizxj** [comment]
我觉得只要记录有使用过的用户即可，没用过的就不要往里面写数据了

**Comment by thaizxj** [comment]
或者加上一个设置，自动清除N个月之前的已用流量信息

**Comment by SRCOL** [comment]
设置里打开“自动清除日志”就会自动清理一个月前的流量日志
