### ISSUE TITLE
怎么解决支付渠道的问题？

### ISSUE THREAD

**Issue by DreamSeekerKaiser** [ssrpanel/SSRPanel#1214]
支付渠道是个大问题如何匿名支付 隐藏身份 那个有赞云也是要身份认证的而且开通费用很贵 各位大佬都是怎么解决的 请指点一下

**Comment by thaizxj** [comment]
TrimePay支付

**Comment by thaizxj** [comment]
> 不知道怎么个流程接入需要提供什么资料以及账户里的钱怎么提到自己的银行卡中 发自我的 iPhone
> […](#)
> 在 2019年1月1日，上午9:36，thaizxj ***@***.***> 写道： TrimePay支付 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

很简单，给80签约，提现到自己支付宝账号

**Comment by ssrpanel** [comment]
准备移除trimepay支付，说好15% aff，结果每笔都是4.9，签约一个80，如果一个站签约支付宝和微信就是80 * 2 = 160，返利应该是24，结果，整整扣的就剩下5都不到。是的，利益矛盾促使我打了一个released，下个版本移除掉trimepay

**Comment by ssrpanel** [comment]
虽然返的利还没有我卖一个号多，但是，这小心眼耍的让人不愉快

**Comment by thaizxj** [comment]
刚买trimepay。。。别啊

**Comment by thaizxj** [comment]
有赞现在不能绑定小店了，只能绑收费的微商城，取消了trimepay，就不知道用啥了 @ssrpanel

**Comment by vft9nesd** [comment]
我的怎么还能用？我也没实名啊

**Comment by thaizxj** [comment]
@vft9nesd 你可以新建一个就知道了

**Comment by vft9nesd** [comment]
酱紫，我用的原来的，不影响吧？

**Comment by victoryLV** [comment]
可以试试码支付

**Comment by cyanogenic** [comment]
> 准备移除trimepay支付，说好15% aff，结果每笔都是4.9，签约一个80，如果一个站签约支付宝和微信就是80 * 2 = 160，返利应该是24，结果，整整扣的就剩下5都不到。是的，利益矛盾促使我打了一个released，下个版本移除掉trimepay

应该已经有不少人买了TrimePay了，可以等一段时间再移除呀

**Comment by DreamSeekerKaiser** [comment]
看来只能买三件套 自己走paypai 类型的支付了 难受 没有支付渠道卡老久了

**Comment by DreamSeekerKaiser** [comment]
谁有三件套 介绍一下啦

**Comment by vft9nesd** [comment]
各种三件套多了去了，就看跑不跑路了，你已经做好跑路的准备了，三件套也在准备跑路和正在跑路的路上了~ :)

**Comment by SRCOL** [comment]
像trimepay这种支付平台太多了，根本就不靠谱的，个人建议还是有赞云+三件套微信
