### ISSUE TITLE
中转与客户端

### ISSUE THREAD

**Issue by mzfqy** [ssrpanel/SSRPanel#1215]
https://github.com/mzfqy/OneClickSsr-ssrpanel/raw/master/iptables.sh
中转用的这个脚本，还不错，就是没有节点信息展示。
另外，发现个定制版的安卓v2app，希望有dalao修改支持ssrpanel造福大家。
https://github.com/leslieee/v2rayNG

**Comment by ssrpanel** [comment]
谢谢

**Comment by ssrpanel** [comment]
我用了逗比的haproxy一键，非常的好用
