### ISSUE TITLE
能否让用户看到所有节点

### ISSUE THREAD

**Issue by 329928** [ssrpanel/SSRPanel#1217]
让用户看到属于他标签外的节点，但是隐藏配置信息或者提示无权限查看。

**Comment by ssrpanel** [comment]
自己改啊，很简单的

**Comment by yidaoqingcheng** [comment]
个人觉得完全没有必要 做个开关还差不多 开启强烈影响运营 而且如果有人要d你节点 这样一次jiund完

**Comment by yidaoqingcheng** [comment]
别想着这样能吸引用户购买，该买的会买，不会买的依然不会买

**Comment by ssrpanel** [comment]
@yidaoqingcheng 对头！

**Comment by Losgif** [comment]
说简单也不简单，关键信息要隐藏。这个功能我写过，我写了个transform类(受大佬启发)。隐藏IP、密码、端口等敏感信息，转换后再传给blade，代码也就百来行。
