### ISSUE TITLE
转一个bbr，效果好像和kcp一样？

### ISSUE THREAD

**Issue by vft9nesd** [ssrpanel/SSRPanel#1218]
![image](https://user-images.githubusercontent.com/24932999/50625537-c7379b80-0f63-11e9-8553-8cc7eae7280b.png)
这个是一个日本vultr  联通延迟200ms+   以前的bbr速度跑不起来 顶多5m/s  非常的蛋疼  开个这个牛逼的bbr  瞬间神清气爽了~
https://github.com/cx9208/bbrplus
试试吧~

**Comment by niyeyeqi** [comment]
有丶东西

**Comment by ssrpanel** [comment]
赞！！！刚好v2ray用
