### ISSUE TITLE
关于现有支付平台的看法和建议！

### ISSUE THREAD

**Issue by cmtomkan310** [ssrpanel/SSRPanel#1224]
标题很明确了，目前取消trimepay支付，不知道为什么？之前推出的时候，直接和微信和支付宝签署协议付款158元，现在无故就取消了，哪怕说出为什么！

有赞支付还是比较稳定，手续费不算高，而且手机有app可随时查收账目，但体现至少3天，有的时候可以碰到1天到账，但是几率极地，最大问题就是实名了，但是昨天取消trimepay后，我登录有赞，实名又取消了。不知道为什么！

支付宝国际版，这个东西压根没告诉怎么用，虽然提供了几个参数，但根本不知道这些参数是通过申请哪个出来的。我也试着申请了一下，需要什么商业机构码之类的。。。我觉得适当给出教程，哪怕文字也好，并大概说和其他2家的优劣势会更好。

**Comment by ssrpanel** [comment]
https://github.com/ssrpanel/SSRPanel/issues/1214

**Comment by 329928** [comment]
有赞18点以前提现，次日2点到

**Comment by jiangjiang5733** [comment]
一次提现1000之内，18点之前发起，次日4点之前到账。
大佬钱多，分几次999提现就好
