### ISSUE TITLE
偶然发现一个支付渠道

### ISSUE THREAD

**Issue by fyshaw** [ssrpanel/SSRPanel#1229]
事情是这样的：寻找支付渠道的时候发现一个支付渠道聚合论坛  https://paybase.cn/all?page=2
然后在这个论坛上发现了paymentwall中文名支付强，支持梯子商家，支持支付宝，见图片
![img_2894](https://user-images.githubusercontent.com/46097804/50731579-80d07f80-11a3-11e9-940d-e05001c101bc.jpg)
![img_2903](https://user-images.githubusercontent.com/46097804/50731580-81691600-11a3-11e9-8ea1-28a2a72558c1.jpg)

**Comment by ssrpanel** [comment]
marked

**Comment by vft9nesd** [comment]
![image](https://user-images.githubusercontent.com/24932999/50732366-8b474500-11b4-11e9-9c93-c3f7635456fa.png)
paymentwall要上传资料呢？

**Comment by mzfqy** [comment]
支付宝当面付好像很容易申请

**Comment by vft9nesd** [comment]
> 支付宝当面付好像很容易申请

当面付就是门店扫码啊

**Comment by mzfqy** [comment]
魔改版的有这个。。。。不知道怎么描述。。支付宝官方通知的

**Comment by vft9nesd** [comment]
我记得很早之前申请过api
![image](https://user-images.githubusercontent.com/24932999/50735126-581caa00-11e4-11e9-9186-a35f2787cdec.png)
这里显示需签约，再点进去
![image](https://user-images.githubusercontent.com/24932999/50735137-71255b00-11e4-11e9-8f46-cf327e02674e.png)

**Comment by vft9nesd** [comment]
https://openhome.alipay.com/platform/appManage.htm#/apps

**Comment by vft9nesd** [comment]
![image](https://user-images.githubusercontent.com/24932999/50735193-b8f8b200-11e5-11e9-8ea4-67a7ea7265d3.png)

**Comment by mzfqy** [comment]
二手鱼搜下。有人20多代开

**Comment by vft9nesd** [comment]
这么骚吗
