### ISSUE TITLE
针对节点限速需求

### ISSUE THREAD

**Issue by Live520** [ssrpanel/ssrpanel#123]
目前ssrpanel是在帐号里面设置端口限速的。
但是如果有多个节点，例如A节点加速游戏，B节点看视频，帐号里面端口限速之后，B节点就没办法用了。
希望可以在节点里面对连接的端口进行限速，而不是在帐号里面设置。

还有就是节点的国家图片没有自动匹配！

**Comment by cheapssr** [comment]
其实节点国际不需要自动匹配，最好是可以手动选择，，广播ip有时候蛋疼。

**Comment by ssrpanel** [comment]
@cheapssr 有道理
@Live520 不自动匹配，就是要让你手动选，因为你添加节点的时候必定是知道这个节点是哪个国家的。
账号限速的那个其实还是假的，我预留的，目前我在寻求办法搞定这个针对每个账号的限速。不想用魔改的那种radius，因为后端是完全破娃原版的ssr 3.4，所以也没有魔改的特殊功能
