### ISSUE TITLE
有2个很神奇的问题，一个后端可以同时给几个前端使用么？

### ISSUE THREAD

**Issue by DizzlyLee** [ssrpanel/SSRPanel#1230]
1.一个后端可以同时给2个前端使用么？
2.想转移前端面板到另外服务器的流程？
求大佬指导，或者发个wifk。

**Comment by DizzlyLee** [comment]
> 1.可以
> 2.只把数据库弄过去就可以
@mzfqy 
1，求方法，如何配置。。
2，蛋疼的是bt面板备份的时候前面带.的文件夹都不会被打包。。。

**Comment by mzfqy** [comment]
1数据库导出
2新机子重新搭建
3导入数据库

**Comment by DizzlyLee** [comment]
> 1数据库导出
> 2新机子重新搭建
> 3导入数据库
@mzfqy 
大佬那个我理解了，我想问的是，一个后端可以同时给2个前端这个。。

**Comment by mzfqy** [comment]
监听的端口不同就可以了

**Comment by vft9nesd** [comment]
开两个进程不就好了

**Comment by DizzlyLee** [comment]
不是两套面板一个数据库。是两套各自的面板，用同一个后端。

**Comment by ssrpanel** [comment]
答案是no

**Comment by mzfqy** [comment]
@ssrpanel 可以的呢，删掉logrun.sh里面的先杀死进程cp一份到另外一个文件夹 然后删掉logrun.sh里面的先杀死进程，然后设置数据库信息
只要两个前端的用户的端口没有重复的就不会有什么错误

**Comment by ssrpanel** [comment]
这样做有什么意义吗？

**Comment by vft9nesd** [comment]
你可以写个脚本，2个数据库user合并新表，后端来连接新表，可以共用端口

**Comment by mzfqy** [comment]
可能穷。。。合租吧

**Comment by yongjie0203** [comment]
> 你可以写个脚本，2个数据库user合并新表，后端来连接新表，可以共用端口

这样更新用户使用量没法更新

**Comment by mzfqy** [comment]
还是闲的慌。。。

**Comment by DizzlyLee** [comment]
> 如果我没猜错，这种做法，就是为了站点去推广，好比他可以制作10个站点，但是后端只有一套，这种一看就是想在商用上动脑筋！

还是大佬了解我。。就是这个意思
