### ISSUE TITLE
【异常】自动关闭超时未支付订单：ErrorException: Trying to get property 'coupon_id' of non-object  in /www/wwwroot/ssrpanel/app/Console/Commands/AutoJob.php:500

### ISSUE THREAD

**Issue by banxianl08** [ssrpanel/SSRPanel#1231]
【异常】自动关闭超时未支付订单：ErrorException: Trying to get property 'coupon_id' of non-object 
in /www/wwwroot/ssrpanel/app/Console/Commands/AutoJob.php:500

求大佬解决

**Comment by ssrpanel** [comment]
多久没更新了？order表结构里少了coupon_id字段

**Comment by banxianl08** [comment]
@ssrpanel  求破啊，大佬

**Comment by banxianl08** [comment]
@ssrpanel   大佬帮帮我啊，怎么解决
