### ISSUE TITLE
求大佬帮忙

### ISSUE THREAD

**Issue by banxianl08** [ssrpanel/SSRPanel#1232]
【异常】自动关闭超时未支付订单：ErrorException: Trying to get property 'coupon_id' of non-object 
in /www/wwwroot/ssrpanel/app/Console/Commands/AutoJob.php:500
Stack trace:
#0 /www/wwwroot/ssrpanel/app/Console/Commands/AutoJob.php(500): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/www/wwwroot/ss...', 500, Array)
#1 /www/wwwroot/ssrpanel/app/Console/Commands/AutoJob.php(74): App\Console\Commands\AutoJob->closeOrders()
#2 [internal function]: App\Console\Commands\AutoJob->handle()
#3 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#4 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#6 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#7 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#8 /www/wwwroot/ssrpanel/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#9 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#10 /www/wwwroot/ssrpanel/vendor/symfony/console/Application.php(953): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /www/wwwroot/ssrpanel/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\AutoJob), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /www/wwwroot/ssrpanel/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /www/wwwroot/ssrpanel/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 {main}

**Comment by banxianl08** [comment]
不自动关闭未支付订单了，定时任务稳定运行1年，求大佬帮忙

**Comment by banxianl08** [comment]
有偿解决， 我的tg  @Banxianl

**Comment by yongjie0203** [comment]
建议修改代码app/Console/Commands/AutoJob.php  498行增加
$order = Order::query()->where('oid', $payment->oid)->get()->first();
退回优惠券部分500 - 503 行
$payment->order->coupon_id 改为$order->coupon_id

**Comment by yongjie0203** [comment]
也可尝试 ：退回优惠券部分500 - 503 行  $payment->order->coupon_id 改为$payment->**order()**->coupon_id

**Comment by banxianl08** [comment]
感谢大佬回复，我试试看@yongjie0203

**Comment by yongjie0203** [comment]
我是小白
