### ISSUE TITLE
v2ray ws+tls+web连接问题求教

### ISSUE THREAD

**Issue by fyshaw** [ssrpanel/SSRPanel#1238]
问题背景：go版本v2ray一键脚本部署后端为WebSocket+TLS+Web，v2ray后端监听10086端口，路径为/v2ray，web伪装服务使用caddy监听443端口，转发v2ray流量至10086端口

问题详述：
shadowrocket扫码添加节点（443端口）无法连接，但浏览器访问节点网址显示2048小游戏一切正常。
所有配置不变，仅把客户端端口改为10086，连接正常还看了一会youtube，再改回443又连不上。感觉问题出在caddy忙活一天排错无果，请问各位大佬何解？

其他信息：前端vps：ggccloud centos7 已关闭所有防火墙；节点vps：onevps 新加坡 centos7 已关闭所有防火墙；节点一键脚本采用阿拉凹凸曼的

前端配置
![2019-01-09 23 01 32](https://user-images.githubusercontent.com/46097804/50907658-e1411480-1462-11e9-9874-549d54052d4a.png)

caddy配置：
www.apple.com { #假装我的域名
  root /srv/www
  tls google@gmail.com #假装我的邮箱
  gzip
  timeouts none
  proxy /v2ray 127.0.0.1:10086 {
    websocket
    header_upstream -Origin
  }
}

v2ray配置：
{
  "log": {
    "loglevel": "error"
  },
  "api": {
    "tag": "api",
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ]
  },
  "stats": {},
  "inbounds": [
    {
    "listen": "127.0.0.1",
    "port": 10085,
    "protocol": "dokodemo-door",
    "settings": {
      "address": "127.0.0.1"
    },
    "tag": "api"
    },
    {
      "listen": "0.0.0.0",
       "tag": "proxy",
      "port": 10086,
      "protocol": "vmess",
      "settings": {
        "clients": [],
        "disableInsecureEncryption": true,
        "default": {
          "level": 0,
          "alterId": 16
        }
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/v2ray"
        }
      }
    }
  ],
  "outbounds": [{
    "protocol": "freedom"
  }],
  "routing": {
    "rules": [{
      "type": "field",
      "inboundTag": [ "api" ],
      "outboundTag": "api"
    }],    
    "strategy": "rules"
  },
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  },

  "ssrpanel": {
    // Node id on your SSR Panel
    "nodeId": 2,
    // every N seconds
    "checkRate": 300,
    // user config
    "user": {
      // inbound tag, which inbound you would like add user to
      "inboundTag": "proxy",
      "level": 0,
      "alterId": 16,
      "security": "none"
    },
    // db connection
    "mysql": {
      "host": "192.168.1.1",  #假装前端ip
      "port": 3306,
      "user": "ssrpanel",  #假装数据库用户名
      "password": "password", #假装数据库密码
      "dbname": "ssrpanel" #假装数据库名称
    }
  }
}

**Comment by ssrpanel** [comment]
V2RAY WS我还没有成功过，等我研究一下放出教程

**Comment by zhouguangyou1994** [comment]
把伪装域名填进去就OK了

**Comment by fyshaw** [comment]
> 把伪装域名填进去就OK了

实测：不行
把centos7换成ubuntu16也不行，我感觉问题出在caddy反代，要么caddy发不出去流量，要么v2ray接收不到

**Comment by mlch911** [comment]
我用的ssrpanel-be，用他写的docker成功实现v2+ws+tls，在windows上和安卓上没问题。
但ios上用shadowraocket需要将算法改为aes-128-gcm（试了好久才发现这样能用）
在macOS上的客户端感觉都有bug，时好时坏，比较迷……

请教一下如何在订阅内容里加上算法的信息？另外有没有老哥在macOS上有推荐的v2ray软件的啊？

**Comment by yjj618** [comment]
作者有说不支持80/443端口
