### ISSUE TITLE
v2ray节点设置0:0流量比例没用，@aiyahacke @Bruskyii Panda

### ISSUE THREAD

**Issue by fjfkg** [ssrpanel/SSRPanel#1239]
![1](https://user-images.githubusercontent.com/45324758/50909304-89a4a800-1466-11e9-883d-516e87894631.png)
![2](https://user-images.githubusercontent.com/45324758/50909336-988b5a80-1466-11e9-83ed-4410043aa75a.png)
![3](https://user-images.githubusercontent.com/45324758/50909358-a0e39580-1466-11e9-93ef-7f99f5fef7e2.png)

**Comment by ssrpanel** [comment]
????????????????????????????

**Comment by fjfkg** [comment]
流量比例不能设置为0，没用
