### ISSUE TITLE
如何防止下三滥CC你的站点 - 管理员请移动到wiki

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#124]
昨天发现站点首页静态文件正常,但是面板进不去. 发了ticket问了vultr说是没问题,再看看couldflare, 尝试的调整了一些设置,短时间正常了,后来又不行了,就怀疑被攻击了.

输入下面命令后发现不少连接超过100,最高1万都有,,去看了下nginx日志,都有2G大了,大概明白了有人攻击
netstat -nat|grep -i '80'|wc -l  
对连接的IP按连接数量进行排序  
netstat -ntu | awk '{print $5}' | cut -d: -f1 | sort | uniq -c | sort -n  
查看TCP连接状态 

由于是免费机场,拿来玩玩,所以懒癌发作,加上其他工作,东扯西扯,七八个小时后才开始动手,nignx日志已经4.5G大小了.

百度了下一大堆ban cc的 shell, 测试了下, 最终用了张戈的这个脚本并设置连接超过10就banned时间600000000000秒,搞定.   https://zhangge.net/5066.html  

git地址:https://github.com/jagerzhang/CCKiller

vultr的机器还是不错, 负载最高达到80了,仍然没死, 懒癌的代价是流量被消耗了差不多30G,就当喂狗了...

大流量的DDOS仍然无法防备, 虽然用了CLOUDFLARE, 当然DDOS是有成本的, 最多我关站不玩, 但是DDOS暴露出来的肉鸡就值不少钱了,特别在这个360基本每台都装的情况的.

建议主站转完后只打开相关端口,
firewall-cmd --zone=public --add-port=80/tcp --permanent  
firewall-cmd --zone=public --add-port=443/tcp --permanent  
firewall-cmd --zone=public --add-port=8888/tcp --permanent  
firewall-cmd --zone=public --add-port=3306/tcp --permanent  
firewall-cmd --zone=public --add-port=22/tcp --permanent  
firewall-cmd --permanent --zone=public --add-port=10000-20000/tcp

重新载入
firewall-cmd --reload
查看
firewall-cmd --zone= public --query-port=80/tcp

**Comment by 1021435278** [comment]
刚最高负载达到130,我日....... 张戈的脚本不起作用, 手动ban掉一些机器, 最多人累点啦.......遇到狗是没办法的.

有些ip是在大陆的,某天我要搞个陷阱,整不死那小子.

**Comment by ssrpanel** [comment]
已加wiki
