### ISSUE TITLE
发个vultr网络测试图，送给没钱买服务器的人

### ISSUE THREAD

**Issue by vft9nesd** [ssrpanel/SSRPanel#1240]
![_20190110021736](https://user-images.githubusercontent.com/24932999/50919613-3b9b9e80-147e-11e9-9651-fb2b80b8875b.jpg)

**Comment by vft9nesd** [comment]
一键ping脚本，保存为bat运行

> echo 01 Tokyo
ping hnd-jp-ping.vultr.com -n 3
echo=
echo =============================
echo 02 Singapore
ping sgp-ping.vultr.com -n 3
echo=
echo =============================
echo 03 Amsterdam
ping ams-nl-ping.vultr.com -n 3
echo=
echo =============================
echo 04 Paris
ping par-fr-ping.vultr.com -n 3
echo=
echo =============================
echo 05 Frankfurt
ping fra-de-ping.vultr.com -n 3
echo=
echo =============================
echo 06 London
ping lon-gb-ping.vultr.com -n 3
echo=
echo =============================
echo 07 New York
ping nj-us-ping.vultr.com -n 3
echo=
echo =============================
echo 08 Chicago
ping il-us-ping.vultr.com -n 3
echo=
echo =============================
echo 09 Dallas
ping tx-us-ping.vultr.com -n 3
echo=
echo =============================
echo 10 Atlanta
ping ga-us-ping.vultr.com -n 3
echo=
echo =============================
echo 11 Los Angeles
ping lax-ca-us-ping.vultr.com -n 3
echo=
echo =============================
echo 12 Miami
ping fl-us-ping.vultr.com -n 3
echo=
echo =============================
echo 13 Seattle
ping wa-us-ping.vultr.com -n 3
echo=
echo =============================
echo 14 Silicon Valley
ping sjo-ca-us-ping.vultr.com -n 3
echo=
echo =============================
echo 15 Sydney
ping syd-au-ping.vultr.com -n 3
echo=
pause

**Comment by ssrpanel** [comment]
666

**Comment by mzfqy** [comment]
哪里有卖vu号的

**Comment by ssrpanel** [comment]
@mzfqy 为什么要卖vu号？自己注册不行吗

**Comment by ssrpanel** [comment]
在我看来，vultr被小白草烂了。
