### ISSUE TITLE
工单有bug

### ISSUE THREAD

**Issue by 928net** [ssrpanel/SSRPanel#1241]
1. 客户发送工单 -> 后台显示待处理
2. 管理员回复后 -> 显示已处理
3. 客户再次回复，应该显示 待处理 。可是一直显示 已处理 ！

如果不是有微信或者邮件提醒，根本发现不了用户回复了。

查看用户控制器里的回复工单，并没有修改状态的代码。

![image](https://user-images.githubusercontent.com/46510615/50947645-248a9a00-14da-11e9-83f5-4cf76e7261d7.png)
另外如果切换到用户回复工单界面，编辑器在切换身份的上面。

**Comment by ssrpanel** [comment]
修复了
