### ISSUE TITLE
听从召唤而来

### ISSUE THREAD

**Issue by 110560** [ssrpanel/SSRPanel#1242]
当前版本存在下面三个影响使用的问题。
一：安卓端的谷歌浏览器 点击用户管理   点操作  目前是卡死状态，只能点网页版使用。
二：面板的流量比例计算有问题，当流量比例小于1，流量日志记录为零，面板是最新版本，后端是使用你的ssrr后端
三：节点里面的节点分组问题
节点管理里面的节点分组
创建两个分组之后，路由器端只能读取一个分组  并且会删除另外一个分组的节点，sstap里面分组是正常的，问题目前出现于  软路由的客户端，以及梅林固件的客户端
再显方式，  节点分组  至少两组。 包含不同的服务器，采用路由器固件订阅   会下载所有的节点 然后再删除其中一个分组的节点  

我提得很清楚了，谢谢胖虎兄，23333
看了你这边提问的 可怕  质量堪忧。
中间有问题询问我，请联系tg杜若

**Comment by ssrpanel** [comment]
一暂时无解，我前端比较菜
二用我发布好的released版，目前那个由 @pch18 大佬维护，我python基本维护不来
三无法处理，客户端问题，就跟C#破娃最后一个版本一摸一样，那些订阅应该由客户端来处理分组，你看Quantuantl就处理的很好

**Comment by ssrpanel** [comment]
一我用iPhone safari下正常

**Comment by 110560** [comment]
@ssrpanel    一般首先测试谷歌浏览器  233333  希望有大佬出来改改。。
后端的话，我到时候有空再去改一下吧。你把你发行版的那个链接发一下，我去更新下
第三个问题 ，我发到了梅林固件社区  希望他们能解决下

**Comment by ssrpanel** [comment]
@110560 
服务端用这个：https://github.com/ssrpanel/shadowsocksr/archive/V3.2.2.tar.gz
