### ISSUE TITLE
v2ray kcp 无法读取流量信息

### ISSUE THREAD

**Issue by garhing** [ssrpanel/SSRPanel#1243]
{
  "log": {
    "loglevel": "debug"
  },
  "api": {
    "tag": "api",
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ]
  },
  "stats": {},
  "inbounds": [
    {
    "listen": "127.0.0.1",
    "port": 10087,
    "protocol": "dokodemo-door",
    "settings": {
      "address": "127.0.0.1"
    },
    "tag": "api"
    },
    {
      "tag": "proxy",
      "port": 10086,
      "protocol": "vmess",
      "settings": {
        "clients": [],
        "disableInsecureEncryption": true,
        "default": {
          "level": 0,
          "alterId": 16
        }
      },
      "streamSettings":{
      "network":"kcp",
      "kcpSettings": {
        "mtu": 1350,
        "tti": 20,
        "uplinkCapacity": 5,
        "downlinkCapacity": 100,
        "congestion": false,
        "readBufferSize": 1,
        "writeBufferSize": 1,
        "header": {
          "type": "none"
        }
      }
    }
    }
  ],
  "outbounds": [{
    "protocol": "freedom"
  }],
  "routing": {
    "rules": [{
      "type": "field",
      "inboundTag": [ "api" ],
      "outboundTag": "api"
    }],    
    "strategy": "rules"
  },
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  },

  "ssrpanel": {
    "nodeId": 2,
    // every N seconds
    "checkRate": 300,
    // user config
    "user": {
      // inbound tag, which inbound you would like add user to
      "inboundTag": "proxy",
      "level": 0,
      "alterId": 16,
      "security": "none"
    },
    // db connection
    "mysql": {
      "host": "127.0.0.1",
      "port": 3306,
      "user": "ssrpanel",
      "password": "ssrpanel",
      "dbname": "ssrpanel"
    }
  }
}

**Comment by ssrpanel** [comment]
V2 go插件作者复活，等一阵子
