### ISSUE TITLE
v2ray的连接问题

### ISSUE THREAD

**Issue by mlch911** [ssrpanel/SSRPanel#1247]
我用的[ssrpanel-be](https://github.com/kszym2002/ssrpanel-be)，用他写的docker成功实现v2+ws+tls，在windows上和安卓上没问题。
但ios上用shadowraocket需要将算法改为aes-128-gcm（试了好久才发现这样能用）
在macOS上的客户端感觉都有bug，时好时坏，比较迷……

请教一下如何在订阅内容里加上算法的信息？另外有没有老哥在macOS上有推荐的v2ray软件的啊？

**Comment by mzfqy** [comment]
可以用新的那个go的版本挺不错的

**Comment by ssrpanel** [comment]
@mlch911 ssrpanel-be 项目里有一个go版的分支。注意看
