### ISSUE TITLE
节点流量统计异常问题

### ISSUE THREAD

**Issue by yongjie0203** [ssrpanel/SSRPanel#1248]
看情况，晚上23:55分只会把状态为1的节点流量使用情况插入表中，第二天早上9点也只是 状态为1的节点发送状态流量试用状态报告，这期间节点有变化的可能。如果这期间节点状态由不为1更新为1，发送流量状态报告时可能会因没有查询到数据而造成异常。

**Comment by ssrpanel** [comment]
前两天定时任务GG了，修复了，再试试？
