### ISSUE TITLE
一键安装SSRpanel，一键安装v2ray和ssrr脚本

### ISSUE THREAD

**Issue by Andyanna** [ssrpanel/SSRPanel#1249]
一键安装SSRpanel，一键安装并对接v2ray和ssrr
安装脚本wget --no-check-certificate http://www.berryphone.club/raspanel &&chmod +x raspanel&&./raspanel

**Comment by cmmdwl** [comment]
这个代码不提供源码么？

**Comment by Andyanna** [comment]
就加了个壳，防小白的

**Comment by ssrpanel** [comment]
@Andyanna 很棒呀，不过软件源里都没有东西，我脱壳完看了一下代码，很棒
tg号留下来吧，我邀请你进来交流啊

**Comment by ssrpanel** [comment]
@cmmdwl 加了壳了。代码我看了，很棒的

**Comment by Andyanna** [comment]
@ssrpanel 我的tg号@Andymurong

**Comment by Vikttttor** [comment]
> 一键安装SSRpanel，一键安装并对接v2ray和ssrr
> 安装脚本wget --no-check-certificate http://www.berryphone.club/raspanel &&chmod +x raspanel&&./raspanel

马克。
