### ISSUE TITLE
节点排序bug

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/ssrpanel#125]
节点设置中设置了的节点的排序顺序，当时首页的节点信息还是按照了节点添加顺序排列；

**Comment by ssrpanel** [comment]
@ZBrettonYe 已修复，git pull一下

**Comment by 828768** [comment]
@ssrpanel 胖虎哥，最新版这个排序又是按添加顺序来的，而且更新订阅节点并不是随机取设定的个数，取的是前3个
