### ISSUE TITLE
GO版一键包,安装成功没有报错，连不上

### ISSUE THREAD

**Issue by yjj618** [ssrpanel/SSRPanel#1252]
![1](https://user-images.githubusercontent.com/42506350/51086021-25425b00-177c-11e9-9822-cc619ff8a142.jpg)

**Comment by yjj618** [comment]
![1547387075 1](https://user-images.githubusercontent.com/42506350/51086039-75b9b880-177c-11e9-891f-c948eb319632.jpg)

**Comment by yjj618** [comment]
2048游戏页面能打开

**Comment by yjj618** [comment]
![1547387186 1](https://user-images.githubusercontent.com/42506350/51086059-b31e4600-177c-11e9-9223-c2d686119bd8.jpg)

**Comment by yjj618** [comment]
还有脚本里数据库端口错了成了数据库名字了

**Comment by mzfqy** [comment]
服务器配置文件呢

**Comment by yjj618** [comment]
{
  "log": {
    "loglevel": "debug"
  },
  "api": {
    "tag": "api",
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ]
  },
  "stats": {},
  "inbounds": [
    {
    "listen": "127.0.0.1",
    "port": 10087,
    "protocol": "dokodemo-door",
    "settings": {
      "address": "127.0.0.1"
    },
    "tag": "api"
    },
    {
      "tag": "proxy",
      "port": 10086,
      "protocol": "vmess",
      "settings": {
        "clients": [],
        "disableInsecureEncryption": true,
        "default": {
          "level": 0,
          "alterId": 16
        }
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/game"
        }
      }
    }
  ],
  "outbounds": [{
    "protocol": "freedom"
  }],
  "routing": {
    "rules": [{
      "type": "field",
      "inboundTag": [ "api" ],
      "outboundTag": "api"
    }],
    "strategy": "rules"
  },
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  },

  "ssrpanel": {
    // Node id on your SSR Panel
    "nodeId": 3,
    // every N seconds
    "checkRate": 300,
    // user config
    "user": {
      // inbound tag, which inbound you would like add user to
      "inboundTag": "proxy",
      "level": 0,
      "alterId": 16,
      "security": "none"
    },
    // db connection
    "mysql": {
      "host": "x.x.x.x",
      "port": 3360,
      "user": "xxxx",
      "password": "xxxx",
      "dbname": "xxxx"
    }
  }
}

**Comment by yjj618** [comment]
感谢大佬，搞明白了是/game路径的流量转发到了10086端口

**Comment by ssrpanel** [comment]
不要关闭，容我试试

**Comment by yjj618** [comment]
面板机安装报错，其他正常
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/usr/lib/systemd/system/caddy.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2019-01-15 13:55:43 CST; 4s ago
     Docs: https://caddyserver.com/docs
  Process: 30965 ExecStart=/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp (code=exited, status=1/FAILURE)
 Main PID: 30965 (code=exited, status=1/FAILURE)

Jan 15 13:55:38 host.localdomain caddy[30965]: Activating privacy features... 2019/01/15 13:55:38 [IN...com
Jan 15 13:55:43 host.localdomain caddy[30965]: 2019/01/15 13:55:43 [INFO][xxxx.xx] acme: Obtain...ate
Jan 15 13:55:43 host.localdomain caddy[30965]: 2019/01/15 13:55:43 [INFO][xxxx.xx] AuthURL: htt...Dj4
Jan 15 13:55:43 host.localdomain caddy[30965]: 2019/01/15 13:55:43 [INFO][xxxx.xx] acme: Could ...-01
Jan 15 13:55:43 host.localdomain caddy[30965]: 2019/01/15 13:55:43 [INFO][xxxx.xx] acme: Could ...-01
Jan 15 13:55:43 host.localdomain caddy[30965]: 2019/01/15 13:55:43 [INFO][xxxx.xx] acme: Trying...-01
Jan 15 13:55:43 host.localdomain caddy[30965]: 2019/01/15 13:55:43 [xxxx.xx] failed to get cert...use
Jan 15 13:55:43 host.localdomain systemd[1]: caddy.service: main process exited, code=exited, status...LURE
Jan 15 13:55:43 host.localdomain systemd[1]: Unit caddy.service entered failed state.
Jan 15 13:55:43 host.localdomain systemd[1]: caddy.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by TBQin** [comment]
借楼问一下GO版的SS 怎么对接 按照教程已经运行，但是面板还是宕机

**Comment by sharkyzh** [comment]
> 感谢大佬，搞明白了是/game路径的流量转发到了10086端口

请问下这个端口，面板上填写的443，那么这里是不是也应该填写443，还是应该跟candy代理的端口一样，填写10086

**Comment by ssrpanel** [comment]
@TBQin 因为我没放出完整的脚本包啊

**Comment by ssrpanel** [comment]
你关了就挂了

**Comment by Dennishaha** [comment]
#开机时输入以启动
nohup /root/vnet_linux_amd64 &

**Comment by Dennishaha** [comment]
@ssrpanel 我发现wiki里的ss go 配置后 ios(多客户端测试过)断链，windows 正常
