### ISSUE TITLE
面板限速接口新版怎么没有了。连限速预留接口都去掉了？

### ISSUE THREAD

**Issue by GitH123i** [ssrpanel/SSRPanel#1254]
面板限速接口新版怎么没有了。连限速预留接口都去掉了？

**Comment by ssrpanel** [comment]
待会再放出来，SS GO DB版群里的大佬已经开发完了。哦也

**Comment by GitH123i** [comment]
厉害了。。藕也。

**Comment by mzfqy** [comment]
那个支持单端口多用户吗？@ssrpanel

**Comment by vft9nesd** [comment]
> 那个支持单端口多用户吗？@ssrpanel

不资慈~

**Comment by ntgeralt** [comment]
0308SSRPanel那个限速的，好像ssr后端不管用，请问只支持SS GO吗？
