### ISSUE TITLE
胖虎可否给面板迁移的教程

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#126]
由于CF后的源IP已经暴露,昨天测试了迁移到其它机器但失败了.

请问你可以给些相关教程, 或者直接写个WIKI吗?  谢谢.

**Comment by ZBrettonYe** [comment]
@1021435278 备份数据库，备份网站代码
之后重新搭建的时候用这些 覆盖，就可以了，记得把分节点的数据库地址改一下

**Comment by ssrpanel** [comment]
直接备份数据库再导入到你要搭建的新站点里。
另一个种：看我wiki里那个防CC方案。数据库应该单独一台VPS。至少我是这么做的。

**Comment by 1021435278** [comment]
@ssrpanel 
直接备份数据库再导入到搭建的新站点我测试过不行, 我听某个群友说是GD2的问题,他说他在测试.

关于CC, 这几天遇到好几条疯狗,数据库暂时还没考虑到这方面,那帮傻逼用的是CC你站点动态文件.不过 vultr的小鸡不错,5美金小鸡我优化了, 昨天高达260都没死.

我列了好几个方案, 大概如下还在测试, 稍后更新.

有2个思路:
通过下面查看命令通过脚本判断,只要web连接在30秒超过50的,直接drop且永远写入iptables.
netstat -nat|grep -i '80'|wc -l  对连接的IP按连接数量进行排序  
netstat -ntu | awk '{print $5}' | cut -d: -f1 | sort | uniq -c | sort -n   查看TCP连接状态

第二个思路
通过fail2ban, 只要web连接在30秒超过50的, 直接BAN且永远写入iptables,不再解封.

目前是CC攻击PHP动态文件, 所以同时希望执行第三种脚本并随机启动,条件需要设置严格点
只要web连接在30秒超过300的, 直接停掉 service php-fpm, 然后等待回复正常,即可service php-fpm restart就可以.

**Comment by 1021435278** [comment]
请问以下命令时候仍然需要执行? 还是说按照新站点来, 成功后再导入备份的数据库文件?

php composer.phar install
php artisan key:generate

**Comment by yeehomlee** [comment]
最近在做迁移。
网站文件、数据库都上传覆盖了。
但在ssrpanel后台，
「卡券、用户、节点、设置」是看不到的，
其他的「商品、标签」则是有的。


数据库在导入时，提示：
![screen_20180518_132717](https://user-images.githubusercontent.com/20637016/40217422-3b40aaf0-5a9f-11e8-84f5-2e863131aec4.png)


请大佬指点一下，我哪里的问题，感谢！
