### ISSUE TITLE
php composer.phar update 出现包不存在

### ISSUE THREAD

**Issue by Alan0429** [ssrpanel/SSRPanel#1261]
[Composer\Downloader\TransportException]                                                            
  The "https://packagist.phpcomposer.com/p/provider-2015%2444556d86c14ae930201c6c3739813ae4d1a78928f  
  4bcb270f09ae4ef775d7788.json" file could not be downloaded: failed to open stream: Connection time  
  d out

**Comment by ssrpanel** [comment]
把composer.json中的
```
"config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "repositories": {
        "packagist": {
            "type": "composer",
            "url": "https://packagist.laravel-china.org"
        }
    }
```

改为.，注意config配置最后的逗号要删除，然后再执行一遍
````
"config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
````
