### ISSUE TITLE
用户列表报错

### ISSUE THREAD

**Issue by mzfqy** [ssrpanel/SSRPanel#1262]
Trying to get property of non-object {"userId":1,"exception":"[object] (ErrorException(code: 0): Trying to get property of non-object at /home/www/wwwroot/ssrpanel/app/Http/Controllers/AdminController.php:208)
昨天更新了数据库什么的一切没问题，今天更新进不了用户列表了

**Comment by Alan0429** [comment]
我也是

**Comment by mzfqy** [comment]
git reset --hard b23465802ba39667445b67c58e7f4b9036e5390b
先滚回去。。。

**Comment by Alan0429** [comment]
回滚后恢复

**Comment by mzfqy** [comment]
php artisan upgradeUserSubscribe

**Comment by Alan0429** [comment]
(1/1) FatalErrorExceptionClass 'Fideloper\Proxy\TrustProxies' not found
--
in TrustProxies.php line 8

全站错误....

**Comment by ssrpanel** [comment]
不看TG频道消息的人，不值得同情
