### ISSUE TITLE
审计订单时更新支付单和订单异常

### ISSUE THREAD

**Issue by kk2007yx** [ssrpanel/SSRPanel#1263]
我知道这个有人反映过，宝塔平台，改所有者为www，改完确实解决了，但是过一段时间又会出现，所有者已经是www，手动再改一遍点确定之后，又正行了，一只就这个循环在状态，不定时出现。
【有赞云】审计订单时更新支付单和订单异常：ErrorException: Undefined index: pay_type 
in /www/wwwroot/52hzl.cn/app/Console/Commands/AutoJob.php:331
Stack trace:
#0 /www/wwwroot/52hzl.cn/app/Console/Commands/AutoJob.php(331): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/www/wwwroot/52...', 331, Array)
#1 /www/wwwroot/52hzl.cn/app/Console/Commands/AutoJob.php(71): App\Console\Commands\AutoJob->detectOrders()
#2 [internal function]: App\Console\Commands\AutoJob->handle()
#3 /www/wwwroot/52hzl.cn/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#4 /www/wwwroot/52hzl.cn/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 /www/wwwroot/52hzl.cn/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#6 /www/wwwroot/52hzl.cn/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#7 /www/wwwroot/52hzl.cn/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#8 /www/wwwroot/52hzl.cn/vendor/symfony/console/Command/Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#9 /www/wwwroot/52hzl.cn/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#10 /www/wwwroot/52hzl.cn/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /www/wwwroot/52hzl.cn/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\AutoJob), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /www/wwwroot/52hzl.cn/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /www/wwwroot/52hzl.cn/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /www/wwwroot/52hzl.cn/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 {main}

**Comment by ssrpanel** [comment]
新新版已经修复
