### ISSUE TITLE
胖虎,lordlezehaf update laravel framework from 5.5 to 5.6 升级后站点无法打开

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/SSRPanel#1268]
HTTP ERROR 500, 请问是什么问题?

**Comment by 1021435278** [comment]
php版本是7.0, 是不是需要更高版本才可以?

**Comment by 1021435278** [comment]
![tim 20190117045611](https://user-images.githubusercontent.com/32491066/51278057-7bc9c680-1a14-11e9-8420-bdca46f43739.png)

重新赋予权限后,出现了这个错误提示, 请问如何解决?

**Comment by ssrpanel** [comment]
@1021435278 需要php7.1.3以上的版本

**Comment by Dennishaha** [comment]
@ssrpanel 同打不开 php 7.2.14

**Comment by ssrpanel** [comment]
@Dennishaha 7.2的不支持

**Comment by ssrpanel** [comment]
目前只能是7.1.X

**Comment by thank243** [comment]
以后都不支持7.2了么？

**Comment by Dennishaha** [comment]
这样弄有什么意义 又要让人折腾 想不明白

**Comment by thank243** [comment]
> 这样弄有什么意义 又要让人折腾 想不明白

7.2安装bcmath有奇效。

**Comment by ssrpanel** [comment]
@Dennishaha 你可以选择不升级，我又没逼你。。。

**Comment by ssrpanel** [comment]
@thank243 等我有空研究一下，这是框架的问题

**Comment by thank243** [comment]
> @thank243 等我有空研究一下，这是框架的问题

刚才一顿操作。装了7.1后正常了，然后切回7.2装了bcmath。结果也正常。
