### ISSUE TITLE
购买服务时，详情有效期有问题

### ISSUE THREAD

**Issue by maxzh0916** [ssrpanel/ssrpanel#127]
商品图片边上的物品详情里有效期只显示1970-01-01。
例如：内含流量 10240 MiB，有效期 1970-01-01 ~ 1970-01-01
不知道是不是bug。

**Comment by ssrpanel** [comment]
@maxzh0916 估计是，我检查下

**Comment by ZBrettonYe** [comment]
顺便再添加一个bug：
用户账号在超过使用时间后，一段时间再购买；SSR不会自动开启；

**Comment by maxzh0916** [comment]
@ssrpanel 我觉得不如把物品详情替换到这儿。

**Comment by ssrpanel** [comment]
@maxzh0916 @ZBrettonYe 你们的都问提都处理掉了，git pull一下
