### ISSUE TITLE
胖虎issue#1271 #1268没能解决

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/SSRPanel#1272]
确认了是Php7.1.

**Comment by 1021435278** [comment]
解决了:

https://stackoverflow.com/questions/48594851/upgrading-laravel-5-5-to-5-6-error/48595052#48595052

**Comment by 1021435278** [comment]
不过用户管理-用户列表还是有点问题, 估计是因为我之前删除了些用户导致, 希望尽快可以解决这个问题

**Comment by gxlrx** [comment]
执行一次php artisan upgradeUserSubscribe

**Comment by 1021435278** [comment]
谢谢已经解决了.
