### ISSUE TITLE
胖虎或者各位,请问centos下如何查看ssr访问的网页?

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/SSRPanel#1279]
这是因为想留文档记录以备万一需求, 是ssr中需要开启哪个参数? 另外方便把这个加到控制面板中做审核用吗/>

**Comment by ssrpanel** [comment]
ssr python版已无人维护更新，python 代码我看的也蛮蛋疼，群里有大佬已经在改 官方go版 [shadowsocks-go](https://github.com/shadowsocks/shadowsocks-go) ，把它转化为可连接数据库，且带上单端口、支持api等特性，可以持续关注作者项目 [vnet](https://github.com/rc452860/vnet) , wiki里暂时未上相关教程，我们内部还处于测试反馈BUG阶段，等着吧，如果你看的懂作者wiki的文档，你也可以自己部署一下，哦对了，记得打赏一下

**Comment by ssrpanel** [comment]
那些所谓的混淆，emmm....貌似没什么卵用，所以未必会接。

**Comment by 1021435278** [comment]
抽时间研究下, Python坑比较大吧, 接手人很难把握上一个开发者思路,还不如新写.

**Comment by ssrpanel** [comment]
python 坑真的巨多
