### ISSUE TITLE
你要的截图。

### ISSUE THREAD

**Issue by 110560** [ssrpanel/SSRPanel#1280]
![img_20190120_125210_820](https://user-images.githubusercontent.com/32481672/51435443-683b8b80-1cb2-11e9-9635-bb0595075673.jpg)

**Comment by ssrpanel** [comment]
laravel框架从5.4升级到5.6了，  .env.example 里的配置有差了，所以 cp .env.example .env 然后 把数据库连接信息填上，执行 php artisan key:generate
