### ISSUE TITLE
紧急：ipv6登录失败

### ISSUE THREAD

**Issue by 928net** [ssrpanel/SSRPanel#1282]
ipv6用户在输入用户名和密码之后登录，会提示“看起来好像出错了（翻译）”
目前只能手动把网址里的login去掉才能进入管理界面。
后台日志：
![image](https://user-images.githubusercontent.com/46510615/51443346-9ce72b80-1d22-11e9-938a-335e36135f75.png)

**Comment by ssrpanel** [comment]
修复了，
