### ISSUE TITLE
不知道算不算问题！！！！

### ISSUE THREAD

**Issue by cmtomkan310** [ssrpanel/SSRPanel#1283]
目前更新到最新版后，发现个奇怪问题，mysql的cpu使用率基本在95%以上，而且节点越多，占用率越高，基本3个节点就占满了！经过反复测试，不管是应用和数据库部在一起，还是单数据库部署都有这个问题！老版本无此问题！！！还请老大查查吧。。。

**Comment by ssrpanel** [comment]
打开日志自动清除啊大哥

**Comment by cmtomkan310** [comment]
@ssrpanel 是mysql的日志自动清除？

**Comment by cmtomkan310** [comment]
问题是我都没记录日志
![image](https://user-images.githubusercontent.com/38905231/51452661-62a77980-1d76-11e9-80e8-8a429c8932c9.png)

**Comment by thank243** [comment]
ssrpanel有个日志清除

**Comment by cmtomkan310** [comment]
@thank243 我知道那个，那个没用，那个我一直开着，现在mysqld的占用率一直是98%以上！这个问题很严重并没有解决，为什么要close？？？

**Comment by cmtomkan310** [comment]
@ssrpanel 问题依旧！
