### ISSUE TITLE
有赞云彻底翻车。

### ISSUE THREAD

**Issue by cnken** [ssrpanel/SSRPanel#1292]
昨天还好的，今天被官方擅自解除授权。

**Comment by ssrpanel** [comment]
翻一番issues，我频道也发了，早就翻车了

**Comment by cnken** [comment]
> 翻一番issues，我频道也发了，早就翻车了

我昨天还能使用的。

**Comment by kk2007yx** [comment]
为啥我已经重新授权也是不可以用

**Comment by cnken** [comment]
> 翻一番issues，我频道也发了，早就翻车了

现在除了ali国际，有什么好的支付接口吗？

**Comment by cnken** [comment]
> 为啥我已经重新授权也是不可以用

重新授权已经不是微小店了！！！！是微商城。

**Comment by kk2007yx** [comment]
国际阿里有没有申请教程 ？

**Comment by cnken** [comment]
> 国际阿里有没有申请教程 ？
自己申请应该不难，就是需要营业执照，貌似还不能用国内的营业执照。

**Comment by kk2007yx** [comment]
> > 为啥我已经重新授权也是不可以用
> 
> 重新授权已经不是微小店了！！！！是微商城。

哎 蛋痛 目前只能暂时关闭在线支付功能

**Comment by kk2007yx** [comment]
> > 国际阿里有没有申请教程 ？
> > 自己申请应该不难，就是需要营业执照，貌似还不能用国内的营业执照。

百度的营业执照能用不？但信息会不对吧

**Comment by cnken** [comment]
> > > 为啥我已经重新授权也是不可以用
> > 
> > 
> > 重新授权已经不是微小店了！！！！是微商城。
> 
> 哎 蛋痛 目前只能暂时关闭在线支付功能

有赞是彻彻底底凉凉了。我已经关了。

**Comment by cnken** [comment]
> > > 国际阿里有没有申请教程 ？
> > > 自己申请应该不难，就是需要营业执照，貌似还不能用国内的营业执照。
> 
> 百度的营业执照能用不？但信息会不对吧

还需要身份证哪~~~~

**Comment by kk2007yx** [comment]
> > > > 国际阿里有没有申请教程 ？
> > > > 自己申请应该不难，就是需要营业执照，貌似还不能用国内的营业执照。
> > 
> > 
> > 百度的营业执照能用不？但信息会不对吧
> 
> 还需要身份证哪~~~~

我晕...太麻烦了

**Comment by cnken** [comment]
> 翻一番issues，我频道也发了，早就翻车了

虎哥有没有什么方法临时挽救下？

**Comment by cnken** [comment]
> > > > > 国际阿里有没有申请教程 ？
> > > > > 自己申请应该不难，就是需要营业执照，貌似还不能用国内的营业执照。
> > > 
> > > 
> > > 百度的营业执照能用不？但信息会不对吧
> > 
> > 
> > 还需要身份证哪~~~~
> 
> 我晕...太麻烦了

是很麻烦的！！！！不然早换了。

**Comment by kk2007yx** [comment]
> 翻一番issues，我频道也发了，早就翻车了

同求！付费的也行啊！

**Comment by cnken** [comment]
> > 翻一番issues，我频道也发了，早就翻车了
> 
> 同求！付费的也行啊！

有能力的自己开发下码支付接口也不错的。

**Comment by kk2007yx** [comment]
> > > 翻一番issues，我频道也发了，早就翻车了
> > 
> > 
> > 同求！付费的也行啊！
> 
> 有能力的自己开发下码支付接口也不错的。
我只是个二手的程序员  改点代码还行 单独开发  不行

**Comment by cnken** [comment]
> > > > 翻一番issues，我频道也发了，早就翻车了
> > > 
> > > 
> > > 同求！付费的也行啊！
> > 
> > 
> > 有能力的自己开发下码支付接口也不错的。
> > 我只是个二手的程序员  改点代码还行 单独开发  不行

同类。

**Comment by kk2007yx** [comment]
> > > > > 翻一番issues，我频道也发了，早就翻车了
> > > > 
> > > > 
> > > > 同求！付费的也行啊！
> > > 
> > > 
> > > 有能力的自己开发下码支付接口也不错的。
> > > 我只是个二手的程序员  改点代码还行 单独开发  不行
> 
> 同类。

哎  只有坐等胖虎大大了

**Comment by mlch911** [comment]
> 0-1 难，1-2简单

大大啥时候上f2fpay啊，我之前看了半天还是没搞懂应该怎么对接……
