### ISSUE TITLE
虎哥把用户等级和节点组绑定+标签 利用起来吧 不要当摆设了.

### ISSUE THREAD

**Issue by samac08** [ssrpanel/SSRPanel#1293]
如题 可以把用户等级和节点分组等级绑定, 匹配实现不同用户使用不同等级调用不同的节点 并以标签过滤.
示例 带有vip标签的节点 例如有多个节点带此标签,多节点及多个节点组等级组内均含有vip标签的节点  绑定用户组及节点组等级后 用户仅可以用当前等级之节点组的所有vip标签的节点. 更高一级的组内带vip标签的节点不可用, 组等级不够 .......

**Comment by cnken** [comment]
貌似这些一直可以这么用吧。

**Comment by ssrpanel** [comment]
==

**Comment by cnken** [comment]
> ==

胖大，什么时候出f2f，没得充值很不die劲。

**Comment by ssrpanel** [comment]
说的好像你每天都能入好几百似的 @cnken 啊哈哈哈

**Comment by ssrpanel** [comment]
这个issues呢，我们内部正在开发测试ss go db版本，很多功能都会配合面板使用，以后会逐步上

**Comment by cnken** [comment]
> 说的好像你每天都能入好几百似的 @cnken 啊哈哈哈

说有收入，那是违法的。。。。

**Comment by ssrpanel** [comment]
等 vnet 出0.0.5版本，加入level 即可
