### ISSUE TITLE
手机端管理界面操作菜单看不见

### ISSUE THREAD

**Issue by GaHoKwan** [ssrpanel/SSRPanel#1296]
用户界面跟节点最右端的管理菜单按钮在手机端点击看不见

浏览器：三星浏览器

**Comment by cmtomkan310** [comment]
这个我早就想提了，忘了！手机点击操作后，无反应！

**Comment by GaryH4** [comment]
用chrome的手机模拟试了试……似乎都点不动

**Comment by ssrpanel** [comment]
这个我目前无法解决，除非又换回之前那个丑的界面，我iphone safari chrome 都没毛病。

**Comment by cmtomkan310** [comment]
@ssrpanel 安卓chrome也不行！

**Comment by yongjie0203** [comment]
测试发现 chrome 勾选桌面版网站选项后 可以正常使用

**Comment by cmtomkan310** [comment]
@yongjie0203 点赞！

**Comment by GaHoKwan** [comment]
是响应式页面布局的问题，页面小于多少px之后点击这个菜单就没反应

**Comment by ssrpanel** [comment]
> 是响应式页面布局的问题，页面小于多少px之后点击这个菜单就没反应

主要是我不会改
