### ISSUE TITLE
版权信息怎么更改

### ISSUE THREAD

**Issue by mynameiscaa** [ssrpanel/SSRPanel#1297]
![1548416012655](https://user-images.githubusercontent.com/41559238/51743611-28bcd700-20d8-11e9-8d78-e432b96e36bc.jpg)
右下角的版权信息在哪修改啊

**Comment by ssrpanel** [comment]
resource/views/user/layouts.blade.php
resource/views/admin/layouts.blade.php

建议后台保留，前台随便删，开源的

**Comment by JusufUs** [comment]
woc。。用人家免费提供的，给人家留个版权都不愿意？

**Comment by SRCOL** [comment]
@JusufUs 老哥你把我想说的说了出来，但我看到胖虎也没说啥就不好意思发炎了

**Comment by ssrpanel** [comment]
@SRCOL 扁桃体同学，请你坐下
