### ISSUE TITLE
升级至 节点是否允许UDP024a4fe74414e536a3cf786cd6bc9c34e72995b0这个版本用户列表报错

### ISSUE THREAD

**Issue by acdiost** [ssrpanel/SSRPanel#1298]
![1](https://user-images.githubusercontent.com/38416288/51748030-1f3a6b80-20e6-11e9-8f4f-a6c5cbfbcf9e.gif)
详情见图。
![default](https://user-images.githubusercontent.com/38416288/51748184-9243e200-20e6-11e9-84f9-ef6b5e000379.png)

另附：统计代码的页面位置需要优化。

还有一个是希望增加未支付完成订单的取消功能。否则，在有赞的订单超时后，出现无法购买的情况。
具体：
1、用户选择一个商品，成功创建了该订单。但未在有效时间内完成支付。
2、用户再次购买，需要支付之前未完成的订单才能再次购买。但此时订单超时失效了。无法完成支付。

望采纳，不胜感激！

**Comment by GaryH4** [comment]
看tg频道了吗

**Comment by acdiost** [comment]
刚刚看了一下。不太明白怎么解决该问题，已经更换了订阅码。

**Comment by GaryH4** [comment]
用户密码更新了吗，翻一翻wiki

**Comment by acdiost** [comment]
刚刚尝试了一下。依然不行。添加了一位新的管理员账户，更改过密码和订阅码也不行。
以下是新管理员报错的信息截图

![default](https://user-images.githubusercontent.com/38416288/51783285-ba792280-2172-11e9-943f-de9413190605.PNG)

**Comment by acdiost** [comment]
用的update.sh脚本执行的升级。

**Comment by GaryH4** [comment]
https://github.com/ssrpanel/SSRPanel/wiki/%E5%AF%86%E7%A0%81%E5%8D%87%E7%BA%A7%EF%BC%88MD5-to-HASH%EF%BC%89
有看过吗

**Comment by acdiost** [comment]
有看过。包括提供的博客里安装的问题之类的，未找到答案。我是从4.5版本升级的，密码已经从md5变为hash了.

**Comment by cmmdwl** [comment]
看起来你没看频道，有些用户没有定义码导致的这个问题

**Comment by acdiost** [comment]
![1](https://user-images.githubusercontent.com/38416288/51795402-b8b86900-221d-11e9-9186-d57227705f8e.PNG)
感谢！的确是这样的。经后台数据库查证，有用户注册了，未使用。没有订阅码导致的。是否应该修改一下，用户注册时就自动生成一个订阅码呢？且状态为封禁，激活后启用！
执行SQL：INSERT INTO `user_subscribe` (`id`, `user_id`, `code`) VALUES ('', '用户id', '订阅码');后即解决该问题。
