### ISSUE TITLE
重装多次还是看日志报错

### ISSUE THREAD

**Issue by ftwl516** [ssrpanel/ssrpanel#13]
![qq 20170906201019](https://user-images.githubusercontent.com/30188650/30111232-79e73ada-933f-11e7-945b-a3a4cfd8e7ab.png)

**Comment by ssrpanel** [comment]
@ftwl516 
1.你php.ini 里的disabled_functions 里的proc开头的函数有没有都删除掉？
2.ssserver.log你做了软连接了吗？
3.整个ssrpanel 如果你是用lnmp装的话默认是www:www用户组的，所以要记得授权一下
4.看样子就是权限问题
5.还有那个ssserver.log文件地址一定要对啊。就是建立软连接的时候。

**Comment by ftwl516** [comment]
1.你php.ini 里的disabled_functions 里的proc开头的函数有没有都删除掉？  (确认都删除了)
2.ssserver.log你做了软连接了吗？(做了软连接,)
3.整个ssrpanel 如果你是用lnmp装的话默认是www:www用户组的，所以要记得授权一下(授权过了,顺便用XFTP改了777权限)
4.看样子就是权限问题
5.还有那个ssserver.log文件地址一定要对啊。就是建立软连接的时候。(地址没错)

用的LNMP试也一样错误  用宝塔也是一样错误!

**Comment by max2max** [comment]
贴详细的安装日志、系统环境吧

**Comment by xiaoanweiwu** [comment]
同样日志报错
1、php.ini 里的disabled_functions 里的proc开头的函数删除了
2、ssserver.log做软连接了
3、ssrpanel目录用户组是www:www
4、ssserver.log也更改用户组为www:www了。

**Comment by 64611187** [comment]
// 日志分析
    public function analysis(Request $request)
    {
        $file = storage_path('app/public/ssserver.log');
        if (!file_exists($file)) {
            $request->session()->flash('analysisErrorMsg', $file . ' 不存在，请先创建文件');

            return Response::view('admin/analysis');
        }

        $logs = $this->tail($file, 10000);
        $url = [];
        foreach ($logs as $log) {
            if (strpos($log, 'TCP connecting')) {
                continue;
            }
把($file, 10000)改成100后不会报错了
$logs = $this->tail($file, 100);

**Comment by panjian-win** [comment]
大佬们 你们怎么解决的啊  我的运行命令：php composer.phar install
报错如下：
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize

                                                                               
  [Illuminate\Database\QueryException]                                         
  SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using pas  
  sword: YES) (SQL: select * from `config`)                                    
                                                                               

                                                                               
  [PDOException]                                                               
  SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using pas  
  sword: YES)                                                                  
                                                                               

Script php artisan optimize handling the post-install-cmd event returned with error code 1

**Comment by ssrpanel** [comment]
@panjian-win 先配置/config/database.php 的数据库链接信息

**Comment by ssrpanel** [comment]
@64611187 那个读取方式有点问题，估计是个BUG
