### ISSUE TITLE
进不了TG群，谁能帮忙解释下单端口的作用？

### ISSUE THREAD

**Issue by ppllpig** [ssrpanel/ssrpanel#130]
今晚迁移网站，遇到一个单端口的问题。
是否要启用单端口？单端口有什么用？
哪位大佬解释下，感谢

**Comment by ZBrettonYe** [comment]
减少被封记录 就是这样

**Comment by ssrpanel** [comment]
@ppllpig 已经解禁啦，启用单端口，单端口按照文档和面板里提示配置，配置完改成严格模式，就所有用户都访问你指定的端口了，可以伪造请求，假设都请求443端口或者80端口
