### ISSUE TITLE
请大佬看看，更新面板后正常使用，日志出错Illuminate\Database\QueryException

### ISSUE THREAD

**Issue by ywly** [ssrpanel/SSRPanel#1308]
gitpull合并和强制更新均出现这个日志问题，最新的数据库已导入，谷歌很久但还是没解决
代码如下，求教

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'where clause' (SQL: select * from `ticket` where `updated_at` <= 2019-01-28 12:22:01 and `status` = 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'where clause' (SQL: select * from `ticket` where `updated_at` <= 2019-01-28 12:22:01 and `status` = 1) at /www/wwwroot/www.ph147.ml/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'where clause' at /www/wwwroot/www.ph147.ml/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:326)
[stacktrace]
#0 /www/wwwroot/www.ph147.ml/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 /www/wwwroot/www.ph147.ml/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select * from `...', Array, Object(Closure))
#2 /www/wwwroot/www.ph147.ml/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1963): Illuminate\\Database\\Connection->select('select * from `...', Array, true)
#3 /www/wwwroot/www.ph147.ml/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1951): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /www/wwwroot/www.ph147.ml/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2435): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /www/wwwroot/www.ph147.ml/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1952): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#6 /www/wwwroot/www.ph147.ml/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(481): Illuminate\\Database\\Query\\Builder->get(Array)
#7 /www/wwwroot/www.ph147.ml/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(465): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#8 /www/wwwroot/www.ph147.ml/ssrpanel/app/Console/Commands/AutoJob.php(524): Illuminate\\Database\\Eloquent\\Builder->get()
#9 /www/wwwroot/www.ph147.ml/ssrpanel/app/Console/Commands/AutoJob.php(79): App\\Console\\Commands\\AutoJob->closeTickets()
#10 [internal function]: App\\Console\\Commands\\AutoJob->handle()
#11 /www/wwwroot/www.ph147.ml/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#12 /www/wwwroot/www.ph147.ml/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /www/wwwroot/www.ph147.ml/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#14 /www/wwwroot/www.ph147.ml/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#15 /www/wwwroot/www.ph147.ml/ssrpanel/vendor/laravel/framework/src/Illuminate/Console/Command.php(179): Illuminate\\Container\\Container->call(Array)
#16 /www/wwwroot/www.ph147.ml/ssrpanel/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#17 /www/wwwroot/www.ph147.ml/ssrpanel/vendor/laravel/framework/src/Illuminate/Console/Command.php(166): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#18 /www/wwwroot/www.ph147.ml/ssrpanel/vendor/symfony/console/Application.php(901): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /www/wwwroot/www.ph147.ml/ssrpanel/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\AutoJob), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /www/wwwroot/www.ph147.ml/ssrpanel/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /www/wwwroot/www.ph147.ml/ssrpanel/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /www/wwwroot/www.ph147.ml/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /www/wwwroot/www.ph147.ml/ssrpanel/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 {main}
"}

**Comment by ssrpanel** [comment]
https://github.com/ssrpanel/SSRPanel/wiki/%E5%A6%82%E4%BD%95%E6%9B%B4%E6%96%B0%E4%BB%A3%E7%A0%81
