### ISSUE TITLE
添加页面请求

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/SSRPanel#131]
管理界面添加
1.消费流水； 可以查看全部用户的消费记录，方便对账；
2.返利流水；可以查看又返利的账号与它的对象 这些信息；

功能添加：
邀请码批量导出；

**Comment by ssrpanel** [comment]
@ZBrettonYe 邀请码已加了点击链接，可以右键复制链接了

**Comment by ssrpanel** [comment]
@ZBrettonYe 消费流水的话，我先把余额那个改一下

**Comment by ZBrettonYe** [comment]
@ssrpanel 邀请码带链接这个功能有点冲突吧；情景如下：本站靠用户传播给激活码与返利进行传播，也就是说要是用户用激活码的链接那么就不会进行返利；所以他们还是要用返利链接+ 给激活码 宣传；
我指的激活码导出是和 优惠卷类似的；管理员生产大量激活码然后导出还没有使用的激活码到txt文件；

**Comment by ZBrettonYe** [comment]
主要是看到 用户界面已经有消费记录了，想在管理界面 加一个可以直观看到所有用户的消费记录历史；安装购买时间排列；顺便显示一下是否有效；
大概需要这些内容：
1.用户名；2.用户ID；3.邀请人ID；3.商品信息 （实际支付价格；4.购买时间；5.状态 ---有效/失效

**Comment by 1021435278** [comment]
@ZBrettonYe  管理员生产大量激活码然后导出还没有使用的激活码到txt文件

这个需要, 因为很多激活码被浪费了, 很多激活码未在规定时间内使用也要显示失效状态..

**Comment by ssrpanel** [comment]
@ZBrettonYe 对，这个我考虑不周到，你说的有道理，返利和邀请码要同时加上

**Comment by ssrpanel** [comment]
@ZBrettonYe 后面那个我也考虑加

**Comment by ssrpanel** [comment]
消费流水已加，返利流水暂时没有
