### ISSUE TITLE
在线IP监控为空

### ISSUE THREAD

**Issue by GaHoKwan** [ssrpanel/SSRPanel#1314]
后端的记录正常，为什么数据库为空？哪里设置不对？

**Comment by kk2007yx** [comment]
我的也是空的，你用的是胖虎大大的改版后端么？

**Comment by GaHoKwan** [comment]
是的，只有改版才有IP上报功能

**Comment by ssrpanel** [comment]
我们已经弃用了SSR Python版了，全面改用vnet（基于shadowsocks go 二次开发的）
https://github.com/ssrpanel/SSRPanel/wiki/SS-Go%E7%89%88%E8%8A%82%E7%82%B9%E9%83%A8%E7%BD%B2

**Comment by ssrpanel** [comment]
不过面板还是兼容SSR Python版、V2Ray Go版，都在WIKI里

**Comment by GaHoKwan** [comment]
vnet作者好像说不支持ssr混淆协议

**Comment by ssrpanel** [comment]
> vnet作者好像说不支持ssr混淆协议

不支持

**Comment by GaHoKwan** [comment]
但是用户都用的ssr，突然换后端，还不兼容原协议和混淆。。。。。。好吧，我放弃

**Comment by GaHoKwan** [comment]
但是好像现在要从ssr换成ss要我们手动把用户的协议和obfs一个个换回去才可以。。。因为用户个人设置里面的协议和obfs选项去掉了，只能由管理员在后台修改
