### ISSUE TITLE
功能建议：过期，流量预警等邮件分批次发送

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#1315]
用mailgun发信，如果单次短时间内发送邮件超过100封会触发mailgun提示邮件发送过快，然后账号发信会被关小黑屋1个小时，建议能把邮件分批次执行，比如每批次发送50封，间隔个5分钟再发送50封

![image](https://user-images.githubusercontent.com/6386202/52100976-baff3680-2614-11e9-971f-7dedbc93de6b.png)

**Comment by ssrpanel** [comment]
而且你也不穷 @828768
