### ISSUE TITLE
面板上没有V2RAY的服务器信息显示

### ISSUE THREAD

**Issue by foxhound1227** [ssrpanel/SSRPanel#1316]
面板上没有V2RAY的服务器信息显示？
前端和后端go版本都配置好了 客户端配置好了uid可以正常连接，但是前端面板里面没有V2RAY服务器的配置显示，订阅里面也没有？ 
是不是我哪里配置的有问题？

**Comment by foxhound1227** [comment]
和 demo.ssrpanel.com 对比了一下 就是下面那个节点列表没有出来！！ 不知道哪里设置有问题？

**Comment by foxhound1227** [comment]
已解决，没有设置用户对应的标签！！！！

**Comment by ssrpanel** [comment]
> 已解决，没有设置用户对应的标签！！！！

是的，就是这么骚
