### ISSUE TITLE
工具箱-流量日志 报错

### ISSUE THREAD

**Issue by xiaoanweiwu** [ssrpanel/SSRPanel#1317]
![fe7bb0ea-6a8b-4367-8b8d-afee86153b4b](https://user-images.githubusercontent.com/28782855/52106221-f1e14680-262c-11e9-912c-ff606b4e5a8c.png)

**Comment by xiaoanweiwu** [comment]
PHP 7.2.14 已安装bcmath扩展

**Comment by ssrpanel** [comment]
BUG。。我今天挖了一个坑。、

**Comment by ssrpanel** [comment]
晚点修正

**Comment by ssrpanel** [comment]
已修复，待提交
