### ISSUE TITLE
用户在线IP和在线IP监控都不显示

### ISSUE THREAD

**Issue by foxhound1227** [ssrpanel/SSRPanel#1319]
1、后端用的V2RAY的GO版本，前端面板里面 节点类别-产生流量 这一栏一直是0,这个是多长时间统计一次？

2、用户在线IP和在线IP监控都不显示，但是查看自己的流量信息又有记录，是后端不支持吗？还是我设置问题？

请大佬指点!

**Comment by zhouguangyou1994** [comment]
同问

**Comment by GaHoKwan** [comment]
这个功能只支持ss-go

**Comment by foxhound1227** [comment]
节点类别-产生流量 这一栏一直是0 过了24小时还是0 。。。。

**Comment by foxhound1227** [comment]
翻到一篇文章
按提示操作 php artisan autoStatisticsNodeDailyTraffic 流量会累加到产生流量里面
定时3分钟执行的 php artisan schedule:run 难道有问题 ？？？

#手动执行定时任务
sudo -u www-data php /var/www/SSRPanel/artisan autoJob
#统计节点流量（小时）
sudo -u www-data php /var/www/SSRPanel/artisan autoStatisticsNodeHourlyTraffic
#统计节点流量（天）
sudo -u www-data php /var/www/SSRPanel/artisan autoStatisticsNodeDailyTraffic

**Comment by GaHoKwan** [comment]
没有问题，问题是后端，后端只支持ssgo，v2ray跟ssr只是兼容了现在

**Comment by ssrpanel** [comment]
只支持SS-GO 后端。也就是vnet
