### ISSUE TITLE
防攻击最便宜的方案 - 基本完成总结呢,可以移动到WIKI了,并删除之前的防CC方案.

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#132]
这几天被DDCC的很烦,参考了胖虎的提议,简单改进了下.觉得有必要把教程公布.

我用的是vultr的机器都很便宜, 这里是连接,带了aff不喜欢可以删除,有需要的可以去买 https://www.vultr.com/?ref=7261365, 没攻击前用的一台机器做前端+数据库,另外跑台邮件服务器单独配置(后来发现单独邮件服务器很容易通过验证邮件头找到ip从而被攻击, 建议改用公用邮件服务器,例如谷歌的免费企业邮箱服务),

---------------------------------------------------------------------------------------------------------------
攻击刚开始是cc,这个挺容易防范的,一堆脚本可以做到. 昨天开始用了Ddos,流量不大也就2G,高峰达到了19G,基本是ntp攻击.

Vultr小机在攻击下很快就流量爆表但机器仍然正常.Vultr在每月没出账单发现你钱为负值钱不会停你机, 发了个ticket给Vultr,免单了.

--------------------------------------------------------------------------------------------------------------
Vultr的5美金/月小鸡还是很强悍的, 很多攻击导致负载高达250-290,但是没有死机,仍然正常工作,我做了以下优化,可做参考:

增加最少2G的SWAP, 我一般是4G, 反正Vultr是ssd硬盘.
连接数改为最大65535.
启用cron自动system update,这样系统就算你不去看也会随时保持在最新update减少漏洞.
4.参考秋水毅冰的bbr脚本, 这样可以增加机器网络吞吐能力, 参考链接:https://teddysun.com/489.html
目前为止我只用了Vultr和Linode, 我个人比较喜欢Vultr这种简洁网站, 可能还有其它IDC有更好,更便宜的小鸡.

---------------------------------------------------------------------------------------------------------------
由于之前买的小鸡是新加坡,不支持防Ddos, 我重新在美国买了个$10/月的带防ddos的机器,加上本身小鸡$5/月, 一共$15/月,并回滚快照同时把cloudflare的 DNS重新指向新的机器IP.

比较懒所以前端用宝塔面板的, 配置好各种信息后,直接关闭面板,减少被攻击点,需要的时候再打开.
前端3306只允许开放给跑数据库的VPS的IP.

在web应用层用nginx1.2的启用waf,并把Cloudflare的白名单全部加进来. https://www.cloudflare.com/ips
-这点Cloudflare做的挺好,国内腾讯云基本上把这当做机密不提供, 阿里云直接CDN收费.

网站前端配置了Cloudflare的免费CDN, 重中之重是保护源站ip, 一旦被人知道立刻换, 不要有任何侥幸心态.
受到攻击后可以通过生成快照,然后新购主机回滚快照,也就几分钟的事情且无需任何改动,只要简单的在Cloudflare指向新的主机. 这个动作只要几分钟的事情,别人要找到新的ip, 代价不低.

在Vultr的控制面板中提前创立firewall规格,把cloudflare的ip全部加进来. Cloudflare的ip段: www.cloudflare/ips, 并应用在新的网站前端机器上.

网站前端运行的小鸡有必要的配置类似redis / membercached 之类的缓存, 和Cloudflare配合桌双层cache.
-默认Redis可以远程登录,注意更改为127.0.0.1只允许本机登录.

Vutrl的10G Ddos mitigation是比较真实的数字,很多商家吹牛逼抗多少多少g攻击是个笑话.

现实中组织一个大于10g的攻击代价不小, 特别Vultr的Ddos mitigation对类似ntp攻击好像作用比较明显(待验证).
------------------------------------------------------------------------------------------------------------
由于是网站/数据库分离,单独买了个Vultr小鸡跑数据库也是$5,因为数据库机器ip除非你自己告诉人家或者胖虎面板程序被攻破得到数据库机器IP地址,否则基本上外人是不知道数据库ip的,所以很安全同时也便于用户管理和迁移.

数据库跑的VPS我用了军哥的一键包, www.lnmp.org, 安装配置完毕后停掉了nginx服务,并把phpmyadmin文件夹删除掉, 可以通过下个adminer文件方便数据库管理(https://www.adminer.org/) ,这样只在特别需要管理时候启用下nginx就可以了.仅仅剩下单独的数据库服务在跑,很隐秘安全.

如果需要更安全, 修改数据库连接的默认端口3306,为自定义端口. 做好以上的动作后,基本上只要把关注点放在网站前端上就行了.

-------------------------------------------------------------------------------------------------
下面是现在正在攻击的截图, 也就3.5G的攻击, (2017-11-26更新,最新的数值是峰值19G)

![a](https://user-images.githubusercontent.com/32491066/33444427-3d1f00b8-d635-11e7-9572-80aec79326db.png)

可以从Vultr的Ddos中看到具体攻击ip, 123端口一般是ntp攻击.

如果是纯流量攻击,可以一个一个的输入到www.ipip.net 找到ip所属机房/IDC, 然后发邮件去投诉.一般来说这种很容易处理, 今天我就收到Vultr机房回复说之前投诉的某个攻击ip所属账号被封的邮件回复)

曲线可以看出Vultr的Ddos mitigation 还是可以的.

任何的Ddos攻击务必在到达机器前拦截住,所以必要的基本Ddos mitigation还是需要的.

大型的攻击(>30g)就需要单独特别寻找服务商了,某种形势下就是比谁钱多, 但是这种层次的攻击很少见,除非你是特别火爆的黑/灰色产业比如菠菜,黄色等,某些情况下防守方可以通过较少的付出完成抵抗,毕竟这种规模的攻击需要的成本也不低.

-----------------------------------------------------------------------------------------------------
另外在网络层用iptable来对异常(主要是cc攻击)进行封杀,基本上可以保证经过vultr 防ddos后漏进来的漏网之鱼:

输入下面命令后发现不少连接超过100,最高1万都有,去看了下nginx日志,都有2G大了,说明有人在进行攻击行为
netstat -nat|grep -i '80'|wc -l
对连接的IP按连接数量进行排序，查看TCP连接状态
netstat -ntu | awk '{print $5}' | cut -d: -f1 | sort | uniq -c | sort -n
可以手动的查看链接Ip, 只要连接超过20的全办了,一个破面板,用来注册和查看节点信息的,超过5个就是有问题了.
--------------------------------------------------------------------------------------------------
你也可以用张戈的防CC脚本并设置连接超过10就banned时间600000000000秒
https://zhangge.net/5066.html
https://github.com/jagerzhang/CCKiller
---------------------------------------------------------------------------------------------------
但是我测试发现效果不太好, 所以改为以下配置(配置完全可以照抄)

设定允许单个IP的最大连接数为 3
iptables -I INPUT -p tcp --dport 80:443 -m connlimit --connlimit-above 3 -j REJECT

#单个IP在60秒内只允许最多新建20个连接,,每分钟Cron自动执行一次
iptables -A INPUT -p tcp --dport 80:443 -m recent --name BAD_HTTP_ACCESS --update --seconds 60 --hitcount 20 -j REJECT
iptables -A INPUT -p tcp --dport 80:443 -m recent --name BAD_HTTP_ACCESS --set -j ACCEPT
然后运行 service iptables save 和 service iptables restart 写入iptables 避免下次重启丢失.

#防止SYN攻击,轻量级预防,每分钟Cron自动执行一次
*/1 * * * * sbin/iptables -N syn-flood
*/1 * * * * sbin/iptables -A INPUT -p tcp –syn -j syn-flood
*/1 * * * * sbin/iptables -I syn-flood -p tcp -m limit –limit 2/s –limit-burst 3 -j RETURN
*/1 * * * * sbin/iptables -A syn-flood -j REJECT

#用Iptables抵御DDOS(参数与上相同),每分钟Cron自动执行一次
*/1 * * * * sbin/iptables -A INPUT -p tcp --syn -m limit --limit 1/s --limit-burst 5 -j ACCEPT
*/1 * * * * sbin/iptables -A FORWARD -p tcp --syn -m limit --limit 1/s -j ACCEPT

#在5秒内只允许最多新建10个连接,,每分钟自动执行一次
*/1 * * * * sbin/iptables -A INPUT -p tcp --dport 80:443 -m recent --name BAD_HTTP_ACCESS --update --seconds 5 --hitcount 10 -j REJECT
*/1 * * * * sbin/iptables -A INPUT -p tcp --dport 80:443 -m recent --name BAD_HTTP_ACCESS --set -j ACCEPT

更多Iptables命令供参考:
打开某个端口:
/sbin/iptables -I INPUT -p tcp --dport 3306 -j ACCEPT
/sbin/iptables -I INPUT -p tcp --dport 22 -j ACCEPT
/sbin/iptables -I INPUT -p tcp --dport 10000:20000 -j ACCEPT

封单个IP的命令：iptables -I INPUT -s 222.155.43.166 -j DROP
封IP段的命令：iptables -I INPUT -s 124.115.0.0/16 -j DROP
封整个段的命令：iptables -I INPUT -s 194.42.0.0/8 -j DROP
封几个段的命令：iptables -I INPUT -s 61.37.80.0/24 -j DROP

只封80端口：iptables -I INPUT -p tcp –dport 80 -s 124.115.0.0/24 -j DROP
解封：iptables -F
清空：iptables -D INPUT 数字
-----------------------------------------------------------------------------------------------------------
消除攻击后,如果发现主机Outbound流量异常增高, 一般是攻击者批量/多线程下载站内客户端下载包来消耗流量导致.

可以考虑把客户端下载文件剥离出去单独用个子域名且启用密码访问才可以下载且设定单线程限速.
最好的解决方案还是是放到公用网盘上,随便别人拖个痛快,他舒服你也舒服,反正不耗费你的流量,且简单快速.

另外每个节点运行封杀PT/BT端口的脚本参考:
https://doub.io/shell-jc2/
-------------------------------------------------------------------------------------------------------------
#每周1/3/5凌晨3点(美国下午15点)自动节点重启ssr客户端命令,可以起到类似节点守护的作用.
节点 0 15 * * 1,3,5 /bin/sh /root/shadowsocksr/stop.sh && /bin/sh /root/shadowsocksr/run.sh
主站:0 15 * * 1,3,5 /bin/sh /root/shadowsocksr/stop.sh && /bin/sh /root/shadowsocksr/logrun.sh

**Comment by NimaQu** [comment]
你觉得
50kvm/50vz
吾云
魔方云
是垃圾idc？
真是笑死本萌妹了

**Comment by 1021435278** [comment]
除了魔方云我好像在哪里听说过, 其它的我可以说是垃圾了,要不就是还没砸够钱投广告,最少没入本人法眼好吧.

**Comment by ppllpig** [comment]
受益匪浅，小白请问“每天凌晨3点自动在个节点重启ssr客户单命令,并运行测试命令并运行几分钟后关闭(无Log)”具体命令是什么，谢谢

**Comment by ppllpig** [comment]
宝塔自带不是有防CC么

**Comment by 1021435278** [comment]
@ # @ppllpig 
这个我是记录下来, 节点跑个cron,每天早上3点自动执行下面命令,避免节点死机,类似守护进程,不过更简洁.

/root/shadowsocksr/run.sh
/root/shadowsocksr/python server.py  运行3分钟后停止的还在测试,或者不需要停止.


其它信息:
#每天凌晨3点自动在个节点重启ssr客户单命令,并运行测试命令并运行几分钟后关闭(无Log),可以起到类似守护的作用.

**Comment by ppllpig** [comment]
还有一个问题，加SWAP是在前端加还是节点加的？谢谢

**Comment by neoFelhz** [comment]
不用看了，他站已经死了。

**Comment by ZBrettonYe** [comment]
@NimaQu 个人不看好 吾云；

以上为个人观点

**Comment by 1021435278** [comment]
@ppllpig 都可以加, 小鸡的我都加了, 虽然vutrl是ssd硬盘,反正都是中转,所以无所谓硬盘空间.

**Comment by 1021435278** [comment]
@ppllpig 

供你参考, 你可以测试看看(我用的是美国时间,对应国内凌晨三点),记得crond reload下.

#每天凌晨3点自动在个节点重启ssr客户单命令,并运行测试命令,可以起到类似守护的作用.
0 15 * * 1,3,5 /bin/sh /root/shadowsocksr/run.sh && /root/shadowsocksr/python server.py -d restart
或者下面
0 15 * * 1,3,5 /bin/sh /root/shadowsocksr/run.sh
1 15 * * 1,3,5 /bin/sh /root/shadowsocksr/python server.py -d restart

**Comment by 1021435278** [comment]
@ZBrettonYe 
请教下:
50kvm/50vz
吾云
还有所谓的80主机, 都是些什么鸡巴玩意? 都不知道网站是什么, 搜索的80主机,出来一大堆.

其中有些人天天ddcc人家? D了几天, 现在防备做好了,昨晚最后折腾了下,现在安稳了.

这帮傻逼攻击我的另外台阿里云去了, 那个随便攻击, 包年的.... 

![qq 20171127121907](https://user-images.githubusercontent.com/32491066/33250735-47dfe906-d36d-11e7-9073-2db196ba7403.png)

**Comment by 1021435278** [comment]
刚简单的看了下阿里云,下载的包看了下, 原来是Ntp 攻击, 这么简单的玩意, 一会封闭掉123端口, 估计是所谓的老王压力测试干的吧, 昨天就看到了.

![qq 20171127170131](https://user-images.githubusercontent.com/32491066/33258587-1696c7b6-d395-11e7-870f-8be265fd70e4.png)

**Comment by neoFelhz** [comment]
@1021435278 
既然你诚心诚意问了，我就大慈大悲告诉你：把 `ntp` 包卸掉就行。

```
apt purge ntp
```
```
apt-get autoremove ntp
```
```
yum -y remove ntp*
```

**Comment by 1021435278** [comment]
neofelhz@jiangxia.gov.cn  还是政府的啊, 挺不错.

**Comment by 1021435278** [comment]
neofelhz@jiangxia.gov.cn  还是政府的啊, 挺不错.
