### ISSUE TITLE
建议：编辑商品添加付费方式

### ISSUE THREAD

**Issue by 329928** [ssrpanel/SSRPanel#1320]
类似于购买商品自动打上对应标签，同时也给用户打上对应商品的付费方式。
这样也方便之后筛选用户。

**Comment by 13221253358** [comment]
建议优惠券，抵用券指定的套餐才可以使用

**Comment by 329928** [comment]
顺便，用户编辑里的速度限制这些，也可以和商品绑定，购买对应套餐之后，给用户对应的速度。

**Comment by 329928** [comment]
订单列表里，也可以按付费方式筛选订单
