### ISSUE TITLE
邮件发送频率调整

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/SSRPanel#1324]
邮箱发送 经常触发 Expected response code 250 but got code "550", with message "550 Connection frequency limited "

账号过期， 流量警告 这些不大重要的 邮件都可以隔1分钟

**Comment by ssrpanel** [comment]
已经将 发邮件改为 队列异步处理，那个间隔问题，容我稍后研究下

**Comment by ZBrettonYe** [comment]
嗯， 毕竟 账号过期，流量警告这些邮件到了 固定时间，就是一拥而上，直接搞的邮箱触发上限

**Comment by kk2007yx** [comment]
我也遇到这个问题了，解决了吗？
