### ISSUE TITLE
咨询各位大大一个诡异的问题

### ISSUE THREAD

**Issue by jackyeow** [ssrpanel/SSRPanel#1328]
前端服务器我用的是阿里云国际新加坡，后端服务器我用的是阿里云香港和板瓦工洛杉矶cn2 Gia，前后端是分离的，不在同一个服务器，前段时间用的好好的，前几天出现香港连接不上，用移动4g也连接不上，但是洛杉矶可以连上，前端后台一切正常，我以为是香港被墙，奇怪的是我的另外几个朋友可以上香港节点，就我不能连上，阿里云安全规则都是打开的，请问这是怎么回事啊？从来没碰到过！

**Comment by victoryLV** [comment]
端口被ban 了

**Comment by ssrpanel** [comment]
这种情况很可能是你当地ISP 对你这个香港IP进行QOS了。你所在地可能是：浙江（宁波较严重）、广东、江苏（个别城市），还有东北地区（各种DNS污染，建议尝试用IP）

**Comment by ssrpanel** [comment]
@jackyeow

**Comment by ssrpanel** [comment]
宁波是一个啥玩意来着，反正好像是 IT 的一个什么试验点，所以浙江温州，宁波，等几个城市的网络非常的奇葩

**Comment by ssrpanel** [comment]
当你的用户可以分布到全国各省市（玩长一点时间，比如2年+）你就会发现，全国的网络是那么的奇葩

**Comment by jackyeow** [comment]
我是上海的，但是我那些朋友也是上海的呀，你说怪不怪？有什么解决办法吗？@ssrpanel
