### ISSUE TITLE
ss-go后端配置成功 启动失败

### ISSUE THREAD

**Issue by Zhangziheng1** [ssrpanel/SSRPanel#1329]
胖虎大大更新的的ip监控功能很诱人，我就在原有的【一键怕配置后端脚本】上直接停止了原有的后端，按照wiki的方法配置了ss-go后端，遗憾的事情发生了。

ERROR 2019-02-09 10:41:09 shadowsocks.go[232] 1: read target address error SOCKS error: 8. (maybe the crypto method 2rong configuration)

**Comment by ssrpanel** [comment]
1.配置要对（作者没写wiki，我写了，但是没有及时更新，建议到生成config。json那一步你自己参照着看）
2.目前vnet还有坑，看频道，我们内部测试的时候已经用到0.0.6了，不过坑巨多，可以自定义dns、可以限速、可以禁止tcp、udp（禁止就无法游戏）、优先IPv6或者IPv4，还有其他配置，有些在0.0.4不生成config的。
3.你上面那个错误，1.是你所在服务器dns无法解析目标网址 2.可能强制走了IPv6了
