### ISSUE TITLE
安装ssrpanel后打开网页提示错误，宝塔面板安装

### ISSUE THREAD

**Issue by chen6532489** [ssrpanel/SSRPanel#1330]
![snipaste_2019-02-09_21-55-14](https://user-images.githubusercontent.com/42490270/52521658-67948480-2cb5-11e9-8bdf-d32824c5dd39.png)
这个应该是被封禁IP了吧。 没有挂代理也出现这个。

**Comment by Mycheol** [comment]
我也遇到了这个问题，如何解决呢？
