### ISSUE TITLE
更改用户端口号以后扫描二维码无效

### ISSUE THREAD

**Issue by jackyeow** [ssrpanel/SSRPanel#1331]
更改用户端口号以后扫描二维码无效，不知道大家有没有碰到过？
![img_1212](https://user-images.githubusercontent.com/10632793/52533226-966d3200-2d6b-11e9-89f6-94f3ca5d99b1.png)
手动填写页无效，不知道哪里出了问题！
各位老大能分析分析有哪几种可能性吗？

**Comment by jackyeow** [comment]
另外你们编辑用户信息里面这里是空白的吗？？
<img width="615" alt="2019-02-10 20 20 07" src="https://user-images.githubusercontent.com/10632793/52533624-5ad56680-2d71-11e9-903f-3f4957a2d44a.png">

**Comment by Alan0429** [comment]
我遇到过，一般是安装不完整，重装即可，或者是CDN照成的

**Comment by Alan0429** [comment]
然后什么未包含，你的客户端问题

**Comment by ssrpanel** [comment]
数据库不完整

**Comment by jackyeow** [comment]
数据库没有动过呀

**Comment by jackyeow** [comment]
@ssrpanel 怎么解决？重新导入数据库？

**Comment by jackyeow** [comment]
少了哪个表？

**Comment by jackyeow** [comment]
我看了下，我一共47张表

**Comment by jackyeow** [comment]
我看了一下，ssrpanel数据库一共48张表

**Comment by jackyeow** [comment]
自己重新导入ss_config表就好了，下拉菜单也有了，扫描二维码也正常了，mark一下，以后碰到的朋友可以少走弯路。
