### ISSUE TITLE
前端纯v2ray服务器订阅失败

### ISSUE THREAD

**Issue by foxhound1227** [ssrpanel/SSRPanel#1332]
前端纯v2ray服务器，win下 v2rayN 订阅失败，用浏览器打开解密后得到的是一个 
ssr://MS4xLjEuMTo4ODg4Om9yaWdpbjpub25lOnBsYWluOk1EQXdNQS8_b2Jmc3BhcmFtPSZwcm90b3BhcmFtPSZyZW1hcmtzPTVwZWc1WS12NTVTbzZJcUM1NEs1NW9pVzZMU201WS0zNktLcjViQ0I1NmFCNW9pVzZLNmk2WmlGNktLcjViQ0I1NmFCJmdyb3VwPTZaU1o2Sy12JnVkcHBvcnQ9MCZ1b3Q9MA
地址 
用ssr 订阅也是一个无效的地址：1.1.1.1 无可用节点或账号被封禁或订阅被封禁

是不是我哪里设置有问题？

**Comment by foxhound1227** [comment]
V2rayN 订阅提示：
更新订阅开始
1->开始获取订阅内容
1->获取订阅内容成功
1->清除原订阅内容
1->导入订阅内容失败
1->更新订阅结束

**Comment by foxhound1227** [comment]
V2rayN日志

 
--------------------------------info[16:08:49]--------------------------------
System.Exception: v2rayN start up

 
--------------------------------Base64Decode[16:08:57]--------------------------------
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. 
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at v2rayN.Utils.Base64Decode(String plainText)

**Comment by foxhound1227** [comment]
服务器重启一遍好了。。。。。。。。
配置不是实时生效的吗？

**Comment by ssrpanel** [comment]
无可用节点或账号被封禁或订阅被封禁 这不是很清楚吗
