### ISSUE TITLE
smtp显示投递成功，实际未成功

### ISSUE THREAD

**Issue by vft9nesd** [ssrpanel/SSRPanel#1335]
端口已开，旧版本好像也没啥问题，也很久没测试
今天重装了一个系统，拉了最新版，发现这个问题
无论smtp账号密码是否正确，都显示投递成功
![image](https://user-images.githubusercontent.com/24932999/52608232-32a25080-2eb4-11e9-8d40-b9e65138c4f7.png)
甚至这样的smtp地址 都显示成功
![image](https://user-images.githubusercontent.com/24932999/52608255-43eb5d00-2eb4-11e9-89f3-501da9b3f8fb.png)
当然把改成smt就成功报错了。

我记得以前，投递不成功，或者配置参数不正确，都会正常报错的。

**Comment by vft9nesd** [comment]
@ssrpanel

**Comment by ssrpanel** [comment]
@vft9nesd 你在群里也不看消息，我昨天更新了，上了异步发邮件走队列了

**Comment by vft9nesd** [comment]
我看了。。redis显示只连接了一个  是没成功吧？ cache和queue都开的redis   php扩展什么的都开着呢
![image](https://user-images.githubusercontent.com/24932999/52608483-210d7880-2eb5-11e9-8049-5bec4f55d534.png)

**Comment by vft9nesd** [comment]
换了database，运行了queue ，好了，是我的redis哪里设置出错了吗？
后面设置了一下，连接的客户端是2，应该cache和queue都正常连接了，php redis扩展也安装了，但是redis怎么也发不出邮件。。

还有这个投递状态都提示成功，没有详细报错，可以修修吗

**Comment by ssrpanel** [comment]
@vft9nesd 如果你要用redis，就要把 queue.sh 里的 那个database 单词改为 redis，其他都默认即可

**Comment by vft9nesd** [comment]
噢酱紫   秒懂了  怪不得这个进程一会就自动没了呢

**Comment by vft9nesd** [comment]
成功踩坑，中间的消息被淹没了没看到，只看频道了哈哈

**Comment by ssrpanel** [comment]
@vft9nesd 意思是用laravel 的 config/queue.php 里的 connections 中的 redis 配置，然后这个redis的配置呢，又在 config/database.php 中的  redis ，然后 这个redis又是读取 .env 文件中的 这三行
```
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
```

因为 宝塔中装redis ，装完启动了默认就是监听6379端口，所以说，全部都是默认配置，都不用改。，只要改 queue.sh 中的那个database 单词和 .env 中的 queue_driver 都改为redis即可启用redis

**Comment by ssrpanel** [comment]
要记得 
```
ps aux|grep php 
然后找到这个 监听，kill掉它，改完queue.sh 之后
重启执行一遍，否则不生效，因为这个是常驻内存的，官方文档推荐用supervisor，不过我用的不习惯，先用nohup挂着，你要不要研究一下supervisor 

主要是要执行这一句（后台常驻）： php artisan queue:work database --queue=default --timeout=60 --sleep=5 --tries=3
```

**Comment by vft9nesd** [comment]
无脑显示投递成功也是个坑啊  smtp.exmail.qq.com123  我这样的smtp地址也显示成功@@

**Comment by ssrpanel** [comment]
@vft9nesd 主要是它是异步发邮件，邮件只要进了队列就认为发成功了，我目前没找到怎么解决这个发邮件失败咋处理

**Comment by vft9nesd** [comment]
这我知道  感觉这个nohup不太稳定    长时间会掉进程   得加个狗

**Comment by vft9nesd** [comment]
如果掉了进程 面板也提示成功  追溯原因就略麻烦了

**Comment by ssrpanel** [comment]
@vft9nesd 所以啊，研究一下supervisor 
文档 https://learnku.com/docs/laravel/5.6/queues/1395#supervisor-configuration

**Comment by ssrpanel** [comment]
我说过了吼，这个功能加上，要坑死一堆小白，小白根本不知道什么叫队列，什么叫异步，会搞死他们的

**Comment by ssrpanel** [comment]
@vft9nesd  我之前centos6 下有 用过，但是不知道为什么有时候 supervisor自己都会挂，所以一直都没用起来。。。有空你研究下？ 只要CentOS 7能跑起来，重启后还能跑起来就够了。

https://github.com/ssrpanel/SSRPanel/wiki/CentOS-6-%E5%AE%88%E6%8A%A4%E8%BF%9B%E7%A8%8B(Supervisord)

**Comment by vft9nesd** [comment]
各有所长嘛，也各有所短，耐心学习就行了，我一个门外汉硬啃呢

**Comment by vft9nesd** [comment]
> ，重启后还能跑起来就够了

Python版的ssr   我是定时任务启动run.sh     那个run.sh  可以判断是否存在server.py进程，然后再启动，十分钟运行一次run.sh 就行了

**Comment by ssrpanel** [comment]
> > ，重启后还能跑起来就够了
> 
> Python版的ssr 我是定时任务启动run.sh 那个run.sh 可以判断是否存在server.py进程，然后再启动，十分钟运行一次run.sh 就行了
> 
> 这个也同理吧 简单粗暴。。 无脑
> 
> 都是定时喂狗。。这个好像更无脑

不是有logrun.sh 吗
我从来都是logrun.sh

**Comment by vft9nesd** [comment]
> > > ，重启后还能跑起来就够了
> > 
> > 
> > Python版的ssr 我是定时任务启动run.sh 那个run.sh 可以判断是否存在server.py进程，然后再启动，十分钟运行一次run.sh 就行了
> > 这个也同理吧 简单粗暴。。 无脑
> > 都是定时喂狗。。这个好像更无脑
> 
> 不是有logrun.sh 吗
> 我从来都是logrun.sh

。。没用过带日志的，要日志没啥用，甚至没打开那个sh看。。

**Comment by ssrpanel** [comment]
说起来就挺蛋疼，我N1到现在还没刷，我的K3刷成砖头了。ε=(´ο｀*)))唉

**Comment by vft9nesd** [comment]
> 说起来就挺蛋疼，我N1到现在还没刷，我的K3刷成砖头了。ε=(´ο｀*)))唉
旧砖方法很多啊，实在不行拆机ttl或者上编程器~~或者50包邮解君愁

**Comment by vft9nesd** [comment]
@ssrpanel 
更新一下queue.sh
```
#!/bin/bash
cd `dirname $0`
eval $(ps -ef | grep queue:work | awk '{print "kill "$2}')
ulimit -n 512000
nohup php artisan queue:work redis --queue=default --timeout=60 --sleep=5 --tries=3 >> ./storage/logs/queue.log 2>&1 &
```
并添加定时任务

```
*/10 * * * * bash /www/wwwroot/SSRPanel/queue.sh
```

每隔十分钟检测进程是否存在，如果存在，则杀掉重启，不存在也启动一下~

**Comment by vft9nesd** [comment]
伪狗新版

更新queue.sh
```
#!/bin/bash
ps -ef|grep queue:work |grep -v grep
if [ $? -ne 0 ]
then
echo "start queue process successfully....."
nohup php artisan queue:work redis --queue=default --timeout=60 --sleep=5 --tries=3 >> ./storage/logs/queue.log 2>&1 &
else
echo "queue is running....."
fi
```
并添加定时任务
```
*/10 * * * * bash /www/wwwroot/SSRPanel/queue.sh
```

每隔十分钟检测进程是否存在，若存在，则退出，若不存在，则启动进程

**Comment by ssrpanel** [comment]
已修复投递失败问题
