### ISSUE TITLE
更新后流量日志报错

### ISSUE THREAD

**Issue by mzfqy** [ssrpanel/SSRPanel#1338]
ErrorException (E_ERROR)
Trying to get property of non-object (View: /www/wwwroot/ssrpanel/resources/views/admin/trafficLog.blade.php)
Previous exceptions
Trying to get property of non-object (0)
   COPY
Application frames (9)  All frames (77)
76
ErrorException 
…/storage/framework/views/e106c2d18bc753efb50c32dea88020023b84c2f7.php77
75
ErrorException 
…/storage/framework/views/e106c2d18bc753efb50c32dea88020023b84c2f7.php77
74
Illuminate\Foundation\Bootstrap\HandleExceptions handleError
…/storage/framework/views/e106c2d18bc753efb50c32dea88020023b84c2f7.php77
63
Illuminate\Support\Facades\Facade __callStatic
…/app/Http/Controllers/AdminController.php1151
55
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/app/Http/Middleware/isAdmin.php24
52
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/app/Http/Middleware/isLogin.php24
49
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/app/Http/Middleware/isForbidden.php85
37
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/app/Http/Middleware/SetLocale.php29
0
Illuminate\Foundation\Http\Kernel handle
…/public/index.php55
/www/wwwroot/ssrpanel/storage/framework/views/e106c2d18bc753efb50c32dea88020023b84c2f7.php
                                    <th> 记录时间 </th>
                                </tr>
                                </thead>
                                <tbody>
                                    <?php if($list->isEmpty()): ?>
                                        <tr>
                                            <td colspan="8" style="text-align: center;">暂无数据</td>
                                        </tr>
                                    <?php else: ?>
                                        <?php $__currentLoopData = $list; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $vo): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                                            <tr class="odd gradeX">
                                                <td> <?php echo e($vo->id); ?> </td>
                                                <td>
                                                    <?php if(empty($vo->user)): ?>
                                                        【账号已删除】
                                                    <?php else: ?>
                                                        <a href="<?php echo e(url('admin/userList?id=') . $vo->user->id); ?>" target="_blank"> <span class="label label-info"> <?php echo e($vo->user->username); ?> </span> </a>
                                                    <?php endif; ?>
                                                </td>
                                                <td> <?php echo e($vo->node->name); ?> </td>
                                                <td> <?php echo e($vo->rate); ?> </td>
                                                <td> <?php echo e($vo->u); ?> </td>
                                                <td> <?php echo e($vo->d); ?> </td>
                                                <td> <span class="label label-danger"> <?php echo e($vo->traffic); ?> </span> </td>
                                                <td> <?php echo e($vo->log_time); ?> </td>
                                            </tr>
                                        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                                    <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                        <div class="row">
                            <div class="col-md-4 col-sm-4">
                                <div class="dataTables_info" role="status" aria-live="polite">共 <?php echo e($list->total()); ?> 条记录，合计 <?php echo e($totalTraffic); ?> </div>
                            </div>
                            <div class="col-md-8 col-sm-8">
                                <div class="dataTables_paginate paging_bootstrap_full_number pull-right">
                                    <?php echo e($list->links()); ?>
 
                                </div>
Arguments
"Trying to get property of non-object (View: /www/wwwroot/ssrpanel/resources/views/admin/trafficLog.blade.php)"

**Comment by ssrpanel** [comment]
翻一下wiki 看怎么更新系统，好吗？

**Comment by mzfqy** [comment]
包导了

**Comment by mzfqy** [comment]
8dc5403397cd093ce69176c54b3bf8bb06252a92
三天前那个版本没问题
今天按方法更新流量日志报错
Trying to get property of non-object (View: /www/wwwroot/ssrpanel/resources/views/admin/trafficLog.blade.php) {"userId":1,"exception":"[object] (ErrorException(code: 0): Trying to get property of non-object (View: /www/wwwroot/ssrpanel/resources/views/admin/trafficLog.blade.php) at /www/wwwroot/ssrpanel/storage/framework/views/e106c2d18bc753efb50c32dea88020023b84c2f7.php:77, ErrorException(code: 0): Trying to get property of non-object at /www/wwwroot/ssrpanel/storage/framework/views/e106c2d18bc753efb50c32dea88020023b84c2f7.php:77)

**Comment by thaizxj** [comment]
我是用户列表翻页报错
