### ISSUE TITLE
配置运行环境的时候出现这个问题，使用的是最新的代码，请问怎么解决？

### ISSUE THREAD

**Issue by maxwellhouse102** [ssrpanel/SSRPanel#1340]
[root@20 20.48.10.20]# php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
PHP Fatal error:  Uncaught Error: Class 'Log' not found in /www/20.48.10.20/app/Exceptions/Handler.php:45
Stack trace:
#0 /www/20.48.10.20/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(353): App\Exceptions\Handler->report(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#1 /www/20.48.10.20/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(132): Illuminate\Foundation\Console\Kernel->reportException(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#2 /www/20.48.10.20/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 {main}
  thrown in /www/20.48.10.20/app/Exceptions/Handler.php on line 45
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255

**Comment by Alan0429** [comment]
恭喜暴露ip
