### ISSUE TITLE
可以考虑弄个端口登入或者端口找回邮箱

### ISSUE THREAD

**Issue by Alan0429** [ssrpanel/SSRPanel#1341]
一些睿智用户，连自己邮箱都不记得，就记得个端口号，要后台来找！

**Comment by ssrpanel** [comment]
那些人，都是不老实的用户，建议你屏蔽临时邮箱

**Comment by ssrpanel** [comment]
marked

**Comment by mzfqy** [comment]
啥时候出白名单邮箱😁

**Comment by niyeyeqi** [comment]
那还不如弄个用户名

**Comment by vft9nesd** [comment]
要这有啥用？直接穷举端口，扫你所有的用户

**Comment by Alan0429** [comment]
> 要这有啥用？直接穷举端口，扫你所有的用户

验证码被你吃了

**Comment by Alan0429** [comment]
> 那些人，都是不老实的用户，建议你屏蔽临时邮箱

问题是他们都是qq邮箱，睿智到连邮箱基本格式都不知道，什么WWW.123456@QQ.COM什么QQ@122345.com....

**Comment by vft9nesd** [comment]
> > 要这有啥用？直接穷举端口，扫你所有的用户
> 
> 验证码被你吃了

别秀智商了，撞库的不活了？验证码除了增加点麻烦，拦得住什么？一嘴一个睿智，我真不知道你是一个什么样的睿智？别秀了好吗，回家好好种地，这里不适合你。

**Comment by Alan0429** [comment]
这我到没想过，好咯好咯

**Comment by ssrpanel** [comment]
那我？？？？关了吧？？？

**Comment by vft9nesd** [comment]
> 那我？？？？关了吧？？？

如果非要弄，可以端口+密码，但有这种奇怪需求的几乎没有，用的人其实连端口是啥都不懂，懂的人自然是不乖的那种
