### ISSUE TITLE
当面付的二维码优化

### ISSUE THREAD

**Issue by vft9nesd** [ssrpanel/SSRPanel#1346]
1、这种天蓝色也太丑了，可以改个配色。。
2、手机浏览器中可以点击图片跳转支付宝支付，地址即二维码的网址文本，省去保存相册扫描的步骤（微信中除外）
3、添加提示文本--手机可点击二维码唤起支付宝支付

**Comment by vft9nesd** [comment]
兼容微信浏览器的二维码
![image](https://user-images.githubusercontent.com/24932999/52864615-7677ad00-3175-11e9-8ee8-35dba2c4bc0d.png)
https://www.dedemao.com/alipay/wap_in_weixin.php

**Comment by vft9nesd** [comment]
微信会追踪，也对，微信是个危险的东西

**Comment by vft9nesd** [comment]
@ssrpanel 
这个样子怎么样，挺骚的吧
![image](https://user-images.githubusercontent.com/24932999/52867213-64990880-317b-11e9-8f06-6b773e41bfba.png)

把/SSRPanel/app/Http/Controllers/PaymentController.php的208行
`
$payment->qr_url = 'http://qr.liantu.com/api.php?text=' . $result . '&bg=ffffff&fg=1eabfc&pt=1c73bd&m=0&w=400&el=1&inpt=1eabfc';
`
改为
`
$payment->qr_url = 'http://qr.liantu.com/api.php?text=' . $result . '&bg=ffffff&fg=000000&pt=1c73bd&m=10&w=400&el=1&inpt=1eabfc&logo=http://t.alipayobjects.com/images/rmsweb/T1Fb0iXnJiXXXXXXXX.png';
`
即可
更新一下吧铁子

**Comment by mzfqy** [comment]
骚啊，已用上当面付，香

**Comment by vft9nesd** [comment]
此处的文字改成动态的吧，trimepay那个超八类网线就很骚 

![image](https://user-images.githubusercontent.com/24932999/52875872-6ae5af80-3190-11e9-8dd4-71704a225823.png)

**Comment by ssrpanel** [comment]
> 此处的文字改成动态的吧，trimepay那个超八类网线就很骚
> 
> ![image](https://user-images.githubusercontent.com/24932999/52875872-6ae5af80-3190-11e9-8dd4-71704a225823.png)

那个迟早进风控，如果可以的话店铺里最好上某个商品

**Comment by vft9nesd** [comment]
有道理，什么比较好？这个是当面付，没有店铺的

**Comment by ssrpanel** [comment]
我自定义一套假商品信息，餐饮类，会靠谱些？

**Comment by ssrpanel** [comment]
随机返回某个餐饮商品

**Comment by vft9nesd** [comment]
好像自己骗自己～支付宝检测机制肯定不是这样的吧

**Comment by vft9nesd** [comment]
管它呢，骚就够了，世界美食菜单，要不来个随机番号吧

**Comment by ssrpanel** [comment]
哈哈， 日了汪汪队，不要拆穿我

**Comment by ssrpanel** [comment]
这次不能像有赞那样公开了，不然真的又要被操烂

**Comment by vft9nesd** [comment]
草料api  样式很好看
 https://cli.im/api/qrcode/code?text=此处替换文本&mhid=4ULHCgG/nMghMHcrItVUMKs

但生成的不是直链图片，图片链接后面有个根据文本信息生成的key，不是md5，不知道是啥算法，也有可能加了密钥什么的，反正交给你了

**Comment by mynameiscaa** [comment]
> 骚啊，已用上当面付，香

怎么对接呀

**Comment by ssrpanel** [comment]
群里说
