### ISSUE TITLE
更新b535a25后访问，设置》系统设置，出现报错

### ISSUE THREAD

**Issue by Alan0429** [ssrpanel/SSRPanel#1347]
![tim 20190215230451](https://user-images.githubusercontent.com/46681198/52864869-1f260c80-3176-11e9-94a7-8866c4f95ebe.png)

**Comment by mzfqy** [comment]
我也是。。。

**Comment by mzfqy** [comment]
还有，你去.env把debug关掉，这个会漏配置文件

**Comment by Alan0429** [comment]
看到楼下大佬了，数据库手动执行以下命令即可
INSERT INTO `config` values ('87', 'is_f2fpay', 0);
INSERT INTO `config` VALUES ('88', 'f2fpay_app_id', '');
INSERT INTO `config` VALUES ('89', 'f2fpay_private_key', '');
INSERT INTO `config` VALUES ('90', 'f2fpay_public_key', '');
