### ISSUE TITLE
当面付对接教程

### ISSUE THREAD

**Issue by mzfqy** [ssrpanel/SSRPanel#1350]
前提：一个通过当面付审核的支付宝号，申请教程#1233
1.登录蚂蚁金服平台
https://open.alipay.com/platform/manageHome.htm
2.进入我的应用，如果你已经申请通过了当面付审核，就会显示一个应用2.0签约xx，点进去查看详情
https://openhome.alipay.com/platform/appManage.htm#/apps
3.左栏中可获取APPID，然后点击左栏应用信息，设置回调地址与应用网关为自己的网站域名
4.用openssl工具生成公钥与私钥
linux服务器执行
openssl
genrsa -out rsa_private_key.pem
rsa -in rsa_private_key.pem -pubout -out rsa_public_key.pem
exit
5.将rsa_public_key.pem与rsa_private_key.pem下载到本地保存好
5.点击网页中设置应用公钥，将rsa_public_key.pem中内容添加到其中
6.将得到的支付宝公钥和自己的rsa_private_key.pem中内容添加到面板设置里
应该可以了。

**Comment by vft9nesd** [comment]
散了散了，少一个是一个，不然风控了

**Comment by mzfqy** [comment]
有没有黑号卖的介绍个鸭

**Comment by mzfqy** [comment]
tg@mzfqy66

**Comment by ssrpanel** [comment]
哈哈哈，不能再公开了，不然像有赞云那样玩坏了
