### ISSUE TITLE
大佬们，你们使用什么ssr加密混淆组合？

### ISSUE THREAD

**Issue by Alan0429** [ssrpanel/SSRPanel#1351]
我目前使用，rc4-md5+auth_aes128_md5+plain
速度中等，16台服务器被封ip的只有2台，半年前，目前想改none+auth_aes128_md5+plain，不知道稳定性如何，速度很快，大佬们有没有推荐

**Comment by vft9nesd** [comment]
none origin plain

**Comment by ssrpanel** [comment]
rc4-md5+auth_aes128_md5+plain
速度中等，16台服务器被封ip的只有2台，说明你那个两个IP是处于高位段或者曾经进过墙，是要不使用tls就基本不会有事

**Comment by ssrpanel** [comment]
因为目前市面上所有可以找到的版本的ssr tls 那里有明显的致命缺陷
