### ISSUE TITLE
邮件频率是个大问题

### ISSUE THREAD

**Issue by Alan0429** [ssrpanel/SSRPanel#1354]
![tim 20190216095828](https://user-images.githubusercontent.com/46681198/52892859-950b9180-31d1-11e9-9f97-448bbbe1b034.png)
![tim 20190216095842](https://user-images.githubusercontent.com/46681198/52892860-95a42800-31d1-11e9-9dbb-56da057aec40.png)

**Comment by mzfqy** [comment]
gmail，请。。。。

**Comment by Alan0429** [comment]
用不起g企业版😂😂，普通版不能使用域名邮箱

**Comment by ssrpanel** [comment]
mailgun能骚一把吗？qq邮箱就算了
