### ISSUE TITLE
安卓手机端添加订阅地址无法更新出任何节点，客户端是广泛流传的ssr3.4.0.8，pc端更新正常

### ISSUE THREAD

**Issue by maxwellhouse102** [ssrpanel/SSRPanel#1356]
安卓手机端添加订阅地址无法更新出任何节点，客户端是广泛流传的ssr3.4.0.8，pc端更新正常

**Comment by maxwellhouse102** [comment]
试了其他issues上说的shadowsocksr-android-3.5.4也是不行

**Comment by maxwellhouse102** [comment]
各位大佬，求一个可订阅的安卓客户端

**Comment by MaHouyin** [comment]
我也发现了类似问题，安卓添加订阅后没有反应，但是后台会有订阅记录

把用户的订阅禁用，然后在客户端里添加订阅，显示没有可用节点，然后再启用订阅，更新一下客户端订阅就出现节点了。

这是个笨方法，但具体因为什么产生这个问题我也不知道。

**Comment by ssrpanel** [comment]
1.用宝塔： 关闭 open_dir 防跨域
2.用户和节点有相同的标签
3.不要存在v2ray 和 ssr 节点混合在一起的情况，因为安卓客户端没人更新了，并不支持混合

**Comment by ssrpanel** [comment]
4.订阅地址上ssl，就是https，不过这个通常仅限于mac端和iPhone端，安卓较少见ssl问题
