### ISSUE TITLE
关于积分的建议

### ISSUE THREAD

**Issue by 329928** [ssrpanel/SSRPanel#1357]
感觉做成手动签到会更加好点，总是有人问积分怎么获得。

另外现在是每隔多少小时登录一次获得积分，有用户反映不知道积分涨没涨，最好做个积分变动记录，放后台管理或者用户界面都行。

**Comment by 329928** [comment]
自己测试，并且在数据库里查询，有时候登录了的确没有增加积分，不知道为什么

**Comment by 329928** [comment]
> 自己测试，并且在数据库里查询，有时候登录了的确没有增加积分，不知道为什么

发现如果浏览器保存了账号密码，每次打开网站就自动登录进去的话，是没有积分的。
必须要在登录页输入账号密码登录进去才有积分。

但是大多数人都是会保存账号密码的吧

**Comment by lovage** [comment]
铜球

**Comment by ssrpanel** [comment]
> 自己测试，并且在数据库里查询，有时候登录了的确没有增加积分，不知道为什么

时间不到，登录100万次都不加。。

**Comment by ssrpanel** [comment]
> > 自己测试，并且在数据库里查询，有时候登录了的确没有增加积分，不知道为什么
> 
> 发现如果浏览器保存了账号密码，每次打开网站就自动登录进去的话，是没有积分的。
> 必须要在登录页输入账号密码登录进去才有积分。
> 
> 但是大多数人都是会保存账号密码的吧

这还真是一个坑
