### ISSUE TITLE
工单bug

### ISSUE THREAD

**Issue by Jinxs9** [ssrpanel/SSRPanel#1358]
回复工单成功后，如果文本输入过多，会出现后半部分文本不见的情况。
![image](https://user-images.githubusercontent.com/42931911/52896554-b5087880-3204-11e9-99e1-ee5ebc2f387f.png)

**Comment by lsbjkc** [comment]
我也遇到了
![image](https://user-images.githubusercontent.com/43370337/53999122-3c4e6980-417d-11e9-9580-40f38d582690.png)

**Comment by 329928** [comment]
> 我也遇到了
> ![image](https://user-images.githubusercontent.com/43370337/53999122-3c4e6980-417d-11e9-9580-40f38d582690.png)

对，像你这种复制粘贴的话还会带上原有样式。
