### ISSUE TITLE
当面付错误curl error 28 

### ISSUE THREAD

**Issue by littlesker** [ssrpanel/SSRPanel#1359]
创建订单失败：cURL error 28: Operation timed out after 10001 milliseconds with 0 out of 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
不知道是什么原因，数据库都导入了，强制更新到最新，目录权限设置www

**Comment by vft9nesd** [comment]
听说是证书权限问题
```
cd /www/wwwroot/SSRPanel/ca
cp cacert.pem /etc/pki/tls/certs/ca-bundle.crt
```

**Comment by littlesker** [comment]
@vft9nesd 还是不行 点那个支付宝当面付直接卡一会然后就失败

**Comment by mike631041** [comment]
配置好后不出二维码。

**Comment by vft9nesd** [comment]
50，留tg

**Comment by samac08** [comment]
> 配置好后不出二维码。
同样的问题 所有都正常 就是不能显示二维码

**Comment by mutebear** [comment]
> > 配置好后不出二维码。
> > 同样的问题 所有都正常 就是不能显示二维码

请问你有处理了吗，我也遇到了这个问题，不知是哪出错了。
