### ISSUE TITLE
Warning: require(/www/wwwroot/www.abc.com/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/www.abc.com/bootstrap/autoload.php on line 17

### ISSUE THREAD

**Issue by ilovebamboo** [ssrpanel/ssrpanel#136]
Warning: require(/www/wwwroot/www.abc.com/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/www.abc.com/bootstrap/autoload.php on line 17

Fatal error: require(): Failed opening required '/www/wwwroot/www.abc.com/bootstrap/../vendor/autoload.php' (include_path='.:/www/server/php/71/lib/php') in /www/wwwroot/www.abc.com/bootstrap/autoload.php on line 17

**Comment by ilovebamboo** [comment]
新版本安装就成这样了

**Comment by ssrpanel** [comment]
1.先编辑好config/database.php 数据库连接
2.执行 php composer.phar install
3.没毛病了
