### ISSUE TITLE
请问节点列表里的状态 1.00 1.03 1.01 是什么意思？

### ISSUE THREAD

**Issue by maxwellhouse102** [ssrpanel/SSRPanel#1360]
![image](https://user-images.githubusercontent.com/25824373/52898375-ef2f4580-3217-11e9-8916-9abb3937a828.png)

**Comment by maxwellhouse102** [comment]
![image](https://user-images.githubusercontent.com/25824373/52898371-dd4da280-3217-11e9-9c0b-7ff9529e3a8f.png)

**Comment by vft9nesd** [comment]
表示服务器要炸了  快关机或重启吧

**Comment by niyeyeqi** [comment]
被人打了，赶紧重启

**Comment by ssrpanel** [comment]
@vft9nesd @niyeyeqi 你们两个真是的
