### ISSUE TITLE
端口被释放的用户重新购买服务后不会自动分配端口

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#1362]
启用了代理禁用1个月的用户自动释放端口的情况下，如果该用户端口被释放，再次购买服务后不会重新分配可用端口，导致购买了服务显示代理启用但实际上还是用不了，因为端口是0

**Comment by ssrpanel** [comment]
这个我记得不存在问题啊？？？

**Comment by vft9nesd** [comment]
遇到过，我以为是bug，再一看，定时任务路径错了

**Comment by GaHoKwan** [comment]
过期端口释放能不能搞个时间设置，我想一个星期没续费就释放

**Comment by ssrpanel** [comment]
> 过期端口释放能不能搞个时间设置，我想一个星期没续费就释放

不建议这么操作，系统默认是1个月，其实1个月更合理

**Comment by 828768** [comment]
> 遇到过，我以为是bug，再一看，定时任务路径错了

定时任务正确的在跑的，要不然其他功能也不会正常

**Comment by 828768** [comment]
> 这个我记得不存在问题啊？？？

难道只有我一个人有这问题？你们都没遇到过么？

**Comment by GaHoKwan** [comment]
没有，实在不行就备份用户数据库直接完整重装吧

**Comment by 828768** [comment]
见鬼了，对比了原版源码，并没有涉及功能性的不同之处，日了狗了。
