### ISSUE TITLE
当面付错误  创建支付订单失败：支付宝返回数据被篡改。请检查网络是否安全！ 

### ISSUE THREAD

**Issue by 13221253358** [ssrpanel/SSRPanel#1363]
![canvas](https://user-images.githubusercontent.com/35331589/52900146-7a670600-322d-11e9-9707-fa789ccadc15.png)

**Comment by littlesker** [comment]
用的是宝塔吧？

**Comment by lusalem** [comment]
这个错误就是私钥和公钥没设置错误引起，自己重新配下。

**Comment by mlgexyz** [comment]
RSA用http://tool.chacuo.net/cryptrsakeyvalid测试过没有问题，现在找不到问题所在很尴尬，等待大佬指点迷津

**Comment by mlgexyz** [comment]
好了解决了，公钥换成支付宝的就行了

**Comment by 13221253358** [comment]
公钥换成支付宝的 创建订单报错

创建支付订单失败：Undefined index: qr_code

**Comment by mlgexyz** [comment]
网关和回调做了么？

**Comment by 13221253358** [comment]
网关和回调怎么设置

**Comment by mlgexyz** [comment]
不可说不可说，自己试吧，反正都开源了，不然教程全公开又得被国人玩坏

**Comment by yulewang** [comment]
网关不用填，回调去看api路径，稍微看一下代码。

另外实在不懂有什么可玩坏了的。payment这项目也1000多个stars，也都用的官方的api。

**Comment by mlgexyz** [comment]
@yulewang 有赞被玩坏就是个例子，接入的商户基本上全是SSRPanel的使用者（微小店那玩意本来早就是没人维护的状态，只是提现审计那边还有人守着而已，api更新是因为微商城的存在），f2f现在虽然规定上不传营业执照也可用，但如果到时候突然涌入大量无证用户的话，根据回调被风控的可能性很大。（毕竟SSRPanel非定制版现有的支付接口就这么几个，发卡的话有抽成，有赞的已经残废了，支付宝国际的审核机制又阻断了好些人，f2f可能是继有赞之后的最优选择）
至于star数这个概念，你觉得那些开机场的人有几成是有Gayhub账号的，更多的用户来源应该是那些博客上的小白向教程，只跟你讲执行这句代码就可以clone这个git项目，并不会有意地去引导阅读者去关注项目本身。

**Comment by cmtomkan310** [comment]
@yulewang 有问题请假，能否加个Q?

**Comment by cmtomkan310** [comment]
@mlgexyz 我按照支付宝rsa也不行，咋整？

**Comment by cmtomkan310** [comment]
@mlgexyz 同样的问题，能否私聊帮助下？

**Comment by cmtomkan310** [comment]
@mlgexyz 公钥这些已经用的支付宝的，但还是弹这个，帮助下？谢了

**Comment by mlgexyz** [comment]
@cmtomkan310 震惊！某G姓网站竟没有私聊功能😂

**Comment by cmtomkan310** [comment]
@mlgexyz 你还别说，找了半天真没有。。。咋整？加个Q？还是V？看你方便

**Comment by cmtomkan310** [comment]
@mlgexyz 本来想让你帮忙直接在这里说，估计胖虎不愿意，但是单聊吧

**Comment by mlgexyz** [comment]
> 
> 
> @mlgexyz 你还别说，找了半天真没有。。。咋整？加个Q？还是V？看你方便
https://t.me/mlgexyz

**Comment by wongyuehan** [comment]
回调也配置了为何创建支付订单失败：Undefined index: sign

**Comment by mlgexyz** [comment]
> 
> 
> 回调也配置了为何创建支付订单失败：Undefined index: sign

@wongyuehan ，创建订单失败和回调没有任何关系，回调只用于支付成功返回。

**Comment by wongyuehan** [comment]
创建支付订单失败：Undefined index: qr_code
