### ISSUE TITLE
大佬能不能把trimepay支付重新加入进去啊

### ISSUE THREAD

**Issue by banxianl08** [ssrpanel/SSRPanel#1364]
有攒微小店已挂，trimepay被移除，当面付签约需要营业执照 还有门头照审核，小白们更难搞了，希望把trimepay重新加入进去，让用户更有选择性

**Comment by ssrpanel** [comment]
trimepay 可以去他们官网找，他们有代码包；
当面付，我们留着自己玩，不教方法，省的被一群人又像 有赞 那样给操烂了
