### ISSUE TITLE
NAT节点端口都映射了，但是节点还是显示宕机

### ISSUE THREAD

**Issue by baiyou2014** [ssrpanel/SSRPanel#1366]
{
    "server": "0.0.0.0",
    "server_ipv6": "::",
    "server_port": 10791,
    "local_address": "127.0.0.1",
    "local_port": 51710,

    "password": "m",
    "method": "chacha20-ietf",
    "protocol": "auth_chain_a",
    "protocol_param": "",
    "obfs": "plain",
    "obfs_param": "",
    "speed_limit_per_con": 0,
    "speed_limit_per_user": 0,

    "additional_ports" : {
        "10801": {
            "passwd": "289124045",
            "method": "chacha20-ietf",
            "protocol": "auth_chain_a",
            "protocol_param": "#",
            "obfs": "plain",
            "obfs_param": ""
        }
    },
    "additional_ports_only" : true,
    "timeout": 120,
    "udp_timeout": 60,
    "dns_ipv6": false,
    "connect_verbose_info": 1,
    "redirect": ["www.amazon.com", "images-na.ssl-images-amazon.com", "m.media-amazon.com", "kdp.amazon.com", "php.net"],
    "fast_open": false
}

用的是CF的。ddns也解析了，就是前台总显示宕机

**Comment by vft9nesd** [comment]
![image](https://user-images.githubusercontent.com/24932999/53025025-2a8d7680-349b-11e9-8dca-c6f4e528f2c4.png)
