### ISSUE TITLE
f2fpay 错误

### ISSUE THREAD

**Issue by xiaoanweiwu** [ssrpanel/SSRPanel#1367]
![image](https://user-images.githubusercontent.com/28782855/52909358-65888200-32c2-11e9-9deb-6940fd438a5f.png)

**Comment by ssrpanel** [comment]
执行 php composer.phar install

**Comment by vft9nesd** [comment]
![image](https://user-images.githubusercontent.com/24932999/53025025-2a8d7680-349b-11e9-8dca-c6f4e528f2c4.png)
