### ISSUE TITLE
建议添加二维码订阅＋小火箭v2ray扫码加密问题

### ISSUE THREAD

**Issue by fyshaw** [ssrpanel/SSRPanel#1369]
目前很多v2ray客户端支持扫码订阅，胖虎兄可否像节点二维码那样添加一个订阅二维码，连复制订阅地址都省了，移动设备拿起来就扫甚是方便。
还有一个问题无解：无论面板里v2ray节点加密方式怎么设置，只要用Shadowrocket扫描节点二维码，扫出来统统是none，每次还得手动改，安卓和windows平台实测没有这个问题，请问各位大佬何解？谢谢！

**Comment by ssrpanel** [comment]
V2RAY 扫码出来是none是 小火箭的问题，目前无解，因为安卓和windows平台 ，有是v2rayN 的，我咨询过作者，都是自动适配加密方式的，因为他提供的解析不支持自定义加密方式。
