### ISSUE TITLE
20190215.sql的问题

### ISSUE THREAD

**Issue by jackyeow** [ssrpanel/SSRPanel#1370]
原来的config下面已经有84、85、86了，这次导入数据库20190215.sql里面还是添加84、85、86、87，提示重复啊！
![6238046](https://user-images.githubusercontent.com/10632793/52928701-261e6c00-337c-11e9-9319-52a332b5df16.jpg)

![6283171](https://user-images.githubusercontent.com/10632793/52928705-29195c80-337c-11e9-9e99-2c26fbb15384.jpg)

**Comment by ssrpanel** [comment]
我说了，旧版本别升级，你那个是带有trimepay的版本，trimepay我已经移除了

**Comment by vft9nesd** [comment]
![image](https://user-images.githubusercontent.com/24932999/53025025-2a8d7680-349b-11e9-8dca-c6f4e528f2c4.png)
