### ISSUE TITLE
近期版本的翻页问题

### ISSUE THREAD

**Issue by Dennishaha** [ssrpanel/SSRPanel#1371]
近期版本用户页翻页会弹出错误，如下
![a1](https://user-images.githubusercontent.com/38273998/52930137-3d605800-3382-11e9-9aea-52a59fdfbb60.jpg)
![a2](https://user-images.githubusercontent.com/38273998/52930136-3d605800-3382-11e9-918d-d9147bb4c23b.jpg)
![a3](https://user-images.githubusercontent.com/38273998/52930145-3fc2b200-3382-11e9-9dc5-f3e22ddb0b3e.jpg)
![a4](https://user-images.githubusercontent.com/38273998/52930142-3fc2b200-3382-11e9-81d6-704488ac95a9.jpg)

**Comment by niyeyeqi** [comment]
我上次也遇到了，应该是删除用户的bug，你检查一下每个表的id，关联的id是否能对的上。我上次是订阅码和用户id有几个重复，排查出来的

**Comment by garhing** [comment]
因为没有执行自动生成订阅码

**Comment by garhing** [comment]
php artisan upgradeUserSubscribe

**Comment by Dennishaha** [comment]
> php artisan upgradeUserSubscribe

正解 感谢大佬们！
