### ISSUE TITLE
当面付错误：支付宝返回数据被篡改。请检查网络是否安全！

### ISSUE THREAD

**Issue by cmtomkan310** [ssrpanel/SSRPanel#1373]
#1363 我跟他还不太一样，所有配置检查各底掉，没问题！公钥私钥回调等等。还请大佬指点一二

**Comment by vft9nesd** [comment]
50解决

**Comment by cmtomkan310** [comment]
@vft9nesd 30吧

**Comment by mzfqy** [comment]
40

**Comment by vft9nesd** [comment]
哈哈，你这恶意竞争

**Comment by cmtomkan310** [comment]
@mzfqy 40第一次

**Comment by vft9nesd** [comment]
100，一分价钱一分货

**Comment by cmtomkan310** [comment]
@vft9nesd 那我不如找胖虎

**Comment by vft9nesd** [comment]
哈哈哈，大家都逗你玩呢，留下tg，12点后帮你看看

**Comment by cmtomkan310** [comment]
@vft9nesd 能不能早点，昨晚就研究到2点，@cmtomkan加我吧

**Comment by cmtomkan310** [comment]
@vft9nesd 一语点醒梦中人，可以close了

**Comment by 13221253358** [comment]
当面付错误这是什么情况
![canvas](https://user-images.githubusercontent.com/35331589/53296722-73537f80-384d-11e9-88ee-faf328073fad.png)

**Comment by mlch911** [comment]
老哥我也是，你怎么解决的啊？之前还用着没问题，最近也显示不了二维码了

**Comment by wongyuehan** [comment]
创建支付订单失败：Undefined index: sign
