### ISSUE TITLE
配置好.env文件为会登录页面还提示缺失.env.example

### ISSUE THREAD

**Issue by caohan345** [ssrpanel/SSRPanel#1374]

**Comment by ssrpanel** [comment]
no pic u say a j9

**Comment by caohan345** [comment]
![image](https://user-images.githubusercontent.com/46741516/53001677-33178a00-3466-11e9-9a14-7c22128de03c.png)

**Comment by ssrpanel** [comment]
cd /www/wwwroot/ssrpanel
chown -R www:www ./*

**Comment by PlaneV** [comment]
这个问题766兄解决了
https://github.com/ssrpanel/SSRPanel/issues/1396
