### ISSUE TITLE
建议银鹭花生莲子粥改成商品自定义的名称

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#1377]
虽然风控更多的是针对收款账号，但现在都是银鹭花生莲子粥，而且还是全国各地的付款，很明显是假的，建议给现在的商品加个必填的别名属性，机场主按照自己申请的店特色自由创意，也不用让用户看见，创建订单的时候把别名提交给马云看。

**Comment by vft9nesd** [comment]
自慰而已，不用在意，风控不会因为这个的
