### ISSUE TITLE
为什么总提示权限不足无法写入.env要么就是缺失.env.example

### ISSUE THREAD

**Issue by caohan345** [ssrpanel/SSRPanel#1379]
![image](https://user-images.githubusercontent.com/46741516/53013442-c8c01300-3480-11e9-890d-bac78a7fe108.png)

**Comment by vft9nesd** [comment]
![image](https://user-images.githubusercontent.com/24932999/53025025-2a8d7680-349b-11e9-8dca-c6f4e528f2c4.png)

**Comment by PlaneV** [comment]
766兄解决了
https://github.com/ssrpanel/SSRPanel/issues/1396
