### ISSUE TITLE
关于1号清零

### ISSUE THREAD

**Issue by ppllpig** [ssrpanel/ssrpanel#138]
对待年付用户1号清零很合适，对于月付用户就有点那什么了
能否套餐设置   月付不重置（可选）？

**Comment by ssrpanel** [comment]
@ppllpig 用户管理这块我还要改。要加入：
1.手动给用户冲余额
2.商品这块我也要改

**Comment by ssrpanel** [comment]
月付1号清零有个问题：假设8月25号买了月付50G，已使用40G，9月1号清零就又有50G了，是个逻辑BUG。。。我得研究下咋改

**Comment by ssrpanel** [comment]
暂时别关闭这个issue，改完我来回复

**Comment by ssrpanel** [comment]
@ppllpig 求写个serverstatus教程。。。支付已经有小伙伴提代码了

**Comment by ssrpanel** [comment]
@ppllpig 大于30天的做减法如何？ 怎么减？

**Comment by ppllpig** [comment]
@ssrpanel 没用逗比的那个，用的这个手动后端加修改前端
https://lala.im/1668.html
