### ISSUE TITLE
胖虎大佬，更新新版本后邮件无法发送，而且报的异常信息还不停改变

### ISSUE THREAD

**Issue by mmliuman22** [ssrpanel/SSRPanel#1380]
主要的异常有：
1.Connection to ssl://smtp.gmail.com:465 Timed Out
2.Expected response code 250 but got code "530", with message "530-5.5.1 Authentication Required. Lear..

**Comment by vft9nesd** [comment]
![image](https://user-images.githubusercontent.com/24932999/53025606-24e46080-349c-11e9-9506-db08865db035.png)
