### ISSUE TITLE
求助日志报错Symfony\Component\Debug\Exception\FatalErrorException

### ISSUE THREAD

**Issue by ywly** [ssrpanel/SSRPanel#1381]
求助大佬日志报错这个，请问怎么解决

error | local | 2019-02-20   19:51:16 | Allowed memory size of 134217728 bytes exhausted (tried to allocate   49184448 bytes) {"userId":1,"exception":"[object]   (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed   memory size of 134217728 bytes exhausted (tried to allocate 49184448 bytes)   at   /www/wwwroot/www.ph147.ml/ssrpanel/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:50)
-- | -- | -- | --
info | local | 2019-02-20   19:51:16 | 异常来源：Symfony\Component\Debug\Exception\FatalErrorException

**Comment by ywly** [comment]
还有这个，哪位大佬能说说这个怎么解决？影响大吗？

info	local	2019-02-20 20:17:15	异常来源：Symfony\Component\HttpKernel\Exception\NotFoundHttpException

**Comment by vft9nesd** [comment]
把你的php memory_limit设置大点
