### ISSUE TITLE
提一个小建议

### ISSUE THREAD

**Issue by AntonyWilsonClub** [ssrpanel/SSRPanel#1382]
提个小建议，能不能把邮箱配置做成图形界面在管理员面板里，这样方便设置些

**Comment by ssrpanel** [comment]
我也想啊，可是实力不允许啊

**Comment by AntonyWilsonClub** [comment]
我晓得的这个这个项目有邮件的配置界面以及配置参数，测试简单配置后就可以正常使用，地址https://github.com/HFO4/Cloudreve/tree/1.0.3
邮件方面的设置应该在/application/index中的model和view/admin中的mail类文件
不知道能不能给大佬提供下参考
