### ISSUE TITLE
真实。。

### ISSUE THREAD

**Issue by mzfqy** [ssrpanel/SSRPanel#1384]
服务器太多导致个人中心强烈卡顿
建议：单独写个服务器列表界面

**Comment by cmtomkan310** [comment]
这个问题的确存在！

**Comment by ssrpanel** [comment]
是有多少？？？

**Comment by ssrpanel** [comment]
@mzfqy 你在群里吗？截图我看看卡了多久

**Comment by cmtomkan310** [comment]
@ssrpanel 我有20个，打开个人中心会有2秒的卡顿，然后一下子刷出所有节点

**Comment by mzfqy** [comment]
@ssrpanel 我不在。。。40+节点卡5s左右 但是苹果不卡

**Comment by 329928** [comment]
> 是有多少？？？

这个问题确实存在，我单独列出了一页节点列表。现在每次打开，卡4秒
![image](https://user-images.githubusercontent.com/42931911/53145837-c8d52580-35dc-11e9-8bbd-d0c30d0ad541.png)

**Comment by ssrpanel** [comment]
已分离
