### ISSUE TITLE
真的很想解决这个问题 望大佬解答

### ISSUE THREAD

**Issue by redtechma** [ssrpanel/SSRPanel#1386]
File "/root/shadowsocksr/db_transfer.py", line 261, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocksr/db_transfer.py", line 377, in pull_db_all_user
    db=self.cfg["db"], charset='utf8')
  File "/usr/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 327, in __init__
    self.connect()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 629, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'xxxxxxxx' ([Errno 110] Connection timed out)")
显示对接数据库 失败 
问题是数据库权限 端口 防火墙  我检查了太多遍了 甚至重装了 很多遍 但是一直显示这样无法对接 却能正常上网 计算流量  也只有这一台 出现这个怪事
望各位大佬给点建议

**Comment by vft9nesd** [comment]
Can't connect to MySQL server on u'xxxxxxxx'

**Comment by redtechma** [comment]
> Can't connect to MySQL server on u'xxxxxxxx'

大佬 我搞了两天 数据库权限 端口 防火墙 重装 没用 还要检查什么吗 问题是同样其他vps没一点事

**Comment by vft9nesd** [comment]
1、二者不通
2、密码错了
3、端口没开

**Comment by redtechma** [comment]
> 1、二者不通
> 2、密码错了
> 3、端口没开

谢谢 密码端口错了感觉不可能能正常外网 二者不通不解 
 而且我的系统定时日志设置是正常的 但是一直显示
![image](https://user-images.githubusercontent.com/38977155/53150149-d7c2d480-35ea-11e9-9ae1-4384f22cf19f.png)
异常来源：Symfony\Component\HttpKernel\Exception\NotFoundHttpException

**Comment by cyanogenic** [comment]
> > 1、二者不通
> > 2、密码错了
> > 3、端口没开
> 
> 谢谢 密码端口错了感觉不可能能正常外网 二者不通不解

一台机器ping另一台看看能不能ping通

**Comment by caohan345** [comment]
Pymysql

**Comment by redtechma** [comment]
> Pymysql
谢谢 大神 请问具体怎么操作？

**Comment by vft9nesd** [comment]
pip install pymysql  但你这不想是pymysql 的问题  是连不上数据库

**Comment by ssrpanel** [comment]
wiki不看，关闭

**Comment by redtechma** [comment]
> wiki不看，关闭

胖虎大哥 我看了wiki几遍 google了两天 才来问的 不可能没注意 你能告诉我具体在哪里吗
