### ISSUE TITLE
Undefined index: website_security_code

### ISSUE THREAD

**Issue by kk2007yx** [ssrpanel/SSRPanel#1387]
更新之后出现如题，怎么解决？

**Comment by kk2007yx** [comment]
我知道了！之前只有插入了f2p的 88项已经存在，改成91手动插入就好了！如下
INSERT INTO `config` VALUES ('91', 'website_security_code', '')

**Comment by hongluoluo** [comment]
你说的这个是什么啊，在哪里操作的，我也遇到同样的问题了

**Comment by NeedforGit** [comment]
> 我知道了！之前只有插入了f2p的 88项已经存在，改成91手动插入就好了！如下
> INSERT INTO `config` VALUES ('91', 'website_security_code', '')

具体怎么修复啊，我也遇到了这个问题！

**Comment by NeedforGit** [comment]
> 你说的这个是什么啊，在哪里操作的，我也遇到同样的问题了

我已经解决了，很简单，导入最新的注册表sql就行了
