### ISSUE TITLE
邮件配置图形化的思路

### ISSUE THREAD

**Issue by AntonyWilsonClub** [ssrpanel/SSRPanel#1388]
我晓得的这个这个项目有邮件的配置界面以及配置参数，测试简单配置后就可以正常使用，地址https://github.com/HFO4/Cloudreve/tree/1.0.3
邮件方面的设置应该在/application/index中的model和view/admin中的mail类文件
不知道能不能给大佬提供下参考

**Comment by cmmdwl** [comment]
这个不是larvel的呢。。
