### ISSUE TITLE
尽快把关键字过滤,域名(支持通配符)功能加上

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#139]
@ssrpanel 
https://doub.io/shell-jc2/  我看了这个脚本里面有支持关键字屏蔽的,     还没研究如何实现的,看看@lifespy有没有时间看看怎么实现的,然后分享下.

**Comment by ssrpanel** [comment]
日，还有人用gov.cn邮箱注册？？？？

**Comment by ssrpanel** [comment]
这个太傻逼了吧。

**Comment by 1021435278** [comment]
还有更弱智的发钓鱼邮件给我的yahoo邮箱, 我笑的肚子都疼.
我假装登录了, 密码你猜我输入了什么?  fuckyoudoyouhappy....

**Comment by ssrpanel** [comment]
@1021435278 自建邮局是不是可以伪造邮件发件地址，比如 我自建邮局，然后发件email地址变成 admin@baidu.com ？

**Comment by 1021435278** [comment]
@ssrpanel   不可以, 必须是真实的邮件地址才可收到, **你可以伪造发信者, 但是收信者邮箱必须真实存在才能收到验证码,这就是自建邮局的好处.** 为了保证进收件箱 dkim/spf/rrdns记录都做了, 甚至变态的DMAC记录也要考虑做不做.

当然你牛逼可以拥有整个DNS ROOT SERVER管理权,随便你改, 做到这点我认栽.

邮件是个很庞大的话题, 做外贸的因为发开发信研究过一段时间, 但是目前很多邮件漏洞已经被封堵住了, 比如很多主机封25端口就是为了抵抗垃圾邮件做的最基本手段, 目前垃圾邮件到达率越来越低,更别说打开率了.

**Comment by 1021435278** [comment]
关于网络安全的话题很深入的,不过发展到今天大部分漏洞都被弥补了, 出错的一般是自己犯错. 比如你现在这个系统, 可以通过实名认证, 电话真实认证后才能使用这个系统.

记得我曾经提过issue要求你把默认生成密码加强吗?  所以我仍然建议你在下个更新的版本把默认生成的密码改为8位以上.

**Comment by lifespy** [comment]
你说的哪个密码，我可以修改了提交过来 @1021435278

**Comment by 1021435278** [comment]
@lifespy 

用户注册时候强制密码长度/大小等.
ssr密码默认生成最少8位.

**Comment by 1021435278** [comment]
刚看了tg群里的, 我的妈呀,还测试下了, 真的可以注册. http://www.jianshu.com/p/0b43457927b4

我真没想到有人还在用asp的邮件系统, 算我蠢.....

**Comment by 1021435278** [comment]
@lifespy 

用户注册时候强制密码长度/大小等.
ssr密码默认生成最少8位且不可更改低于八位.
增加个重试密码次数超过5次自动锁定2个小时, 这样也强迫用户记住登录密码.
