### ISSUE TITLE
安全登录配置后，登录不了后台

### ISSUE THREAD

**Issue by limho0202** [ssrpanel/SSRPanel#1390]
/login?securityCode=zhf8xwae 输入账号密码登录后跳转到 /login 报404错误。

**Comment by kk2007yx** [comment]
我也是 直接404 所以安全码一直空着

**Comment by redtechma** [comment]
> /login?securityCode=zhf8xwae 输入账号密码登录后跳转到 /login 报404错误。

大哥 你是怎么解决的？

**Comment by kk2007yx** [comment]
你在源码上应该看得懂安全码所在数据库吧  然后在数据库里 找到安全码这项 把安全码删掉保存 之后 就能正常打开后台

**Comment by redtechma** [comment]
> 你在源码上应该看得懂安全码所在数据库吧 然后在数据库里 找到安全码这项 把安全码删掉保存 之后 就能正常打开后台

谢谢及时解答 小白一个 有没有具体路径

**Comment by redtechma** [comment]
> 你在源码上应该看得懂安全码所在数据库吧 然后在数据库里 找到安全码这项 把安全码删掉保存 之后 就能正常打开后台

ok 找到了 谢谢啊 安全码具体是怎么登陆的 你知道吗

**Comment by kk2007yx** [comment]
> > 你在源码上应该看得懂安全码所在数据库吧 然后在数据库里 找到安全码这项 把安全码删掉保存 之后 就能正常打开后台
> 
> ok 找到了 谢谢啊 安全码具体是怎么登陆的 你知道吗

我也不知道，他们说的方法我试了 还是404  所以一直没用这个功能
