### ISSUE TITLE
用户流量叠加问题

### ISSUE THREAD

**Issue by ZhilinChris** [ssrpanel/SSRPanel#1393]
示例：
用户购买A套餐（内含100G流量）到期后，变换B套餐（内含50G流量），此时用户的流量会变成150G。

个人理解：
从A切换到B之后，就是B到标准，不应该为总和。
不知道胖虎大大是有意为之还是bug。

**Comment by ZhilinChris** [comment]
问了朋友之后，好像他那边可以覆盖，有可能是个体问题。

**Comment by vft9nesd** [comment]
套餐覆盖流量包叠加

**Comment by cmtomkan310** [comment]
楼上正解
