### ISSUE TITLE
缺失标准配置文件.env.example

### ISSUE THREAD

**Issue by 766** [ssrpanel/SSRPanel#1396]
![image](https://user-images.githubusercontent.com/6436579/53283077-db399580-377b-11e9-95d3-8f4a644ae0dd.png)

chown -R www:www ssrpanel
chmod -R a+x ssrpanel
都执行过了

环境 lnmp  php7.2 + nginx1.14 + mysql 5.5

**Comment by 766** [comment]
自己解决了，lnmp的防止跨目录导致的

**Comment by 766** [comment]
自己解决了，lnmp 的防止跨目录导致的

**Comment by 766** [comment]
有一个新的问题搞不定了：安装完之后可以跳转登陆，也登陆成功了，但是随便点击几个页面就又跳转到了install.php 然后还是提示.env要么就是缺失.env.example 刷新几下就会提示已经安装过 重新安装删除.env 的提示

**Comment by PlaneV** [comment]
lnmp设置方法
https://lnmp.org/faq/lnmp-vhost-add-howto.html#user.ini

**Comment by PlaneV** [comment]
> 有一个新的问题搞不定了：安装完之后可以跳转登陆，也登陆成功了，但是随便点击几个页面就又跳转到了install.php 然后还是提示.env要么就是缺失.env.example 刷新几下就会提示已经安装过 重新安装删除.env 的提示

我还没遇到，你要好好研究下了[手动捂脸]

**Comment by 766** [comment]
> 有一个新的问题搞不定了：安装完之后可以跳转登陆，也登陆成功了，但是随便点击几个页面就又跳转到了install.php 然后还是提示.env要么就是缺失.env.example 刷新几下就会提示已经安装过 重新安装删除.env 的提示

shit 缓存导致的

**Comment by PlaneV** [comment]
> > 有一个新的问题搞不定了：安装完之后可以跳转登陆，也登陆成功了，但是随便点击几个页面就又跳转到了install.php 然后还是提示.env要么就是缺失.env.example 刷新几下就会提示已经安装过 重新安装删除.env 的提示
> 
> shit 缓存导致的

牛逼，这么快就解决了

**Comment by 766** [comment]
> > > 有一个新的问题搞不定了：安装完之后可以跳转登陆，也登陆成功了，但是随便点击几个页面就又跳转到了install.php 然后还是提示.env要么就是缺失.env.example 刷新几下就会提示已经安装过 重新安装删除.env 的提示
> > 
> > 
> > shit 缓存导致的
> 
> 牛逼，这么快就解决了

哈哈哈，抱着试试看的态度没想到还真是

**Comment by ssrpanel** [comment]
100%用宝塔了

**Comment by KtQiu** [comment]
> 自己解决了，lnmp 的防止跨目录导致的

你是怎么解决的？直接修改.user.ini吗。我改了但是还是不能用

**Comment by 766** [comment]
> > 自己解决了，lnmp 的防止跨目录导致的
> 
> 你是怎么解决的？直接修改.user.ini吗。我改了但是还是不能用

删掉就好了
