### ISSUE TITLE
更新4133432后出现报错

### ISSUE THREAD

**Issue by Alan0429** [ssrpanel/SSRPanel#1397]
![tim 20190223155504](https://user-images.githubusercontent.com/46681198/53283571-81d56480-3783-11e9-9c5d-1d8f2f5f5382.png)

**Comment by niyeyeqi** [comment]
导入数据库

**Comment by Alan0429** [comment]
> 导入数据库

已经导入了数据库的了，经过查明是写入数据库的文件里面的id冲突了
INSERT INTO `config` VALUES ('88', 'website_security_code', '');
88是f2fpay_app_id
把f2fpay_app_id改写到89，往下推，88填入website_security_code，解决问题
