### ISSUE TITLE
面板首页期望 

### ISSUE THREAD

**Issue by vft9nesd** [ssrpanel/SSRPanel#1398]
- 1、节点影响首页载入时间，如果独立页面就成魔改了，难看
可以先展示首页框架，节点可以一个一个的放出，美观又动态

- 2、节点分组展示

- 3、公告可修改，对接数据库存储吧，文章功能，就可以割掉了

- 4、扁平化风格

- 5、主题配色，背景等（如果支持主题框架模板diy，又是一个业务）

- 6、这应该是个比较长的过程

- 7、没有皮的机场，不叫机场

**Comment by mzfqy** [comment]
Mark

**Comment by ssrpanel** [comment]
1.魔改有些优点应当吸收，首页我目前已经在着手改造了
2.等改
3.等改，文章不移除，两者只是一个类型字段的区别，等加markdown编辑器
4.风格改不来，目前的响应式布局兼容手机端（这个是主要目的）
5.会改的都自己改了，不会的永远不会，模板主题化配置那种的话，等等，毕竟对我来说改皮费时费力还不讨好，对于我个人来说需求接近0（当然主要是0收益=没意义）
6.什么j8？
7.这个本来定位就是一个账号管理系统，而不是机场
