### ISSUE TITLE
ss go最新版貌似有bug, 上报的用户id初始使用0开始

### ISSUE THREAD

**Issue by niyeyeqi** [ssrpanel/SSRPanel#1401]
![tim 20190224204613](https://user-images.githubusercontent.com/31157068/53299450-3e5b2300-3875-11e9-8058-ff8c09caac1b.png)
user_id面1的是我手动改的，下面是上报的没改的

**Comment by maxwellhouse102** [comment]
为什么我用的GO版不能上报IP？你用的是哪个版本的面板？

**Comment by ssrpanel** [comment]
v2ray吗？

**Comment by niyeyeqi** [comment]
ss的，v2的是压根上报不了
@ssrpanel

**Comment by ssrpanel** [comment]
不，SS GO 可以上报IP，不然我发频道里那个图是假的吗？
V2 作者已经也改进上报IP了。我还没有测试
