### ISSUE TITLE
Access Controller +Access Point 模式

### ISSUE THREAD

**Issue by bickernwong** [ssrpanel/SSRPanel#1403]
用AC来集中化控制所有服务器节点AP，负责管理所有AP，对AP管理包括：下发配置、修改相关配置参数、接入数量控制、把新连接上的用户分配给使用人数最少的那个AP。

**Comment by ssrpanel** [comment]
what？

**Comment by bickernwong** [comment]
> what？

比如10台日本的服务器组成一个虚拟的日本节点，当用户连接日本虚拟节点时，AC就把刚刚连上的用户分派到用户数量最少的服务器上

**Comment by ssrpanel** [comment]
嗯，想法很好，很商业化，请先预付定制款人民币10万元整

**Comment by cmmdwl** [comment]
这。。。已经不是ssr服务器能解决的了，可能要客户端也要定制。。。。
目前服务器是把节点下发，除非未来节点时时下发，不然有点难解决服务器负载问题呢

**Comment by cmmdwl** [comment]
我觉得客户端还能提示服务器负载是否很高，让用户选择连入。。

**Comment by niyeyeqi** [comment]
负载均衡？如果是的话v2自带的就可以了，看官方的文档去，集成在一起的话就像胖虎大佬说的一样，10w

**Comment by cmmdwl** [comment]
@niyeyeqi 我和iss主的意思是服务器的负载均衡，并非客户端的负载均衡
客户端的负载均衡并不一定回均衡，因为客户端有效连接延迟低的服务器
iss的意思可能是节点汇报信息给服务器，用户访问服务器服务器下发负载最轻的服务器

**Comment by niyeyeqi** [comment]
v2还分客户端？

**Comment by ssrpanel** [comment]
> 负载均衡？如果是的话v2自带的就可以了，看官方的文档去，集成在客户端的话就像胖虎大佬说的一样，10w

10W我都嫌少。
