### ISSUE TITLE
流量监控不显示

### ISSUE THREAD

**Issue by xiaoanweiwu** [ssrpanel/ssrpanel#141]
已经搭建使用几天了，流量监控和已用流量还是不显示

<img width="386" alt="qq20171128-113550 2x" src="https://user-images.githubusercontent.com/28782855/33301360-5b95c92a-d430-11e7-8b16-eb37ccc8b486.png">
<img width="934" alt="qq20171128-113601 2x" src="https://user-images.githubusercontent.com/28782855/33301362-5e17ad1c-d430-11e7-8988-bf1c9c1da8a2.png">
<img width="247" alt="qq20171128-113609 2x" src="https://user-images.githubusercontent.com/28782855/33301365-626a8b32-d430-11e7-8dad-5e583c8d7e4d.png">

**Comment by ssrpanel** [comment]
@xiaoanweiwu 看项目首页，你肯定是漏了定时任务了

**Comment by ssrpanel** [comment]
如果定时任务也跑起来了，就去看一下日志，日志位于storage/logs/laravel-XXXX(日期)，看一下最新的那个是不是报错了。如果报错了，可能是数据库漏表或者漏字段了，备份一下user表和ss_node表，然后删除ssrpanel数据库中所有的表，重建一下，再导入备份数据
