### ISSUE TITLE
搭建完成 插入数据库错误

### ISSUE THREAD

**Issue by ramber2000** [ssrpanel/SSRPanel#1412]
按照wiki搭建的 数据库也设置成utf8mb4 COLLATE utf8mb4_unicode_ci了 可插入数据的时候可用流量那插入的值跟实际不一样 可以说说完全错误 
比如填入1024 -1024 100 250 等值 再返回用户列表 用户的可用流量显示为0  插入-50 返回用户列表显示为-2GB  这是数据库编码的问题吗？mysql数据库本事没做修改 应该是utf8的编码。
![1024](https://user-images.githubusercontent.com/10754721/53548271-0fda9200-3b6c-11e9-8f21-58fb5c011587.jpg)
这是填入的时候的值
![1024-0](https://user-images.githubusercontent.com/10754721/53548281-1406af80-3b6c-11e9-891b-dbaee71b8f4e.jpg)
这是保存后 返回用户列表时候显示的值 再进入编辑还是显示0.。。。。。

**Comment by ssrpanel** [comment]
还可以插入 -50 吗？？？？？？？

**Comment by ramber2000** [comment]
没提示错误 因为正常插入有些正数 成功后 就会显示-2GB 这种格式 所以就尝试插入-50试试看 。。
结果一样 还是显示0 感觉是在数值转换的过程出现错误了？

**Comment by ramber2000** [comment]
另外 单链接限速和单用户限速那里 默认生成用户后 再点击编辑则会变为 -2147483648  希望这个能有所帮助

**Comment by ssrpanel** [comment]
> 没提示错误 因为正常插入有些正数 成功后 就会显示-2GB 这种格式 所以就尝试插入-50试试看 。。
> 结果一样 还是显示0 感觉是在数值转换的过程出现错误了？

我没有碰到过，真的挺奇怪

**Comment by ssrpanel** [comment]
> 另外 单链接限速和单用户限速那里 默认生成用户后 再点击编辑则会变为 -2147483648 希望这个能有所帮助

你的版本是一件包吧。没遇到过

**Comment by ramber2000** [comment]
不是一键安装的 自己手动安装的 重装过几次数据库了 都这样。。
