### ISSUE TITLE
更新数据库错误！

### ISSUE THREAD

**Issue by cmtomkan310** [ssrpanel/SSRPanel#1413]
![image](https://user-images.githubusercontent.com/38905231/53549318-dfe0be00-3b6e-11e9-8496-b7e80a48b4b8.png)

**Comment by cmtomkan310** [comment]
可以close

**Comment by kk2007yx** [comment]
> 可以close

解决了吗

**Comment by cmtomkan310** [comment]
@kk2007yx 必须的

**Comment by kk2007yx** [comment]
> @kk2007yx 必须的

可以告诉我怎么解决的吗 我这边还是错误 手动清空数据表也不成功

**Comment by cmtomkan310** [comment]
@kk2007yx 我就是清空弄的啊

**Comment by kk2007yx** [comment]
> @kk2007yx 我就是清空弄的啊

为什么我不可以？

**Comment by cmtomkan310** [comment]
@kk2007yx 那你就手动插入数据，不就4条吗

**Comment by kk2007yx** [comment]
> @kk2007yx 那你就手动插入数据，不就4条吗

可以把你已经插入好的那个数据表截图给我吗？ 非常感谢  因为我手动插入也是错误

**Comment by kk2007yx** [comment]
> @kk2007yx 那你就手动插入数据，不就4条吗

我已经知道了！

**Comment by cmtomkan310** [comment]
![image](https://user-images.githubusercontent.com/38905231/53615665-fdb72d00-3c19-11e9-9cd7-e896c59c6afe.png)

**Comment by ssrpanel** [comment]
旧版本 level 表里有 created_at updated_at 字段，这两个字段很早就被移除了，需要手动删除这两个字段
