### ISSUE TITLE
折扣券算金额3位数，导致支付宝创建订单失败

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#1414]
最后金额应该四舍五入成2位小数
![image](https://user-images.githubusercontent.com/6386202/53550047-bf196800-3b70-11e9-885e-cec2f13ab55e.png)

**Comment by ssrpanel** [comment]
当面付吗？

**Comment by 828768** [comment]
> 当面付吗？

是的，合计金额是3位小数的，创建订单失败，应该四舍五入成2位数

**Comment by ssrpanel** [comment]
fixed
