### ISSUE TITLE
邮件推送的错误代码，已查，但不知道怎么解决

### ISSUE THREAD

**Issue by Zhangziheng1** [ssrpanel/SSRPanel#1415]
胖虎大哥，我认真的查了您说的队列，也慢慢明白。但是我遇到问题了。

【Expected response code 250 but got code "503", with message "503 Bad sequence of commands [@sm190202]"】
这是错误代码，发送邮件的时候。我去【https://www.mailenable.com/kb/content/article.asp?ID=ME020032】查到503错误是因为： 【503错误的命令序列
错误说明：该错误表示远程客户端已向服务器发送的命令不是SMTP服务的正确和已识别顺序。

错误解决方案：  使用SMTP活动日志查找命令的内容以及按正确顺序发出的命令。】

胖虎大哥，能指导一下不？

**Comment by Zhangziheng1** [comment]
![_20190228161227](https://user-images.githubusercontent.com/43085710/53551237-c55d1380-3b73-11e9-9b13-945d92e1ecfb.png)

**Comment by ssrpanel** [comment]
阿里云发邮件？？？？如果你服务器也是阿里云，要开端口的 22 465 等几个端口

**Comment by ssrpanel** [comment]
还有你发邮件那里要允许stmp发送

**Comment by Zhangziheng1** [comment]
阿里云的服务器端口开了。设置的是全部TCP+udp的1:65535

**Comment by Zhangziheng1** [comment]
发邮件的，是指阿里云的邮件推送吗？
我之前在胖虎哥没有更新队列发邮件的时候，邮件是好的，配置都是没问题的。

**Comment by Zhangziheng1** [comment]
我找到问题的原因了。查了一下是因为队列监听，更新配置文件以后需要重启队列。所以一直都是一个错误。
执行 ：php artisan queue:work --daemon
然后停止，再执行 sh queue.sh

**Comment by ssrpanel** [comment]
ps aux | grep queue
找到 它
kill 掉对应的pid

重新 sh queue.sh

具体可以翻一下以前的close 的issues
