### ISSUE TITLE
更新后购买页报错

### ISSUE THREAD

**Issue by Dennishaha** [ssrpanel/SSRPanel#1418]
![649e9c85-70a5-4407-ba11-85dd45c978fc](https://user-images.githubusercontent.com/38273998/53567445-36172680-3b9a-11e9-876a-6cc03faf9523.jpg)

**Comment by jackyeow** [comment]
报错+1

**Comment by 329928** [comment]
可能是等级表里的id缺失，手动往上加

**Comment by jackyeow** [comment]
@329928 问题是等级表里有ID呀

**Comment by kk2007yx** [comment]
报错+1

**Comment by mynameiscaa** [comment]
报错+2

**Comment by mynameiscaa** [comment]
![image](https://user-images.githubusercontent.com/41559238/53616489-c5195280-3c1d-11e9-95fc-dbd35ad3c762.png)
去用户列表里面查看，之前你肯定有改过用户等级

**Comment by kk2007yx** [comment]
归根结底 就是插入数据库不成功 找到level 数据库 然后手动插入 普通用户 VIP1 vip2 VIP3 就可以了

**Comment by jackyeow** [comment]
> ![image](https://user-images.githubusercontent.com/41559238/53616489-c5195280-3c1d-11e9-95fc-dbd35ad3c762.png)
> 去用户列表里面查看，之前你肯定有改过用户等级

先全部改成1就可以了，谢谢

**Comment by jackyeow** [comment]
> 归根结底 就是插入数据库不成功 找到level 数据库 然后手动插入 普通用户 VIP1 vip2 VIP3 就可以了

这些数据已经导入了，问题出在改过用户等级

**Comment by 329928** [comment]
> > 归根结底 就是插入数据库不成功 找到level 数据库 然后手动插入 普通用户 VIP1 vip2 VIP3 就可以了
> 
> 这些数据已经导入了，问题出在改过用户等级

我上面就说过，缺少对应的ID，你之前如果改成王者，那ID就是7，现在的ID最多就3。

**Comment by ssrpanel** [comment]
> > > 归根结底 就是插入数据库不成功 找到level 数据库 然后手动插入 普通用户 VIP1 vip2 VIP3 就可以了
> > 
> > 
> > 这些数据已经导入了，问题出在改过用户等级
> 
> 我上面就说过，缺少对应的ID，你之前如果改成王者，那ID就是7，现在的ID最多就3。

是的
