### ISSUE TITLE
节点离线与TCP阻断分离

### ISSUE THREAD

**Issue by 110560** [ssrpanel/SSRPanel#1419]
我还是开个问题好些 
分离后 ServerChan推送节点离线信息就行了 不然下面这个功能就废物了  
tcp阻断我又用不到
-------------------
节点离线提醒
启用后如果节点离线则发出提醒邮件

**Comment by Zhangziheng1** [comment]
TCP阻断为什么用不到？
TCP阻断了不就没法使用节点了吗？

**Comment by ssrpanel** [comment]
已分离，等提
