### ISSUE TITLE
更新最新版，提交公告出错

### ISSUE THREAD

**Issue by kk2007yx** [ssrpanel/SSRPanel#1420]
is:issueSQLSTATE[42S22]: Column not found: 1054 Unknown column 'logo' in 'field list' (SQL: insert into `article` (`title`, `type`, `author`, `summary`, `logo`, `content`, `is_del`, `sort`, `updated_at`, `created_at`) values  麻烦大大看看是不是哪里没设置对！

**Comment by kk2007yx** [comment]
更新导入数据库也出错了！

**Comment by cmtomkan310** [comment]
![image](https://user-images.githubusercontent.com/38905231/53610837-60eb9400-3c07-11e9-9cce-d218f7a2e09e.png)
正常啊！

**Comment by kk2007yx** [comment]
![_20190301095357](https://user-images.githubusercontent.com/44048312/53611009-f8e97d80-3c07-11e9-8e19-b0839f19c15c.png)
我已提交就跳这个画面
