### ISSUE TITLE
当面付创建订单成功后不显示二维码

### ISSUE THREAD

**Issue by deming41981** [ssrpanel/SSRPanel#1424]

**Comment by deming41981** [comment]
前几天还显示，今天就不显示了

**Comment by 828768** [comment]
二维码生成接口挂了，刚刚换好，只是新界面把用户信息和节点入口隐藏起来了，有傻逼来又找不到了

**Comment by deming41981** [comment]
> 二维码生成接口挂了，刚刚换好，只是新界面把用户信息和节点入口隐藏起来了，有傻逼来又找不到了

我该怎么做呢

**Comment by cmtomkan310** [comment]
@deming41981 说说咋整的啊

**Comment by deming41981** [comment]
> @deming41981 说说咋整的啊

更换生成二维码的api接口
参考:http://www.k780.com/api/qr.get
