### ISSUE TITLE
购买服务和节点列表藏太深，请给傻逼留个第一入口

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#1427]
如题，小白各种来问，其实都是找不到在哪看。
尤其是手机登录用户，右上角的菜单图标不明显不会点，建议增加在首页顶部增加明显的入口：
1. 购买服务入口
2. 节点配置入口
3. 账号信息：到期时间，剩余流量信息也应该放在首页展示
4. 右上角那个菜单图标，可能改成 `菜单` 两个字还更好一点

![image](https://user-images.githubusercontent.com/6386202/53675955-218c7880-3cd7-11e9-852b-bf791f496faf.png)

**Comment by vft9nesd** [comment]
你的客户怎么就成傻逼了？把你的面板地址报上来

**Comment by 828768** [comment]
> 你的客户怎么就成傻逼了？把你的面板地址报上来

请不要在意这些细节

**Comment by vft9nesd** [comment]
哈哈哈，坏的很

**Comment by SRCOL** [comment]
我都是个人中心加的按钮

**Comment by ZhilinChris** [comment]
我做了超链接在公告。。。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ssrpanel** [comment]
> 我做了超链接在公告。。。
> 
> Sent with [GitHawk](http://githawk.com)

都是这么干的，打到1楼
