### ISSUE TITLE
工具箱  邮件投递记录点开就这样，，，，，

### ISSUE THREAD

**Issue by 110560** [ssrpanel/ssrpanel#143]
Whoops, looks like something went wrong.
(2/2) ErrorException
Trying to get property of non-object (View: /www/wwwroot/duruossr/resources/views/emailLog/logList.blade.php)
in 53cdac5800f69a2540a242eaa3b59571df4410c0.php (line 58)

**Comment by ssrpanel** [comment]
@110560 查了代码，是你乱删除用户导致的。
我代码做了兼容，强烈建议不删除用户，禁用SSR和禁止登陆即可

**Comment by ssrpanel** [comment]
@110560 代码已修正，git pull一下
