### ISSUE TITLE
用户消耗流量与后台流量展示图表不一致

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#1430]
这个问题之前提过，我决定还是再提个issue，这样胖虎才会理俺！

某用户购买了10G流量，使用了某个2倍率的节点，爽91porn，sexsexsex完了，然后来问：流量咋用得这么快，而且你还只露了个B？
![image](https://user-images.githubusercontent.com/6386202/53692604-e7ea6900-3dcd-11e9-9fa2-2960d6884170.png)

可是可是可是，首页的流量监控图表是这样的：
![image](https://user-images.githubusercontent.com/6386202/53692554-16b40f80-3dcd-11e9-94ed-6cd45a8c8403.png)

用户前台的流量监控图表里用的数据并不是乘以节点倍率后的那些汇总数据，跟管理员在后台看到的是一样的：
![image](https://user-images.githubusercontent.com/6386202/53692551-f8e6aa80-3dcc-11e9-95dd-5a894397f1a4.png)

![image](https://user-images.githubusercontent.com/6386202/53692531-c341c180-3dcc-11e9-8a73-f51ac2339a0c.png)

胖虎你来说，这问题要不要改？

**Comment by 329928** [comment]
即使你都是1倍率，这里的流量和已用也是对不上的。流量的坑很大
