### ISSUE TITLE
v2ray go版可以正常上报，就是页面不显示，具体看下图

### ISSUE THREAD

**Issue by dawfds** [ssrpanel/SSRPanel#1431]
![1](https://user-images.githubusercontent.com/45940465/53694381-00b44800-3de9-11e9-890b-1a144a6c2068.png)
![2](https://user-images.githubusercontent.com/45940465/53694382-014cde80-3de9-11e9-8d8a-ff4bfed882ed.png)
建议使用用户id查询的方式@Bruskyii Panda

**Comment by ssrpanel** [comment]
端口为0？？？

**Comment by ssrpanel** [comment]
@rc452860

**Comment by dawfds** [comment]
不是ss，是v2ray go，是v2ray go，是v2ray go

**Comment by dawfds** [comment]
@ssrpanel

**Comment by ssrpanel** [comment]
V2RAY go去作者那反馈吧
