### ISSUE TITLE
全新安装，运行 php artisan key:generate ，出错。

### ISSUE THREAD

**Issue by ls886** [ssrpanel/SSRPanel#1433]
In Container.php line 767:
                                   
  Class translator does not exist

**Comment by ssrpanel** [comment]
已经不需要这么干了

**Comment by ajian2002** [comment]
what's mean

**Comment by ls886** [comment]
按照  https://www.lee-blog.com/ssrpanel/ssrpanel-bt/?source=wiki  教程安装的。 
到执行  php artisan key:generate ，就出错了。安装不成功。

**Comment by 828768** [comment]
这个错误+1

**Comment by zknyoyo** [comment]
同样错误+1

**Comment by mrxx** [comment]
同样错误+1

**Comment by ls886** [comment]
可以参考下，我粗略写的教程。 
https://blog3.good-a-day.net/index.php/archives/5/

**Comment by QZtymp** [comment]
@ls886 网址打开错误了

**Comment by zssshk** [comment]
zhusaisai.com 通过宝塔界面安装的详细教程，自己记录的，还有关于错误信息的解决办法！可以参照下
