### ISSUE TITLE
这东西咋没了，是功能删除了吗？

### ISSUE THREAD

**Issue by dawfds** [ssrpanel/SSRPanel#1438]
![99](https://user-images.githubusercontent.com/45940465/53800956-e27d5200-3f78-11e9-8739-41712efaf532.png)

**Comment by Zhangziheng1** [comment]
看一下Release

**Comment by dawfds** [comment]
那啥时候邮件群发能上啊？

**Comment by Zhangziheng1** [comment]
问问胖虎，别问我 @ssrpanel

**Comment by ssrpanel** [comment]
移除了，没意义
