### ISSUE TITLE
英文模版 - 已回复更新.

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#144]
需要个英文模版, 同时方便的话参考下wordpress后台的paypal插件, 非常容易的就开始了Paypal的付款, 还有各种信用卡支付通道, 无比舒畅啊.

**Comment by ssrpanel** [comment]
别只丢给我一个tips然后就让我搞出来啊，你到是多找找资料，贴出来我看啊，怎么跟那些产品经理一个屌德行。都特么说简单，然后让我们程序员搞出来。。。搞个毛

**Comment by 1021435278** [comment]
@ssrpanel  

刚刚才看到回帖, 我这里提供下资料, Wordpress和Mangento等流行B2C网站程序后台都带有Woocommer这种shop插件, 并内置了Paypal / Stripe 等国际主流支付通道, 开通非常容易,简单提交Paypal的收款邮件地址就可以完成绑定.
一个典型的安装Paypal插件支付帮助文档:
http://woocommerce.chongyuan.cc/woocommerce-gateway-paypal-powered-by-braintree.html

以及Stripe支付:http://woocommerce.chongyuan.cc/stripe.html 支持比特币和Apple Pay.
你可以实际性的安装一个Wordpress并安装上述2个支付插件后分析下代码就可以很容易应用到你的系统中.

以下为Wordpress后台Woocommerce插件截图:

![a](https://user-images.githubusercontent.com/32491066/33780547-155342bc-dc8c-11e7-8274-cfc5a65ed3c1.png)
![b](https://user-images.githubusercontent.com/32491066/33780548-15898b92-dc8c-11e7-81af-2ef70a5e7561.png)

若有任何不明白的,请继续跟帖提问, 我会根据你的疑问来解释.

**Comment by ssrpanel** [comment]
多国语言包已开发出，未提git，paypal开发中
