### ISSUE TITLE
商品颜色里的白色和灰色不能忍

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#1440]
1. 字体也是白色，如果底色是白色就看不到标题
2. 灰色和白色相近，而且灰色底色给人一种不能用的错觉

**Comment by ssrpanel** [comment]
你说的是购买按钮？？？

**Comment by 828768** [comment]
> 你说的是购买按钮？？？

是的，如果商品显示颜色设置白色和灰色，那用户前台的商品购买页效果你可以去看下

**Comment by ssrpanel** [comment]
你可以不设置啊。
