### ISSUE TITLE
邮件发送异常 但是后台显示的又是投递成功

### ISSUE THREAD

**Issue by KtQiu** [ssrpanel/SSRPanel#1442]
#我已经做过了`bash queue.sh`
下面是我的错误界面
![qq 20190306161103](https://user-images.githubusercontent.com/30206886/53865751-e5d11600-402a-11e9-95e2-f04834390cf4.png)
![qq 20190306161041](https://user-images.githubusercontent.com/30206886/53865764-ea95ca00-402a-11e9-8ac1-7b1fad13e286.png)
下面是我的.env的配置
![qq 20190306161221](https://user-images.githubusercontent.com/30206886/53865815-0600d500-402b-11e9-9b2f-89f6c4f48576.png)

**Comment by KtQiu** [comment]
实际上邮箱也是没有投递成功的

**Comment by ssrpanel** [comment]
浏览器 按 F12 ，看一下为什么提示请求异常？？
