### ISSUE TITLE
提现超级大BUG

### ISSUE THREAD

**Issue by Jinxs9** [ssrpanel/SSRPanel#1446]
用户申请提现，返利总金额计算的是截止到目前为止的所有金额合计，而提现的单数最多只有64单。情况大概如下：
用户在3月1日有返利64单，3月2日返利100单，他在3月3日申请提现。

申请提现的金额会计算这164单的金额合计，但是查看提现单详情，只有最多64单。如果你给用户返利后点击审核通过已打款，用户界面也只有前面64单也就是3月1日的那64单显示“已提现”，3月2日的100单还是“未提现”（可实际我们的钱已经给他们了）

当他下次提现，又会从这100单开始计算（因为状态是未提现），而实际消掉的单数也最多只有64单，再下次提现，就会从后面这36单开始计算。这其中形成的损失太大了、

**Comment by ZhilinChris** [comment]
建议直接关闭该功能

**Comment by 329928** [comment]
> 建议直接关闭该功能

你不用不代表别人也不用

**Comment by ZhilinChris** [comment]
>> 建议直接关闭该功能 ...

@329928 看不懂建议两个字吗？二道杠

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mr-Kwok** [comment]
买卖干的够大啊？

**Comment by 329928** [comment]
> 买卖干的够大啊？

你可以在你的注册链接后面加上?aff=1
