### ISSUE TITLE
建议：shadowrocket订阅二维码

### ISSUE THREAD

**Issue by ntgeralt** [ssrpanel/SSRPanel#1448]
我知道可能有点难，要研究二维码格式；不过你做出来的话，用户用起来更方便了，登进去，一扫，搞定~ 
: )

**Comment by ssrpanel** [comment]
？？？？？？？？？？？？？？？？？？？？？？？？？？？

**Comment by ntgeralt** [comment]
就是用户登陆进去，看到订阅地址旁边有个二维码，供小火箭扫码订阅。另外新版的订阅服务怎么放进去二级菜单了，在首页也没多大问题

**Comment by ssrpanel** [comment]
有小火箭扫码订阅的scheme吗？有就发出来

**Comment by ntgeralt** [comment]
我也是普通玩家不大会阿，我刚试了
小火箭订阅地址是https://www.tvb.com/s/Fd5tn，备注是vip。
左滑订阅地址生成的二维码识别的结果是
sub://aHR0cHM6Ly93d3cudHZiLmNvbS9zL0ZkNXRu#vip
中间base64加密

**Comment by ssrpanel** [comment]
操，小火箭还可以往左滑动显示二维码，我日了汪汪队长，怎么我就没注意到。。感谢提醒

**Comment by ssrpanel** [comment]
不要关闭这个issues，等我做出来，我来手动close

**Comment by tuhang** [comment]
看得很有喜感…

**Comment by ssrpanel** [comment]
@tuhang 好了好了不要闹了，

**Comment by ssrpanel** [comment]
已加

**Comment by ntgeralt** [comment]
666

**Comment by vft9nesd** [comment]
![image](https://user-images.githubusercontent.com/24932999/56042669-30525a80-5d6e-11e9-8e2b-88b0a6228a5b.png)
