### ISSUE TITLE
升级后打开网站报错，经典翻译器不存在

### ISSUE THREAD

**Issue by lsbjkc** [ssrpanel/SSRPanel#1449]
![image](https://user-images.githubusercontent.com/43370337/54025789-929bc680-41d6-11e9-9cb5-248c954b0ee2.png)

![image](https://user-images.githubusercontent.com/43370337/54025874-de4e7000-41d6-11e9-9dde-1eda18437596.png)

**Comment by ajian2002** [comment]
same
