### ISSUE TITLE
节点流量显示不正常

### ISSUE THREAD

**Issue by DanielZhang17** [ssrpanel/ssrpanel#145]
今天重新配置了一个服务器，不过用的是以前的数据库，安装最新版本面板之后首页上的流量显示正常
但是节点管理里的每个节点都显示为0B
但是点击流量监控时发现是有记录的，请问是不是节点管理里的流量是每24小时更新的呢
备注：定时任务工作正常

**Comment by ssrpanel** [comment]
@DanielZhang17 节点的流量记录是取ss_node_traffic_daily 表的。这个表里的数据时定时任务自动跑出来的

**Comment by DanielZhang17** [comment]
24小时更新一次吗
