### ISSUE TITLE
 Class translator does not exist

### ISSUE THREAD

**Issue by mrxx** [ssrpanel/SSRPanel#1452]
php artisan 时提示

 Class translator does not exist

安装后在浏览器里面也显示这个错误

**Comment by 828768** [comment]
[看这里](https://sobaigu.com/laravel-class-translator-does-not-exist-client-error-post-401-mailgun.html)

**Comment by ls886** [comment]
可以参考下，我粗略写的教程。 
https://blog3.good-a-day.net/index.php/archives/5/

**Comment by mrxx** [comment]
> [看这里](https://sobaigu.com/laravel-class-translator-does-not-exist-client-error-post-401-mailgun.html)

试过好几次  php composer.phar install 还是不行
搜了一下很多人遇到 larvael 的 class does not exist 的问题，但都不知道怎么解决，这可能和框架有关，一个无法解决调试的问题，或者是框架给出的异常提醒不够准确

--



--

**Comment by 828768** [comment]
> > [看这里](https://sobaigu.com/laravel-class-translator-does-not-exist-client-error-post-401-mailgun.html)
> 
> 试过好几次 php composer.phar install 还是不行
> 搜了一下很多人遇到 larvael 的 class does not exist 的问题，但都不知道怎么解决，这可能和框架有关，一个无法解决调试的问题，或者是框架给出的异常提醒不够准确
> 
> --
> 
> --

呀，发现这问题真没解决。

**Comment by mrxx** [comment]
编辑 config/app.php 找到下面的代码，去掉注释就行
Illuminate\Translation\TranslationServiceProvider::class, // 弃用自带多国语言包功能
