### ISSUE TITLE
ipip.ipdb / qqwry.dat 建议迁移位置或是以 script 抓取

### ISSUE THREAD

**Issue by farrrr** [ssrpanel/SSRPanel#1454]
因为使用类似 envoyer.io 这类型 deployment service，初次建立时， storage 目录是重新建立，并且与 laravel 本身的结构一样，然后放置在 webroot 外头，以 symlink 方式连结，以达到排除在 cvs 外，但资料是持续性的。

但因为 ipip.ipdb / qqwry.dat 这两个档案被放置在 storage 下时，透过 envoyer.io 这类 deployment service 就会造成找不到档案（因为被移除了）。建议有几个做法。

1. install.php 执行时，再行下载这两个档案至 storage，或透过 artisan 来下载也行。
2. 直接不放在 storage 中，改放其他目录。

**Comment by ssrpanel** [comment]
容我迁移 走

**Comment by ssrpanel** [comment]
放storage 下确实不合理

**Comment by ssrpanel** [comment]
已迁移至 public下
