### ISSUE TITLE
利用dnsmasq屏蔽特定网址

### ISSUE THREAD

**Issue by ghost** [ssrpanel/SSRPanel#1455]
部署一个DNS服务器，将节点机DNS改为该主机IP
或者，直接部署在节点机，将节点机DNS改为127.0.0.1

安装：
yum -y install dnsmasq  #安装dnsmasq
systemctl enable dnsmasq  #设为开机启动

然后做一下安保，三条命令顺序不能错
iptables -I INPUT -p udp --dport 53 -j ACCEPT  #允许所有IP UDP流量访问本机53端口
iptables -I INPUT -p udp --dport 53 -j DROP  #禁止所有IP UDP流量访问本机53端口
iptables -I INPUT -s x.x.x.x -p udp --dport 53 -j ACCEPT  #仅允许x.x.x.x UDP流量访问本机53端口，x.x.x.x为节点机IP
iptables-save  #保存配置，不然重启后就没了

配置：
为特定域名指定解析IP：address=/baidu.com/0.0.0.0 将baidu.com及其子域名解析为0.0.0.0，这里主要使用这个功能屏蔽特定网址
为特定域名指定上游DNS：server=/google.com/8.8.8.8 当解析google.com及其子域名时使用8.8.8.8，其他域名使用server=x.x.x.x指定的DNS
/etc/dnsmasq.conf 粘贴如下

no-hosts  #不加载本地hosts
no-resolv  #不读取resolv-file来指定上游DNS
server=1.1.1.1  #指定上游DNS，最多三个

address=/ad.youku.com/0.0.0.0  #去广告(欢迎各位补充)
address=/ad.iqiyi.com/0.0.0.0

address=/api.map.baidu.com/0.0.0.0  #防百度高精度定位（全）
address=/ps.map.baidu.com/0.0.0.0
address=/sv.map.baidu.com/0.0.0.0
address=/offnavi.map.baidu.com/0.0.0.0
address=/newvector.map.baidu.com/0.0.0.0
address=/ulog.imap.baidu.com/0.0.0.0
address=/newloc.map.n.shifen.com/0.0.0.0

address=/360.com/0.0.0.0  #防360（可能不全）
address=/360.cn/0.0.0.0
address=/so.com/0.0.0.0
address=/360securityapps.com/0.0.0.0
address=/360safe.com/0.0.0.0
address=/360totalsecurity.com/0.0.0.0

address=/gov.cn/0.0.0.0  #防老大哥(欢迎各位补充)
address=/zzdjw.org.cn/0.0.0.0
address=/zgdsw.org.cn/0.0.0.0
address=/people.cn/0.0.0.0
address=/people.com.cn/0.0.0.0
address=/djyj.cn/0.0.0.0
address=/wxyjs.org.cn/0.0.0.0
address=/cpcnews.cn/0.0.0.0
address=/xinhuanet.com/0.0.0.0
address=/showchina.org/0.0.0.0
address=/dangjian.cn/0.0.0.0
address=/chinanews.com/0.0.0.0
address=/cnr.cn/0.0.0.0
address=/youth.cn/0.0.0.0
address=/ce.cn/0.0.0.0
address=/chinadaily.com.cn/0.0.0.0
address=/cctv.com/0.0.0.0
address=/china.com/0.0.0.0
address=/cctb.net/0.0.0.0
address=/xuexi.cn/0.0.0.0
address=/qstheory.cn/0.0.0.0
address=/mzhoudeng.com/0.0.0.0
address=/shaoqiguli.com/0.0.0.0
address=/zhudeguli.com/0.0.0.0
address=/ssmzd.com/0.0.0.0
address=/zunyihy.cn/0.0.0.0
address=/cntheory.com/0.0.0.0
address=/71.cn/0.0.0.0
address=/china.org.cn/0.0.0.0
address=/cgtn.com/0.0.0.0
address=/chinaview.cn/0.0.0.0
address=/chinamil.com.cn/0.0.0.0
address=/womenofchina.cn/0.0.0.0
address=/tibet.cn/0.0.0.0
address=/taiwan.cn/0.0.0.0
address=/cri.cn/0.0.0.0
address=/theorychina.org/0.0.0.0
address=/cssn.cn/0.0.0.0
address=/cipg.org.cn/0.0.0.0
address=/swchina.org/0.0.0.0
address=/redchinacn.net/0.0.0.0
address=/chinagate.cn/0.0.0.0

屏蔽域名可能不全，欢迎各位评论补充

**Comment by ssrpanel** [comment]
vnet刚好可以自建dns来配合

**Comment by Lins** [comment]
谁做个一键脚本！

**Comment by fcwork** [comment]
能不能同时解锁nf

**Comment by fyshaw** [comment]
> 能不能同时解锁nf

这个有现成的啊
https://github.com/ab77/netflix-proxy
需要dnsmasq劫持配合sniproxy反代，上面这个docker部署自带webUI，或者你觉得性能不佳可以直接部署dnsmasq和sniproxy软件包

**Comment by ssrpanel** [comment]
vnet后端已经实现规则审计功能了
