### ISSUE TITLE
换服务器后，导入原服务器user.sql，开大用户列表报错，跪求解决！

### ISSUE THREAD

**Issue by xfhack** [ssrpanel/SSRPanel#1458]
换服务器后，导入原服务器user.sql，开大用户列表报错，我已遍历所有相关问题，看到老大统一回复：不TG频道的人不值得同情，在这里我弱弱的说一下，我是小白，连TG频道是什么都不知道，所以还是不得已，上线发帖，跪求解决，谢谢！

![微信图片_20190310104002](https://user-images.githubusercontent.com/22985419/54079930-e0bce100-4320-11e9-80db-e0ee4a7f5efb.png)

**Comment by 828768** [comment]
数据库导入不完整

**Comment by ssrpanel** [comment]
你这个版本也太老了，你从 频道里的  升级用户 （生成）订阅码 那开始往下找 

主要是因为订阅码丢失导致
