### ISSUE TITLE
大佬可以添加一个cisco anyconnect协议对接吗？

### ISSUE THREAD

**Issue by w328242092** [ssrpanel/SSRPanel#1459]
cisco anyconnect 443端口 这个为企业 不容易被和谐，建议添加上去
软件 也比较好下载 支持多平台。还有就是设置终端数

**Comment by vft9nesd** [comment]
这玩意不是早凉了

**Comment by samac08** [comment]
保有量很少, 这个并不易用 没意义吧 还不如对接下火酱的 Trojan [https://github.com/trojan-gfw/trojan](url) 相当轻快简单

**Comment by w328242092** [comment]
> 这玩意不是早凉了

这个协议是不会凉的，毕竟是利用的是443端口 企业专用的软件 思科是是大公司，不可能凉，

**Comment by w328242092** [comment]
> 保有量很少, 这个并不易用 没意义吧 还不如对接下火酱的 Trojan [https://github.com/trojan-gfw/trojan](url) 相当轻快简单

思科支持全平台，苹果手机 可以直接下载，使用也比较方便

**Comment by ntgeralt** [comment]
> > 保有量很少, 这个并不易用 没意义吧 还不如对接下火酱的 Trojan [https://github.com/trojan-gfw/trojan](url) 相当轻快简单
> 
> 思科支持全平台，苹果手机 可以直接下载，使用也比较方便

你抓包看看特征明不明显。现在能用只是给小企业留口气

**Comment by vft9nesd** [comment]
> > 这玩意不是早凉了
> 
> 这个协议是不会凉的，毕竟是利用的是443端口 企业专用的软件 思科是是大公司，不可能凉，

你备案了  裸连都不会墙

**Comment by w328242092** [comment]
> > > 这玩意不是早凉了
> > 
> > 
> > 这个协议是不会凉的，毕竟是利用的是443端口企业专用的软件思科是是大公司，不可能凉，
> 
> 你备案了裸连都不会墙

备案肯定不行的呀 那样直接gg 
不过思科是比较安全的

**Comment by w328242092** [comment]
> > > 保有量很少，这个并不易用没意义吧还不如对接下火酱的Trojan [https://github.com/trojan-gfw/trojan](url)相当轻快简单
> > 
> > 
> > 思科支持全平台，苹果手机可以直接下载，使用也比较方便
> 
> 你抓包看看特征明不明显。现在能用只是给小企业留口气

怎么说了 gw想gg思科，也要考虑一些大企业的需求 ，这个协议大企业用的比较多 ，主要作用是外网链接公司内网办公的协议

**Comment by ssrpanel** [comment]
不加，别等了
