### ISSUE TITLE
邮件发送connection timeout

### ISSUE THREAD

**Issue by DanielZhang17** [ssrpanel/ssrpanel#146]
配置定时任务成功之后用了如下设置配置了mail.php
   `Host: smtp-mail.outlook.com`
   `port: 587`
   `encryption:  tls`
然后发送邮件显示：
`Connection could not be established with host smtp-mail.outlook.com [Connection timed out #110]`
请问如何处理，这个现在是这个面板最让我头疼的地方
邮件一直都没成功过，或者如果可以用mailgun的话请大佬指点一下怎么设置mail.php

**Comment by ssrpanel** [comment]
@DanielZhang17 我写个mailgun的wiki吧，那个是说明你的配置可能错了导致链接超时

**Comment by DanielZhang17** [comment]
还是mailgun好用
