### ISSUE TITLE
最新版，流量异常用户面板无提示。

### ISSUE THREAD

**Issue by ZhilinChris** [ssrpanel/SSRPanel#1460]
用户因为流量异常被系统临时封禁之后，面板无提示（用户个人中心和节点列表都没有），可以优化下。

**Comment by ssrpanel** [comment]
截图举例

**Comment by 329928** [comment]
> 截图举例

用户状态： 禁用 （因*****临时封禁*小时）

**Comment by ZhilinChris** [comment]
> 截图举例

后台可以看到提示，但是用户那边好像没有任何提示：因为流量异常被暂时封禁，只会表现出不能使用，也无禁用标记。

**Comment by 329928** [comment]
> 截图举例


首页的用户状态后台如果是禁用，写上禁用理由，如：
用户状态： 禁用 （因 ***** 原因 封禁 *** 时间 ）

不管是什么原因封禁，给用户发个提示邮件。
后台手动封禁代理状态，在封禁时填写封禁理由，然后理由用户也会在首页看到。
