### ISSUE TITLE
套餐续费时间的问题

### ISSUE THREAD

**Issue by kk2007yx** [ssrpanel/SSRPanel#1463]
我看过issue 有好多人提到过，我目前是面板最新版本，还是存在同样的问题，套餐续费后到期时间是按续费日期计算，而不是前一个套餐到期时间开始计算。
![image](https://user-images.githubusercontent.com/44048312/54168870-90be5580-44ab-11e9-99e7-2ebb16ca6aac.png)
如图，这个就比较尴尬了 。

**Comment by kk2007yx** [comment]
我知道原因了 原来之前那个是流量包

**Comment by Lins** [comment]
兄弟 不是流量包也不叠加好不好！

**Comment by kk2007yx** [comment]
> 兄弟 不是流量包也不叠加好不好！

胖虎大大修复过这个问题的，就是你提前续费的话是根据你的到期日期延期，流量包的失效是独立的，用完就扣除流量包的流量了
