### ISSUE TITLE
最新版本 圈订阅问题 混合订阅及SSR协议识别错误

### ISSUE THREAD

**Issue by samac08** [ssrpanel/SSRPanel#1464]
更新新版本后 圈节点订阅出现问题
0 .订阅列表不再显示2条 有效日期及剩余流量了, 
1.变成了在测速页面显示总流量和上/下使用流量.
2. 只要是采用vnet 部署的节点-圈订阅都变不正常了
3.vnet部署节点协议识别错误 SSR的节点变成SS协议的节点了
4.python版SSRR部署的单端口节点,不受影响识别正常SSR协议
5. 混合订阅 采用v2协议-wss协议部署的节点 一直没有订阅成功过,期待兼容下
---------------------
小火剑混合订阅 SSR(vnet及python部署)及v2-wss部署的节点 SSR识别一切正常 双协议订阅完全正常
---------------------
kit 混合订阅V2 也是一直不能订阅成功 现在唯一完美双协议订阅支持的就是小火剑...

**Comment by ssrpanel** [comment]
还有quan

**Comment by samac08** [comment]
> 还有quan @ssrpanel 
确实是这样子 你可以先把quan里面的已有订阅节点删除, 刷新下订阅 测试看看 vnet的节点都不正常了,变成ss协议了. kit确实不能订阅混合里面的V2节点, 圈只能订阅里面的SSR,现在vnet部署的识别成SS了 ,测试了I2RAY-app可订阅V2,.唯一完美的还是小火煎,v2-ssr混合订阅双协议一直ok.......

**Comment by redtechma** [comment]
> ## 更新新版本后 圈节点订阅出现问题
> 0 .订阅列表不再显示2条 有效日期及剩余流量了,
> 1.变成了在测速页面显示总流量和上/下使用流量.
> 2. 只要是采用vnet 部署的节点-圈订阅都变不正常了
> 3.vnet部署节点协议识别错误 SSR的节点变成SS协议的节点了
> 4.python版SSRR部署的单端口节点,不受影响识别正常SSR协议
> 5. 混合订阅 采用v2协议-wss协议部署的节点 一直没有订阅成功过,期待兼容下
> ## 小火剑混合订阅 SSR(vnet及python部署)及v2-wss部署的节点 SSR识别一切正常 双协议订阅完全正常
> kit 混合订阅V2 也是一直不能订阅成功 现在唯一完美双协议订阅支持的就是小火剑...

是的 圈上面日期和流量 消失了 说缺少group参数 小火箭一直完美

**Comment by 329928** [comment]
日期问题可以自己看下代码，V2的订阅没有标准格式，所以在quan上面要另外转换格式，这个我觉得让胖虎写不同参数对应不同订阅格式比较好。

**Comment by samac08** [comment]
> 日期问题可以自己看下代码，V2的订阅没有标准格式，所以在quan上面要另外转换格式，这个我觉得让胖虎写不同参数对应不同订阅格式比较好。

-

这些都是次要的 最关键是现在vnet布的会被识别错误 变成了ss 你试试看

**Comment by 329928** [comment]
> > 日期问题可以自己看下代码，V2的订阅没有标准格式，所以在quan上面要另外转换格式，这个我觉得让胖虎写不同参数对应不同订阅格式比较好。
> 
> 
> 这些都是次要的 最关键是现在vnet布的会被识别错误 变成了ss 你试试看

vnet本来就是ss
