### ISSUE TITLE
虎。手动添加的用户、添加出来的日期都比当前日期少一天这个是bug还是这样设置的呢？

### ISSUE THREAD

**Issue by GitH123i** [ssrpanel/SSRPanel#1465]
虎。手动添加的用户、添加出来的日期都比当前日期少一天这个是bug还是这样设置的呢？

**Comment by ssrpanel** [comment]
截图？？

**Comment by GitH123i** [comment]
![image](https://user-images.githubusercontent.com/45822319/54250210-d3506280-457d-11e9-8f30-eb1ffa3208e7.png)
你看，这个就是手动添加的用户 ，默认是一年的。今天应该是3月13号，但是默认开出来的一年是12号。比当前日期少一天。

**Comment by PlaneV** [comment]
这样系统不就可以在3月13日凌晨0点的时候读到过期，然后把这个客户停掉，没毛病

**Comment by GitH123i** [comment]
系统开出来的到期日期是12号呀，那不就是说12号就被停掉了？问题是用户的到期日期是13号。那就应该13号当天用完啊，14号凌晨停掉才对吧。

**Comment by 329928** [comment]
1月1日买，因为即时生效，当天也计算进去，第365天是12月31日，所以少一天，你把365改成366就没毛病了

**Comment by ssrpanel** [comment]
默认是 + 365天的
