### ISSUE TITLE
未知问题 数据库配置访问都没问题 不知道问题出在哪里了

### ISSUE THREAD

**Issue by ilovebamboo** [ssrpanel/ssrpanel#147]
![qq20171129-124746](https://user-images.githubusercontent.com/6214084/33358464-b5ba3c46-d503-11e7-8eaa-a399625a6d4d.png)
![qq20171129-124557](https://user-images.githubusercontent.com/6214084/33358465-b5eca9f6-d503-11e7-9cc7-39197a200be2.png)
![qq20171129-124442](https://user-images.githubusercontent.com/6214084/33358466-b61f71ec-d503-11e7-9030-76ac28ba6a4a.png)

**Comment by ilovebamboo** [comment]
修正字打错了 第一张图片 是第二台服务器 运行

**Comment by DanielZhang17** [comment]
不是python3吗

**Comment by ilovebamboo** [comment]
![qq20171129-131141](https://user-images.githubusercontent.com/6214084/33358966-db6fb788-d506-11e7-8a06-af5291613d97.png)
2.7

**Comment by ssrpanel** [comment]
@ilovebamboo 
如果节点机连不上，这么排查
1.节点机关闭iptables
2.数据库机关闭iptables
3.数据库对节点机进行授权
4.如果是阿里云，注意安全组策略
