### ISSUE TITLE
新发现，最近一些人包括我自己出现一个情况，vps本身没有被封，但是一些ss端口频繁被封，更换一个又好了过段时间又不行了。

### ISSUE THREAD

**Issue by GitH123i** [ssrpanel/SSRPanel#1474]
新发现，最近一些人包括我自己出现一个情况，vps本身没有被封，但是一些ss端口频繁被封，换个端口就又可以使用了。过段时间又不行了。你们有出现这个情况吗？

**Comment by jackyeow** [comment]
我碰到过，也没有频繁，被封过一次，用到现在已经2个月了，还没有被封过。

**Comment by vft9nesd** [comment]
不要用plain

**Comment by GitH123i** [comment]
怎么老铁有什么说法吗？我记得之前他们的建议是最好不要使用http_simple类的，使用plain最好。

**Comment by vft9nesd** [comment]
说tls特征太明显，没说http_simple吧..   参数为空就可以了。

**Comment by maxwellhouse102** [comment]
我的有这情况，日本的特别严重，一个端口用几天就被封了

**Comment by ssrpanel** [comment]
不解答，跟面板无关，我只能说你的姿势不对

**Comment by ssrpanel** [comment]
因为特喵的onevps去年7月用到现在，一个服务器每月6T 的流量，一直就好好的

**Comment by GitH123i** [comment]
老大 看到你的推荐了 买年的。。被强了怎么办。。。亏死。可以更换ip吗。多少钱。

**Comment by GitH123i** [comment]
@ssrpanel 老大 看到你的推荐了 买年的。。被强了怎么办。。。亏死。可以更换ip吗。多少钱。

**Comment by mynameiscaa** [comment]
我也是，origin+plain，用电信4g和wifi端口都被封，但移动可以却可以连接
