### ISSUE TITLE
设置页无法打开，严重BUG

### ISSUE THREAD

**Issue by Dennishaha** [ssrpanel/SSRPanel#1475]
![image](https://user-images.githubusercontent.com/38273998/54416355-13f4db00-473a-11e9-9d21-74fcb8914137.png)

**Comment by Alan0429** [comment]
数据库文件，更新

**Comment by Dennishaha** [comment]
更新了过了不行
在想怎么手动纠正
@Alan0429

**Comment by chinashanda** [comment]
这个不是bug，就是数据库文件没有更新导致的

**Comment by Alan0429** [comment]
> 更新了过了不行
> 在想怎么手动纠正
> @Alan0429

去下载数据库更新文件，用记事本打开，复制里面的信息，到数据库命令台执行
，再不行就看更新文件里面的数据，手动找到对应的数据库文件自己更新

**Comment by Dennishaha** [comment]
我是每次都会手动更新sql，但是还是错了，且不知道哪里错了。

**Comment by big-chief** [comment]
建议你git pull 单文件
system.blade.php

**Comment by ssrpanel** [comment]
不是BUG，记得看wiki，看看怎么更新，没事别瞎更新，能用就行

**Comment by Dennishaha** [comment]
手动修正数据库完成
