### ISSUE TITLE
建议：订阅增加ss scheme

### ISSUE THREAD

**Issue by DesperadoJ** [ssrpanel/SSRPanel#1477]
目前SSRPanel的订阅支持ssr scheme以及v2ray scheme，但是不支持ss scheme。
而Win和Android平台支持订阅且还在更新维护的客户端，比如v2rayN，v2rayNG，都不支持ssr订阅，但是支持ss订阅。
并且与SSRPanel配合较好的Vnet也是ss后端。如果订阅使用ssr scheme，由于Win/Android平台的SSR客户端均不支持aes-256-gcm/aes-192-gcm/aes-128-gcm/chacha20-ietf-poly1305等支持AEAD算法的加密方式，无法与Vnet做到完全兼容。
建议：增加ss订阅

**Comment by ssrpanel** [comment]
1.什么客户端支持SS scheme 
2.什么客户端支持SS 订阅？
3.具体的SS订阅规则是什么样的，举个栗子

**Comment by DesperadoJ** [comment]
> 1.什么客户端支持SS scheme
> 2.什么客户端支持SS 订阅？
> 3.具体的SS订阅规则是什么样的，举个栗子

刚刚又去看了眼 SSD 的 [订阅协定和 Scheme](https://github.com/CGDF-Github/SSD-Windows/wiki/%E8%AE%A2%E9%98%85%E5%8D%8F%E5%AE%9A%EF%BC%88http%EF%BC%89)，发现是自有的，兼容不佳，把这个软件从上面的例子里划掉。以下都是支持/兼容 Shadowsocks 官方 [SIP002 URI Scheme](https://shadowsocks.org/en/spec/SIP002-URI-Scheme.html) 的软件

1. 支持 SIP002 URI Scheme 导入的客户端：
  Windows: [Shadowsocks-windows](https://github.com/shadowsocks/shadowsocks-windows)，[v2rayN](https://github.com/2dust/v2rayN)
  Android: [shadowsocks-android](https://github.com/shadowsocks/shadowsocks-android)，[v2rayNG](https://github.com/2dust/v2rayNG)
  iOS: Quantumult，Kitsunebi，诸如 Shadowrocet 等其他的 APP，由于我没有购买，无法测试，应该还有很多也是支持的
  MacOS: [ShadowsocksX-NG](https://github.com/shadowsocks/ShadowsocksX-NG)

2. 支持 SIP002 URI Scheme 订阅的客户端：
  Windows: [v2rayN](https://github.com/2dust/v2rayN)
  Android: [v2rayNG](https://github.com/2dust/v2rayNG)
  iOS: Quantumult，Kitsunebi，其他 APP 没有购买无法测试
  MacOS: 不详

3. 订阅规则：
  将 Shadowsocks 的 SIP002 URI Scheme 按一个一行排列后进行 base64 编码即可，可以参考
 [v2rayN 的订阅功能说明](https://github.com/2dust/v2rayN/wiki/%E8%AE%A2%E9%98%85%E5%8A%9F%E8%83%BD%E8%AF%B4%E6%98%8E)
具体例子可以看 [这里](https://gist.githubusercontent.com/DesperadoJ/69ef93241ae0da28177e4902b3cc53ec/raw/71e1eb460979f66a5a9b7cd3ba347fbe2bfb6d14/SS%2520Sub)

另外我提了个 [request](https://github.com/ssrpanel/SSRPanel/pull/1470)，改进了一下目前面板上 SS URL 最后的备注信息，胖虎有空看一眼啊，要不然按目前的 URL 导入客户端，看到的所有节点的名字都是 VPN，没法区分节点

**Comment by ssrpanel** [comment]
SSD 会屏蔽电脑里的360、电脑助手啥的。我不喜欢。

**Comment by DesperadoJ** [comment]
> SSD 会屏蔽电脑里的360、电脑助手啥的。我不喜欢。

是的，SSD 就别管它了，这些支持官方 SIP002 URI Scheme 的有很多，能不能做一个 SIP002 URI Scheme 的订阅支持呢

**Comment by ssrpanel** [comment]
v2rayN 的作者我喊他加个scheme 的 method 字段他都不愿意，ε=(´ο｀*)))唉

**Comment by ssrpanel** [comment]
“method 为空就客户端自动适配，不为空则 method是什么客户端就选什么。“
我是这么理解的。
不过v2rayN 的作者非得说自动选择，那通过订阅的就没办法很好的控制了。蛋疼

**Comment by DesperadoJ** [comment]
> “method 为空就客户端自动适配，不为空则 method是什么客户端就选什么。“
> 我是这么理解的。
> 不过v2rayN 的作者非得说自动选择，那通过订阅的就没办法很好的控制了。蛋疼

你的理解好像也没什么问题，由于 v2ray 的服务端会自动适配客户端的加密方式，所以其实填什么加密方式都不会导致连接失败。所以这个 method 字段确实是不用加的，因为即使加入了，目前 SSRPanel 对用户实际使用的加密方式也是无法控制的（用户那边自己改了加密方式还是能连上）。
v2rayN 的开发者也是利用 v2ray 服务端自动适配加密方式的特性，让客户端在不同的硬件平台上选取最合适的加密方式（当然，“**自动选择**”是在加密方式为 “**auto**” 的情况下进行的）。但是一旦用户自己在 v2rayN 中指定了加密方式，就还是会用指定的加密方式和服务端通讯。

**Comment by ntgeralt** [comment]
我大概明白楼主想要什么，v2ray服务端内部允许加建ss服务端，但没做ssr适配。
所以v2ray dust那系也支持ss
所以楼主有这建议
其实这只是为了PC客户端

**Comment by ssrpanel** [comment]
> > “method 为空就客户端自动适配，不为空则 method是什么客户端就选什么。“
> > 我是这么理解的。
> > 不过v2rayN 的作者非得说自动选择，那通过订阅的就没办法很好的控制了。蛋疼
> 
> 你的理解好像也没什么问题，由于 v2ray 的服务端会自动适配客户端的加密方式，所以其实填什么加密方式都不会导致连接失败。所以这个 method 字段确实是不用加的，因为即使加入了，目前 SSRPanel 对用户实际使用的加密方式也是无法控制的（用户那边自己改了加密方式还是能连上）。
> v2rayN 的开发者也是利用 v2ray 服务端自动适配加密方式的特性，让客户端在不同的硬件平台上选取最合适的加密方式（当然，“**自动选择**”是在加密方式为 “**auto**” 的情况下进行的）。但是一旦用户自己在 v2rayN 中指定了加密方式，就还是会用指定的加密方式和服务端通讯。

只要v2rayNG作者加入那个method，我就可以兼容很多客户端了。懂么？？？
不过那个作者他才不管你兼容不兼容。他觉得他有道理，也对。不信你试试vmess格式，扫码看看，shadowrocket 加密方式自动为none，连不上的。等会要是说多了，人家会跑来说：那你叫shadowrocket 去改。

**Comment by DesperadoJ** [comment]
> > > “method 为空就客户端自动适配，不为空则 method是什么客户端就选什么。“
> > > 我是这么理解的。
> > > 不过v2rayN 的作者非得说自动选择，那通过订阅的就没办法很好的控制了。蛋疼
> > 
> > 
> > 你的理解好像也没什么问题，由于 v2ray 的服务端会自动适配客户端的加密方式，所以其实填什么加密方式都不会导致连接失败。所以这个 method 字段确实是不用加的，因为即使加入了，目前 SSRPanel 对用户实际使用的加密方式也是无法控制的（用户那边自己改了加密方式还是能连上）。
> > v2rayN 的开发者也是利用 v2ray 服务端自动适配加密方式的特性，让客户端在不同的硬件平台上选取最合适的加密方式（当然，“**自动选择**”是在加密方式为 “**auto**” 的情况下进行的）。但是一旦用户自己在 v2rayN 中指定了加密方式，就还是会用指定的加密方式和服务端通讯。
> 
> 只要v2rayNG作者加入那个method，我就可以兼容很多客户端了。懂么？？？
> 不过那个作者他才不管你兼容不兼容。他觉得他有道理，也对。不信你试试vmess格式，扫码看看，shadowrocket 加密方式自动为none，连不上的。等会要是说多了，人家会跑来说：那你叫shadowrocket 去改。

我还特地去买了Shadowrocet测试，加密方式为none也是连得上的
