### ISSUE TITLE
在线IP监控不会刷新

### ISSUE THREAD

**Issue by mynameiscaa** [ssrpanel/SSRPanel#1479]
![image](https://user-images.githubusercontent.com/41559238/54475478-b68d8680-482c-11e9-8a8a-41e66608f9b3.png)
换了vnet为什么在线ip实时监控不会刷新？

**Comment by maxwellhouse102** [comment]
服务端用vnet，客户端你用的什么？

**Comment by ssrpanel** [comment]
不应该，没出现过

**Comment by mynameiscaa** [comment]
> 服务端用vnet，客户端你用的什么？

vnet 0.0.6啊就这2个ip一直存在不会刷新。。
