### ISSUE TITLE
禁止用户问题

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#148]
禁止用户的时候为什么不一同连ssr禁止了, 既然都禁止了这个用户了, 为什么还留着ssr, 留着煲汤?

**Comment by ssrpanel** [comment]
@1021435278 行，我加一起，

**Comment by ssrpanel** [comment]
@1021435278 我加一下，编辑用户信息时如果禁止用户登录，则SSR状态一起置为禁止

**Comment by 1021435278** [comment]
谢谢...

**Comment by ssrpanel** [comment]
@1021435278 已改，等更新
