### ISSUE TITLE
系统日志页面错误500

### ISSUE THREAD

**Issue by kk2007yx** [ssrpanel/SSRPanel#1480]
![image](https://user-images.githubusercontent.com/44048312/54485486-504c4680-48b4-11e9-9329-10c0097d32b1.png)
如图，我翻了一堆issue 也没找到解决方法，已经一段时间了，因为影响不大，所以一直没管，是权限问题么？

**Comment by big-chief** [comment]
wiki自己找

**Comment by kk2007yx** [comment]
> wiki自己找

我找遍了没找到啊！

**Comment by big-chief** [comment]
F12 .报错日志。nginx php。 框架日志

**Comment by kk2007yx** [comment]
![image](https://user-images.githubusercontent.com/44048312/54485864-572a8780-48bb-11e9-8afe-cc691d68a03d.png)
我看到这个，我改过了，重启了php 也是一样的。

> F12 .报错日志。nginx php。 框架日志

**Comment by big-chief** [comment]
我建议你，F12 控制台看看报错返回的什么信息。你这样的问答什么内容都没有。让人很懵逼

**Comment by kk2007yx** [comment]
😂 😂 好 枫叶看看

**Comment by kk2007yx** [comment]
> 我建议你，F12 控制台看看报错返回的什么信息。你这样的问答什么内容都没有。让人很懵逼

Failed to load resource: the server responded with a status of 500 ()  这句话也看不出啥啊

**Comment by ssrpanel** [comment]
估计没升级数据库

**Comment by kk2007yx** [comment]
好的 我去检查下是哪个数据库没更新
