### ISSUE TITLE
升级面板后负载瞬间飚满

### ISSUE THREAD

**Issue by maxwellhouse102** [ssrpanel/SSRPanel#1482]
升级了面板后负载瞬间就飚满了，是最新面板有问题吗
![image](https://user-images.githubusercontent.com/25824373/54488457-f613ab80-48dc-11e9-9199-89801d21f2a9.png)

**Comment by littlesker** [comment]
肯定的！这还要提问

**Comment by 828768** [comment]
你这垃圾服务器行不行，自己心里没点数？
