### ISSUE TITLE
加功能，订阅地址不同解析格式

### ISSUE THREAD

**Issue by Jinxs9** [ssrpanel/SSRPanel#1485]
不同客户端不同解析格式
![image](https://user-images.githubusercontent.com/42931911/54514957-73e7bd80-4996-11e9-8451-8c898229e5d0.png)

**Comment by ssrpanel** [comment]
那个叼毛tony 二开完也不来提PR，群里叼他

**Comment by samac08** [comment]
> 那个叼毛tony 二开完也不来提PR，群里叼他
@ssrpanel  这个订阅确实该改进了 还有kit也是不能订阅 现在就火箭是完美混合ssr+v2订阅 圈仅能ssr i2ray
可以V2  MAC下主力的v2rayX 也是不能订阅 clash设计很不友好 装了都不过三分钟就删除了 个人感觉不需要考虑这个....

**Comment by ZBrettonYe** [comment]
@329928  方便服务他们的链接，然后把他们的json文件 格式 发过来一下吗？

我觉的这个没什么难度
