### ISSUE TITLE
SSRPanel可以限制节点的流量吗？

### ISSUE THREAD

**Issue by Mr-Kwok** [ssrpanel/SSRPanel#1487]
SSRPanel可以限制节点的流量吗？比如给节点限制1T的流量上限，到达1T流量节点自动离线。

**Comment by littlesker** [comment]
这个可以唉！

**Comment by Mr-Kwok** [comment]
> 这个可以唉！

请问这个功能要在哪里操作啊？我添加节点时没有找到这个功能项，系统设置里也没有这个选项啊！

**Comment by ssrpanel** [comment]
目前不支持。marked
