### ISSUE TITLE
如果面板服务器IP被墙，支付宝回调信息能收到吗

### ISSUE THREAD

**Issue by FPSRussia** [ssrpanel/SSRPanel#1489]

**Comment by big-chief** [comment]
大佬。你也出现支付之后状态没更新的问题了吗？

**Comment by FPSRussia** [comment]
> 大佬。你也出现支付之后状态没更新的问题了吗？

我已经很久没更新了

**Comment by Blackyezi** [comment]
同样的问题用的f2fpay支付后一直回调不了。之前是可以的

**Comment by mlgexyz** [comment]
回调失败的各位检查一下日志文件（不是文件夹）的权限是否是777

**Comment by ssrpanel** [comment]
如果面板IP在国外，被墙了，肯定无法回调，因为支付宝也无法连上这个IP，如果在墙内，就没有墙不墙的概念了
