### ISSUE TITLE
全新安装的，后台点击设置-系统设置报错

### ISSUE THREAD

**Issue by lbwanwan** [ssrpanel/SSRPanel#1490]
ErrorException (E_ERROR)
Undefined variable: f2fpay_subject_name (View: /www/wwwroot/****/ssrpanel/resources/views/admin/system.blade.php)

**Comment by Uhtred009** [comment]
我也遇到了这个问题  ，装过好几次了 看好像是 支付接口有什么不对

**Comment by mlgexyz** [comment]
重新拉取并安装，问题已修复
