### ISSUE TITLE
V2ray后端，ss+ws的支持

### ISSUE THREAD

**Issue by rico93** [ssrpanel/SSRPanel#1491]
1. 主要获得的数据和v2ray版本一致，
2. 新增一个host混淆，这部分是 sspanel的逻辑代码，地址https://github.com/Anankke/ss-panel-v3-mod_Uim/blob/0e999814b65c202b373ea7e50cac062b11633961/app/Models/User.php#L59, 目前把这个整个当做host了，后期会重新用一个新key在headers里面

**Comment by yulewang** [comment]
那原版ss也可以单端了么？

**Comment by rico93** [comment]
需要支持v2ray-plugin
