### ISSUE TITLE
安装面板后，出现这个错误

### ISSUE THREAD

**Issue by zssshk** [ssrpanel/SSRPanel#1497]
Undefined variable: f2fpay_subject_name

**Comment by elvischao** [comment]
是系统设置-支付宝当面付-自定义商品名称 的部分安装后报错的

**Comment by changwangyun** [comment]
解决没有。我也是这样

**Comment by zssshk** [comment]
还没有解决！不知道怎么弄

**Comment by changwangyun** [comment]
我知道了。数据库执行

INSERT INTO `config` VALUES ('89', 'f2fpay_subject_name', '');

**Comment by zssshk** [comment]
谢谢这位朋友！
