### ISSUE TITLE
大佬 顺便弄个Q群交流交流 

### ISSUE THREAD

**Issue by ftwl516** [ssrpanel/ssrpanel#15]
那个什么群不会用啊

**Comment by ftwl516** [comment]
另对接如果能像魔改那样用WEBAPI会更方便吧 多节点使用的情况下

**Comment by ssrpanel** [comment]
WEBAPI你的用途是什么？我从未使用过。不知道你们的应用场景是什么？我研究下搞一搞？

**Comment by ssrpanel** [comment]
@ftwl516

**Comment by ftwl516** [comment]
多节点使用的时候,用WEBAPI方式可能会更安全些吧.不用把数据库暴露到公网IP中!

**Comment by ftwl516** [comment]
https://91vps.us/2017/08/24/ss-panel-v3-mod/ 可以参考下这个的功能  
还是喜欢您的界面!

**Comment by ftwl516** [comment]
![image](https://user-images.githubusercontent.com/30188650/30203799-def3c796-94b5-11e7-8528-1e076e48d92c.png)
这两个有区别?加密方式和自定义加密方式 只要一个就行了吧?

**Comment by ssrpanel** [comment]
@ftwl516 嗯，按照你的意见我把那个自定义的隐藏了，貌似没用，以前有套go版本的后端用这个字段，不过没卵用了。你拉下最新的代码

WEBAPI，，，我研究下先。。目前我自己手上买了3台KVM小鸡（求打赏我再买几台）做多节点，还是需要运维基础才能搞的定的。我是通过mysql 授权特定指定账号（账号只允许子节点机的IP连接主节点），不过如果子节点被共计一样整个库都会完蛋。看来这个应该很有趣。过阵子我把这些多节点写一份部署教程都发出来

**Comment by ftwl516** [comment]
手上还有台2核4G 5M带宽的华为云主机 应该还有几个月 可以拿去用!

**Comment by ftwl516** [comment]
节点管理里面 还有算定义加密方式  拉了最新代码了!

**Comment by ssrpanel** [comment]
@ftwl516 代码更新了，国内的机器不玩。

**Comment by max2max** [comment]
telegram是只有频道没有群组吗？
