### ISSUE TITLE
用户和节点的管理 - 防备节点被D影响全局

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#150]
胖虎:今天有个节点被D, 目前只要有用户注册就可以看到全部节点,这让我想起来需要建立用户和节点容器来隔离避免全军覆没的问题, 避免任一用户注册可以看到全部节点信息. 以下是我的思路供参考:

任意节点创立时候都必须强制限制在某一个区域(容器中),每个容器种可以容纳节点数量可以自定义, 比如容器A可以容纳3个节点.容器B可以容纳4个节点.

任意用户注册时候都必须强制性的划入到某一个容器, 这样一旦某个节点被D.立刻就明白是这个容器某个用户出问题, 可以用排除法慢慢加以识别即可.

用户可以被管理员移动到任一个容器 (其实也就是群组概念了), 一旦判断某个用户可靠就可以被管理员手动移动到另外一个容器中,临时解决方案可用, 以上思路可以较大概率的减少节点信息对整站造成影响.

比如一个容器我限制100个用户, 只能看到3个节点, 第101个用户自动强制性加入到下个容器中, 只能看到下个容器中的节点数量.

对于付费用户来说, 每看到一个容器中节点,他需要付费的, 也算是有代价的.

目前你的管理系统已经有分组系统,修改完善下应该可以完成上面的想法的,比如节点创立时候强制划入到某个容器, 用户注册时候强制性被系统归纳到某个容器中.

**Comment by ssrpanel** [comment]
不是有等级分组吗？

**Comment by 1021435278** [comment]
是的, 不过如果能够直接在管理员管理阶段把节点也用容器归纳管理的方式就好办了...
