### ISSUE TITLE
面板更新体系的建议

### ISSUE THREAD

**Issue by Dennishaha** [ssrpanel/SSRPanel#1501]
建议在面板管理界面做个更新面板的界面并可点击自动更新数据库。
类似于 WordPress 的方法，降低学习成本。
![ww](https://user-images.githubusercontent.com/38273998/54874583-30bf9b80-4e29-11e9-8804-feb684bebaf2.jpg)

**Comment by mlgexyz** [comment]
提高出错几率

**Comment by littlesker** [comment]
没用的功能
