### ISSUE TITLE
更新后500错误

### ISSUE THREAD

**Issue by thank243** [ssrpanel/SSRPanel#1504]
In ProviderRepository.php line 208:
                                                             
  Class 'Misechow\Geetest\GeetestServiceProvider' not found  
                                                             

In ProviderRepository.php line 208:
                                                             
  Class 'Misechow\Geetest\GeetestServiceProvider' not found  
                                                             

In ProviderRepository.php line 208:
                                                             
  Class 'Misechow\Geetest\GeetestServiceProvider' not found

**Comment by MIseChow** [comment]
试下更新下依赖 php composer.phar update

**Comment by thank243** [comment]
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
Killed

**Comment by MIseChow** [comment]
这个只是警示而已吧，正常还是可以继续更新的吧
如果不行试试 composer update

**Comment by ssrpanel** [comment]
php composer.phar install

**Comment by ssrpanel** [comment]
@MIseChow 啊，你项目改名了

**Comment by MIseChow** [comment]
我项目依赖没有改啊 怎么啦？出错了？
