### ISSUE TITLE
来个订单完成推送？方糖邮件？

### ISSUE THREAD

**Issue by ghost** [ssrpanel/SSRPanel#1507]
。

**Comment by Uhtred009** [comment]
现在支付api的接口都有这个功能吧 ？

**Comment by vft9nesd** [comment]
当面付  没提醒啊。。通知都开着呢。。

**Comment by ssrpanel** [comment]
marked

**Comment by ssrpanel** [comment]
我淘宝体系全部被封了，除了支付宝，是不是只要支付宝还活着就行？

**Comment by vft9nesd** [comment]
> 我淘宝体系全部被封了，除了支付宝，是不是只要支付宝还活着就行？

很奇怪啊  我没开当面付的时间  收款通知还在  开了当面付  怎么都找不到入口了  。。收钱码的下面 提示我开启收款通知  点进去毛都没有

**Comment by ssrpanel** [comment]
已加
