### ISSUE TITLE
有关节点列表无法显示的问题

### ISSUE THREAD

**Issue by lryyy** [ssrpanel/SSRPanel#1509]
你好，以"节点列表"、“无法购买服务”、“购买服务”等关键词进行检索后无法检索相关问题，发issue提问一下：
     普通用户登陆后，点击节点列表，订阅服务下只显示“请先购买服务”提示；无论购买套餐还是流量包均无法解决。在admin账户内查看的订阅连接可正常使用，前端后端配置应该正常。
     请问是不是我哪里的配置出现问题，应该做如何修正，烦请解答，谢谢！

**Comment by garhing** [comment]
请确认所购服务是否包含相应的节点标签。

**Comment by lryyy** [comment]
> 请确认所购服务是否包含相应的节点标签。

谢谢，已解决。

后面的同学请注意，节点列表中节点需设置标签，套餐中需要将相应的标签选上，然后普通用户订购套餐时才能看到相应节点；不然的话一直显示请先购买服务。

DEAL!

**Comment by mlgexyz** [comment]
老哥关一下issue:blush:
