### ISSUE TITLE
ErrorException (E_ERROR) Undefined variable: login_add_score (View: /www/wwwroot//resources/views/admin/system.blade.php) Previous exceptions Undefined variable: login_add_score (0)

### ISSUE THREAD

**Issue by maxwellhouse102** [ssrpanel/SSRPanel#1511]
ErrorException (E_ERROR)
Undefined variable: login_add_score (View: /www/wwwroot//resources/views/admin/system.blade.php)
Previous exceptions
Undefined variable: login_add_score (0)

**Comment by vft9nesd** [comment]
对着你的ip 反手就是一个举报 ^_^

**Comment by jackyeow** [comment]
ping了下，丢包率好高啊，vultr日本服务器已经不能玩了：）

**Comment by dawfds** [comment]
你是真的nb
