### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by 110560** [ssrpanel/SSRPanel#1516]
验证码关闭之后，
登录页面还是在出现

**Comment by mlgexyz** [comment]
#1513 中已经修复了此问题，等代码合并入主干后更新即可。

**Comment by wongyuehan** [comment]
购买后用户无法订阅节点 仍然显示需要购买服务

**Comment by mlgexyz** [comment]
@wongyuehan 要反馈bug去自己建个issue，在别人的issue下发没有用，作者又不一定看得到。请先学会github基本使用方法:blush:
