### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by one-mo** [ssrpanel/SSRPanel#1517]
PC端的页面还可以，但还是允许我吐槽一下，手机端的页面真的差劲，页面不兼容，希望针对手机端UI进行改进一下。（个人感觉和意见，没有恶意）

**Comment by mlgexyz** [comment]
请附上截图以及所使用的浏览器名称

**Comment by one-mo** [comment]
机型：OPPO Find X 
浏览器：Google Chrome 
后台部分按钮或页面超出屏幕，如编辑节点时，截图稍后附上

**Comment by one-mo** [comment]
以及部分按钮较大，如  用户中心-购买服务页面，说明、套餐、流量包页面显示拥挤，字体较大，显示很不协调

**Comment by mlgexyz** [comment]
超出屏幕的问题我也有，横屏可以解决

**Comment by ZBrettonYe** [comment]
这个问题只需要 胖虎改皮了， 就都可以解决

**Comment by ssrpanel** [comment]
那个无解，我问过专业前端开发，因为在table里，除非又改成以前那种操作模式
