### ISSUE TITLE
网页修改的信息无法提交

### ISSUE THREAD

**Issue by 110560** [ssrpanel/ssrpanel#152]
29号到现在重装了不下7次系统   前端搭建好后，进去网页无法修改任何东西 比如用户名 密码   手机谷歌浏览器  别人的能进我网页   能帮我修改默认密码，但是邀请码也不能生成。。。，请解决，数据库每次都是拉取代码下载再导入，，确定不是数据库丢失字节问题，，，，，

**Comment by 110560** [comment]
操作流程  前后端搭建完成  修改默认 账号密码   添加第一个节点       生成邀请码    修改通用配置和网页信息   退出  注册第二个账号测试接收邮件  成功   回到管理员账号  添加第二个节点 网页出现无法提交任何修改过的数据  退出管理账号  登陆注册的第二个普通账号  测试 修改密码 成功，，，再次登陆第一个管理员账号  还是无法提交任何信息，，。日志用tg发给你了

**Comment by ssrpanel** [comment]
找不到问题就重建数据库啊
