### ISSUE TITLE
建议增加一个更改所有（批量）用户混淆协议等的选项。

### ISSUE THREAD

**Issue by Nisekoi5** [ssrpanel/SSRPanel#1527]
由于是优先使用用户设置。然后想更换协议了需要一个用户一个用户的点开。如果用户多的话非常繁琐，
或者每个节点在创建的时候可以设置优先使用用户设置或者是节点

**Comment by Alan0429** [comment]
我直接进数据库改，哈哈哈

**Comment by cmtomkan310** [comment]
UPDATE ssrpanel.user SET method = 'aes-192-ctr' WHERE method = 'aes-256-cfb'

根据自己需求，改‘’里面的参数即可！

**Comment by Nisekoi5** [comment]
> UPDATE ssrpanel.user SET method = 'aes-192-ctr' WHERE method = 'aes-256-cfb'
> 
> 根据自己需求，改‘’里面的参数即可！

只有这样了。先备份好 ，然后导出数据表批量替换。
