### ISSUE TITLE
提个建议！增加在线版本更新功能！

### ISSUE THREAD

**Issue by zssshk** [ssrpanel/SSRPanel#1528]
我这搭建好后，都不敢更新。一更新不是那个错误，就是那个错误！提示php版本过低！我都用php7.2了！宝塔里面只有php7.1，没有7.1.3这个版本！还有，git pull 提示什么需要更改或者保存本地配置什么的。反正更新后，打来后台就会出错！也不知道是哪里的问题！

**Comment by littlesker** [comment]
在线更新没有任何用处，反而错误更多，错误还是自己排查，多搜搜才可以
