### ISSUE TITLE
反馈一下BUG

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/ssrpanel#153]
主界面的盈利是按照分....；

胖虎让数据库用分显示钱，之后的主界面显示麻烦还是用元显示吧

**Comment by ZBrettonYe** [comment]
还有一个错误：
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ssrpanel.user_traffic_daily' doesn't exist (SQL: select * from `user_traffic_daily` where `user_id` = 1 and `node_id` = 0 order by `id` desc limit 30)
看起来 数据库升级里  没有user_traffic_daily 这个数据库

**Comment by ZBrettonYe** [comment]
文章访问日志报错：SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ssrpanel.article_log' doesn't exist (SQL: select count(*) as aggregate from `article_log`)

**Comment by ZBrettonYe** [comment]
还有就是邮箱发生偶尔会有Connection could not be established with host smtp.exmail.qq.com [Connection timed out #110] 这个报错；
据我猜测是发生邮箱太频繁造成的；

希望可以设置个 重发按钮，管理员可以选择重发邮件；每个邮件发生设置一个间隔；

**Comment by ZBrettonYe** [comment]
还有就是近期添加的流量异常阈值功能， 可以的话， 麻烦添加一个邮箱提醒功能；

 内容大概是X时间内消耗XGB流量，系统检测异常，联系管理，限制会在X时间后自动解除；同时希望规范使用服务等等

**Comment by ssrpanel** [comment]
@ZBrettonYe 哪有2位？？？
自己看下sql目录下，每次更新都有放sql进去，不然就去sql/db.sql里找
第一个问题今天早上更新了
