### ISSUE TITLE
php composer.phar install提示版本过低！

### ISSUE THREAD

**Issue by zssshk** [ssrpanel/SSRPanel#1530]
我已经在宝塔里面切换了PHP版本了！
[root@host ssrpanel]# php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php ^7.1.3 but your HHVM version does not satisfy that requirement.
  Problem 2
    - barryvdh/laravel-ide-helper v2.6.1 requires php >=7 -> your PHP version (5.6.30) does not satisfy that requirement.
    - barryvdh/laravel-ide-helper v2.6.1 requires php >=7 -> your PHP version (5.6.30) does not satisfy that requirement.
    - Installation request for barryvdh/laravel-ide-helper v2.6.1 -> satisfiable by barryvdh/laravel-ide-helper[v2.6.1].

You have new mail in /var/spool/mail/root

**Comment by littlesker** [comment]
重装宝塔

**Comment by ssrpanel** [comment]
PHP 版本低于7，至少要求7.1.3

**Comment by mlch911** [comment]
你必须确保你系统的默认php是7.1.3以上才行。要么你去给这个php建一个别名，或者直接在宝塔里把其它版本删了，这个装好了再把那些装回来
