### ISSUE TITLE
关于点进去‘邀请管理’出错的问题

### ISSUE THREAD

**Issue by ntgeralt** [ssrpanel/SSRPanel#1536]
你好，我在今天4月8日在新的VPS装了您的ssrpanel测试，数据库为最初自动导入那个，admin进去发现点‘邀请管理’出现Whoops, looks like something went wrong.

去日志看有下面一段内容，我水平不够看不懂，能不能指点一二……

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'invite.deleted_at' in 'where clause' (SQL: select count(*) as aggregate from `invite` where `invite`.`deleted_at` is null) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'invite.deleted_at' in 'where clause' (SQL: select count(*) as aggregate from `invite` where `invite`.`deleted_at` is null) at /www/wwwroot/frgh567.3322f.net/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'invite.deleted_at' in 'where clause' at /www/wwwroot/frgh567.3322f.net/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:326)

**Comment by dawfds** [comment]
数据库没导入

**Comment by ntgeralt** [comment]
> 数据库没导入


在新的vps，数据库用的
git clone https://github.com/ssrpanel/ssrpanel.git ssrpanel
默认的那个哦

**Comment by xDingDang** [comment]
数据库执行下 根目录 sql/update/20190403.sql & sql/update/20190404.sql 这两个sql文件

**Comment by ntgeralt** [comment]
导入20190404不成功，后来自行在invite增加deleted_at解决。参考了article的deleted_at格式。

**Comment by xDingDang** [comment]
> 
> 
> 导入20190404不成功，后来自行在invite增加deleted_at解决。参考了article的deleted_at格式。

那是因为你数据库并没有 is_del 字段，所以执行出错中断了。
把 sql 前四个 语句 删除再执行就没事了。

**Comment by redtechma** [comment]
一模一样的 不是普遍错误吧
