### ISSUE TITLE
How to Fix this ?

### ISSUE THREAD

**Issue by Aistrix** [ssrpanel/SSRPanel#1537]
![image](https://user-images.githubusercontent.com/49381267/55694889-d443ab00-59e8-11e9-95d2-c8ffd8e78b44.png)
im from philippines, itry to build that panel on hosting

**Comment by ntgeralt** [comment]
https://github.com/ssrpanel/SSRPanel/wiki/SSRPanel%E6%90%AD%E5%BB%BA%E6%95%99%E7%A8%8B%EF%BC%88LNMP%EF%BC%89

no need to change  .env file.

**Comment by ssrpanel** [comment]
https://github.com/ssrpanel/SSRPanel/blob/master/.env.example
