### ISSUE TITLE
优化圈订阅到期信息显示 

### ISSUE THREAD

**Issue by samac08** [ssrpanel/SSRPanel#1538]
@ssrpanel  虎哥优化下圈的订阅信息吧 添加用户到期头字段 我测试手动添加user表Unix_time字段并赋值UTC时间戳 更新订阅测试结果完美,  现在是SQL需要写用户UTC时间 值即可正常调用 靠你了 ....

-----------------修改后圈 响应头------------
if (self::$systemConfig['is_custom_subscribe']) {
            $headers = [
                'Content-type'          => 'application/octet-stream; charset=utf-8',
                'Cache-Control'         => 'no-store, no-cache, must-revalidate',
                'Subscription-Userinfo' => 'upload=' . $user->u . '; download=' . $user->d . '; expire=' .$user->Unix_time . '; total=' . $user->transfer_enable
            ];
-----------------------------
<a href="https://imgchr.com/i/A4g29g"><img src="https://s2.ax1x.com/2019/04/08/A4g29g.md.jpg" alt="A4g29g.jpg" border="0" /></a>
-----------------------------
编码规范:
The expire=1862111613 is the seconds from 00:00:00 UTC, January 1, 1970

Subscription-Userinfo: upload=2375927198; download=12983696043; total=1099511627776; expire=1862111613

**Comment by samac08** [comment]
> @ssrpanel 虎哥优化下圈的订阅信息吧 添加用户到期头字段 我测试手动添加user表Unix_time字段并赋值UTC时间戳 更新订阅测试结果完美, 现在是SQL需要写用户UTC时间 值即可正常调用 靠你了 ....
> 
> ## -----------------修改后圈 响应头------------
> if (self::$systemConfig['is_custom_subscribe']) {
> $headers = [
> 'Content-type' => 'application/octet-stream; charset=utf-8',
> 'Cache-Control' => 'no-store, no-cache, must-revalidate',
> 'Subscription-Userinfo' => 'upload=' . $user->u . '; download=' . $user->d . '; expire=' .$user->Unix_time . '; total=' . $user->transfer_enable
> ];
> ## [![A4g29g.jpg](https://camo.githubusercontent.com/fa77139916277bc141f4c2cd20b84deebc5a85dd/68747470733a2f2f73322e617831782e636f6d2f323031392f30342f30382f4134673239672e6d642e6a7067)](https://imgchr.com/i/A4g29g)
> 编码规范:
> The expire=1862111613 is the seconds from 00:00:00 UTC, January 1, 1970
> 
> Subscription-Userinfo: upload=2375927198; download=12983696043; total=1099511627776; expire=1862111613
----------------源地址有更多URI Scheme说明 及圈 X----------------
https://github.com/crossutility

**Comment by ssrpanel** [comment]
主要是我不晓得哪个URI SCHEME

**Comment by ssrpanel** [comment]
https://github.com/crossutility/Quantumult/blob/master/extra-subscription-feature.md

**Comment by samac08** [comment]
@ssrpanel   
----------------Quantumult-----------------
<img src="https://s2.ax1x.com/2019/04/08/A4TnVH.jpg" alt="A4TnVH.jpg" border="0" />

------------------kitsunebi ----------------------
官方订阅地址: https://raw.githubusercontent.com/eycorsican/rule-sets/master/kitsunebi_sub
---------------------------------------------------

这下因该支持完整了 有这些应该足够了 虎哥看你的了...

**Comment by ssrpanel** [comment]
@samac08 代码提了，不过你这种效果我根本不知道从哪才能展示出来？？？quan的

**Comment by samac08** [comment]
@ssrpanel 虎哥  你在首页中间圆点击那个测速会就会显示  提交下 圈现有支持的订阅编码
`vmess://TCP订阅=vmess, www.aa.com, 443, chacha20-ietf-poly1305, "362c1a5b-5042-4625-9258-a91ec0bebbbc", group=节点组A, over-tls=false, tls-host=www.aa.com, certificate=1[Rr][Nn]User-Agent: safari/5.1

vmess://WS+TLS订阅B=vmess, www.bb.com, 443, chacha20-ietf-poly1305, "362c1a5b-5042-4625-9258-a91ec0bebbbc", group=节点组B, over-tls=true, tls-host=www.bb.com, certificate=1, obfs=ws, obfs-path="/path", obfs-header="Host: www.bb.com[Rr][Nn]User-Agent: safari/5.1

vmess://HTTP+TLS订阅=vmess, www.cc.com, 443, chacha20-ietf-poly1305, "362c1a5b-5042-4625-9258-a91ec0bebbbc", group=节点组C, over-tls=true, tls-host=www.cc.com, certificate=1, obfs=http, obfs-header="Host: www.cc.com[Rr][Nn]User-Agent: safari/5.1`

**Comment by samac08** [comment]
@ssrpanel  kitsunebi 订阅
 
vmess://Y2hhY2hhMjAtcG9seTEzMDU6OTUxMzc4NTctNzBmYS00YWM4LThmOTAtNGUyMGFlYjY2MmNmQHVuaS5raXRzdW5lYmkuZnVuOjEwMDI1?network=tcp&aid=0&tls=0&allowInsecure=1&mux=0&muxConcurrency=8&remark=TCP%20Test%20Outbound

vmess://Y2hhY2hhMjAtcG9seTEzMDU6OTUxMzc4NTctNzBmYS00YWM4LThmOTAtNGUyMGFlYjY2MmNmQHVuaS5raXRzdW5lYmkuZnVuOjgw?network=ws&wsPath=/v2&aid=0&tls=0&allowInsecure=1&mux=0&muxConcurrency=8&remark=WS%20Test%20Outbound

vmess://Y2hhY2hhMjAtcG9seTEzMDU6OTUxMzc4NTctNzBmYS00YWM4LThmOTAtNGUyMGFlYjY2MmNmQHVuaS5raXRzdW5lYmkuZnVuOjU2NjY=?network=ws&wsPath=/v2&aid=0&tls=1&allowInsecure=1&mux=0&muxConcurrency=8&remark=WSS%20Test%20Outbound

vmess://Y2hhY2hhMjAtcG9seTEzMDU6OTUxMzc4NTctNzBmYS00YWM4LThmOTAtNGUyMGFlYjY2MmNmQHVuaS5raXRzdW5lYmkuZnVuOjQ0Mw==?network=h2&h2Path=/v2&aid=0&tls=1&allowInsecure=0&tlsServer=uni.kitsunebi.fun&mux=0&muxConcurrency=8&remark=H2%20Test%20Outbound

vmess://Y2hhY2hhMjAtcG9seTEzMDU6OTUxMzc4NTctNzBmYS00YWM4LThmOTAtNGUyMGFlYjY2MmNmQHVuaS5raXRzdW5lYmkuZnVuOjEwMDI1?network=kcp&uplinkCapacity=1&downlinkCapacity=4&aid=0&tls=0&allowInsecure=1&mux=1&muxConcurrency=8&remark=KCP%20Test%20Outbound

**Comment by samac08** [comment]
@ssrpanel  主流使用基本OK了  剩下的就靠虎哥了 辛苦!......

**Comment by ssrpanel** [comment]
marked

**Comment by FenghenHome** [comment]
@samac08
圈的http协议对应v2ray的那种h2？

**Comment by 766** [comment]
> 主要是我不晓得哪个URI SCHEME

虎佬，py一下内部群呗
