### ISSUE TITLE
节点和用户都可以归组的建议.

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#154]
参考https://github.com/ssrpanel/ssrpanel/issues/150

我觉得还是增加个节点归组的功能, 这样某节点通过加入某个节点组后可以指定派给某个用户群组.

极端情况下, 一个节点组划给一个用户单独拥有的群组, 容易实现管理.

-比如某企业所有用户划入专有群组, 并指定节点组, 没有外人, 容易管理, 且客户体验很好.

建议强制新用户注册进来时候务必需要管理员手动划入某个群组,这样收费和免费用户就很容易做到区别对待了, 这种情况下,千人/万人机场将会重新出现, DDCC无任何作用.

**Comment by ssrpanel** [comment]
我还是没明白，节点分组不就是节点归组吗？

**Comment by 1021435278** [comment]
其实应该是我没表达清楚, 节点列表中排列按照节点组别显示,甚至可以直接在节点组别中把节点移动到任一组别就可以, 这样比较直观方便管理.
另外用户也增加个按照组别显示就基本可以了.   
建议整站管理中增加个用户注册后是管理员手动加入到某个节点群组还是直接加入到默认群组功能.

最后请教下,最新支付接口是内置谁家的支付?  能否方便参看wordpress/magento后台插件形式,增加个Paypal支付吗?
