### ISSUE TITLE
已删除的商品相关订单页面打开报错

### ISSUE THREAD

**Issue by 329928** [ssrpanel/SSRPanel#1542]
![image](https://user-images.githubusercontent.com/42931911/55818256-cdbc4d00-5b28-11e9-9cf5-5452211fb0e6.png)
发现是这句代码的锅；
因为有用户购买过旧套餐，当旧套餐删除掉之后，订单页面关于旧套餐这一页或详情 就无法打开，并且提示服务已删除（繁体字），估计其他的优惠券文章之类的都是这种情况。

**Comment by ssrpanel** [comment]
已修复

**Comment by ssrpanel** [comment]
这个是软删除。
