### ISSUE TITLE
流量变动查看,订单查看都报错 Access Denied

### ISSUE THREAD

**Issue by x6893** [ssrpanel/SSRPanel#1543]
Trying to get property of non-object (View: /www/wwwroot/www.iiiqy.xyz/resources/views/admin/userTrafficLogList.blade.php) {"userId":1,"exception":"[object] (ErrorException(code: 0): Trying to get property of non-object (View: /www/wwwroot/www.xxxxx.xyz/resources/views/admin/userTrafficLogList.blade.php) at /www/wwwroot/www.xxxxx.xyz/storage/framework/views/72dbdf6a9d3ff36d24a5eb554958c7de638c8183.php:62, ErrorException(code: 0): Trying to get property of non-object at /www/wwwroot/www.xxxxx.xyz/storage/framework/views/72dbdf6a9d3ff36d24a5eb554958c7de638c8183.php:62)

**Comment by ssrpanel** [comment]
已修复
