### ISSUE TITLE
digital-vm

### ISSUE THREAD

**Issue by cmtomkan310** [ssrpanel/SSRPanel#1544]
更正几个问题
这个VPS，线路和IP没什么问题。用VMNEW只能用于月付。季度、半年、年付用此优惠吗无效，并且我也和在线客服落实此问题。新账号也是一样！说白了，这个优惠吗只能月付！

**Comment by cmtomkan310** [comment]
![image](https://user-images.githubusercontent.com/38905231/55887469-24389280-5be0-11e9-8266-42a757126eb0.png)

**Comment by cmtomkan310** [comment]
![image](https://user-images.githubusercontent.com/38905231/55887527-3f0b0700-5be0-11e9-8c05-69ce9f03459b.png)

季付无效
备注：新账号

**Comment by cmtomkan310** [comment]
![image](https://user-images.githubusercontent.com/38905231/55887594-5a761200-5be0-11e9-8888-7da9204468fa.png)

年付无效

**Comment by cmtomkan310** [comment]
![image](https://user-images.githubusercontent.com/38905231/55887715-91e4be80-5be0-11e9-89ee-c445caa134b1.png)

新账号

**Comment by ssrpanel** [comment]
我日。。反正我买了1台月付，4台半年付，都没有用码
