### ISSUE TITLE
能考虑增加虚拟货币支付吗？比如说比特币？

### ISSUE THREAD

**Issue by Indi55erent** [ssrpanel/SSRPanel#1545]
我认为用虚拟货币交易更安全，在中国大陆，使用支付宝、微信收款都是不安全的，最近一段时间以来，有什么VPN提供商已经被拘捕了，我认为是时候考虑增加虚拟货币付款 的条件了，比如说比特币，就是一个可以用来交易的货币。

**Comment by littlesker** [comment]
会用比特币的不会买你的节点

**Comment by Zhangziheng1** [comment]
@littlesker  言之有理

**Comment by ssrpanel** [comment]
不加，需要定制私信我
