### ISSUE TITLE
SSRPanel面板v2ray-Go节点显示不正常，不显示在线人数。

### ISSUE THREAD

**Issue by Mr-Kwok** [ssrpanel/SSRPanel#1546]
SSRPanel面板v2ray-Go节点显示不正常，不显示在线人数。
服务器系统：Centos7.6
服务端：V2ray-Go版
SSRPanel面板节点在线状态显示一串数字，之前用SS魔改版的服务端节点状态也是显示一串数字，换成了SS-Go版就能正常显示CPU+内存+硬盘信息了，难道面板不匹配V2ray-Go版吗？还有在线人数一直显示为0，不知道咋搞啊！

**Comment by ssrpanel** [comment]
V2RAY go版本得问下作者

**Comment by Mr-Kwok** [comment]
请问原版的V2ray可以在ssrpanel正常显示吗？或者有没有可推荐的版本？

**Comment by Mr-Kwok** [comment]
还有目前最好的SSR服务端就是SS-Go了吗？

**Comment by Mr-Kwok** [comment]
什么时候可以支持设置节点流量上限功能？

**Comment by Mr-Kwok** [comment]
还有速度限制单位可否改成MB？每次换算byte有点吃力。
