### ISSUE TITLE
请教下  “节点订阅”的问题

### ISSUE THREAD

**Issue by tudi1909** [ssrpanel/SSRPanel#1547]
最新版安装完成，前期没有填写空白，但现在另一个二级域名 xxx.baidu.com 就不能识别，客户端填写 www.baidu.com 即可识别订阅，不知道如何处理 感谢！

**Comment by xMiaoMiaoi** [comment]
xxx.baidu.com 要A解析去面板

**Comment by tudi1909** [comment]
> xxx.baidu.com 要A解析去面板

嗯这个已经设置过的

**Comment by xMiaoMiaoi** [comment]
把 xxx.baidu.com 域名解析后面板服务器后
ping 一下 xxx.baidu.com , 确认是否生效为自己的服务器IP
然后后台配置填 http://xxx.baidu.com 或者 https
然后就可以啦

**Comment by tudi1909** [comment]
解析可以确定是正确的，但就是填写上不能生效，只能是以前的面板域名

**Comment by tudi1909** [comment]
@xMiaoMiaoi 已自行解决，感谢！
