### ISSUE TITLE
报告一个小BUG哦

### ISSUE THREAD

**Issue by dxdbl** [ssrpanel/SSRPanel#1548]
1.面板有节点在运行；
2.有用户使用此节点产生流量记录，已经写入user_traffic_log表；
3.管理中心删除此节点；
4.再次查看流量日志页面报错哦；
原因：user_traffic_log表中的node_id字段关联不上节点名称；
修改建议：
1.管理员删除某个节点时，除了移除ss_node表相关信息外，也删除user_traffic_log表相应记录；
  delete from user_traffic_log where node_id = '2';
2.或者不删除user_traffic_log表相应记录，关联结果返回null的话用其他字符串代替；
个人愚见，仅供参考，勿喷我哦哈哈

**Comment by ssrpanel** [comment]
fixed
