### ISSUE TITLE
请问在更新代码的时候！出现这个错误！

### ISSUE THREAD

**Issue by zssshk** [ssrpanel/SSRPanel#1549]
php composer.phar install
运行这个命令！出现以下错误！
[root@host ssrpanel]# php composer.phar install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php ^7.1.3 but your HHVM version does not satisfy that requirement.
  Problem 2
    - Installation request for barryvdh/laravel-ide-helper v2.6.2 -> satisfiable by barryvdh/laravel-ide-helper[v2.6.2].
    - barryvdh/laravel-ide-helper v2.6.2 requires php >=7 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 3
    - Installation request for dragonmantank/cron-expression v2.3.0 -> satisfiable by dragonmantank/cron-expression[v2.3.0].
    - dragonmantank/cron-expression v2.3.0 requires php ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 4
    - Installation request for erusev/parsedown 1.7.3 -> satisfiable by erusev/parsedown[1.7.3].
    - erusev/parsedown 1.7.3 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 5
    - Installation request for league/flysystem 1.0.51 -> satisfiable by league/flysystem[1.0.51].
    - league/flysystem 1.0.51 requires php >=5.5.9 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 6
    - Installation request for misechow/geetest v1.0.5 -> satisfiable by misechow/geetest[v1.0.5].
    - misechow/geetest v1.0.5 requires php >=5.6.0 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 7
    - Installation request for misechow/no-captcha v1.0.3 -> satisfiable by misechow/no-captcha[v1.0.3].

**Comment by xMiaoMiaoi** [comment]
最低要求PHP7。
将默认版本改成71。
命令 ln -sf /www/server/php/71/bin/php /usr/bin/php

**Comment by ssrpanel** [comment]
你php版本太低了，最低要求7.1.3
