### ISSUE TITLE
时区设置建议

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/ssrpanel#155]
图形界面配置时区的命令：
dpkg-reconfigure tzdata 

此方法更加方便，支持Debian, CentOS，Ubuntu 
1. 选择 Asia
2. 再选择 Shanghai

上下键 选择，回车键 确定

**Comment by ssrpanel** [comment]
-bash: dpkg-reconfigure: command not found
.....
还得install一下锕

**Comment by ZBrettonYe** [comment]
@ssrpanel apt-get install dpkg 
一般服务器都应该有吧，我下面20台服务器，也没去安装过，都有

**Comment by ssrpanel** [comment]
你是ubuntu吗？我都是centos

**Comment by ZBrettonYe** [comment]
我3个系统都有

**Comment by 1021435278** [comment]
@ZBrettonYe  centos无法安装啊
