### ISSUE TITLE
免费邀请码有页面logo需修复

### ISSUE THREAD

**Issue by vft9nesd** [ssrpanel/SSRPanel#1551]
![image](https://user-images.githubusercontent.com/49652677/56148651-4fa2ef00-5fdd-11e9-9a5e-add8cb018698.png)
不然很难看
![image](https://user-images.githubusercontent.com/49652677/56148916-eec7e680-5fdd-11e9-94ab-0924708d166f.png)

**Comment by ssrpanel** [comment]
自己做的图哭着也要自己改
