### ISSUE TITLE
小火箭二维码需修复

### ISSUE THREAD

**Issue by vft9nesd** [ssrpanel/SSRPanel#1552]
![image](https://user-images.githubusercontent.com/49652677/56149501-4adf3a80-5fdf-11e9-9b04-c87de5ff1c32.png)
![image](https://user-images.githubusercontent.com/49652677/56149601-811cba00-5fdf-11e9-8514-0f719bb7cbd8.png)

**Comment by ssrpanel** [comment]
已修复
