### ISSUE TITLE
只有一个用户能收到邮件，很奇怪。

### ISSUE THREAD

**Issue by JerryGai** [ssrpanel/SSRPanel#1553]
测试注册了几个用户，全部使用gmail的邮箱注册的。 只有一个邮箱的用户能收到激活码，或者正常使用忘记密码功能。
其他几个用户，收不到激活码，和忘记密码邮件。失败的日志提示“
Client error: `POST https://api.mailgun.net/v3/*************.mailgun.org/m...--”

成功的提示“投递成功”
--------------------------------------------------------------

之前配置过mailgun和smtp两种方式，后来去掉了mailgun，使用的是smtp方式。

为什么有一个用户能正常收到邮件？
为什么使用的是smtp，失败日志提示确是去找了 mailgun？

.env文件，mail.php, service.php里面 都没有mailgun的配置信息了。

**Comment by ssrpanel** [comment]
只要能收到，说明正常。
