### ISSUE TITLE
new pay method

### ISSUE THREAD

**Issue by ssrpanel** [ssrpanel/SSRPanel#1559]
http://www.hackwl.cn/jkwd/

**Comment by ntgeralt** [comment]
建议楼主优化一下内存消耗，GCP 700Mb也能用。但升一档到1.7G内存后网页明显快了，也贵了…

**Comment by ssrpanel** [comment]
@ntgeralt VPS配置吗？面板我向来只推荐1G+内存的，我自己用2G内存的搬瓦工CN2
