### ISSUE TITLE
改写的一键部署后台

### ISSUE THREAD

**Issue by maxzh0916** [ssrpanel/ssrpanel#156]
修改Hao-Luo大佬的SSR脚本，
https://github.com/maxzh0916/1ClickDeploy
我也是个小白，看着别人的代码自己瞎改着玩的。大佬觉得可以就加到wiki吧~

**Comment by ssrpanel** [comment]
@maxzh0916 感谢，容我测试一番就挂wiki

**Comment by ssrpanel** [comment]
@maxzh0916 已加wiki
