### ISSUE TITLE
UnexpectedValueException 报错，跪求解决办法

### ISSUE THREAD

**Issue by xfhack** [ssrpanel/SSRPanel#1561]
![QQ浏览器截图20190423151759](https://user-images.githubusercontent.com/22985419/56562076-3270b080-65db-11e9-8fed-9be84d96cd90.jpg)

**Comment by BigHead0599** [comment]
别这样,先起来说话!

**Comment by Mr-Kwok** [comment]
老版本会有这样那样的错误，F5刷新一下就正常了，重新安装最新版本，到现在任何报错从未出现过。

**Comment by ssrpanel** [comment]
权限问题
