### ISSUE TITLE
请问单端口怎么限制连接数和速度呢

### ISSUE THREAD

**Issue by a394484** [ssrpanel/SSRPanel#1566]
是在 additional_ports中修改"protocol_param": 和"speed_limit_per_user":  吗？

 "additional_ports" : {
          "8880": {
            "passwd": "p4ssw0rd",
            "method": "aes-256-cfb",
            "protocol": "auth_chain_a",
            "obfs": "plain",
            "obfs_param": ""
             //修改下面这两个？
            **"protocol_param": "1",**
            **"speed_limit_per_user":500 ,** 
        }
    },

**Comment by x1aoguan** [comment]
您好 ,请问修改过后有效果吗

**Comment by ssrpanel** [comment]
> 您好 ,请问修改过后有效果吗

自己试

**Comment by ssrpanel** [comment]
看wiki
