### ISSUE TITLE
chown: changing ownership of ‘./public/.user.ini’: Operation not permitted

### ISSUE THREAD

**Issue by Mr-Kwok** [ssrpanel/SSRPanel#1567]
目录下更新后提示：
chown: changing ownership of ‘./public/.user.ini’: Operation not permitted
啥问题啊？找了一下没发现有这个文件啊?

**Comment by sevewt** [comment]
这个文件是防跨站的，不影响使用的话不用管，如果打开显示 500 , 执行
```
#chattr -i 你的文件路径/.user.ini
```
然后修改或者删除。

**Comment by Mr-Kwok** [comment]
> 这个文件是防跨站的，不影响使用的话不用管，如果打开显示500，执行
> 
> ```
> #chattr -i 你的文件路径/.user.ini
> ```
> 
> 然后修改或者删除。

谢谢！
