### ISSUE TITLE
邮件发送失败，后台提示成功

### ISSUE THREAD

**Issue by tiandawen** [ssrpanel/SSRPanel#1571]
注册开启了邮件验证码，提示发送成功 后台也看到了投递成功，但是邮箱未收到邮件。用email.class文件写了个PHP邮件发送测试是正常的，邮箱可以收到邮件。就SS注册就无法收到邮件。之前的版本是可以正常接收到的。

**Comment by ssrpanel** [comment]
看wiki，执行sh update.sh，走队列发邮件
