### ISSUE TITLE
注册时可重复提交数据问题

### ISSUE THREAD

**Issue by bingotl** [ssrpanel/ssrpanel#158]
注册时快速双击可以重复提交数据，不会贴图，TG上联系过你了。

ID	用户名	端口	加密方式	已消耗	最后使用	有效期	状态	SS(R)	操作
101	13861818XXX@163.com	80XXX	rc4-md5	0B / 500MB	未使用	2017-12-04	未激活	启用	编辑  配置信息 流量监控  重置流量
100	13861818XXX@163.com	26XXX	rc4-md5	179.75MB / 50GB	2017-12-02 16:23:04	2018-01-02	未激活	启用	编辑  配置信息 流量监控

**Comment by bingotl** [comment]
日常催促完善限速功限客户端数量能。。。

**Comment by ssrpanel** [comment]
@bingotl 催促。。。日啊，我自己都没整明白那个限速的，容我问问ssrr作者

**Comment by ssrpanel** [comment]
@bingotl 已修正，git pull 一下代码
