### ISSUE TITLE
再次提交错误

### ISSUE THREAD

**Issue by WTFTWTM** [ssrpanel/SSRPanel#1582]
在您修复了composer带来的一系列错误之后，我回滚并进行了新的尝试，使用update.sh进行强制升级后，composer正常安装完毕，但网站进入500错误，sql文件夹中并未发现您更新了新的数据库，稍等我会将日志上传上来
以下是queue.log中的内容
> 
In ProviderRepository.php line 208:
                                                                    
  Class 'Tymon\JWTAuth\Providers\LaravelServiceProvider' not found  
                                                                    

以下是错误报告：
[https://api.aliserver.net/laravel-2019-08-05.log](url)
感谢您的辛勤开发

**Comment by ssrpanel** [comment]
php composer.phar install

**Comment by WTFTWTM** [comment]
发此Issue前已尝试，无效

**Comment by WTFTWTM** [comment]
> php composer.phar install
发此Issue前已尝试，无效

**Comment by WTFTWTM** [comment]
> php composer.phar install
![image](https://user-images.githubusercontent.com/34577787/62469583-21832e00-b7cb-11e9-90cb-a9e700f6cd6f.png)

**Comment by edrun** [comment]
> 在您修复了composer带来的一系列错误之后，我回滚并进行了新的尝试，使用update.sh进行强制升级后，composer正常安装完毕，但网站进入500错误，sql文件夹中并未发现您更新了新的数据库，稍等我会将日志上传上来
> 以下是queue.log中的内容
> 
> > 
> 
> In ProviderRepository.php line 208:
> 
> Class 'Tymon\JWTAuth\Providers\LaravelServiceProvider' not found
> 
> 以下是错误报告：
> [https://api.aliserver.net/laravel-2019-08-05.log](url)
> 感谢您的辛勤开发

建议先屏蔽掉

**Comment by WTFTWTM** [comment]
> > 在您修复了composer带来的一系列错误之后，我回滚并进行了新的尝试，使用update.sh进行强制升级后，composer正常安装完毕，但网站进入500错误，sql文件夹中并未发现您更新了新的数据库，稍等我会将日志上传上来
> > 以下是queue.log中的内容
> > > 
> > 
> > 
> > In ProviderRepository.php line 208:
> > Class 'Tymon\JWTAuth\Providers\LaravelServiceProvider' not found
> > 以下是错误报告：
> > [https://api.aliserver.net/laravel-2019-08-05.log](url)
> > 感谢您的辛勤开发
> 
> 建议先屏蔽掉

没办法屏蔽啊，网站是直接是500错误的

**Comment by chasenn** [comment]
楼主解决了嘛，同样错误

**Comment by WeAnyLink** [comment]
同样500错误，尝试和重置了很多次，都不行
