### ISSUE TITLE
重新安装以后 通过 php composer.phar install 安装的错误

### ISSUE THREAD

**Issue by nonewind** [ssrpanel/SSRPanel#1583]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package youzan/open-sdk ^1.0 exists as youzan/open-sdk[2.0.0, 2.0.1, 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.14, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, dev-bifrost, dev-carmen, dev-compatible, dev-hotfix/compatible_params_list_type, dev-hotfix/fix_ecommerce_path, dev-hotfix/standardized_header, dev-hotfix/update_readme, dev-master] but these are rejected by your constraint.

谢谢胖虎大哥

**Comment by xuelang113** [comment]
[root@izj6chzido76fpuz1b04bnz www.shidongli.rocks]# php composer.phar install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Killed


无法安装该依赖，报错。

**Comment by edrun** [comment]
> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - The requested package youzan/open-sdk ^1.0 exists as youzan/open-sdk[2.0.0, 2.0.1, 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.14, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, dev-bifrost, dev-carmen, dev-compatible, dev-hotfix/compatible_params_list_type, dev-hotfix/fix_ecommerce_path, dev-hotfix/standardized_header, dev-hotfix/update_readme, dev-master] but these are rejected by your constraint.
> 
> 谢谢胖虎大哥

兄台 我也遇到一样的错误 解决了吗？

**Comment by edrun** [comment]
改composer.json文件，youzan 改youzanyun 版本1改2

**Comment by bryant24** [comment]
> [root@izj6chzido76fpuz1b04bnz www.shidongli.rocks]# php composer.phar install
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Killed
> 
> 无法安装该依赖，报错。

内存不够，wiki中有如何增加swap
