### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by yi-shiyu** [ssrpanel/SSRPanel#1586]
试了好几次都500，开启debug报错"Class 'Tymon\JWTAuth\Providers\LaravelServiceProvider' not found"

**Comment by yi-shiyu** [comment]
![QQ截图20191106033436](https://user-images.githubusercontent.com/27227092/68239719-75114c00-0046-11ea-9317-a8954752e5f7.png)

**Comment by WeAnyLink** [comment]
朋友解决了吗？
我也遇到一样的情况
