### ISSUE TITLE
建议增加：1、用户自定义分组和节点自定义分组  2、用户浏览行为过滤

### ISSUE THREAD

**Issue by aazzpp678** [ssrpanel/ssrpanel#16]
1、用户和节点自定义分组  
使用场景：针对不同的用户组可以使用不同的节点组

2、用户浏览行为过滤
禁止用户BT下载、迅雷、某轮网站

**Comment by aazzpp678** [comment]
另外的话，分享链接推广也是极好的

**Comment by ssrpanel** [comment]
@aazzpp678 分享链接推广是要搞来返利的么？目前还是注册分享？我目前的设定是后台可以设置每个账号允许生成多少个邀请码，你的分享链接推广是指直接把带邀请码的链接分享给别人让别人直接注册的吗？

禁止用户BT下载、迅雷这种，我也头疼着呢，貌似得用glzjin的魔改版本SSR后端，它的PYTHON代码写的我看的有点晕。

节点分组我已经在改进了

**Comment by aazzpp678** [comment]
@ssrpanel 是的，分享链接主要是为了运营，目前的问题是邀请码不能设置返利，比如说分享出去的链接有人注册的话送多少流量或者多少积分这样

**Comment by ssrpanel** [comment]
@aazzpp678 好的，我捣鼓一下

**Comment by ssrpanel** [comment]
@aazzpp678 节点分组搞定了，那个邀请码如果要分享出去给多人注册的话，就跟我之前设定的初衷违背了，我是希望让一个用户邀请几个人来（后台可以设定），这个是控制数量的，而你那种则不可控制数量，一个码可以重复使用。你这种适合做二级分销，就是代理商

**Comment by ssrpanel** [comment]
@aazzpp678 要不然就换一种概念，就不是在邀请码上做文章，而是每个账号有自己的独立ID，然后分享链接给其他人注册，然后呢，注册的人还是得用邀请码（可以在系统里决定是否启用邀请注册），通过分享链进来的如果有消费则给这个邀请人现今返利或者送流量、积分等。

**Comment by aazzpp678** [comment]
@ssrpanel 非常好的想法。不过可能我没表达清楚，其实我本意就是这个，不管是邀请码还是一段链接，就是希望如果有人通过这个链接注册了，会给分享链接的人一定奖励

**Comment by aazzpp678** [comment]
@ssrpanel 就是跟目前国外的vultr，digitalOcean这些主机商类似。不过最好和邀请注册脱钩，即关闭了邀请注册，也能够分享链接

**Comment by ssrpanel** [comment]
@aazzpp678 好的，这个我排进开发计划里

**Comment by ssrpanel** [comment]
@aazzpp678 代码更新了，拉一下，注意数据库加字段
