### ISSUE TITLE
用户界面不随窗口大小自适应

### ISSUE THREAD

**Issue by DanielZhang17** [ssrpanel/ssrpanel#160]
有用户反馈说在PC端浏览器里打开界面时就出现节点信息显示不全的问题
不过如果窗口再小一点就会变成类似移动端的样子，可能这个参数还需要优化一下，算是一个小问题吧

**Comment by ssrpanel** [comment]
这个不算问题，，，这个metronic 前端框架的自动识别功能，没办法改了。。
