### ISSUE TITLE
单端口BUG

### ISSUE THREAD

**Issue by Joyace** [ssrpanel/ssrpanel#165]
后端这样设置
![screenshot_20171203-231835](https://user-images.githubusercontent.com/23218157/33526839-abaad46e-d881-11e7-9f6b-bb017b255c28.png)
前端这样设置
![-36f0df9fac663f69](https://user-images.githubusercontent.com/23218157/33526848-bf6d97a2-d881-11e7-84b0-4aea226c5705.png)
![-13ab8901da1189dc](https://user-images.githubusercontent.com/23218157/33526853-c8cf2194-d881-11e7-9520-1c7f0a403f4b.png)
订阅之后密码不是单端口的统一密码，而是用户密码，混淆方式也错了。使用其他方式导入之后密码正确了，但是混淆方式还是有问题。
![screenshot_20171203-233632](https://user-images.githubusercontent.com/23218157/33526921-fa334ab6-d882-11e7-9794-dfdff51c70d4.png)
![-421e8976d70fb303](https://user-images.githubusercontent.com/23218157/33526923-06f72fd8-d883-11e7-9ab5-10bc67bc2b92.jpg)

**Comment by ssrpanel** [comment]
@Joyace 那个单端口，破娃官网上，那个obfs只能用tls1.2

**Comment by ssrpanel** [comment]
@Joyace 所以还是老老实实用回tls1.2吧，别用http_simple了
