### ISSUE TITLE
按文档安装完成登陆后台出现FatalThrowableError

### ISSUE THREAD

**Issue by smarterq** [ssrpanel/ssrpanel#169]
按文档安装完成登陆后台出现如下页面
Parse error: syntax error, unexpected 'public' (T_PUBLIC), expecting end of file

![fireshot capture 002 - - http___me secxss cn_5223_admin](https://user-images.githubusercontent.com/16562294/33617543-f3f304fe-da1a-11e7-95e7-f65faa6ecc4e.jpg)

查看   /app/Http/Controllers/AdminController.php
发现在第1706行多了一个  “}” ， 在 “ // 操作用户余额”  前面
删除该括号问题解决

![snipaste_20171206_001732](https://user-images.githubusercontent.com/16562294/33617558-fcb64100-da1a-11e7-8803-52ba2c5ab4c6.jpg)

**Comment by ssrpanel** [comment]
已修正，git pull更新
