### ISSUE TITLE
对接问题

### ISSUE THREAD

**Issue by mmmwhy** [ssrpanel/ssrpanel#17]
[安装SSH2扩展库让PHP通过SSH连接操作远程服务器](http://www.xxorg.com/archives/3555)

感觉对接有些麻烦，是否设置好对接脚本。

网站通过ssh远程连接节点，运行预设好的脚本即可完成对接。

每次用户添加节点的时候，用户只需要添加vps的ssh进入网站，网站即可完成自动对接。

我对脚本和后端py比较熟悉，你还是别用go写了 /捂脸哭 

目前大部分的ssr后端都是py写的，重造轮子很累的。

**Comment by ssrpanel** [comment]
@mmmwhy 对接啊？不是很懂呀。。PYTHON你会呀？那请教下SSR3.4版本的那个我要怎么把单个用户限速加上，就是我在user表里加了两个限速字段，但是SSR那两个限速字段貌似只能全局配置（正台服务器），单用户咋办？求改一改

**Comment by iGeekQu** [comment]
feiyang 大佬能写个后端安装脚本那肯定是极好的🌚

**Comment by ssrpanel** [comment]
@iGeekQu 以后吧，先完善基础功能，打第一个版本包release一下先。先给有基础的人玩

**Comment by ssrpanel** [comment]
@mmmwhy 你这个libssh2我看了下，php自带的扩展没毛病，我明白你的意思，你是希望以主节点让添加子节点，所有数据由主节点主动去拉取子节点的，不过这个不适用于这个场景下。。因为ssr后端。。。

**Comment by mmmwhy** [comment]
你说的那个如果每个用户限制的代码我看了，是在[tcprelay.py](https://github.com/esdeathlove/shadowsocks/blob/manyuser/shadowsocks/tcprelay.py)这个文件
2114行，获得限制速度
```
                bandwidth = float(
                    self.multi_user_table[id]['node_speedlimit']) * 128
```
115行`isExceed`函数
```
    def isExceed(self):
        if self.max_speed > 0:
            cut_t = time.time()
            self.sum_len -= (cut_t - self.last_time) * self.max_speed
            if self.sum_len < 0:
                self.sum_len = 0
            self.last_time = cut_t
            return self.sum_len >= self.max_speed
```
定义了带宽超出之后该怎么办。
因为每个端口是单独生成一个`tcp_server`来服务的，所以限速之间不影响。

好了，你问我的问题我解决啦。

我本来想自己写前端的，但是我前端写的太丑，所以想用你的，你能不能写出那个自动对接呀。我可以写好脚本，只需要php执行就可以了。

**Comment by ssrpanel** [comment]
@mmmwhy 什么是自动对接，我很小白，不太懂python

**Comment by ssrpanel** [comment]
@mmmwhy 我国庆的时候又看了一遍代码，ssr python后端的这个限速写法限制的是整个节点的速度，我要的是基于数据库 user 表里加入限速字段，让ssr 去读取user表的时候把限速字段也读取出来

**Comment by 828768** [comment]
@ssrpanel @mmmwhy 大佬们，现在新建的用户默认都是204800M限速，这个在哪改？
