### ISSUE TITLE
返回管理页面，非法请求

### ISSUE THREAD

**Issue by xiaoanweiwu** [ssrpanel/ssrpanel#171]
<img width="506" alt="qq20171206-134754 2x" src="https://user-images.githubusercontent.com/28782855/33646777-53f32fde-da8c-11e7-9ddf-92327939bbba.png">
<img width="185" alt="qq20171206-134812 2x" src="https://user-images.githubusercontent.com/28782855/33646779-584c830a-da8c-11e7-9741-c39725b889b1.png">
<img width="488" alt="qq20171206-134832 2x" src="https://user-images.githubusercontent.com/28782855/33646782-5b522366-da8c-11e7-859a-16b4753ac09d.png">

**Comment by ssrpanel** [comment]
已修正 ，git pull一下
