### ISSUE TITLE
关于服务续费

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/SSRPanel#172]
希望添加功能，在余额充值的情况下，自动续费上一个套餐类型 这个功能；

还有就是一个日期bug，
发现实例为：用户提前手动续费； 然后他们反馈:"到期日是12月10日，我今天刚才充了一个月费（30天）套餐，现在到期日是1月5日了；"

 也就是说程序是在本日（6号）的基础上添加了30天； 
希望胖虎可以可【套餐】的这个机制的时间计算方法上修改为到期日+套餐时间；

**Comment by xiaoanweiwu** [comment]
是的，这个问题我也觉得难受

**Comment by ssrpanel** [comment]
再改了

**Comment by ssrpanel** [comment]
已改
