### ISSUE TITLE
管理界面--系统设置报错

### ISSUE THREAD

**Issue by 187264733** [ssrpanel/ssrpanel#173]
![default](https://user-images.githubusercontent.com/34293918/33647528-71d4a2fe-da90-11e7-96fe-960cf11bdce7.png)

**Comment by 187264733** [comment]
找到问题原因了，添加：
INSERT INTO `config` (`id`, `name`, `value`) VALUES (NULL, 'is_clear_log', '0');

**Comment by 1021435278** [comment]
@187264733 @ssrpanel 

https://github.com/ssrpanel/ssrpanel/issues/183  我的是报另外错, 请问可否有修复代码?
