### ISSUE TITLE
更新后的一些问题。

### ISSUE THREAD

**Issue by gitject** [ssrpanel/ssrpanel#176]
1.
![qq 20171207224358](https://user-images.githubusercontent.com/31369527/33720914-640e3098-dba0-11e7-8db3-448b8e2e31ee.png)

![qq 20171207224701](https://user-images.githubusercontent.com/31369527/33720971-8eeaf4c2-dba0-11e7-91a0-cf5e5cee0b62.png)
后台的是3条线，在个人中心显示4条，前2条是一样重复的。

2.
![qq 20171207225028](https://user-images.githubusercontent.com/31369527/33721350-bb3e8678-dba1-11e7-904e-d0d5f435249f.png)
临近到期这里和更新前显示的不一样，是改规则了？到期前多少天是临近到期？

3.
问个问题，那个用户到期提醒的检测是一天检测统一发一次？
是在几点检测执行？，哪里修改。

**Comment by ZBrettonYe** [comment]
1. 应该是数据库不干净的原因吧，并不是更新导致的，毕竟更新没有动这方面的东西；
