### ISSUE TITLE
自动重置流量问题

### ISSUE THREAD

**Issue by lm93129** [ssrpanel/ssrpanel#177]
新购买商品的用户，每天都会自动重置使用流量。
![tim 20171208094203](https://user-images.githubusercontent.com/22451712/33747125-11bd0e20-dbfc-11e7-9dd1-8ed53bbf15d2.png)
之前看到是有流量统计的，但是过了一天，就自动清零了。
我在后台修改了重置日期为0后，才会一直正常显示

**Comment by ssrpanel** [comment]
@lm93129 套餐是不是设置错误了

**Comment by lm93129** [comment]
套餐的日期是30天，是否要设置为31天？
