### ISSUE TITLE
现在通知采用邮件方式，可以提供SERVER酱通过微信推送管理员消息！

### ISSUE THREAD

**Issue by q815362636** [ssrpanel/SSRPanel#178]
1.现在服务器宕机用户激活等通知都是采用邮件方式，可以提供SERVER酱通过微信推送管理员消息！
Server酱地址：http://sc.ftqq.com
邮件可能并非实时并且邮箱关注度不高，系统可以加上微信同时提醒！

2.目前充值成功也没有邮件提醒，用户充值并非实时到账，还需要管理员后台操作，充值成功后也可以同时提醒用户充值成功，如果用户个人资料可以设置Server酱的SCKEY那也给用户发送微信通知

3.工单系统，用户提交工单时同时提醒管理员即使处理，管理员回复后提示用户已经回复通知方法同时采用邮件+微信！
以上都是通知消息相关，可选择两种同时推送，或只选择一种方式推送!

4.还有系统更新的问题，希望做成线上更新，不用每次git pull，再更新数据库

5.现在服务端端口是随机分配的，希望做到管理员在后台可以修改用户端口，比如指定某用户端口为8080用于测试免流

**Comment by ssrpanel** [comment]
好的，我加上

**Comment by ssrpanel** [comment]
已加入该功能，未提git
