### ISSUE TITLE
问题 - 胖虎请解决

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#179]
@ssrpanel 

日志按照提示操作后,生成的日志名称是ssserverlogsssver.log这种, 肯定日志分析无效,请检查并更新下安装指南, 日志分析还是需要的,可以看到某些人究竟浏览了那些网站,敏感网站可以想办法屏蔽掉.

另外邮件不建议做到默认封闭,逗逼的脚本可以开放,然后每个人针对性设置.如果一定要默认选择一个, PT/BT禁止掉是必须要的.

![a](https://user-images.githubusercontent.com/32491066/33759998-408425c0-dc3f-11e7-9c5c-3fefa3287238.png)
![b](https://user-images.githubusercontent.com/32491066/33759999-40b3beac-dc3f-11e7-8155-1ebcc2fae5c9.png)

**Comment by ZBrettonYe** [comment]
这个功能，wiki里早就加入在开发列表了
