### ISSUE TITLE
用户/用户群组,节点/节点群组/ 账号等级等级联动修改,方便管理.

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/SSRPanel#180]
这样可以直观的看到有多少个群组, 以及每个群主中里面有哪些用户,且可以一次性设置群组中流量限制等,方便管理.用户也可以很轻松的移动到其它群组中.

因为目前用户/用户群组,节点/节点群组/ 账号等级很分散杂乱, 希望可以做到联动就可以了,避免因为增加/删除群组和对应账户需要这几个步骤全部按照顺序走完才可以 几个账号没关系, 账号多的时候就很头疼且无法管理.

**Comment by 1021435278** [comment]
另外目前的群组等级有点问题, 如果等级1是默认等级的话,比如我是等级9的就可以看到1-9等级,也能看到等级8. 等级8的就可以看到1-8等级,也能看到等级8以下所有群组节点. 

可是实际上只想让等级9看到9和1,8的只能看到8和1, 7只能看到7和1 来限制组别只能看到该等级而不能看不到其它等级.

**Comment by ssrpanel** [comment]
@1021435278 我想你要要的不是分组，而是标签

**Comment by ssrpanel** [comment]
节点分组是为了给节点划分等级

**Comment by 1021435278** [comment]
我要的不是标签, 标签也算是方便管理,能有尽量有.

我要的是基于下列场景:

某些付费用户需要单独稳定的专有节点, 针对此情况就需要建立个完善的用户/用户群组的管理系统, 用户可以是单独用户,也可以被划入某个自定义群组. 用户可以属于多个群组, 也可以单群组,甚至不加入群组仅仅作为用户存在(可理解为单独默认群组,参考目前的倔强青铜)

用户可以被管理员手动移动或者指定的套餐产品付费后自动划入对应的群组.
对应的用户和用户群组就需要在管理中心存在菜单以便管理员方便观看, 检查归属群组以及移动到其他群组等.


节点/节点群组和用户/用户群组之间的归属关系:

节点可以为单独群组或者属于多个节点群组, 也可以单节点,甚至不加入节点群组仅仅作为单独节点存在.

节点/节点群组可以被管理员手动移动或者指定的套餐产品付费后自动划入对应的用户/用户群组中. 这样某用户/用户群组只能看到他们专有的节点/节点群组, 无法看到其它用户/群组的节点信息.

这样可以完善的隔离不同用户/用户群组之间的节点信息,避免某节点信息被攻击后影响到其它节点以及对应的用户/群组使用,比较适合大规模部署, 尤其是商用部署, 因为专有的共享专线不会有太多外人知道节点信息,就算ddos被攻击也很快就知道被攻击以及很快的查明某个用户账号有问题,然后封禁不退费处理.


其它可以改善地方:

最后单一个用户/用户群组被删除后, 所有的用户/用户群组要不直接归纳到默认的倔强青铜,要不就悬空看不到任何节点/节点群组信息, 除非管理员手动指定任何新的节点/节点群组.

目前的节点/节点群组和用户/账号等级管理太复杂,且操作性差, 具体表现在:

1. 高等级账号等级可以随意看到低等级的用户节点信息, 这样无法做到节点隔离.
2. 目前系统中账号等级修改极其不便. 举例说明如果你需要删除或者更改某个账号等级,你需要彻底把此等级下用户移走,然后再改回来才可以, 不太人性化操作, 建议用户/用户群组, 节点/节点群组和账号等级可以联动即可.

可以简单的理解把目前的账号等级取消掉关联制度, 所有账号等级都是平等,唯一的,除了默认的青铜.  因为这个不是打怪升级游戏应用,而是个用户/节点管理应用.
