### ISSUE TITLE
加入流量统计代码

### ISSUE THREAD

**Issue by lm93129** [ssrpanel/SSRPanel#181]
加入类似CNZZ或者Google Analytics这种流量分析的代码添加的地方

谷歌的流量分析代码帮助文档
https://support.google.com/analytics/topic/1008079?visit_id=1-636483380283277765-440739297&rd=1

**Comment by 1021435278** [comment]
这个需要, 后台加个输入跟踪代码的地方就可以了.  
建议GA, 对CNZZ/百度等还是太危险了.

**Comment by ssrpanel** [comment]
@lm93129 好滴，我这我优先做

**Comment by 1021435278** [comment]
@ssrpanel  好了通知下好更新.

**Comment by 1021435278** [comment]
@ssrpanel  请问这个已经搞好了吗?

**Comment by ssrpanel** [comment]
还是不做了，直接改footer.php 自己添加
