### ISSUE TITLE
垃圾开发者吃枣药丸

### ISSUE THREAD

**Issue by pipilupipixia** [ssrpanel/ssrpanel#182]
我辛辛苦苦给你做功能,你merge后全他妈把代码删了(详情可见 [这个commit](https://github.com/ssrpanel/ssrpanel/commit/d791ee0e666ce37538631ba1edc44a14ef97e43f) 可以看到 整个PaymentController全部删掉了.)
What the hell are you thinking?

**Comment by 1021435278** [comment]
和气生财啊, 每个开发者都有自己的套路,思路.
你们商量协调下,我的建议是你应该迁就胖虎, 因为你是想赚钱的那个....

**Comment by pipilupipixia** [comment]
...... @1021435278 我不是赚钱的哪个..接口卖出去几个跟我半毛钱关系没有..我纯粹是喵姐找来的开发...

**Comment by pipilupipixia** [comment]
并且..迁就不迁就是一回事儿..我也没有逼他用我的方法...

**Comment by pipilupipixia** [comment]
这人的水平..我不想说什么..各位自用就用吧,商用就算了...(当然这个对于只会用"一键包"的小白是挺友好的)

**Comment by 1021435278** [comment]
@pipilupipixia  

我觉得胖虎还是很能接受提出整改要求的, 从一开始我提交了不少issue基本都完成了,一个好的作品是需要点时间的. 胖虎的文档注释还是很清晰的,不妨按照他的思路对应重新提交就可以了.

很明显他的系统相对其它市面上的系统更清晰简单,界面也美观, 跟下来很多人就会用他的.

目前他的完全可以商用了, 我看了下,只要他把我提的https://github.com/ssrpanel/ssrpanel/issues/180 这个目前用户/用户群组,节点/节点群组/ 账号等级联动解决掉就很完美,方便管理.

再增加个支付通道,按照我给他的建议用Paypal 以及Stripe的话基本上就可以商用, 同时Paypal和 Stripe都支持信用卡,基本上撇开了难缠的用户,挺好的.

国内的支付通道我觉得迟早都会有问题,建议你们也增加对应的PayPal / Stripe接口.

**Comment by ssrpanel** [comment]
@pipilupipixia 你以为你提了PR，就可以肆无忌惮说我写的代码垃圾是吗？我就不上你黛米云，你愿意改随便你改

**Comment by pipilupipixia** [comment]
呵呵

**Comment by pipilupipixia** [comment]
这也是国内PHP社区的通病🌚

**Comment by ZBrettonYe** [comment]
@pipilupipixia 自己fork一下代码，然后给鸣谢一下胖虎之后，自己开发不就好了？ 反正Github开源的，这也不难吧

**Comment by pipilupipixia** [comment]
@ZBrettonYe  我从头开发呢.开源的东西不准备做了,正在做全功能的whmcs插件.

**Comment by pipilupipixia** [comment]
为什么要fork...
