### ISSUE TITLE
UnexpectedValueException 

### ISSUE THREAD

**Issue by xfhack** [ssrpanel/SSRPanel#186]
之前一直正常，没有做过任何操作，管理员无法新增账号，用户新注册，点击提交之后报错，跪求各位大神帮忙。

![qq 20171214220102](https://user-images.githubusercontent.com/22985419/33995949-84229f02-e11a-11e7-9973-81f219ab8b82.png)

**Comment by 187264733** [comment]
chmod 777  项目所在目录

**Comment by ssrpanel** [comment]
今天更新的吧，
git pull
php composer.phar install
导入 sql/update/20171210.sql
