### ISSUE TITLE
新建服务器，导入原先的user.sql，使用正常，但是注册新用户的ID不是按照顺序递增，而是一个非常大的数字，造成下一个注册用户失败，系统报错。

### ISSUE THREAD

**Issue by xfhack** [ssrpanel/SSRPanel#187]
新建服务器，导入原先的user.sql，使用正常，但是注册新用户的ID不是按照顺序递增，而是一个非常大的数字，造成下一个注册用户失败，系统报错，跪求大神解决。

![qq 20171214220931](https://user-images.githubusercontent.com/22985419/33996435-22679d60-e11c-11e7-8512-ded52fe406bf.png)

**Comment by ssrpanel** [comment]
@xfhack 无法重现，手动到数据库里改值吧。
