### ISSUE TITLE
单端口模式,使用订阅地址获取的密码为用户密码

### ISSUE THREAD

**Issue by cdlaimin** [ssrpanel/SSRPanel#188]
前端已配置单端口模式,统一验证密码已填写,在首页的节点配置信息中已看到统一密码并是正确的

后端开启强制使用443/80端口,并已经按照wiki填写

使用订阅地址更新后,密码获取为用户个人资料中的ssr密码
将获取到的用户密码修改为统一验证密码可以正确翻墙

**Comment by ssrpanel** [comment]
fixed
