### ISSUE TITLE
自定义用户/用户组, 自定义节点/节点组.

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/SSRPanel#189]
@ssrpanel  我关闭了之前issue, 这里重新组织语言解释下一个理想的用户/用户组, 节点/节点组应用场景.

假设我是个商用公开或者小圈子分享的网站,一些新用户过来注册,但开始他们不想付费,需要提供免费的节点给他们试用几天, 正常后转为付费用户.

补充说明，其实很简单。

用户必须属于某默认或自定义用户组。

节点必须属于某默认或自定义组。 通过节点组绑定到某个用户组形式赋予某用户组中所有用户能拿到该节点组内所有节点信息。

 这样不同用户组看不到其它用户组的节点信息，实现节点隔离，避免节点被墙或者受到攻击影响网站所有用户。

当节点被墙时管理员删除掉，重新创立个节点并加入到原始节点组中，原来用户就可以看到新节点信息，整站用户不受影响。

用户可以被管理员手动移动到任何用户组中，如果有必要甚至可以属于多个用户组，可以看到对应各用户组下绑定节点组下所有节点信息。

用户注册为网站会员时候，根据网站管理员喜好，要不需要手动加入到某个用户组(留空待定义)。要不直接自动加入到默认用户组，看到默认用户组绑定下免费节点从而可以测试。

也可以根据管理员设定，比如每30个人一个用户组，第31-60个自动加入另外一个用户组方法，以此类类推实现节点隔离。

以上可以把管理员基本从繁琐的管理工作中解脱出来，也避开了最讨厌的节点被攻击和被墙之后的手忙脚乱。

**务必删除掉目前系统中默认的账号等级,因为在ssrpanel这样一个系统中, 账号等级没有任何意义,不是打怪升级. 通过用户归属某个用户组,然后节点属于节点组，把节点组赋予某节点组方式来大规模简化管理操作难度.**

某些节点因为被攻击/墙之后,删除掉然后通过简单的重新创立新节点,加入到原来节点组,用户很容易在他们用户中心拿到新的节点信息,有时候一个公告或者邮件通知即可.

**- 强烈要求在管理后台中增加个导出用户/或者用户组中用户所有邮件地址的功能,这样发通知邮件就很容易.目前我是进数据库导出user表为excel格式,然后用Foxmail | Yomail群发单显来实现邮件群发通知的,参见下图:**

**或者参考wordpress后台增加个smtp插件,连接邮件服务器直接群发所有站内用户邮件即可.(和wordpress一样启用smtp后可以忽略掉mail.php来配置)**

![a](https://user-images.githubusercontent.com/32491066/34058903-a32a5982-e217-11e7-8155-b7ac0e70f658.png)

------------------------------------------------------------------------------------------------------------

我用Vultr是比较熟悉这个系统, 他们的镜像和自动备份挺不错. 目前我创立个节点基准镜像, 增加节点或者更换节点时候,只需创立instance简单的选择导入节点基准镜像,然后简单的修改 usermysql.json中node id值就可以, 通常一个小时内我可以创立最少20个节点.

自动备份可以用在数据库服务器上.

**Comment by 1021435278** [comment]
补充说明，其实很简单。

用户必须属于某用户组。

节点必须属于某节点组。 通过节点组绑定到某个用户组形式赋予某用户组中所有用户能拿到该节点组内所有节点信息。

 这样不同用户组看不到其它用户组的节点信息，实现节点隔离，避免节点被墙或者受到攻击影响网站所有用户。

当节点被墙时管理员删除掉，重新创立个节点并加入到原始节点组中，原来用户就可以看到新节点信息，整站用户不受影响。

用户可以被管理员手动移动到任何用户组中，如果有必要甚至可以属于多个用户组，可以看到对应各用户组下绑定节点组下所有节点信息。

用户注册为网站会员时候，根据网站管理员喜好，要不需要手动加入到某个用户组。要不直接自动加入到默认用户组，看到默认用户组绑定下免费节点从而可以测试。

也可以根据管理员设定，比如每30个人一个用户组，第31-60个自动加入另外一个用户组方法，以此类类推实现节点隔离。

以上可以把管理员基本从繁琐的管理工作中解脱出来，也避开了最讨厌的节点被攻击和被墙之后的手忙脚乱。

按照此用户及节点规划管理，几千人机场估计一到两个管理员就可以管理过来。

人多了就可以自己拿机器开小鸡，利润更高，更有自主性。

**Comment by 1021435278** [comment]
务必删除掉目前系统中默认的账号等级,因为在ssrpanel这样一个系统中, 账号等级没有任何意义,不是打怪升级. 通过用户归属某个用户组,然后节点属于节点组，把节点组赋予某节点组方式来大规模简化管理操作难度.

**Comment by 1021435278** [comment]
刚看了https://github.com/ssrpanel/SSRPanel/issues/100 这个issue,发现这位朋友已经提过了我的要求，只是比较模糊，我上面应该很清楚的阐述了具体要求。

这里还有个要考虑的是，流量是赋予用户组，还是单独赋予用户来实现。主要看管理便利性， 希望提#100的朋友一起加入讨论。

此外个人觉得用户组的设置应该和系统默认的设置区别开-仅仅指流量限制等方面，系统默认的设置对默认用户起作用。用户组的就使用用户组的单独群组策略，不受系统默认的设置限制。

**Comment by 1021435278** [comment]
胖虎请问有计划参考我的建议来修改用户/用户组, 节点/节点组关系吗?

**Comment by 1021435278** [comment]
@ssrpanel  我简单的画了个草图,应该很容易理解.

![a](https://user-images.githubusercontent.com/32491066/34361942-db353cd0-eaa9-11e7-98d4-bd599d55b0b0.jpg)

**Comment by ssrpanel** [comment]
@1021435278 在做了。图不错。思路一下就开了

**Comment by ssrpanel** [comment]
已加，用户和节点必须处于同一个标签下，用户才可见本次更新：1.git pull2.修改config/database.php 下 mysql 配置中的strict 为 falst（不使用mysql的严格模式）3.导入db/update下最后一个sql文件到数据库4.truncate table user_subscribe 、 truncate table user_subscribe_log5.进后台给节点设置标签、给每个用户分配标签
--
