### ISSUE TITLE
免流

### ISSUE THREAD

**Issue by chenyanmo** [ssrpanel/ssrpanel#19]
能否加入移动网络免流功能呢？

**Comment by ssrpanel** [comment]
@chenyanmo 那个我都没玩过。。。求教

**Comment by aazzpp678** [comment]
@chenyanmo 自己改下混淆的参数即可

**Comment by ssrpanel** [comment]
@aazzpp678 求教程，我可以先玩下，然后如以你的署名写个WIKI ，哈哈

**Comment by chenyanmo** [comment]
@aazzpp678 混淆的参数改了木有用， 求详细教程，然后会以你的署名

**Comment by aazzpp678** [comment]
@chenyanmo  http://blog.lanyus.com/archives/248.html  大同小异，原理一样，就是利用移动搞的活动，用http_simple模拟假流量。这个要根据地方，因为不同的地方活动不一样

**Comment by chenyanmo** [comment]
@aazzpp678 感谢链接， 所以ssr免流已经无效了吗？

**Comment by aazzpp678** [comment]
@chenyanmo 照抄应该是没用了，你可以看看你们那边运营商有什么网站上网不算流量，然后照着画瓢即可

**Comment by ssrpanel** [comment]
@chenyanmo @aazzpp678 移动137 138端口在SSR后端已经被屏蔽了，那招无效，而且可以检测出异常大流量。只能去完那种咪咕音乐这种免流app

**Comment by chenyanmo** [comment]
@ssrpanel 嗯 还没找到免流应用

**Comment by chenyanmo** [comment]
@ssrpanel 咪咕音乐没说免流呀

**Comment by aazzpp678** [comment]
地方特色，有的地方是免流的

**Comment by max2max** [comment]
这个，我觉得不要太高调的好，会有风险的

**Comment by ssrpanel** [comment]
@max2max 福建这已经会识别了，以前破娃就是把这个屏蔽掉因为风险较高
