### ISSUE TITLE
用户删除及管理中心的节点推荐.

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/SSRPanel#190]
@ssrpanel  

现在用户可以删除了吗?  有些未激活/重复注册用户想在数据库中直接删除掉, 问题是删除了有什么影响? 可否简单描述下,以方便提出对应措施方案? 如果没问题,建议在用户管理中增加删除按键.
- 强迫症没办法.
------------------------------------------------------------------------

管理中心推荐的IDC看起来都不错,不过可以完善下,因为大部分人愿意寻找按时付费的主机, 按月付费的还是存在被墙/被攻击的风险导致成本高企.
https://github.com/ssrpanel/ssrpanel/wiki/VPS%E6%8E%A8%E8%8D%90&%E8%B4%AD%E4%B9%B0%E7%BB%8F%E9%AA%8C

如果可以请参考:https://github.com/ssrpanel/SSRPanel/issues/189 最后面高级开发需要,如果linod | 搬瓦工 | Hostdare都有这种api的话,可否直接做进ssrpanel系统,你也可以直接做个agent或者reseller,好过aff这种方式.

**Comment by ssrpanel** [comment]
@1021435278 agent reseller是什么鬼？

**Comment by 1021435278** [comment]
就是你做那几个idc代理，我们从你那里买主机，用户数量大的话每个月几万很轻松。最好的结果是自己做idc卖小鸡给米的追随者。

**Comment by 1021435278** [comment]
用户现在可以直接删除了吗？没影响了吧？
