### ISSUE TITLE
新手求助

### ISSUE THREAD

**Issue by akudamatata** [ssrpanel/SSRPanel#191]
用宝塔或者脚本一键安装的LNMP 开启curl gd openssl 各种失败，linux玩的不转，求一个教程！ @ssrpanel 感激不尽

**Comment by ZBrettonYe** [comment]
本项目不建议小白使用。这个项目使用需要一定的编程基础

**Comment by akudamatata** [comment]
我有编程基础和网络工程技术，我只是linux玩的不转。

**Comment by akudamatata** [comment]
我没看见安装过程哪儿需要用编程基础了
