### ISSUE TITLE
能不能将充值码直接充值到余额

### ISSUE THREAD

**Issue by ilovebamboo** [ssrpanel/SSRPanel#193]

**Comment by ilovebamboo** [comment]
![qq20171220-083327](https://user-images.githubusercontent.com/6214084/34185469-7aa217ec-e560-11e7-95d5-6b9e78e2c8ce.png)

**Comment by ilovebamboo** [comment]
能不能把充值的地方 可以用卡券充值 这个怎么没有 搞余额只能管理员手动填写。太没效率了

**Comment by ssrpanel** [comment]
@ilovebamboo 这不是我的代码，你哪里搞的代码哪里去找

**Comment by ilovebamboo** [comment]
这个是卡券充值啊 你自己做的

**Comment by a5234338** [comment]
我怎么没这个悬浮页面
