### ISSUE TITLE
使用支付码数据库失败

### ISSUE THREAD

**Issue by ilovebamboo** [ssrpanel/SSRPanel#194]
![qq20171220-144944](https://user-images.githubusercontent.com/6214084/34194713-08b63764-e595-11e7-9148-7057436041ea.png)

**Comment by ssrpanel** [comment]
@ilovebamboo 订单接口已变。删除order表重新导入

**Comment by ilovebamboo** [comment]
好的，谢谢。

**Comment by 1021435278** [comment]
@ilovebamboo  你这个支付接口是什么?
