### ISSUE TITLE
能不能考虑一下 余额可以用卡券充值

### ISSUE THREAD

**Issue by ilovebamboo** [ssrpanel/SSRPanel#197]
能不能考虑一下 余额可以用卡券充值。 手工转支付宝微信没效率。不然卡券功能失去意义。

**Comment by ilovebamboo** [comment]
非常感谢

**Comment by waimaoyun** [comment]
楼上的兄弟,方便PM我你的qq嘛?

**Comment by ilovebamboo** [comment]
![qq20171223-122645](https://user-images.githubusercontent.com/6214084/34316895-90c9809a-e7dc-11e7-9177-360368a248cf.png)
![qq20171223-122509](https://user-images.githubusercontent.com/6214084/34316896-9100a192-e7dc-11e7-879c-667adf51e96e.png)

**Comment by ssrpanel** [comment]
@ilovebamboo 已加了
