### ISSUE TITLE
请问为什么新版里面,用户登陆首页不显示SSR连接信息了?

### ISSUE THREAD

**Issue by ewjo** [ssrpanel/SSRPanel#198]
请问为什么新版里面,用户登陆首页不显示SSR连接信息了?

**Comment by ssrpanel** [comment]
不是有吗 ？截个图？

**Comment by ewjo** [comment]
https://www.ewjo.org/wp-content/uploads/2017/12/111.jpg
请看图

**Comment by ssrpanel** [comment]
节点那不是可以点击小飞机图标显示吗？？？

**Comment by ewjo** [comment]
那里显示的是配置节点时候设置的连接信息...而不是账户注册后自动生成的连接信息. 每个人都是不一样的啊

**Comment by ssrpanel** [comment]
@ewjo 必须跟着节点信息走，不然SSR会连不上的。
