### ISSUE TITLE
管理方面邮箱功能强化

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/SSRPanel#199]
25. 发布或者回复工单则自动发邮件提醒；这个功能还可以再加一条；

邮箱发生失败后，设一个按钮 允许管理员在不同时间再试尝试发送；
一键导出用户邮箱；或者管理员可以给用户邮箱发邮件 来进行通知网站最近的变动；

**Comment by 1021435278** [comment]
这个提议挺好的, 我早就提出了.

**Comment by ssrpanel** [comment]
就是手动发邮件是吗？

**Comment by ZBrettonYe** [comment]
@ssrpanel 是的，想群发所有用户 关于活动之类的东西，毕竟不是所有人都会看官网，要是官网管理员功能加入这个应该会很方便，这样就能安利用户了；

**Comment by ssrpanel** [comment]
@ZBrettonYe 我考虑下。

**Comment by ssrpanel** [comment]
@ZBrettonYe 
还有什么地方需要发邮件的额，或者自动发邮件提醒用户的，都说说

**Comment by 828768** [comment]
> 还有什么地方需要发邮件的额，或者自动发邮件提醒用户的，都说说

@ssrpanel 
1、新发或者修改文章、公告可选择是否触发邮件通知用户，如果选是则主动将公告内容或者地址邮件给用户

**Comment by 828768** [comment]
邮件通知这个功能做了个图，胖虎看你的了@ssrpanel
![20180312151222](https://user-images.githubusercontent.com/6386202/37270005-fc2d0316-2607-11e8-8cd3-6bee20b1557b.png)

**Comment by ssrpanel** [comment]
@ZBrettonYe 工单回复邮件的我加上了

@828768 邮件营销的话我再研究看看

**Comment by yeehomlee** [comment]
补充一下，需要群发邮件的地方可能还有：

1、域名被ban，面板更换域名，通知用户从新地址访问。
2、节点更换服务器，提醒用户更新IP地址。
3、套餐/流量包有较大改动或优惠，提醒用户关注。

**Comment by izhangxm** [comment]
### 邮件群发（还在开发）
![image](https://user-images.githubusercontent.com/16874796/40884674-f44ba0ce-674a-11e8-9377-c4749611dc21.png)

### 首页教程
![image](https://user-images.githubusercontent.com/16874796/40884682-0bdc897e-674b-11e8-8076-425d9ba67716.png)

### 账户信息
![image](https://user-images.githubusercontent.com/16874796/40884694-4425c796-674b-11e8-8c52-af7a549be5ce.png)

### 文章编辑可插入视频代码
![image](https://user-images.githubusercontent.com/16874796/40884699-5b9f42f8-674b-11e8-9510-bf38e97c7f78.png)

### 邀请码优化
![image](https://user-images.githubusercontent.com/16874796/40884706-70582ee4-674b-11e8-9724-656f2cc6ec5e.png)

### 优化推广
![image](https://user-images.githubusercontent.com/16874796/40884716-9e2980c0-674b-11e8-8fce-45377316f8c8.png)

### 加入前端页面
![image](https://user-images.githubusercontent.com/16874796/40884725-c8b0bd0e-674b-11e8-8ccc-1e15fede95c9.png)

### 推介计划
![image](https://user-images.githubusercontent.com/16874796/40884732-d85939e8-674b-11e8-90a5-b16762f6b9f4.png)

由于前端页面完全去除了胖虎的版权信息，所以暂时不能提交到作者的分支，感兴趣的朋友可以到我的主页克隆并下载相关项目

**Comment by yeehomlee** [comment]
我对「推广优化」这个比较感兴趣，通过cookies及邀请码追踪。现有的机制几乎没法统计到。

不知道涉及到的代码多不多？

具体是哪个项目呢？@izhangxm

**Comment by izhangxm** [comment]
@yeehomlee 我更改了后端代码，通过拦截器实时注入并更新cookie

**Comment by izhangxm** [comment]
![image](https://user-images.githubusercontent.com/16874796/40884863-2f22b6bc-674e-11e8-90ba-f767fbbe3e7b.png)
### 注册时再取出来
![image](https://user-images.githubusercontent.com/16874796/40884866-435c6bbe-674e-11e8-92b5-6fb60c982505.png)

**Comment by yeehomlee** [comment]
@izhangxm 感谢！再请问「邀请码优化」通过邀请码推广，这个是通过哪些代码？ 
在您的项目中没找到，谢谢。

**Comment by izhangxm** [comment]
@yeehomlee 邀请码优化可以在用户注册的位置看到
![image](https://user-images.githubusercontent.com/16874796/40894868-032c4b04-67df-11e8-8c7e-2c62466ace06.png)

### 优化：可以在这里看到自己的推广人
![image](https://user-images.githubusercontent.com/16874796/40894976-87fe532c-67df-11e8-92d5-89071849c0e3.png)

### 新功能：邮件群发功能开发完毕，采用Laravel队列实现，可以降低前端等待时间；存在的问题是邮件投递日志没做；欢迎给出意见
![image](https://user-images.githubusercontent.com/16874796/40895017-a9576c48-67df-11e8-8035-6cc637f03df9.png)

**Comment by yeehomlee** [comment]
非常感谢，已经用上了。

**Comment by ssrpanel** [comment]
@izhangxm 日哦，你二开了这么多好东西

**Comment by ssrpanel** [comment]
@izhangxm 你没有开源啊。。

**Comment by ssrpanel** [comment]
看到了。。。@izhangxm 有些功能我要抄过来，哈哈
