### ISSUE TITLE
配置完成后打开网站500错误

### ISSUE THREAD

**Issue by tensh1** [ssrpanel/ssrpanel#2]
打开了错误提示
![image](https://user-images.githubusercontent.com/30756616/28998799-99e1e278-7a66-11e7-92b7-4955410ea34f.png)

粗略看应该是限制了资源目录不能直接跳转? （雾）

**Comment by ssrpanel** [comment]
PHP 的配置问题，自行上网搜索解决方式。。open_basedir 。。。

**Comment by ssrpanel** [comment]
@tensh1 
vim /usr/local/nginx/conf/fastcgi.conf
找到 fastcgi_param PHP_ADMIN_VALUE "open_basedir=$document_root/:/tmp/:/proc/"; 这句
把它注释掉

**Comment by tensh1** [comment]
连了一天前后端终于通了 
不过教程里面在用php artisan key:generate之前好像要先复制一份.env文件 否则会出错找不到.env文件

**Comment by tensh1** [comment]
@ssrpanel  我觉得可以做一个注册的功能 每次都要自己加略显麻烦

**Comment by ssrpanel** [comment]
@tensh1 先完善后端用户管理，然后准备开个分支做有前端注册的和用户界面端的，最后再实现第三方支付，目前是这么计划的，哈哈哈哈哈，谢谢支持

**Comment by kur0mi** [comment]
说说我的情况吧，我也是500错误，不过我是因为 ssrpanel目录权限是root所以无法访问
chown -R www-data:www-data ssrpanel 解决

**Comment by DizzlyLee** [comment]
宝塔面板，没有找到 vim /usr/local/nginx/conf/fastcgi.conf 这个文件。
