### ISSUE TITLE
在线人数，服务器负载，实时流量这些是后端直接提供的吗？

### ISSUE THREAD

**Issue by hansansui** [ssrpanel/ssrpanel#20]
请教，这个版本的后端，可以返回哪些数据啊？

**Comment by ssrpanel** [comment]
@hansansui 对的，在线人数，服务器负载，都是SSR3.4版本自带的，会实时往数据库里写数据的。如果有更好用的SSR后端，请推荐下，或者别人改过的

**Comment by ssrpanel** [comment]
@iGeekQu roger that, i will 研究研究

**Comment by hansansui** [comment]
@ssrpanel 往哪个表的字段写的数据？也是只操作user一张表吗？

**Comment by ssrpanel** [comment]
@hansansui 是 `ss_node_info` 表我是看着ssr 3.4后端python 版本代码写的这套系统，有些业务功能是参照sspanel，有些参照魔改版。

**Comment by ssrpanel** [comment]
@iGeekQu 我比较下代码看看
