### ISSUE TITLE
SSRpanel在新增节点中能否添加中转功能？

### ISSUE THREAD

**Issue by cndanili** [ssrpanel/SSRPanel#205]
SSRpanel可见作者开发效率很高。

但是观察SSRpanel在新建节点时缺少将节点设置成中转的功能，并实现通过中转节点将流量转发至目标节点。

在实际使用过程中需使用到中转节点：

通过国内CN2机房连接韩国，日本等节点可以迷惑游戏服务器或者视频串流服务器观看本地视频的功能。

**Comment by ssrpanel** [comment]
@cndanili tg群里喊下我，中转我没玩过呢

**Comment by ssrpanel** [comment]
中转只有魔改后端+魔改面板才有，用魔改吧。我这个写不来，没空研究。。
