### ISSUE TITLE
继续提交issue，胖虎很勤奋啊

### ISSUE THREAD

**Issue by cheapssr** [ssrpanel/SSRPanel#207]
积分其实用处不大
直接签到给流量就行，不必多个兑换手续
这个，胖虎技术好，可是，审美和布局捉急，我一直在关注，这个界面其实没毛病，就是布局啥的，确实有点问题。对老司机来说，只要节点稳，好用，都能操作，对新手不太友好

因为说，啥用户都有，要把用户当作傻瓜，一切操作，尽量简洁

我画个布局的图，做好了提交你看看

**Comment by ssrpanel** [comment]
图呢

**Comment by cheapssr** [comment]
。。。。么有顾得上画图。。元旦。。。你懂的
