### ISSUE TITLE
增加删除用户功能

### ISSUE THREAD

**Issue by lm93129** [ssrpanel/SSRPanel#208]
比如有人恶意注册了一堆僵尸用户，这样就占用了大量的端口，可否加个定时任务，自动删除超过90天不使用的且已经过期的用户，或者增加批量手动删除功能，不然一个个去数据库删除很是麻烦....

**Comment by ssrpanel** [comment]
@lm93129 可以啊

**Comment by cndanili** [comment]
注册时候需要验证码就解决了，不过批量删除用户感觉挺不错的。

**Comment by 110560** [comment]
三个月不使用  账户余额为零 自动删除该用户  这样完全ojbk

**Comment by lijinlei521** [comment]
增加删除用户功能

**Comment by ssrpanel** [comment]
@lm93129 @cndanili @110560 @lijinlei521 其实我个人是没有这个需求的，我想你们这个需求应该转化成：自动禁用长期不登录（或者余额为0）的账号并发去邮件提醒，并且释放他们占用的端口

**Comment by 110560** [comment]
讲真， 这些人的账号留在数据库，永远不会用，我目前的做法是，修改账号用户名。  修改密码。 这样就可以给新的用户用，，，但是这样太累了。。。。

**Comment by ssrpanel** [comment]
@110560 已加入端口自动释放，需要用改进版本的SSRR，但是目前有个小BUG，如果端口被置为0，当端口再次被改为非0即便重新启用账号，账号也无法真的启用（因为SSRR一开始就把所有账号都载入到资源中），必须手动sh stop.sh 再 sh logrun.sh
