### ISSUE TITLE
流量套餐的建议

### ISSUE THREAD

**Issue by max2max** [ssrpanel/ssrpanel#21]
首先，感谢一下作者的辛苦付出。
我有个合租群，前端用的是魔改版。我这边有相当一部分群友，流量用得很少，所以我就开一个10G/年的套餐。但是这个套餐触发重置的条件是一年之后。期间流量如果用完了，服务突然中止，就需要用户手动购买新的套餐，这样比较影响使用体验。
我觉得ssrpanel，如果有流量用完自动重置的功能就好了。

**Comment by GeekQu** [comment]
这个问题换种方式来描述就是 **自动续订流量包** 咯。

**Comment by ssrpanel** [comment]
@max2max 魔改版很强大，glzjin大神还厉害，但是配置比较复杂。我这个要做的简单傻瓜化但是比sspanel强大比魔改弱鸡。
你的需求我也记录下来了，我会在配置里加一个开关，允许开启或者关闭流量自动重置，但是如 @GeekQu 所说，这会涉及到购买流量包的问题呢，不过从运营角度上来说也不过，让用户先充值到期自动续费。还好我已经加上了用户余额字段了。。。我先mark这个需求

**Comment by max2max** [comment]
谢过大佬
