### ISSUE TITLE
更新到12.28以后Shadowrocket订阅功能失效

### ISSUE THREAD

**Issue by stmail** [ssrpanel/SSRPanel#210]
已确认Shadowrocket正常使用，两台iPad（另一台不是我的）均安装最新版（截至今日）。
Windows以及Android客户端均能正常订阅获取节点信息（Windows是4.9，Android使用的是3.4.0.7）.
上述情况发生在12.20更新至12.28以后，不清楚哪儿出现bug

**Comment by ssrpanel** [comment]
估计是shadowrocket更新了规则，跟mac一样要强制订阅地址是https的

**Comment by stmail** [comment]
我现在就是在用https
