### ISSUE TITLE
手动重置节点流量

### ISSUE THREAD

**Issue by lm93129** [ssrpanel/SSRPanel#213]
由于节点没有设置重置日期，所以建议增加手动重置功能
因为VPS并不一定是每月1日购买的
![image](https://user-images.githubusercontent.com/22451712/34549034-ab3cb7fe-f140-11e7-9c93-f252f00b002a.png)
可以大概在这个位置，增加一个和用户重置流量一样的重置按钮

**Comment by ssrpanel** [comment]
那个节点流量是IDC分配给你的，节点里的那个设置只是用来看的
