### ISSUE TITLE
SSRpanel管理界面若干疑问

### ISSUE THREAD

**Issue by cndanili** [ssrpanel/SSRPanel#214]
1. 管理界面中菜单用户管理-用户列表，点击操作编辑用户资料，有“付费方式”项，注册用户默认值为“免费”，但是除了管理员手工更改之外，有没有其他方式更改“付费方式“的值？如果没有的话，建议通过商品挂钩的方式更改此项；”付费方式“的值个人觉得选项应该为”支付宝“、”微信“、”贝宝（PayPal）、转账“，建议将描述改为”订阅模式“，选项为”按量“、”包月“、”包季“、”包年“；但是”按量“和”包月“不冲突，如2个商品都购买，不知如何表示？
2.用户注册页面须使用邮箱注册，但是登录页面描述却为”用户名“，建议注册页面添加用户名选项，或将”用户名“描述改为”邮箱地址“或者”注册时输入的邮箱“或”注册邮箱“之类的名称。
3.购买商品无法改变用户等级（好像之前有人提过issue）。
4.套餐有效期设置成有效期**90天**，内含流量20G，用户购买商品后提示”每月X日自动重置流量“。我的理解是，在购买当天的90天有效期内每个月X日是重置成20G。那如果用户是1月31日购买的，那么2月份和4月份不知道如何判断的；如果是每个月都有20G的流量，那么套餐的内含流量应该是60G。不妨套餐流量设置成根据”订阅模式“对流量进行重置，比如包季用户，有效期90天，总共60G，90天内每30天重置用户流量为20G。
5.若套餐可以更改用户等级，用户混合购买，等级应该怎么算？
6.在面板节点配置界面单端口”开启“状态，模式为”严格模式“，协议若为auth_sha1_v4，混淆为tls1.2_ticket_auth，在后端的user-config.json配置相同协议和混淆并将additional port only改为true之后，实际后端是无法启动单一端口的，能否在界面上或者后端予以改善？

**Comment by ssrpanel** [comment]
首先感谢热情提问，答：
1.不加支付宝，微信，paypal半成品，实验性的，商业用请去买whmcs或者找人做改好的魔改。不花钱的东西能用就凑合着用吧，加了这些支付接口我也不会放出来的。
2.1中的那些问题，可以忽略，因为那些是我自用的，用来标记用户属性的
3.2不改
4.3我看着有空捣鼓下
5.4不解释，面板里已经很清楚说明了
6.5跟3一样我有空再捣鼓
7.单端口的肯定没认真看wiki，我既然能放出来，百分之百可以用，不能用是你配置错了
