### ISSUE TITLE
节点信息展示逻辑希望改进

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#215]
登录ssrpanel后，展示节点信息包含：节点名称，节点服务器信息，小飞机图标，qr图标和流量结算比例图标。

其中：
流量结算比例 - 这个图标点下显示，不如直接文字显示出结算比例
小飞机图标 - 点击后显示ssr及ss地址，还没复制完就退出了，对手机操作更是无能为例，能不能直接改成点击后复制ssr或者ss地址？
所有的信息对手机操作来说只有点击节点ip或者域名那里显示配置信息有用，其他的对于手机来收都无能为力啊，胖虎兄

**Comment by 110560** [comment]
小飞机弹出的问题说过了，，，倒不如直接用改成魔改的那种，点击链接直接调用ssrr软件，，就像你点击应用链接自动调用软件，，，，，

**Comment by ssrpanel** [comment]
好滴，我有空改进一下；你们对SSR链接有很强的需求吗？

**Comment by 828768** [comment]
> 好滴，我有空改进一下；你们对SSR链接有很强的需求吗？
@ssrpanel 其实没有，只是你提供了一个，觉着这至少不该这样用，现在的样子相当于没有。如果点击后能自动复制到粘贴板，那对于在手机上操作来说倒是有点用。

还有就是，现在后台的用户，活跃用户，当前在线三个点进去都是到用户列表，并没有筛选展示，这是bug么？还是本来就没做这些功能？

**Comment by a5234338** [comment]
我之前在群里也提过单击小飞机跳出ssr链接时间太短的问题，一群友还说练手速，醉了

**Comment by ZBrettonYe** [comment]
SSR 链接显示时间 这个东西 好像和浏览器有很大关系

**Comment by ssrpanel** [comment]
看着淫民群众的意见很大，所以我还是改了
