### ISSUE TITLE
购买商品到期时间bug

### ISSUE THREAD

**Issue by ller** [ssrpanel/SSRPanel#216]
假如账号1月2号到期  然后1月12号购买个产品有效期30天的，最终到期时间为2月2号。购买商品的有效期间从过期时间直接加的。。假如如果到期一个月后 如果去买个新的 30天服务。。那么 。账号还是到期的之前加了30天。而不是从购买时间开始加时间

**Comment by 110560** [comment]
这逻辑才对的呀，，，原来的不叠加商品有效期，现在可以叠加了，，，

**Comment by ller** [comment]
@110560 加入用户1月1号套餐过期 然后过了15天1月16日  重新买个套餐 有效期加30天。。那么现在套餐有效期是 1月1日 加30天 2月1日。。而不是2月16日。。中间少了。。半个月时间。。另外假如用户1月1日过期了 然后4月1日重新买了一个月加30天。。那么到期时间是1月1日加30天。。2月1日。。所以说不能用

**Comment by 110560** [comment]
这，，，懂了，，，你第一波没解释清楚

**Comment by ZBrettonYe** [comment]
这个BUG 我也遇到过； 死鱼用户忽然复活，上次续费是11月，买了个月费后 有效期变成12月；然后就来找我了

**Comment by 110560** [comment]
胖虎，，快来我也遇到了，我都是手动修改回来，，，，

**Comment by wangrong1994** [comment]
这个问题好解决啊，改下代码就行了

**Comment by 110560** [comment]
可是我们不会改呀。。。

**Comment by ller** [comment]
@wangrong1994 求修复方法

**Comment by ssrpanel** [comment]
@ller @110560 @wangrong1994 BUG已修正，git pull一下
