### ISSUE TITLE
怎么加不了TG群呢？

### ISSUE THREAD

**Issue by hackagony** [ssrpanel/SSRPanel#219]
怎么加不了tg群呢？还有怎么设置邮箱发送呢？我的配置好了qq邮箱发送总是没发送成功，能指导一下吗？开启了stmp功能了

**Comment by hackagony** [comment]
Failed to authenticate on SMTP server with username "53999592@qq.com" using 1 possible authenticators

**Comment by fengchenggf** [comment]
@hackagony 我用的阿里的，SSL，没问题

**Comment by ssrpanel** [comment]
@hackagony tg群可以啊
@fengchenggf qq邮箱可以的，要在后台开启smtp

**Comment by hackagony** [comment]
开启smtp了的，但就是发送不成功，能来个教程吗？ 是输入QQ密码还是授权码？

**Comment by fengchenggf** [comment]
@hackagony 应该是授权码

**Comment by chasenn** [comment]
TG群是多少
