### ISSUE TITLE
希望可以对接支付功能，支付宝当面付、zfbjk等

### ISSUE THREAD

**Issue by echoowall** [ssrpanel/SSRPanel#22]
希望可以对接支付功能，支付宝当面付、zfbjk等，谢谢。

**Comment by ssrpanel** [comment]
@echoowall 支付宝当面付的SDK地址有么，我都没找到呀。那种扫码的那种吗？
zfbjk是什么东东？我有准备加支付功能，最近在优化优惠券这个功能。

**Comment by cheapssr** [comment]
支付宝商家付款功能，可以对接吗？
https://docs.open.alipay.com
以后会加上中转功能吗？

**Comment by ssrpanel** [comment]
@cheapssr 中转我都没玩过，请问怎么玩，或者有文章教程什么的，求贴个地址。我先玩看看才写的出代码。

**Comment by ssrpanel** [comment]
@cheapssr 原来昨天打赏的是你，哈哈谢谢了

**Comment by cheapssr** [comment]
不客气，我希望你能保持热情做下去，一直更新。
对作者要支持的。
现在功能最全面和强大的就是V3，，功能确实很牛掰，但是。
问题是界面太丑，而且有点杂乱，我实在受不鸟。
关于中转的话。。你看看V3魔改就行的。。
他的支持中转规则，需要后端配合，我看了你的介绍，说是正在研究，我很期待
近期我看了好几个酸酸乳管理的面板。。你的面板应该是最好的了，，但是完成度感觉还不是很高。
商品只能按照流量卖吗？
月付，季付，半年，一年付呢。。。我看到可以筛选，但是没有找到如何添加。
还有，我设置的默认加密，协议混淆啥的，新注册用户，还是原来安装时候的默认，不是我设定的。
还有分组名称，我没有看到客户界面有显示。。
也许是我使用的姿势不对。

那个商品图片，是不是该有个分辨率或者尺寸的提示。
然后，，酸酸乳，产品介绍啥的，要有放几行文字就行的地方吧。
你有没有讨论群，或者qq，tg号啥的，，可以方便讨论。
说了很多，希望你不会嫌弃麻烦

**Comment by cheapssr** [comment]
刚才看了一下前台，总结了一下情况，属于讨论和建议哈。
用户面板的，管理员后台的暂时不知道怎么说
不要打我哈
登陆cookie周期是不是有点短呢，一会就掉了

即使用户不勾选记住我。。也要多登陆一会儿吧

账号信息
积分换取流量，作为可选功能最好了，获取积分也就是邀请或者登陆签到啥的。其实邀请成功的话，直接给他加流量，或者加日期。不用积分也可以的

可用流量进度条看不准呢，有个数字显示最好。还有，买了好几个流量包，进度条没有变化。

开通月付，或者年付，不限制流量的用户，但是要防止他滥用。

举例，设定流量上限200G，到达之后，发邮件通知用户，线路停止，用户必须登录网站，手动清空一下流量。
添加清空已使用流量的按钮，重置流量数据。。管理员后台也可以直接清空。

感觉个人资料和ss信息掺杂一起没有必要啊

个人资料可以放到左面导航栏

在导航栏专门有个人资料，展示出用户的各种信息，允许用户修改自己的各种信息，右上角，个人有个退出就行了。。

在首页已经有了ss信息，而且可以修改了啊。


节点列表，没有看到节点分组的名称呢，各项名称最好是可选展示（比如负载啥的），如果不好弄的话，全部展示也可以的。。那个负载没有看懂，是cpu内存的占用率吗。

节点的当前展示加密，协议，混淆，要和用户修改过的一致。

节点列表的协议和混淆展示其实无所谓，用户购买以后，其实都是看配置，扫二维码，或者ssr链接（希望加入这个，最好有批量复制，一次性把可用线路的ssr连接都复制）

然后，节点列表的订阅功能。

节点如何限制用户的分享呢，，比如好几个人，用一个账号。（流量包就无所谓了，月付之类的咋办呢。）

商品图片，希望可以远程调用。，或者可选的去除。
图片感觉没有啥必要。。有些文字介绍就行。

最顶部黑色的栏，一大片黑色，或者显眼位置，弄个公告展示啥的。公告需要有个专门存放的地方，让管理选择展示谁，展示几条。。

要有帮助中心啥的。。管理员要写点帮助文章。

**Comment by ssrpanel** [comment]
@cheapssr 
1.商品目前只能按流量卖，接下来要加入那个包年包季套餐包，不过这个有个前提，我得先做一个到某天自动重置流量的功能。
2.“月付，季付，半年，年付“这些选项是我自己用的用来标识这个用户的，将来改进掉
3.“我设置的默认加密，协议混淆啥的，新注册用户，还是原来安装时候的默认，不是我设定的。”这个我今天查一下，算是个BUG，等我修正下。
4.“还有分组名称，我没有看到客户界面有显示”，这个应当怎么展示，我还没想好。
是像魔改那种分组名称，点下去再看到底下的节点吗？我目前的分组用法是根据分组设定的级别和账号对应的级别，不同级别可以看到不同分组下的节点。
5.登录那个记住我是假的，以后再改进吧，登录用的是session不是cookie，session默认是两个小时，这个暂时不改进了。2个小时就是让用户上去看一眼当前账号的信息而已。
6.节点列表负载信息都可以显示，但是界面要怎么展示，如果你有想法，或者能画出原型图，麻烦发出来看下，我照着做。
7.“节点的当前展示加密，协议，混淆，要和用户修改过的一致。”这是啥意思？通常每个节点用SSR后端都会设置一个加密方式，协议，混淆的，像auth_chain_a如果节点后端设置好，用户自己把自己的加密方式改成auth_sha1_v4，则是无法连的。
8.有道理，我加个生成SSR链接的功能。
9.节点列表的订阅功能，这个是什么？SSR C#客户端的那个节点订阅功能是吗？这个我都不晓得怎么整。服务端的那个咋配置？求教程。
10.节点限制用户分享：目前我只知道有三种方式 1.把SSR服务端都设置为auth_chain_a不带兼容，协议参数填1，混淆为none，表示这个节点只能连一个账号 。2.用网上的一键iptables限制IP数 3.换魔改后端（有自带的限制）
11.添加商品时我没有强制得加商品图啊，我价格商品描述字段吧
12.这个我后面加上。我要把所有东西都限制为必须登录，不然会被爬虫爬到文章内容，尤其是出现shadowsocks、VPN这种关键字，无名不是被污染就是网站被墙，我已经被污染了一个域名也被墙了一个了。

**Comment by ssrpanel** [comment]
@cheapssr tg群我在首页有放了，但是不知道为啥只能我发言。

**Comment by ssrpanel** [comment]
@echoowall 昨天已经在看支付宝当面付-扫码支付 的文档了

**Comment by max2max** [comment]
大佬，你那个是频道啊，不是群组😅
频道是只有一个人发，其他人看的

**Comment by wxlost** [comment]
可以对接一个spay嘛.和魔改一样
http://spay.swapteam.cn/

**Comment by onesez** [comment]
希望可以增加一个支付接口，推荐https://www.fakajun.com，没有支付接口只能用发卡君的发卡不是很方便，能一起用发卡君的支付就好了。

**Comment by ssrpanel** [comment]
@onesez 发这个我看不懂它的api，api都没完善

**Comment by ssrpanel** [comment]
@wxlost 这个我看看

**Comment by onesez** [comment]
@ssrpanel QQ群号660639701，API非常简单啊，群内文档和PHP代码实力，我尝试写过魔改版的接口，但是没坚持下去

**Comment by onesez** [comment]
PHP的SDK和代码实例地址：http://fakajun.nos-eastchina1.126.net/Fakajun.php

**Comment by onesez** [comment]
API开发文档DOC下载地址：http://fakajun.nos-eastchina1.126.net/%E5%8F%91%E5%8D%A1%E5%90%9B%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3.doc

**Comment by onesez** [comment]
http://fakajun.nos-eastchina1.126.net/发卡君开发文档.doc

**Comment by ZBrettonYe** [comment]
关于支付宝插件 可以参考https://github.com/Ehco1996/django-sspanel  用的 支付宝插件：https://github.com/fzlee/alipay

**Comment by xh33006** [comment]
www.zfbjk.com 魔改版支持这个三方接口的，而且我也部署成功可用，这边不知道怎么弄

**Comment by pipilupipixia** [comment]
我已经对接了支付宝，QQ，微信，发起了pr。

**Comment by onesez** [comment]
什么叫做PR

**Comment by nishuo** [comment]
当面付门槛较低,还有50块代开当面付的,如果能支持当面付就最好了~
[支付宝开放平台服务端当面付SDK&Demo ](https://docs.open.alipay.com/194/105201/)

**Comment by ssrpanel** [comment]
国内全部不接，已经在做paypal接口了

**Comment by ssrpanel** [comment]
paypal 已实现
