### ISSUE TITLE
宕机邮件投递记录bug

### ISSUE THREAD

**Issue by shinjidotme** [ssrpanel/SSRPanel#222]
宕机邮件提醒关闭状态下，宕机确实没邮件，但仍有投递记录

**Comment by ssrpanel** [comment]
WTF，不科学，我改一下

**Comment by ssrpanel** [comment]
已修正，把“节点宕机警告”关闭则不发邮件不发serverchan
把“节点宕机警告”打开，必须填收邮件地址，才会发邮件
把“节点宕机警告”打开，不打开serverchan，则只发邮件不发serverchan，打开serverchan则也发serverchan消息
