### ISSUE TITLE
自动封禁用户流量异常 BUG

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/SSRPanel#223]
BUG出现在：用户使用流量24小时内达到限制流量， 用户会被禁了X分钟后解封，到这里一切正常； 解封10分钟后，用户又会再次被封 然后反复重复解封-被封；很是滑稽。

**Comment by ssrpanel** [comment]
@ZBrettonYe WTF，我试试哈哈哈哈啊

**Comment by ssrpanel** [comment]
把用户折腾死。。哈哈哈

**Comment by ssrpanel** [comment]
@ZBrettonYe 不对，你应该把封禁时间设置长一些

**Comment by ssrpanel** [comment]
@ZBrettonYe 这个没坑，我当初的目的就是要封至少3个小时的，我自己设置是180分钟，这样3个小时候后，流量就不会超了。还有24小时内流量我至少20G才算异常

**Comment by ZBrettonYe** [comment]
24小时 20G  那是很多人在用一个账号吧，我设置的是 6GB，  算过一个人用看视频 24小时很难达到这个水平

**Comment by ZBrettonYe** [comment]
还有续费功能还是有逻辑问题
