### ISSUE TITLE
结算比例不对

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#226]
1、某节点设定的结算比例是1.5，可流量日志里面统计的流量比例是1。

2、某节点分配给一个较高等级分组，某用户是最低等级分组。管理员登录进去去》用户列表》操作：点小飞机，此时可以看到本来不属于这个用户所在分组的节点
  
ssrpanel为最新版。

**Comment by ssrpanel** [comment]
@828768 节点SSR自己配置，面板里这个用来展示的

**Comment by 828768** [comment]
2、某节点分配给一个较高等级分组，某用户是最低等级分组。管理员登录进去去》用户列表》操作：点小飞机，此时可以看到本来不属于这个用户所在分组的节点

@ssrpanel 第一个明白了，那这个呢？
