### ISSUE TITLE
更新最新版本后，后台无法添加新帐号

### ISSUE THREAD

**Issue by mtk00713** [ssrpanel/SSRPanel#227]
![default](https://user-images.githubusercontent.com/28838804/34802245-902862b2-f6a7-11e7-9318-bdda54942a93.png)
选项变红色，按钮点击无反应
查看日志发现500错误

**Comment by ssrpanel** [comment]
你倒是把错误信息上报上来啊？

**Comment by ssrpanel** [comment]
重建user表
