### ISSUE TITLE
ssrpanel是如何将用户使用的上传流量和下载流量写入数据库的

### ISSUE THREAD

**Issue by wangrong1994** [ssrpanel/SSRPanel#228]
请教一下，我看到ssrpanel中的定时任务只是将user_traffic_log相关数据表的上传流量u和下载流量d进行统计监测，可是我不知道这些数据库的流量数据是怎么写进去的

**Comment by lm93129** [comment]
是后端SSR上报数据库写入的

**Comment by wangrong1994** [comment]
后端SSR是定时任务里进行写入的吗？

**Comment by ssrpanel** [comment]
@wangrong1994 那个vnstat规划是用于编辑节点时的节点监控地址用。后面暂停开发
