### ISSUE TITLE
默认打开的都是控制面板，能否改为登录界面？

### ISSUE THREAD

**Issue by leonis999** [ssrpanel/ssrpanel#23]
建好站点后每次打开域名默认都是打开的控制面板，能否直接改为登录界面。另外流量能否设置为每个月自动重置，流量显示条那里没有具体数值，不太直观，谢谢！

**Comment by leonis999** [comment]
还有新用户注册默认可用的流量就1GB，这个在哪里可以改动啊？

**Comment by ssrpanel** [comment]
@leonis999  leon是你，哈哈哈，好，需求我MARK下
