### ISSUE TITLE
用户余额的体现

### ISSUE THREAD

**Issue by 110560** [ssrpanel/SSRPanel#231]
在用户列表增加 查询 余额为0 以上的用户选项
在用户名下方的空白挺大的 
用户名下方的空白区域  显示 用户余额 并且显示 充值 
这样就可以 不用进入编辑页面查看用户余额和充值了

**Comment by ssrpanel** [comment]
嗯，我自己再使用过程中也挺蛋疼这点的，mark先

**Comment by 110560** [comment]
追加一个  身份切换 也可以放在用户名下方  地方真的挺大的
