### ISSUE TITLE
无法访问admin界面

### ISSUE THREAD

**Issue by iammsf** [ssrpanel/SSRPanel#233]
按照wiki页提供的方式安装，全程没有什么问题，结果进入panel之后发现无法对用户和节点列表进行操作。然后进入设置里的系统管理，出现了错误界面。报错如下：

> 

(2/2) ErrorExceptionUndefined variable: is_free_code (View: /www/ssrpanel/resources/views/admin/system.blade.php)
--
in ed47bb2b94e6f0f66165e6476c90c23c6ebf8c55.php (line 122)
at CompilerEngine->handleViewException(object(ErrorException), 1)in PhpEngine.php (line 44)
at PhpEngine->evaluatePath('/www/ssrpanel/storage/framework/views/ed47bb2b94e6f0f66165e6476c90c23c6ebf8c55.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'is_rand_port' => '0', 'is_user_rand_port' => '0', 'invite_num' => '3', 'is_register' => '1', 'is_invite_register' => '1', 'website_name' => 'SSRPanel', 'is_reset_password' => '1', 'reset_password_times' => '3', 'website_url' => 'http://www.ssrpanel.com', 'is_active_register' => '1', 'active_times' => '3', 'login_add_score' => '1', 'min_rand_score' => '1', 'max_rand_score' => '100', 'wechat_qrcode' => '', 'alipay_qrcode' => '', 'login_add_score_range' => '1440', 'referral_traffic' => '1024', 'referral_percent' => '0.2', 'referral_money' => '100', 'referral_status' => '1', 'default_traffic' => '1024', 'traffic_warning' => '0', 'traffic_warning_percent' => '80', 'expire_warning' => '0', 'expire_days' => '15', 'reset_traffic' => '1', 'default_days' => '7', 'subscribe_max' => '3', 'min_port' => '10000', 'max_port' => '40000', 'is_captcha' => '0', 'is_traffic_ban' => '1', 'traffic_ban_value' => '10', 'traffic_ban_time' => '60', 'is_clear_log' => '1', 'is_node_crash_warning' => '0', 'crash_warning_email' => '', 'is_server_chan' => '0', 'server_chan_key' => '', 'is_subscribe_ban' => '1', 'subscribe_ban_times' => '20', 'paypal_status' => '0', 'paypal_client_id' => '', 'paypal_client_secret' => ''))in CompilerEngine.php (line 59)
at CompilerEngine->get('/www/ssrpanel/resources/views/admin/system.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' =>object(ViewErrorBag), 'is_rand_port' => '0', 'is_user_rand_port' => '0', 'invite_num' => '3', 'is_register' => '1', 'is_invite_register' => '1', 'website_name' => 'SSRPanel', 'is_reset_password' => '1', 'reset_password_times' => '3', 'website_url' => 'http://www.ssrpanel.com', 'is_active_register' => '1', 'active_times' => '3', 'login_add_score' => '1', 'min_rand_score' => '1', 'max_rand_score' => '100', 'wechat_qrcode' => '', 'alipay_qrcode' => '', 'login_add_score_range' => '1440', 'referral_traffic' => '1024', 'referral_percent' => '0.2', 'referral_money' => '100', 'referral_status' => '1', 'default_traffic' => '1024', 'traffic_warning' => '0', 'traffic_warning_percent' => '80', 'expire_warning' => '0', 'expire_days' => '15', 'reset_traffic' => '1', 'default_days' => '7', 'subscribe_max' => '3', 'min_port' => '10000', 'max_port' => '40000', 'is_captcha' => '0', 'is_traffic_ban' => '1', 'traffic_ban_value' => '10', 'traffic_ban_time' => '60', 'is_clear_log' => '1', 'is_node_crash_warning' => '0', 'crash_warning_email' => '', 'is_server_chan' => '0', 'server_chan_key' => '', 'is_subscribe_ban' => '1', 'subscribe_ban_times' => '20', 'paypal_status' => '0', 'paypal_client_id' => '', 'paypal_client_secret' => ''))in View.php (line 137)
at View->getContents()in View.php (line 120)
at View->renderContents()in View.php (line 85)
at View->render()in Response.php (line 38)
at Response->setContent(object(View))in Response.php (line 201)
at Response->__construct(object(View), 200, array())in ResponseFactory.php (line 55)
at ResponseFactory->make(object(View), 200, array())in ResponseFactory.php (line 69)
at ResponseFactory->view('admin/system', array('is_rand_port' => '0', 'is_user_rand_port' => '0', 'invite_num' => '3', 'is_register' => '1', 'is_invite_register' => '1', 'website_name' => 'SSRPanel', 'is_reset_password' => '1', 'reset_password_times' => '3', 'website_url' => 'http://www.ssrpanel.com', 'is_active_register' => '1', 'active_times' => '3', 'login_add_score' => '1', 'min_rand_score' => '1', 'max_rand_score' => '100', 'wechat_qrcode' => '', 'alipay_qrcode' => '', 'login_add_score_range' => '1440', 'referral_traffic' => '1024', 'referral_percent' => '0.2', 'referral_money' => '100', 'referral_status' => '1', 'default_traffic' => '1024', 'traffic_warning' => '0', 'traffic_warning_percent' => '80', 'expire_warning' => '0', 'expire_days' => '15', 'reset_traffic' => '1', 'default_days' => '7', 'subscribe_max' => '3', 'min_port' => '10000', 'max_port' => '40000', 'is_captcha' => '0', 'is_traffic_ban' => '1', 'traffic_ban_value' => '10', 'traffic_ban_time' => '60', 'is_clear_log' => '1', 'is_node_crash_warning' => '0', 'crash_warning_email' => '', 'is_server_chan' => '0', 'server_chan_key' => '', 'is_subscribe_ban' => '1', 'subscribe_ban_times' => '20', 'paypal_status' => '0', 'paypal_client_id' => '', 'paypal_client_secret' => ''))in Facade.php (line 221)
at Facade::__callStatic('view', array('admin/system', array('is_rand_port' => '0', 'is_user_rand_port' => '0', 'invite_num' => '3', 'is_register' => '1', 'is_invite_register' => '1', 'website_name' => 'SSRPanel', 'is_reset_password' => '1', 'reset_password_times' => '3', 'website_url' => 'http://www.ssrpanel.com', 'is_active_register' => '1', 'active_times' => '3', 'login_add_score' => '1', 'min_rand_score' => '1', 'max_rand_score' => '100', 'wechat_qrcode' => '', 'alipay_qrcode' => '', 'login_add_score_range' => '1440', 'referral_traffic' => '1024', 'referral_percent' => '0.2', 'referral_money' => '100', 'referral_status' => '1', 'default_traffic' => '1024', 'traffic_warning' => '0', 'traffic_warning_percent' => '80', 'expire_warning' => '0', 'expire_days' => '15', 'reset_traffic' => '1', 'default_days' => '7', 'subscribe_max' => '3', 'min_port' => '10000', 'max_port' => '40000', 'is_captcha' => '0', 'is_traffic_ban' => '1', 'traffic_ban_value' => '10', 'traffic_ban_time' => '60', 'is_clear_log' => '1', 'is_node_crash_warning' => '0', 'crash_warning_email' => '', 'is_server_chan' => '0', 'server_chan_key' => '', 'is_subscribe_ban' => '1', 'subscribe_ban_times' => '20', 'paypal_status' => '0', 'paypal_client_id' => '', 'paypal_client_secret' => '')))in AdminController.php (line 1564)
at AdminController->system(object(Request))
at call_user_func_array(array(object(AdminController), 'system'), array(object(Request)))in Controller.php (line 55)
at Controller->callAction('system', array(object(Request)))in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(AdminController), 'system')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 574)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Admin.php (line 23)
at Admin->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in User.php (line 33)
at User->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php (line 41)
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 576)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 535)
at Router->dispatchToRoute(object(Request))in Router.php (line 513)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php (line 27)
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 53)

请问如何解决

**Comment by ssrpanel** [comment]
重新导入config表
