### ISSUE TITLE
Windows 客户端单端口节点无法通过订阅地址获取节点信息

### ISSUE THREAD

**Issue by a327958099** [ssrpanel/SSRPanel#236]
Windows 客户端 ShadowsocksR-4.7.0   单端口多用户节点无法通过订阅地址获取节点信息，安卓SSR客户端可以订阅到节点，但是密码不对有问题，需要手动重新输入密码才能连接，大家有出现这个情况吗？

**Comment by ssrpanel** [comment]
截图

**Comment by zdf0221** [comment]
也遇到了这个问题

**Comment by ssrpanel** [comment]
@a327958099 @a327958099 配置错了吧，看这个
https://github.com/ssrpanel/SSRPanel/wiki/%E5%8D%95%E7%AB%AF%E5%8F%A3%E5%A4%9A%E7%94%A8%E6%88%B7%E7%9A%84%E5%9D%91
