### ISSUE TITLE
每月可用流量重置时间点

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#237]
每月可用流量这个是固定的时间重置么？
买的vps时间不同，一般是下个月同日重置流量，那在ssrpanel后台是什么时候去重置呢？如果是固定下月1日重置也不合理，应该有个地方指定某节点流量何日重置。

**Comment by ssrpanel** [comment]
那个只是用来备注显示用，方便二次开发给别人展示给用户的
