### ISSUE TITLE
已过期用户   有效期不重置 bug

### ISSUE THREAD

**Issue by 110560** [ssrpanel/SSRPanel#239]
具体案例表现为
用户A   用户有效期已经在1月1号过期    1月10号再次购买商品（商品有效期30天）    购买后用户过期时间为1月31日，   正常计算应该是2月9日过期，中间缺少了十天

**Comment by w3forever** [comment]
同样有这个情况，比如：新用户注册后默认30天有效期，但实际时期是大于30天的。

**Comment by ssrpanel** [comment]
@110560 @w3forever BUG已修正，更新一下

**Comment by w3forever** [comment]
谢谢修正。

**Comment by ller** [comment]
@110560 @ssrpanel 更新代码测试了下。。我发现bug还是在呀
