### ISSUE TITLE
希望可以在面板内增加一栏软件下载，以及公告的一些建议

### ISSUE THREAD

**Issue by a582995627** [ssrpanel/ssrpanel#24]
Rt，更加便捷。

另外更新后发现变成顶部的通知，如果想找到历史公告还有些麻烦，要等待一定的时间切换，如果可以的话建议在右边加一个类似查看更多的选项，来浏览全部公告

**Comment by ssrpanel** [comment]
@a582995627 
软件下载那个我想想看怎么跟文章整合在一起，排版布局的问题，工具的话最好自己上传维护
