### ISSUE TITLE
ssr单端口多用户+ssrpanel 怎么限制同时登录设备数量

### ISSUE THREAD

**Issue by lijinlei521** [ssrpanel/SSRPanel#240]
ssr单端口多用户+ssrpanel 怎么限制同时登录设备数量，如果不能的话 那么  ssrpanel +ssr多用户模式 可以吗？ 
那么该如何配置 ，需要限制设备数量

**Comment by 110560** [comment]
不支持限设备  也不支持限速。  自己用魔改去。回答完毕。 请关闭你的问题。
