### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/SSRPanel#241]
刚刚发现了一个莫名奇妙的bug；
用户 24号过期的， 现在21号； 用户套餐应该没有过期的（流量没有超过套餐流量）； 去查后台 显示为

【自动封禁】-流量超限...  然后去看了一下 其他的 结果发现很多这种情况被封的。。。。

**Comment by ZBrettonYe** [comment]
补充：他们的套餐流量都被清空为默认值；

**Comment by ssrpanel** [comment]
流量超限。。。你自己看设置

**Comment by ZBrettonYe** [comment]
@ssrpanel 流量超额这些 我还是会看的； 目前推测是 流量自动重置 这个按钮关闭以后 并没有实制关闭
