### ISSUE TITLE
关于面板进化的建议

### ISSUE THREAD

**Issue by cheapssr** [ssrpanel/ssrpanel#25]
01，关于分组，用户界面展示他拥有的分组。

举例：我后台建立了几个分组。免费节点分组，基础节点分组，高级节点分组，不同等级的用户，拥有不同的节点分组，和你的思路一样，级别不同，显示的节点不同。向下兼容。

我的意思是，把这个节点分组名称展示出来，比如我是高级用户，那么我拥有免费，基础，高级三个分组，显示出三个分组，点击分组，显示节点列表。

我这么建议的原因是：节点少的话无所谓，如果节点多，几十个的话，那直接显示所有的节点列表，几十行啊。。

当然，也可以给节点加标签，游戏，下载，bt等等，可以让用户筛选。节点有自己的分组，也有自己的标签。这个可以和聊天说的一样，向wordpress学习，嘿嘿。节点少的用不上，节点多的才有用。

02，节点负载信息，不需要展示cpu内存啥的，用户不会关心的。可以学习魔改的，展示延迟，速度啥的，建议你搭建一个魔改，添加一条线路，看看他那很丑，很难看懂的图表。可以学习他的功能，他的图表千万别用，对小白用户并不友好。我有时间会画个给小白看的图表传上来。

03，关于加密，协议，混淆。。这个咋说呢。。
   （1）节点列表，不显示加密方式呢，端口，服务地址啥的。但是显示协议和混淆
    我个人觉得，要么都显示，要么都不显示，显示两项没有啥意义
  （2）节点列表
       我是管理员
       我建立线路，默认的，加密chacha20，协议v4，混淆tls1.2，选择了 后端配置兼容ss。

我现在作为一个普通用户，
节点列表，展示的线路，协议混淆就是管理员建立时默认的。。
然后，我在首页选择自己的加密为rc4md5，协议a协议，混淆httpsimple。。
现在，我打开线路列表，显示的协议和混淆，还是v4和tls1.2，，配置文件的话，倒是和我自己选择的一样。

总结：这样给人一种很别扭的赶脚。。我觉得吧，
1，节点信息就是显示负载，人数，流量，流量比例，线路介绍，线路分组啥的，，可以不显示节点连接参数，连接参数要看后面的配置文件，二维码。
2，如果连接参数必须要显示在节点上，那么要和用户修改过的一致，不要显示线路默认的配置。。
不知道有没有说清楚。。

04，，关于订阅，，我没有教程啊，参考魔改吧，搭建一个看看他是咋做到的

05，关于限制，流量包无所谓，，如果是月付的用户，限制很有必要。。这个以后解决吧，倒是不急。。不过，限制用户的速度，破娃的后端就可以啊，能否加上呢，单线程速度，总速度都能限制。

06，添加商品，可以不添加图片，，但是空着一块好丑的。。可否选择显示呢。

07，这个，管理员的管理体验有些混乱。。
     建议是，管理员登陆的话，和普通用户一样的展示和功能，但是多了一个后台管理的按钮，点击之后，就是单纯的后台管理。再点击用户中心，就又是单纯的用户界面和功能了。

或者，彻底的管理员登录地址和普通用户不同。可以完全操控普通用户的各个功能。
这个容易实现吗。

现在的情况是，管理员功能和用户功能掺杂在一起了。

**Comment by cheapssr** [comment]
(1/1) FileExceptionUnable to create the "/www/wwwroot/***.***.com/ssrpanel/public/upload/image/goods/" directory
上传图片这个提示。是权限不够吧

**Comment by cheapssr** [comment]
添加商品，，售价过大时会跳到报错页面。。建议修一下，过大弹出个提示啥的

**Comment by cheapssr** [comment]
访问网站域名，出现的是管理面板，bug，，快，不然你会忘记的

**Comment by ssrpanel** [comment]
@cheapssr 好，先别close 这个issue，我留着一个个改，
1.访问网站域名那个BUG我修复了
2.那个上传图片是没权限，你要把整个public设置为nginx的运行者，lnmp默认用户是www:www
这样：
chown -R www:www /www/wwwroot/***.***.com/ssrpanel/public/
chmod -R 755 /www/wwwroot/***.***.com/ssrpanel/public/

**Comment by ssrpanel** [comment]
@cheapssr 添加商品售价过大的那个截个图啊，我看下你是怎么搞的

**Comment by cheapssr** [comment]
上传图片没有权限哪个，，我用的是宝塔面板搭建的。。
public/upload/images
images目录直接改成777就能上传了，，好神奇

然后，issues咋上传图片啊

售价如果是：99999999999999999999
这个错误。
我是不是有点吹毛求疵了，，一般人也不会这个售价
(2/2) QueryException
SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'price' at row 1 (SQL: insert into `goods` (`name`, `logo`, `traffic`, `price`, `score`, `status`, `updated_at`, `created_at`) values (1, , 10, 99999999999999999999, 1, 0, 2017-09-20 17:12:28, 2017-09-20 17:12:28))

**Comment by cheapssr** [comment]
关于网站升级，，站点git pull，，
数据库需要重新导入，，用户数据也就没有了。。
希望的是，数据库能跟着升级，原来的用户数据要在。。
或者说，，用户的各种信息能保留着升级

**Comment by cheapssr** [comment]
用户注册，自动获得流量，希望可以管理员自定义给多少流量，，我想给200M的。。

**Comment by cheapssr** [comment]
线路默认的密码只有4位，是不是太短了，虽然可以自定义，但是大多数用户，都是比较懒的，给啥就用啥，这种密码太弱了。

希望改成10位数的大小写数字字母混合密码。。带上特殊字符更好。

如果能让管理员自定义初始密码的排列组合就更好了。

这个不急，以后慢慢改就行，不是刚需。

**Comment by cheapssr** [comment]
记得。。充值记录要有。。

**Comment by cheapssr** [comment]
Commits on Sep 22, 2017
这个版本git pull更新后报错误，管理员的系统设置

数据库删除旧的，重新导入了。。

(2/2) ErrorExceptionUndefined variable: default_traffic (View: /www/wwwroot/****.com/ssrpanel/resources/views/admin/system.blade.php)
--

in 97ca5664bdf972ec8e0f0992ca7a69b2c36d13d6.php (line 129)
--
at CompilerEngine->handleViewException(object(ErrorException), 1)in PhpEngine.php (line 44)
at PhpEngine-at PhpEngine->evaluatePath('/www/wwwroot/*****.com/ssrpanel/storage/framework/views/97ca5664bdf972ec8e0f0992ca7a69b2c36d13d6.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'is_rand_port' => '0', 'is_user_rand_port' => '0', 'invite_num' => '3', 'is_register' => '1', 'is_invite_register' => '1', 'website_name' => 'SSRPanel', 'is_reset_password' => '1', 'reset_password_times' => '3', 'website_url' => 'http://baidu.com', 'is_active_register' => '1', 'active_times' => '3', 'login_add_score' => '1', 'min_rand_score' => '1', 'max_rand_score' => '100', 'wechat_qrcode' => '', 'alipay_qrcode' => '', 'login_add_score_range' => '1440', 'referral_traffic' => '1024', 'referral_percent' => '0.2', 'referral_money' => '100', 'referral_status' => '1'))
in CompilerEngine.php (line 59)

**Comment by ssrpanel** [comment]
@cheapssr 除了限速、充值记录，全部都完善了。。

**Comment by 828768** [comment]
默认单连接和单用户限速在哪设置？设置的200M相当于是没限速，一个个去改麻烦
