### ISSUE TITLE
工单系统标签安全过滤 BUG发现

### ISSUE THREAD

**Issue by LYJSPEEDX** [ssrpanel/SSRPanel#257]
## **在使用工单系统时，若用户在编辑器内写入脚本代码，管理员查看工单时，脚本将会被运行，引发一系列不可预知的后果**
下图为写入了提示框代码的工单打开后果
![browser](https://user-images.githubusercontent.com/26499797/35574890-fb151390-0615-11e8-8768-c31dea22b172.png)
源码查看
![source](https://user-images.githubusercontent.com/26499797/35574877-f2f4aa36-0615-11e8-8a07-4d1ca2fc409a.png)
本人觉得是否在工单系统内加入标签安全过滤，防止此类漏洞。

**Comment by SmallOyster** [comment]
为啥不把那张带有for的脚本工单show出来？[滑稽脸]

**Comment by LYJSPEEDX** [comment]
[捂脸]

**Comment by ssrpanel** [comment]
感谢反馈

**Comment by ssrpanel** [comment]
@LYJSPEEDX 代码已更新，请git pull后，执行一遍 php composer.phar install
