### ISSUE TITLE
对用户、节点分组的改进建议~

### ISSUE THREAD

**Issue by LYJSPEEDX** [ssrpanel/SSRPanel#258]
希望在节点分组中，加入“仅某一级别用户可见”这一功能，增加特定用户组访问特定节点的功能。即将'对应账号级别可见该分组下的节点（向下兼容）'改为选用。

> **这可使站长更加灵活地分配节点，配置具有特定套餐的特定线路。而不必级别范围所限制。望接纳，谢谢！~**

**Comment by SmallOyster** [comment]
(自己写啦，二次开发不难啊 :joy:)

**Comment by ssrpanel** [comment]
@LYJSPEEDX 见wiki中的规划

**Comment by ssrpanel** [comment]
已加，用户和节点必须处于同一个标签下，用户才可见

本次更新：
1.git pull
2.修改config/database.php 下 mysql 配置中的strict 为 falst（不使用mysql的严格模式）
3.导入db/update下最后一个sql文件到数据库
4.truncate table user_subscribe   、 truncate table user_subscribe_log
5.进后台给节点设置标签、给每个用户分配标签
