### ISSUE TITLE
建议增加天卡，月卡，年卡功能

### ISSUE THREAD

**Issue by aazzpp678** [ssrpanel/ssrpanel#26]
1、目前离正式商用其实就只差 月卡，年卡功能了。个人对于功能的想法是都以天来作为结算单位，创建包时卡的时候，自定义包时卡的名字（如月卡，季卡等）就可以了，这样拓展性最强。同时也可以自定义价格。
2、对于支付的想法的话，个人建议接入发卡平台，毕竟飞机场还是有一定法律风险的，直接对接支付宝微信感觉不是特别好。

**Comment by ssrpanel** [comment]
@aazzpp678 好，我有这方便想法

**Comment by ssrpanel** [comment]
@aazzpp678 好，需求加入排期

**Comment by cheapssr** [comment]
如果做的话，希望可以一步到位，直接自定义周期，比如月卡，我自定义一个30天的周期，就是月卡了，季卡，年卡也可以这样。。
然后说，也可以按照小时定义周期，也可以做个流量包给用户，
适合让用户体验一下，比如第一次注册，，免费用户想尝试收费的线路。
这个想法咋样。

**Comment by aazzpp678** [comment]
反正我觉得现在最大的痛点就是包时卡和支付了，没有的话不好卖。如果作者来得及开发的话那就最好了，哈哈

**Comment by cheapssr** [comment]
慢慢等吧，功能要一个个添加的，也要排除bug，，，作者业余时间做。。能做到现在这样，已经很好了

**Comment by ssrpanel** [comment]
@cheapssr @aazzpp678 商品带有效期功能做好了，不过目前不能实现月卡，需要定时任务支持。每个月重置一次这个。。

**Comment by aazzpp678** [comment]
@ssrpanel 我觉得可以把功能用另外套思路完成，不需要定时任务，那个太复杂。  月卡其实就是 流量大小（已知）和有效期（已知）。只要每次有效期（我觉得有效期可以简化成天就可以了，当晚12点过期）到期的时候，给用户账户下扣除这段有效期内的剩余的流量（举个例子，如设定月卡为 30天100G，9月1日订购了季卡（其实就是3个月），则在每30号的时候，扣除100G）

**Comment by aazzpp678** [comment]
所有需要的字段在数据库里记录就可以

**Comment by aazzpp678** [comment]
不过想了下也是需要定时任务。。。。来出发这个操作

**Comment by cheapssr** [comment]
@aazzpp678 定时任务是必须需要的。。关于，9月1日订购了季卡（其实就是3个月），则在每30号的时候，扣除100G。。。如果我是用户，那么我在30号之前，，用的流量不算数吗？流量必须实时的扣除，扣光100G就无法连接，程序上可以清空已经使用的流量，设定是否允许用户自己清空的选项。管理员后台，也要能控制，是否给用户清空。

**Comment by cheapssr** [comment]
@aazzpp678 这个功能，其实也不急，，把现有的bug修复再说吧。。。感觉无法投入商用现在。。

**Comment by aazzpp678** [comment]
现在流量扣除不就是实时的么？我举的是9.1号的日子，其实9.8号订购也没啥问题啊，10月8号扣啊

**Comment by aazzpp678** [comment]
没有包时卡和支付谈何商用？BUG？我用的没啥问题啊，自己根据错误日志自己改改啊，不可能这个程序像微信那样无BUG

**Comment by aazzpp678** [comment]
最重要的是要让作者帮我们框架和功能写好，细节的东西其实主要还是靠我们自己动手的，毕竟不是真正的商业产品，没有问题是不可能的，除非给作者配一个团队

**Comment by cheapssr** [comment]
@aazzpp678 咱俩说的错位了。。。。如果说：我9月8号订购的，当天用了100G，，肯定就上不去了吧。。
错误日志，，我都看不懂，这个我不会告诉你的。。然后，，放心，我动手能力绝对不够。完全依靠作者的。没关系，我可以慢慢等作者的产品成熟，毕竟出来么有多久，慢慢来吧，一年，2年，只要作者中途不放弃，慢慢会成熟的。

**Comment by aazzpp678** [comment]
包时卡的基本要素就是，期限和流量大小。流量用完了，上不去不是很正常…

**Comment by cheapssr** [comment]
@aazzpp678 所以说，咱俩说的错位了。。等作者慢慢做吧

**Comment by aazzpp678** [comment]
我说的动手能力是指会懂点php和mysql…如果你指的是安装php的话…都是一键包也没啥要动手的吧

**Comment by aazzpp678** [comment]
1年两年后ssr在不在还是个问题…

**Comment by cheapssr** [comment]
VPN都活了10年。。。除非有个更容易商业化的技术出来

**Comment by aazzpp678** [comment]
对啊，你也知道这是个生意的事，没有支付和订单购买…怎么算商业产品？

**Comment by aazzpp678** [comment]
不过刚的讨论也让我更细化了下需求，我现在总结下：
1.包时卡的要素是流量大小和时效，两者其一不满足则该用户当月套餐（包时卡）服务结束
2.不管是月卡，还是季卡，流量结算都以月为一个周期。购买后的第30天（即一个月）那天晚十二点，在满足1的条件下，将用户账户下这个月的剩余流量清空（举个例子，如设定季卡为每月 100G，9月8日订购了季卡，在10月7号晚12点的时候，如果用户用了40G，则剩余的60G不累加到下个结算月。10月8号开始依然是100G）
3.其实说了这么多，就是手机流量卡的概念………
4.@cheapssr你觉得如何

**Comment by aazzpp678** [comment]
还有吧，我始终觉得一个panel太完美的话，用的人非常多的话，作者要被请去喝茶

**Comment by cheapssr** [comment]
@aazzpp678 简单问题复杂化了。。。周期自定义，以天为单位。。自定义30天，取名月卡，自定义90天，取名季卡，，设定每个月的流量上限，每个月1号清空已经使用的流量。要有提前清空流量的功能，就这样可以了。

**Comment by aazzpp678** [comment]
MRD和PRD😂

**Comment by ssrpanel** [comment]
@cheapssr 
1.已加手动重置已使用流量
2.已加每月1日流量自动重置

**Comment by ssrpanel** [comment]
@aazzpp678 @cheapssr 把商品改成了带日期的，分两种类型：套餐、流量包，记得启用定时任务
