### ISSUE TITLE
更新出错紧急求救。   

### ISSUE THREAD

**Issue by 110560** [ssrpanel/SSRPanel#261]
![img_20180202_153917_839](https://user-images.githubusercontent.com/32481672/35721925-4251b950-082f-11e8-907b-5db2e5602dac.jpg)

**Comment by xiaoanweiwu** [comment]
最新的那个更新吗？
执行一次php composer.phar install

**Comment by 110560** [comment]
@xiaoanweiwu     (⊙o⊙)哇   操作就好了    你怎么知道

**Comment by xiaoanweiwu** [comment]
@110560 新加了PHP依赖，所以要执行这个装上新的依赖。
