### ISSUE TITLE
2个小添加

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/SSRPanel#262]
1. 节点设置中 带上混淆参数；就是在首页上同步显示后台设置的混淆参数；二维码扫描会自动设置上混淆参数；

2. 文章支持纯连接； 
（除了公告和文章以外，在添加一个纯连接；
管理选择后，下面的不是文章输入框而是网址输入框；显示位置还是在文章处，用户点击后会自动转到链接指向页面）；

第一点主要是看了破娃酱的  这篇文章 《让linode复活》 中提到的方法；

链接：https://breakwa11.blogspot.com/2016/07/linode.html

**Comment by ZBrettonYe** [comment]
还有关于单端口多用户：

 https://breakwa11.blogspot.com/2017/01/shadowsocksr-mu.html 中提到了

> 第一部分：直接修改服务端配置文件大法，仅适用于使用单用户配置的情况
> 首先是服务端的配置
> 服务端把协议(protocol)配置为 auth_aes128_md5 或 auth_aes128_sha1，然后在协议参数(protocol_param)配置所有可用的用户id及其密码，示例如下：
> 
>         "protocol": "auth_aes128_sha1",
>         "protocol_param": "64#12345:breakwa11,233:zhihuyaowan",
> 
> 含义：
> 在#前面的表示每个用户的最大客户端数，照着写这个值或者不填都可以，但必须有#号。在#后，以英文逗号分隔所有的用户，而英文冒号的前面是用户的id，注意这个id必须是范围在 1~2147483647之间，后面的是用户的密码，密码不能有特殊符号，建议仅使用数字和大小写字母

不知道这个方法 能不能 变为限制端口设备数量的 方法

**Comment by ssrpanel** [comment]
@ZBrettonYe 谢谢开路，我研究下就加上这个功能

**Comment by ssrpanel** [comment]
@ZBrettonYe 这个搞明白了，你直接在每个节点上的配置里（单端口也是），把 "protocol_param": 中的
#号前面加上要限制的数量即可
