### ISSUE TITLE
http://域名/user页面不存在0.0

### ISSUE THREAD

**Issue by qq3461269698** [ssrpanel/SSRPanel#269]
没有用户面板？

**Comment by ZBrettonYe** [comment]
你这是没有搭建成功

**Comment by JMVoid** [comment]
@ZBrettonYe 我用十一的一键搭建后。也存在这个问题。安装后，admin面板全部的功能就没有问题。但是用注册新用户后，用一般用户登录，跳转 http://domainname/user 就会有404页面错误。因为我对于php没经验，试过想打开php-fpm的错误日志。但是什么都没有任何纪录。请问怎么入手解决问题？多谢了
