### ISSUE TITLE
注册的时候不发送激活邮件

### ISSUE THREAD

**Issue by laurieryayoi** [ssrpanel/ssrpanel#27]
admin重置密码邮件无法发送会跳转的报错页面
另外，把删帐号的按钮加回来吧……测试邮件的时候把自己的邮箱都注册完了。
然后删不了帐号……

**Comment by ssrpanel** [comment]
@laurieryayoi 注册发激活邮件加上了，删除按钮还是不要加，可以删除账号坑好多的。账号一删除，所有跟账号有关的一切信息都会有问题
