### ISSUE TITLE
更新到 d9f5827后用户不关联标签看不到节点

### ISSUE THREAD

**Issue by lowprofileusername** [ssrpanel/SSRPanel#270]
即使节点没有任何标签用户也看不到节点。

如：用户没标签，节点没标签。用户看不到节点

必须给用户和节点都上了标签节点才能显示。

之前用户和节点没标签都可以显示。或者节点有标签用户没标签也可以显示。

另外一个BUG是给某节点设置标签后删除标签点击保存标签还存在。

**Comment by ssrpanel** [comment]
1.弃用节点分组，太low b了
2.用标签来管理用户与节点的关系，需要手动给每个节点设置标签，然后给每个用户设置标签
3.特定节点给特定的用户用，其他人除非黑了你的服务器，否则根本看不到这些节点

**Comment by ssrpanel** [comment]
另外一个BUG是给某节点设置标签后删除标签点击保存标签还存在。

这个我不明白，能描述的清晰点吗

**Comment by lowprofileusername** [comment]
1、就是比如我给节点设置一个“联通”的标签。发现标错了。清空标签那栏。点击提交显示编辑成果。再次打开该节点“联通”标签海存在节点标签处。是否是因为每个节点必须至少有一个标签。这个标签一一旦添加了是怎么都删除不掉的。
2、还是分组的问题，用户分组默认有7组，我尝试添加第8组。添加失败。
3、用户ID递增问题。目前有10个用户。从数据库里把ID为10的用户删除。再注册一个新用户。这个新用户的ID是11不是10。 再把这个ID为11的用户从数据库删除。再注册一个新用户，这时候新用户的ID为12。我想请教一下这个用户ID是根据什么判断的？有时候不小心注册了一个测试用户删除了。再注册的时候用户ID就不连贯了。谢谢

**Comment by lowprofileusername** [comment]
另外流量日志里是否可以更改一下文字表述。目前30日内流量消耗情况和24小时内流量消耗情况会让人看不太懂。 1-30 和1-24 想要知道具体是几号或者是几点的流量得做一些换算才能明白。

**Comment by lslzl3000** [comment]
@ssrpanel 现在必须手动给用户加标签~~~ 这太不合理了吧，根本没法管理，起码购买某个套餐或者符合某种规则后，能自动加标签吧~~

**Comment by ssrpanel** [comment]
已经再改进了

**Comment by ssrpanel** [comment]
已经改进了
