### ISSUE TITLE
流量赠送是不是赋错用户了？

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#271]
后台设置的推荐新用户赠送500M流量，可流量赠送为啥不是邀请码生成者而是使用者，是不是刚好搞反了？
![snipaste_2018-02-12_22-12-47](https://user-images.githubusercontent.com/6386202/36100667-fa4c71b6-1041-11e8-8951-5ca828c6daf4.png)
![snipaste_2018-02-12_22-12-57](https://user-images.githubusercontent.com/6386202/36100668-fa86a4bc-1041-11e8-941a-bb9b7c2cf9f2.png)

**Comment by 828768** [comment]
@ssrpanel 查了下邀请码的历史记录，应该都送错了，被邀请者送了设置的流量，而邀请者却没得到奖励。

**Comment by ssrpanel** [comment]
系统设置-推广返利设置-启用这个功能。。里面的注册送流量就是要送的流量值，送给注册的人的

**Comment by ssrpanel** [comment]
跟扩展设置里的初始流量是叠加的

**Comment by ssrpanel** [comment]
邀请者是不送流量的，邀请的人会有消费返利。。。需要的话我加上

**Comment by 828768** [comment]
@ssrpanel 理解下来这个奖励流量不给邀请者，那就没多大意义，完全可以直接用初始流量就可以了。要么就给个选项让两方都能得到流量奖励，这样才有动力推广邀请新用户。

**Comment by ssrpanel** [comment]
嗯，已加上，等待更新
