### ISSUE TITLE
用户面板无法显示节点

### ISSUE THREAD

**Issue by qq3461269698** [ssrpanel/SSRPanel#272]
我在管理员后台面板添加了节点，数据库里已经有了节点数据，分组可见也是最低可见的，但是在用户首页就不显示，这是为什么？
望解答   ------通过宝塔搭建

**Comment by 828768** [comment]
猜，你这个节点分的组不是你这个用户所在等级可以看到的。高等级分组可以看到低等级分组的节点，反过来是不行的。

**Comment by ssrpanel** [comment]
@828768 不对，已经弃用节点分组了。。全部改成标签了。需要手动维护每个节点的标签，和每个用户对应的标签

**Comment by he123789** [comment]
我重新搭建了现在这个包含标签的面板，然后导入了之前的数据库，所以之前那些人都没有设置标签，都看不到节点什么的，有没有办法快速修改那些人的标签，使他们可以看到节点，一个个的改好麻烦😂
