### ISSUE TITLE
更新了最新的“标签管理”版本后，面板出错。

### ISSUE THREAD

**Issue by sanboukarasu** [ssrpanel/SSRPanel#273]
QueryException
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #29 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'v****01.ss_node_label.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select * from `ss_node` left join `ss_node_label` on `ss_node`.`id` = `ss_node_label`.`node_id` where `ss_node_label`.`label_id` in (2) and `ss_node`.`status` = 1 group by `ss_node`.`id`)
管理员登陆没问题。
但是普通用户登陆报这个错误，应该是标签管理的问题，求教如何修正。

**Comment by sanboukarasu** [comment]
修好了。原因是database.php文件本身也更新了，重新配置就好了。
这次更新以后，节点和用户都必须注明标签才能显示了。
新注册的用户，必须被管理员编辑一次才能使用了。

**Comment by ssrpanel** [comment]
@sanboukarasu 是的，这样就方便哪些维护特定人群，某些人不给看某些节点，某些人给看

**Comment by ssrpanel** [comment]
还需要完善一下。过年后把
