### ISSUE TITLE
更新到d9f5827后 系统设置出错

### ISSUE THREAD

**Issue by handuck1984** [ssrpanel/SSRPanel#274]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
(2/2) ErrorException
Undefined variable: is_forbid_robot (View: /www/wwwroot/ssrpanel/resources/views/admin/system.blade.php)

**Comment by ZBrettonYe** [comment]
数据库少了一项 is_forbid_robot， 去更新一下数据库
