### ISSUE TITLE
标签管理的一些建议和业务逻辑上的提议

### ISSUE THREAD

**Issue by LYJSPEEDX** [ssrpanel/SSRPanel#275]
# 关于标签管理的一些建议和业务逻辑上的提议

## 引入and问题发现

在近日更新中，ssrpanel更新了标签管理机制，这无疑是ssr自动化管理上的一大创新，使站长对ssr的自动化管理更加灵活，但在使用中，我发现了以下问题：
1、**新**用户本身无标签，即无法取得任何节点。这使站长的**试用**机制，必须通过手动给用户加如“免费体验”的标签，才可启用。
2、用户无法通过购买商品等手段，**自己**提高身份，取得更多节点。这使得用户购买套餐后，站长必须手动给用户更改权限，来给用户**新的节点**使用；这使得面板的自主购买功能只适用于**单节点**

## 为什么要解决

以上问题，我予以以下总结：
①号问题：更新标签管理系统后，站长必须手动给每个新旧用户增加标签，用户才可正常使用面板，这与ssrpanel的发展息息相关，希望胖虎尽快看一下~
②号问题：该问题则是针对单用户，多节点时的自动化管理，希望日后完善

## 解决方案
对于刚刚问题，我想提出以下解决方案，可供采纳，**在最下面，我给出了标签管理下，较为全面折中的业务逻辑解决方案**：
新的标签功能可以叠加使用，这给ssrpanel的灵活使用给予了很大的发展空间
①：加入“默认标签”这一功能，即新用户一注册，即可获得默认节点
②：完善商品功能，加入购买商品时，给用户加某标签以及天数（变更身份）的功能，与流量包等商品类型**平行**
③：重要：**取消原来的用户、节点分组功能，避免混淆。因为现在的标签管理，已经可以满足绝大自动化管理功能，具体原因，在下面有详解**

---------------------
**在下面，我附上了一副以时间线为核心的业务逻辑图，更容易理解，以下会有解释**
![42860159255449235](https://user-images.githubusercontent.com/26499797/36242618-ef227714-1257-11e8-90b2-a64977bfd077.jpg)

-----------------------
为了减少开发周期，我提议使用**标签管理用户与节点之间的关系，包括时间和流量等**，开一套机制，监视用户下该标签所有节点的时间和流量。
所以，商品下包含两类标签商品：
①限时类  ：时间一够，收回标签，用户不可见该标签节点
 ②限流量类：流量一够，收回标签，用户不可见该标签节点

## 总结
本套标签业务逻辑，兼顾了**多节点管理（一个用户可用多个节点，并可自由选择）**、**多计费方式（时间、流量）管理**，希望胖虎阅读并采纳，共同完善ssrpanel，谢谢！

## 进一步讨论
相信本套方案一定有缺漏之处，本人非常希望与阅读者进行交流，进一步完善ssrpanel，联系方式：
frankjunx@gmail.com
谢谢！

**Comment by 828768** [comment]
我也正想说这事，你有产品经理的风范，😎😎😎

**Comment by 1021435278** [comment]
很欣喜的看到很多人和我一样的想法,这个取消特别重要,否则很容易混淆:
③：重要：取消原来的用户、节点分组功能，避免混淆。因为现在的标签管理，已经可以满足绝大自动化管理功能，具体原因，在下面有详解

另外胖虎的标签功能非常好,在这基础上发展完全很完善.

**Comment by LYJSPEEDX** [comment]
谢谢

**Comment by ssrpanel** [comment]
mark

**Comment by ssrpanel** [comment]
都已实现
