### ISSUE TITLE
用户面板自定义布局

### ISSUE THREAD

**Issue by qq3461269698** [ssrpanel/SSRPanel#279]
我想在用户的面板里自定义一下      《加一个其他的连接地址》
不知道能不能改  或者是改哪个文件？

**Comment by ZBrettonYe** [comment]
可以改

**Comment by qq3461269698** [comment]
可以具体说一下?
就是现在
用户面板主页有
========
流量日志
邀请码
消费记录
========
这三个选项卡
我如果要替换邀请码这个选项卡的名字和对应网址，该去哪里替换？
感觉这个源码不像cms那样。。我都定位不到每一个选项卡的源文件在哪

**Comment by ssrpanel** [comment]
全文搜索关键字，马上就可以找到
