### ISSUE TITLE
控制面板编辑用户可用流量出错。

### ISSUE THREAD

**Issue by lowprofileusername** [ssrpanel/SSRPanel#280]
在控制面板编辑用户可用流量出错. 可用流量为1G时候。是正常的，可用流量编辑为2G时候显示为-2G.可用流量为3G的时候显示为-1G。 编辑为900G的时候显示为0B。只能去数据库里面赋值。另外设置用户注册的时候初始流量为921600 MB也就是900G 也不生效。默认注册用户得到的流量是0B.导致系统自动禁用该用户。我这是朋友自己共享的所以设置流量比较大。
![default](https://user-images.githubusercontent.com/9425810/36350392-1de4fc26-14d2-11e8-8218-39091acfbe9d.PNG)
![3](https://user-images.githubusercontent.com/9425810/36350393-1e23c9f6-14d2-11e8-9b6e-10ea6498b7e1.PNG)
![4](https://user-images.githubusercontent.com/9425810/36350394-1e61da16-14d2-11e8-8101-c87060c5ecaa.PNG)

**Comment by lowprofileusername** [comment]
![425](https://user-images.githubusercontent.com/9425810/36353775-404294bc-1505-11e8-8880-b1ca1d7bfdd3.png)
另外节点域名显示不全，第二个域名是*.*.in的。只显示了*.*.i 漏了个N

**Comment by lowprofileusername** [comment]
请问作者有看到不？

**Comment by ssrpanel** [comment]
@lowprofileusername 
1.问题1无法重现，流量那个我这很正常
2.你电脑屏幕太小，屏幕大点就正常，或者你按“ctrl”  +  “-”，缩小浏览屏幕就看到效果了，这种问题根本不是问题。
