### ISSUE TITLE
添加一个可以关闭标签的功能

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/SSRPanel#282]
标签这功能就是 等级的一个升级版本；可以我已经按照等级对业务做了调整了，结果标签出来了；搞的我300多个账号都要手动重新调节....；

胖虎桑，首页显示的账号到期 不等于 套餐到期时间，这个问题能修复一下吗？
还有自动充值流量的功能关闭了，还是会自己清理用户的拥有流量

**Comment by ZBrettonYe** [comment]
补充： 就是关闭了自动重置流量， 数据库中user的 traffic rest day 还是会赋值，然后网站还是会在那一天重置流量

**Comment by ssrpanel** [comment]
首页显示的账号到期 不等于 套餐到期时间 什么意思？截图看看？？
关闭了自动重置流量 并不会出现你说的这种情况

**Comment by cdlaimin** [comment]
这问题是因为默认账号新注册的时候是有一段时间的有效期 比如七天
之后购买套餐之后:套餐有效期+七天=总的有效期
而套餐过期后,账户不能用,但是账户有效期还有的

**Comment by ZBrettonYe** [comment]
@ssrpanel 右侧个人信息的 【账号到期】 显示日期没有到期；
但是用户用的套餐到期了（从后台的 用户管理 的消费记录上查的）；

结果： 用户信息上显示 禁用；
这些都很合理；不过由于【账号到期】 与 【套餐到期】时间不同；很多用户会混淆为【账号到期】=【套餐到期】；
然后就是工单/售后 轰炸； 

建议：首页的【账号到期】改为【套餐到期】的时间

**Comment by ssrpanel** [comment]
已经再改进了。

**Comment by ssrpanel** [comment]
注册默认标签已加上
