### ISSUE TITLE
关于Issue #262，配置参数未如预期生效

### ISSUE THREAD

**Issue by cciecm** [ssrpanel/SSRPanel#285]
我把"protocol_param": "#" 所有的"protocol_param": 的都改成1#，但是测试时，同一个账号还是可以在多台设备上接入。

# cat user-config.json
{
    "server": "0.0.0.0",
    "server_ipv6": "::",
    "server_port": 8388,
    "local_address": "127.0.0.1",
    "local_port": 1080,

    "password": "pass",
    "method": "none",
    "protocol": "auth_chain_a",
    "protocol_param": "1#",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",
    "speed_limit_per_con": 0,
    "speed_limit_per_user": 0,

    "additional_ports" : {
        "443": {
            "passwd": "pass",
            "method": "none",
            "protocol": "auth_chain_a",
            "protocol_param": "1#",
            "obfs": "tls1.2_ticket_auth",
            "obfs_param": ""
        }
    },
    "additional_ports_only" : true,
    "timeout": 120,
    "udp_timeout": 60,
    "dns_ipv6": false,
    "connect_verbose_info": 1,
    "redirect": "",
    "fast_open": false
}

原Issue
https://github.com/ssrpanel/SSRPanel/issues/262

**Comment by ssrpanel** [comment]
你再试试，理论上是可以的

**Comment by ssrpanel** [comment]
additional_ports_only 设置成false，

**Comment by cciecm** [comment]
刚才我在另外一台服务器上重做了这个测试，protocol_param都设置成了1#，重启SSR进程。然后在笔记本，手机和iPad上同时连接这一台服务器。三个设备都可以连接。

确认这个方法在单端口多用户模式下不生效。

**Comment by cciecm** [comment]
不行呢

配置如下
# cat user-config.json
{
    "server": "0.0.0.0",
    "server_ipv6": "::",
    "server_port": 8388,
    "local_address": "127.0.0.1",
    "local_port": 1080,

    "password": "24hours",
    "method": "none",
    "protocol": "auth_chain_a",
*    "protocol_param": "1#",*
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",
    "speed_limit_per_con": 0,
    "speed_limit_per_user": 0,

    "additional_ports" : {
        "443": {
            "passwd": "24hours",
            "method": "none",
            "protocol": "auth_chain_a",
*            "protocol_param": "1#",*
            "obfs": "tls1.2_ticket_auth",
            "obfs_param": ""
        }
    },
*    "additional_ports_only" : false,*
    "timeout": 120,
    "udp_timeout": 60,
    "dns_ipv6": false,
    "connect_verbose_info": 1,
    "redirect": "",
    "fast_open": false
}
