### ISSUE TITLE
单端口多用户  混淆参数 生效文件

### ISSUE THREAD

**Issue by 110560** [ssrpanel/SSRPanel#287]
[混淆参数文件.zip](https://github.com/ssrpanel/SSRPanel/files/1757586/default.zip)
但是“group”那个字段我是按自己的需求改的
emmmmm TG杜若言叶
上次给你发过的呀  以为你改过了 尴尬
![qq 20180226154048](https://user-images.githubusercontent.com/32481672/36658434-74550670-1b0b-11e8-9647-5cb38e290ec1.png)

**Comment by ssrpanel** [comment]
你确定这样能生效吗？我没做过实验。这样SSR和所有用户都必须填这个

**Comment by 110560** [comment]
能呀  在用了，另外一个大佬给我的，，，，，“group”那个字段 
你看下，

**Comment by 110560** [comment]
虎哥   套餐的流量重置逻辑，还是麻烦看下，，，我头都炸了，用户购买了也不重置流量，到期也不重置流量，，，，
好了之后给我说下替换哪个文件，

**Comment by ssrpanel** [comment]
@110560 你那个混淆参数是跟ssr后端设置一样的呢还是每个用户设置不一样的？，那个是节点设置的里的值吗？

**Comment by 110560** [comment]
那个是放在节点里面的值，用的单端口多用户，
所有人都获取到这个混淆参数

**Comment by VTLUER** [comment]
后端不用设置，面板节点设置混淆参数，更新订阅推送到客户端自动配置好混淆参数

**Comment by VTLUER** [comment]
如图
![20180306095426](https://user-images.githubusercontent.com/35829269/37010024-6480541a-2124-11e8-9c59-0cdbe1bc37ad.png)

**Comment by VTLUER** [comment]
如图
![20180306095736](https://user-images.githubusercontent.com/35829269/37010101-db0aece4-2124-11e8-9c40-73b7473cf09f.png)

**Comment by ssrpanel** [comment]
等我有空亲自测一遍再上代码

**Comment by ssrpanel** [comment]
已加上
