### ISSUE TITLE
注册时套餐选择

### ISSUE THREAD

**Issue by max2max** [ssrpanel/ssrpanel#29]
作者大大您好，又来提个小需求233
注册时可选套餐，注册成功后状态为pending，等待确认开通
确认开通的条件就随意咯，当然如果对接了支付宝，那就可以无人值守自动购买了
最后先多谢啦！

**Comment by ssrpanel** [comment]
@max2max 这个跟我开发方向不太像啊，注册的时候选了某个套餐。。那要跟注册送多少流量那个配置区分开来了。不过我可以加一下，排进需求，先别close issue

**Comment by ssrpanel** [comment]
这个不开发了。
