### ISSUE TITLE
能否增加中转节点的功能？

### ISSUE THREAD

**Issue by ghost** [ssrpanel/SSRPanel#291]
因为通过部分HK服务器中转到美国的速度快过CN2直连，我在这些节点上配置了iptables。在同一个HK节点上：
80端口：普通单端口多用户，出口即这个HK节点
443端口：利用iptables中转到美国节点，出口在美国节点

由于iptables的配置对面板来说是不可知的，因此，面板无法自动生成443端口的配置信息给用户。这种情况下，用户转移到中转节点的比例不高。

如果面板可以提供在同一节点上做出口和中转到另一台服务器的功能就好了。

**Comment by ssrpanel** [comment]
中转教程方便丢我一份吗？我的iptables貌似一直没有成功过

**Comment by ssrpanel** [comment]
就是你常用的中转方案，稳定且快速的那种，我好研究下

**Comment by cciecm** [comment]
我目前用的中转方案：
香港中转节点（Ubuntu 16.04.4，端口443）--- 美国出口节点（Ubuntu 16.04.4，端口443）
用Ubuntu的原因是iptables策略默认会保存，重启仍然生效。CentOS需要调整策略才能保障重启后iptables仍然生效，但我没成功过。

如果有Ubuntu防火墙，在上面允许routed流量和相关端口
ufw default allow routed
ufw allow 80
ufw allow 443

香港中转节点user-config中单端口多用户部分的配置
    "additional_ports" : {
        "80": {     //普通单端口多用户
            "passwd": "pass",
            "method": "none",
            "protocol": "auth_chain_a",
            "protocol_param": "#",
            "obfs": "tls1.2_ticket_auth",
            "obfs_param": ""
        },
        "443": {     //中转端口
            "passwd": "pass",
            "method": "none",
            "protocol": "auth_chain_a",
            "protocol_param": "#",
            "obfs": "tls1.2_ticket_auth",
            "obfs_param": ""
        }
    },

出口节点user-config中单端口多用户部分的配置
    "additional_ports" : {
        "443": {     //出口节点端口
            "passwd": "pass",
            "method": "none",
            "protocol": "auth_chain_a",
            "protocol_param": "#",
            "obfs": "tls1.2_ticket_auth",
            "obfs_param": ""
        }
    },

在中转节点上手动或者使用脚本配置iptables。我直接用的逗比的脚本
wget -N --no-check-certificate https://softs.fun/Bash/iptables-pf.sh && chmod +x iptables-pf.sh && bash iptables-pf.sh
他写了个教程https://doub.io/wlzy-20，但是用词不太规范。在他的教程里，被转发服务器 = 出口节点

按照脚本指示，先选择1. 安装 iptables，然后选择4. 添加 iptables 端口转发，依次输入：
出口节点端口，这里是443
出口节点IP地址
中转节点端口，这里是443
中转节点IP地址（如果是私网地址，填私网地址）
最后选择转发协议类型： 1. TCP 2. UDP 3. TCP+UDP

部署完成后，用户的客户端上配置的是香港中转节点IP+443端口，实际连接到出口节点的443端口。中转节点上不会产生有关443端口的SSR日志。

**Comment by ssrpanel** [comment]
@cciecm 用iptables 转发流量，单端口多用户你能正常跑吗？

**Comment by cciecm** [comment]
@ssrpanel 你检查一下/etc/sysctl.conf文件里面有没有配置net.ipv4.ip_forward=1
配置后用命令sysctl net.ipv4.ip_forward检查一下ip forwarding有没有开启，返回值应该是
net.ipv4.ip_forward = 1
```
# sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1
```
我发现有些VPS默认没开这个功能。逗比的脚本似乎没检查这个。
http://www.microhowto.info/howto/enable_forwarding_of_ipv4_packets.html

**Comment by Joyace** [comment]
[https://imgurl.org/temp/1805/42e44f79e9b5ce87.png](url)
iptables -t filter -A INPUT -p tcp -m state --state NEW -m tcp --dport 2333 -j ACCEPT
iptables -t nat -A PREROUTING -p tcp -m tcp --dport 2333 -j DNAT --to-destination 54.39.***.***:2333
iptables -t nat -A POSTROUTING -d 54.39.***.***/32 -p tcp -m tcp --dport 2333 -j SNAT --to-source 173.82.***.***

**Comment by Andyanna** [comment]
不错

**Comment by redtechma** [comment]
> 因为通过部分HK服务器中转到美国的速度快过CN2直连，我在这些节点上配置了iptables。在同一个HK节点上：
> 80端口：普通单端口多用户，出口即这个HK节点
> 443端口：利用iptables中转到美国节点，出口在美国节点
> 
> 由于iptables的配置对面板来说是不可知的，因此，面板无法自动生成443端口的配置信息给用户。这种情况下，用户转移到中转节点的比例不高。
> 
> 如果面板可以提供在同一节点上做出口和中转到另一台服务器的功能就好了。

你好 请问中转时你的面板是如何设置单端口的一个节点可以填入多个单端口吗？不是只有一个node 面板必须填中转节点信息 又没办法像v3那样单端口单节点？

**Comment by jiangjiang5733** [comment]
> 我目前用的中转方案：
> 香港中转节点（Ubuntu 16.04.4，端口443）--- 美国出口节点（Ubuntu 16.04.4，端口443）
> 用Ubuntu的原因是iptables策略默认会保存，重启仍然生效。CentOS需要调整策略才能保障重启后iptables仍然生效，但我没成功过。
> 
> 如果有Ubuntu防火墙，在上面允许routed流量和相关端口
> ufw default allow routed
> ufw allow 80
> ufw allow 443
> 
> 香港中转节点user-config中单端口多用户部分的配置
> "additional_ports" : {
> "80": { //普通单端口多用户
> "passwd": "pass",
> "method": "none",
> "protocol": "auth_chain_a",
> "protocol_param": "#",
> "obfs": "tls1.2_ticket_auth",
> "obfs_param": ""
> },
> "443": { //中转端口
> "passwd": "pass",
> "method": "none",
> "protocol": "auth_chain_a",
> "protocol_param": "#",
> "obfs": "tls1.2_ticket_auth",
> "obfs_param": ""
> }
> },
> 
> 出口节点user-config中单端口多用户部分的配置
> "additional_ports" : {
> "443": { //出口节点端口
> "passwd": "pass",
> "method": "none",
> "protocol": "auth_chain_a",
> "protocol_param": "#",
> "obfs": "tls1.2_ticket_auth",
> "obfs_param": ""
> }
> },
> 
> 在中转节点上手动或者使用脚本配置iptables。我直接用的逗比的脚本
> wget -N --no-check-certificate https://softs.fun/Bash/iptables-pf.sh && chmod +x iptables-pf.sh && bash iptables-pf.sh
> 他写了个教程[https://doub.io/wlzy-20，但是用词不太规范。在他的教程里，被转发服务器](https://doub.io/wlzy-20%EF%BC%8C%E4%BD%86%E6%98%AF%E7%94%A8%E8%AF%8D%E4%B8%8D%E5%A4%AA%E8%A7%84%E8%8C%83%E3%80%82%E5%9C%A8%E4%BB%96%E7%9A%84%E6%95%99%E7%A8%8B%E9%87%8C%EF%BC%8C%E8%A2%AB%E8%BD%AC%E5%8F%91%E6%9C%8D%E5%8A%A1%E5%99%A8) = 出口节点
> 
> 按照脚本指示，先选择1. 安装 iptables，然后选择4. 添加 iptables 端口转发，依次输入：
> 出口节点端口，这里是443
> 出口节点IP地址
> 中转节点端口，这里是443
> 中转节点IP地址（如果是私网地址，填私网地址）
> 最后选择转发协议类型： 1. TCP 2. UDP 3. TCP+UDP
> 
> 部署完成后，用户的客户端上配置的是香港中转节点IP+443端口，实际连接到出口节点的443端口。中转节点上不会产生有关443端口的SSR日志。

大佬你好，可否贴两份中转节点的usermysql.json?搞了几天中转，一直没成功...

**Comment by ssrpanel** [comment]
已加入

**Comment by ssrpanel** [comment]
使用的haproxy
