### ISSUE TITLE
登陆出现错误

### ISSUE THREAD

**Issue by longyup** [ssrpanel/SSRPanel#296]
注册后登陆提示 

(2/2) QueryException
SQLSTATE[42000]: Syntax error or access violation: 1055 'ssrpanel.ss_node.name' isn't in GROUP BY (SQL: select * from `ss_node` left join `ss_node_label` on `ss_node`.`id` = `ss_node_label`.`node_id` where 0 = 1 and `ss_node`.`status` = 1 group by `ss_node`.`id`)
管理员账号可以登录

**Comment by longyup** [comment]
感觉是要从ss_node ss_node_label等数据库表获取  然后这两张表并没有东西

**Comment by longyup** [comment]
按#273貌似也是一样，我对用户加了几个默认就有的标签  仍然无法登陆【是因为我没有添加节点的影响吗】

**Comment by ssrpanel** [comment]
where 0=1这个是怎么出现的！好神奇！完整截图看下？

**Comment by longyup** [comment]
![image](https://user-images.githubusercontent.com/35375865/36957306-715c41a0-206e-11e8-97e9-f4a33fdc8355.png)

**Comment by longyup** [comment]
![_meitu_0](https://user-images.githubusercontent.com/35375865/36957598-5c17f774-2070-11e8-89c2-bbeba6238781.jpg)

**Comment by ssrpanel** [comment]
你漏了ss_node表的name字段了。。

**Comment by longyup** [comment]
我是直接导入目录下的数据库来着

**Comment by longyup** [comment]
找到问题了  我按Leo Chu的安装记录  其中database的strict为true我便改了  翻了更新记录发现改为了false【允悲】
