### ISSUE TITLE
增加标签后新用户注册无法看到节点

### ISSUE THREAD

**Issue by yangzhili66** [ssrpanel/SSRPanel#297]
增加标签后新注册用户无法看到节点，如何解决？

**Comment by yangzhili66** [comment]
原有用户也无法看到节点了

**Comment by ssrpanel** [comment]
需要手动一个个给用户打标签。。。

**Comment by yangzhili66** [comment]
@ssrpanel 如果这样 用户注册是不可预知的 用户不能及时看到节点信息

**Comment by qq3461269698** [comment]
有没有办法 在用户注册的时候给他们预设一个标签？

**Comment by 1021435278** [comment]
建议针对用户增加个默认标签， 这样可以随时把任一节点添加到这个默认标签作为默认节点即可。

**Comment by ssrpanel** [comment]
@1021435278 @qq3461269698 好的，我再改进一下，给一个默认不能删除的标签，然后添加用户和节点都会自动生成一个这个默认标签，但是节点可以删除掉这个标签

**Comment by LoadingZhang** [comment]
+1 望修复，现在没有打标签的节点和用户都无法被看到

**Comment by slobber** [comment]
#325

**Comment by yangzhili66** [comment]
@ssrpanel 建议在用户在激活的时候标签表增加关联默认标签，好多用户注册以后 都没激活 如果默认注册就增加标签 标签表数据冗余了

**Comment by cciecm** [comment]
这个标签功能作用不大啊。新用户注册后看到没节点就不用了。

**Comment by cciecm** [comment]
没有事先沟通就注册的用户，看不到节点就再也联系不上了。发邮件不回复，可能被丢到spam了。所有的都是这样。发展新客户的时间成本变的很高，必须事先聊过。

**Comment by 828768** [comment]
@ssrpanel 改成节点和用户默认都无标签吧，无标签的节点可以被默认用户看到，除非节点加了标签才分给相同标签的用户看。
所以要给默认用户看的节点不加标签就好了

**Comment by ssrpanel** [comment]
@828768 @yangzhili66 @qq3461269698 @1021435278 @LoadingZhang @slobber 
感谢 @slobber 提了代码，我已merge ，大家使用的时候要导入 sql/update/20180321.sql 到数据库
