### ISSUE TITLE
注册激活出错

### ISSUE THREAD

**Issue by VTLUER** [ssrpanel/SSRPanel#298]
致命的投掷能力错误
![20180305164551](https://user-images.githubusercontent.com/35829269/36965578-06e06abe-2095-11e8-8ecc-1b100fe5f9b4.png)
![20180305164627](https://user-images.githubusercontent.com/35829269/36965582-0cd0edd6-2095-11e8-80d2-9ee5be60ee29.png)
![20180305164649](https://user-images.githubusercontent.com/35829269/36965586-10232012-2095-11e8-95a4-ab098507c012.png)
![20180305164736](https://user-images.githubusercontent.com/35829269/36965594-16ca2528-2095-11e8-9072-dfd7fcbbb1c6.png)
![20180305164754](https://user-images.githubusercontent.com/35829269/36965601-1b40d4ee-2095-11e8-836f-26ceb6b63915.png)

**Comment by VTLUER** [comment]
看了关闭的问题和wiki也没有类似相关问题，面板是4/3安装，注册功能没问题，开邮件激活功能注册出现错误

**Comment by ssrpanel** [comment]
执行一遍 php composer.phar install

**Comment by VTLUER** [comment]
依赖也执行过，面板直接报错，执行全部命令及设置文件权限才恢复，注册激活并不能得到解决

**Comment by VTLUER** [comment]
以往的sql也刷了一遍，没有漏的;现重装Panel试下; 
mailgun如何配置？
![20180305204658](https://user-images.githubusercontent.com/35829269/37009320-5b7392f4-2121-11e8-8436-af2e59605665.png)
不管怎么配置，面板都出错
