### ISSUE TITLE
有没有办法限制同一个账号的设备同时登录数？

### ISSUE THREAD

**Issue by qq3461269698** [ssrpanel/SSRPanel#299]
最近好像发现有人得到二维码后分享给了很多人，。。好像还有的拿去卖
有没有办法限制同一个账号的设备同时登录数？

**Comment by ssrpanel** [comment]
翻一下wiki，wiki里有，修改每个节点的
protocol 为 auth_chain_a
然后 把 protocol_param 设置为某个值，比如3 最多就只能3个设备连接
用户的 协议必须是auth_chain_a
