### ISSUE TITLE
两台设备之间的问题

### ISSUE THREAD

**Issue by DukeChina** [ssrpanel/ssrpanel#3]
一台纯后端设备连前端设备，可以连接，但是流量记录不更新，前端设备上部署的后端能正常更新流量记录？请问是我配置有问题还是什么情况

**Comment by ssrpanel** [comment]
@DukeChina 先到面板的节点管理里添加好一个节点的地址，然后它有一个ID，在对应的节点的SSR服务端 的usermysql.json的node_id要填上这个ID

[root@ss shadowsocksr]# cat usermysql.json 
{
    "host": "104.2xx.xx.xxx",
    "port": 3306,
    "user": "ssrpanel",
    "password": "ssrpanel",
    "db": "ssrpanel",
    "node_id": 5,              <------这个
    "transfer_mul": 1.0,
    "ssl_enable": 0,
    "ssl_ca": "",
    "ssl_cert": "",
    "ssl_key": ""
}
