### ISSUE TITLE
几点建议，谢谢！

### ISSUE THREAD

**Issue by leonis999** [ssrpanel/ssrpanel#30]
最近代码更新很快，修复了不少问题，赞一个！有几点建议：

1、登陆后首页可用流量最好有个数值的直接显示，现在是鼠标移到那里才有提示，但手机端就没法直观看到了；

2、后台通用设置里面的加密、协议、混淆改了默认值似乎不起作用；

3、推广返利后台能否关闭，个人自用的时候不需要这个；

4、增加常用手机端、电脑端的客户端软件下载链接，方便新手使用，类似http://www.ehcozone.club/ssclient/    这样的；

5、自定义端口似乎只有管理员可用，普通用户没法用；

6、建议可以设置新注册用户的赠送流量以及有效期；

7、管理后台中账号列表只能看到每个账号已消耗流量，看不到总流量和剩余流量；

**Comment by ssrpanel** [comment]
@leonis999 
1.改进了
2.哪里不起作用，你怎么操作的
3.开关已加
4.下载那个我准备放到文章系统里，你们自己定义，以后更新吧
5.普通用户为什么要给他们自定义端口，你的服务器运维会非常蛋疼的
6.已改
7.已改
