### ISSUE TITLE
这要是支持v2ray自动设置用户uuid那就非常牛逼了

### ISSUE THREAD

**Issue by zllikey** [ssrpanel/SSRPanel#300]
v2ray已经开放api，V2Ray 中可以开放一些 API 以便远程调用。这些 API 都基于 gRPC
参考文档
https://www.v2ray.com/chapter_02/api.html

https://medium.com/@TachyonDevel/%E8%B0%83%E7%94%A8-v2ray-%E6%8F%90%E4%BE%9B%E7%9A%84-api-%E6%8E%A5%E5%8F%A3%E8%BF%9B%E8%A1%8C%E7%94%A8%E6%88%B7%E5%A2%9E%E5%88%A0%E6%93%8D%E4%BD%9C-adf9ff972973

**Comment by zllikey** [comment]
使用 v2ray 的 WebSocket+TLS+Web 协议可以防止防火墙根据特征进行封杀ip
WebSocket+TLS+Web 能同时在运行着https网站的服务器上公用一个端口，流量经过web服务器加证书tls进行混淆，从而数据被洗白，也无任何特征，因为https无法被破解，服务器也没有其他开放端口能被检测，因此现阶段可以说非常安全，建议集成,v2ray可以配置多个用户，但是缺憾没有流量监控
参考配置网址
https://toutyrater.github.io/advanced/wss_and_web.html

**Comment by ssrpanel** [comment]
@zllikey 感谢推荐，还有没有，这个我先研究看看

**Comment by zllikey** [comment]
我自己搭得v2使用确实比ss稳很多，但是对api我还是只在观望中，因此官方对此也比较少信息，然而v2已经发展了两年多，估计也是限制了一部分人对v2进行特别用途所以api文档比较少
https://steemit.com/cn/@v2ray/4lnvvz-v2ray
https://cnsteem.com/cn/@v2ray/meemg-v2ray
https://lighti.me/3165.html

**Comment by LoadingZhang** [comment]
SS(R)早就能被精确识别了，如果面板只能支持SS(R)，等到墙决定发力的那天，这个面板也就失去了意义。建议增加V2RAY的支持。

**Comment by ssrpanel** [comment]
@LoadingZhang  我要加了v2ray了，请问你要捐赠我多少钱？墙发力那天面板失去意义，大家都没得用了，有技术会捣鼓的人还是可以继续用了，只是小白们苦了，所以我不愁的

**Comment by LoadingZhang** [comment]
不好意思，我没有在使用您的项目，只是提个建议。
而且公开要捐赠的行为我觉得不太合适。

**Comment by ssrpanel** [comment]
@LoadingZhang 你用都没用来提什么狗屁意见？我爱加什么功能跟你有半毛钱关系？

**Comment by ssrpanel** [comment]
你提需求，我任务你是在要求我做东西，既然你敢要求我做东西，那我为什么不能向你要钱？我不觉得有毛病，我一个开源项目，你要是会你开发你可以自己去改，不会就别瞎比比

**Comment by ssrpanel** [comment]
你心虚什么？发了还删除？

**Comment by zllikey** [comment]
不好意思，需求是我提的，但是现在情况有变，请不要增加v2ray，真的不要，的不要，不要，不，我还想继续稳定用下去

**Comment by cmmdwl** [comment]
这要是真做了，gfw就难受了，用tls加密 要么白名单，要么全放过

**Comment by ssrpanel** [comment]
v2ray 群里的 @tonychan已经做了，并且提交代码了，需要我研究一番再完整合并进面板，然后再放出教程

**Comment by cmmdwl** [comment]
给v2打一个卡，顺便催促一下胖虎

**Comment by ssrpanel** [comment]
已经在加

**Comment by ssrpanel** [comment]
已加上v2ray，教程也上到wiki里了 @zllikey
