### ISSUE TITLE
HTTPS 问题

### ISSUE THREAD

**Issue by donaldcox2** [ssrpanel/SSRPanel#306]
翻过 WIKI 和 Issues 了，没看到有相关的。

若启用 HTTPS，浏览器会提示不安全，主要是图片引用变成了http，有 favicon，国家图标，验证码等。

**Comment by lowprofileusername** [comment]
你怎么开启的HTTPS,
我这是正常的
https://xxx/assets/images/country/xx.png

**Comment by ssrpanel** [comment]
@donaldcox2 截图我看下？

**Comment by donaldcox2** [comment]
@ssrpanel ![2](https://user-images.githubusercontent.com/27288090/37199337-4a8317ce-23bc-11e8-9669-dfeeac3f68b3.png)

**Comment by ssrpanel** [comment]
没有这个问题。。。无法重现

**Comment by LYJSPEEDX** [comment]
web服务器配置问题
