### ISSUE TITLE
用十一的一键安装后，也与#269的问题一样.user出现404错误

### ISSUE THREAD

**Issue by JMVoid** [ssrpanel/SSRPanel#307]
我用十一的一键搭建后。admin面板全部的功能没有问题。但是用注册新用户后，用一般用户登录，跳转 http://domainname/user 就会有404页面错误。因为我对于php没经验，试过想打开php-fpm的错误日志。但是什么都没有任何纪录。请问怎么入手解决问题？多谢了

**Comment by longyup** [comment]
看看config中database的strict是否为false？

**Comment by JMVoid** [comment]
问题解决。将config中的database.php->mysql-> strict 设为false就可以了
