### ISSUE TITLE
基于有赞云的个人收款即时到账

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#309]
胖虎，感觉你wiki里的那个收款不是很靠谱，做个这个吧：[基于有赞云的个人收款即时到帐实现方案](https://zhuanlan.zhihu.com/p/31783511) ，1%的交易费不算贵，公司大点靠谱

**Comment by ssrpanel** [comment]
感谢分享，我研究下

**Comment by ssrpanel** [comment]
给你打CALL，很不错

**Comment by yangzhili66** [comment]
支持 这块要接入很方便了

**Comment by qq3461269698** [comment]
https://codepay.fateqq.com也可以看看这个怎么样，直接到自己的支付宝 缺点就是 好像微信是要钱的

**Comment by 828768** [comment]
@qq3461269698 都要钱的，人家提供给你通道总要图点啥。
有一种不要钱的方案就是用付款尾数去区分，后台有个程序一直在扫支付宝账单或者消息通知，匹配尾数额度就认为是对应的订单

**Comment by ssrpanel** [comment]
这个我已经再做了，我个人页有需求

**Comment by ssrpanel** [comment]
开发中

**Comment by ssrpanel** [comment]
赶紧的，捐赠码在首页，你看着办，有赞云支付做出来了。@828768

**Comment by ssrpanel** [comment]
代码已更新，导入 sql/update/20180313.sql到数据库，然后再ssrpanel里执行 php composer.phar install 安装有赞的sdk

**Comment by 828768** [comment]
给力，已给你转五百万，早日迎娶白富美，然后接着好好干活！
