### ISSUE TITLE
BUG reports

### ISSUE THREAD

**Issue by liboysoft** [ssrpanel/ssrpanel#31]
1. 当user表transfer_enable为0时，app/Http/Controllers/UserController.php line 53报错，分母不为0
2. 购买商品时支付报：[2017-09-21 20:20:19] production.ERROR: 支付订单失败：SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'order_id' cannot be null (SQL: insert into `user_balance_log` (`user_id`, `order_id`, `before`, `after`, `balance`, `desc`, `created_at`) values (1, , 100.00, 70, 30, 购买流量包, 2017-09-21 20:20:19))

**Comment by ssrpanel** [comment]
@liboysoft 1.我修复下
2.账号估计已经过期了

**Comment by ssrpanel** [comment]
@liboysoft 查证后确实是BUG，谢谢反馈，已修复，等待代码更新

**Comment by liboysoft** [comment]
@ssrpanel 
2. 的话原因应该是 app/Http/Controllers/UserController.php line 735  $order->id 取不到值，应该是$order->orderId 吧，然后第二个user_balance_log表的 orderId 字段是int(11) 与 order 表定义的 varchar(20) 不一致

**Comment by liboysoft** [comment]
@ssrpanel 另外我发现购买流量包写入的时候没有将GiB转换成字节写入，还有就是购买完账户信息发生改变是否应该刷新用户信息session比较好，不然得重新登陆才看得见。谢谢！
