### ISSUE TITLE
后台管理员添加用户时无状态字段

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#311]
管理员在后台主动添加用户时，无用户状态那个字段界面，需要保存后再去编辑才有。
建议改进：
1、提供该字段设置入口，让管理员可以在新建用户时就一步更改用户状态
2、如果不想由管理员激活，那么新建用户后触发激活邮件通知，并将该用户账号连同密码明文一起发送，第一次登录时要求强制更改密码

**Comment by ssrpanel** [comment]
@828768 你为何会有这种需求？手动开账号？？？

**Comment by 828768** [comment]
@ssrpanel 是啊，这不也是你已经做了的功能么？

**Comment by ssrpanel** [comment]
@828768 草，可以啊，niubility

**Comment by 828768** [comment]
@ssrpanel 关键是胖虎你做不做啊\(^o^)/~，包括用户和节点的标签，分组，级别之间的关系

**Comment by ssrpanel** [comment]
@828768 没钱做个毛，有空心情好再搞吧

**Comment by 828768** [comment]
@ssrpanel 早点做完才有空出去找女朋友，要不然你找女朋友都会心不在焉

**Comment by ssrpanel** [comment]
@828768 没钱找个毛女朋友？？？

**Comment by 1021435278** [comment]
以前我们刚工作时候有屁钱啊,还不是一拍即可,对上眼即可.

给你个忠告,如果你没钱,找个有钱的女朋友不就解决问题了吗?

**Comment by 1021435278** [comment]
现在管理员手动增加用户根本增加不了.

**Comment by ssrpanel** [comment]
@1021435278 可以增加，怎么会增加不了。？？？是不是你没有更新到最新
