### ISSUE TITLE
订阅的长度

### ISSUE THREAD

**Issue by RomeoJBY** [ssrpanel/SSRPanel#314]
她们告诉我，喜欢long long的订阅的链接，Too short不喜欢，Too short的订阅链接容易被破解，简直是三秒射，受够了，建议修改下生成订阅链接的长度,首先感谢胖虎；没有扫码的扫下码，给予胖虎洞力

**Comment by ssrpanel** [comment]
我就是故意要把长度缩短的，以前是18位，现在改成5位，强制识别大小写的，所以破解这种东西，还是算了把

**Comment by ssrpanel** [comment]
即便能破解，用户去订阅界面手动点一下更换地址就可以换一个了

**Comment by ssrpanel** [comment]
扫码什么？打赏么？？根本不指望使用我这个面板的人会给我打赏。。
