### ISSUE TITLE
增加修改用户默认配置

### ISSUE THREAD

**Issue by lslzl3000** [ssrpanel/SSRPanel#316]
目前好像没有用户默认配置的选项，希望增加修改默认用户配置
1. 默认标签【作者可能正在做】
2. 账户有效期
3. 可用流量
4. 单链接限速 & 单用户限速

**Comment by lslzl3000** [comment]
另外，希望用户的限速可以联动套餐/等级/标签
e.g. 通过购买高级套餐 -> 自动改等级/标签 -> 获得更高的限速

**Comment by ssrpanel** [comment]
@lslzl3000 
1.默认标签在做了，主要是日常工作比较忙，一直拖着
2.账户有效期 杜言若叶 也有反馈过，要再跟商品那块重新构思一下
3.可用流量？？？后台自己改，注册时默认流量就是初始流量了
4.单链接和单用户不会放出来的，商业价值比较大
