### ISSUE TITLE
流量用超了后台状态不会变更为禁用

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#317]
某用户流量用超了，实际上他的端口也停止服务器了，但后台界面上仍然显示正常状态，并不会置为禁用
![image](https://user-images.githubusercontent.com/6386202/37349641-d82d3d86-2711-11e8-8b64-ccc275f29212.png)

**Comment by ssrpanel** [comment]
你定时任务没跑把

**Comment by 828768** [comment]
真的没自动跑，手动执行没问题。系统任务奇怪没法执行，768M的机子，难道有关系？
