### ISSUE TITLE
关于订阅长度的问题#314

### ISSUE THREAD

**Issue by RomeoJBY** [ssrpanel/SSRPanel#319]
订阅链接可以更改，这点不错，有效防止盗用，但只能在windows设置自动更新下有效，不自动更新，节点还是在，还能用；安卓端不手动更新，不会变更，节点还在，能用；用户少没问题，多用户不建议，多用户几把能破
so现在个人想把订阅码生成长度改长点，建议全部修改或告诉修改位置，自己修改；无论如何，首先常感谢胖虎

**Comment by ssrpanel** [comment]
@RomeoJBY 这个问题不是问题，如果订阅地址泄露，并且手动更换了，密码自己改一下就行了。马上就全部都用不了了
