### ISSUE TITLE
重装最新的，系统设置打不开

### ISSUE THREAD

**Issue by xiaoanweiwu** [ssrpanel/ssrpanel#32]
![ff547048-67ba-44d7-9297-bf4eafce318d](https://user-images.githubusercontent.com/28782855/30731121-0674679c-9f9e-11e7-9c4a-cda1ac875238.png)

**Comment by ssrpanel** [comment]
@xiaoanweiwu 查看sql下的db.sql，找到`config` 部分，然后把你的数据库里的config表删除，重新建表和insert那一堆的配置
