### ISSUE TITLE
发表文章不能添加图片

### ISSUE THREAD

**Issue by 514454786** [ssrpanel/SSRPanel#321]
在文章发表的输入框内，点击添加图片，然后点开始上传，出现“目录创建失败”的字样。不知道这是怎么回事，麻烦作者看一看。使用你的面板两三天了，功能非常好，如果能够添加购买商品后自动给用户贴上标签的功能更佳。已赞助你，加油！

**Comment by 828768** [comment]
没给权限

**Comment by 514454786** [comment]
请问如何给这个权限。

**Comment by ssrpanel** [comment]
自己百度
