### ISSUE TITLE
回复#319

### ISSUE THREAD

**Issue by RomeoJBY** [ssrpanel/SSRPanel#323]
就订阅哪几个字母，想几下能破，面板更改订阅，在安卓端不手动更新不凑效，节点信息依然还在，还能用，windows不设置自动更新也不凑效；现在只想改变生成订阅的长度，告诉下位置，自行更改，谢谢

**Comment by ssrpanel** [comment]
你这强迫症。跟你说了，改了订阅地址之后再把密码改一下，分分钟用不了
代码位于 /app/Http/Controllers/Controller.php   makeSubscribeCode 方法 中         $code = makeRandStr(5); 把5改大一点。就生成的长一些

**Comment by RomeoJBY** [comment]
@ssrpanel 用户需要，自己用无所谓；” $code = makeRandStr(5)“这个地方修改过，面版报错
