### ISSUE TITLE
更新面板,购买商品报错

### ISSUE THREAD

**Issue by RomeoJBY** [ssrpanel/SSRPanel#326]
![1](https://user-images.githubusercontent.com/35829269/37518554-8f758bb6-2950-11e8-83b0-c791448c4884.PNG)
![2](https://user-images.githubusercontent.com/35829269/37518560-935cce4c-2950-11e8-8347-def01332772d.PNG)

**Comment by RomeoJBY** [comment]
执行 php composer.phar install 也解决不了

**Comment by 514454786** [comment]
同样的问题，更新后不能购买商品

**Comment by ssrpanel** [comment]
我草，导入 sql/update/ 最后一个sql到数据库啊。你们都不看更新记录的吗？

**Comment by RomeoJBY** [comment]
导入最后一个sql也没用，另外装一个面板test也不行

**Comment by 514454786** [comment]
我表示按照胖虎的方法，把20180305.sql导入到数据库中。浏览器清除缓存，依旧购买错误

**Comment by 514454786** [comment]
楼主兄弟，我不知道你怎么办了，我备份网站了，覆盖就处理好了，坐等胖虎修复。

**Comment by LoadingZhang** [comment]
+1

**Comment by ssrpanel** [comment]
我日，我忘记提了，，，不是20180305.。。。哈哈哈啊哈尴尬了

**Comment by ssrpanel** [comment]
来吧，come on baby 们，提代码了，上有赞云支付了。赶紧测试一波。

**Comment by SRCOL** [comment]
我也遇到了，购买商品出错，我的不是报错，而是直接404。。。emmm

**Comment by 514454786** [comment]
胖虎已修复这个问题，同时加入了有赞云支付，感觉作者在用心做这个，继续赞助一波，虽然不多，聊表心意。

**Comment by ssrpanel** [comment]
已修复，已更新，已加入有赞云支付
