### ISSUE TITLE
节点账号信息如何重置

### ISSUE THREAD

**Issue by saszr** [ssrpanel/SSRPanel#327]
原来建了一个节点，别人有了这个节点配置可以连接。
现在我改标签，别人是看不见了，但是他有原来的节点配置。
我还要用这个节点，不可以停用。
只是想单单停掉别人连接这个节点。   （禁端口有点麻烦哈）
  -----------
想了想  应该不可以实现吧   就算我管理中心改密码端口，别人通过知道已有的节点 又知道改了标签消失的节点地址也可以改了连接上吧
 
改标签不显示节点，其实只是屏蔽了配置而已，后台还是一样端口密码的

所以说 还是直接屏蔽节点端口？

**Comment by ssrpanel** [comment]
直接个人设置里，改掉SSR的密码
