### ISSUE TITLE
是否支持按量计费呢？

### ISSUE THREAD

**Issue by nishuo** [ssrpanel/SSRPanel#328]
例如购买30G流量，用完为止,可以设置单G流量的价格。
如果作者愿意开发，我愿意支付一定的费用

**Comment by lslzl3000** [comment]
流量包不是可以吗？

**Comment by ssrpanel** [comment]
@nishuo 已经有了，你搭建起来就会发现很好很强大。来吧，捐赠码在首页，自己看着办吧
