### ISSUE TITLE
节点获取和显示顺序问题

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#329]
文档说：
1. 节点显示按排序值来的 - 可实际上是按节点ID来的 #125 
![image](https://user-images.githubusercontent.com/6386202/37557063-d434183c-2a39-11e8-82fd-a17636c4d39e.png)

2. 订阅节点按设定的个数随机获取 - 实际上也是按节点ID来的
![image](https://user-images.githubusercontent.com/6386202/37557071-04a8c594-2a3a-11e8-9a23-468b6a66f600.png)
![image](https://user-images.githubusercontent.com/6386202/37557080-2ece756c-2a3a-11e8-8be5-573c8bf11ee3.png)

**Comment by ssrpanel** [comment]
妈啦，观察的真仔细

**Comment by ogays** [comment]
老铁，这个流量统计怎么没显示啊，求解决方法
![qq 20180407174344](https://user-images.githubusercontent.com/32096394/38453624-52c68dd6-3a8b-11e8-8cf1-604a18344459.png)

**Comment by 828768** [comment]
@ogays 系统定时任务应该没执行，[可以参考这个](https://sobaigu.com/linux-schedule-donot-run-with-crond.html)

**Comment by ssrpanel** [comment]
@828768 你tg号多少，我拉你进群

**Comment by 828768** [comment]
@ssrpanel `sobaigu`  这是要被翻牌宠幸？

**Comment by ssrpanel** [comment]
已修复，等待提交
