### ISSUE TITLE
系统设置报错

### ISSUE THREAD

**Issue by 64611187** [ssrpanel/ssrpanel#33]
![41 74m _b352xtu9 1cv 4](https://user-images.githubusercontent.com/18624659/30768715-e16e3008-a03e-11e7-9d9f-3285c0849436.png)
求帮助

**Comment by cheapssr** [comment]
图片咋上传呢，，我找不到上传图片的按钮。。。

**Comment by liboysoft** [comment]
@cheapssr 这是因为最新的sql config表少了一个用户初始流量 **default_traffic** 的记录，可自行插入：
`INSERT INTO `jiasu_men`.`config` (`id`, `name`, `value`) VALUES ('22', 'default_traffic', '0')

`

**Comment by cheapssr** [comment]
@liboysoft 嗯，谢谢告知，，这个是导入的sql有问题，还是我的操作错误呢

**Comment by ssrpanel** [comment]
@64611187 @cheapssr @liboysoft 数据库的sql下的db.sql里的config部分重新删除重新导入
