### ISSUE TITLE
用户无法注册，手动添加用户也失败

### ISSUE THREAD

**Issue by cciecm** [ssrpanel/SSRPanel#331]
自今天起，用户注册会显示404错误。
后台手动添加时，用户名，加密方式，协议，混淆无论填什么值，都会报错。
此服务器3月初新装，只从旧服务器导入了user部分数据库。

排错步骤：
新建了一台服务器（代码最新），从现有服务器导入完整数据库，出现一模一样的问题。
删除数据库ssrpanel，导入初始数据库文件db.sql，phpAdmin有如下报错：
错误
SQL 查询：

-- ----------------------------
-- Table structure for `ss_node`
-- ----------------------------
CREATE TABLE `ss_node` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(128) NOT NULL DEFAULT '' COMMENT '名称',
  `group_id` int(11) NOT NULL DEFAULT '0' COMMENT '所属分组',
  `country_code` char(5) DEFAULT '' COMMENT '国家代码',
  `server` varchar(128) DEFAULT '' COMMENT '服务器域名地址',
  `ip` varchar(30) DEFAULT NULL COMMENT '服务器IP地址',
  `desc` varchar(255) DEFAULT '' COMMENT '节点简单描述',
  `method` varchar(32) NOT NULL DEFAULT 'aes-192-ctr' COMMENT '加密方式',
  `protocol` varchar(128) NOT NULL DEFAULT 'auth_chain_a' COMMENT '协议',
  `protocol_param` varchar(128) DEFAULT '' COMMENT '协议参数',
  `obfs` varchar(128) NOT NULL DEFAULT 'tls1.2_ticket_auth' COMMENT '混淆',
  `obfs_param` varchar(128) DEFAULT '' COMMENT '混淆参数',
  `traffic_rate` float NOT NULL DEFAULT '1' COMMENT '流量比率',
  `bandwidth` int(11) NOT NULL DEFAULT '100' COMMENT '出口带宽，单位M',
  `traffic` bigint(20) NOT NULL DEFAULT '1000' COMMENT '每月可用流[...]

MySQL 返回：

#1046 - No database selected

**Comment by cciecm** [comment]
哦，MySQL报错是因为ssrpanel整个没了。现在db.sql能恢复。不过，导入之前服务器数据库，那个问题还是会出现

**Comment by ssrpanel** [comment]
对比一下你原来那个user表跟最新的db.sql里的字段的差异的字段差异

**Comment by cciecm** [comment]
我来逐条比较…… 工作量略大

**Comment by cciecm** [comment]
额，我把过期的用户在数据库里全部干掉。现在好了。测试了新用户注册和手动添加用户，都能用了。不过问题原因不明。

**Comment by ssrpanel** [comment]
你把storage/logs下最后 17个小时前（应该是昨天的 laravel-2018-03-18.log） 打开看一下错误日志。贴上来我就知道你错哪里了

**Comment by DreamSeekerKaiser** [comment]
我怎么没找到用户注册的入口呢？ 网站进去就是后台管理的登录页面啊～～
