### ISSUE TITLE
多条公告滚动显示

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#332]
现在有多条公告时，只会显示最新那条，而且用户界面没入口去看其他的公告。
建议：
多条公告时，公告栏上下滚动显示有效状态的公告，或者让公告和文章一起显示在文章列表栏。

**Comment by ssrpanel** [comment]
有图吗？画个草图也行。。我也觉得这个公告有点low

**Comment by 828768** [comment]
我也不知道怎么做才显得高大上，也不需要做得多高大上，能公告到位就好。
1. 多条公告滚动显示：多条公告时，现在的公告栏比如5秒上下滚动轮换显示公告标题，建议增加下划线明示这是条链接
2. 公告和文章一起显示：理论上公告和文章都是传达讯息的，现在的文章显示栏完全可以同时显示文章和公告列表，可以在标题前显示类型，比如：
```
【公告】公告公告快来看
【文章】这是篇教程文章
【文章】另一篇文章
```

**Comment by ssrpanel** [comment]
已处理
