### ISSUE TITLE
希望支持仅结算下载流量

### ISSUE THREAD

**Issue by DanielZhang17** [ssrpanel/SSRPanel#334]
如题

**Comment by ssrpanel** [comment]
什么东西？？不是很明白？？什么叫仅结算下载流量？？？这种需求比较少吧。说说场景？

**Comment by DanielZhang17** [comment]
比如有一个节点用的谷歌云，因为谷歌往中国大陆的出口流量是US$0.23/GB 然后上传流量是免费，所以我就想说只结算用户产生的下载流量，不然价格没法降下去，别的VPS提供商也有上下行流量区分定价的操作

**Comment by DanielZhang17** [comment]
本来是想用流量比例来算的，但是那样又不是很合理，所以还是代码实现比较合理一点。另外就是不同节点之间能做到流量不通用或者套餐分别定制吗？这样两个价格差别比较大的节点就不用用流量比例或者多面板来实现了。

**Comment by ssrpanel** [comment]
城里人会玩啊。还分上下流量

**Comment by lm93129** [comment]
谷歌节点并不是上传免费，请不要搞错了，只有极个别的商家才是单向流量的

**Comment by DanielZhang17** [comment]
[https://cloud.google.com/compute/pricing?hl=zh-cn#network](url)
自己看看再说吧
这里写的很清楚的，入站流量免费
然后入站对应的是SSR的用户上传流量

**Comment by ssrpanel** [comment]
@DanielZhang17 等我有空弄一下，这个需求很特别，不过我看了文档，貌似确实有这种操作。。。你果然是老司机

**Comment by ssrpanel** [comment]
还有吗？我最近也碰到这个问题了，10T的流量 用起来才发现 是5G上传 5G下载。。见鬼了。。。求推荐商家

**Comment by 2050545641** [comment]
我的阿里云也是这样，只计费出方向的流量
