### ISSUE TITLE
有赞支付有教程吗？

### ISSUE THREAD

**Issue by 514454786** [ssrpanel/SSRPanel#336]
看到胖虎提供的有赞支付，感觉挺好的，请问有教程吗？开店了，但找不到client_id和client_secret的申请方法。求指导

**Comment by 828768** [comment]
@514454786 #309

**Comment by 514454786** [comment]
@828768 你发的那个教程没看懂，到了后面的什么收款码之类的看不懂，我填写了店铺id，client_id和client_secret但上架商品点击在线支付，没反应了。不知道哪里做错了。

**Comment by 828768** [comment]
@514454786 这也看不懂，那就那就。。。提供付费代搭服务\(^o^)/~

**Comment by ZBrettonYe** [comment]
1. 手机上 下载 [有赞微小店](https://h5.youzan.com/v2/index/wxdpc)；
2. 在手机上配置一个微店 （注册一个账号，开一个小店，身份验证，绑定微信/银行卡等等）；
3. 再到[有赞云](https://console.youzanyun.com/login) 登入账号；
4. 创建一个应用；（选择：自用型，产品类型：有赞微商店，授权绑定刚刚注册的微小店）；
5. 进来有赞云的应用后台，点击左侧列表【应用设置】，右侧界面中可以找到上面有【client_id】【client_secre】，下面基本信息中有【授权店铺ID】；
6. 将3个数字信息输入到SSRPanel后台有赞云设置中；
7. 将设置中的推送网址（h ttp://网站网站/api/yzy）复制；
8. 到 有赞云【应用设置】开发信息中的 点击修改；
9. 打开推送服务，粘贴上刚刚复制的网址，然后将下面的推送内容全部都勾上（字面意思）；
10. 保存；----完成

**Comment by ssrpanel** [comment]
@ZBrettonYe 你有博客网站之类的不，写一个我挂你链接

**Comment by ZBrettonYe** [comment]
@ssrpanel 我不玩博客，就几个字而已，就真要留名的话，就留我Github主页好了

**Comment by 514454786** [comment]
@ZBrettonYe 都按照你的教程设置好了，面板上也复制好了所有数据修改完成，回到商品购买的时候，出现的在线支付，怎么点都没反应，这是什么原因呢？大佬是否有遇到过、？？？？

**Comment by ZBrettonYe** [comment]
@514454786 清理浏览器缓存试试

**Comment by SRCOL** [comment]
先mark为敬！多谢老哥@ZBrettonYe

**Comment by sanboukarasu** [comment]
我也遇到同样的问题了。在线支付，按了没有反应。

**Comment by lslzl3000** [comment]
最新版，配置了有赞，在线支付时 /payment/create 出错

> Class 'Youzan\Open\Token' not found

**Comment by 514454786** [comment]
依旧点击在线支付没响应，我已经按照大大的步骤，做了好几次了，依旧不能实现，有相同情况的小伙伴吗？胖虎大佬能帮忙看看吗？

**Comment by ssrpanel** [comment]
教程

https://github.com/ssrpanel/SSRPanel/wiki/%E6%9C%89%E8%B5%9E%E4%BA%91%E6%94%AF%E4%BB%98
