### ISSUE TITLE
订单管理 的一点BUG

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/SSRPanel#338]
1. 用户可以多次点击在线购买按钮，后台会开N个新的订单；（现在一下，规定时间内可下订单之类的）
2.  订单管理 中 订单状态 除了已支付/未支付，没有已过期；
（希望把已支付改成绿色，未支付改为红色，已过期改为灰色，来突出显示）

顺便价格分类选项之类的吧；
感谢dalao的开发，有赞 支付 很给力

**Comment by ssrpanel** [comment]
我还要加一个60分钟内没付款自动关闭订单

**Comment by ZBrettonYe** [comment]
还有个小细节，节点列表中显示尝试流量 单位为GBG了

**Comment by ssrpanel** [comment]
纳尼

**Comment by ssrpanel** [comment]
已经修正了，更新代码把骚年

**Comment by 828768** [comment]
@ssrpanel 
![image](https://user-images.githubusercontent.com/6386202/37702441-7e76d9e2-2d2d-11e8-84cf-06493472b8c2.png)
测试订单没有支付，最后订单超时关闭，但消费记录里显示有实付，建议支付成功的才写如消费记录
