### ISSUE TITLE
过期用户续费BUG

### ISSUE THREAD

**Issue by yangzhili66** [ssrpanel/SSRPanel#339]
例如用户3月10日过期的 用户购买的套餐是包月31天，应该是在当前时间上加31天吧 不是在3.10加31天 ，望修复

**Comment by SRCOL** [comment]
这个不算Bug，很多计费系统都是这样子算的

**Comment by ssrpanel** [comment]
1.用户3月10号过期，今天是3月1号，此时，请问应该怎么加？当然是加31天了

**Comment by ssrpanel** [comment]
1.用户3月10号过期，今天是3月1号，此时，请问应该怎么加？当然是在3月10号之上再加加31天了，哪有再今天买今天加的

**Comment by yangzhili66** [comment]
@ssrpanel 我的意思是用户过期是3.10 今天是3.20日 用户购买包月套餐应该按照哪个加？

**Comment by SRCOL** [comment]
@yangzhili66按用户过期时间加

**Comment by SRCOL** [comment]
就像@ssrpanel 说的，这种逻辑是合理的，但要是在这基础上加入判断用户是否过期，根据用户是否过期来加时间，这样裆燃是坠吼滴
