### ISSUE TITLE
有赞支付 'Youzan\Open\Token' not found

### ISSUE THREAD

**Issue by lslzl3000** [ssrpanel/SSRPanel#341]
最新版 f383609，已正确配置了有赞各个id，点击[在线支付] /payment/create 回复出错

`Class 'Youzan\Open\Token' not found`

我看issues里也有人遇到了点击[在线支付]没反应，应该都是这个错误，有人知道why？

**Comment by ssrpanel** [comment]
php composer.phar install 执行一次
