### ISSUE TITLE
面板后台显示订单未支付，实际支付成功

### ISSUE THREAD

**Issue by YoungCabbage** [ssrpanel/SSRPanel#343]
### 问题
面板后台显示订单未支付，实际支付成功
  - 使用**有赞云**方式支付套餐，微信端显示支付成功，并且有赞微小店后台收到了金额。
  - 但是在 ssrpanel 面板**用户消费记录**栏显示**待付款**，并且在面板的**订单管理**显示**订单状态为待支付**。

### 支付过程中的提示
1. 收银台支付信息获取失败
2. 支付成功后，订单页面一直不跳转到成功的界面

收银台支付信息获取失败 | 支付成功后，订单页面一直不跳转
------------ | -------------
![](http://image-host.b0.upaiyun.com/Screenshot_20180320-222607.jpg) | ![](http://image-host.b0.upaiyun.com/Screenshot_20180320-222624.jpg)

### 个人判断
&emsp;&emsp;结合以上两个提示，推测是因为推送消息没有送达服务器的问题。
- 检查了有赞云后台推送权限，已经全部打开。推送地址也是自己的网址
- 又或者是因为服务器的端口问题？除了必要端口以外，我封禁了其余所有端口。

&emsp;&emsp;排除下来想不到其他的方法，不知道这是否是个 bug 还是我的设置问题呢。

**Comment by ssrpanel** [comment]
你自己检查把。防火墙？我也不知道。没碰到过

**Comment by xiaoanweiwu** [comment]
昨天没问题  刚刚git pull了下，然后也出现了同样的问题！

**Comment by 828768** [comment]
@ssrpanel 没支付的订单也写入消费记录了
![image](https://user-images.githubusercontent.com/6386202/37702651-35c6bfcc-2d2e-11e8-8a50-95d91ed10f70.png)

**Comment by ssrpanel** [comment]
@828768 大哥啊，不要看这个，今天git抽风提不上代码，看订单管理

**Comment by ssrpanel** [comment]
这个页面我已经废弃了

**Comment by lslzl3000** [comment]
@ssrpanel 同样遇到微信显示‘收银台支付信息获取失败’，不过能支付成功，有读取订单的接口问题？

@YoungCabbage 如果确定配置没错且防火墙端口没问题，那就检查一下你的服务器是不是能从中国大陆正常访问，可能是有赞服务器无法访问你的服务器

**Comment by YoungCabbage** [comment]
@ssrpanel 我重新把 nginx 的错误日志看了一遍，有大量的 `SSL_shutdown() failed (SSL: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init) while SSL handshaking, client: 106.75.30.7, server: 0.0.0.0:443` 报错

谷歌后，根据 openssl 的 github 上的 [issues信息](https://github.com/openssl/openssl/issues/1760)，是 openssl 和 nginx 的版本特性问题。请问胖虎你现在用的是都是什么版本？

**Comment by ZBrettonYe** [comment]
应该是 推送没有成功， 你可以去有赞云 看看推送失败的记录

**Comment by xiaoanweiwu** [comment]
@ssrpanel 找到问题所在了，把/storage/logs/ 下的文件全部设置为www用户，就可以成功了！我前两天自动创建的文件是root的，刚手动改成www，就可以用了！

**Comment by 828768** [comment]
系统定时任务非www用户执行，改成www执行应该就可以了

**Comment by ZBrettonYe** [comment]
@828768 愿闻其详； 具体书写代码是怎么样的？

**Comment by kuangshao11** [comment]
我的就是www用户，仍然会有1楼的问题，自己试了试，能支付成功，ss账号也加钱了。但是有赞微商城收不到款，不知道钱充哪去了。。。

**Comment by ssrpanel** [comment]
@kuangshao11
你确定你是用微小店？？？

**Comment by kuangshao11** [comment]
@ssrpanel
说错了，确定是有赞微小店。不知道是不是因为宝塔安装导致出现了问题。

**Comment by 828768** [comment]
楼上的不会是充一分钱那个吧？ 有赞有手续费的，充一分有赞该怎么收？看下微小店的流水，要么就被充当手续费去了。

@ZBrettonYe 不是代码的事：[记一次系统任务无法正常执行](https://sobaigu.com/linux-schedule-donot-run-with-crond.html)

**Comment by kuangshao11** [comment]
![tim 20180328151313](https://user-images.githubusercontent.com/33590269/38014389-36c69d94-329b-11e8-8269-16665576df02.png)
![tim 20180328151400](https://user-images.githubusercontent.com/33590269/38014392-3859449a-329b-11e8-872a-8fd7f8b579b9.png)
![tim 20180328151444](https://user-images.githubusercontent.com/33590269/38014395-3950b086-329b-11e8-9292-14390803545b.png)
扎心了，这又是啥问题？我直接复制过去的，求大大们捞我一手
