### ISSUE TITLE
节点显示宕机

### ISSUE THREAD

**Issue by kevin913265** [ssrpanel/SSRPanel#344]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问

大佬你好，加了群发现不能说话，只能来这里问你了。。
请问刚搭的panel，节点显示宕机。
我先在面板添加了节点，检查了ss_node表有数据，节点ID正确，面板和数据库在同一IP上。
SSR用的https://github.com/shadowsocksrr/shadowsocksr
SSR配置了usermysql.json，user-config.json，config.json，
Nginx，php，ssr，都重启过很多次了，还是不行。
确实不是很懂代码，又查不到资料。胖虎大佬能帮忙分析一下可能是哪里的问题吗？
![user-config](https://user-images.githubusercontent.com/37589568/37676756-c1f2be18-2cb3-11e8-975b-a675a640c8ca.png)
![usermysql](https://user-images.githubusercontent.com/37589568/37676757-c22bb2fe-2cb3-11e8-8af5-201b8702e23a.png)
![config_json](https://user-images.githubusercontent.com/37589568/37676758-c25f09f6-2cb3-11e8-99fc-0585e96b9af2.png)
![ss_node](https://user-images.githubusercontent.com/37589568/37676760-c291e40c-2cb3-11e8-9262-39d6f8bb0193.png)

系统：Linux version 4.9.75-040975-generic (kernel@kathleen) (gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) )

**Comment by 514454786** [comment]
进入你安装的目录下，运行./stop.sh，确保你的后端已经停止，再运行一次./run.sh 稍等1分钟左右，刷新面板的节点，即可看到不是宕机了。如果不行，重启服务器，再运行./run.sh。搞定

**Comment by 828768** [comment]
目录下有个server.py，运行这个看结果才是王道。
看来我可以写篇扫盲教程，骗点流量

**Comment by kevin913265** [comment]
通了通了。。原来是防火墙没开端口。。。原谅我发了这个逗比贴。。感谢各位大佬帮助，十分感谢！

**Comment by kevin913265** [comment]
胖虎大佬的东西是真的好，非常好用，谢谢大佬无私奉献！
