### ISSUE TITLE
使用过程中遇到的一点问题和小建议

### ISSUE THREAD

**Issue by CrazyEig** [ssrpanel/SSRPanel#346]
下面都是个人使用中遇到的现象，不知有无通用性。机器为谷歌GCP centos7 ssd10g 3.6G内存 台湾节点。

1.用户注册界面的我已阅读并同意遵守服务条框无法勾选，阅读条款后依旧无法勾选。
![default](https://user-images.githubusercontent.com/30516692/37710516-df161cde-2d48-11e8-8331-42d9d0d9dbe9.png)
2.用户注册后页面无法正常给出提示，一直停留在注册页面，但此时用户数据已经写入数据库。重新注册提示该用户名已经存在。停留界面如下：
![default](https://user-images.githubusercontent.com/30516692/37710636-2f63ad8c-2d49-11e8-9119-c8b27d53b1b0.png)
3.用户注册后邮箱激活界面有一定几率卡死，停留在如下界面：
![default](https://user-images.githubusercontent.com/30516692/37710791-b28630e0-2d49-11e8-9592-3f420012744e.png)
4.初始用户登陆后无法看到节点，需要手动后台添加标签，如果后台管理员没有及时添加，用户完全二丈和尚摸不到头脑的感觉。这个问题已经有人提过，这里再次提出，希望胖虎不要觉得烦。

**Comment by ssrpanel** [comment]
换chrome吧，ie不打算兼容的

**Comment by ssrpanel** [comment]
@CrazyEig  4已经在处理了。。。我也觉得有点烦了。。。哈哈哈，一个个加真心累

**Comment by CrazyEig** [comment]
一开始用的就是chrome，怀疑是浏览器兼容问题，所以换了edge，问题依旧，上面的截图是截图于edge，也试过safari，也存在同样的问题，不知其他人有没有遇到或者是我个人安装的问题。

**Comment by ssrpanel** [comment]
@没人碰到过。

**Comment by CrazyEig** [comment]
大佬，刚刚发的网站http://demo.ssrpanel.com注册界面也无法勾选，勾不勾都显示一样，也不知道有没有勾；）
