### ISSUE TITLE
前端跳转优化建议

### ISSUE THREAD

**Issue by lslzl3000** [ssrpanel/SSRPanel#347]
大部分页面跳转都没有任何loading提示，尤其是付款，我的服务器在国外比较慢尤其明显，很多按钮点击后页面没有任何反应，用户感受很差，建议加上页面loading或提示

**Comment by lslzl3000** [comment]
@ssrpanel 其他界面还好，页面跳转等待一点时间没有问题，主要是付款的界面，点击付款后发起的post有比较长的等待时间，但没有任何提示，这个很影响用户的体验，很多人都以为卡死了

现阶段我觉得应该在付款页面加上loading提示，其他页面可以先不用优化

**Comment by CrazyEig** [comment]
同意，如果是个人用的话，核心功能健全就好，如果是商用的话，用户体验非常重要。

**Comment by ssrpanel** [comment]
@CrazyEig 商业用魔改，比这个强多了
@lslzl3000 有赞云服务器在国内，你网站打开都慢，还玩个卵啊。服务器在美国直接ping国内通常速度都很快，说明你的面板机是真的烂。我用ultravps（洛杉矶） 国内ping 300ms ，但是生成支付单也是秒开

**Comment by yangyzp** [comment]
这个属于个人vps主机性能问题了~~  与面板没什么关系，

**Comment by lslzl3000** [comment]
@yangyzp @ssrpanel  你们一看就不搞前端开发，前端交互一定要考虑加载时间和提示（即使网速很快），不仅是VPS性能和网速的问题，有可能出现很多情况：e.g.
1. 访问人数多，网络或者IO堵塞
2. 程序出错、数据库出错、有赞出错等（顺便说一下，目前的版本只相应成功，如果支付创建出错，前端也没有任何错误处理和提示）
3. 用户自己的网络慢，网络堵塞，比如常见的移动网络下的信号丢失、延迟、掉线等

**Comment by ZBrettonYe** [comment]
@lslzl3000 大佬看起来，很强。 帮帮胖虎dalao优化一下吧， 然后提个pull request， 胖虎很谦虚的 一定和用的 😀

**Comment by ssrpanel** [comment]
@lslzl3000 对啊，来，提个PR

**Comment by ssrpanel** [comment]
@lslzl3000 loading 已加入。哈哈

**Comment by lslzl3000** [comment]
@ssrpanel ^_^ Thanks
