### ISSUE TITLE
关于客户端数量限制

### ISSUE THREAD

**Issue by victoryLV** [ssrpanel/SSRPanel#348]
希望能在商品设置里，增加客户端数量限制个数的套餐，客户购买套餐后，客户端数量能够限制，或者在管理面板能否加个手动限制客户端数量，谢谢胖虎大哥。

**Comment by 828768** [comment]
这个可以有，设定节点服务器在线用户上限。如果在线用户已经超了就不再分配给新用户连接了

**Comment by victoryLV** [comment]
能否实现和sspanel魔改那样，限制客户端连接数量。

**Comment by ssrpanel** [comment]
@victoryLV 赵大我认识，我推荐你用魔改。那个东西搭建起来很多一键包也很快的
