### ISSUE TITLE
请求加个设定

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/SSRPanel#349]
节点 域名地址 和 ip地址 只要填其中一个 就可以创建节点； 而不是 2个都必须填

**Comment by 514454786** [comment]
现在本来就是可以的，你只填写了节点名称，然后在Ip那里填写你的服务器ip就可以了。这样在首页就不会显示你的ip而是显示你的节点名称。

**Comment by ssrpanel** [comment]
@ZBrettonYe IP是一定要填的，域名可以填可以不填，填了优先取域名，这个需求是源于我之前IP老是被墙搞出来的，我的使用场景是这样的：当IP被墙，我只要把域名解析到另一个节点上即可，原来那个节点把域名改掉
