### ISSUE TITLE
商店商品类型和支付方式、用户端订单显示优化等建议 有需求的进来扣 +1

### ISSUE THREAD

**Issue by ghost** [ssrpanel/SSRPanel#350]
1.**商店商品类型**
建议添加一个商品实物类型,邮费设定，发货地等，设定 赠送流量 赠送流量有效期 等 ，
用户端 商品购买页面 ：填写 收货人 ，电话 ，邮箱 ，地址 ，邮编 等
消费记录：商品状态： 如未发货 已发货 物流公司 快递单号等 信息：收货人 ，电话 ，邮箱 ，地址 ，邮编等
订单管理：发货功能 物流公司 快递单号等
![20180322165324](https://user-images.githubusercontent.com/35829269/37760436-a3defe02-2df1-11e8-99b1-85881c62711f.png)
2.**stripe**
stripe支付方式最全，牛逼哄哄的收款商
![20180322172129](https://user-images.githubusercontent.com/35829269/37761861-c2357210-2df5-11e8-9825-920d56c689b8.png)
费用;美国账户2.9%+30美分，香港账户3.4%+HKD 2.35,英国账户：欧洲卡为1.4％  + 20P，非欧洲卡：2.9％  + 20P
主页地址：https://stripe.com/us
文档地址; https://stripe.com/docs/sources
3.**手机用户界面订单显示优化**
![photo_2018-03-22_17-32-26](https://user-images.githubusercontent.com/35829269/37762403-284c3bb4-2df7-11e8-926b-ffa932b95a16.jpg)

**Comment by 828768** [comment]
搞这么复杂，不要搞得当ERP使，你想累屎胖虎啊

**Comment by RomeoJBY** [comment]
@ssrpanel 有时间和兴趣研究下 ，1做二次营销，2 支付种类多， 更安全

**Comment by lslzl3000** [comment]
支持换个国外的支付代理商，国内真的查的很严，我不是危言耸听，真的会被请喝茶

**Comment by ZBrettonYe** [comment]
不感兴趣，胖虎别看了，真的做出来会累死；还是先把以前的坑填了吧

**Comment by RomeoJBY** [comment]
@ssrpanel #287 好神速  叫网友打30w给你  TG 发信息给你了

**Comment by RomeoJBY** [comment]
stripe git ： https://github.com/stripe

**Comment by cciecm** [comment]
胖虎不乐意吧。说了好多次了。

**Comment by ssrpanel** [comment]
这东西不也要实名吗？有什么优势说一下

**Comment by ssrpanel** [comment]
还有，能不能把文档啊，说明啊什么都都一起贴上来。向提有赞那个哥们，你们总不能直接说做个啥，我就自己去找半死

**Comment by ssrpanel** [comment]
因为我没有这个需求，又是开源免费的，我就懒得去找。所以有什么就先贴资料信息吧

**Comment by RomeoJBY** [comment]
@ssrpanel stripe 支持visa、MasterCard、**UnionPay**、**alipay**、**WeChatPay**、**Apple Pay Web**、**Bitcoin**等多种支付方式，海外银行卡（包括香港）提现，账户资料在海外不容易被泄露；资料在收集了 ，需要些时间，资料收集齐全一次贴上来。

**Comment by cciecm** [comment]
@ssrpanel 优势不在技术方面，而是司法管辖权。VPN在其它国家是合法业务，法理上，其法院会拒绝某国索取个人信息的请求，因为这是合法应用，更何况某国的目的是镇压言论自由。在没有和某国签署引渡协议的国家，要通过官方渠道索取这种信息就更难了，除非某国能拿出证据证明当事人违反了该国法律。某国成功的先例也是有的，在某个事件中，它成功拿出当事人散布儿童色情的信息。

**Comment by cciecm** [comment]
这里有个开发指南，日期还挺新
https://juejin.im/post/5a6dda7ef265da3e5a578300

**Comment by RomeoJBY** [comment]
stripe git PHP ：https://github.com/stripe/stripe-php
官网 PHP：https://stripe.com/docs/api
stripe 文档：https://stripe.com/docs
stripe cards ：https://stripe.com/docs/sources/cards
stripe alipay ：https://stripe.com/docs/sources/alipay
stripe wechatpay 找不到任何文档 ，需要通过审核提供私人测试，邀请请求在审核中...
![20180326210159](https://user-images.githubusercontent.com/35829269/37908244-34337820-313a-11e8-953a-50e0111bca25.png)
stripe 比特币  4月23日前停止支付
@ssrpanel 目前收集就这么多; 提供stripe美国账户（已通过验证）用于测试，发送到您的TG

**Comment by RomeoJBY** [comment]
这个是在WooCommerce后台看到的stripe相关设置，希望有帮助
![20180329215344](https://user-images.githubusercontent.com/35829269/38093224-e2c921e6-339c-11e8-8383-64c88af1244d.png)
![20180329215450](https://user-images.githubusercontent.com/35829269/38093237-e7e768b8-339c-11e8-9b1b-f580e03efe7e.png)
![20180329215636](https://user-images.githubusercontent.com/35829269/38093245-ee4ec8d6-339c-11e8-8ff9-54deeed529b5.png)
stripe api 和 webhooks端点
![20180329221047](https://user-images.githubusercontent.com/35829269/38093711-59cb4282-339e-11e8-9162-5293ac1707cc.png)
![20180329221154](https://user-images.githubusercontent.com/35829269/38093722-628260d6-339e-11e8-8262-7ed8e9a39147.png)

**Comment by RomeoJBY** [comment]
这个是WooCommerce后台stripe设置，参照下，希望有帮助
![20180329215344](https://user-images.githubusercontent.com/35829269/38094326-0f090d40-33a0-11e8-8cf1-7aac31cc310e.png)
![20180329215450](https://user-images.githubusercontent.com/35829269/38094333-11fabd96-33a0-11e8-99c5-6c979116fecc.png)
![20180329215636](https://user-images.githubusercontent.com/35829269/38094343-17d4ea0c-33a0-11e8-8cd9-2f627c70116d.png)
stripe API测试调用 和 webhooks端点设置
![20180329221047](https://user-images.githubusercontent.com/35829269/38094417-43ef2cb0-33a0-11e8-8afe-44fd50e1ccf3.png)
![20180329221154](https://user-images.githubusercontent.com/35829269/38094421-47783dea-33a0-11e8-8e75-2de1a949a3da.png)

**Comment by ssrpanel** [comment]
很好很好，我有空研究看看

**Comment by OJBK2333** [comment]
@ssrpanel WC调试支付，被stripe扫出支付宝条款禁止商业名单关键词，支付宝支付被移除；stripe开发暂缓，正在和stripe协商更改业务类型，看能不能扳回
![0410114252](https://user-images.githubusercontent.com/35829269/38535382-c4f3c80c-3cb5-11e8-8b5e-4b63052089a2.png)

**Comment by cciecm** [comment]
你申报了什么业务类型...
  

  
  

  
  
>

**Comment by cciecm** [comment]
别关，我还要呢

**Comment by OJBK2333** [comment]
@cciecm 好吧， 提供ssl环境  ，stripe账号给胖虎用于开发，测试；完成，扫码自己掂量

**Comment by OJBK2333** [comment]
@cciecm 支付宝会审查网站，包括TOS ,商品名称 ,stripe客服小哥已经把支付宝情况说得很详细了，有先例，建议先把支付宝搞掂再做确定，除非不用支付宝权限

**Comment by cciecm** [comment]
不用支付宝也行。我的目标客户群是有信用卡，支付能力较强的人群。
  

  
  

  
  
>

**Comment by OJBK2333** [comment]
信用卡支付方式有很多种，例如：VISA 、MasterCard、UnionPay...等，Stripe UnionPay个人没权限。

**Comment by XD2333** [comment]
@cciecm 贴你的TG上来

**Comment by cciecm** [comment]
@XD2333 我的TG隐私策略是陌生人必须有和我一样的联系人才能通信。这个怎么关掉？

**Comment by XD2333** [comment]
@cciecm 没有遇到过，用的是TGX? 对邀请进群组可以设置权限

**Comment by XD2333** [comment]
@cciecm 贴上来 看下是什么情况

**Comment by cciecm** [comment]
@one_more_second 你试试
  

  
  

  
  
>
