### ISSUE TITLE
有老铁的老用户标签批量修改了的?

### ISSUE THREAD

**Issue by cdlaimin** [ssrpanel/SSRPanel#351]
看了下sql 标签是在另外一张表中 不大会 现在正在研究sql中..
应该如何写?

**Comment by ZBrettonYe** [comment]
我现在的想法是导出user的数据库，然后用其他语言写个导入，修改的程序；
不过可能其他人用不了

**Comment by 828768** [comment]
UPDATE  `user_label`  SET `label_id`=?  WHERE  ????

**Comment by cdlaimin** [comment]
DELIMITER ;; 
CREATE PROCEDURE test_insert () 
BEGIN 

DECLARE i INT DEFAULT 1;

WHILE i<100 
DO 
INSERT INTO `user_label` (`id`, `user_id`, `label_id`) VALUES (NULL, i, '5'); 
SET i=i+1; 
END WHILE ; 
commit; 

END;; 

CALL test_insert();

**Comment by ssrpanel** [comment]
@cdlaimin 你不要太666了。。。哈哈，我做个功能吧

**Comment by ZBrettonYe** [comment]
@cdlaimin 如何按照用户等级赋予标签
因为我之前都是按照等级给的

**Comment by cdlaimin** [comment]
你有没有删过用户这些,你先复制数据库出来 然后往标签表中插入用户等级的那一列数据 看是不是对应的 
对应的就好做 做一个判断 @ZBrettonYe
