### ISSUE TITLE
请问兼容SS的#VPN字样怎么设定删除？

### ISSUE THREAD

**Issue by 514454786** [ssrpanel/SSRPanel#352]
最近老有用户想直接用SS，但死活不会把#VPN的省略，请问在哪个文件夹里能够把#VPN字样修改掉？就是点击兼容后，线路直接不出现#VPN？？？

**Comment by ssrpanel** [comment]
最新版本已经实现了，这个VPN已经改为节点的分组了

**Comment by ssrpanel** [comment]
如果节点不设定分组，就不会显示VPN三个字了
