### ISSUE TITLE
关于新用户账户激活的问题

### ISSUE THREAD

**Issue by zhengyi345** [ssrpanel/SSRPanel#353]
1、管理面板系统设置中 打开激活开关：新用户点击邮箱发送的激活链接后跳转至 http://www.ssrpanel.com/active/885aad7f981b2402c296da20c7220614
然而，返回登陆任然提示账号未激活

2、管理面板系统设置中 关闭激活开关：新用户注册成功并登陆后，状态显示为正常，但无法使用相关节点，而管理面板中新用户账户为未激活，需要管理员手动激活，客户才能正常使用。能否实现账号注册后初始状态就为激活？

**Comment by 828768** [comment]
这个功能是正常的，要么是你环境有问题

**Comment by ssrpanel** [comment]
@zhengyi345 后台有关闭激活，注册 不用激活

**Comment by zhengyi345** [comment]
面板后台关闭激活只是不需要邮箱激活了，不知道什么原因，注册后的账户初始状态仍为未激活
