### ISSUE TITLE
默认值怎么修改

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#354]
用户属性里，这些默认参数在哪设置的？
```
<label for="protocol_param" class="col-md-3 control-label">协议参数</label>
<div class="col-md-8">
       <input type="text" class="form-control" name="protocol_param" value="2" id="protocol_param" placeholder="节点单端口时无效">
</div>
```
adduser文件里设置这个默认值`2`可以保存，为啥下面这个不能保存？
```
<label for="obfs_param" class="col-md-3 control-label">混淆参数</label>
     <div class="col-md-8">
           <textarea class="form-control" rows="3" name="obfs_param" value="microsoft.com,amazon.com,www.walmart.com,www.ctrip.com,bing.com,www.baidu.com,www.youku.com,www.taobao.com,www.qq.com,www.sina.com" id="obfs_param" placeholder="不填则取节点自定义混淆参数"></textarea>
</div>
```
![image](https://user-images.githubusercontent.com/6386202/37822683-20bd55ec-2ec2-11e8-9834-521100aaa973.png)

**Comment by ssrpanel** [comment]
你是说用户自己填吗？

**Comment by ssrpanel** [comment]
我觉得没必要让用户自己填写，你直接设置节点的混淆参数即可。如果要针对某个用户给予特定的混淆参数你后台给她改

**Comment by 828768** [comment]
不是用户，是管理员后台，有时候会管理员创建用户，你的面板默认协议和混淆参数为空，单连接和单用户限速填的200m，虽然也没卵用，这个值看代码里是获取的输入框的值，那为啥代码里指定默认值部分能设置部分还是空或者填的204800？

**Comment by ssrpanel** [comment]
那个无所谓了，我原本规划的带第三方限速用的。不过一直没空做，就给留着

**Comment by ssrpanel** [comment]
@828768 那个协议和混淆参数，已经用上了。单端口的时候用户协议参数不生效，会自动生成。混淆参数如果用户这个有设置，则取用户的，否则就取节的混淆参数，其实读节点上的混淆参数就够了。
非单端口的话如果用户这些有设置就读用户否则读节点的

**Comment by ssrpanel** [comment]
我原本想要给用户开放这个自己修改协议和混淆参数，后面想想，不对，应该给管理员设置的，用户懂个屁
