### ISSUE TITLE
提现管理处，查看提现申请报错

### ISSUE THREAD

**Issue by lzmfor** [ssrpanel/SSRPanel#355]
提现管理处，查看 提现申请报错，出现下面这个页面。。
![21](https://user-images.githubusercontent.com/11819708/37859145-b523c454-2f4a-11e8-943a-96434fb97baf.png)
![2](https://user-images.githubusercontent.com/11819708/37859146-b9267272-2f4a-11e8-9e5e-ac94959887f9.png)

要说明的一点就是：
这个报错和我更新之后点击  <系统设置> 出现的好像一样的。

我已经更新了数据库config表了，点击 <系统设置> 已经正常了。

这里好像还是有点问题。。（2018.03.24更新）

谢谢！

**Comment by lzmfor** [comment]
问题变了变了，估计还是我更新过程中的问题。。但每次更新都出错

重新布置了一下。。但是查看 <提现申请>还有问题出现，下面这两个问题。。
而且我发现。。胖虎你的demo网站里面好像也是这样的

![1-1](https://user-images.githubusercontent.com/11819708/37859751-f358af74-2f53-11e8-8d9c-1c0838e16bd1.png)
![1-2](https://user-images.githubusercontent.com/11819708/37859754-f5b44bc0-2f53-11e8-803a-b2d20f1a7a2d.png)

**Comment by ssrpanel** [comment]
出现第一个这种错误，大多数是你的定时任务用root权限跑，导致日志无法正常写入，所以如果你用宝塔，看一下宝塔的php 默认的用户组是什么。lnmp安装的话默认用户组是www:www ， 看wiki首页
