### ISSUE TITLE
各位大佬们，请教有赞云的实名问题

### ISSUE THREAD

**Issue by 514454786** [ssrpanel/SSRPanel#357]
毕竟如果我们作为销售的话，有赞云需要实名验证，请问大佬们是如何做到非实名，绑定有赞云订单？今天看胖虎大佬更新的有赞云能用了，所以尝试了一下可行了。就是有赞实名这个问题，让自己心慌慌的，你们有好法子吗？

**Comment by cciecm** [comment]
就算非实名通过注册了也要用你的真实支付宝微信绑定吧？你要用支付宝黑号可以避开实名制。这更不好弄，就算弄到，人家可以把你钱全弄走的。

我是用WooCommence上的Paypal插件做支付的，付款后发兑换码，到面板来激活服务。不会编程。这一步是目前还是手动操作的。

麻烦是麻烦，Paypal商户账户不需要实名制，查不到什么。安全第一。

**Comment by 514454786** [comment]
所以，我在想能不能用其他方法实名。从卡出发

**Comment by cciecm** [comment]
有一个环节实名就容易被喝茶。那几个倒霉鬼都是因为支付环节暴露的。

**Comment by lslzl3000** [comment]
其实可以换一个国外的支付代理商，手续费高一点，但是安全

**Comment by cciecm** [comment]
@lslzl3000 那几个不幸登上新闻和维基百科的，还有破娃被人肉，突破口都是支付环节。怪蜀黍们去调查第三方第四方支付平台的交易记录，很快就能查到卖家身份。

**Comment by ssrpanel** [comment]
你想赚钱还不想被抓？？？逗我呢。。。改名吧，改为XX加速服务或者买卡套，一套1000来块吧。
