### ISSUE TITLE
QQ邮箱注册无法收到激活邮件

### ISSUE THREAD

**Issue by cciecm** [ssrpanel/SSRPanel#358]
我发现很多用QQ邮箱注册的用户无法收到激活邮件。腾讯似乎直接拦截了这些激活邮件而不做任何提示。我的系统邮箱会收到相关报错。
有一个用户不依不挠的用QQ邮箱激活了十次，还没成功。

在用户注册页面，能否加上可自定义的字段。比如我的需求是提示用户不要用QQ邮箱。

**Comment by 514454786** [comment]
我直接就是关闭邮箱激活，根本把邮箱给废了

**Comment by cciecm** [comment]
这个方案还是有隐患呀。用户忘记密码了要重置密码，系统邮件还是会被腾讯屏蔽。

我测试过用我网站后缀的邮箱给QQ邮箱发邮件，QQ邮箱上没有任何反应。

最好就是禁止QQ邮箱注册。差一点的方法就是提示不要用QQ邮箱。

**Comment by zhengyi345** [comment]
@514454786 @cciecm 我现在的情况是关闭邮箱，新用户注册完成后的初始状态仍是未激活，请问你们也这样吗？？每次都要手动激活好麻烦
还有，腾讯的SMTP 似乎无法发邮件，我换成126的就一切正常了

**Comment by cciecm** [comment]
@zhengyi345
嗯，刚测试了。关闭邮箱激活，注册后，在后台看是未激活状态。

用户侧，他们可以登录，但是系统不会告知他们的账号未激活。

PS：我发邮件给那位激活10次的仁兄，告诉他我给他激活了。他似乎没收到邮件。

**Comment by 828768** [comment]
Gmail正常发信的路过

**Comment by ssrpanel** [comment]
qq邮箱发信多了，你自己上你的发信qq邮箱看，会被qq邮箱提示说疑似垃圾邮件。说白了，qq邮箱要让你成为付费用户才不会设定一个卡来卡你。所以，域名绑定 yandex.ru，免费邮箱

**Comment by cciecm** [comment]
用的是自己注册域名的邮箱。
