### ISSUE TITLE
关于文章与商品插入图片的出错问题

### ISSUE THREAD

**Issue by zhengyi345** [ssrpanel/SSRPanel#359]
1、在添加商品页面，添加图片后执行，页面出错，并提示：
Unable to create the "/www/wwwroot/ssrpanel/ssrpanel/public/upload/image/goods/" directory
in File.php (line 110)
后来手动添加了goods目录，并赋予777权限，不再出错
不知道是我网站配置过程中出错了，还是其他问题。
2、再文章中添加图片，上传图片后 提示“无法创建目录”；无法知道具体原因了，求救胖虎哥~！

**Comment by 828768** [comment]
原因你已经知道了，都提示无法创建了，就是没权限啊。

**Comment by zhengyi345** [comment]
@828768 可是不知道是哪个文件目录呀？我把public整个目录777了，还是不行
