### ISSUE TITLE
有赞云支付成功，但是收不到款

### ISSUE THREAD

**Issue by kuangshao11** [ssrpanel/SSRPanel#360]
按照 [ https://github.com/ssrpanel/SSRPanel/wiki/%E6%9C%89%E8%B5%9E%E4%BA%91%E6%94%AF%E4%BB%98 ] 一步一步做的，有赞云也配置好了，推送正常。机场支付宝扫码支付时会提示“收银台支付信息获取失败”，但是仍然可以支付，支付成功后在机场是付款成功的状态，有赞云日志也是push success，有赞微小店app中浏览次数会+1。都很正常，就是收不到款....试了好几次0.01元，但今日营业额一直是0.00，请问哪里出了问题？centos7，防火墙关的，所有端口已放行
亟待您的解答，非常感谢！

**Comment by 828768** [comment]
充一分。。。你是不是能充一块试试？有赞有流水，详情点进去看下就知道了

**Comment by juzixs** [comment]
冲0.01元 都不够扣有赞云1%的手续费吧

**Comment by kuangshao11** [comment]
@828768 dalao帮我看看吧，谢谢，，，
![sketch-1522046245148](https://user-images.githubusercontent.com/33590269/37890562-8df26b32-3103-11e8-839b-1592aad25392.png)
![sketch-1522046243624](https://user-images.githubusercontent.com/33590269/37890563-8e5c6410-3103-11e8-942e-6b6283ebedbd.png)
![sketch-1522046244024](https://user-images.githubusercontent.com/33590269/37890566-8ecd9f54-3103-11e8-92cd-c65df5b345f6.png)
![sketch-1522046244383](https://user-images.githubusercontent.com/33590269/37890568-900dbdc2-3103-11e8-9125-f6d3444324df.png)
![sketch-1522046244829](https://user-images.githubusercontent.com/33590269/37890571-90b9411a-3103-11e8-9880-c98f2db4a7b3.png)

**Comment by 514454786** [comment]
有赞的提款好像延迟很久，试过一次，就不想试了

**Comment by kuangshao11** [comment]
发现是我是我自己蠢了，授权到另一个商店去了。已申请提现。
