### ISSUE TITLE
限制特定用户不能使用某节点 能做到？

### ISSUE THREAD

**Issue by qq3461269698** [ssrpanel/SSRPanel#364]
好像现在标签和分组功能都只能限制用户是否能看到该节点  如果一个用户导入过一个分组的节点  但是之后不想让他连接这个节点了，这样的功能能够实现？

**Comment by cdlaimin** [comment]
若是这个标签功能和以前的分组差不多的话 那就是不行的

**Comment by ssrpanel** [comment]
@qq3461269698 用魔改
