### ISSUE TITLE
请问胖虎大大，sspanel用户数据可以同步到您的面板上吗？

### ISSUE THREAD

**Issue by Nfeiyue** [ssrpanel/SSRPanel#365]
我相信很多人都是从sspanel魔改转过来的，屁股后面还带了一大群客户。用户各项数据可以和您的面板对接吗？看了您的计划，看样子是在开发计划内？另外是否可以接入支付宝当面付的模块，很多大机场主需求很大，感谢您的无私奉献。

**Comment by ssrpanel** [comment]
不用感谢，我不会无私奉献的。不用转了
