### ISSUE TITLE
有赞云 收银台支付信息获取失败

### ISSUE THREAD

**Issue by xiaoanweiwu** [ssrpanel/SSRPanel#366]
胖虎，收银台支付信息获取失败  这个是啥问题啊。

**Comment by ssrpanel** [comment]
@xiaoanweiwu 我页不清楚，我也有这个问题，正在处理，在问有赞云官方了

**Comment by rogerlan** [comment]
今天有赞云来电话了，说不购买就停掉商铺，一看价格，要5千块啊！！商铺停掉是不是意味着有赞支付模式就没法用了？大家是如何解决的啊？

**Comment by 828768** [comment]
@rogerlan 不是让你注册商城，是有赞微小店啊哥哥

**Comment by rogerlan** [comment]
@828768 泥煤昏了个头，谢谢凹凸弟弟提醒！

**Comment by ZBrettonYe** [comment]
我的情况是 用户一直反馈 按下按钮 提示 有未完成支付订单 🙈； 然而他们是第一次按钮；后台也没有订单

**Comment by kuangshao11** [comment]
我也是同样问题，一开始设置错了用有赞微商城反而能用，换了有赞微小店就一直client_id错误

**Comment by kuangshao11** [comment]
![tim 20180331110919](https://user-images.githubusercontent.com/33590269/38159072-03c90a2c-34d4-11e8-824c-f5cb8216abf5.png)
这个又是什么操作？？？我刚问的

**Comment by rogerlan** [comment]
微小店是可以的。我重新安装面板，填好微小店接口，就没问题了。

**Comment by yangzhili66** [comment]
@ssrpanel 只有6天的试用，到期以后要购买微赞商城套餐 有赞的支付接口才可以正常使用  这是个鸡肋啊 …………

**Comment by rogerlan** [comment]
@yangzhili66 哥哥你看看上面的帖子再提问啊

**Comment by yangzhili66** [comment]
@rogerlan 不管是微小店和微赞商城都用不了 提示创建支付单失败：参数 client_id 不正确 新申请的账号一样  前几天可以的 好好的这样了

**Comment by yangzhili66** [comment]
“收银台支付信息获取失败”这个问题联系官方了  BUG明天会修复 @xiaoanweiwu @ssrpanel @rogerlan @828768 @ZBrettonYe

**Comment by SRCOL** [comment]
@ssrpanel 新问题：只要其中一个用户有未支付订单(未过期的)，别的用户新增订单也会显示 “创建支付单失败：尚有未支付订单，请先去支付” ，把未支付订单支付后才可以新增

**Comment by ssrpanel** [comment]
@SRCOL 已经修复了这个bug。
@yangzhili66 谢谢提醒，有赞最近估计突然涌入了几百家新微小店，希望大家别把这个给玩烂了。不懂去翻WIKI，是微小店，不是微店。微店要钱。微小店是自己开发的
@rogerlan @yangzhili66 去有赞云后台把所有非微小店的都删除，微小店要用  自用型

**Comment by yeehomlee** [comment]
是在有赞微小店APP上申请的「微小店」，且只有一个微小店。
有赞云绑定后，在SSRPanel后台填好后。
前台在线支付时，仍然是提醒「创建支付单失败：参数 client_id 不正确」。

我在有赞换了个手机号重新注册，尝试第二次也仍然是这样呢。

**Comment by woodytang** [comment]
参数 client_id 不正确, 出问题在这段代码：
```if (Cache::has('YZY_TOKEN')) {  	
            $token = Cache::get('YZY_TOKEN');
         
            if (isset($token['error'])) { // 错误兼容
                Cache::forget('YZY_TOKEN');
            } else {
                return Cache::get('YZY_TOKEN')['access_token'];
            }
        }```
缓存的token有问题，@作者 能不能请解释一下为啥要缓存token？我不太懂支付流程, 请教一下，我好改下这个地方
