### ISSUE TITLE
请问邮件的名片能否改变？在哪里更改？

### ISSUE THREAD

**Issue by 514454786** [ssrpanel/SSRPanel#367]
![image](https://user-images.githubusercontent.com/35135762/38014822-82297134-329c-11e8-95f9-0ebc7f0ad7d2.png)如图，可否把邮件的SSRpanel的字样改变成其他文字？

**Comment by SRCOL** [comment]
你这个问题根本不叫问题（完全没必要问），不过既然你发了问，我就诚心诚意的告诉你
在SSRPanel面板的resources/views/emails目录下可以修改
