### ISSUE TITLE
请问邮件怎么具体配置

### ISSUE THREAD

**Issue by muyuqiyan** [ssrpanel/SSRPanel#368]
按你里面写的配置了mail.php  但是发不出邮件

**Comment by 514454786** [comment]
请谷歌搜索sspanel  QQ邮箱配置，按照上面设置即可

**Comment by ssrpanel** [comment]
@muyuqiyan 你估计屏蔽了25端口，关闭iptables 和selinux 再试试，如果还不行，可能是ISP封了你的25端口（阿里云默认是封25的）
