### ISSUE TITLE
设置同样的端口的用户失败

### ISSUE THREAD

**Issue by ilinsen** [ssrpanel/SSRPanel#375]
![z3x 39qi mu b t0hrf ud](https://user-images.githubusercontent.com/37134914/38136403-b68cf080-3450-11e8-9673-60d3cbf366fd.png)
![zx1yx14h h n 6htdg 05d](https://user-images.githubusercontent.com/37134914/38136405-b6f4a0a4-3450-11e8-8fe0-abca1a1c959b.png)
我自己搭建了两次 都显示这样  但是在演示站没有问题 是不是更新的有bug导致不能摄者

**Comment by 514454786** [comment]
你是不是机器的端口没开80？回去开了看看

**Comment by ilinsen** [comment]
不是80没开，是设置端口直接编辑失败

**Comment by kuangshao11** [comment]
直接改数据库试试？

**Comment by ilinsen** [comment]
试过了，不让改

**Comment by ilinsen** [comment]
感觉是新版本的bug，作者怎么看
