### ISSUE TITLE
提交已知Bug

### ISSUE THREAD

**Issue by vikenlau** [ssrpanel/SSRPanel#377]
已知Bug:
.../user/trafficLog 流量日志無內容
.../admin/nodeList 產生流量無內容
.../user/profile 個人修改后無法連結 

多節點伺服器User-配置文件加密/混淆內容不一致會導致無法連結。

為了維持開源項目本身氛圍，只是盡責向開源作者提交已知Bug，勿誤作個人需求要求作者改善，望理解良性方向思考。

**Comment by suifengv32** [comment]
慢慢来，突然这么多想累屎胖虎啊

**Comment by vikenlau** [comment]
@suifengv32 只是提交Bug,我只是將問題歸檔起來，我覺得相信這樣處理起來會比較有條理。

**Comment by suifengv32** [comment]
我也只是开玩笑的啦~因为看到有个问题贴说了这句话，觉得搞笑~

**Comment by RomeoJBY** [comment]
这些不是bug,付费同你解决

**Comment by ssrpanel** [comment]
@RomeoJBY 你懂就好，小白太多了。根本不是BUG。。。。
