### ISSUE TITLE
用户流量警告收不到邮件

### ISSUE THREAD

**Issue by liganss** [ssrpanel/SSRPanel#378]
smtp已经设置，注册激活邮件能收到。已设置定时任务，超流量会自动禁用帐号，但是收不到流量警告邮件。不知道是不是定时任务出错了。宝塔安装的，定时任务是这样设置的：
crontab -e -u www
* * * * * root/www/server/php/71/bin/php/www/wwwroot/sspanel/artisan schedule:run >> /dev/null 2>&1

**Comment by ZBrettonYe** [comment]
www/wwwroot/sspanel/ 这里要根据你的目录改
