### ISSUE TITLE
#工单自动回复 更新第一时间测试

### ISSUE THREAD

**Issue by RomeoJBY** [ssrpanel/SSRPanel#379]
工单自动回复这个功能非常不错，提高工单效率
更新第一时间做了测试
1.用户发起工单邮件通知admin，admin邮件收到用户的工单提醒
2.admin回复用户工单，admin收到回复工单提醒，用户收不到回复工单提醒
![photo_2018-03-31_20-36-59](https://user-images.githubusercontent.com/35829269/38163349-26813a3e-3525-11e8-8236-1ddb789a3dea.jpg)
2调转了，admin回复用户工单，则应是用户收到回复工单提醒
![20180331211242](https://user-images.githubusercontent.com/35829269/38163573-8bda40a8-3528-11e8-8e16-a87e3530f50f.png)

**Comment by RomeoJBY** [comment]
![20180331211242](https://user-images.githubusercontent.com/35829269/38163567-796e6fd4-3528-11e8-982d-98aafab8c037.png)

**Comment by ssrpanel** [comment]
@RomeoJBY 我改改

**Comment by ssrpanel** [comment]
@RomeoJBY 修复了，git pull 一下
