### ISSUE TITLE
#工单自动通知 ；看情况 有时间修改

### ISSUE THREAD

**Issue by RomeoJBY** [ssrpanel/SSRPanel#380]
1.git pull 之后测试如图1
![20180331223854](https://user-images.githubusercontent.com/35829269/38164362-c8ca304c-3535-11e8-9747-6ee846732f4f.png)
2.关闭工单测试
![20180331230535](https://user-images.githubusercontent.com/35829269/38164487-25b2f620-3538-11e8-9be1-1ed6618ead9f.png)
3.图3这个应该是回复工单的，另外关闭工单需要改
![20180331224440](https://user-images.githubusercontent.com/35829269/38164662-45a67216-353a-11e8-9250-8e8fe29bf18d.png)
@cciecm 扫码数字建议按大点!!!，Panel后续需要维护

**Comment by ssrpanel** [comment]
@RomeoJBY @cciecm 又更新了下。@cciecm 打赏给力

**Comment by ssrpanel** [comment]
这回应该没毛病了

**Comment by RomeoJBY** [comment]
更新测试：
1.admin回复工单，用户仍然收不到回复工单邮件通知
![20180401001828](https://user-images.githubusercontent.com/35829269/38165255-476c9bf8-3543-11e8-92f4-ff29a4eccdec.png)
2.关闭工单，用户收不到通知
![20180401002032](https://user-images.githubusercontent.com/35829269/38165263-716275f4-3543-11e8-8373-1036e60c5c2a.png)
@ssrpanel 有待 @cciecm 测试结果

**Comment by cciecm** [comment]
还在研究升级失败

**Comment by RomeoJBY** [comment]
@cciecm 是否修改了本地文件？如是那么把显示错误的文件删除或修改为原来再 git pull

**Comment by cciecm** [comment]
图片改回去了。执行git pull显示已经最新

[root@vj1 ssrpanel]# git pull
Already up-to-date.

**Comment by RomeoJBY** [comment]
如果只是单单改了图片，建议执行覆盖再git pull

**Comment by cciecm** [comment]
wiki里没这条呢

**Comment by RomeoJBY** [comment]
https://github.com/ssrpanel/SSRPanel/wiki/代码无法更新问题处理办法 ，先备份 邮箱和数据库配置信息在执行

**Comment by ssrpanel** [comment]
@RomeoJBY 更新了，试试看。

**Comment by RomeoJBY** [comment]
Very good ,完全OJBK
