### ISSUE TITLE
登录不上了

### ISSUE THREAD

**Issue by Bennett561** [ssrpanel/SSRPanel#383]
我把订阅节点的那个网站设置成和面板首页一样之后，就再也登录不上面板了..伤心

**Comment by Bennett561** [comment]
直接返回HTTP ERROR 502， 请问胖虎大大，有什么补救的方法吗？不想再重来一次啊……

**Comment by 828768** [comment]
我要告诉你在数据库把这个设置值清空的话我想你又该问怎么清了，还是换个服务器重来一遍吧，你这个估计是服务器太烂了。

**Comment by ssrpanel** [comment]
@Bennett561 贴个日志上来把？？ storage/logs/laravel 最新的.log

还有 502错误，基本是你服务器配置问题
