### ISSUE TITLE
升级失败

### ISSUE THREAD

**Issue by cciecm** [ssrpanel/SSRPanel#384]
为什么我在我的测试服务器用这个步骤总是失败
**设置-系统设置** 消失了
我只好准备两台服务器备份好数据库，全新安装，再倒入数据库。

> 进到ssrpanel目录下执行：
> git pull
> 
> 如果每次更新都会出现数据库文件被覆盖，请先执行一次：
> chmod a+x fix_git.sh && sh fix_git.sh
> 
> 如果更新完代码各种错误，请先执行一遍 php composer.phar install

**Comment by ssrpanel** [comment]
那个是早期的问题
现在只要git pull

**Comment by cciecm** [comment]
执行后面两个会导致文件丢失么

**Comment by ssrpanel** [comment]
@cciecm 不会
