### ISSUE TITLE
SSRPanel支持IPv6么？

### ISSUE THREAD

**Issue by cciecm** [ssrpanel/SSRPanel#385]
有客户想用IPv6连接。正好我的面板和部分节点支持IPv6

**Comment by cciecm** [comment]
我这里可以telnet 节点 IPv6地址，测试端口443已打开
MBP:~ $ telnet -6 2400:84c0:f:0:216:3eff:fe1a:xxxx 443
Trying 2400:84c0:f::216:3eff:fe1a:xxxx...
Connected to 2400:84c0:f:0:216:3eff:fe1a:xxxx.
Escape character is '^]'.
^CConnection closed by foreign host.

在客户端上把IP地址改为IPv6，测试连接时，节点没有产生任何关于IPv6连接日志。

**Comment by cciecm** [comment]
现在可以连上了（啥都没改）。
不过观察了出站流量还是IPv4。。。
Client ---- Native IPv6 ---- Server ---- IPv4 ---- Netflix

**Comment by cciecm** [comment]
好像是Linux的问题，我继续研究……

**Comment by ssrpanel** [comment]
你前面一个iSSUE提的，目的是不是这样：节点增加一个填写IPV6的，再增加一个是否显示IPV6的，如果是则给用户显示 IPV6 的信息 包括 获取二维码的时候新增加一个IPV6的二维码

**Comment by ssrpanel** [comment]
这样的话我阔以加上的

**Comment by ZBrettonYe** [comment]
话说SSR 怎么用ipv6 @cciecm 方便写个配置教程码？

**Comment by ssrpanel** [comment]
@cciecm 已收入至wiki

**Comment by ssrpanel** [comment]
@cciecm 那个DNS 有什么用吗？话说我从未设置过这个东西，有什么规则写法吗？

**Comment by cciecm** [comment]
@ssrpanel 这个是指定SSR转发流量时请求的DNS，不影响系统自身的DNS请求。
比如，你的节点系统DNS是8.8.8.8，而，SSR的DNS设为1.1.1.1，那么：
源IP是节点的DNS请求，会发送给8.8.8.8
所有SSR的相关流量，节点会使用1.1.1.1来解析域名

**Comment by ssrpanel** [comment]
已加上

**Comment by ssrpanel** [comment]
@cciecm 试试

**Comment by ssrpanel** [comment]
@cciecm 卧槽，打开ipv6，如果ipv6走不通就不通了。不能自动切换成ipv4。。。
