### ISSUE TITLE
面板可以做IPv4/IPv6双栈么？

### ISSUE THREAD

**Issue by cciecm** [ssrpanel/SSRPanel#386]
同一台节点，支持IPv4/IPv6双栈。目前面板只能配纯IPv4或纯IPv6，两者不能共存。

能否在面板上对客户同时显示IPv4和IPv6地址（IPv4和IPv6有各自对二维码和ssr地址）

将来这个需求会越来越普遍的。

**Comment by ssrpanel** [comment]
@cciecm 举例咋用？应用场景。

**Comment by cciecm** [comment]
同一个节点的IPv4和IPv6手动配置信息、SSR地址和二维码在面板上分开显示
订阅时，IPv4和IPv6也分开显示。

IPv6和IPv4的路由不一样。使用IPv6不必去挤CN2这个独木桥。

**Comment by cciecm** [comment]
之前那个中转的功能也可以用类似的方案。面板上只需要多显示一个项，与原配置仅有端口差异，剩下的交给iptables解决就行了。

**Comment by ssrpanel** [comment]
@kuangshao11 @cciecm 已加上，等待提代码
