### ISSUE TITLE
用户过期后续费时是按照过期时间开始计算而不是当前日期开始

### ISSUE THREAD

**Issue by cdlaimin** [ssrpanel/SSRPanel#387]
这里大家有问题吗 我这里一直都是这样滴

**Comment by ZBrettonYe** [comment]
老问题了

**Comment by SRCOL** [comment]
这不是个问题，逻辑是对的，前面已经有人问过了

**Comment by 828768** [comment]
@SRCOL 不能说不是个问题，程序逻辑是对的，但业务逻辑是不对的。
![](https://user-images.githubusercontent.com/6386202/38252290-532e1af8-3786-11e8-8f51-b6354cb3c98a.png)

**Comment by SRCOL** [comment]
@828768 对对对，你把我真正想说的表述清楚了，感谢感谢🐸

**Comment by tonychanczm** [comment]
@ssrpanel 求胖虎大佬解决

**Comment by ssrpanel** [comment]
已修复，等待提交
