### ISSUE TITLE
严重商品问题反馈

### ISSUE THREAD

**Issue by 514454786** [ssrpanel/SSRPanel#388]
用户充值后购买商品，流量出现负数，而且数值高达几TB，请胖虎大大帮忙查看一下！
![image](https://user-images.githubusercontent.com/35135762/38285093-20f27032-37f1-11e8-9be9-115df90966fb.png)

**Comment by ssrpanel** [comment]
@514454786 截图全一些，后台商品信息，这个用户买了什么商品，

**Comment by 514454786** [comment]
![image](https://user-images.githubusercontent.com/35135762/38286570-9c982716-37f8-11e8-8bd9-29371cbfac6d.png)
@ssrpanel

**Comment by 514454786** [comment]
![image](https://user-images.githubusercontent.com/35135762/38286595-c39bf888-37f8-11e8-8502-345048f41a59.png)
@ssrpanel

**Comment by 514454786** [comment]
多次购买其他商品，流量依旧异常

**Comment by 514454786** [comment]
![image](https://user-images.githubusercontent.com/35135762/38286672-227cc7e2-37f9-11e8-92e7-5195463c28b0.png)

**Comment by 514454786** [comment]
![image](https://user-images.githubusercontent.com/35135762/38286700-43271cea-37f9-11e8-80d1-3e66b43aeb14.png)
这是季度套餐，流量比较大的，用户购买后，会出现0B流量

**Comment by 514454786** [comment]
@ssrpanel 出问题是所有商品都出了，月套餐就300G流量，但购买后出现-2.8T的情况，不知道怎么回事。

**Comment by SRCOL** [comment]
溢出了？🐸

**Comment by 514454786** [comment]
@ssrpanel 胖虎，我把3月26日备份的网站覆盖后，发现商品能正常了。但重新换会4月3号的备份，商品一样报错。所以应该是代码的问题，麻烦你有空查看一下吧！

**Comment by andygebb** [comment]
為何需QQ號才能激活賬號服務？因本人從未有過QQ號，故而根本無法激活SS註冊後的賬號服務。更甚的事，眾所周知QQ是個專門監視用戶一舉一動的木馬監控軟件，請是否能改為註冊後即能開通服務，或者應用其它途徑G+等方式激活開通服務。

**Comment by ZBrettonYe** [comment]
@ssrpanel 这个问题我觉得我知道原因，胖虎你的机制是过期扣除过期套餐的流量； 只要管理员在后台改过套餐流量，就会造成这个套餐对应ID的流量被扣除，导致负数；

附加BUG：先选择在线购买套餐A，用户不支付，然后选择了余额支付 支付套餐B， 系统会先扣除套餐A的流量 然后再加上套餐B 的流量；

还有数据库中订单（order） 的 status 说明可能不对， -1 才是关闭

**Comment by ZBrettonYe** [comment]
@andygebb 本面板都是用邮箱作为账号的，激活也是用注册邮箱激活，不知道你在说啥；还有QQ是不是并不是木马，tx虽然恶心，但还没有到这种地步

**Comment by 514454786** [comment]
@ZBrettonYe 不知道为什么，应该是有问题，我覆盖了3月26日的代码，就不会出现这个情况，老用户也能直接购买。

**Comment by ssrpanel** [comment]
@514454786 我看看，奇怪了。。
@ZBrettonYe 什么，你们还有这种操作？商品设置好了都已经有人购买了还改商品信息？？这点我没考虑到。这样的话一定会有问题的

**Comment by ssrpanel** [comment]
@514454786 已修正，试试看

**Comment by 514454786** [comment]
@ssrpanel 反馈一下问题：管理中心——用户——切换身份——报错：ip6

**Comment by 514454786** [comment]
@ssrpanel 胖虎，是不是手动调过流量设置的用户，购买套餐流量都不会出现重置？？？？我现在是新客户可以直接购买套餐无任何报错，但旧用户通过购买套餐，流量均不改变

**Comment by 514454786** [comment]
我现在思考着，我当时手动改了很多用户的流量，我可不想每次给他们手动修改！求胖虎提供解决办法
