### ISSUE TITLE
用户连接的时候如何对用户的帐户密码进行验证？

### ISSUE THREAD

**Issue by DreamSeekerKaiser** [ssrpanel/SSRPanel#389]
老哥哥受累 有一个问题一直不明白比如我现在有用户A密码是123 当A用户连接的时候如何验证用户的帐号密码才开启SS的连接？  SSR服务器端提供的文档并没有写明白多用户MYSQL 的时候如何跟现有用户关联 

其实我的问题是  如何让用户连接的时候提供用户名和密码 然后我去数据库查询OK之后才允许用户连接？

**Comment by ssrpanel** [comment]
你的问题太高深，我看不懂

**Comment by DreamSeekerKaiser** [comment]
现在大致明白了一点就是用户可以用来连接的凭证 只是一个密码谢谢你

2018-04-04 12:03 GMT+08:00 Bruskyii Panda <notifications@github.com>:
