### ISSUE TITLE
怎么设置流量重置日期

### ISSUE THREAD

**Issue by 64611187** [ssrpanel/ssrpanel#39]
因为vps不是固定时间重置流量需要给节点设置流量重置日期也没有账号流量重置。
流量记录大量占用数据库希望增加开关和删除记录功能虽然可以直接删数据库。

**Comment by 64611187** [comment]
目前版本已经可以稳定运行了后面希望大佬能写个更新说明

**Comment by ssrpanel** [comment]
@64611187 
1.目前还没有用户流量重置功能，这个涉及到购买流量包的问题，我还得再考虑下
2.流量记录几十万条才占用多少数据库而已，硬盘才多少啊，流量记录是用来统计这个账号已经消耗了多少流量，跟账号的流量分析都有关系，暂时不提供删除和清空空能，方便做用户流量分析，如果要改可能我得换种方式做流量分析。
