### ISSUE TITLE
Scheme Links和二维码 混淆参数为空.

### ISSUE THREAD

**Issue by yulewang** [ssrpanel/SSRPanel#391]
管理员设置了某节点的混淆, 点击域名查看配置信息, 混淆正常展示.
但是通过Scheme Links和扫描二维码得到的配置中混淆参数为空.

**Comment by ssrpanel** [comment]
@yulewang 贴图，我看下你的设置，默认是优先取用户的，其次如果节点设置了单端口就取单端口的，否则就取节点设置的

**Comment by ssrpanel** [comment]
已修复
