### ISSUE TITLE
邮件发不出去

### ISSUE THREAD

**Issue by Bennett561** [ssrpanel/SSRPanel#392]
我配置的应该没问题，但是不知道为啥，各种错误
Expected response code 250 but got code "501", with message "501 mail from address must be same as authorization user "
Expected response code 250 but got code "535", with message "535-5.7.8 Username and Password not accepted.

**Comment by SRCOL** [comment]
你可以试着翻译一下这段话可能就知道原因了。。。

**Comment by Bennett561** [comment]
看得懂，但是报的错都不一样啊

**Comment by ssrpanel** [comment]
这是账号密码不对吧？？邮件系统的问题，跟面板无关
