### ISSUE TITLE
功能实现能改一下就牛逼了

### ISSUE THREAD

**Issue by Bennett561** [ssrpanel/SSRPanel#393]
用户列表的很多信息如果不用点小铅笔进去改，直接改那就很方便了，
比如状态：有激活，未激活，禁用，，如果 只要点一下就改一个状态那样就方便很多。

小白的建议。谢

**Comment by ssrpanel** [comment]
@Bennett561 这个有安排做

**Comment by 828768** [comment]
@ssrpanel 胖虎，根据购买商品自动贴标签的功能什么时候能好啊？坐等
