### ISSUE TITLE
希望能增加些比较至关重要的功能

### ISSUE THREAD

**Issue by miniaoe** [ssrpanel/SSRPanel#394]
1.可以在商品界面设置购买时自动为用户加上特定的标签，用户可以存在多重标签，
2.可以增加在线IP限制，以及审计规则（可以限制BT，恶意邮件类）
3.可以设置新注册用户看不到任何节点信息，以及做不了相关的操作。

个人认为上述是比较重要的几种。

@ssrpanel  感谢。

**Comment by ZBrettonYe** [comment]
提交问题前， 请看wiki

**Comment by ssrpanel** [comment]
@ZBrettonYe 这几天突然多了好多小白
