### ISSUE TITLE
建议增加SSR服务器订阅功能

### ISSUE THREAD

**Issue by leonis999** [ssrpanel/ssrpanel#40]
建议可以针对每个用户自动生成一个SSR服务器订阅网址的功能，这样多节点可以自动导入和自动更新，更方便使用，谢谢！

**Comment by ssrpanel** [comment]
@leonis999 真对每个用户生成一个用户专属唯一的服务器订阅网址啊？
那个订阅怎么搞？我都没试过，帮我找下文章吧，我得先了解下原理

**Comment by ssrpanel** [comment]
@leonis999 弄明白了，我稍后就加

**Comment by 64611187** [comment]
建议增加单账号设备链接数量限制

**Comment by ssrpanel** [comment]
@leonis999 节点订阅功能已上，拉下最新的代码，记得到项目主页看 定时任务，需要编辑crontab，还有，要导入/sql/update下的20171002.sql到数据库

**Comment by ssrpanel** [comment]
@64611187 这个我到目前为止都没搞明白，貌似需要第三方配合
