### ISSUE TITLE
节点产生流量无法统计，一直显示0

### ISSUE THREAD

**Issue by ogays** [ssrpanel/SSRPanel#401]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
节点产生流量无法统
![qq 20180407135328](https://user-images.githubusercontent.com/32096394/38451882-1439de80-3a6b-11e8-9b73-0059f501802c.png)
计，一直显示0

**Comment by foxhound1227** [comment]
解决了吗？ 同样的问题！
