### ISSUE TITLE
关于套餐流量清空

### ISSUE THREAD

**Issue by qq3461269698** [ssrpanel/SSRPanel#403]
最近发现套餐流量套餐到期后流量还是存在，导致即使套餐到期，用户也依然可以使用，能不能这样弄一下，在套餐到期的时候，清空一下用户流量，或者套餐流量

**Comment by ssrpanel** [comment]
@qq3461269698 已经修正，试试？

**Comment by qq3461269698** [comment]
我去试试

**Comment by 514454786** [comment]
@ssrpanel 不知道哪里错误，更新代码后，点击用户管理，切换身份就报错
