### ISSUE TITLE
节点添加功能是不是有问题

### ISSUE THREAD

**Issue by zouwei11** [ssrpanel/SSRPanel#407]
昨天更新的是不是有问题，添加节点会报错，我还以为是我这边的问题，后来发现用演示站也是这样。

**Comment by number018** [comment]
我也是，添加报TokenMismatchException，我发issue，这么回的：把config/app.php 中的debug 改为false，然后这个你在页面停留太久没动，导致csrf防跨站生效了。刷新一下即可
然而我试了，也并不可以，提示页面不存在。节点也没添加

**Comment by zouwei11** [comment]
我直接添加进数据库里了，可以显示出来，后面的还不知道能不能行。

**Comment by ssrpanel** [comment]
@zouwei11 @number018 你们都只知道git pull ，但是不看更新了什么吗？sql/update/最后一个sql导入到数据库

**Comment by number018** [comment]
不好意思啊..我今天才安装的...

**Comment by ssrpanel** [comment]
@number018 @zouwei11 我曹，我的错，我刚试了，确实有毛病，我的问题，sorry

**Comment by zouwei11** [comment]
我也是今天安装的，数据库已经里面有了ipv6啊

**Comment by ssrpanel** [comment]
@zouwei11 @number018 更新了，试一下
