### ISSUE TITLE
单端口多用户无法上网（链接已经建立）./logrun 无日志记录

### ISSUE THREAD

**Issue by DreamSeekerKaiser** [ssrpanel/SSRPanel#408]
亲爱的胖虎你好 我有一个疑问 我以单端口多用户的形式成功启动服务 用户也可以连接到服务器的端口但是就是无法上网 监控./tail.sh也无错误日志 请问这是什么情况？ 单节点多用户 如果每个用户都通过同一个端口连接 怎么识别用户？我看了你的read.me 文件 有这么一段文字 是关于 单端口多用户 客户端的设置的。 

        协议参数：1026:SSRP4ne1 (SSR端口:SSR密码)   
这个 SSR 端口指的是哪一个端口 是在后台 建立用户时候分配给用户的端口？还是你要连接的目的服务器设置的以单端口提供服务时候指定的端口 如443？ 这个密码是写在服务器user-config.json配置文件中单端口的的密码还是建立用户时候给用户设置的端口密码？

疑问 1 如果服务端设置的协议参数是 '#'  例如  "protocol_param": "#",  此时客户端应该如何设置该参数？
      
              #1026:SSRP4ne1 (SSR端口:SSR密码)  是这样嘛？

我以单端口多用户形式启动ssr服务的时候 应该 去哪个文件夹呢？  是 /shadowsocksr/shadowsocks 还是
／shadowsocksr。非常感谢和期待您的回复
                             您的粉丝致上。

**Comment by ssrpanel** [comment]
@DreamSeekerKaiser 
1.先看项目主页
2.然后翻一翻wiki
3.然后翻一翻close issues
