### ISSUE TITLE
新添加的有效期，感觉有问题

### ISSUE THREAD

**Issue by cheapssr** [ssrpanel/ssrpanel#41]
可能是我没有理解，你看对不对
01
不能这么设定日期，应该是直接设定多少天
有效期是以天数为单位
举例：
管理员设定，5G流量，有效期填个10，，那么就是5g流量在10天内有效
然后，有了两个值，5G和10天，，平时使用，流量会扣除。。
5G流量用完，或者，流量没有用完，但是到了10天
那么他的流量包取消

02
流量包取消之后，要给用户一个提示，邮件或者站内信（这个要醒目）

03

流量包列表
比如我设定10G流量
那么显示
内含流量 
10240
这个看着就很别扭，最好显示出来G这个东西，让用户看到

04
流量日志要有清空的功能，正式用起来，，流量日志估计会有很多
他们是保存在哪里的，数据库吗

给予厚望，努力吧

**Comment by cheapssr** [comment]
仔细想了想，我好像理解了，销售模式的不同。。
你是不是想做成，我以前提到过的那种模式
30天有效，流量阈值比如是20G，，到20G自动停，然后，管理员可以后台操作清空已经使用的流量？？
是这样吗？

**Comment by ssrpanel** [comment]
@cheapssr 有道理，我研究下

**Comment by ssrpanel** [comment]
@cheapssr 流量记录保存在数据库里，行，我加一个一键清空流量日志

**Comment by ssrpanel** [comment]
@cheapssr 站内信，我捣鼓一下

**Comment by cheapssr** [comment]
嗯，，其实这个功能比较关键，销售的流量，看我提出的01，，这是一种情况，，延伸出来，比如说，没到10天，5G流量用完了，，如果用户和管理员py交易的话。。能不能灵活处理呢，，再给用户多少G流量，但是有效期还在这个10天以内。。

**Comment by ssrpanel** [comment]
@cheapssr 我在开发了，我把它做得更灵活些

**Comment by ssrpanel** [comment]
@cheapssr 代码已上，更新下，然后倒入/sql/update_20171008.sql
