### ISSUE TITLE
教程求收录！ 百度ssrpanel排名第一

### ISSUE THREAD

**Issue by a723690032** [ssrpanel/SSRPanel#410]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
https://www.xiaoweigod.com/network/1363.html

**Comment by ssrpanel** [comment]
@a723690032 已收录，握爪，哈哈哈

**Comment by ssrpanel** [comment]
@a723690032 教程太老了，哈哈哈，都已经有有赞云支付了。。可以更新一波教程了

**Comment by ssrpanel** [comment]
看到我把整套系统做的更漂亮了吗？哈哈哈，截图
