### ISSUE TITLE
刚刚在更新代码时遇到了一个问题

### ISSUE THREAD

**Issue by nishuo** [ssrpanel/SSRPanel#411]
我首先执行了fix_git.sh 然后执行update.sh 重新编辑了config/database.php
访问页面出现了一个错误

> 

(1/1) ErrorExceptionUndefined property: stdClass::$ipv6
--
in UserController.php (line 117)

以及各种一堆报错。。不知道怎样算正确的姿势更新代码。

**Comment by Saszr** [comment]
如何解决啊
