### ISSUE TITLE
几个节点都是443单端口,用了几天无法统计流量

### ISSUE THREAD

**Issue by nishuo** [ssrpanel/SSRPanel#413]
在自己群里分享了几个小伙伴用，今天在面板上看流量消耗情况还是0B，可以正常在节点列表看到是在线的，另外用单端口后，SS协议没法兼容。。连上没数据，下面是我的节点配置，按照教程后都加了_compatible

>additional_ports"
 : {
        "80": {
            "passwd": "onepispeed",
            "method": "aes-256-cfb",
            "protocol": "auth_sha1_v4_compatible",
            "protocol_param": "#",
            "obfs": "tls1.2_ticket_auth_compatible",
            "obfs_param": ""
        },
        "443": {
            "passwd": "onepispeed",
            "method": "aes-256-cfb",
            "protocol": "auth_sha1_v4_compatible",
            "protocol_param": "#",
            "obfs": "tls1.2_ticket_auth_compatible",
            "obfs_param": ""
        }

**Comment by lslzl3000** [comment]
没加定时任务吧~

**Comment by ssrpanel** [comment]
@nishuo 节点流量是每天凌晨4.30统计一次的。

**Comment by ssrpanel** [comment]
要开定时任务
