### ISSUE TITLE
后台 “添加节点”和“系统设置”两个选项  页面不存在

### ISSUE THREAD

**Issue by ehcsa** [ssrpanel/SSRPanel#414]
面板折腾好，终于可以登陆，准备添加节点，发现 addnode  和 system 两个页面不存在，无法添加节点，百度一圈没发现类似的问题，请问有没有遇到过这种事，大概怎么解决，感谢

**Comment by ssrpanel** [comment]
截图

**Comment by ehcsa** [comment]
解决了  重新用宝塔搭建也存在这个问题，但是有提示说是：label表不存在。
发现是自动部署 不知道为什么会少了几张表，导入db.sql就可以了
---------------------------------------
php artisan migrate
播种(填充数据)

php artisan db:seed --class=ConfigTableSeeder
php artisan db:seed --class=CountryTableSeeder
php artisan db:seed --class=LevelTableSeeder
php artisan db:seed --class=SsConfigTableSeeder
php artisan db:seed --class=UserTableSeeder
----------------------------------------------------------
