### ISSUE TITLE
后台页面流量不会进行统计，但是流量记录内是有流量在走的

### ISSUE THREAD

**Issue by miniaoe** [ssrpanel/SSRPanel#417]
![popo_2018-04-11 17-42-10](https://user-images.githubusercontent.com/21149432/38609151-e4d4b4f6-3daf-11e8-9364-3f9f4589b381.jpg)

点击进去是有流量在走的，胖虎大大查看下，还有购买自动打标签功能超期待。。。

**Comment by cnxfire** [comment]
我也一样

**Comment by nishuo** [comment]
你是单端口吗？我443单端口。。节点列表内有显示用户在线，我在用户中心查看，最后使用：从未使用。
后台的流量也一直0B无法统计
