### ISSUE TITLE
大神能不能搞一个定制客户端的教程

### ISSUE THREAD

**Issue by dayuezai123** [ssrpanel/SSRPanel#419]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问

**Comment by dayuezai123** [comment]
大神能不能搞一个定制客户端的教程

**Comment by miniaoe** [comment]
git搜shadowsocks-backup 就是ss的源码，自己改啊

**Comment by ssrpanel** [comment]
@dayuezai123 @miniaoe 是的，有源码的，自己改。我那个api是给自己会改的大佬强烈要求下加的

**Comment by ogays** [comment]
这个是客户端源代码## https://github.com/shadowsocksr-backup/shadowsocksr-android/releases

**Comment by dayuezai123** [comment]
可以搞win专用客户端吗？




发自网易邮箱大师
在2018年4月13日 14:31，Bruskyii Panda<notifications@github.com> 写道：

@dayuezai123@miniaoe 是的，有源码的，自己改。我那个api是给自己会改的大佬强烈要求下加的
