### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by a582995627** [ssrpanel/ssrpanel#42]
就是在后端对一个账号修改数据后，类似日期及流量之类的，前端账号需要退出在登录数据才会刷新

**Comment by ssrpanel** [comment]
@a582995627 OMG!貌似这个是因为我用的都是session缓存导致的。我改一下，谢谢反馈

**Comment by a582995627** [comment]
另外，刚刚发现，删除掉已有的节点信息后再用户面板中还会残留有一列在那，里面没有信息。

**Comment by a582995627** [comment]
[[ https://thumbnail0.baidupcs.com/thumbnail/d35499e982bebfe9185710ac6803fa9a?fid=1868218007-250528-250460328484826&time=1506870000&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-qWgzYE6Q%2FRkNKvZ6HB9Q6KklRn0%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=6354660591996128006&dp-callid=0&size=c710_u400&quality=100&vuk=-&ft=video | height = 100px ]]

**Comment by a582995627** [comment]
[[ https://thumbnail0.baidupcs.com/thumbnail/d35499e982bebfe9185710ac6803fa9a?fid=1868218007-250528-250460328484826&time=1506870000&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-qWgzYE6Q%2FRkNKvZ6HB9Q6KklRn0%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=6354660591996128006&dp-callid=0&size=c710_u400&quality=100&vuk=-&ft=video.jpg | height = 100px ]]

**Comment by a582995627** [comment]
还有面板貌似只能显示两条线路的人数。。。我新增的第三条不显示人数和负载，不知道有无此事

**Comment by ssrpanel** [comment]
@a582995627 面板显示节点的问题呢，你得先把节点加入到某个分组下，账号的等级对应分组的等级，用户只能看到小于等于自己等级的分组的节点。

**Comment by a582995627** [comment]
不是，我指的是人数显示与负载那里。就是说我接入的第三条线路流量日志没有同步到数据库。对接是正常的，可以连接

**Comment by ssrpanel** [comment]
@a582995627 那你ssr后端的usermysql.json里的node_id要跟后台添加的节点的ID一致才可以
