### ISSUE TITLE
建议搞个客服插件

### ISSUE THREAD

**Issue by ogays** [ssrpanel/SSRPanel#424]
国外客服网站
有各种客户端
https://app.crisp.chat/
可以安装电报 脸书 推特等社交插件
![qq 20180412121229](https://user-images.githubusercontent.com/32096394/38656075-d4c36120-3e4a-11e8-8b90-10d556b387ff.png)
![qq 20180412121203](https://user-images.githubusercontent.com/32096394/38656077-d8ea9494-3e4a-11e8-931d-773b524c0994.png)

效果可以看图
![qq 20180412120618](https://user-images.githubusercontent.com/32096394/38655964-016caea8-3e4a-11e8-9f3f-68e934880c3c.png)

**Comment by 828768** [comment]
这个功能挺好的，但我觉着还是放个QQ联系链接更靠谱\(^o^)/~，这种站内信消息时效性得不到保障的

![image](https://user-images.githubusercontent.com/6386202/38656413-f2ac9d1c-3e4c-11e8-9d86-1438a513649d.png)

**Comment by ogays** [comment]
@828768 安卓 苹果 windows有客户端的

**Comment by ssrpanel** [comment]
@ogays 阔以阔以，就喜欢你酱紫的，提需求带图带资料的，我稍后加一下

**Comment by ogays** [comment]
@ssrpanel 谢谢

**Comment by ssrpanel** [comment]
@ogays 留下你的tg号，我拉你进群，确实非常好用，看demo.ssrpanel.com

**Comment by ogays** [comment]
demo.ssrpanel.com 网站没有变化啊
![qq 20180413231615](https://user-images.githubusercontent.com/32096394/38743099-cc2cef50-3f70-11e8-945a-0d3e1fb3e2e4.png)
![qq 20180413231746](https://user-images.githubusercontent.com/32096394/38743135-e72c2bb8-3f70-11e8-88df-d089734979cf.png)

**Comment by zddewe** [comment]
@828768 有没有搞错哇，会被请喝茶( ^‐^)_~~

**Comment by ogays** [comment]
@zddewe 喝茶净化思想

**Comment by 828768** [comment]
@zddewe 要喝茶怎么样都会被喝茶的，放心吧。这个客服插件是不错，但最高效的还是QQ

**Comment by ssrpanel** [comment]
@ogays @828768 @zddewe @slobber 网站统计代码、客服统计代码配置加上了，git pull 一下，然后倒入最后一个sql/update/20180413.sql到数据库即可
