### ISSUE TITLE
通过订阅无法获得混淆参数

### ISSUE THREAD

**Issue by yulewang** [ssrpanel/SSRPanel#427]
通过订阅获取的节点信息无法获得混淆参数, 对节点服务器似乎不太安全.

**Comment by ssrpanel** [comment]
截图？

**Comment by 828768** [comment]
用户混淆参数留空，节点混淆参数填了，客户端通过订阅节点拿到的节点信息里没有混淆参数。节点二维码和ssr链接里是有混淆参数的。
![image](https://user-images.githubusercontent.com/6386202/38768380-7cc13d44-4025-11e8-8c2e-fc83e14445ce.png)

**Comment by XD2333** [comment]
确实,更新订阅节点混淆参数无法推送到win和安卓客户端，截图不知实际情况，亲自试下有没有推送到客户端了然

**Comment by yulewang** [comment]
@ssrpanel  配置应该没有问题，不需要截图了，因为无论面板展示还是通过Scheme和二维码都是可以正常获取混淆参数（在我报这个之后@ssrpanel 修复了https://github.com/ssrpanel/SSRPanel/issues/391）
但在几个客户端上通过订阅都拿不到。

**Comment by ssrpanel** [comment]
那估计是bug，我查查

**Comment by ssrpanel** [comment]
混淆参数取得规则是这样：1.优先取用户的混淆参数（目前没开放给用户自己设置，我也觉得完全没必要）
2.如果用户没有设置混淆参数，就取节点设置的混淆参数（这样最合理）

**Comment by 828768** [comment]
> 1.优先取用户的混淆参数（目前没开放给用户自己设置

@ssrpanel 这个功能不是已经对用户开放了吗？用户后台有这个设置入口，整个ssr设置功能确实都应该屏蔽掉。

> 如果用户没有设置混淆参数，就取节点设置的混淆参数

这个应该的，可现在实际上不是

另外，发现macOS 10.13上订阅节点能更新成功，却无法正常使用，客户端日志报 `ERROR: getsockopt error code 0 61` ，跟[这里的错误](https://github.com/shadowsocks/ShadowsocksX-NG/issues/716)是一样的。而同样的账号和客户端，自己装的一个10.12系统却能正常，客户端版本也前前后后试过了，不知道什么原因，有人遇到过吗？怎么解决？
用的这个客户端：https://github.com/qinyuhang/ShadowsocksX-NG-R/releases

**Comment by ssrpanel** [comment]
@828768 不用看了，mac的客户端改了，网址必须上https

**Comment by 828768** [comment]
@ssrpanel 没上https是订阅节点更新失败，已经上了的。
现在这个是节点更新成功，服务器测速也能正常的，但是代理不成功，我怀疑是系统和客户端的兼容问题，回头有环境换个客户端试试，之前只试了同客户端换版本

**Comment by ssrpanel** [comment]
已修复
