### ISSUE TITLE
443单端口无法统计流量以及不兼容SS协议

### ISSUE THREAD

**Issue by nishuo** [ssrpanel/SSRPanel#429]
这个问题困扰几天了...定时任务执行状态正常. www用户组 目录也是.
后面都有_compatible但是SS协议一直无法连接。
common.py:238 unsupported addrtype 69, maybe wrong password or encryption method
SS协议连接会出现这个..并且会去连接user-config.json文件的"redirect": ["www.amazon.com", "images-na.ssl-images-amazon.com", "m.media-amazon.com", "kdp.amazon.com", "php.net"],各类网站。

单端口下SSR正常使用，无法统计流量
单端口下SS无法正常使用,无法统计流量

后端使用胖虎修改版的 https://github.com/ssrpanel/shadowsocksr

以下是我的配置信息。
>additional_ports"
 : {
        "80": {
            "passwd": "onepispeed",
            "method": "aes-256-cfb",
            "protocol": "auth_sha1_v4_compatible",
            "protocol_param": "#",
            "obfs": "tls1.2_ticket_auth_compatible",
            "obfs_param": ""
        },
        "443": {
            "passwd": "onepispeed",
            "method": "aes-256-cfb",
            "protocol": "auth_sha1_v4_compatible",
            "protocol_param": "#",
            "obfs": "tls1.2_ticket_auth_compatible",
            "obfs_param": ""
        }

**Comment by yulewang** [comment]
协议(protocol)配置为 auth_aes128_md5 或 auth_aes128_sha1
https://breakwa11.blogspot.hk/2017/01/shadowsocksr-mu.html

你这问题和面板没有关系

**Comment by nishuo** [comment]
只有md5和sha1才支持单端口使用ss吗？

**Comment by nishuo** [comment]
还是不行。。SS协议无法连接，无法统计使用流量

**Comment by ssrpanel** [comment]
你配置了单端口还要用原版协议？什么鬼
