### ISSUE TITLE
小bug

### ISSUE THREAD

**Issue by 64611187** [ssrpanel/ssrpanel#43]
流量结算设置的1.3在流量日志里显示的是1
![image](https://user-images.githubusercontent.com/18624659/31022405-477bff98-a56b-11e7-94bb-13c748a9728a.png)
![image](https://user-images.githubusercontent.com/18624659/31022456-6b88f2ce-a56b-11e7-8d11-ed03787e40dd.png)

**Comment by ssrpanel** [comment]
@64611187 这个你必须设置节点里的SSR配置，面板的这个设置是用来给用户看的

**Comment by 64611187** [comment]
上图阿里云设置的流量比例是1.3
但是日志却是1应该不是设置的问题把
