### ISSUE TITLE
关于数据库和商品的问题

### ISSUE THREAD

**Issue by 514454786** [ssrpanel/SSRPanel#431]
因为之前在后台自己修改过客户的流量，导致了现在就算更新了最新面板，这些被修改过的客户购买商品是不会增加流量的，只会改变到期时间。如果我把原来数据库中的user列表导入到一个全新的数据库，那么这些被修改的用户就可以自己购买商品并且不会出现不增加流量的事（ps:已实操，可行），但会不会出现到期不断开连接的情况呢？求问于胖虎大神！最好能修复第一个问题，这样我就不用更换user数据库了。下面附送图片。

**Comment by 514454786** [comment]
![image](https://user-images.githubusercontent.com/35135762/38766374-e72fc942-4003-11e8-81db-24b31f3200b6.png)

**Comment by 514454786** [comment]
![image](https://user-images.githubusercontent.com/35135762/38766385-1621514e-4004-11e8-982a-63eef9f389bf.png)

**Comment by 514454786** [comment]
![image](https://user-images.githubusercontent.com/35135762/38766393-367ad032-4004-11e8-87eb-ea1f1094d1dd.png)

**Comment by 514454786** [comment]
![image](https://user-images.githubusercontent.com/35135762/38766398-42efea96-4004-11e8-81ab-cad0cf0e9212.png)

**Comment by 514454786** [comment]
![image](https://user-images.githubusercontent.com/35135762/38766406-6d619676-4004-11e8-9fa9-366f02b36957.png)

**Comment by XD2333** [comment]
要不要考虑付费，包解决

**Comment by XD2333** [comment]
这样的情况得解决，要不然面板没法用，贴下storage/logs今天一部分日志上来

**Comment by 514454786** [comment]
我相信胖虎能解决，已经赞助多次了。往后还是会继续赞助胖虎的

**Comment by XD2333** [comment]
my昵称。看下你的网站目录下的文件权限是755还是644 ,www或root

**Comment by XD2333** [comment]
他没有空，再者，这不是bug

**Comment by 514454786** [comment]
权限是755

**Comment by XD2333** [comment]
文件夹权限还是文件是755

**Comment by 514454786** [comment]
你是指storage的权限还是所有文件和文件夹的权限？文件夹的权限是755，部分文件是644

**Comment by XD2333** [comment]
说不能解决，付费

**Comment by 514454786** [comment]
谢谢，不用

**Comment by 514454786** [comment]
扯什么收费的，不都在用胖虎的面板么，小白怎么了？不会用又怎么了？我刚开始搭建都出错，现在还不是一步一步摸索出来了。我问心那句，用胖虎面板，我一直都有赞助。新手有问题，我也帮忙答一下。就我提的这个问题，上面说收费的，不愿意说就算。反正可以慢慢能整明白怎么回事。不乐意就别帮。后边一条我会发评论发解决方法。

**Comment by 514454786** [comment]
如果遇到像我这种情况的：曾经把用户流量重置为0，或者输入值低于使用流量值，客户会出现数据错误。表现为这些客户购买商品只改变时间，不改变流量。
解决方法：数据库——order——删除错误账号的订单信息。账号就会恢复正常（已实操证实）

**Comment by ssrpanel** [comment]
marked

**Comment by ssrpanel** [comment]
最迟5月会处理，近期较忙，需要大的重构
