### ISSUE TITLE
支付模块建议

### ISSUE THREAD

**Issue by ogays** [ssrpanel/SSRPanel#434]
建议增加支付宝 微信 QQ支付模块，毕竟有赞云不是免费的，很多人玩不起这个支付系统。虽然卡券也可以代替支付，但是大多数客户喜欢直接支付购买产品。

**Comment by ssrpanel** [comment]
@ogays 是100%免费的，请看wiki，是微小店，不是微店。。。

**Comment by ogays** [comment]
@ssrpanel 必须开通有赞云微商城才可以进行支付，小店的需要申请下单API才能进行支付。
![qq 20180415012548](https://user-images.githubusercontent.com/32096394/38770863-f33bb834-404b-11e8-9f79-582b607e37d4.png)

**Comment by ogays** [comment]
![qq 20180415012749](https://user-images.githubusercontent.com/32096394/38770889-43bf02fc-404c-11e8-8db7-8858ea03fbc8.png)
![qq 20180415012833](https://user-images.githubusercontent.com/32096394/38770895-54f1264a-404c-11e8-913a-1d2b1319a1e6.png)
正确配置会显示错误

**Comment by ogays** [comment]
@ssrpanel 应该是更新后文件权限问题
