### ISSUE TITLE
2018/4/14 在git更新后部署 出现错误

### ISSUE THREAD

**Issue by Dennishaha** [ssrpanel/SSRPanel#435]
2018/4/14 在git更新后部署 出现错误

ErrorException
Undefined index: website_analytics

in LoginController.php (line 128)
--
at HandleExceptions->handleError(8, 'Undefined index: website_analytics', '/www/wwwroot/ssrpanel/app/Http/Controllers/LoginController.php', 128,array('request' => object(Request), 'view' => array('is_captcha' => '0', 'is_register' => '1')))in LoginController.php (line 128)
at LoginController->index(object(Request))
at call_user_func_array(array(object(LoginController), 'index'), array(object(Request)))in Controller.php (line 55)
at Controller->callAction('index', array(object(Request)))in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(LoginController), 'index')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 574)

**Comment by ogays** [comment]
看wiki

**Comment by ogays** [comment]
进到ssrpanel目录下执行：
git pull

如果每次更新都会出现数据库文件被覆盖，请先执行一次：
chmod a+x fix_git.sh && sh fix_git.sh

如果本地自行改了文件，想用回原版代码，请先备份好 config/database.php，然后执行以下命令：
chmod a+x update.sh && sh update.sh

如果更新完代码各种错误，请先执行一遍 php composer.phar install
