### ISSUE TITLE
订单下单后未支付不建议不能继续购买其他

### ISSUE THREAD

**Issue by yangzhili66** [ssrpanel/SSRPanel#436]
订单下单后未支付不建议不能继续购买其他，这样用户购买错误或想购买其他的套餐只能等订单自动关闭后购买，建议取消限制

**Comment by 514454786** [comment]
有赞要留信息，不敢用。假的一套下来贼贵

**Comment by ssrpanel** [comment]
@yangzhili66 你代码不是最新的，没有这个问题
@514454786 所有平台都要信息，真要查，那些第三方支付平台照样把信息交出去，你提款不需要用到实名账号是吗？
