### ISSUE TITLE
总消耗流量不统计,计划任务已经运行

### ISSUE THREAD

**Issue by a644326772** [ssrpanel/SSRPanel#437]
![qq 20180415114157](https://user-images.githubusercontent.com/27955995/38774726-0bcb4422-40a2-11e8-86c5-d41a2f88d5cf.jpg)
![qq 20180415114302](https://user-images.githubusercontent.com/27955995/38774735-2b7fef02-40a2-11e8-8aa8-916ccea64649.jpg)
![qq 20180415114426](https://user-images.githubusercontent.com/27955995/38774767-6539dd7a-40a2-11e8-9713-80e88c4b6e06.jpg)

**Comment by ogays** [comment]
禁用账户

**Comment by ogays** [comment]
好像是凌晨4点半统计
