### ISSUE TITLE
更新文件权限问题

### ISSUE THREAD

**Issue by ogays** [ssrpanel/SSRPanel#438]
@ssrpanel 跟新文件会导致storage 里面log文件夹里的文件权限错误，手动恢复文件导致有赞云支付id错误。

**Comment by ssrpanel** [comment]
你要切换到www 用户去 git pull

**Comment by ogays** [comment]
@ssrpanel 恩 我试试

**Comment by ogays** [comment]
@ssrpanel 更新机制需要改一下，我现在重新安装之后现在有赞云恢复正常了

**Comment by ogays** [comment]
@ssrpanel 用户流量也有问题，建议监控流量时间以秒定时。要不然用户会用超流量

**Comment by 828768** [comment]
千万别按秒，现在是按分钟的，超这么点完全没什么，甚至应该建议按半小时甚至一小时来执行，减少日志及服务器压力。
