### ISSUE TITLE
能不能实现邮件手动一键投递

### ISSUE THREAD

**Issue by GaHoKwan** [ssrpanel/SSRPanel#439]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问

比如想手动提醒某个用户流量使用情况,账户期限剩余天数

**Comment by lslzl3000** [comment]
支持，用户列表加上个按钮，一键提醒该用户流量和天数

@ssrpanel  另外，我觉得除了流量监控邮件提醒，因各种原因封禁的账号应该再自动发一封邮件通知用户比较好吧，我这边每天都有用户问我为什么不能用了，都是各种原因被封禁的，但是用户不知道为什么~

还有，上次提问为什么流量不提醒，看代码发现这个定时任务是daily()的，但是如果用户在一天内就从70%-100%，然后就禁用了~ 这种情况用户收不到任何提醒，而且很普遍

我建议，改为每小时检测，但是为了不重复发送提醒，邮件提醒只一次就行，最后再配合封禁时候的提醒

**Comment by ssrpanel** [comment]
你们想邮箱被列入警告吗？

**Comment by 828768** [comment]
可以额外设置个人工发信邮箱，隔三差五换个发信邮箱是不是很爽？

**Comment by ssrpanel** [comment]
@828768 我不会啊

**Comment by ssrpanel** [comment]
另外，我觉得除了流量监控邮件提醒，因各种原因封禁的账号应该再自动发一封邮件通知用户比较好吧，我这边每天都有用户问我为什么不能用了，都是各种原因被封禁的，但是用户不知道为什么~


各种原因都是什么原因？？@lslz3000

**Comment by 828768** [comment]
可能是我的邮件内容里带了教程链接这些

**Comment by GaHoKwan** [comment]
邮件群发功能好像拖了挺久了，是不是有什么大问题？

**Comment by ssrpanel** [comment]
不想放出来啊，能有什么大问题？
