### ISSUE TITLE
邮件提醒功能同一邮箱短时间内发送多次

### ISSUE THREAD

**Issue by gitject** [ssrpanel/ssrpanel#44]
![image](https://user-images.githubusercontent.com/31369527/31063715-0cb300e2-a768-11e7-9cab-347149f220ae.png)

**Comment by ssrpanel** [comment]
@gitject 问题已查正，正在修复中

**Comment by ssrpanel** [comment]
@gitject 已修复，请拉取最新的代码，全部改成了用定时任务来跑，所以要加入crontab，具体用法看项目主页，还有记得把/sql/update/20171002.sql导入到数据库
