### ISSUE TITLE
注册时报错

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/SSRPanel#442]
![m7fi l 50okh 90 yl 4c](https://user-images.githubusercontent.com/18015854/38785044-7cc4c87e-40e8-11e8-9f3d-3a6ea7f568d7.png)

即使出现报错，账号还是会注册； 
不过 不会发生激活邮件；

**Comment by ogays** [comment]
检查文件权限

**Comment by ZBrettonYe** [comment]
@ogays 哪个一个文件夹的权限？

**Comment by ogays** [comment]
Mail文件改了么 邮件添加了没

**Comment by ZBrettonYe** [comment]
@ogays 没改，添加了

**Comment by ZBrettonYe** [comment]
咩~

**Comment by ZBrettonYe** [comment]
@ssrpanel 之前都正常的 ， 不知道怎么的 就开始报错了

**Comment by biigaa** [comment]
怎么解决的?
