### ISSUE TITLE
SSR二次开发客户端交流群

### ISSUE THREAD

**Issue by ilovebamboo** [ssrpanel/SSRPanel#443]
群主关闭了群，所以新建一个# 

> 二次开发客户端群 
[点我加入](https://t.me/joinchat/Gc7hiUtsO-xDFeGSXRmZWA)

**Comment by 828768** [comment]
弄了个SS小白群，[快点此加入](https://t.me/joinchat/IHV6pQl1HqHuDHacBJdyrw)

**Comment by ssrpanel** [comment]
已入，我分享我自己用.net framework 4.6 下编译的 C#版本，精简了菜单在群里

**Comment by ilovebamboo** [comment]
![allow vpn configuration](https://user-images.githubusercontent.com/6214084/39101419-eba4ec68-46cb-11e8-8d0b-060e5184906a.png)
![confirmation screen](https://user-images.githubusercontent.com/6214084/39101420-ebde043a-46cb-11e8-805d-2059ee6628e6.png)
![select country](https://user-images.githubusercontent.com/6214084/39101421-ec163b48-46cb-11e8-830b-96657c118d71.png)
![select premium plan](https://user-images.githubusercontent.com/6214084/39101422-ec4f40be-46cb-11e8-9556-e6dcef2c51d1.png)
