### ISSUE TITLE
建议去掉结算比例提示

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#446]
首页的结算比例提示有点多余：
1. 用户不知道结算比例做什么的，产生各种疑问，并没有什么益处
2. 用户问完一圈也根本不关心结算比例的事

建议去除用户界面结算比例相关提示：
1. 去除结算比例相关提示，包括节点下方的结算比例的图标按钮，那个地方可以腾出来给其他用途，比如显示节点负载状态
2. 订阅节点按钮那栏的文字提示去掉结算比例的说明，改成：`订阅节点：客户端可自动同步更新服务商节点信息，点此显示订阅地址`

**Comment by ssrpanel** [comment]
已改进，等待更新
