### ISSUE TITLE
发现以下bugs，求作者dalao尽快修复

### ISSUE THREAD

**Issue by tonychanczm** [ssrpanel/SSRPanel#447]
发现下列bug：
1.当用户已经过期一段时间后再续费购买套餐时，如某用户是1月1日过期，他在4月1日续费一个月，那么他的状态还是过期的，有效期只被调整到了2月1日。
2.当用户使用余额付款时，套餐里面的流量会莫名其妙地减少10gb

**Comment by ogays** [comment]
@tonychanczm 流量购买请使用流量包，套餐适合月付用户

**Comment by tonychanczm** [comment]
@ogays 不是的，是在购买初始套餐的时候就会少10g，这就很奇怪。因为我有个套餐是10g的，又客户反馈说买了之后没有加流量，这就好奇怪了

**Comment by 514454786** [comment]
呵呵，请看我的贴 #431 ,把你数据库对应的商品删除，搞定。有人要收钱哦

**Comment by 514454786** [comment]
哦对了，是商品订单，不是商品。该账号下所有的订单都删除，即可。 @tonychanczm

**Comment by ssrpanel** [comment]
已修复，等待提交
