### ISSUE TITLE
删除日志文件重建后日志分析报错

### ISSUE THREAD

**Issue by 64611187** [ssrpanel/ssrpanel#45]
![vh x2jplmi z4_z5f _ of](https://user-images.githubusercontent.com/18624659/31109367-1c904e82-a832-11e7-9bed-0d17be613eab.png)

删除/shadowsocksr/ssserver.log和/public/ssserver.log
运行logrun.sh
 cd  /www/wwwroot/ssrpanel/ssrpanel/storage/app/public/
 ln -S ssserver.log /home/shadowsocksr/ssserver.log
chown www:www ssserver.log
之后就这样了

**Comment by ssrpanel** [comment]
@64611187 我复现一下看看，理论上不应该出现

**Comment by ssrpanel** [comment]
无法重现

**Comment by 64611187** [comment]
```
  // 日志分析
    public function analysis(Request $request)
    {
        $file = storage_path('app/public/ssserver.log');
        if (!file_exists($file)) {
            $request->session()->flash('analysisErrorMsg', $file . ' 不存在，请先创建文件');

            return Response::view('admin/analysis');
        }

        $logs = $this->tail($file, 10000);
        $url = [];
        foreach ($logs as $log) {
            if (strpos($log, 'TCP connecting')) {
                continue;
            }
```
把($file, 10000)改成100后不会报错了
`$logs = $this->tail($file, 100);`

但是刷新页面11条日志有时候会变成5条不知道为什么


![n](https://user-images.githubusercontent.com/18624659/31212386-cecca7de-a9d2-11e7-8706-62f68d4b06f8.png)
