### ISSUE TITLE
注册、添加用户出问题

### ISSUE THREAD

**Issue by liganss** [ssrpanel/SSRPanel#453]
能正常登录使用，注册时候出现这个
![qq 20180418200843](https://user-images.githubusercontent.com/30563823/38931043-7ad276f2-4344-11e8-9dc3-07fd8dd881e0.jpg)

**Comment by WTFTWTM** [comment]
这个好像是权限问题

**Comment by liganss** [comment]
问题找到了，之前手动换了端口，我现在又修改回去 解决了
