### ISSUE TITLE
关于用户过期后依然可以使用的问题

### ISSUE THREAD

**Issue by qq3461269698** [ssrpanel/SSRPanel#455]
再用户使用时间到期后建议可以直接清空用户流量  或者直接禁用用户  直到再次购买

**Comment by xiaoanweiwu** [comment]
麻烦自己注意下，你自己的问题。定时任务里有过期禁用。

**Comment by 514454786** [comment]
小白同问，不清楚楼上说的定时任务在哪里

**Comment by 514454786** [comment]
![image](https://user-images.githubusercontent.com/35135762/38968605-caa1102e-43be-11e8-909c-d38edeeb3fac.png)
开了的，我也有用户账号过期，流量未用完，依旧可以用。不知道是不是数据库出的问题

**Comment by 828768** [comment]
[SSRpanel搭建相关设置问题](http://sobaigu.com/shadowsocks-ssrpanel-setting.html)
