### ISSUE TITLE
有没有免费的在线支付api

### ISSUE THREAD

**Issue by GaHoKwan** [ssrpanel/SSRPanel#456]
自带的有赞云每个月要交400块钱的授权费,都足够租40台后端服务器了
简直贵得不可理喻

**Comment by GaHoKwan** [comment]
![qq20180418-215940](https://user-images.githubusercontent.com/7671203/38936643-d37f298a-4353-11e8-9dd8-8efec75d809d.png)

**Comment by xiaoanweiwu** [comment]
微小店微小店，麻烦仔细看看。

**Comment by GaHoKwan** [comment]
您的店铺未购买App开店服务，请领取体验包或购买，然后弹了一个9800块钱的界面出来,我无语了

**Comment by GaHoKwan** [comment]
![wx20180418-232503](https://user-images.githubusercontent.com/7671203/38941734-c8856f6a-435f-11e8-9ccd-de40fe9c1fed.png)
![wx20180418-232517](https://user-images.githubusercontent.com/7671203/38941738-cadf9db2-435f-11e8-8b20-7e61f69aa1bb.png)

**Comment by ogays** [comment]
请看wiki  微小店 不是微商城

**Comment by GaHoKwan** [comment]
微小店是不能绑定的有赞云,根本没有这个选项
![wx20180418-233948](https://user-images.githubusercontent.com/7671203/38942599-ceab45b6-4361-11e8-80df-ac677499a6ba.png)

**Comment by GaHoKwan** [comment]
好像是设置错了
