### ISSUE TITLE
关于微小店绑定问题

### ISSUE THREAD

**Issue by WTFTWTM** [ssrpanel/SSRPanel#458]
微小店绑定完毕后购买提示Client_ID错误，经检查有赞云绑定无误，已经尝试重新创建应用并绑定，但依然无效，请作者帮忙查找一下问题

**Comment by SRCOL** [comment]
我也跟你一样，错误>检查>重建都不行，只有更换面板服务器才行（不知道重装面板行不行）

**Comment by GaHoKwan** [comment]
怎么解决？
