### ISSUE TITLE
没有对单端口多用户的支援嘛？

### ISSUE THREAD

**Issue by EasonSummer** [ssrpanel/ssrpanel#46]
找了作者很多页面都没有说明 所以发问

**Comment by ssrpanel** [comment]
@EasonSummer 那个我都没玩过呢，有教程么，哈哈哈哈哈

**Comment by EasonSummer** [comment]
@ssrpanel 破娃以前关于单端口多用户的说明https://breakwa11.blogspot.sg/2017/01/shadowsocksr-mu.html   
glzjin 那边是建立一个单端口承载账号 设置单端口节点 然后其他节点就能启用单端口多用户了

**Comment by 1021435278** [comment]
这个需要尽快考虑, 单端口多用户会减少被封的机会.特别是一些常用端口无法封.

**Comment by ssrpanel** [comment]
@EasonSummer 已实现，请更新代码，注意数据库
