### ISSUE TITLE
较全面有赞支付设置教程

### ISSUE THREAD

**Issue by WTFTWTM** [ssrpanel/SSRPanel#463]
我TM反手就是一个Issues，作者你可别嫌我烦
https://www.aliserver.net/?p=483

**Comment by WTFTWTM** [comment]
加到WIKI吧，我咋这么闲呢

**Comment by WTFTWTM** [comment]
另外我叫狐狸  不叫WTFTWTM

**Comment by ssrpanel** [comment]
@WTFTWTM 你tg号呢，拉你进群吹牛逼

**Comment by ssrpanel** [comment]
@WTFTWTM 已加入wiki
