### ISSUE TITLE
能不能对接一下wordpress 数据库登录用户 开源客户端

### ISSUE THREAD

**Issue by ilovebamboo** [ssrpanel/SSRPanel#464]
能不能对接一下wordpress 数据库登录用户？做前端说明用
[SSRpanel客户端开发交流群 点我加入](https://t.me/joinchat/Gc7hiUtsO-xDFeGSXRmZWA)

**Comment by SRCOL** [comment]
作者是免费更新维护的，怎么还这么多要求

**Comment by ssrpanel** [comment]
wordpress 真心没空，要写我会直接写一个完整的插件出来卖钱的
