### ISSUE TITLE
能不能优化一下一键导入的功能

### ISSUE THREAD

**Issue by GaHoKwan** [ssrpanel/SSRPanel#466]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问

就是节点那个小飞机按钮，目前是只可以弹出来一个窗口，而且里面的链接并不是超链接，是不可以点的

能不能优化一下实现多平台客户端状态下的一键配置，至少可以把这个界面改成可以直接点的

**Comment by tonychanczm** [comment]
这种东西自己改就可以了，当然，胖虎修改好之后不用自己每更新一次就改革半天是极好的

**Comment by tonychanczm** [comment]
![avatar](https://raw.githubusercontent.com/tonychanczm/public-files/master/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-04-20%20%E4%B8%8B%E5%8D%888.30.48.png)

**Comment by tonychanczm** [comment]
`<div class="modal fade draggable-modal" id="link_{{$node->id}}" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">{{$node->name}}的SSR/SS链接</h4>
                        </div>
                        <div class="modal-body">
                            <textarea class="form-control" rows="5" readonly="readonly">{{$node->ssr_scheme}}</textarea>
                            <a href="{{$node->ssr_scheme}}" class="btn purple uppercase" style="display: block; width: 100%;margin-top: 10px;">直接打开SSR</a>
                            <p></p>
                            <textarea class="form-control" rows="3" readonly="readonly">{{$node->ss_scheme}}</textarea>
                            <a href="{{$node->ss_scheme}}" class="btn blue uppercase" style="display: block; width: 100%;margin-top: 10px;">直接打开SS</a>
                        </div>
                    </div>
                </div>
            </div>`
感觉这样子加个按钮之后对于用户来说是极好的。 @ssrpanel

**Comment by Pinkpiglet** [comment]
@tonychanczm 谢谢大佬的代码

**Comment by GaHoKwan** [comment]
我觉得glzjinmod的sspanel v3的导入功能就做得挺好的,可以参考一下
https://github.com/esdeathlove/ss-panel-v3-mod/tree/dev

**Comment by SRCOL** [comment]
想法不错，滋磁一个

**Comment by tonychanczm** [comment]
@Pinkpiglet 英文提示不是说了嘛，你还没提交更改的文件

**Comment by Pinkpiglet** [comment]
@tonychanczm  怎么提交啊

**Comment by cdlaimin** [comment]
@Pinkpiglet  这种我一般都是 直接用更新覆盖本地文件
git reset --hard
git pull
这两个命令就是覆盖本地文件

**Comment by GaHoKwan** [comment]
这么麻烦干嘛,直接sh update.sh

**Comment by ssrpanel** [comment]
@tonychanczm 就喜欢你这种人！mark
