### ISSUE TITLE
查看提现管理里面的项目时报错？？大家也会有这样的情况码？

### ISSUE THREAD

**Issue by tonychanczm** [ssrpanel/SSRPanel#471]
赶脚好奇怪呀，不知大家有没有这样的情况的呢？
![avatar](https://raw.githubusercontent.com/tonychanczm/public-files/master/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-04-22%20%E4%B8%8A%E5%8D%8811.20.27.png)
![avatar](https://raw.githubusercontent.com/tonychanczm/public-files/master/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-04-22%20%E4%B8%8A%E5%8D%8811.20.42.png)

**Comment by hellodpex** [comment]
1.权限
2.数据库删了某些奇怪的东西
