### ISSUE TITLE
大佬好 这边我搭建好ssrpanel 后 有2个问题 第一是经过我测试好像限速没有任何效果 第2是 没有控制设备数的选项功能

### ISSUE THREAD

**Issue by Google688** [ssrpanel/SSRPanel#472]
大佬好 这边我搭建好ssrpanel 后 有2个问题 第一是经过我测试好像限速没有任何效果 第2是 没有控制设备数的选项功能

**Comment by hellodpex** [comment]
1.限速功能目前是没用的
2.设备控制功能也没上线
解决:修改user-config.json

"speed_limit_per_con": 0, '端口单线程速度,单位KB/S
"speed_limit_per_user": 0, '端口多线程速度,单位/KB/S
"protocol_param": "", '空则限制64设备
所有设置基于非原版并且不兼容_compatible才生效
tips:限速限制设备商用价值太大,不会放出来的哈哈

**Comment by 2717201365** [comment]
谢谢解答哈  没想到大佬回复的这么快。。吓一跳。。 上面那个限速是限制节点吗？ 限制每个账号怎么限速呢
