### ISSUE TITLE
建议增加有赞商家主动退款的功能，感觉如果出纠纷直接转账给买家不太好。。。

### ISSUE THREAD

**Issue by tonychanczm** [ssrpanel/SSRPanel#474]
https://www.youzanyun.com/apilist/detail/group_trade/seller_refund/youzan.trade.refund.seller.active
感觉不想让别人知道我其他常用的账号2333

**Comment by ssrpanel** [comment]
等我重构完整个商品结构，才能加，现在有坑

**Comment by 1021435278** [comment]
@估计重建多久? 正好今天我删库了,准备重装,如果时间不久就等你好了重装.

**Comment by ssrpanel** [comment]
商品那块已经重构完了，可以更新了，退款这个我得研究下api
