### ISSUE TITLE
数据库level有点小错误

### ISSUE THREAD

**Issue by SoDa-GitHub** [ssrpanel/SSRPanel#477]
https://github.com/ssrpanel/SSRPanel/blob/master/sql/db.sql
第179行
王者荣耀里其实是“至尊星耀”，而不是黑曜。。。

**Comment by ssrpanel** [comment]
@SoDa-GitHub 你tmd还真细心，不过这个等级这块我有规划将来再改进到别的地方用，以前是用来给用户按等级分配节点，现在暂时没有用了
