### ISSUE TITLE
SSR二次开发客户端交流群 

### ISSUE THREAD

**Issue by ilovebamboo** [ssrpanel/SSRPanel#479]
群主关闭了群，所以新建一个# 

> 二次开发客户端群 开源
[点我加入](https://t.me/joinchat/Gc7hiUtsO-xDFeGSXRmZWA)

![allow vpn configuration](https://user-images.githubusercontent.com/6214084/39101431-13fd8d0a-46cc-11e8-927b-6bb8cdef0a4a.png)
![confirmation screen](https://user-images.githubusercontent.com/6214084/39101432-1435e7c2-46cc-11e8-98ca-ab174f64b630.png)
![select country](https://user-images.githubusercontent.com/6214084/39101433-146e10fc-46cc-11e8-8a1f-acc6f0d16e29.png)
![select premium plan](https://user-images.githubusercontent.com/6214084/39101435-14a566ec-46cc-11e8-930d-8705cf591650.png)

**Comment by ssrpanel** [comment]
@ilovebamboo 你都搞出了产业链了？。。。

**Comment by xiaoanweiwu** [comment]
![5a080221-b086-4b2e-b7e9-4ea5a7d21387](https://user-images.githubusercontent.com/28782855/39112308-a7bd00c8-470a-11e8-8e1c-1efad3701e3b.jpg)

**Comment by 514454786** [comment]
这广告，贼烦人，里面要15W一个定制呢！

**Comment by cdlaimin** [comment]
骗一个是一个 15万 可以让人定制15个app+网站了

**Comment by ssrpanel** [comment]
@cdlaimin 不至于吧，15万。。

**Comment by cdlaimin** [comment]
@ssrpanel emmm 我回复的时候我前面还有一条信息的..不见了 TA说的15万
