### ISSUE TITLE
使用赞有云支付有点问题，胖虎大佬进来一下

### ISSUE THREAD

**Issue by suifengv32** [ssrpanel/SSRPanel#480]
我一个用户注册购买了，使用支付宝支付，然而支付成功后没有在后台显示已经付还是待支付状态，使用微信的好像没有这个问题
这是我用户发给我的截图
http://wp.lolimon.cn/index.php?user/publicLink&fid=f113cL1YnV-AC1430-JhncnwERsl2l92obBT_a2Z5i9ZrZm9lq_PelsowAA-cj1RoZzf3heALO9rEWM39AIaIV88w9VIvvX0Vo1sKYreKQp76O_LaFHS9hEe0aqy2lVQ&file_name=/0423_1.png
http://wp.lolimon.cn/index.php?user/publicLink&fid=515bdYHB49khmUVRZMKYWBcG1mB_RASZGHbPGhfVRkRL9zpg2dOPmFwVt9SE5d8VKQpgXZzAFir4ts-TVaAuqoGv_vUGdbjEDFxUoyfVDk1iHYR0VnBkmi72cAwX_jKO&file_name=/0423_2.png

**Comment by ssrpanel** [comment]
这是因为有赞云回调请求不到你的面板机等不到你面板机的响应，你可以到有赞云后台看一下回调日志。还需要优化一下，你的面板最好是部署再日本，韩国，香港这种地方，请求时间端，

**Comment by suifengv32** [comment]
有赞云回调没有这个单支付的日志，昨天有个用户用微信购买了没有出现这个问题

**Comment by suifengv32** [comment]
@ssrpanel 面板机网络问题影响的吗？面板是不是应该部署在亚洲地区网路环节更好的vps上呢

**Comment by suifengv32** [comment]
谢谢了

**Comment by suifengv32** [comment]
@ssrpanel 好像问题找到了，storage/logs目录下生成的.log日志都是不是777权限，修改后立刻支付可以立刻跳转成功

**Comment by suifengv32** [comment]
但是我记得我设置了目录777权限和www用户组，不知道为什么生成的都不是777权限的日志文件

**Comment by suifengv32** [comment]
第二天生成的又变成644权限的了，然后有赞云又不能支付成功了

**Comment by suifengv32** [comment]
@828768 你好，请问如果是宝塔面板该怎么添加呢

**Comment by suifengv32** [comment]
@828768 大佬可以告知一下吗

**Comment by 828768** [comment]
宝塔的计划任务都是root的，进系统设置www的计划任务即可
