### ISSUE TITLE
有赞云价钱问题

### ISSUE THREAD

**Issue by xiaoanweiwu** [ssrpanel/SSRPanel#483]
商品设置价格为20元，用户仅需支付0.2元

<img width="279" alt="wx20180424-123643 2x" src="https://user-images.githubusercontent.com/28782855/39166449-577808e4-47bc-11e8-8b6b-86f88b858fba.png">
<img width="915" alt="wx20180424-123729 2x" src="https://user-images.githubusercontent.com/28782855/39166452-6067181e-47bc-11e8-9014-73682c8bca9c.png">
<img width="482" alt="wx20180424-123915 2x" src="https://user-images.githubusercontent.com/28782855/39166483-87d0c01c-47bc-11e8-816a-a4a37645d6f8.png">

**Comment by tonychanczm** [comment]
最新版本？感觉有点害怕，不敢更新233

**Comment by ssrpanel** [comment]
呃，我改一下，先别更新

**Comment by ssrpanel** [comment]
是bug，我引入的laravel特性那个模型修改器没用好，bug已处理，晚上回去提代码

**Comment by ssrpanel** [comment]
已经fix了，晚上回去提代码

**Comment by lzmfor** [comment]
好像还是不对。。还是百分之一

**Comment by ssrpanel** [comment]
已修复
