### ISSUE TITLE
自动定时任务添加错误，有帮忙看看的？

### ISSUE THREAD

**Issue by qq3461269698** [ssrpanel/SSRPanel#486]
在添加自动任务的时候出现错误无法添加
错误代码：errors in crontab file, can't install.
Do you want to retry the same edit? 
确认之后又回到要输入的页面
php /www/ysr.ykan.cc/artisan schedule:run >> /dev/null 2>&1
这是我的定时代码

**Comment by ssrpanel** [comment]
自己百度。。这种问题有点low。。你系统里没装crontab
