### ISSUE TITLE
界面显示服务器ip的问题

### ISSUE THREAD

**Issue by 514454786** [ssrpanel/SSRPanel#487]
![1111111111111111111111111111111](https://user-images.githubusercontent.com/35135762/39193519-557526ec-480e-11e8-99f2-57565e0e8a19.png)
如图，之前的面板是把ip4的地址隐藏的，只显示服务器名称，这样适用于试用的用户，而不至于直接暴露ip！希望能遮掩一下！

**Comment by yangzhili66** [comment]
着有什么意义尼？尼隐藏了客户怎么用？你是要给客户集成到软件一键登录获取吗？

**Comment by 514454786** [comment]
![image](https://user-images.githubusercontent.com/35135762/39194211-c3b10210-480f-11e8-854b-c16a214ed0be.png)这样的会更加好，一进去就看到Ip真的不怎么好，个人认为！
