### ISSUE TITLE
没有SSR连接客户端个数限制

### ISSUE THREAD

**Issue by dayuezai123** [ssrpanel/SSRPanel#490]
没有SSR连接客户端个数限制。
我记得以前安装91vps一键包带这个功能。希望大神加一个。

**Comment by 514454786** [comment]
![image](https://user-images.githubusercontent.com/35135762/39196477-d3352680-4814-11e8-96d0-4b1fa72172a9.png)
vi user-config.json 打开配置，这里填写数字，当然origin plain这个是不生效的，其他加密方式可以生效！

**Comment by dayuezai123** [comment]
能不能加到个人中心里。 管理员添加帐号的时候可以直接设置允许这个帐号使用几个客户端。。
