### ISSUE TITLE
更新完后创建订单出错 代码1054

### ISSUE THREAD

**Issue by Banxianlxx** [ssrpanel/SSRPanel#492]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问

git pull
chmod a+x fix_git.sh && sh fix_git.sh
php composer.phar install

都执行过了还是出现
创建支付订单失败：SQLSTATE[42S22]: Column not found: 1054 Unknown column 'order_sn' in 'field list' (SQL: insert into `order` (`order_sn`, `user_id`, `goods_id`, `coupon_id`, `origin_amount`, `amount`, `expire_at`, `is_expire`, `pay_way`, `status`, `updated_at`, `created_at`) values (180424235307985951, 1, 9, 0, 1500, 1500, 2018-05-24 23:53:07, 0, 2, 0, 2018-04-24 23:53:07, 2018-04-24 23:53:07))

**Comment by Banxianlxx** [comment]
从新注册了个新号创建订单一直转圈，原谅我是小白

**Comment by GaHoKwan** [comment]
导入sql

**Comment by lidingrong** [comment]
@GaHoKwan 
![default](https://user-images.githubusercontent.com/3904913/39225455-0df54902-487f-11e8-8e1f-dc7f6fe9cef1.png)

**Comment by SRCOL** [comment]
@Banxianlxx 导入数据库之后转圈的话执行
chown -R www:www storage/
chmod -R 777 storage/
