### ISSUE TITLE
有赞云价格Bug已经解决，但余额支付仍有bug。求胖虎大佬解决

### ISSUE THREAD

**Issue by tonychanczm** [ssrpanel/SSRPanel#493]
余额支付只扣了应付款的1%十块钱只收一毛。
另外，套餐时长能不能设置为最低1月呢？90天太长了有的人不买账。
胖虎大佬求解决～
@ssrpanel

**Comment by SRCOL** [comment]
我没这个问题。。。（还没更新，而且有赞云价格BUG有是个什么鬼？）

**Comment by tonychanczm** [comment]
@lidingrong 看来又有个bug，看来只能请胖虎大佬 @ssrpanel 去fix咯😂

**Comment by ssrpanel** [comment]
已处理
