### ISSUE TITLE
能不能实现让SSR和SS同时使用

### ISSUE THREAD

**Issue by GaHoKwan** [ssrpanel/SSRPanel#496]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问

现在除非是单独设置为origin或者加个auth_sha1_v4_compatible协议才可以使用ss
能不能让ss_node的compatible=1的时候让ss和ssr可以同时使用

**Comment by ganwen1994** [comment]
ssr和ss的数据库版本本身就可以同时使用，因为SSR是可以用原版协议的。

但是不建议，因为ssr混淆等一些都已经不推荐了，推荐的协议不兼容ss原版客户端。
