### ISSUE TITLE
建议增加群发自定邮件功能

### ISSUE THREAD

**Issue by tonychanczm** [ssrpanel/SSRPanel#498]
每次有公告要发布都要去数据库拖邮箱地址出来群发很不是滋味，希望能够增加一个群发邮件的功能，一键群发。

**Comment by ssrpanel** [comment]
@Pinkpiglet 什么购买邮件通知，解释一下

**Comment by tonychanczm** [comment]
@ssrpanel 估计是购买了服务之后发个邮件过去吧233

**Comment by ssrpanel** [comment]
正在做营销管理

**Comment by ssrpanel** [comment]
营销管理 通过微信订阅消息通道推送消息已上了，，那个邮件的那个再等等
