### ISSUE TITLE
账号问题

### ISSUE THREAD

**Issue by Pinkpiglet** [ssrpanel/SSRPanel#499]
用户未激活，但是可以用使用节点。

![image](https://user-images.githubusercontent.com/38532706/39343474-8a80d270-4a0f-11e8-9d45-a0a82f7d7dee.png)

**Comment by ssrpanel** [comment]
未激活当然可以使用了，激活不激活 意思是 这个账号能不能登录，如果系统设置里开启了需要激活，则这个账号未激活就不能登录

**Comment by Pinkpiglet** [comment]
好的 谢谢
