### ISSUE TITLE
一些建议和疑问

### ISSUE THREAD

**Issue by xiaoshaoyc** [ssrpanel/ssrpanel#5]
## 感谢作者无私奉献！在此提几个建议：

- 由于不是每个人都会使用 git pull 的，在更新时应该**说明更新方法**。

- 用户页面，节点连接方式应该不限于扫二维码

- 用户首页，那个“流量”是干什么用的，那个“35”又是什么？意义不明确

- 用户首页，没有系统公告的时候那一块空白有点丑

- 配置文件过于松散，能否集中到一个文件里？

## 再来说几点我的疑问：

- 有一次更新涉及到了database更新，请问能否在不删除已有数据库的前提下更新数据库？

- app性能堪忧，好像容易被打死。。

- 能考虑建个Telegram群吗？方便交流

## 最后提一下我的想法：

- 华莱士的鸡腿真好吃~

**Comment by ssrpanel** [comment]
@xiaoshaoyc 谢谢，还在更新中，用户端界面那个35我原本是要写成已用流量35%的，忘记更新代码了，还在开发中，最近加入一些注册限制，和系统配置，直接后天点一点就搞定的东西，我尽量做到操作简单。

1.目前暂时没有时间做到那么简单，适合有一定基础的人用
2.节点链接已经加了用户配置信息文字
3.系统公告优化了，再试试？
4.配置文件除了config/database.php 和 config/mail.php 其他废弃掉了，你再试试
5.代码还在优化，telegram群已建 看首页
6.目前做了一些防爬虫处理，尽量屏蔽爬虫，很多关键字都去掉了，目前还不会被识别到，导致网站域名被污染
7.持续更新代码
