### ISSUE TITLE
Script php artisan optimize handling the post-install-cmd event returned with error code 1

### ISSUE THREAD

**Issue by 1263297168** [ssrpanel/ssrpanel#50]
运行命令：php composer.phar install
报错如下：
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize

                                                                           
  [Illuminate\Database\QueryException]                                     
  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `config`)  
                                                                           

                                             
  [PDOException]                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             

Script php artisan optimize handling the post-install-cmd event returned with error code 1

这怎么解决呢？大佬们。

**Comment by 64611187** [comment]
database.php把数据库资料填进去
127.0.0.1改成localhost

**Comment by ssrpanel** [comment]
@1263297168  看 @64611187 的回答，先填/config/database.php 里的数据库链接配置再安装。
看来我的安装教程要重写了
