### ISSUE TITLE
优惠券计算bug

### ISSUE THREAD

**Issue by yulewang** [ssrpanel/SSRPanel#500]
优惠券计算多了10倍，成了骨折券。。。

订单:
优惠券 | 原价 | 实价
9折优惠券 | ￥199 | ￥1791

**Comment by slobber** [comment]
笑哭

**Comment by slobber** [comment]
看了下代码，估计楼主是以前建的优惠券，新版代码逻辑变化了，你只更新了代码，数据库里的优惠券记录没更新。

**Comment by yulewang** [comment]
@slobber 😂这样！下午我更新一下sql，再来update…

**Comment by ssrpanel** [comment]
应该没毛病的。你生成新的优惠券，并购买使用看看

**Comment by slobber** [comment]
原来9折数据库中存的9，然后在代码中读出后直接除10，新代码是在模型层完成的转换（存入数据库的是0.9）。

**Comment by yulewang** [comment]
@ssrpanel @slobber 新建一个优惠券依旧复现。

**Comment by slobber** [comment]
确实！！！
@ssrpanel 
https://github.com/ssrpanel/SSRPanel/blob/35b449387c7bbe99af0be09494b9d886bcacf72b/app/Http/Controllers/PaymentController.php#L56

```
            $amount = $coupon->type == 2 ? $goods->price * $coupon->discount : $goods->price - $coupon->amount;
```
这里是 bug 位置，计算总价直接用的乘过的值，应该用 $coupon->attributes['discount']，后面的应该用 $coupon->attributes['amount']

感人的 bug，幸亏不是除 10。.

**Comment by ssrpanel** [comment]
我在demo上测试过了，没毛病。

**Comment by yulewang** [comment]
@ssrpanel 
刚刚在demo上测试的结果，用的9折可重复折扣券。

![coupon_bug](https://user-images.githubusercontent.com/2869885/39512579-12ba8826-4e24-11e8-811a-93383805d032.png)

**Comment by miniaoe** [comment]
确实还是有这个问题的存在。目前我的方式是 8折 改为 0.8折。。。
