### ISSUE TITLE
大佬们 后台节点流量一直显示为零啊 我也试着看了很多问题并尝试解决可就是不行啊，我是宝塔搭建的。定时任务这么填的   php /home/wwwroot/SSRPanel/artisan schedule:run >> /dev/null 2>&1

### ISSUE THREAD

**Issue by Google688** [ssrpanel/SSRPanel#501]
大佬们 后台节点流量一直显示为零啊 我也试着看了很多问题并尝试解决可就是不行啊，我是宝塔搭建的。定时任务这么填的   php /home/wwwroot/SSRPanel/artisan schedule:run >> /dev/null 2>&1   

![123](https://user-images.githubusercontent.com/38600824/39372993-bc59d0b2-4a78-11e8-94b7-6dfa02d73ea4.jpg)
宝塔的目录是这样的  可以小白的解答一下吗。谢谢了。

**Comment by suifengv32** [comment]
设置任务没分钟，第二天会显示

**Comment by Google688** [comment]
很多天了。都还是这样显示okb的。。。

**Comment by Google688** [comment]
![456](https://user-images.githubusercontent.com/38600824/39392104-5ec9d2a2-4ae2-11e8-84bf-1519bb4433da.jpg)

**Comment by suifengv32** [comment]
设置定时任务为每分钟

**Comment by Google688** [comment]
老铁 执行每分钟了。这样设置之后第2天才会显示流量吗？

**Comment by suifengv32** [comment]
是的

**Comment by Google688** [comment]
好的 我试试 明天看看 老铁 谢了。

**Comment by Google688** [comment]
老铁 今天还是0kb啊 我昨天设置的每分钟。

**Comment by suifengv32** [comment]
你定时任务填的路径不是和你网站路径一样的吧，你自己看看，修改好路径

**Comment by Google688** [comment]
![image](https://user-images.githubusercontent.com/38600824/39403087-3ee8e564-4ba4-11e8-8cc9-cc5b558b59e7.png) 定时任务这么填 的。我的网站目录在 
![image](https://user-images.githubusercontent.com/38600824/39403102-975a4ea4-4ba4-11e8-8531-b45319afd897.png) 老铁你看看哪里不对

**Comment by suifengv32** [comment]
php /www/wwwroot//ssrpanel/artisan schedule:run >> /dev/null 2>&1

你路径都设置错了

**Comment by Google688** [comment]
。。。谢谢老铁啊。如此热心的。我第一次搭建这个。。。我明天在看看。#
