### ISSUE TITLE
按照教程全部安装完成，但是打开网站还是403....求解！

### ISSUE THREAD

**Issue by movecat** [ssrpanel/SSRPanel#502]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问

按照教程全部安装完成，但是打开网站还是403....求大神帮忙！！
用的是宝塔PHP7.1＋mysql5.6＋Nginx1.8环境

**Comment by 514454786** [comment]
伪静态写了没？运行目录设置对了吗？代搭（教）看名称
