### ISSUE TITLE
希望可以增加mu api支持其他服务端

### ISSUE THREAD

**Issue by lshen1120** [ssrpanel/SSRPanel#503]
支持mu api可以让服务端有更多其他选择，现在支持mu的服务端还是很多的,例如有go nodejs python版本
通过mu api进行管理也可以不让服务节点直连面板的数据库,更加安全

mu api的说明 https://sspanel.xyz/docs/muapi/v2
这是另一个sspanel的一个参考实现https://github.com/orvice/ss-panel/tree/v3/app/Controllers/Mu

**Comment by tonychanczm** [comment]
顶一个

**Comment by ssrpanel** [comment]
@lshen1120  我看了下，怎么用呢？这个相当等于节点不直接配置usermysql.json文件（数据库连接信息），那么节点怎么用这些api？这些是规范化的？

**Comment by lshen1120** [comment]
@ssrpanel 嗯，这算是一个约定俗成的规范，很多面板和节点服务分支都支持这个规范
节点服务支持mu api,就会通过mu api来获取用户配置，上传节点的流量数据，那个ss-panel就是一个实现的服务端可以参考一下

**Comment by kuangshao11** [comment]
隔壁django-sspanel已经实现了，可以参考。不过webapi的话，网页一炸所有节点都连不上了吧。。。

**Comment by lshen1120** [comment]
@ssrpanel 是给后端ss用的，就是通过web api，而不是直接访问数据库
https://sspanel.xyz/docs/muapi/v2 这个是文档的
https://github.com/orvice/ss-panel/tree/v3/app/Controllers/Mu 这是一个按照上面文档实现的panel例子
https://github.com/fsgmhoward/shadowsocks-py-mu 这个是实现对接mu api 后端

我提了一个PR，可以看一下，有个路由问题我不知道什么原因注册不上去

**Comment by Chennhaoo** [comment]
各位大佬写的很详细啊，我等小白就只有支持了。
感觉这个接口可以实现限速、限设备数等的功能，说错了大佬不要打我~~

**Comment by ssrpanel** [comment]
@lshen1120 你这个ssrpanel.xyz域名很官方。。。

**Comment by ssrpanel** [comment]
sspanel 的mu api 看起来很有问题。我会按照我的风格写一个的，更偏向实际商业开发下的那种风格

**Comment by ssrpanel** [comment]
go nodejs python版本
通过mu api进行管理也可以不让服务节点直连面板的数据库

哪些后端，

**Comment by ssrpanel** [comment]
@lshen1120 
@Chennhaoo 
@dovela 
@tonychanczm

**Comment by ssrpanel** [comment]
后端地址贴上来，已经在整mu api了，我看看都有哪些项目可以适配

**Comment by lshen1120** [comment]
https://github.com/mengskysama/shadowsocks/tree/manyuser
https://github.com/orvice/shadowsocks-go
https://github.com/catpie/ss-go-mu
可以看看，nodejs的ss据说比较坑，用的人也很少

**Comment by ssrpanel** [comment]
再来看一次

**Comment by ssrpanel** [comment]
mark one more time ， 群内大佬已经在改ss go db版，哦也
