### ISSUE TITLE
希望套餐能改会30天

### ISSUE THREAD

**Issue by 514454786** [ssrpanel/SSRPanel#505]
套餐现在只能选择90天，这。。。根本没办法售卖包月套餐啊！希望胖虎大大顺手改回来！有这需求的请扣1

**Comment by tonychanczm** [comment]
1,虽然可以自己改，但是怕出问题

**Comment by ssrpanel** [comment]
千万别改，如果套餐只要30天，那你直接用流量包 30天就可以了，因为30天的套餐没有意义。

**Comment by 514454786** [comment]
@ssrpanel 流量包30天的话，在30天后，流量和时间会清零么？
