### ISSUE TITLE
更新后系统设置挂了，

### ISSUE THREAD

**Issue by Banxianlxx** [ssrpanel/SSRPanel#507]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
Whoops, looks like something went wrong.
(2/2) ErrorException
Undefined variable: register_ip_limit (View: /www/wwwroot/ssrpanel/resources/views/admin/system.blade.php)

**Comment by ssrpanel** [comment]
加入tg订阅组，看更新信息。。。。
