### ISSUE TITLE
当前发现的漏洞和不足

### ISSUE THREAD

**Issue by WTFTWTM** [ssrpanel/SSRPanel#509]
下面是我用了这段时间的用户反馈
1.更新到最新版本容易出现问题

- 就打比方说，在你的上上个版本安装的，我都不敢更新，更新百分百会出一大堆问题，要修复根本无从下手

- 就拿现在这个版本说，你在数据库新增了一个Good什么什么的数据表，然后不动数据库直接更新又会出现报错，我还修改了部分界面样式，重装又要再次修改一遍，数据库还不兼容老版本，我只能重新备份一下数据库，再导入数据。

- OK 你觉得问题就这么多了？不不不，在处理完毕能正常登陆后，你会发现你无法登陆到系统的管理员设置面板了。就连新用户注册都是报错，怎么修？根本没办法修，找不到问题！

目前就这么多问题  给你几个解决方案

更新不使用GitHUB的推送功能，那样会覆盖已修改的文件，如果保留本地则会出错（亲测）
既然不使用GayHub的更新，那如何更新？

- PHP检测版本更新并在管理员后台提示，如果用户确定更新，则从云端下载更新脚本

- 脚本怎么写？ 那这里有个方法，你每次发布版本之前，把这个版本的修改操作写到一个PHP文件中
例如你要求新建一个数据库，则在php中把脚本写好，Config文件中标明的有链接用户信息。

再例如你更改了一个文件，就直接从云端下载覆盖，这样除非你重做，要修改的文件数量也会大大降低。

再例如你删除了一个文件，php有文件删除的操作方式的对吧？？

还有吗？
So TMD Easy

这TM不比辣鸡GayHub的更新方式高到天上去了？？

不说了我还得滚回去修出错

![qq 20180430051004](https://user-images.githubusercontent.com/34577787/39411139-a7431f48-4c36-11e8-94ae-5e673a87594a.png)

![qq 20180430052449](https://user-images.githubusercontent.com/34577787/39411147-d6a87eea-4c36-11e8-99a5-3a5cbc3fb0c1.png)

**Comment by WTFTWTM** [comment]
好了 现在根本修不好了
只能重装丢弃其他表  能恢复的只有用户数据库   淦

**Comment by WTFTWTM** [comment]
我现在想杀人

**Comment by 514454786** [comment]
我深夜测试了一大堆，商品购买就是个坑！继续发提问了，无奈

**Comment by 514454786** [comment]
一直用胖虎的面板，就是为了简洁，但现在弄得不 人性化了！

**Comment by 514454786** [comment]
@WTFTWTM 你这种情况大概是sql没导入，去SQL文件夹把这几个月的sql下载好，导入到你的数据库就好了，更新出问题的确很频繁，但胖虎也很努力更新了

**Comment by WTFTWTM** [comment]
@514454786 我现在在尽力恢复数据库 历史数据库已经全部消失，幸好在升级之前我备份了一下  我现在在一张表一张表的处理手动恢复，就因为TM的这个该死的更新，傻逼的一笔！！！

**Comment by WTFTWTM** [comment]
@514454786 我承认胖虎很努力了 发工资我会给他打赏个一二百  但是问题是现在弄得我火大

**Comment by WTFTWTM** [comment]
@514454786  按照我说的方式来进行更新根本不会出问题，Git Hub 更新不跟你讲道理 就是覆盖文件 难受的一笔

**Comment by WTFTWTM** [comment]
@tonychanczm
那到底是哪个更方便更适合新手或者不太熟悉的人呢？？

**Comment by ssrpanel** [comment]
你们的要求太高了，想要一键搞定还想挣钱，还不会最基本的导入数据库还从来不看更新了什么

**Comment by WTFTWTM** [comment]
@ssrpanel 问题是我已经导入了数据库，报错一大堆。怪我咯？？？我就是两个版本没更新，因为就怕出现这种报错。这是看你更新了自动标签才更新到最新版，结果依旧崩了。
