### ISSUE TITLE
支持多服务器吗?

### ISSUE THREAD

**Issue by docrun** [ssrpanel/ssrpanel#51]
多台服务器上面独立IP的SSR

**Comment by 64611187** [comment]
配置ssr的数据库信息
ssrpanel的数据库要对外开放新手不建议这样毕竟暴露mysql端口风险大

**Comment by ssrpanel** [comment]
@docrun 支持啊，每个服务器上设置一个SSR后端（就是一个节点），数据库可以单独一个服务器，也可以跟网站放一起，当做主节点，主节点可以不放SSR后端，所有子节点都用来连接主节点，开放iptables

**Comment by ssrpanel** [comment]
@64611187 这个很正常，主节点、子节点配置很简单啊，iptables限制一下就行了，主节点给每个子节点开放一个仅有这个子节点的IP可以连接的只有增删改查这个ssrpanel数据库的账号就行了
