### ISSUE TITLE
还是商品的坑，有问题的都进来看看

### ISSUE THREAD

**Issue by 514454786** [ssrpanel/SSRPanel#510]
昨晚提的问题要求套餐改回30天，胖虎说直接用流量包，时间设置为30天就好了。好吧，我去设置，然后测试了半天，发现如果再次购买，有效时间不会改变，曾经购买过套餐的用户，重置流量日期不变！胖虎，我还是建议套餐弄回30天起步吧！现在根本无所适从啊！如下图，买了2个30天的流量包，流量叠加是对的，时间只有一个月，重置日期为25号！
![image](https://user-images.githubusercontent.com/35135762/39411362-3ebcddba-4c3b-11e8-88a3-63c288b73587.png)

**Comment by 514454786** [comment]
一直用这个面板，但最主要的商品统计上不能这样出错啊，否则面板是真的没办法使用的！

**Comment by WTFTWTM** [comment]
同 我不明白不弄成随意设置的就算了  还TM九十天是搞什么事情？？？？？

**Comment by 514454786** [comment]
可那不是我们用户的需求啊！面板如果不能设置为用户需求的，那将是失败之作啊！

**Comment by SRCOL** [comment]
@tonychanczm 但是只要用户知道节点地址，就算没有tag也能用该节点，我提这个问题胖虎没回复就给closed了
