### ISSUE TITLE
tag的自动管理是极好的，但是貌似有一些问题。

### ISSUE THREAD

**Issue by tonychanczm** [ssrpanel/SSRPanel#512]
当tag移除后，用户是看不见节点列表了。但是有个问题，只要用户知道节点地址，并且以前的流量没有用完的话，就算没有tag也能用该节点喔，这样就很麻烦了。求胖虎大佬解决，谢谢。

**Comment by linuxtoddler** [comment]
用户过期。或者流量用完。就算知道节点也是链接不了的。

**Comment by SRCOL** [comment]
@tonychanczm 为什么你提这个问题没被closed，我的直接不回复就给closed，难道我说错什么了？

**Comment by ssrpanel** [comment]
“另外，希望tag到期之后是恢复到默认tags或者最好是原来的tags而不是删除所有tags（这是别人的反馈）”

@tonychanczm 这个我改一下

**Comment by ssrpanel** [comment]
已经优化了
