### ISSUE TITLE
订阅链接windows客户端能用。在andriod客户端却用不了

### ISSUE THREAD

**Issue by linuxtoddler** [ssrpanel/SSRPanel#513]
https://github.com/shadowsocksrr/shadowsocksr-android/releases/download/3.5.3/shadowsocksr-android-3.5.3.apk

这个是我下载的客户端。不知道这个是系统bug还是 客户端的问题。
我的订阅链接如下
http://ssr.hn88.info/s/Sbsrt
其他朋友，烦请测试。

**Comment by ssrpanel** [comment]
@linuxtoddler 咦。。我手上可是有3.5.4的版本。。。哈哈。还有自己编译的版本。。没毛病。

**Comment by ssrpanel** [comment]
只要有一个windows能用，安卓不能用，说明你安卓的版本有问题
