### ISSUE TITLE
提现审核的时候出现问题！

### ISSUE THREAD

**Issue by cmtomkan310** [ssrpanel/SSRPanel#515]
(2/2) ErrorExceptionTrying to get property of non-object (View: /www/wwwroot/ssrpanel/resources/views/admin/applyDetail.blade.php)
--
in 1df4453830c200ed95d4d4db032ee6452537ebe4.php (line 70)
at CompilerEngine->handleViewException(object(ErrorException), 1)in PhpEngine.php (line 44)
at PhpEngine->evaluatePath('/www/wwwroot/ssrpanel/storage/framework/views/1df4453830c200ed95d4d4db032ee6452537ebe4.php', array('__env' =>object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'info' => object(ReferralApply), 'list' => object(LengthAwarePaginator)))in CompilerEngine.php (line 59)
at CompilerEngine->get('/www/wwwroot/ssrpanel/resources/views/admin/applyDetail.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'info' => object(ReferralApply), 'list' => object(LengthAwarePaginator)))in View.php (line 137)
at View->getContents()in View.php (line 120)
at View->renderContents()in View.php (line 85)
at View->render()in Response.php (line 38)
at Response->setContent(object(View))in Response.php (line 201)
at Response->__construct(object(View), 200, array())in ResponseFactory.php (line 55)
at ResponseFactory->make(object(View), 200, array())in ResponseFactory.php (line 69)
at ResponseFactory->view('admin/applyDetail', array('info' => object(ReferralApply), 'list' => object(LengthAwarePaginator)))in Facade.php (line 221)
at Facade::__callStatic('view', array('admin/applyDetail', array('info' => object(ReferralApply), 'list' => object(LengthAwarePaginator))))in AdminController.php (line 1810)

**Comment by tonychanczm** [comment]
一样，同求解决

**Comment by ssrpanel** [comment]
测试一下demo.ssrpanel.com会不会有同样问题

**Comment by tonychanczm** [comment]
@ssrpanel  demo也这个问题喔

**Comment by cmtomkan310** [comment]
demo也存在这个问题，我觉得体现这块可以结合第三方支付一起改进。

**Comment by ssrpanel** [comment]
已修正，等待提交
