### ISSUE TITLE
建议用户可以存在多张待支付订单，以及可以进行取消订单

### ISSUE THREAD

**Issue by miniaoe** [ssrpanel/SSRPanel#518]
目前的机制是用户只要存在一张未支付的订单就不能再次购买，建议可以修改为用户可以存在多张未支付的订单或者用户未支付订单有一个上限比如3张未支付订单才会提示不可以进行购买，如果用户不想购买也可以进行取消订单。目前是无法取消订单的情况。

**Comment by cmtomkan310** [comment]
对，这个问题一直存在，也希望改进下！同时希望胖虎尽快支持第三方支付，有赞试用时间太短了，呵呵

**Comment by ssrpanel** [comment]
@xiaoanweiwu 很多人想挣钱，又不看wiki，连最基本的翻阅文档的能力都没有，知道我为什么把tg的千人讨论群关闭了把

**Comment by ssrpanel** [comment]
@miniaoe 好的，可以限制一下多张订单，之前的出发点是：如果用户不愿意付款，到期后支付单会自动关闭（如果没关闭说明你的定时任务没配好），因为创建过多的待支付订单，可能导致你的账号出现异常，被有赞给封了

**Comment by miniaoe** [comment]
@ssrpanel 感谢。

**Comment by GaHoKwan** [comment]
关于被有赞封号的问题可以实现本地购物车的逻辑,要确认支付的时候才会把订单提交到有赞,这样也可以实现取消订单,最好另外也实现管理员后台取消有赞订单的功能,虽然感觉代码量似乎有点大,O(∩_∩)O哈哈~

**Comment by ssrpanel** [comment]
@GaHoKwan 别逗，不请求有赞根本没法创建有赞的收款二维码
