### ISSUE TITLE
用户等级和节点等级问题

### ISSUE THREAD

**Issue by hansansui** [ssrpanel/ssrpanel#52]
用户等级达不到节点等级要求的时候，高级节点会自动停止该用户的端口服务，而满足该用户权限的节点，会继续保持服务吗

**Comment by ssrpanel** [comment]
@hansansui 不会，用户达不到对应等级的分组时，看不到对应更高级的分组下的节点

**Comment by ssrpanel** [comment]
只是看不到而已
