### ISSUE TITLE
邮件无效.

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/SSRPanel#520]
最近重装了系统,发现邮件无效了.
我是自建邮局按照下面提示做了,之前有效,为什么现版本无效?

php5.6版本后强制要求验证邮件服务器证书有效性,通过在config/mail.php 最下面增加下面语句就关闭了有效性验证并解决问题了.

———————-
‘stream’ => [
‘ssl’ => [
‘allow_self_signed’ => true,
‘verify_peer’ => false,
‘verify_peer_name’ => false,
],
],
———————-

**Comment by ssrpanel** [comment]
mark 收藏，已加入wiki

**Comment by cnken** [comment]
收到邮件格式如下：

激活账号
点击这里去【激活账号】，或者点击下面的链接（30分钟内有效）。

但是激活账号位置无超链接，下方也无链接地址~
