### ISSUE TITLE
新注册用户中心点击“ 显示订阅地址 ”报错

### ISSUE THREAD

**Issue by longdoer** [ssrpanel/SSRPanel#522]
新注册用户中心点击“ 点此显示订阅地址 ”报错如下
![qq 20180503205631](https://user-images.githubusercontent.com/16441085/39577673-8c553046-4f14-11e8-94c1-cbcd5b38a677.png)

**Comment by greatvpn** [comment]
同问，上次就反馈过 没敢再更新了 回滚到上一个版本了

**Comment by ssrpanel** [comment]
已修复，等待提交
