### ISSUE TITLE
账号禁用与解禁建议

### ISSUE THREAD

**Issue by Pinkpiglet** [ssrpanel/SSRPanel#524]
今天发现一个新问题，用户流量使用完了之后，推广注册送了流量，但是账号还是禁用状态。
建议规则如下
账号无流量－禁用－账号购买或其他方式获得流量－自动解除禁用

**Comment by ssrpanel** [comment]
mark ，，，好的

**Comment by Pinkpiglet** [comment]
@ssrpanel 辛苦大佬了
