### ISSUE TITLE
流量重置bug

### ISSUE THREAD

**Issue by yulewang** [ssrpanel/SSRPanel#525]
每五分钟一次的AutoResetUserTrafficJob，会在流量重置日不停的重置用户流量。

需要加一个flag，或者将重置job改为每天执行一次。

**Comment by ssrpanel** [comment]
还有这种事？我看看

**Comment by ssrpanel** [comment]
最新应该不会出现了

**Comment by ssrpanel** [comment]
@yulewang 麻烦再看看
