### ISSUE TITLE
知道作者不打算做支付宝微信等官方接口，但是还是想说一下。

### ISSUE THREAD

**Issue by aaaxiaoganaaa** [ssrpanel/SSRPanel#526]
大佬，用酸酸乳的不一定都是翻墙的，

也有回国的，比如我做的业务，就是给用户回国的，而且ICP和公安备案都过了公安局网监都说不违法的，大佬您目前做的有赞是挺方便，但是还是不如官方接口的方便，费率低，提现灵活等等。

大佬要考虑一下我的建议哦！

一个好东西，可以用来做很多的事情，为人民提供自由的网络，不管是回国还是出国，谢谢！

**Comment by 828768** [comment]
> 比如我做的业务，就是给用户回国的

很好奇是什么业务都有公安局网监背书了(#^.^#)

**Comment by ssrpanel** [comment]
如果你打算挣这块钱，我建议你先花钱找人二次开发，不然去用魔改，魔改里自带有支付宝插件。（或者我帮你联系赵大给你定制开发加密版）

**Comment by aaaxiaoganaaa** [comment]
我目前并没有使用您的面板，只是觉得这是一个好项目，可以尽力而为的完善提一些建议。

  以后如果有机会，可以尝试一下您的面板，或者找您定制。


@ssrpanel

**Comment by aaaxiaoganaaa** [comment]
@828768 我们这边如果要做公安备案，必须要去本地网安大队背书，说明业务类型等，至少我们这边是这样的。
