### ISSUE TITLE
重复购买不同套餐标签不会自动删除

### ISSUE THREAD

**Issue by WTFTWTM** [ssrpanel/SSRPanel#527]
第几个ISSUES了

用户在重复购买多个套餐后，上个套餐的标签并不会移除掉，注意：这些商品的标签是完全不相同的

但是上个套餐的流量总数却可以正常扣除，请修复这个BUG，

**Comment by 828768** [comment]
流量包是可以叠加的，本来就不该移除。

**Comment by WTFTWTM** [comment]
@828768 但是我说的是套餐

**Comment by ssrpanel** [comment]
修正了
