### ISSUE TITLE
微小店绑定好了（参数 client_id 不正确）

### ISSUE THREAD

**Issue by vinsanchen** [ssrpanel/SSRPanel#529]
授权完毕，推送服务也设定了（健康状态）
后台也设置完毕了，测试付款显示以下讯息：
  
创建支付单失败：参数 client_id 不正确
  
wiki过好像也有人有同状况，
不知道大家解决没有？

**Comment by SRCOL** [comment]
这个问题我在以前某个issues里回答过，但是我忘了具体在哪里，楼主可以慢慢去翻一下#滑稽

**Comment by vinsanchen** [comment]
感谢，我有看到您的回覆了！
但是不知道是不是我设定的问题，
未支付的单子一直没有过期...
现在一直卡着...单子也没办法删除@@"

**Comment by vinsanchen** [comment]
感谢，我有看到您的回覆了！
但是不知道是不是我设定的问题，
未支付的单子一直没有过期...
现在一直卡着...单子也没办法删除@@"

**Comment by yeehomlee** [comment]
@vinsanchen  你解决了吗？我也是一样的情况。
WIKI说的是换「微小店」，可是我也确实没注册错呀。

**Comment by SRCOL** [comment]
这个问题好像是自动任务还是Storage权限问题（一定是其中之一）我忘了是哪个

**Comment by vinsanchen** [comment]
我解决了：）
重新安装面板就好了！
但是重新安装之后要面对的问题就是定时任务，
等你重新装完就知道了🤣

**Comment by woodytang** [comment]
这个问题为啥要关闭？

这个不是权限问题，出问题在这段代码：
`if (Cache::has('YZY_TOKEN')) {
          	
            $token = Cache::get('YZY_TOKEN');
         
            if (isset($token['error'])) { // 错误兼容
                Cache::forget('YZY_TOKEN');
            } else {
                return Cache::get('YZY_TOKEN')['access_token'];
            }
        }`
缓存的token有问题，@作者 能不能请解释一下为啥要缓存token？我不太懂支付流程
