### ISSUE TITLE
商品套餐增加提前续费的逻辑

### ISSUE THREAD

**Issue by bingotl** [ssrpanel/SSRPanel#532]
到期时间问题：
像充值QQ会员一样，没到期之前购买套餐，可以延期而不是覆盖当前的到期时间。
https://t1.picb.cc/uploads/2018/05/07/27e5AT.jpg
像这样，在商品套餐里增加一个是否延期，
如果否，逻辑和现在一样，
如果是，那么到期时间会在原本的基础上再增加对应的天数。

已用流量问题：
如果套餐是延期，用户的已用流量保持不变（不重置流量）。

流量重置日问题：
如果套餐是延期，建议每个用户都有自己的流量重置日，例如我7号首次购买，如果我没到期一直续费，流量重置日都是7号不变。如果我已经到期了，等到10号重新购买，那么该用户的流量重置日变成每月10号

我认为这是很常用的月付计费模式吧，望胖虎采纳完善

By bingo

**Comment by tonychanczm** [comment]
顶一个

**Comment by cmtomkan310** [comment]
顶一下！

**Comment by cmtomkan310** [comment]
补充一下，套餐有效期必须大于90天，这个设计不知道为了啥？

**Comment by tonychanczm** [comment]
[fix.txt](https://github.com/ssrpanel/SSRPanel/files/1983825/fix.txt)
大概改了下，还没试过行不行2333

**Comment by 828768** [comment]
@cmtomkan310 不知道你们都在纠结什么，30天和流量包有区别？套餐本来就是按月重复的，你设置个30天然后就没下次了，意义何在？

如果非得按你们的要求来，那就都直接扔出论据是不是好点？或者直接砸点钱给胖虎让他跪舔，要不然作者也找不到推翻自己代码的动力，你说是不是？

**Comment by bingotl** [comment]
@828768 
我之前不知道套餐是按月来的，
其实区别就在于一点，现在的套餐要等过期后才能买，否则会重置已用流量和到期时间。那么如果想搞活动，搞个半年或者包年特价的优惠促销，但是用户还有20多天才到期，那用户也可以提前续费。我觉得这个需求不算推翻之前的逻辑吧。

**Comment by cmtomkan310** [comment]
@828768 
我相信用ssrpanel的用户不少，可能每个人的需求和出发点不同，我想说，请你客观点，我们提出这个问题，肯定多少是有点问题，套餐是按月，但是起步是3月，目前很多ssr用户都是按照月付费的，流量包模式就会出现上面提到的问题，系统是为用户服务的，不是咱们在这里纠结你、我思路的问题。我特别纳闷这有什么可急赤白脸的？我只是把我的问题，想法说出来，如果作者觉得可行就适当修改，如果不行就算了，就这么简单的事，难道遇到问题还不能说，活着说遇到问题就是我们自己脑子有问题？

再次强调，不用按照我们的意思来，我们没啥意思。就是想让ssrpanel更完美！

**Comment by 828768** [comment]
我也很无奈，摆事实讲规则你们不会，写那么大段说我急赤白脸，倒是把需求背景，功能要求，业务逻辑这些表述明白啊。

**Comment by cmtomkan** [comment]
四楼说的那么明白，看不懂吗？

**Comment by ssrpanel** [comment]
@cmtomkan310 我不觉得@828768说的有什么毛病，我就纳闷了，你用户按月付费，你不会设置一个流量包30天的吗？你愿意按月买，难道不愿意到期了再买一次？？？？

**Comment by ssrpanel** [comment]
什么时候买什么生效，30天过后不就失效了？没毛病。你设置一个30天的套餐，请问，30天后，找谁重置流量去？？

**Comment by ssrpanel** [comment]
这特么的根本就是伪需求

**Comment by cmtomkan310** [comment]
@ssrpanel 30天流量包，没有问题，谁都没说30天流量包按照月卡意思走有问题！假设：这个流量包30天 内有50G流量！
问题在于用户第一次购买流量包后，第29天续费，这个流量包，会出现什么问题？？？
1、因为第二次购买没有达到30天帐号禁用后购买，所以时间没有延续，还是按照第一次购买的时间算，也就是购买了2次，但是时间却是30天？懂了吗？说白了，这个流量包不能提前续费，只要提前续费就会出现问题，所以这个不是月卡的概念，懂了吗？最主要现在续费都是提前，没有往后拖到帐号禁用后再续费。

也别回复了，争论半天也没意义，我现在ssrpanel有1100多用户，我觉得我有一定发言权，很多问题是用户反馈的问题，我是上来提提，没说作者必须按照我们提出来的问题修改，我只是想让ssrpanel更符合逻辑！

**Comment by tonychanczm** [comment]
@cmtomkan310  你觉得他的业务逻辑不适合你那你自己改不就好咯？这么麻烦在这里说这么多不如自己去慕课网学学php学学laravel自己去改。
