### ISSUE TITLE
出现如下错误，已翻阅资料，无果

### ISSUE THREAD

**Issue by NutterChen** [ssrpanel/SSRPanel#536]
![1](https://user-images.githubusercontent.com/32509481/39699227-c32d0170-522a-11e8-8d51-a1453a8ec1f8.jpg)
大约在安装第9台服务端出现的，前面都没有问题，自己虽然不是高手，但还是尝试自己着手解决，翻阅了一些资料，无果，遂在此提交Issues跪求大神解决，小弟感激涕零！

**Comment by Pinkpiglet** [comment]
@NutterChen 善用搜索，可以电报找我。

**Comment by Pinkpiglet** [comment]
已解决，但是还是会出现间断碟机

**Comment by NutterChen** [comment]
@Pinkpiglet 我在ssrpanel的电报群发了这个问题  求大佬看到下私聊一下 这样也能不暴露大佬的信息 中午出现的这个问题  我错了很多资料 甚至把已经关闭的494个Issues翻阅完了都没找到结果 很伤

**Comment by echo-marisn** [comment]
解决方法 自己替换CyMySQL以前的版本 是由于最新CyMySQL不匹配

**Comment by Pinkpiglet** [comment]
@echo-marisn 节点间歇性碟机。。

**Comment by echo-marisn** [comment]
@Pinkpiglet  问题不是节点间歇性碟机....吧 管他的呢 能用就行

**Comment by Chennhaoo** [comment]
@echo-marisn 大佬，那个版本比较稳定啊

**Comment by echo-marisn** [comment]
@Chennhaoo 0.95的吧 就那个REL_0_9_5

**Comment by Chennhaoo** [comment]
@echo-marisn 谢谢

**Comment by NutterChen** [comment]
感谢各位大佬，已经解决了，我关闭Issues了

**Comment by vinsanchen** [comment]
已新增完毕@@"结果新节点好了，老节点挂了...
