### ISSUE TITLE
标签BUG提交

### ISSUE THREAD

**Issue by cmtomkan310** [ssrpanel/SSRPanel#542]
在线支付后，标签没有应用到用户账号上，但是用余额支付，是可以的！

关于订阅
目前订阅是可以选择订阅节点数量，但是没法控制那些节点愿意开发供大家订阅，建议：可否在节点配置列表增加个字段，可否订阅此节点，这样既方便订阅节点，也可取消在系统设置中订阅节点数量字段。只是建议，感觉这样更合理些！

**Comment by ssrpanel** [comment]
阔以阔以，marked

**Comment by tonychanczm** [comment]
@ssrpanel  感觉只要改一下YzyController.php就可以了

**Comment by Pinkpiglet** [comment]
@ssrpanel 大佬这个什么时候修复？

**Comment by ssrpanel** [comment]
@Pinkpiglet 在线支付打标签已经修复了，等待提代码
那个节点订阅我正在搞

**Comment by Pinkpiglet** [comment]
@ssrpanel 谢谢

**Comment by ssrpanel** [comment]
已加上，晚上提代码
