### ISSUE TITLE
请教一个愚蠢的定时任务问题

### ISSUE THREAD

**Issue by vinsanchen** [ssrpanel/SSRPanel#545]
我今天支付的时候，钱到了帐户，但是订单未启用，
后来发现是xxx/laravel-2018-01-09.log的问题，
我手动进去改了权限以后就正常了...
  
但是现在问题来了...
虽然定时任务正常运行了，
但是创建出来的log还不是WWW的权限，
因为我用的宝塔....
实在不知道crontab -e -u www是在哪操作？
有人可以教一下吗？谢谢

**Comment by Chennhaoo** [comment]
@vinsanchen 我建议宝塔面板搭建，简单省事，稳定性和资源占用都不错。
我的宝塔定时任务就是对的，手动lnmp已放弃。

**Comment by vinsanchen** [comment]
这个我改了，但是产生的log权限是root，怎么改成自动生成www的权限？

**Comment by tonychanczm** [comment]
chown -R www:www stroage
chmod -R 777 stroage

**Comment by Chennhaoo** [comment]
@828768 @vinsanchen   在SSH中执行`crontab -e -u www`，然后提示创建文件，选nano，然后打开一个黑框，直接输入`* * * * * php /home/wwwroot/ssrpanel/artisan schedule:run >> /dev/null 2>&1`（注意网站路径），然后ctrl+X，他会提示你保存路径（重点），你直接删了他的路径(一般是tmp/XXX)，把你网站的路径复制进去，比如`/home/wwwroot/ssrpanel/crontab `，执行`service crond status`可以查看计划任务了，应该会有个www的用户，最后等几分钟，在网站日志里面查看日志，应该是下面这种

```
- 
- [2018-05-11 20:55:01] production.INFO: 定时任务：自动监测节点是否宕机  
- [2018-05-11 20:55:01] production.INFO: 定时任务：自动关闭超时未支付订单  
- [2018-05-11 20:55:01] production.INFO: 定时任务：自动禁用到期用户  
- [2018-05-11 20:55:01] production.INFO: 定时任务：自动禁用流量超限的用户  
- [2018-05-11 20:55:02] production.INFO: 定时任务：自动释放端口  
- [2018-05-11 20:55:02] production.INFO: 定时任务：自动解封用户  
- [2018-05-11 20:55:02] production.INFO: 定时任务：自动重置用户可用流量  
- [2018-05-11 20:56:01] production.INFO: 定时任务：自动监测节点是否宕机
```
