### ISSUE TITLE
邮件配置实在无力解决,请各位帮忙说一下!

### ISSUE THREAD

**Issue by biigaa** [ssrpanel/SSRPanel#548]
用了阿里云的ECS,安全组端口全开,BT安全全开!
按照mail.php文件里面的说明做了修改
使用了gmail/163mail/mailgun/QQmail

都不能注册激活发信!!!

不知道是哪里的问题!!

端口使用的都是ssl 465

有没有人碰到过!

望各位大神能够耽误几分钟给说一下!

**Comment by ssrpanel** [comment]
阿里云限制发邮件。。。。如果需要发邮件需要发邮件请求阿里云开通这个权限。。。

**Comment by biigaa** [comment]
@ssrpanel 我知道他限制了25,想问一下465也限制了吗?

**Comment by biigaa** [comment]
@ssrpanel 官方给我回复可以使用465端口!
下面是官方回复
> 不支持本机25端口解封，建议您尝试使用外部邮件服务商的465加密端口，或者查询所访问发信服务是否提供其它SMTP端口。如果使用的是阿里企邮或邮件推送，支持80和465端口发送，请将25更换为80端口。

**Comment by yeehomlee** [comment]
邮箱那么多，换个gmail或者QQ邮箱试试行不行，你就知道问题出在哪了。
