### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/ssrpanel#55]
1. 能加入一个主页吗？ 这样可以美化一下网站
2. 网站logo +头像 可替换， 胖虎的头像 有够恐怖的...
3.工单加入邮箱提示

bug：网站后端默认选项并没有运用到新注册的用户那里
不知道是不是我设置的问题....

**Comment by ZBrettonYe** [comment]
再加一条 希望购买流量的界面  流量按照GB来显示 
MB看起来很大，而且有点小复杂

**Comment by ZBrettonYe** [comment]
用了一段时间后发现，账号管理中 编辑账号 付费方式，没有流量付费，有2个月费 ...

**Comment by ssrpanel** [comment]
@ZBrettonYe 
1.主页不加，自己搞，怕被墙或者爬虫识别出太多关键字
2.LOGO头像自己换图啊
3.加入开发排期
4.注册默认的加密方式、协议、混淆已修复
5.等我重现
6.什么流量付费？你给账号多少流量就是多少流量，那个付费只是用来标记账号的
