### ISSUE TITLE
胖虎，我是绑匪，静香现在在我手上！

### ISSUE THREAD

**Issue by NutterChen** [ssrpanel/SSRPanel#551]
静香现在在我手上，如果你不想她缺胳膊少腿儿，请你带着修复过在线购买后不打标签的bug的代码到gayhub，将代码pull上去，我会派人去取并放掉静香！

**Comment by ssrpanel** [comment]
截图我看看？？

**Comment by ZBrettonYe** [comment]
这个只要更新一下 yzy.php 文件就好了

**Comment by Pinkpiglet** [comment]
@ZBrettonYe 你修复了么？

**Comment by ZBrettonYe** [comment]
@Pinkpiglet 嗯， 按照usecontol 文件里的改就好了

**Comment by ssrpanel** [comment]
最新版没毛病是吗？ 那我不用看了。。

**Comment by ssrpanel** [comment]
我擦，我看了下还真漏了

**Comment by ssrpanel** [comment]
已修正，等待提交
