### ISSUE TITLE
希望在网页上提供文件下载

### ISSUE THREAD

**Issue by kuangshao11** [ssrpanel/SSRPanel#553]
rt，提供个ssr软件下载能方便不少，甚至可以把 教程.doc 这种文件放上去

**Comment by vinsanchen** [comment]
我現在是用公告的方式，但是其实不太直观，
我觉得最好可以做在左边的控制栏。

**Comment by kuangshao11** [comment]
我是把文件扔群里了，不过总有不愿加群的，网页上有个链接会好很多

**Comment by cmtomkan310** [comment]
公告和文章已经可以做到这些功能。

**Comment by yeehomlee** [comment]
文件上传到服务器上，链接放到文章里，可以实现。

但，还是借这里提个小建议：
希望可以在左侧菜单加个「文章」（可以自定义名称就更好了），进去后仍然是所有文章、公告的列表。
主要还是引起用户的注意。
原先的公告/文章栏太不显眼，小白用户进去很容易找不到北。光看功能也不知道怎么使用。

**Comment by Dennishaha** [comment]
我是做个wordpress里面有教程，测速，下载什么的，然后留个链接进入55Rpanel

**Comment by kuangshao11** [comment]
嗯，确实，毕竟个人开发者，ssrpanel是个优秀的面板，希望它变得更好吧

**Comment by vinsanchen** [comment]
我也是想過做wordpress，
有沒有人交流一下的@@"

**Comment by ssrpanel** [comment]
@Dennishaha 你这样做很聪明，我也是这么干的
