### ISSUE TITLE
提供韩文语言包

### ISSUE THREAD

**Issue by nalansj** [ssrpanel/SSRPanel#554]
因需要翻译了韩文语言包

[kr.zip](https://github.com/ssrpanel/SSRPanel/files/2000909/kr.zip)

**Comment by NutterChen** [comment]
怎么设置让用户可以选择英语中文和韩语？

**Comment by ssrpanel** [comment]
@nalansj 太棒了，谢谢你，会提pr吗？提个pr我合并吧。

**Comment by ssrpanel** [comment]
已更新，注意导入数据库
