### ISSUE TITLE
新增商品提示失败 实际点开商品列表成功

### ISSUE THREAD

**Issue by 110560** [ssrpanel/SSRPanel#555]
![qq 20180514113823](https://user-images.githubusercontent.com/32481672/40005826-83b94656-57cb-11e8-9d7b-411c6a5f8df5.png)
![qq 20180514113849](https://user-images.githubusercontent.com/32481672/40005862-96c08ec6-57cb-11e8-903d-dbc01e8364ba.png)
 日志截图

**Comment by ssrpanel** [comment]
代码不是最新的
