### ISSUE TITLE
请教一下，远程子节点如何统计流量/定时任务？

### ISSUE THREAD

**Issue by yeehomlee** [ssrpanel/SSRPanel#560]
目前情况是这样：
- 节点01 跟 SSRPanel 是在同一台服务器上，用的是宝塔。
- 节点02 是另一台服务器，安装了SSR后端（没安装SSRPanel），通过远程数据库连到01服务器上。
- 两个节点都已经连接正常，用户可以正常使用。

- 我在01服务器上，按照胖虎大佬的代码设置了定时任务，运行正常。
但是，只能统计到01节点的流量，02节点始终为0。

搜索了一通，没找到关于子节点的流量统计问题。

那么，请问：

我是不是应该按照同样的方法，在子节点02上，再安装一遍SSRPanel，并设置定时任务。这样是否可行？

还是通过其他什么办法呢？

不太清楚统计的逻辑，应该在主节点01上想办法，还是在子节点02上？

感谢！
确实不懂，才来请教

**Comment by ssrpanel** [comment]
1.不用在任何子节点上安装面板
2.子节点一定要可以连的上数据库
3.面板机上要设定crontab 定时任务，保证能正常运行
4.即可
