### ISSUE TITLE
注册用户时产生的问题

### ISSUE THREAD

**Issue by Dennishaha** [ssrpanel/SSRPanel#563]
当前panel 在 http:/xx.com/register注册用户时 php 报错误，
但是用户是正常生成的。胖虎哥debug下 ❤❤❤

**Comment by Dennishaha** [comment]
![2](https://user-images.githubusercontent.com/38273998/40188278-30a8dc3e-5a2c-11e8-946f-6dee1d9e0988.jpg)
![4](https://user-images.githubusercontent.com/38273998/40188335-4a6a9950-5a2c-11e8-83c5-161670187fb6.jpg)

**Comment by ssrpanel** [comment]
config 表里 删除重新导入 
漏了 initial_labels_for_user 字段

**Comment by Dennishaha** [comment]
![image](https://user-images.githubusercontent.com/38273998/40191877-454fd846-5a35-11e8-92a3-85585f6e7571.png)

**Comment by Dennishaha** [comment]
initial_labels_for_user 字段存在于config表中

**Comment by ZBrettonYe** [comment]
我也有一样的问题 @ssrpanel 

@Dennishaha  我把count的判断直接删了，这样一切正常。

count（）这个地方不解决的话，邀请链接也不会更新为已使用这些，
