### ISSUE TITLE
请问，面板机(主节点)的速度会不会影响到子节点？

### ISSUE THREAD

**Issue by yeehomlee** [ssrpanel/SSRPanel#564]
**环境：**
- 主节点 01 是面板机。
- 有两个子节点 02、03，通过远程数据库连接到面板机。
- 节点都用了「域名地址」，域名DNS是解析到主节点 01 的IP地址上。

**于是：**

ping 子节点的域名 02.name.com，会看到 01 的IP地址。
一旦主节点 01 宕机，所有子节点的SSR都无法使用。

**请问：**

1、子节点的代理流量，是不是通过面板机中转的呢？

2、这种情况下，假如主节点01的速度太慢(延迟高)，会不会影响到子节点的SSR速度？
      或者说，用户使用子节点02的速率，有没有可能超过主节点01？

3、如果确实会影响，那我把域名地址取消，改用IP地址，是否能解决问题？

感谢！感激！打扰了！

**Comment by kuangshao11** [comment]
节点是和你机场数据库通信的，节点只是把已连接的用户信息发到机场，没几个流量。上网的流量还是走的节点

**Comment by yeehomlee** [comment]
明白了，非常感谢。
