### ISSUE TITLE
提交日语语言包

### ISSUE THREAD

**Issue by Dennishaha** [ssrpanel/SSRPanel#566]
胖虎大大，业余做了个日语语言包，快来签收~
另外我也发现了现有中文，也有些不合理可以改得更好的地方。
[jp.zip](https://github.com/ssrpanel/SSRPanel/files/2017734/jp.zip)

![default](https://user-images.githubusercontent.com/38273998/40231307-40d95c68-5acd-11e8-998b-c8180a041f08.PNG)
![default](https://user-images.githubusercontent.com/38273998/40231259-0502c56c-5acd-11e8-9499-0166cbdae84f.PNG)
![107](https://user-images.githubusercontent.com/38273998/40231160-8ffd18da-5acc-11e8-8882-ced1daba7c1c.jpg)

**Comment by lifespy** [comment]
好的，稍后集成

**Comment by yeehomlee** [comment]
问个题外话，自动分配节点什么？怎么实现的？

**Comment by ssrpanel** [comment]
啥自动分配节点

**Comment by ssrpanel** [comment]
@Dennishaha 稳

**Comment by ssrpanel** [comment]
666，@lifespy已经合并了代码了，我晚上回去看看，好像韩文那个有个小bug

**Comment by ssrpanel** [comment]
已合并。

**Comment by Dennishaha** [comment]
这里出现语义重复了，修复下
![default](https://user-images.githubusercontent.com/38273998/40268485-af85a9c2-5ba0-11e8-9446-fb749079d480.PNG)
![2](https://user-images.githubusercontent.com/38273998/40268486-afcc4882-5ba0-11e8-8579-2c3d26342bd1.PNG)
