### ISSUE TITLE
对于某些人为原因导致邀请返利失效的优化。

### ISSUE THREAD

**Issue by tonychanczm** [ssrpanel/SSRPanel#567]
有的用户通过邀请返利链接点进去之后会点去别的地方看看，然后再回来注册。当他回来注册的时候，注册页面url里的?aff=XXX就没有了，导致邀请返利失败。然后我刚刚学会了laravel的session的使用，就学以致用改一下吧～
如果有什么问题欢迎大佬们指出。
@ssrpanel 

RegisterController.php 第136行左右

// 校验aff对应账号是否存在

            if($request->session()->has('affId')){
                if($aff != 0){
                    $request->session()->put('affId',$aff);
                }
            }
            else{
                $request->session()->put('affId',$aff);
            }
            $affId = $request->session()->get('affId');

            if ($affId) {
                $affUser = User::query()->where('id', $affId)->first();
                $referral_uid = $affUser ? $affId : 0;
            } else {
                $referral_uid = 0;
            }

**Comment by lifespy** [comment]
这样容易出问题，建议直接使用html的sessionstorage实现

**Comment by tonychanczm** [comment]
我见胖虎里面好想用的好多都是session啊XD @lifespy

**Comment by ssrpanel** [comment]
阔以阔以，你都已经开始一只脚踏进开发者行列了

**Comment by ssrpanel** [comment]
@lifespy 最近严打三方清算，你还ok吗

**Comment by lifespy** [comment]
@ssrpanel 我一直都比较低调，希望多撑一段时间吧

**Comment by lifespy** [comment]
@ssrpanel 我的TG之前那个号丢了。新注册了个号加你

**Comment by ssrpanel** [comment]
@tonychanczm 已修正，妥了，等提代码

**Comment by ssrpanel** [comment]
修正逻辑为：如果链接网址有aff，则取aff，没有则取session里的
这种情况仅适合：访客A访问了XXX.COM带了AFF，然后访客又跑到别的地方乱点（还在你的站内），然后直接去点注册了，此时 因为你的aff已经存在session里了，所以注册还是返利。

但是，如果A跑去BBB.com再点一下aff，最后是通过后面这个人去注册的。
