### ISSUE TITLE
订阅请求日志错误

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/SSRPanel#569]
提示是这个

(2/2) ErrorException
Trying to get property 'username' of non-object (View: /www/wwwroot/xxxxx/ssrpanel/resources/views/admin/subscribeLog.blade.php)

**Comment by ssrpanel** [comment]
你确定你代码最新？

**Comment by ssrpanel** [comment]
100%你手动从数据库里删除了某个账号

**Comment by ZBrettonYe** [comment]
嗯 是删过账号

**Comment by ssrpanel** [comment]
我已修正，等晚上提代码
