### ISSUE TITLE
实在找不到SSR3.4Python。

### ISSUE THREAD

**Issue by ewjo** [ssrpanel/ssrpanel#57]
找到一个3.12的
https://github.com/Kry4tal/shadowsocksr  是这个不？

求给个3.4的.

**Comment by ewjo** [comment]
好像不是SSR  是 shadowsocks-py-mu-3.4.0  这个版本吧!

**Comment by ssrpanel** [comment]
@ewjo 我去，为何你不好好看项目首页，明明有写，在server目录下

**Comment by ewjo** [comment]
抱歉眼龊
