### ISSUE TITLE
定时任务执行时将ssr禁用状态的用户标签清空

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#577]
如题。

如果不清空，在标签统计中分不出有多少是真正在使用某个服务器状态。
比如有100个用户是有 `周付` 这个标签的，其中50个已经过期或者流量用完了，当前在标签统计中 `周付` 标签仍然是100个，改成禁用状态的用户清理掉所有标签，此处显示50个 `周付` 标签，另外50个显示无标签是不是好点？

被清空标签的用户也就是ssr禁用状态的用户，再购买服务后重新贴对应标签启用。

**Comment by ssrpanel** [comment]
已加
