### ISSUE TITLE
做的很不错，希望可以增加删除用户的功能和修复SS二维码和连接功能

### ISSUE THREAD

**Issue by Hao-Luo** [ssrpanel/ssrpanel#58]
我觉得算是用下来最好用的， 希望能增加删除用户的功能，不用每次都到数据库删。
另外希望能够增加SS二维码和SS链接功能， 因为现在的链接和二维码只有SSR能用。
SS的二维码和连接都用不了，显示连接错误

**Comment by ssrpanel** [comment]
@Hao-Luo 删除用户那个有BUG，一旦删除了账号，会出现一堆的异常问题，功能有了，后面隐藏了。
SS二维码要看你后台账号的设置，你把节点的【兼容】打开，就会出现SS的二维码，但是强烈不推荐使用SS，要用的时候记得把账号的混淆、协议都设置为orgin，一切以账号为基准，节点的后端要记得改配置

**Comment by Hao-Luo** [comment]
可以看得到ss的二维码和连接，可是扫码后说错误。 我自己把你后加的那个#vpn去掉了，二维码可以用了，可是链接还是不行，好奇怪。 然后随机密码默认的那个@我给去掉了，这个会影响软件读ss链接。
