### ISSUE TITLE
语言标签建议

### ISSUE THREAD

**Issue by Dennishaha** [ssrpanel/SSRPanel#584]
在知乎上看到的，Emm .我记得目前好像叫zh-cn 和zh-tw

单一的 zh 和 zh-CN 均属于废弃用法。问题主要在于，zh 现在不是语言code了，而是macrolang，能作为语言code的是cmn（国语）、yue（粤语）、wuu（吴语）等。我通常建议写成 zh-cmn 而不是光写 cmn，主要是考虑兼容性（至少可匹配 zh），有不少软件和框架还没有据此更新。zh-CN 的问题还在于，其实多数情况下标记的是简体中文，但是不恰当的使用了地区，这导致同样用简体中文的 zh-SG（新加坡）等无法匹配。更典型的是 zh-TW 和 zh-HK。所以其实应该使用 zh-Hans / zh-Hant 来表示简体和繁体。那么完整的写法就是 zh-cmn-Hans，表示简体中文书写的普通话/国语。一般而言没有必要加地区代码，除非要表示地区特异性，一般是词汇不一样（比如维基百科的大陆简体和新马简体）。所以回答题主，两种都不对。如何标记的例子：1. 简体中文页面：html lang=zh-cmn-Hans2. 繁体中文页面：html lang=zh-cmn-Hant3. 英语页面：html lang=en

作者：贺师俊
链接：https://www.zhihu.com/question/20797118/answer/16809331
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

**Comment by ssrpanel** [comment]
不想改，我也知道这个问题，不过现在大量的网站\移动端都是这么用的
