### ISSUE TITLE
商品过期时间和账号过期时间的问题

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#586]
服务购买信息显示24日13点过期
![image](https://user-images.githubusercontent.com/6386202/40461356-92519f28-5f3d-11e8-938a-d4ae378c025d.png)

用户ssr实际上是在24日0点任务的时候就禁用了
![image](https://user-images.githubusercontent.com/6386202/40461386-bf0ad0ac-5f3d-11e8-95a9-b9f103ad8cb2.png)

该用户刚好24日账号到期，购买商品也是24日13点到期，
每日凌晨任务的时间和商品服务的到期时间不一致，在0点任务的时候账号过期处理了，但购买的服务没到期但不能用，这种该怎么处理？

**Comment by ssrpanel** [comment]
应该是修正了
