### ISSUE TITLE
注册出现错误

### ISSUE THREAD

**Issue by Pinkpiglet** [ssrpanel/SSRPanel#589]
注册出现错误，但是实际上注册成功。
![qq 20180524235247](https://user-images.githubusercontent.com/38532706/40496986-b1c9a60a-5fad-11e8-93e7-7f4c153821ff.png)

**Comment by Pinkpiglet** [comment]
刚重新在另外一台服务器安装了一次，出现同样问题，数据库没问题。

**Comment by ssrpanel** [comment]
已修复，等待提交

**Comment by xsaddata** [comment]
我也一样出现了这个错误

**Comment by xsaddata** [comment]
@ssrpanel 今天修复了么

**Comment by Pinkpiglet** [comment]
@xsaddata 等待胖虎修复

**Comment by ssrpanel** [comment]
已修复

**Comment by ssrpanel** [comment]
@xsaddata 今天你给我打钱了吗？
