### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/ssrpanel#59]
1. 账号界面中：等级显示（目前不管谁，显示都是普通会员。希望这个功能可以和节点浏览等级结合，用最强王者或者自定义可变动的权限等级代替）；
2. 套餐中加入权限设置，比如使用者买了一个年费套餐，然后管理员设置：该套餐为最强王者级别（最高等级），那么该用户自动获得该套餐设置的权限，（时限与套餐时限相同）；
3. 账号编辑功能加强, 管理员可以对账号进行手动设置，和商品对应 添加2个设置（流量，套餐）；流量=使用流量，该账号无视过期时间直到流量使用完毕后 X天才会提示关闭账号； 套餐= 无限流量；只管账号有效期
（为什么我会在意这个问题，是因为我在想让我以前的手动过渡用户信息到SSRpanel，结果设置了时长，账号还是会按照流量来扣）；
4. 公告功能， 现状：现有公告在界面上方的小夹层，这样的公告不够醒目，作用太小，希望胖虎大大能在用户界面的左侧加入公告分页面，这样用户可以看到所有公告；

再次感谢 胖虎大大 的开发

**Comment by Hao-Luo** [comment]
你设置时长了，流量设置999999不就是无限流量了么

**Comment by ssrpanel** [comment]
@Hao-Luo  机智如你，我就是这么打算的。。。

**Comment by ssrpanel** [comment]
@ZBrettonYe  问题1已修正，其他我再研究下

**Comment by ZBrettonYe** [comment]
发的时候没有重新阅读，发现错别字好多....
2. 改用户自动 = 该用户自动
3.改=该， 手动等级过度到 = 手动用户过渡
4. 加成= 夹层

**Comment by ZBrettonYe** [comment]
5. 管理端商品编辑中 有商品描述，但是个人端 并有没有出现商品描述的bug

**Comment by ssrpanel** [comment]
我在做一个新版本的用户端的商品界面@ZBrettonYe
