### ISSUE TITLE
有赞支付 自动任务报错

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/SSRPanel#590]
查了logs文件后 发现的

`production.ERROR: ErrorException: Undefined index: kdt_name in /www/wwwroot/ssrpanel/app/Http/Controllers/Api/YzyController.php:67`

没有察觉到 任何影响，只是logs里看起来没那么好看

` production.ERROR: Exception: response invalid, data:  in /www/wwwroot/ssrpanel/vendor/youzan/open-sdk/src/Open/Client.php:45`

**Comment by ssrpanel** [comment]
难道有赞的接口升级了？

**Comment by Pinkpiglet** [comment]
@ssrpanel 我的支付正常啊

**Comment by ZBrettonYe** [comment]
支付是正常的
只是logs里 有这些报错
