### ISSUE TITLE
大佬，定时任务自动执行出错，但是手动执行就没问题

### ISSUE THREAD

**Issue by xinwenpiaoxue** [ssrpanel/SSRPanel#592]
站点目录
![default](https://user-images.githubusercontent.com/36916070/40535354-7664aa68-603b-11e8-99e1-09a30c33e487.png)

定时任务文件及目录
![default](https://user-images.githubusercontent.com/36916070/40535236-15c0c66a-603b-11e8-85e1-bddba80eafd0.png)
![2](https://user-images.githubusercontent.com/36916070/40535977-44dac8a4-603d-11e8-90a8-40f43d19903b.png)

定时任务我是这样写的:
* * * * * php /www/wwwroot/xinwenpiaoxue/artisan schedule:run >> /dev/null 2>&1
下面应该是cron执行日志吧
![1](https://user-images.githubusercontent.com/36916070/40535555-0173321e-603c-11e8-9efd-66c645a14723.png)
然后是执行记录
![default](https://user-images.githubusercontent.com/36916070/40535642-49f20ace-603c-11e8-8e68-692d11693b4f.png)
下面是定时任务日志
![qq 20180525165614](https://user-images.githubusercontent.com/36916070/40542018-dafdb018-6050-11e8-9fe8-afaec7ecb596.png)

里面只有我手动执行两次的记录
![qq 20180525165845](https://user-images.githubusercontent.com/36916070/40535863-ed30c702-603c-11e8-98d0-3467ddc775b1.png)
我不知道错在哪   很郁闷

**Comment by xinwenpiaoxue** [comment]
M 小白。。。

**Comment by Chennhaoo** [comment]
目测是`/var/spool/cron/`中的`www`定时任务文件权限问题，我也是半灌水哈，你可以试试
1、删除www定时任务
2、切到网站更目录，执行`chown -R www:www storage/`和`chmod -R 777 storage/`命令，主要是给日志写入的权限
3、执行`crontab -e -u www`，然后把代码写进去，保存，再看看效果。

**Comment by xinwenpiaoxue** [comment]
@Chennhaoo 不行   还是还是失败
May 25 19:09:01 vultr CROND[6564]: (CRON) ERROR chdir failed (/home/www): No such file or directory
May 25 19:10:01 vultr CROND[7165]: (CRON) ERROR chdir failed (/home/www): No such file or directory

定时任务文件内容是
* * * * * php /www/wwwroot/xinwenpiaoxue/artisan schedule:run >> /dev/null 2>&1
错误提示为什么是ERROR chdir failed (/home/www): No such file or directory
路径我明明写的是/www/wwwroot/xinwenpiaoxue/
郁闷。。。

**Comment by Chennhaoo** [comment]
https://blog.csdn.net/leeslee_feng/article/details/52351532 我百度的
大意是在/home下建一个www用户文件夹
`cd /home`
`mkdir www`
`chown www -R www`
`chgrp www -R www`

我的系统是debian 8.1，我按教程步骤来没出过问题，实在不行建议换个系统。

**Comment by Pinkpiglet** [comment]
mkdir home

**Comment by xinwenpiaoxue** [comment]
感谢各位大佬    问题完美解决    
![image](https://user-images.githubusercontent.com/36916070/40550646-4ae8900c-606d-11e8-89cd-2fb582f4e687.png)

**Comment by Chennhaoo** [comment]
@xinwenpiaoxue 朋友，你要说下怎么解决的啊，以供后人参考

**Comment by xinwenpiaoxue** [comment]
@Chennhaoo    不好意思   有点兴奋
解决方法
cd /home
mkdir www
chown www -R www
chgrp www -R www

然后过几分钟查看日志记录就正常了

**Comment by ZBrettonYe** [comment]
这个就是宝塔建立www权限的自动任务的方法； @ssrpanel  胖虎大佬记录一下

**Comment by Chennhaoo** [comment]
@xinwenpiaoxue 朋友问个私人问题，vultr的机子是不是会自动杀SSR啊，比如运行一段时间后自动kill ssr进程，日本节点速度如何，晚上爆炸不，准备搞个，怕浪费钱，谢谢。

**Comment by xinwenpiaoxue** [comment]
@Chennhaoo   我暴露了这么多信息嘛！？    进程没杀  速度还可以 昨晚有人说日本节点连不上游戏服务器不知道咋回事，

**Comment by xinwenpiaoxue** [comment]
@Chennhaoo   hhh   没事没事   要不要续费呀

**Comment by kuangshao11** [comment]
怕kill写个定时任务，10分钟自动运行一次logrun 。45.32.23的日本随时断流，gfw干扰严重。不断的时候很好，晚上不炸。
