### ISSUE TITLE
显示这个

### ISSUE THREAD

**Issue by zs910208565** [ssrpanel/SSRPanel#596]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
Warning: require(/www/wwwroot/www.xxxx.club/ssrpanel/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/www.xxxx.club/ssrpanel/bootstrap/autoload.php on line 17

Fatal error: require(): Failed opening required '/www/wwwroot/www.xx.club/ssrpanel/bootstrap/../vendor/autoload.php' (include_path='.:/www/server/php/71/lib/php') in /www/wwwroot/xxxx.club/ssrpanel/bootstrap/autoload.php on line 17

这什么意思

**Comment by 520xcy** [comment]
目录权限对不对

**Comment by zs910208565** [comment]
给777了啊

**Comment by 520xcy** [comment]
你的PHP版本对不对，PHP的目录是不是在include_path指向的地方

**Comment by zs910208565** [comment]
www/server/php/71/lib/php
版本是71   这个目录吗？

**Comment by Chennhaoo** [comment]
宝塔吗？@zs910208565  贴一下站点运行目录的设置图

**Comment by zs910208565** [comment]
运行目录是public

**Comment by Chennhaoo** [comment]
@zs910208565 好吧 ，爱莫能助。建议删了站点，从新来一遍

**Comment by zs910208565** [comment]
好吧，还是谢谢！
