### ISSUE TITLE
每月流量重置的问题

### ISSUE THREAD

**Issue by longdoer** [ssrpanel/SSRPanel#597]
例如用户用户4.25购买了2次月套餐 到期日期应该为6.25 但是目前有个每月25日重置流量 导致用户5.25日被重置后 无法使用  这个问题如何解决？

**Comment by longdoer** [comment]
应该是日期到期重置流量吧？

**Comment by ZBrettonYe** [comment]
手动给用户再冲一下

**Comment by longdoer** [comment]
@Chennhaoo 现在是时间累加的 25日到期了系统重置以后可用流量成了用户默认初始流量1G了

**Comment by Chennhaoo** [comment]
@longdoer 你的那个是叫流量包吧，套餐最低设置90天啊

**Comment by longdoer** [comment]
@ZBrettonYe 是套餐不是流量包

**Comment by longdoer** [comment]
@Chennhaoo 是套餐不是流量包
