### ISSUE TITLE
邀请系统错误

### ISSUE THREAD

**Issue by xsaddata** [ssrpanel/SSRPanel#598]
出现了 #589 的错误之后，发现后台出现问题的用户注册使用的邀请码一直显示未使用，可以重复使用。

**Comment by ZBrettonYe** [comment]
原因是 因为count（）的报错，count下面的自动任务都没有执行；

**Comment by ZBrettonYe** [comment]
临时解决方法：把count（）整个判断删除，

**Comment by ssrpanel** [comment]
已修正
