### ISSUE TITLE
支付后有赞收到钱但是面板却还是待支付

### ISSUE THREAD

**Issue by ziui** [ssrpanel/SSRPanel#601]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
支付后有赞收到钱，但是面板却还是待支付状态。

**Comment by 799953468** [comment]
已经回掉还是不行。 错误
":{"consign_time":"","buyer_area":"","original_post_fee":"0.00","num":1,"adjust_fee":{"pay_change":"0.00","change":"0.00","post_change":"0.00"},"relation_type":"","type":"QRCODE","order_mark":"","tid":"E20180519175039025000006","send_num":0,"feedback":0,"delivery_start_time":0,"outer_user_id":0,"qr_id":"6897037","price":"1.00","button_list":[{"tool_parameter":"{}","tool_type":"goto_native:trade_memo","create_time":"","tool_value":"","tool_title":"备注","new_sign":"0","tool_icon":"https://img.yzcdn.cn/upload_files/2015/08/28/FpO1UIXyOEZO026tWIgUOm9uZnT2.png"}],"total_fee":"1.00","payment":"1.00","order_type":"6","is_tuan_head":0,"lat":"","sub_trades":[],"delivery_time_display":"","buyer_message":"","delivery_end_time":0,"lng":"","created":"2018-05-19 17:50:39","kind":1,"delivery_list":[],"is_retail_offline":false,"offline_id":"0","goods_kind":1,"status_str":"已完成","close_time":"","pay_time":"2018-05-19 17:50:47","group_no":"","shop_id":"40755528","out_trade_no":[],"points_price":0,"tuan_no":"","orders":[{"is_virtual":0,"outer_item_id":"","pic_thumb_path":"https://img.yzcdn.cn/public_files/2016/12/29/33e6c838cefa614c5121c63c80f860e9.png?imageView2/2/w/200/h/0/q/75/format/png","item_type":30,"num":"1","refunded_fee":"0.00","oid":18005754,"title":"体验卡","fenxiao_payment":"0.00","discount_fee":"0.00","new_oid_str":"1449742053852319654","buyer_messages":[],"is_present":0,"price":"1.00","fenxiao_price":"0.00","total_fee":"1.00","payment":"1.00","outer_sku_id":"","sku_unique_code":"","is_send":0,"item_id":"2147483647","sku_id":"0","sku_properties_name":"","pic_path":"https://img.yzcdn.cn/public_files/2016/12/29/33e6c838cefa614c5121c63c80f860e9.png","new_oid":1449742053852319654,"item_refund_state":"NO_REFUND","refund_id":"","state_str":"待发货","unit":"件","order_promotion_details":[],"allow_send":1,"seller_nick":"酸酸乳批发中心"}],"promotion_details":[],"id_card_number":"","refund_state":"NO_REFUND","status":"WAIT_SELLER_SEND_GOODS","post_fee":"0.00","pic_thumb_path":"https://img.yzcdn.cn/public_files/2016/12/29/33e6c838cefa614c5121c63c80f860e9.png?imageView2/2/w/200/h/0/q/75/format/png","invoice_title":"","receiver_city":"","shipping_type":"express","refunded_fee":"0.00","title":"体验卡","discount_fee":"0.00","buy_way_str":"","hotel_info":"","pf_buy_way_str":"运费到付","receiver_state":"","update_time":"2018-05-19 17:50:39","coupon_details":[],"receiver_zip":"","receiver_name":"","pay_type":"ALIPAY","fans_info":{"fans_type":"14","fans_weixin_openid":"","buyer_id":"811555066","fans_nickname":"17681548036","fans_id":"-811555066"},"delivery_third_party_supported":false,"transaction_tid":"180519175040000001","item_id":"2147483647","receiver_district":"","box_price":"0.00","pic_path":"https://img.yzcdn.cn/public_files/2016/12/29/33e6c838cefa614c5121c63c80f860e9.png","feedback_num":0,"receiver_mobile":"","confirm_time":"","sign_time":"2018-05-19 17:50:48","seller_flag":0,"service_phone":"","is_retail_free_buy":false,"shop_type":"1","order_source":{"platform":"OTHER"},"receiver_address":"面对面扫码收款","trade_memo":"","relations":[],"outer_tid":"2018051921001004580582415265"}}

**Comment by lifespy** [comment]
你这卖家昵称太放肆了

**Comment by Ailearnerr** [comment]
可能是日志权限问题
/ssrpanel/storage/logs      给权限777

**Comment by JMVoid** [comment]
我也遇到这个问题。果然是由于logs里面的权限不够导致的。 修改成777权限就正常回调并修改状态了
@ssrpanel  laravel daily log的默认权限可以修正吗？
多谢了

**Comment by mahuihuang** [comment]
同样的问题，我的就更离谱了，前几天还有日志，现在有赞云的日志都没有了。

**Comment by gtx980** [comment]
请问有没有解决呢？如果解决了是怎么样解决的，我也卡在这里了

**Comment by mahuihuang** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    

按照面板提示在有赞云里面添加api的地址


    在2018年7月8日 21:45，gtx980<notifications@github.com> 写道： 


请问有没有解决呢？如果解决了是怎么样解决的，我也卡在这里了

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.



        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }

**Comment by bigrain1993** [comment]
请问定时修改权限为777的具体代码有吗

**Comment by bigrain1993** [comment]
有木有大佬知道怎么修改文件权限777然后定时吗

**Comment by ssrpanel** [comment]
@bigrain1993 项目首页啊大哥

**Comment by ssrpanel** [comment]
@Ailearnerr 其实是你再设置定时任务的时候，权限没设置好，如果用宝塔或者lnmp都必须是crontab -uwww -e 这样，以www用户权限去跑定时任务的，项目首页都写明了
