### ISSUE TITLE
在线支付后流量变负数

### ISSUE THREAD

**Issue by kuangshao11** [ssrpanel/SSRPanel#605]
套餐，有赞支付成功后，流量被扣成了负数，订单记录里也显示已过期，手动改余额再余额支付就一切正常，请问如何解决？

**Comment by ZBrettonYe** [comment]
请不要随意修改套餐的流量

**Comment by kuangshao11** [comment]
请问能删了重新上架吗？我看其他issue说删了商品的话购买过的人会出错...

**Comment by ssrpanel** [comment]
这种都不算是BUG。自己爱折腾跟我没关系
