### ISSUE TITLE
关于卡券和文章管理的优化建议

### ISSUE THREAD

**Issue by wubin2** [ssrpanel/SSRPanel#606]
1、作者能不能完善一下卡券的操作功能啊？比如用ServerChan（或者[PushBear](https://pushbear.ftqq.com/admin/#/)）将券码发给某个特定用户；
2、文章管理有BUG，当把两个文章的排序设置为相同数字时，id都等于0，无法修改和删除文章了，就算在mysql数据库里也是无法操作；
3、用户无法在前台删除；
4、手机访问时header2行显示合并为1行显示比较美观。
![图片](http://test.imgurl.org/upload/1805/fbc9f5282dedbd90.jpg)

**Comment by ssrpanel** [comment]
PushBear 订阅频道 和 telegram 机器人有考虑接入，其他问题不是没法重现就是没法改，要能改我早改了。。。
