### ISSUE TITLE
折扣卷BUG

### ISSUE THREAD

**Issue by Pinkpiglet** [ssrpanel/SSRPanel#607]
原价10，生成的8折，结果付款80。
![qq 20180529231825](https://user-images.githubusercontent.com/38532706/40668295-b758f3fe-6396-11e8-9b0b-41eb7fdc6dc7.png)

**Comment by Pinkpiglet** [comment]
![image](https://user-images.githubusercontent.com/38532706/40710229-a935c9d4-642a-11e8-856d-25bcf8e1b2e0.png)

**Comment by ssrpanel** [comment]
已修复
