### ISSUE TITLE
5.29更新时以及更新后定时任务出现以下错误，请胖虎大佬看一下

### ISSUE THREAD

**Issue by NutterChen** [ssrpanel/SSRPanel#609]
![photo_2018-05-30_12-38-20](https://user-images.githubusercontent.com/32509481/40699924-acd8d05c-6409-11e8-8004-5410036ee13d.jpg)

![1](https://user-images.githubusercontent.com/32509481/40699916-a1015ca4-6409-11e8-9d2c-213f30ee14f4.jpg)

**Comment by ssrpanel** [comment]
你把 add index `idx_node` 这行删除
