### ISSUE TITLE
上传商品图片的时候说incorrect integer value 'jpg'

### ISSUE THREAD

**Issue by Hao-Luo** [ssrpanel/ssrpanel#61]
(2/2) QueryException
SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'jpg' for column 'type' at row 1 (SQL: update `goods` set `name` = 30天10GB, `desc` = 30天10GB, `logo` = /upload/image/goods/201710270503241213.jpg, `traffic` = 10240, `price` = 30, `score` = 999999, `type` = jpg, `days` = 30, `status` = 1, `updated_at` = 2017-10-27 05:03:24 where `id` = 1)

是不是有bug, 应该是输入type的数字，不应该输入'jpg'

**Comment by ssrpanel** [comment]
奇怪。我看下。。。

**Comment by ssrpanel** [comment]
@Hao-Luo 已修复，谢谢

**Comment by Hao-Luo** [comment]
新商品可以用，老商品还是有同样的错误，我已经手动修改数据库了。
