### ISSUE TITLE
购买流量包后，还有每月重置？还有为什么套餐不能设置每月30天

### ISSUE THREAD

**Issue by longdoer** [ssrpanel/SSRPanel#612]
1、之前购买过包月套餐，已经过期了。现在购买了流量包，还有原来的每月重置，这会不会影响到现在的流量包使用
![image](https://user-images.githubusercontent.com/16441085/40754857-07a2b896-64ae-11e8-938b-728162f33fee.png)
2、现有的套餐不能设置30天了？这样造成了原来的用户购买力越来越小了，原来包月30天套餐购买力每天都会有，现在必须至少90天后 购买力 直接没人购买了  90天这样也不符合业务逻辑啊

**Comment by greatvpn** [comment]
这个套餐问题我也反馈很多次了，现在90天后  没人买了 用户少了一大批

**Comment by Chennhaoo** [comment]
@longdoer 30天套餐可以使用流量包，设置成30天，反正30天后都要让用户决定是否再购买，所以套餐改成30天无意义。<br>
流量包也是到期后会清空流量的，没啥要担心的。

**Comment by ssrpanel** [comment]
为什么不用流量包？

**Comment by kuangshao11** [comment]
统一起来的话比较好看，自己去改文件就好了
