### ISSUE TITLE
用户我的账单界面建议，几个BUG反馈

### ISSUE THREAD

**Issue by Chennhaoo** [ssrpanel/SSRPanel#614]
1、用户`我的账单`界面增加`服务到期时间`栏，方便客户了解自己的到期时间
     希望增加删除已购买订单，因为有些人想中途变更套餐

2、用户`我的节点`界面
![default](https://user-images.githubusercontent.com/38855823/40760860-52e7f4b6-64cb-11e8-9927-95aff91376a7.png)
用户的套餐已经过期了，未购买其他套餐和流量包，但是界面上还是会有`每月XX日重置`

3、用户`我的节点`界面
![default](https://user-images.githubusercontent.com/38855823/40761685-4b002c88-64cf-11e8-869c-a5bf47a82fd9.png)
流量包过期后，已用流量不会清空，重新购买流量包后
![default](https://user-images.githubusercontent.com/38855823/40762296-f6bb79d0-64d2-11e8-9544-5e131ead1852.png)
SSR还是禁用，已用流量也没有清空，定时任务没有报错

**Comment by yeehomlee** [comment]
1、 有效期 = 服务到期时间
2、流量包不会影响账户有效期，胖虎大哥写的很清楚了。

**Comment by Chennhaoo** [comment]
@yeehomlee 感谢朋友的解答，但是如果客户购买流量包，有效期那里没法作为参考吧，所以说可以在账单界面添加一列到期时间，方便查看。
