### ISSUE TITLE
节点警告不准确

### ISSUE THREAD

**Issue by Pinkpiglet** [ssrpanel/SSRPanel#615]
节点使用正常，但是网站提醒宕机。🤣🤣

**Comment by Pinkpiglet** [comment]
节点时间和面板时间一致

**Comment by xsaddata** [comment]
同样出现问题，使用的是SSRR

**Comment by Pinkpiglet** [comment]
@xsaddata我都烦死了，明明正常，网站就是显示宕机，我都把节点关了，一直发邮件。

**Comment by Pinkpiglet** [comment]
@xsaddata 我还没更新

**Comment by mingtochu** [comment]
同样的情况

系统：debian 9
错误:   db_transfer.py:514 (1146, "Table '*********.ss_node_info_log' doesn't exist")
数据库中: 
ss_node           有数据
ss_node_info   没数据

**Comment by xsaddata** [comment]
@mingtochu @Pinkpiglet 可以close了，用官方的SSRR修改版即可。
https://github.com/ssrpanel/shadowsocksr
