### ISSUE TITLE
管理员-工具箱-日志分析BUG

### ISSUE THREAD

**Issue by QinZerui** [ssrpanel/ssrpanel#62]
已新建ssserver.log文件并给予写入权限，报错来看应该是参数传递有误0.0
![image](https://user-images.githubusercontent.com/14584068/32090647-096c3b46-bb23-11e7-93b9-f24871fe89bc.png)

**Comment by Hao-Luo** [comment]
Looks like the problem of the 2.38xxxxxxxxxxxxx, it requires an integer. 
Similar bugs in my issue.

**Comment by ZBrettonYe** [comment]
非官方说法：节点用久一点，ssserver.log上数据多一点就会解决

**Comment by ssrpanel** [comment]
@QinZerui 这个至今都有问题，我得再研究下。。。
