### ISSUE TITLE
希望添加个通过ssr链接批量添加功能

### ISSUE THREAD

**Issue by kuangshao11** [ssrpanel/SSRPanel#620]
像图上这样，他这是sspanel-v3魔改的，链接地址 https://github.com/NimaQu/ss-panel-v3-mod_Uim 
现在的ssrpanel如果有ios用户使用shadowrocket的话，是要手动一个个添加节点的，小火箭似乎没有订阅入口？感谢您阅读此问题
![image](https://user-images.githubusercontent.com/33590269/40870443-f675c666-6661-11e8-8701-54d65998a3fa.png)

**Comment by Bennett561** [comment]
小火箭有的，自己查一下，右上角加号

**Comment by ssrpanel** [comment]
不好意思，小火箭还真的有订阅入口。。。
