### ISSUE TITLE
用户的流量记录不统计

### ISSUE THREAD

**Issue by kkkway** [ssrpanel/SSRPanel#623]
用户的流量记录不统计，是什么问题呢?但是用户使用的流量数量，会正常记录的，只是流量统计图是空的。是文件权限的问题，还是数据库的问题？

**Comment by NutterChen** [comment]
至少要一天才开始统计吧

**Comment by kkkway** [comment]
不是啊，一直是空白的。。。已经超过24小时了

**Comment by MrPangzhan** [comment]
chmod 755 -R /网站根目录
chown www:www -R /网站根目录

**Comment by MrPangzhan** [comment]
在看你的定时任务状态，启动了吗

**Comment by kkkway** [comment]
Jun  3 20:44:01 wskshr CROND[4445]: (www) CMD (php /www/wwwroot/freeudp/ssrpanel/artisan schedule:run >> /dev/null 2>&1)
Jun  3 20:44:01 wskshr CROND[4445]: (CRON) ERROR chdir failed (/home/www): No such file or directory

**Comment by kkkway** [comment]
Jun  3 20:44:01 kkkway CROND[4445]: (www) CMD (php /www/wwwroot/ssrpanel/artisan schedule:run >> /dev/null 2>&1)
Jun  3 20:44:01 kkkway CROND[4445]: (CRON) ERROR chdir failed (/home/www): No such file or directory


好像好了？o.o

**Comment by kkkway** [comment]
[root@kkkway ~]# /bin/systemctl status  crond.service
● crond.service - Command Scheduler
   Loaded: loaded (/usr/lib/systemd/system/crond.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2018-06-02 17:27:36 CST; 1 day 3h ago
 Main PID: 436 (crond)
   CGroup: /system.slice/crond.service
           └─436 /usr/sbin/crond -n

Jun 03 20:39:01 kkkway crond[436]: (php) ERROR (getpwnam() failed)
Jun 03 20:40:01 kkkway crond[436]: (php) ERROR (getpwnam() failed)
Jun 03 20:41:01 kkkway crond[436]: (php) ERROR (getpwnam() failed)



好像不行 o-o
crontab -e -u www和root分别添加 和同时添加 都是这个样儿
google也没搜到很好的答案
http://www.nideyuan.com/?p=377
这个文章添加的这个root 能在这个定时任务用吗

**Comment by Chennhaoo** [comment]
@kkkway https://github.com/ssrpanel/SSRPanel/issues/592
