### ISSUE TITLE
关于「推广返利」的一丁点建议！

### ISSUE THREAD

**Issue by yeehomlee** [ssrpanel/SSRPanel#625]
实际运营过程中，发现「推广返利」的实用性比较差。
在此斗胆提个小建议。希望大佬们关注一把。

**问题具体体现在：**
1、推广链接的追踪性比较差。只有用户打开链接直接注册，才能追踪到。但实际使用中，用户随意浏览再回来注册的比较多。
2、推广人 无法了解自己的推广情况。被邀请人是否注册，他并不清楚，只有当消费了才有记录显示。

这两个问题结合在一起，就导致了我遇到的这种情况：

老会员去发链接邀请，但有没有人注册根本不清楚。很容易过了几个星期，发现他邀请的朋友购买了套餐，但他却没收到返利（推广链接没追踪到）。这种情况，直接导致推广积极性降低。

**所以建议两个修改：**

1、在「推广返利」中实时显示成功邀请的会员，已注册但还没消费的也显示出来。（提高推广积极性）
2、通过邀请码追踪。即使推广链接失效，使用了他的邀请码，就等同于推广生效。

否则，目前的推广返利确实可用性不大。

感谢！
言语不到之处，敬请谅解。

**Comment by kkkway** [comment]
邀请码+链接都可追踪，提现的单位是分，可以改成元，打眼一看吓一跳

**Comment by yeehomlee** [comment]
关于第一点修改，也可采用更简单的方式：
在 推广返利 页面，显示自己已成功邀请的人数 或者 显示自己因推广而奖励的流量总数。
都有利于激励推广。

**Comment by izhangxm** [comment]
@kkkway 目前胖虎的注册中，并没有把注册码考虑到推广人当中

**Comment by izhangxm** [comment]
@yeehomlee 
>在「推广返利」中实时显示成功邀请的会员，已注册但还没消费的也显示出来。（提高推广积极性）

这一点真实太棒了！兄弟你这简直就是优秀的产品经理啊！
现实过程中还发现，小白们进了系统根本不知道自己要干啥，也不知道怎么用。在引导用户如何使用方面，能否给些建议？

**Comment by yeehomlee** [comment]
@izhangxm 
感觉可以分步骤引导。

- 登录后的初始页：
介绍产品特征、用途
介绍使用步骤（按先后顺序，配图说明，点击跳转至子页）
引导进入帮助页面（帮助子页：列出所有用户常见问题，并提供「提交工单」入口）


- 步骤子页：
1、试用/购买套餐  --> 购买服务
2、下载客户端  --> 选择不同客户端
3、配置节点  --> 选择不同客户端  --> 使用教程

**Comment by ssrpanel** [comment]
邀请码带入aff已加上
