### ISSUE TITLE
WARNING  server_pool.py:165 IPV4 [Errno 98] Address already in use

### ISSUE THREAD

**Issue by mingtochu** [ssrpanel/SSRPanel#626]
system: debian9
kernel: 4.9
webPanel: 宝塔面板
防火墙允许: 10000:65535
之前是使用的SSRR原版，正常使用可以访问（UserApiConfig.py   API=sspanelv3)，因为不能服务器监控会显示宕机，使用了 rm -rf shadowsocksr， 安装了最新的 SSRPanel提供的SSRR改版，使用默认配置（UserApiConfig.py API=ssrpanel)
现在的故障是:  运行 bash run.sh，然后运行 python server.py 一直显示Error，提示端口被占用。
                          运行 bash stop.sh, 然后运行 python server.py 一直会实时显示端口正在使用。
尝试过 ps aux 查找pid， fuser -k *****/tcp 清TCP端口，lsof -9 [pid]，全都无果。
python 全部删了重装过也还是这些提示，就差重装服务器系统了，救命!

**Comment by kuangshao11** [comment]
这就是正常运行了

**Comment by mingtochu** [comment]
又正常了，怪自己输错密码了
