### ISSUE TITLE
希望增加码支付

### ISSUE THREAD

**Issue by Bennett561** [ssrpanel/SSRPanel#627]
有赞微小店似乎只能开一家，有两个面板以上的话就比较麻烦。
我看码支付好像挺好用的，也不用备案什么的很简单，不知道有没有做的可能 。

**Comment by Pinkpiglet** [comment]
有赞你不知道在申请个？

**Comment by ZBrettonYe** [comment]
我觉得这个问题有点弱智；

**Comment by Bennett561** [comment]
有赞微小店申请不了两个啊……再申请账号需要验证..只有一个手机搞不了哦


徐捷
