### ISSUE TITLE
重置密码/激活等链接无效

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/SSRPanel#629]
点击邮箱中收到链接跳转提示404,是不是数据库没有对应更新? 我的问题还是程序问题? 需要等待胖虎修复?

**Comment by tonychanczm** [comment]
自己没配置好伪静态，自己去翻wiki研究

**Comment by 1021435278** [comment]
我在表中verify中发现了生成的token,但是不知道为什么是404,难道是因为xx.com/reset/token多了个reset的原因吗?

**Comment by 1021435278** [comment]
重装解决了
