### ISSUE TITLE
一些bug

### ISSUE THREAD

**Issue by flishqq** [ssrpanel/ssrpanel#63]
1.
用户编辑界面付费方式里有两个月付

2.
商品里的套餐有效期是从注册时间往后加的，即如果是17-10-1日注册的，买了一个30天的套餐后账户有效期变成17-11-1，但是我在买一个30的套餐话时间并不会叠加，有效期还是17-11-1

3.
节点生成的二维码我这边扫的话显示无效，不知道为啥

4.
设置-通用配置里修改加密 混淆方式 协议不能生效。新注册用户的配置信息还是默认的

**Comment by ganwen1994** [comment]
二维码确实是有问题的

老版本的SSR识别没问题,新一点的版本就确实是有问题了.

**Comment by ZBrettonYe** [comment]
第一个：在ssrpanel/resources/views/admin 中的 editUser.blade 中第80行修改；这只是打错字，并不是bug。
3. 这个问题只能说设备不兼容
4. 这个问题可以直接去数据库修改解决

**Comment by flishqq** [comment]
@ZBrettonYe
我不是来问这些问题如何解决的，我只是来告诉作者希望下一个版本解决而已。。大家都喜欢在issues里提问导致现在反馈一下bug就直接给解决方法了么。。
至于二维码的问题。。说设备不兼容二维码。。我怎么感觉怪怪的。。反正同样的软件扫其他二维码没出现过这种问题。。

**Comment by ZBrettonYe** [comment]
@flishqq 我只是说一下临时解决办法，最主要的是希望胖虎大大看到以后可以方便对症修代码

**Comment by flishqq** [comment]
@ZBrettonYe
这套面板其实还不错。。等功能慢慢完善了应该算是目前几个开源面包里比较好用的了

**Comment by ssrpanel** [comment]
@flishqq 我的shadowrocket和potatso用了没问题，这两个软件我之前是买的，现在都被下架了，所以，用软件直接扫描二维码是没问题的，用软件里的扫描里的打开本地图片是会报错的，我现在没有办法测试。因为没有更新版本的软件

**Comment by ssrpanel** [comment]
还有，你扫无效，是怎么扫的，截图我看下

**Comment by ssrpanel** [comment]
@flishqq 
1.已修正
2.这个不调整
3.上面已说明
4.拉取最新的代码，正常的
