### ISSUE TITLE
激活邮件无法用Gmail发送

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#630]
driver=mailgun邮件都显示发送成功，但邮件都没有发出去。。。这个不知道问题在哪，暂且不表。

一直用的Gmail发信，更新最新版本后激活邮件发送的时候提示：
```
Connection could not be established with host smtp.gmail.com [php_network_getaddresses: getaddrinfo failed: Name or service not known #0]
```
但此时同样的配置，0点的自动通知邮件是发送成功的，而且邮件也发出去了：
![image](https://user-images.githubusercontent.com/6386202/41050681-ad956fb8-69e6-11e8-83f2-c9c4c302c543.png)
![image](https://user-images.githubusercontent.com/6386202/41050703-bd0b9f1c-69e6-11e8-81ee-13734dc8f079.png)
激活邮件的功能换了个CentOS7.4的系统确实没问题，这是什么幺蛾子知道不？

```
[root@sobaigu]# uname -a
Linux sobaigu.com 4.14.15-1.el7.elrepo.x86_64 #1 SMP Tue Jan 23 20:28:26 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@sobaigu]# cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 
[root@sobaigu]# php --version
PHP 7.1.15 (cli) (built: Mar 11 2018 03:03:09) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.0.2, Copyright (c) 2002-2017, by ionCube Ltd.
    with Zend OPcache v7.1.15, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by 828768** [comment]
靠，Gmail发激活邮件报`Connection could not be established with host smtp.gmail.com`的问题果然是系统升级的事，7.4升级到7.5就完蛋了有达人研究下么 @ssrpanel 激活邮件用到的发信函数有不一样？

**Comment by 828768** [comment]
谷歌自己的8.8.8.8居然不行，换了个80.80.80.80能解析smtp。google了，而且过一会儿又ping不通了，目前邮件还能发。搞不懂同期激活邮件报错过期预警邮件正常发是咋回事？

**Comment by yeehomlee** [comment]
建议你用 mailgun 就好，按照胖虎的wiki配置好，比其他个人邮箱都稳定。

**Comment by 828768** [comment]
@yeehomlee mailgun折腾了一天，ssrpanel显示发送成功，邮件没收到，mailgun上也没记录，不知道问题在哪，求mailgun发信配置指点

**Comment by ssrpanel** [comment]
自己看wiki
