### ISSUE TITLE
增加商品还是有bug

### ISSUE THREAD

**Issue by Bennett561** [ssrpanel/SSRPanel#632]
很奇怪，我增加了一个400G流量的包年套餐，购买之后却是这样。
已用流量：0B（-199GB）
我是小白，查不出来问题，还请其他大佬看看。
其他套餐都是正常的。

**Comment by Bennett561** [comment]
现在所有套餐都不正常，怎么购买都是只有1024M

**Comment by ssrpanel** [comment]
贴记录

**Comment by Bennett561** [comment]
![11](https://user-images.githubusercontent.com/17747051/41294677-36886606-6e8b-11e8-97fa-88104a9de275.png)
我先后购买了两个套餐，第一个1000G流量，第二个400G流量，结果第二次买完只有100G流量，各种时候有各种不一样的数值，我很迷。不太确定你要我贴什么记录，服务器日志是没报任何错误。
