### ISSUE TITLE
重装站点

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/SSRPanel#633]
打算重装目前站点, 请问数据库中哪些表导出即可完整转移? 谢谢.

**Comment by yeehomlee** [comment]
ssrpanel 全部表。

**Comment by Bennett561** [comment]
改了不少

**Comment by 1021435278** [comment]
@yeehomlee  有些表不需要的

**Comment by Bennett561** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
确实，不过为了防止出错还是都搞了好，不然还得看代码，，本小白看得太累了



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    
    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    
徐捷


                


    在2018年6月9日 22:39，ifengsheng<notifications@github.com> 写道： 


@yeehomlee  有些表不需要的
