### ISSUE TITLE
升级面板以后Quantumult无法更新订阅

### ISSUE THREAD

**Issue by cciecm** [ssrpanel/SSRPanel#639]
升级面板后，在Quantumult中更新订阅，提示 

> NOT found any shadowsocks(R)

在Shadowrocket里正常。

**Comment by ssrpanel** [comment]
Quantumult 不是正规的SSR订阅规则

**Comment by cciecm** [comment]
今天有两个Android用户也反馈不能更新订阅。Android客户端版本3.5.4

**Comment by cciecm** [comment]
这个不像是客户端的问题

**Comment by Bennett561** [comment]
安卓不能订阅我这也有不少……
