### ISSUE TITLE
抱歉又来提问题了, Online Log 和Goods的问题

### ISSUE THREAD

**Issue by Hao-Luo** [ssrpanel/ssrpanel#64]
1. 我的Online Log这个Table是空的，我看了下实现也不知道为什么是空的。是SSR Node要写进这个Table但是没写么？
2. Goods有效期是不是有问题， 在添加商品的时候有days这个属性，但是购买商品的时候goods model没有days这个属性。 在Php template里面用的是start_date - end_date. 这些goods都没有属性。 建议可以改成today + goods.days.
3. 怎么帮别人的账户充值?
4. 建议使用ordergoods的table里面的price加上余额总数来计算利润。
5. 邮件模板希望可以加入自定义功能。

**Comment by ssrpanel** [comment]
@Hao-Luo online log这个是ssr后端写入的，你要在节点的usermysql.json里的node_id里填上面板添加的节点对应的ID
2.goods这个我研究下
3.这个得改整套的钱的流量，所以暂时不考虑
4.这个以后跟3改了之后再一起改
5.邮件模板自定义啥？

**Comment by Hao-Luo** [comment]
谢谢回复，
1. 我后端的usermysql.json已经填入了node_id，是不是哪里有问题。
5. 邮件模板就是比如到期邮件之类的模板。改成可以自己自定义文字的。

**Comment by ssrpanel** [comment]
@Hao-Luo 子节点要能连得上主节点（数据库），可以先把子节点的iptables关掉试一下，数据库要对其进行授权grant

**Comment by Hao-Luo** [comment]
iptables是肯定没问题的，子节点能连得上主节点，数据库也肯定是可以连通的，已经测试过了，还是不知道为什么online log是空的。
