### ISSUE TITLE
有赞云未支付账单的影响   流量自动重置的逻辑欠缺

### ISSUE THREAD

**Issue by 110560** [ssrpanel/SSRPanel#642]
有赞云未支付的套餐  会导致用户流量为该套餐包含流量的负数  情况如下
情况:购买A套餐 在线支付 未支付  套餐流量为该套餐的负数
举例:
比如你这个套餐有30GB  你的流量就    -30GB
比如套餐B为200GB  套餐A为30GB（套餐A在线支付未支付，套餐B余额支付）
 显示可用流量为170GB
流量自动重置逻辑欠缺 
情况: 如果用户提前把流量用完  账号状态禁用，到了流量重置日它是不会自动重置的
举例 :
套餐的自动重置日6月14号   6月9号已经提前把所有流量用完  账号状态禁用
6月14号 并不会自动重置已用流量   账号状态也不会自动恢复正常

**Comment by ssrpanel** [comment]
应该修复了？

**Comment by ssrpanel** [comment]
还会有这种情况吗？
