### ISSUE TITLE
订单管理总是出现酱紫的情况

### ISSUE THREAD

**Issue by kkkway** [ssrpanel/SSRPanel#643]
![image](https://user-images.githubusercontent.com/24932999/41405046-6334ca0c-6ffb-11e8-8a03-92cf1b2388ef.png)
如图，看了之前几个issuse，发现没有好的解决办法啊，这个到底是什么个情况，大佬能不能给我的解释一下o.o

**Comment by kkkway** [comment]
我发现是进数据库手动删除下过单的用户，会出现这样的情况，但是用户总得删除的啊，何不加入一个按钮来删除呢@ssrpanel

**Comment by kuangshao11** [comment]
依赖太多了，一开始就没分离开，删用户的话很多东西读取不到uid就出bug了

**Comment by kkkway** [comment]
是的，删用户的同时 得同时把该用户的订单记录什么的 统统删掉  才不会这样
