### ISSUE TITLE
为什么我的测试账户充值购买服务之后还是一直看不到任何节点

### ISSUE THREAD

**Issue by Cathgao** [ssrpanel/SSRPanel#644]
我已经在管理后台添加可用节点，而且我的管理员账户也看到了这个节点，但测试账户的“我的节点”一直是空的
![default](https://user-images.githubusercontent.com/21031564/41444437-a0f4ac8e-7075-11e8-916d-7e71d4e1c0ad.PNG)

**Comment by MrPangzhan** [comment]
你的用户是上面标签，节点是上面标签。两者要一样。check....

**Comment by Cathgao** [comment]
这个问题解决了，然后有新的问题。
节点列表里的节点产生流量永远是0B，但是走势图又能看到流量用量
![1](https://user-images.githubusercontent.com/21031564/41452983-b41126a4-70a6-11e8-8fa1-c337e6009ea0.PNG)

![default](https://user-images.githubusercontent.com/21031564/41452991-ba1c820a-70a6-11e8-8e29-c138331e9b14.PNG)

**Comment by MrPangzhan** [comment]
明天在看看，如果还是没有就看你的计划任务有没有问题

**Comment by ssrpanel** [comment]
定时任务没有跑起来，很可能是因为你使用了宝塔，crontab 用的不是跟同跑php相同用户去跑
