### ISSUE TITLE
关于SSR(R)禁用状态用户前端购买套餐流量无法解除禁用

### ISSUE THREAD

**Issue by MrPangzhan** [ssrpanel/SSRPanel#645]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
![3](https://user-images.githubusercontent.com/39323056/41444425-9195d830-7075-11e8-8cdc-5b997a33d410.png)
描述：
1、用户是免费体验的标签，分配了1G的体验流量，1G流量用完后，前台界面就显示禁用状态。我看后台节点的标签被清除，SSR(R)禁用，前端界面看不到节点。

2、用户前端购买一个10G流量包使用余额支付，前端界面可以看到节点，但是状态还是禁用，神奇的是过了一分钟后刷新下又看不到节点了（估计是自动任务又删除了标签），查看面板日志正常，没有报错。

是我设置的问题还是Bug。请各位大佬指教！

**Comment by biigaa** [comment]
修改到期时间,改超过当前时间,再试

**Comment by ssrpanel** [comment]
有bug 等待修复

**Comment by longdoer** [comment]
这个问题我也发现了 昨天有个用户就是这样 过期禁用以后购买没起作用

**Comment by ssrpanel** [comment]
已修复
