### ISSUE TITLE
Andoird客户端无法更新订阅

### ISSUE THREAD

**Issue by cciecm** [ssrpanel/SSRPanel#649]
机型包括小米、华为、Nexus
客户端版本 3.53 3.54

重装系统和客户端不能解决该问题。

**Comment by cciecm** [comment]
反馈该问题的人非常多，今天就有4个

**Comment by cciecm** [comment]
刚刚又来一个反馈Quantumult不能订阅。以前可以的。请问要搜集什么日志？？

**Comment by cciecm** [comment]
查服务器订阅请求记录，空的

**Comment by yeehomlee** [comment]
1、那 Windows 客户端可以订阅吗？
2、若不行，检查订阅地址(域名) 的问题。

**Comment by cciecm** [comment]
@yeehomlee 
PC/Mac/路由器客户端可以。iOS Shadowrocket可以
问题在面板升级后出现
Android客户端全部不行，无论任何版本
Quantumult户端全部不行，无论任何版本
上述两个客户端发起订阅请求，服务器端没有产生日志。

**Comment by yeehomlee** [comment]
特地测试了一下，
Android 5.1，SSRR 客户端，https 订阅地址，最新ssrpanel代码。
可以的。
供你参考。

**Comment by willyyang1** [comment]
订阅地址该不会是www.ssrpanel.com(?我刚刚也没调。正納悶着

**Comment by cciecm** [comment]
@willyyang1 当然不是。PC/Mac/路由器/iOS Shadowrocket客户端可以订阅

**Comment by ssrpanel** [comment]
安卓使用低版本SSRR 或者 最后一个版本的SSR，我试了，魅族也有这个问题，没招。那个 Quantumult 我没有app，所以无法测试。你们可以尝试订阅一下然后发我最后10条 user_subscribe_log日志我看下

**Comment by cciecm** [comment]
@ssrpanel 这个日志的路径是在哪？

**Comment by ssrpanel** [comment]
在数据库里：user_subscribe_log 这个表，你可以倒叙导出最后10条，处理一下订阅地址，然后贴上来，如果没有产生订阅日志，100%客户端的问题

**Comment by MrPangzhan** [comment]
@ssrpanel 处理过的日志，目前安卓和PC订阅正常。安卓：3.5.4  PC：4.7

(94, 1, '00.00.00.00', '2018-06-12 16:06:06', 'Accept:          */*\r\nAccept-Encoding: deflate, gzip\r\nContent-Length:  \r\nContent-Type:    \r\nHost:            ss.domain.com\r\nUser-Agent:      Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.94 Safari/537.36\r\n'),
(95, 2, '00.00.00.00', '2018-06-13 18:54:48', 'Connection:     Keep-Alive\r\nContent-Length: \r\nContent-Type:   \r\nHost:           ss.domain.com\r\nUser-Agent:     Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36\r\n'),
(96, 2, '00.00.00.00', '2018-06-13 19:18:23', 'Connection:     Keep-Alive\r\nContent-Length: \r\nContent-Type:   \r\nHost:           ss.domain.com\r\nUser-Agent:     Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36\r\n'),
(97, 1, '00.00.00.00', '2018-06-13 21:35:25', 'Accept:          */*\r\nAccept-Encoding: deflate, gzip\r\nContent-Length:  \r\nContent-Type:    \r\nHost:            ss.domain.com\r\nUser-Agent:      Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.94 Safari/537.36\r\n'),
(98, 2, '00.00.00.00', '2018-06-15 11:58:08', 'Connection:     Keep-Alive\r\nContent-Length: \r\nContent-Type:   \r\nHost:           ss.domain.com\r\nUser-Agent:     Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36\r\n'),
(99, 2, '00.00.00.00', '2018-06-15 17:43:50', 'Connection:     Keep-Alive\r\nContent-Length: \r\nContent-Type:   \r\nHost:           ss.domain.com\r\nUser-Agent:     Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36\r\n'),
(100, 2, '00.00.00.00', '2018-06-15 20:31:13', 'Connection:     Keep-Alive\r\nContent-Length: \r\nContent-Type:   \r\nHost:           ss.domain.com\r\nUser-Agent:     Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36\r\n'),
(101, 2, '00.00.00.00', '2018-06-16 09:47:41', 'Connection:     Keep-Alive\r\nContent-Length: \r\nContent-Type:   \r\nHost:           ss.domain.com\r\nUser-Agent:     Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36\r\n'),
(102, 2, '00.00.00.00', '2018-06-16 10:58:40', 'Connection:     Keep-Alive\r\nContent-Length: \r\nContent-Type:   \r\nHost:           ss.domain.com\r\nUser-Agent:     Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36\r\n'),
(103, 2, '00.00.00.00', '2018-06-17 17:52:58', 'Connection:     Keep-Alive\r\nContent-Length: \r\nContent-Type:   \r\nHost:           ss.domain.com\r\nUser-Agent:     Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36\r\n'),
(104, 2, '00.00.00.00', '2018-06-18 09:53:35', 'Connection:     Keep-Alive\r\nContent-Length: \r\nContent-Type:   \r\nHost:           ss.domain.com\r\nUser-Agent:     Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36\r\n'),
(105, 2, '00.00.00.00', '2018-06-18 19:04:19', 'Connection:     Keep-Alive\r\nContent-Length: \r\nContent-Type:   \r\nHost:           ss.domain.com\r\nUser-Agent:     Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36\r\n'),
(106, 2, '00.00.00.00', '2018-06-19 11:32:51', 'Connection:     Keep-Alive\r\nContent-Length: \r\nContent-Type:   \r\nHost:           ss.domain.com\r\nUser-Agent:     Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36\r\n'),
(107, 2, '00.00.00.00', '2018-06-19 14:20:09', 'Connection:     Keep-Alive\r\nContent-Length: \r\nContent-Type:   \r\nHost:           ss.domain.com\r\nUser-Agent:     Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36\r\n'),
(108, 2, '00.00.00.00', '2018-06-19 17:32:41', 'Connection:     Keep-Alive\r\nContent-Length: \r\nContent-Type:   \r\nHost:           ss.domain.com\r\nUser-Agent:     Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36\r\n'),
(109, 2, '00.00.00.00', '2018-06-19 18:26:14', 'Connection:     Keep-Alive\r\nContent-Length: \r\nContent-Type:   \r\nHost:           ss.domain.com\r\nUser-Agent:     Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36\r\n'),
(110, 2, '00.00.00.00', '2018-06-20 10:25:27', 'Connection:     Keep-Alive\r\nContent-Length: \r\nContent-Type:   \r\nHost:           ss.domain.com\r\nUser-Agent:     Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36\r\n');

**Comment by cciecm** [comment]
@ssrpanel 测试了Android和Quantumult。没有任何日志产生。

**Comment by cciecm** [comment]
@ssrpanel 新买了台VPS，全新安装。把节点迁移到新节点。此问题仍然存在。

**Comment by cciecm** [comment]
@ssrpanel 这个bug对我们影响实在太大，最后我们自己研究解决了。

**Comment by ssrpanel** [comment]
@cciecm 怎么解决的？我

**Comment by ssrpanel** [comment]
bug个屁，根本不是bug，我拿小米和魅族都试过了，无论是http还是https都是一点毛病都没有，订阅地址是有区分大小写的

**Comment by cciecm** [comment]
这个问题我们在三台新装机器上可以复现。是订阅部分的配置文件错误，改了就好了。
