### ISSUE TITLE
小白可以用的一键搭建ssrpanel

### ISSUE THREAD

**Issue by echo-marisn** [ssrpanel/ssrpanel#65]
胖虎兄弟别打我

[https://blog.67cc.cn/archives/new-ss-panel-ssrpanel-one-click-script-version.html](https://blog.67cc.cn/archives/new-ss-panel-ssrpanel-one-click-script-version.html)

**Comment by Hao-Luo** [comment]
贡献一个节点的， 带systemd守护的。

**Comment by Hao-Luo** [comment]
https://github.com/Hao-Luo/Others/tree/master/apps/ssr

**Comment by ssrpanel** [comment]
@d1059053986  @Hao-Luo  好滴，谢谢参与

**Comment by ssrpanel** [comment]
@d1059053986 给你挂到wiki了，哈哈哈

**Comment by DearTanker** [comment]
@Hao-Luo 这2个可以改成安装过程可选操作吗。

**Comment by Hao-Luo** [comment]
这2个本身是分开的，输入1就是安装node,输入2就是安装bbr

**Comment by ssrpanel** [comment]
@Hao-Luo 赞，挂到WIKI里了。
