### ISSUE TITLE
git pull 后，系统设置页面无法打开

### ISSUE THREAD

**Issue by ZhangqianStudio** [ssrpanel/SSRPanel#652]
![image](https://user-images.githubusercontent.com/19299425/41508601-fecedc16-7279-11e8-96b0-288361b1f530.png)
报错请见上图
或许是个已知 bug? 希望抽空修一下

**Comment by xsaddata** [comment]
更新后请及时导入最新的SQL文件，这次更新了限购，数据库会增加相应的表项，你需要从update文件内找到最新的SQL文件，直接导入即可。

**Comment by ZhangqianStudio** [comment]
明白了。谢谢
