### ISSUE TITLE
一次性优惠码能够多次重复使用bug

### ISSUE THREAD

**Issue by tonychanczm** [ssrpanel/SSRPanel#659]
购买商品时输入优惠码，然后使用在线支付，创建订单后先不付款，在用一次那个优惠码创建一个新的订单，如此循环，最后慢慢付款，这样子就能做到一张一次性优惠码能够多次使用
修正思路：
提交订单时先把优惠码置无效，或者设置为的新的状态（比如待使用），如果支付，则置无效，如果不支付，等到过期的时候就自动把优惠码恢复为可用状态

**Comment by ssrpanel** [comment]
。。。。

**Comment by ssrpanel** [comment]
修正了
