### ISSUE TITLE
SS兼容模式无法使用，user-config修改过，连接提示无法解析报头

### ISSUE THREAD

**Issue by mtk00713** [ssrpanel/ssrpanel#66]
ERROR    tcprelay.py:1097 can not parse header when handling connection from 

config数据
{
    "server": "0.0.0.0",
    "server_ipv6": "::",
    "server_port": 8388,
    "local_address": "127.0.0.1",
    "local_port": 1080,

    "password": "m",
    "method": "aes-192-cfb",
    "protocol": "auth_sha1_compatible",
    "protocol_param": "",
    "obfs": "http_simple_compatible",
    "obfs_param": "",
    "speed_limit_per_con": 0,
    "speed_limit_per_user": 0,

    "additional_ports" : {}, // only works under multi-user mode
    "additional_ports_only" : false, // only works under multi-user mode
    "timeout": 120,
    "udp_timeout": 60,
    "dns_ipv6": false,
    "connect_verbose_info": 1,
    "redirect": "",
    "fast_open": false
}
~
~

**Comment by ssrpanel** [comment]
"protocol": "auth_sha1_compatible",   =====> 改 auth_sha1_v4_compatible
"obfs": "http_simple_compatible",   =====> 改 tls1.2_ticket_auth_compatible

**Comment by ssrpanel** [comment]
@mtk00713
