### ISSUE TITLE
123行处报错 fseek() expects at least 2 parameters, 1 given 

### ISSUE THREAD

**Issue by Losgif** [ssrpanel/SSRPanel#662]
```
fseek($fp, 0);
```
![image](https://user-images.githubusercontent.com/13404752/41648662-20fd90fa-74ac-11e8-9081-1e3a0567a6c1.png)

**Comment by ssrpanel** [comment]
没毛病啊。你的记录数不够就产生这个错误

**Comment by Losgif** [comment]
可是报错信息不是说 123行 fseek 函数需要 两个参数，但是只给了一个？
