### ISSUE TITLE
流量包和套餐

### ISSUE THREAD

**Issue by haygcao** [ssrpanel/SSRPanel#669]
我昨天在设置流量包和套餐的时候发现一个问题。就像我们买手机套餐可以买一个月的然后下个月换其他的套餐，但是ssrpanel得套餐有效期最低是90天，不能设置30天。然后我还想test半年或者3个月的套餐，每30天后自动重置流量，然后套餐到期后流量变为0，但好像都不成功。不知道是不是我的设置有问题

**Comment by Chennhaoo** [comment]
30天的可以用流量包代替，我怀疑你定时任务没设置好。
