### ISSUE TITLE
各位大佬，你们是怎么控制每个节点的人数的？

### ISSUE THREAD

**Issue by SheffieldLee** [ssrpanel/SSRPanel#673]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问

**Comment by Chennhaoo** [comment]
请先翻一遍CLOSED的Issues，里面应该有。

**Comment by SheffieldLee** [comment]
我发现，只要他们只要知道我另一个节点的ip，他就可以把ip改成那个节点，直接上？哪怕他的标签里没有这个节点的标签。我的问题是，怎么能让他只能用自己标签归属的服务器？？？？

**Comment by cmtomkan310** [comment]
@SheffieldLee 这个问题一直存在，不能单独控制用户对应节点的开关，其实这个应该和标签挂钩，用户有某个节点的标签，就只能用这个节点，无标签的节点，即便知道ip也无法使用！其实这算个大bug

**Comment by SheffieldLee** [comment]
所以胖虎大佬能不能想个法子解决这个问题 ，加个开关啥的，让用户只能用它自己标签的服务器，不能用它没有标签的服务器，我发现所有服务器端口、密码、混淆、协议都是一样的，所以存在这种情况：他上个月买了这个标签的服务器，这个月换成了另一个标签，，所以他们一些耍小聪明的人，发现了只要改IP，就能穿梭于各个服务器，我将他们毫无办法。。。。。

**Comment by cmtomkan310** [comment]
呵呵！中国人就是聪明！

**Comment by 1021435278** [comment]
这个问题其实比较容易解决, 找胖虎每个节点单独一个表增加到数据库中就可以解决了.

**Comment by SheffieldLee** [comment]
搞多张表，这个方法行不通吧？节点是直接从数据库读userconfig，你搞多张表的意思是每个节点用户存在不同的端口、密码吗？那客户面板岂不是多一个节点，就多一套端口、密码？

**Comment by SheffieldLee** [comment]
我觉得这样可以，一张用户表，但是可以设置多张密码表，每个节点都对应一张密码表，密码表是用户表的密码字段的外键，默认select from密码表。
当用户拥有该节点的标签的时候，他的密码就是用户表中的密码，当用户失去这个节点标签后，然后用随机密码填充这个节点的密码表，不级联更新用户表，这样他不知道这个随机密码，他就连不上这个节点了。
这样可行吗？

**Comment by tonychanczm** [comment]
用mu-api即可解决

**Comment by cmtomkan310** [comment]
@tonychanczm 具体讲讲呗

**Comment by SheffieldLee** [comment]
@tonychanczm 讲讲呗

**Comment by yeehomlee** [comment]
我是这样解决的，每个节点的协议、混淆参数、单端口多用户密码，都是不同的。
有本事给我猜去。

**Comment by DreamSeekerKaiser** [comment]
能月入5万么 我想搞这个实现财务自由 不再上班啥的

**Comment by ssrpanel** [comment]
@DreamSeekerKaiser 5万我不知道，不过我已经知道小群里有几个 月入2万+的，辞职在家全职干这个

**Comment by DreamSeekerKaiser** [comment]
胖虎 我知道是你 ～～ 人进终年不能在这样下去了

**Comment by yeehomlee** [comment]
@DreamSeekerKaiser  可以呀，帮我解决拉新的问题。

**Comment by ssrpanel** [comment]
@DreamSeekerKaiser 是啊，我要是不开源，靠卖面板应该也可以挣点钱，不过算了。。

**Comment by DreamSeekerKaiser** [comment]
@yeehomlee  请转账付费妥妥的

**Comment by DreamSeekerKaiser** [comment]
PYTHON ssr 后端启动服务获取用户的时候 只获取属于自己这个节点的用户数据 即可~ 不属于自己节点的用户不启动服务这样用户就无法通过链接验证 就无法使用该节点 select * from user where node='服务器节点标识'
