### ISSUE TITLE
建议：SMTP发送失败提醒

### ISSUE THREAD

**Issue by tonychanczm** [ssrpanel/SSRPanel#674]
胖虎大佬，提一个建议，就是注册激活邮件如果发送失败的话，建议发个方糖微信通知给管理员处理
话说今天突然发现我那个邮件smtp在前天炸了，就很崩溃，2天错过了10多个用户，不怪得这几天一分钱都没有收2333

**Comment by ssrpanel** [comment]
...MMP

**Comment by cmmdwl** [comment]
稍微看了下，投递要么ok要么报这样的错误
Failed to authenticate on SMTP server with username "xxx@qq.com" using 1 possible authenticators

**Comment by cmmdwl** [comment]
顺便建议将ServerChan与smtp的投递日志分开

**Comment by ssrpanel** [comment]
> 顺便建议将ServerChan与smtp的投递日志分开

已分开

邮件发送已经改为队列发送，不会发失败了
