### ISSUE TITLE
关于前端和后端链接的一些问题

### ISSUE THREAD

**Issue by cardbug** [ssrpanel/ssrpanel#68]
当前端面板把用户等级降级时，用户已经使用的高级节点依然可以使用。应该是数据库没有及时共享过去给节点服务器还是说是数据库的分享单向的。。。
然后就是，git pull的时候提示
error: Your local changes to '.env' would be overwritten by merge.  Aborting.
Please, commit your changes or stash them before you can merge.
emmm这个怎么解决呀。。。

**Comment by ssrpanel** [comment]
@cardbug 目前高等级的节点是可以用滴。。只是不可见

**Comment by cardbug** [comment]
对。。就是有没有办法在降极用户之后，在高等级节点服务器中取消这个端口

**Comment by ssrpanel** [comment]
@cardbug 我找到办法了，在开发中
