### ISSUE TITLE
tcp ping check tool

### ISSUE THREAD

**Issue by ssrpanel** [ssrpanel/SSRPanel#681]
https://check-host.net/check-tcp?host=

**Comment by cmmdwl** [comment]
这个是打算接入面板用来监视服务器是否正常的？

**Comment by ssrpanel** [comment]
@cmmdwl 已经捐了一台服务器给他们家了，也上线了，是打算用来做防墙自检用。当节点被TCP阻断第一时间通知管理员

**Comment by ssrpanel** [comment]
一家
