### ISSUE TITLE
username为什么是邮箱……

### ISSUE THREAD

**Issue by silenvps20** [ssrpanel/SSRPanel#682]
胖虎大佬，明明是用户名，用的却是邮箱，话说数据库可不可以加个mail字段……

**Comment by silenvps20** [comment]
还有付款方式除了免费月付半年付年付外，可以再加个季付吗

**Comment by ssrpanel** [comment]
username 那个 是早期为了兼容sspanle 统一那么搞的，那个付款方式 阔以阔以。。

**Comment by silenvps20** [comment]
现在sspanel 魔改都是有username和mail。付款方式感觉最好就是能够自定义

**Comment by ssrpanel** [comment]
魔改一堆开发者在折腾，我这个基本就我一个人在折腾
