### ISSUE TITLE
一个不错的免费的在线聊天插件

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/SSRPanel#683]
www.tawk.to
可以设置欢迎词等,多语言

**Comment by ssrpanel** [comment]
mark

**Comment by ZBrettonYe** [comment]
https://www.xianliao.me/ 

這個可以給用戶頁面添加 一個群聊窗口

**Comment by ssrpanel** [comment]
@ZBrettonYe 这个闲聊么根本无法注册，喊了他们的技术、商务的QQ，感觉项目要死了？？？连个注册页面都搞不好。。。

**Comment by ZBrettonYe** [comment]
我看到过 一个福利导航加入了这个 https://yuexiangzs.com/

**Comment by ssrpanel** [comment]
@ZBrettonYe 这个闲聊么响应速度非常的糟糕，昨天中午说的bug，到今天还没修复。根本没法注册。我要关闭这个了

**Comment by ssrpanel** [comment]
@1021435278 如果网站用户多是非大陆，推荐用tawk ，我试过了确实好用。如果用户多是大陆用户，国内有竞品 ：美洽  ，这个东西也很棒，推荐

**Comment by ssrpanel** [comment]
@ZBrettonYe 这个闲聊么真心不行，到尽头还没修复注册，完全没法注册的
