### ISSUE TITLE
国旗材质更新

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/SSRPanel#685]
原有国旗图标 存在白色斜杠水印

食用方法：覆盖原有country文件夹

[country.zip](https://github.com/ssrpanel/SSRPanel/files/2143465/country.zip)

**Comment by ssrpanel** [comment]
合并了

**Comment by ZBrettonYe** [comment]
[country.zip](https://github.com/ssrpanel/SSRPanel/files/2148293/country.zip)
这是最新的了，补上漏掉的；

还有原国旗里有一个标错的多余国旗。 @ssrpanel
