### ISSUE TITLE
如果降低起始端口

### ISSUE THREAD

**Issue by cheapssr** [ssrpanel/ssrpanel#69]
搭建好，发现端口10000起的
怎么才能降低呢，我想1100端口起

**Comment by ssrpanel** [comment]
@cheapssr 我加个整个自定义端口生成范围吧，目前可以手动编辑账号的端口

**Comment by ssrpanel** [comment]
@cheapssr 代码更新了，拉一下代码，然后执行一下sql/20171101.sql
