### ISSUE TITLE
首页文字修改的问题

### ISSUE THREAD

**Issue by Chennhaoo** [ssrpanel/SSRPanel#690]
我想删除首页的语言选择，让语言默认显示英语，效果如图
![2018-06-30_203249](https://user-images.githubusercontent.com/38855823/42125391-8079fd58-7ca8-11e8-8f15-15a401378b98.png)

我修改 `\resources\views\login.blade.php`文件中的
修改第5行： `<html lang="{{app()->getLocale()}}">` 为 `<html lang="en">`

删除40行-68行
```
<nav style="padding-bottom: 20px;text-align: center;">
       @if(app()->getLocale() == 'zh-CN')
       ........
       @endif
</nav>
```

刷新后为什么首页没有变化啊，请各位给我看看。

**Comment by ssrpanel** [comment]
你不看项目wiki，只需要改config/app.php 的 locale 为en即可

**Comment by Chennhaoo** [comment]
感谢解答，请问首页那个语言选择怎么删除啊，我修改`\resources\views\login.blade.php`怎么没反应啊
