### ISSUE TITLE
用户的订单中添加一个取消支付

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#694]
发现用户一次只能进行一个订单，
建议在用户的订单中添加一个取消支付，方便点错订单的用户取消订单。
我看了下数据库payment下有保留一个-1的标志，所以只要添加一个按钮将0修改为-1
丢个MySQL语句给你，我不太会写php
话说萌新不懂赞赏码如何使用，教一下？
mysql语句

UPDATE `be*****r_com`.`payment` SET `status` = '-1' WHERE `payment`.`id` = 1
UPDATE `be*****r_com`.`order` SET `status` = '-1' WHERE `order`.`oid` = 4

**Comment by ssrpanel** [comment]
你是在线支付是吗？同一个商品在30分钟内就是要限制，下了单不买再下了单再不买再下单再不买，你的接口很容易被有赞给封掉的

**Comment by ssrpanel** [comment]
如果是下了A商品没付款，但是现在又想下B商品，但是无法下，这个才算是bug，你可以测试一下？

**Comment by cmmdwl** [comment]
确实，可以进行不同的订单操作
