### ISSUE TITLE
有赞云支付报错

### ISSUE THREAD

**Issue by shijingyu** [ssrpanel/SSRPanel#696]
Issues和wiki都找了，商品在线支付报错：
**创建支付订单失败：参数 client_id 不正确**
对比了有赞云控制台是正确的，看了config数据库也是正确的，用的是有赞微小店。
请问怎么解决？

**Comment by shijingyu** [comment]
权限给了 睡了一觉好了  不知道啥情况- -

**Comment by woodytang** [comment]
这个不是权限问题，出问题在这段代码：
`if (Cache::has('YZY_TOKEN')) {
          	
            $token = Cache::get('YZY_TOKEN');
         
            if (isset($token['error'])) { // 错误兼容
                Cache::forget('YZY_TOKEN');
            } else {
                return Cache::get('YZY_TOKEN')['access_token'];
            }
        }`
缓存的token有问题，@作者 能不能解释一下为啥要缓存token？我不太懂支付流程
