### ISSUE TITLE
BUG反馈：未完成的订单关闭后，仍会触发「商品限购」机制

### ISSUE THREAD

**Issue by yeehomlee** [ssrpanel/SSRPanel#697]
**环境：**
「商品限购」开启「限全部商品」。

**场景：**
购买A套餐时，选择在线支付，没有及时完全支付，30分钟后订单自动关闭。

**问题：**
再次重新购买A套餐，会提示商品限购的「已有商品，无法重复购买」。

也就是说，
用户选了A套餐，没及时完成支付，今后无论如何都没法再次购买A套餐了。
一是未完成的订单也触发了限购机制，二是用户也没法自己删除订单。
而且甚至相隔一两个月仍然一样，并没有时间关联。

不确定这是否我的个例，因为demo站我无法访问，测试不了。
请各位确认，谢谢。

**Comment by yeehomlee** [comment]
另外，建议「商品限购」允许选择「限购套餐」、「限购流量包」。

我个人觉得，该功能最大的用处，就是防止用户重复购买套餐导致覆盖，造成不必要的纠纷。

**Comment by ilovebamboo** [comment]
看看我的

**Comment by ssrpanel** [comment]
@yeehomlee 已修复，待提交
