### ISSUE TITLE
希望大佬能开发出一个站群服务器多IP挂SSR后端的解决方案。

### ISSUE THREAD

**Issue by heyuan0028** [ssrpanel/SSRPanel#698]
一般情况下，我们开的机子都是只有一个ip，然后是多用户共享使用一个节点，即多个用户使用一个IP。如果使用站群服务器的话，举例一个站群服务器里带有256个IP，那么我想把这256个IP分配给256个用户，即一个用户一个独立的IP。目前我还没有找到一个能够对接ssrpanel前后端的解决方案，在此之前，秋水大佬的一个SSR一键安装包，可以不需要绑定IP，直接是什么IP连入，就什么IP出站访问，只需要设置多个端口用户即可，即一个站群服务有多少个IP，设置多少个端口和密码。issues：https://github.com/teddysun/shadowsocks_install/issues/3    虽然这个方案能够接近完美的解决我提出的这个问题，但是由于难以管理这么多的用户，比如续费等一些问题，看下大佬是否有思路解决这个问题

**Comment by heyuan0028** [comment]
具体的实现方案可能会比较复杂，一个node，里面需要含有256个IP信息，因为每个用户都需要独立使用一个IP，所以不能使用DNS均衡解析，所以每个用户在节点信息显示IP是不一样的。

**Comment by ssrpanel** [comment]
marked

**Comment by ssrpanel** [comment]
可以实现的，部署多个后端，后端用的mu api访问，但是多个后端开放的端口范围不能重叠

**Comment by ssrpanel** [comment]
本质上这样：1台VPS有多个IP，这些IP想把它变成多个节点展示（实质上还是只有一台服务器而已）。

**Comment by ssrpanel** [comment]
@heyuan0028 dns负载均衡解析，那个，求教程。。。国内的不要，帮我找找国外的厂家
我最近在搞ddns

**Comment by heyuan0028** [comment]
本质上这样：1台VPS有多个IP，展示一个节点，但是每个用户看到的节点信息的IP都是不一样的，即一个用户独立享受一个IP（实质上还是只有一台服务器而已）。

**Comment by heyuan0028** [comment]
如果部署多个后端，如果一个VPS有256个IP，那么就要部署256个后端，太多了，我想能否一个后端实例能够处理完这256个IP链接

**Comment by heyuan0028** [comment]
大多数域名注册商都支持对统一主机添加多条A记录，你试一下，目前我知道的国内的DNSPOD可以，其他国外的我没有试过，你可以试一试国外知名的DNS服务商添加同一主机名不同的A记录试一试，另外DNS均衡负载的解析是随机选择的。

**Comment by heyuan0028** [comment]
这个的话，DNS均衡负载应该可以完成你的需求，但是不清楚客户机在进行随机解析的时候是否会自动跳过那个被Q的IP地址选择其他的解析记录，你可以在测试环境下进行测试

**Comment by ssrpanel** [comment]
我买了一台杜甫 带 5个IP，最近测试下

**Comment by heyuan0028** [comment]
最好就是有批量导入？还是后段对接解决多ip的配置问题？目前我这边站群服务器都是绑定256个ip的😂

**Comment by ssrpanel** [comment]
我之前特定花了几百块买了一个多IP的vds，还在研究

**Comment by heyuan0028** [comment]
我有一个256ip的vps闲置 可以给你做测试

**Comment by heyuan0028** [comment]
用户名就是wx

**Comment by ssrpanel** [comment]
前阵子有小伙伴给我介绍了一个跟你需求一模一样的，最后谈价钱崩了
不知道是不是你
需求跟你差不多，基本等于彻底重写整个后端+面板

**Comment by ssrpanel** [comment]
@heyuan0028

**Comment by ssrpanel** [comment]
这个需求太过于企业化，而且极其小众，需要定制
