### ISSUE TITLE
注册帐户希望加个限制

### ISSUE THREAD

**Issue by ftwl516** [ssrpanel/ssrpanel#7]
测试了一下 如果注册的用户名不是邮箱 激活的时候会报错
希望改成 注册帐户一定要邮箱格式!

**Comment by ftwl516** [comment]
找到SSR服务端所在的ssserver.log文件
进入ssrpanel所在目录，建立一个软连接，并授权
cd /home/wwwroot/ssrpanel/public/storage/app/public
ln -S ssserver.log /root/shadowsocksr/ssserver.log
chown www:www ssserver.log

说明中 建立软连接是不是有错误呢?
CD的路径应该不对!

**Comment by ssrpanel** [comment]
@ftwl516 哈哈，谢谢。
1.晚上回去加校验，明天更新代码
2.第二个问题的话需要看你把ssrpanel装在哪里了，主要目的是进这个目录 ssrpanel/public/storage/app/public 
然后建立软连接到SSR服务端，让ssrpanel可以读取ssserver.log文件
这个目前只支持单节点（就是SSRPANEL 和 SSR服务端在同一个VPS上）

**Comment by ssrpanel** [comment]
@ftwl516 代码已更新
