### ISSUE TITLE
订单管理页面“不存在”

### ISSUE THREAD

**Issue by GaryH4** [ssrpanel/SSRPanel#700]
<del>请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问</del>都翻了
控制面板里面的“订单管理”页面打不开，提示“页面不存在”
文件 resources/views/admin/orderList.blade.php 存在
MySQL中的oederList表 存在且有记录

**Comment by ssrpanel** [comment]
你nginx没有正常的重写规则？？

**Comment by GaryH4** [comment]
添加了，其他网页都打得开

**Comment by woyaoss2017** [comment]
我发现是由于引用了已删除的商品名导致的。
暂时解决办法：
修改orderList.blade.php第87行，改为：
 <td> {{$order->goods ? $order->goods->name:'商品已删除'}} </td>
