### ISSUE TITLE
关于用户支付的问题

### ISSUE THREAD

**Issue by gtx980** [ssrpanel/SSRPanel#704]
支付后钱收到了，但是不会跳转是怎么回事

**Comment by ssrpanel** [comment]
有赞没有提供跳转接口

**Comment by ssrpanel** [comment]
https://bbs.youzan.com/forum.php?mod=viewthread&tid=670618

**Comment by gtx980** [comment]
那该怎么解决，钱收到了但还是待支付，管理面板的也没有回调

**Comment by gtx980** [comment]
问题解决了

**Comment by ssrpanel** [comment]
@gtx980 咋解决的。。

**Comment by gtx980** [comment]
看了下有赞那个日志，然后搜索了下那个代码，开放全部端口，估计防火墙有问题

**Comment by Pinkpiglet** [comment]
@ssrpanel 未支付过几天支付显示二维码过期，无法在支付
