### ISSUE TITLE
Windows不能订阅

### ISSUE THREAD

**Issue by cciecm** [ssrpanel/SSRPanel#709]
看日志，请求头部信息就这么点，没有后续的报文。

Accept-Encoding: gzip
Content-Length:  
Content-Type:    
Host:            网址
User-Agent:      okhttp/3.8.0

抓包显示服务器向客户端发出了RST重置中断请求。

测试过HTTP和HTTPS

同一个网络环境下，Mac/iOS/Android正常

**Comment by ssrpanel** [comment]
1.我正在做一个订阅设备限制功能
2.windows客户端应该是可以正常订阅的，https 和 http都试试，win下https如果可以但是http不可，100%有劫持（运营商往里面丢html了，你换个dns试试，小群里有dns一键切换工具，我都配置好了）

**Comment by cciecm** [comment]
@ssrpanel 抓包看了TTL。没有劫持。如果有劫持，TTL应该有异常变化，但所有报文的TTL都保持一致。何况，同一个路由器下的手机等客户端没这个问题。抓包显示，所有RST都是服务器发的。

**Comment by ssrpanel** [comment]
@cciecm 哦对了，订阅那个，切记要选 不使用代理更新订阅，就是直接更新订阅，再不行就打开软件多手动退出一下试试

**Comment by ssrpanel** [comment]
RST请求中断我也不清楚，你确定你本地没有二级甚至三级代理？把ss给拦住了？

**Comment by cciecm** [comment]
@ssrpanel 这些全试过了…… 从昨天陆续开始有人反馈PC不能订阅，各种运营商都有。之前好的，突然不能订阅了。

**Comment by ssrpanel** [comment]
客户端用的哪个？

**Comment by ssrpanel** [comment]
发上来，我试试

**Comment by ssrpanel** [comment]
如果shadowrocket的订阅正常，说明返回数据是正确的，

**Comment by ssrpanel** [comment]
还有，你第一个贴的那个订阅请求日志是SSR SSRR的安卓版本请求头，不是windows的

**Comment by cciecm** [comment]
我给你建个账户，你订阅连连看

**Comment by ssrpanel** [comment]
好滴，如果不想放出来，就tg私信我

**Comment by cciecm** [comment]
你的TG多少

**Comment by cciecm** [comment]
@ssrpanel https://panel.myharbour.website//s/xk2xK

**Comment by yeehomlee** [comment]
刚也碰到这个问题，上来一看发现有人issues了。

在 ShadowsocksR 4.9.0 (Windows) 客户端上，完全无法更新，不管通不通过代理。
尝试过更换域名、直接使用IP地址、http或https都一样。

好像是最近两三个星期的版本才出现的。
我之前没有这个问题，同一个环境。


**1、不是订阅地址问题。**
我在Android的 SSRR 客户端反复测试，是一切正常的。

**2、不是客户端问题。**
同一个客户端，用别人的SSR地址测试是可以更新的。

**Comment by ssrpanel** [comment]
@yeehomlee @cciecm 神奇了，我用了SSR 可以更新的，

**Comment by ssrpanel** [comment]
破娃 4.7.1 
SSRR 的 4.9
还有我自己改的 4.9.1
都妥妥的

**Comment by yeehomlee** [comment]
@ssrpanel 
*破娃 4.7.1
SSRR 的 4.9*
这两个能否提供一下地址，我这边试试？

**Comment by cciecm** [comment]
@yeehomlee 你测试他的没有用。这个问题不是每个机器都有。

**Comment by yeehomlee** [comment]
@cciecm 我想看一下是不是客户端的问题，毕竟我在其他终端上可以。

那胖虎大佬不是测试了你的SSR订阅地址了吗？不是可以吗？

**Comment by cciecm** [comment]
@yeehomlee 不是客户端的问题。今天就有5个Windows用户问我这个问题，现在就有一个。

**Comment by ssrpanel** [comment]
@yeehomlee 我的都正常

**Comment by cciecm** [comment]
@ssrpanel 订阅用HTTP/HTTPS不影响结果。问题不在通信过程。Windows客户端不行，其它的可以，服务器主动发RST，最近的版本才有这个问题。这些现象表示：Windows客户端和服务器端不能正确理解对方发的消息。服务器端的某个配置改动造成了消息结构的变化。

**Comment by yeehomlee** [comment]
@ssrpanel 
胖虎大佬，你发一个你用的Windows客户端呗。

**Comment by yeehomlee** [comment]
@fyglinfo  @cciecm   
你们两位问题解决了吗？

看下咱们几个面板有啥共同点呀，看问题出在哪，我折腾到现在还不行。

**Comment by cciecm** [comment]
@yeehomlee @fyglinfo 没有。小胖虎解决不了的就直接关单，这不是第一次了。

**Comment by yeehomlee** [comment]
我把面板还原到7月1日之前的备份，数据库没动，发现该问题解决。
但现在具体原因还没找到。
供你们参考。

**Comment by banxianl08** [comment]
有没有大佬解决这个问题了吗

**Comment by cciecm** [comment]
@banxianl08 没有。
