### ISSUE TITLE
搭建后的一些建议

### ISSUE THREAD

**Issue by ppllpig** [ssrpanel/ssrpanel#71]
1，商品管理界面上传图片报错,JPG和PNG都不行。
2，分组管理不是很方便，我有包月独享客户，单独一条线一个人，或者3人一条线，其他人要不可见，如何设置？
3，是否能考虑php自动发卡整合，省去人工时间。
4，能否增加404页面
5，限制设备数 能否增加

暂时就这几条建议了，希望胖虎采纳~~~机场上线，给胖虎发包包~~~YEAH

**Comment by ZBrettonYe** [comment]
第一条：我是通过ftp的方式传到服务器上，然后再数据库里直接修改套餐图片来解决报错问题的，我觉得这个应该和后台的文件权限有关
第五条： 这个好像已经在wiki里设为未来开发项目了吧

**Comment by ssrpanel** [comment]
@ppllpig 
1.提交错误截图，感觉应该是你没有设置好目录权限
2.单独一条线一个人，这个我不建议你用面板，直接拿个笔记软件记录，更不建议你把这个服务器添加到面板里，直接用json文件维护。
3.卡券里已经有批量导出，你可以批量生成后导出再手动添加到发卡平台，发卡平台有推荐的吗？代码是开源的，可以叫发卡平台的人来开发接入API。我合并到master里
4.404页面已经有了，把config/app.php 下的debug改为false报错就有404
5.限制设备数啊，这个需要第三方。包括限速我都还在研究呢，不用魔改那种方案。

**Comment by ppllpig** [comment]
@ssrpanel 是因为上传图片组件
https://ws1.sinaimg.cn/large/005HchDNgy1fl2xm20896j30w409jwep.jpg

**Comment by 1021435278** [comment]
胖虎,请问有考虑增加类似魔改那种审计和审计规则吗?

**Comment by ssrpanel** [comment]
@ppllpig 这TMD尴尬了，改了添加没改编辑。。。谢谢反馈

**Comment by ppllpig** [comment]
@ssrpanel 工具箱有啥用啊

**Comment by gaojianye** [comment]
@ssrpanel 是不是又忘了更新这个问题。。

**Comment by ssrpanel** [comment]
@ppllpig @gaojianye 代码更新了，拉一下，修正了编辑商品问题
工具箱里可以把原本用ss 通过json管理账号的批量把json转换成ssr 的格式，然后导入ssrpanel里
