### ISSUE TITLE
营销管理出现错误

### ISSUE THREAD

**Issue by ChokiJ** [ssrpanel/SSRPanel#711]
新安装的面板 后台营销管理中的无论是邮件群发还是消息推送均无法打开 提示
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ssrpanel.marketing' doesn't exist (SQL: select count(*) as aggregate from `marketing` where `type` = 1)
貌似是marketing表不见了

**Comment by Pinkpiglet** [comment]
邮件群发还在开发中啊 不能用

**Comment by ssrpanel** [comment]
为什么不看我更新了什么代码？update/sql下不是有吗？
