### ISSUE TITLE
希望每月清理节点产生流量功能

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/SSRPanel#713]
每月月底清理节点产生流量；

并记录每月最后的流量值；制作一个按照月份的流量图；

以此来记录节点的使用程度

**Comment by ssrpanel** [comment]
what？？？

**Comment by ZBrettonYe** [comment]
@ssrpanel 节点列表里的 产生流量选项不是一直累积的吗？

我希望这个只显示这个月的流量产生；

然后在流量图表里 除了今日，本月，再加个按照月份记录的

**Comment by yeehomlee** [comment]
其实，如果能加一个「清空流量统计」的按钮就足够了。

之前在数据库里，想找一下如何清空「节点列表」中的「产生流量」。
但没找到，胖虎大佬能告知一声吗？

**Comment by ZBrettonYe** [comment]
清理ss_node_traffic 之类的表就好了；

你讲的和我说的不是一个东西好不。 你只不过是不知道怎么搞数据库；
我想要的是数据的整理；看看什么线路比较受欢迎还有使用率这些方面的改进。
