### ISSUE TITLE
工单页面在用户按提交后要限制重复提交

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#716]
刚刚试了下，用户如果在工单界面上次一张图片，按多次提交工单话，服务器就会多次接收相同的数据并记录下来

**Comment by yeehomlee** [comment]
面板的前后顺序是先开始推送邮件，再返回操作结果。
大概是由于邮件服务器比较慢，所以才有机会给用户按多几次。
同样的情况还出现在：回复工单、关闭工单。

建议使用mailgun，可以基本解决。

**Comment by 828768** [comment]
@yeehomlee 话说，mailgun这事，从来没有成功过，各种配置都尝试没成功过，胖虎写的更简单，就改3行配置
