### ISSUE TITLE
今天用git pull更新完，直接500打不开首页了

### ISSUE THREAD

**Issue by fyglinfo** [ssrpanel/SSRPanel#717]
今天用git pull更新完，直接500打不开首页了
用这个chmod a+x update.sh && sh update.sh试过还原，重新上传了之前的database.php
php composer.phar install也试过，还是没有 500

**Comment by ssrpanel** [comment]
？？？什么错误？sql/update导入了吗？

**Comment by fyglinfo** [comment]
哦，没有导入，再去试试@ssrpanel
