### ISSUE TITLE
节点一直显示宕机

### ISSUE THREAD

**Issue by flonely** [ssrpanel/SSRPanel#718]
我节点服务器所有都设置好了，server.py执行也没有报错，也执行./run.sh，nodeid设置无误，时间cst，1G内存，但是面板一直显示宕机.....换了好几个服务器就是不行

**Comment by Chennhaoo** [comment]
用这个后端试试 https://github.com/ssrpanel/shadowsocksr

**Comment by ssrpanel** [comment]
面板里的定时任务？？

**Comment by flonely** [comment]
没事了
