### ISSUE TITLE
后端限制设备数时遇到的一个问题

### ISSUE THREAD

**Issue by Chennhaoo** [ssrpanel/SSRPanel#719]
原问题：https://github.com/ssrpanel/SSRPanel/issues/715#issuecomment-404368694
不好意思，再次打扰。我把上面检查了一遍，发现问题很玄乎。
DO VPS，debian9_X64，后端是你的改版ssr，[安卓客户端](https://github.com/shadowsocksrr/shadowsocksr-android/releases)最新版

服务器配置`user-config.json`
```
    "password": "m",
    "method": "aes-192-ctr",
    "protocol": "auth_aes128_md5",
    "protocol_param": "",
    "obfs": "plain",
    "obfs_param": "",
    "speed_limit_per_con": 0,
    "speed_limit_per_user": 300,
```
![default](https://user-images.githubusercontent.com/38855823/42692967-12426f9a-86e0-11e8-8d38-c5b22a1193d4.png)

服务器时间：和本地时间一样的
![default](https://user-images.githubusercontent.com/38855823/42693063-62c89bf6-86e0-11e8-94b8-ebf4e5746c3d.png)

客户端配置：
```
加密：aes-192-ctr
协议：auth_aes128_md5
混淆：plain
密码、端口都是没错的
```

问题描述：我想限制用户设备数，就设置了服务器  `"protocol_param": "2"` 参数，然后客户端就报错了，连不上，只要    `"protocol_param": ""`参数为空就没问题，链接也不报错，但是限速设置没问题，请问这是什么情况啊。

**Comment by MrPangzhan** [comment]
干嘛不试试 auth_chain_a ？

**Comment by Chennhaoo** [comment]
@MrPangzhan 试了的，后端还是报错

**Comment by Chennhaoo** [comment]
放弃了，不知出了什么未知问题，能限速基本上也能防止滥用了
