### ISSUE TITLE
审计规则 (正则) 参考魔改.

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#72]
胖虎,请问有考虑增加类似魔改那种审计和审计规则吗?

![123](https://user-images.githubusercontent.com/32491066/32284484-53c64e00-bf62-11e7-80c6-109df96dde0f.png)

**Comment by ssrpanel** [comment]
@1021435278 我还没弄懂它那个是怎么是实现的，貌似是魔改作者改了ssr后端的东西。。得用魔改的ssr

**Comment by 1021435278** [comment]
为什么你的微信无法打赏, 请PM我你的微信,我donate点点.
