### ISSUE TITLE
希望能添加一个数据库自动切换功能

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#721]
我的面板的数据库是分离的，服务器的数据库偶尔还是会挂的，我想，如果能设置两个不同ip的数据库话，那么就不会出现服务器突然报错的问题了。

**Comment by cmmdwl** [comment]
我在想能不能做一个自动切换的设置。。

**Comment by Mr-Kwok** [comment]
我也是有两个数据库，分别在两台设备上互相做备份，如果有一台数据库挂了，更改面板的配置到好说，可我15台SSR的后端数据库的IP改起来就麻烦了，后端能不能设置多数据库IP连接呢？

**Comment by yongjie0203** [comment]
节点端都是配置的域名，如果换数据库ip 只需修改dns解析就可以了

**Comment by Mr-Kwok** [comment]
> 节点端都是配置的域名，如果换数据库ip 只需修改dns解析就可以了

那也要每次都登录每台节点一台一台修改吧？就不能一个节点同时指向两个以上数据库IP地址吗？这样一个数据库挂了自动连接另一台数据库。

**Comment by yongjie0203** [comment]
只需修改域名解析呐
