### ISSUE TITLE
导出导入JSON报错

### ISSUE THREAD

**Issue by dayuezai123** [ssrpanel/SSRPanel#724]
在用户列表那里导出所所有用户json文件。 再从数据库里删除所有用户。 然后进后台工具， 数据导入  导入 json文件出错。。
![fireshot capture 14 - - http___ss ss123 xyz_admin_import](https://user-images.githubusercontent.com/38280021/42730546-88f79dd2-8829-11e8-8f2d-5ce55dba687f.png)

**Comment by ssrpanel** [comment]
你SSRPanel目录的权限有问题，宝塔装的吧？
