### ISSUE TITLE
建议添加一个新用户默认限速

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#728]
建议添加一个新用户默认限速
找了半天没有找到默认限速设置

**Comment by yeehomlee** [comment]
啥？
那个「用户限速」是有用的吗？

**Comment by Chennhaoo** [comment]
这个只有去后端设置

**Comment by Chennhaoo** [comment]
@2050545641 老哥能限制设备数吗？我老是失败https://github.com/ssrpanel/SSRPanel/issues/719

**Comment by Chennhaoo** [comment]
@2050545641 感谢老哥回复，我今天幽暗我以前的参数配置了一下，发现设备限制有点问题，最后决定懒得搞了，限速也能达到防止滥用的目的。

**Comment by ssrpanel** [comment]
@Chennhaoo 限速暂时只能用后端，配置好ssr。
