### ISSUE TITLE
套餐天数是否能改成不限制

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#729]
我想按月算套餐，结果商品内不允许按月算
于是我翻了下代码

SSRPanel-master\app\Http\Controllers\ShopController.php
       61行
     // 套餐有效天数必须大于90天
            if ($type == 2 && $days < 90) {    **//我想把这个90改改小一点 不知道会不会有问题**
                $request->session()->flash('errorMsg', '套餐有效天数必须不能少于90天');

                return Redirect::back()->withInput();
            }

**Comment by Chennhaoo** [comment]
月付可以用流量包嘛

**Comment by ssrpanel** [comment]
按月为什么不用流量包？
