### ISSUE TITLE
商品修正

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/ssrpanel#73]
问题/现象：1. 在账号过期后，SSR关闭。 重新购买服务，流量和时间 会增加 但是SSR不会自动开启

2. 商品的 [套餐] 不会重置流量，只会叠加； 情景：我机场 X元 50G 一个月， 买家再购买后，流量变成100G了，而我想的是总流量50G，重置流量；

**Comment by ssrpanel** [comment]
@ZBrettonYe 估计是BUG

**Comment by Hao-Luo** [comment]
确实是有这个问题，我暂时也没想到有什么好的解决办法。重置流量这个按照现在的数据库实现不了，肯定得改数据库结构,流量计算得计算流量包的过期时间，其实略显复杂了。

**Comment by 1021435278** [comment]
@Hao-Luo 请问有计划修改这个bug吗?

**Comment by ssrpanel** [comment]
@Hao-Luo 我已经加了两个表了，而且加了两个定时任务用于按天、按小时统计所有用户的所有节点流量，表分别是user_traffic_daily \ user_traffic_hourly，目前后端没有体现罢了，用于替换用户流量监控和30天内流量记录用，有这两个则账号到期自动重置流量就很简单了。

**Comment by ZBrettonYe** [comment]
能不能将套餐设为覆盖/重置 而不是叠加

**Comment by Hao-Luo** [comment]
我不是作者，胖虎才是作者。  如果能够做到到期自动扣除流量就太好了。 我本来的想象是流量从流量包里扣。每个人有默认流量包和会过期的流量包。 流量先从最早过期的流量包走这样。 这样需要一个人流量包的table，链接商品和账户。

**Comment by Hao-Luo** [comment]
我不会php.小改改还行 大改估计得先去学学php的基本语法架构之类的

**Comment by ssrpanel** [comment]
@Hao-Luo 已经实现了，定时任务一定要跑起来，定时任务里会自动执行，还有后台的那个自动重置流量要开启，每月1号自动重置流量

**Comment by Hao-Luo** [comment]
还是没懂是怎么实现的，如果每月1号重置流量的话，月中加入的人就不适用了。

**Comment by ZBrettonYe** [comment]
@Hao-Luo 我的想法是，按照模式来
按月/时间计费： 当流量达到上限→ SSR关闭; 当时间达到上限→SSR关闭;
按流量计费： 当流量达到上限 →SSR关闭；
SSR关闭，同时已用以及可用流量清零；
续费就是 添加可用流量，重置可用时间为（购买时间+套餐时间）；
检查 流量没有到上限/0→ SSR开启；（这一步检查续费后开启SSR）

**Comment by Hao-Luo** [comment]
我的想法是直接从套餐扣费， 有一个套餐的table, 然后只要有有效期，就从套餐走流量。超过有效期就从下一个套餐走流量。

**Comment by Hao-Luo** [comment]
不过估计SSR也要改就是了，现在好像是直接更新数据库的,得改成call SSPanel的api
