### ISSUE TITLE
推荐整合这个免签约接口

### ISSUE THREAD

**Issue by flonely** [ssrpanel/SSRPanel#730]
有赞云认证和支付太麻烦，一会微信一分钱，一会创建应用，而且只支持卡和支付宝，我客户很多都没有支付宝，但是这个接口认证和支付都很方便，支持微信，QQ，支付宝
http://www.hackwl.cn/
希望胖虎大佬考虑添加，谢谢！

**Comment by ssrpanel** [comment]
这种个人第三方支付很容易跑路的

**Comment by cmmdwl** [comment]
就这个？这个站源代码我都有

**Comment by ssrpanel** [comment]
@cmmdwl 发我一份？tg或者星球里私信都可以的

**Comment by cmmdwl** [comment]
你tg号？

**Comment by cmmdwl** [comment]
看了下开发文档，和我手上的源代码一摸一样，除了界面是不同的

**Comment by cmmdwl** [comment]
t.me/cmmdwl

**Comment by flonely** [comment]
emmm

**Comment by ssrpanel** [comment]
@cmmdwl 喊你了

**Comment by cmmdwl** [comment]
@ssrpanel 发你了
