### ISSUE TITLE
节点后端的加密协议都不一样，但是用户界面的加密协议都是用户默认的，这是BUG么？

### ISSUE THREAD

**Issue by Nightma7e** [ssrpanel/SSRPanel#732]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
节点后端加密：none，协议：auth_chain_a，混淆：tls1.2_ticket_auth
用户默认加密：ase-256-ctr，协议：auth_sha1_v4，混淆：tls1.2_ticket_auth
客户端订阅的和用户默认信息一致，而且还能用。。。

另外公告和文章可以放在订阅上面么，本来进的人就少，公告和文章放在右下角就更没人看了

**Comment by dovela** [comment]
是通过数据库转换的

**Comment by cmmdwl** [comment]
并不是，如果设置成数据库获取话那么节点无论如何设置都一样
