### ISSUE TITLE
建议：让「邀请码填写」可选。

### ISSUE THREAD

**Issue by LEE-Blog** [ssrpanel/SSRPanel#733]
由于现在「邀请码」已经成为邀请返利的重要一环，不太可能关闭。
同时，又希望让注册变的更加便利，比如在重要的推广期。

现在是通过后台「邀请注册」的开关，要么显示+必填，要么不显示+填不了。

因此，**建议注册页面的邀请码有三个状态选项：**
1、必须填写    2、可选填写    3、关闭

这样一来，可以满足「正常注册不需要邀请码」+「邀请返利时也可以输入邀请码」的需求。

因为我现在确实有这个环境需求，但自己试了一下改不出来。
即使在关闭邀请注册时，显示邀请码输入框，也会导致邀请失败。

以上，感谢。

**Comment by yeehomlee** [comment]
是的，就是这个意思。

1、必须填写：等同于 现在的开启「邀请注册」。
2、可选填写：填了邀请码返利，不填照样可以注册。
3、关闭：等同于 现在的关闭「邀请注册」。

**Comment by ssrpanel** [comment]
marked

**Comment by ZBrettonYe** [comment]
其实吧， 注册界面的 require属性 改一下就ok的

**Comment by ssrpanel** [comment]
已+
