### ISSUE TITLE
胖虎兄，你是不是错把 Google 分析的代码放到开发里了？

### ISSUE THREAD

**Issue by yeehomlee** [ssrpanel/SSRPanel#735]
![screen_20180717_143650](https://user-images.githubusercontent.com/20637016/42800536-f26618e2-89ce-11e8-9716-ab10f99abf80.png)

昨天的更新。

**Comment by ssrpanel** [comment]
没有，故意放的，我想看看有多少人在用我的开源程序，没办法追踪，这个谷歌分析工具页不好用，根本看不出个鸡毛

**Comment by ssrpanel** [comment]
看来更新到最新版的人很少

**Comment by ssrpanel** [comment]
有没有什么好的工具可以让我知道有多少人在我的开源程序，而且又可以正大光明的

**Comment by cmmdwl** [comment]
可能需要自己写，主要是获取一个服务器信息和服务器使用量，不过估计难搞。不妨试试网站统计代码？

**Comment by ssrpanel** [comment]
@cmmdwl 思路很好，赞
