### ISSUE TITLE
为毛PC端节点订阅不了了，安卓 IOS都可以

### ISSUE THREAD

**Issue by banxianl08** [ssrpanel/SSRPanel#736]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
PC端 ShadowsocksR-dotnet4.0  SSTap-beta 都订阅不了 今天早上还可以
都在同一个网络下安卓 IOS都可以，唯独PC不行  卸载重装都不行，哪里出问题了

**Comment by Dennishaha** [comment]
+1

**Comment by cmmdwl** [comment]
不妨验证下服务器是否被投毒了？

**Comment by ssrpanel** [comment]
1.更换一下本地dns
2.多更新几次
3.这个问题以前论证过一次，在closed issue 里搜 订阅 自己看看

**Comment by cciecm** [comment]
这么多人有这个问题，小胖虎还是一副你们这些渣渣自己的问题的态度。

**Comment by ssrpanel** [comment]
@ghost 关我屁事？
