### ISSUE TITLE
商品购买里希望能添加限制购买

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#738]
有些付费商品我不希望用户重复购买（比如月付某节点流量包）
而有些商品又要可以重复购买（比如xGB增量包）
并且用户的流量包过期了好像标签不会被删？（未验证）
本来想使用套餐
但是套餐是90day的
并且希望套餐添加互锁（比如买了a就不能买b）
不然有些套餐客户可以薅羊毛

**Comment by MrPangzhan** [comment]
并且用户的流量包过期了好像标签不会被删？（未验证）

我碰到这个问题，用户用完节点流量，标签是免费，后购买了VIP节点的标签。SSR状态启用了，但是标签是两个，免费的和VIP的节点标签，购买了VIP的节点，后台查看并没有删除已经使用完的免费节点的标签，这样的话标签会累加不会自动删除。希望大佬修复下，流量用完或者套餐到期自动删除标签。重新购买在加上购买的节点标签。

**Comment by ssrpanel** [comment]
已有了。
