### ISSUE TITLE
推广链接过于粗暴，建议加些随机数

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#739]
https://bes**sr.com/register?aff=1 像这样的链接很容易看出注册量，希望能改成一串代码
例如https://bes**sr.com/register?aff=usexc

**Comment by ssrpanel** [comment]
哈哈哈，我有想过这个，以后再改，目前可用即可。跟很多whmcs的aff返利一样的，其实不影响
