### ISSUE TITLE
git pull用户数据丢失解决了吗?

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#74]
关于网站升级，，站点git pull，，
数据库需要重新导入，，用户数据也就没有了。。
希望的是，数据库能跟着升级，原来的用户数据要在。。
或者说，，用户的各种信息能保留着升级

**Comment by 1021435278** [comment]
已赞 20 大洋, 如果你愿意接付费开发,请pm我.

**Comment by ssrpanel** [comment]
@1021435278 谢谢，现在有更新拉代码下来就要去看下sql/update/下的sql，该导入的导入
