### ISSUE TITLE
胖虎哥，标签去重没效果啊，还是会出现有重复标签出现的情况。

### ISSUE THREAD

**Issue by SheffieldLee** [ssrpanel/SSRPanel#740]
done---请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问---done

**Comment by SheffieldLee** [comment]
好像跟注册时，初始用户标签有关。

**Comment by ssrpanel** [comment]
更新完再试试？貌似是定时任务里的bug，我又修了一下

**Comment by SheffieldLee** [comment]
您等我今晚上更新了告诉您

**Comment by SheffieldLee** [comment]
标签还是重复出现了

**Comment by SheffieldLee** [comment]
手动给用户标签，然后用户在线购买该标签的节点，user_label 里该用户就会有两个相同的标签。

**Comment by ssrpanel** [comment]
@SheffieldLee 你是什么场景需要给用户手动上标签？

**Comment by SheffieldLee** [comment]
@ssrpanel 不是说手动，就是这样的情况：用户通过注册拥有了初始标签，然后他购买了拥有该标签的节点（在线支付），然后user_label里该用户就会有两个相同的标签。多次测试，此bug确实存在，5555555

**Comment by ssrpanel** [comment]
现在还有吗？今晚更新完应该不会有了，如果还有，你真的的看看你是不是设置了两个定时任务（crontab不用用户设定的定时任务互相看不到的）

**Comment by SheffieldLee** [comment]
@ssrpanel 已更新最新版，我确定只有www用户有面板的定时任务，root没有面板的定时任务，然后重复标签我手动删除过，明天测试一下，胖虎哥你等我测试好了给你反馈。

**Comment by SheffieldLee** [comment]
![tim 20180725183517](https://user-images.githubusercontent.com/33490770/43196172-b08b20d6-9039-11e8-817d-235af6180de1.png)
![tim 20180725183542](https://user-images.githubusercontent.com/33490770/43196177-b470c2c8-9039-11e8-8631-25b0454f1d44.png)
@ssrpanel 胖虎兄 还是没有效果，又出现重复标签了，这样该标签统计人数就会多一人，现在我是手动删除。。。

**Comment by ssrpanel** [comment]
修复了，合并了@SheffieldLee 的代码，现在越来越复杂了，所以遗漏较多。我很多功能其实开发出来并没有用过。所以。。。
