### ISSUE TITLE
BUG：删除用户指定节点标签后，还能使用这个节点

### ISSUE THREAD

**Issue by Chennhaoo** [ssrpanel/SSRPanel#741]
已更新到最新版前端，debian9X64，PHP7.1。
用户一共有3个标签，我删除了一个标签，然后设置SSR禁用，等到后端弹出关闭端口后，我又启用SSR。
用户标签里已没有那个节点标签，但是还是可以用，后端也弹出打开端口信息。

**Comment by yeehomlee** [comment]
目前来说，标签只能决定用户能不能看到节点配置。
如果他之前已经加到客户端了，就能继续使用，除非你更改节点配置。

这是个老问题，但解决成本比较高，不知道在不在胖虎兄的更新列表里。

**Comment by SheffieldLee** [comment]
是的  这是个大BUG 我之前提过

**Comment by Chennhaoo** [comment]
@SheffieldLee 老铁，最新版删除标签后能禁用了吗？我测试还是不行。

**Comment by SheffieldLee** [comment]
@Chennhaoo 肯定不行啊 ，这个要大改，胖虎兄 感觉胖虎兄不会做了

**Comment by Chennhaoo** [comment]
@SheffieldLee 魔改版我试了，改分组后也可以连原来的，不知道是不是也有同样问题。

**Comment by ssrpanel** [comment]
需要用mu api来操作后端。还没做
