### ISSUE TITLE
自定义LOGO的图片太小

### ISSUE THREAD

**Issue by GaHoKwan** [ssrpanel/SSRPanel#743]
站内的自定义LOGO和主界面LOGO都太小了，又小又扁，放进去一点都不好看

**Comment by yeehomlee** [comment]
<div class="logo">
<a href="#"> <img src="#" alt="#" style="height:auto;max-width:350px;"/></a>
</div>

**Comment by ssrpanel** [comment]
好像真实这样，沃日，我有空改改

**Comment by ssrpanel** [comment]
fixed
