### ISSUE TITLE
Windows/PC端 「SSR订阅地址」无法正常使用，请进来这里汇总一下：

### ISSUE THREAD

**Issue by yeehomlee** [ssrpanel/SSRPanel#744]
近期，发现很多人「SSR订阅地址」无法正常使用，手动更新时提示「更新失败」。
大部分是只有 Windows 客户端不行，Android/iOS/macOS 则正常。

但没有人给出解决方案，或者给出的解决方法都无效，完全找不到根本问题所在。
因此，我发这个自觉 Closed 的 Issuse 来汇总一下，看一下大家的环境及数量，便于我们自己确认问题。

**请按照以下格式填写并回复：**

> SSRPanel 版本 (或最近一次更新代码的日期) ：
订阅地址的链接协议 (http or https) ：
出现问题的平台系统 ( 比如 Windows7 64位 )：
出现问题的客户端 ( App全名+版本号 )：
出现问题的时间点 ( 从什么时候开始 )：

如果你也碰到这个问题，如果你也想解决，请按照要求回复。
谢谢合作。

**Comment by SRCOL** [comment]
SSRPanel版本：今(7月20)日更新
订阅地址的链接协议：https/http均无法订阅
出现问题的平台系统：Windows10
出现问题的客户端：SSTap-Beta-1.0.9.7+ShadowSocksR4.7（别的版本没试过）
出现问题的时间点：今日更新之后（6月份也出现过一次，更新后又可以了）

**Comment by cciecm** [comment]
@yeehomlee 你降级到了哪个commit？

**Comment by yeehomlee** [comment]
问题似乎解决，以我使用宝塔为例。
在网站设置中修改 Nginx 配置文件，添加「TLSv1」进去。

![screen_20180721_113514](https://user-images.githubusercontent.com/20637016/43031743-63520828-8cda-11e8-9dcd-e21613563f21.png)

**Comment by baiyou2014** [comment]
你好，我这样都弄好的，节点也分组了还是无法订阅
