### ISSUE TITLE
管理中心流量无法统计，流量日志却有流量记录

### ISSUE THREAD

**Issue by SuberuLine** [ssrpanel/SSRPanel#746]
一开始装的时候流量统计正常的，但是在之后更换vps后重新导入sql文件后就变得无法统计流量，但是流量日志一直有流量记录。个人中心的已用流量也是正常的

**Comment by Google688** [comment]
是的 这个问题我搭建了几个都是这样的问题。怎么回事呢 大神出面解决一下。。

**Comment by Google688** [comment]
以前老版本没有这样的问题

**Comment by Chennhaoo** [comment]
个人感觉哈，这个要等两天左右就有了

**Comment by SuberuLine** [comment]
不是。。我十几天前就有这个情况的，昨天才来git想请教下作者

**Comment by Chennhaoo** [comment]
我昨天git pull ，今天节点流量正常统计，请检查是否有日志文件生成。

**Comment by SuberuLine** [comment]
有日志文件生成，但是流量统计还是0b

**Comment by Chennhaoo** [comment]
@SuberuLine 检查服务端系统时间是否与本地时间及前端时间同步且都是CST

**Comment by SuberuLine** [comment]
date了下都是cst，应该不是系统时间的问题
