### ISSUE TITLE
讨论一个厉害的问题

### ISSUE THREAD

**Issue by senwzz** [ssrpanel/SSRPanel#748]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
怎么避免请去喝茶。。。

**Comment by MrPangzhan** [comment]
rm -rf *

**Comment by cmmdwl** [comment]
paypal要验证身份证 一样可能被喝茶

**Comment by yeehomlee** [comment]
别盈利。

**Comment by senwzz** [comment]
有没有什么 telegram 群可以聊天交流的？

**Comment by yeehomlee** [comment]
又一位想着发家致富又害怕喝茶的年轻人。

**Comment by senwzz** [comment]
这收益和风险平衡不了说实话，可能我卖的是假ssr。。。发家可能有点难

**Comment by senwzz** [comment]
paypal 要是能查到身份证了，基本你的数字比较大了吧，国内什么公司，ZF一个电话就能弄到

**Comment by ssrpanel** [comment]
又一位想着发家致富又害怕喝茶的年轻人。

**Comment by ssrpanel** [comment]
@senwzz 
1.又一位想着发家致富又害怕喝茶的年轻人。
2.群里月入2万的人好几个。别bb这些支付方式了
