### ISSUE TITLE
windows客户端无法订阅本人已解决

### ISSUE THREAD

**Issue by banxianl08** [ssrpanel/SSRPanel#749]
解决方法
最近很多人pc端上无法订阅，已确认不是ssrpanel问题，而是站点配置文件缺少ssl协议，把TLSv1添加进去就好，完整的应该是TLSV1 TLSV1.1 TLSV1.2。

**Comment by senwzz** [comment]
我订阅地址 用 http 可以订阅，https 不行

**Comment by yeehomlee** [comment]
![screen_20180721_113415](https://user-images.githubusercontent.com/20637016/43031725-07ebe896-8cda-11e8-8c32-b27e89552f40.png)

非常感谢，亲测有效。
试了几次，应该是问题所在了。

**Comment by yeehomlee** [comment]
![screen_20180721_113514](https://user-images.githubusercontent.com/20637016/43031734-2619745a-8cda-11e8-8055-16dc53fd206b.png)

非常感谢，亲测有效。
试了几次，应该是问题的关键所在了。

**Comment by ssrpanel** [comment]
tls1.0已经要被废弃了。

**Comment by ssrpanel** [comment]
所以有些人用的客户端是新编译的，废弃了tls1.0

**Comment by cciecm** [comment]
@ssrpanel 这时候你就懂了，啧啧啧

**Comment by ssrpanel** [comment]
@cciecm 我不懂，你厉害行了吧

**Comment by ssrpanel** [comment]
@cciecm 伸手党，你好

**Comment by cciecm** [comment]
@ssrpanel 我伸手很正常呀，你也伸手找我们要呀

ssrpanel commented 18 days ago
@cciecm 怎么解决的？我

 @ssrpanel
Owner
ssrpanel commented 18 days ago
bug个屁，根本不是bug，我拿小米和魅族都试过了，无论是http还是https都是一点毛病都没有，订阅地址是有区分大小写的

 @ssrpanel ssrpanel closed this 18 days ago
@cciecm
  
cciecm commented 18 days ago • 
这个问题我们在三台新装机器上可以复现。本来想告诉你哪里错了。但是你直接关case了，那就算了。

**Comment by ssrpanel** [comment]
@cciecm 你就等着别人做好东西给你用，是吧？我有义务为你解决一切问题吗？显然没有。我有从你身上得到一分好处吗？显然也没有。既然没有，那我愿意回答是我好心，我不愿意回答是我没有这个义务，每个人都有问题，难道非面板的问题我每个都要去验证一遍？叫你们手动装，你们非得宝塔宝塔。可怜

**Comment by cciecm** [comment]
@ssrpanel 你基本东西都做不好，提个问题关一个问题，屁都不会解决，还指望要钱啊？？

**Comment by ssrpanel** [comment]
@ghost你可以选择不用。你为什么要用？还要浪费时间来我这里跟我扯这些没用的？
