### ISSUE TITLE
商品修改问题

### ISSUE THREAD

**Issue by aiyahacke** [ssrpanel/ssrpanel#75]
新增完商品后编辑更换图片保存时报错

(2/2) QueryExceptionSQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'png' for column 'type' at row 1 (SQL: update `goods` set `name` = 100G流量月卡, `desc` = 100G流量月卡，每月1日清空流量！, `logo` = /upload/image/goods/201711022037421269.png, `traffic` = 102400, `price` = 20, `score` = 0, `type` = png, `days` = 30, `status` = 1, `updated_at` = 2017-11-02 20:37:42 where `id` = 2)
--

**Comment by aiyahacke** [comment]
已找到问题原因，ShopController中110行变量$type与post参数变量名重复，导致商品类型被赋值成图片扩展名

**Comment by ssrpanel** [comment]
@aiyahacke 这个请git pull 拉一下最新的代码，已经修正了啊
