### ISSUE TITLE
有没有人做过SSRPanel到魔改或WHMCS的迁移？胖虎bug搞不定只会关单 订阅 流量 标签 好多问题

### ISSUE THREAD

**Issue by cciecm** [ssrpanel/SSRPanel#751]
提过好多cases，小胖虎不会搞就直接关单。
早点脱离这个one-man project比较靠谱。

**Comment by Chennhaoo** [comment]
one-man都坚持了快1年了

**Comment by cciecm** [comment]
@Chennhaoo 他这样搞，适合高中生玩玩，不适合运营啊。

**Comment by Chennhaoo** [comment]
@cciecm 我两个都用，我还没开始商用，应为我的客户少，到时候实在不行我就手动录入。开源程序自己没有贡献的话，不太好催作者，你要是真的想商业化，可以微信捐助进群，然后找他定做，或者直接找魔改版作者定做，这是我的建议哈。

**Comment by ZBrettonYe** [comment]
胖虎大佬是开源的，你要是觉得不够商业化，为什么不自己开发 或者 找别人帮你开发？ 自己不开发，就别去怼开发者，毕竟别人要求你什么东西。
