### ISSUE TITLE
php composer.phar install出错，确定装了php7.1,确定装了fileinfo

### ISSUE THREAD

**Issue by fyglinfo** [ssrpanel/SSRPanel#754]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
 - Installing symfony/http-kernel (v3.3.5): Downloading (failed)    Failed to download symfony/http-kernel from dist: The "https://files.phpcomposer.com/files/symfony/http-kernel/16ceea64d23abddf58797a782ae96a5242282cd8.zip" file could not be downloaded (HTTP/1.1 405 Not Allowed)
    Now trying to download from source
  - Installing symfony/http-kernel (v3.3.5): Cloning 16ceea64d2
  - Installing symfony/finder (v3.3.5): Downloading (failed)    Failed to download symfony/finder from dist: The "https://files.phpcomposer.com/files/symfony/finder/baea7f66d30854ad32988c11a09d7ffd485810c4.zip" file could not be downloaded (HTTP/1.1 405 Not Allowed)
    Now trying to download from source
  - Installing symfony/finder (v3.3.5): Cloning baea7f66d3
哪有问题，看不懂啊

**Comment by Chennhaoo** [comment]
@fyglinfo 我的环境 debian9 X64  宝塔  PHP 7.1

**Comment by cmtomkan310** [comment]
今天凌晨出现了这个情况，但凡从新安装的执行php composer.phar install都会出问题，跟什么系统没关系。

**Comment by fyglinfo** [comment]
是这么个情况啊，哪这么处理呢

**Comment by 2050545641** [comment]
https://files.phpcomposer.com/files/symfony/finder/baea7f66d30854ad32988c11a09d7ffd485810c4.zip这个网站貌似都挂了啊，在浏览器上都访问不了了
![1](https://user-images.githubusercontent.com/30212669/43036007-6b40d5ae-8d2b-11e8-8b2f-fb34b85e5259.png)
@ssrpanel

**Comment by fyglinfo** [comment]
看来我不是第一个提问的

**Comment by 2050545641** [comment]
那个网站https挂了，但是http依然可以正常访问，但是不太清楚在哪里可以改，求教

**Comment by fyglinfo** [comment]
这不坑人吗

**Comment by ssrpanel** [comment]
@fyglinfo 是的，我也被坑了，composer的中国区镜像源挂了。

**Comment by ssrpanel** [comment]
各位把 composer.json 里面的这段 删除，再执行 php composer.phar install 即可（不使用composer的中国镜像源）
"repositories": {
        "packagist": {
            "type": "composer",
            "url": "https://packagist.phpcomposer.com"
        }
    }

**Comment by cmtomkan310** [comment]
@ssrpanel 还是不行，删除这段后提示

[Seld\JsonLint\ParsingException]                                  
  "./composer.json" does not contain valid JSON                     
  Parse error on line 63:                                           
  ...oader": true    },}                                            
  --------------------^                                             
  Expected: 'STRING' - It appears you have an extra trailing comma

**Comment by cmtomkan310** [comment]
括号弄错了，弄好后，还是跟之前一样报错！

**Comment by cmtomkan310** [comment]
修改后，问题依旧

**Comment by ssrpanel** [comment]
改回去，不删除的话，执行php composer.phar install 不行的话就执行 php composer.phar update
我试过了，大陆服务器都会出现这种错误，美国的不会。我也是纳闷了

**Comment by ssrpanel** [comment]
执行 php composer.phar update 就可以了。貌似是源更新之后那个唯一id变了导致的

**Comment by ssrpanel** [comment]
但是还是存在部分组件包无法下载的情况。我已经给phpcomposer作者发消息了

**Comment by ssrpanel** [comment]
@cmtomkan310 我这也是，尴尬了。。。

**Comment by fyglinfo** [comment]
两天了，还是不行

**Comment by ssrpanel** [comment]
今晚更新完，面板放国内的执行 php composer.phar install 的全部得卡死（因为我把那个responxxxx什么鬼的给删除了，不用国内的源了，国外都OK的，这个是我开发的坑，毕竟我开发的时候用国内源比较快）

**Comment by banxianl08** [comment]
你们都能用，我用国外的服务器执行php composer.phar install 出错，现在网站没法般了

**Comment by bigrain1993** [comment]
这个问题现在怎么样啦～被迫去用魔改了……

**Comment by ZBrettonYe** [comment]
/usr/bin/composer self-update  可以完美解决

**Comment by feizhai521** [comment]
@ZBrettonYe 大佬 你这个具体怎么操作啊

**Comment by ssrpanel** [comment]
@ZBrettonYe @feizhai521 php composer.phar self-update 这不是更新composer自身吗？

**Comment by ssrpanel** [comment]
@banxianl08 代码拉最新的，国外的应该是妥了

**Comment by feizhai521** [comment]
vultr拉最新代码还是不行

**Comment by Google688** [comment]
@ 各位哒哒 这是什么问题呀 
![qq 20180902014818](https://user-images.githubusercontent.com/38600824/44952608-0373c600-aeb6-11e8-9ad6-797c10bb7c29.png)
