### ISSUE TITLE
账号到期 不禁用了？？？？

### ISSUE THREAD

**Issue by SheffieldLee** [ssrpanel/SSRPanel#757]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问

**Comment by SheffieldLee** [comment]
不知道怎么的 账号到期 不会禁用用户ssr了

**Comment by cmmdwl** [comment]
过期自动封号
被禁用SSR(R)的用户在账号到期时同时封禁账号（账号将无法登录）
这个设置对了吗？

**Comment by SheffieldLee** [comment]
@cmmdwl 这个设置 我就没开 封账号不好，万一人家回头来购买呢

**Comment by ssrpanel** [comment]
今晚更新之后就不会了，应该是修复了

**Comment by SheffieldLee** [comment]
@ssrpanel 辛苦了，虎哥，已更新，一会告诉你修复了没

**Comment by SheffieldLee** [comment]
@ssrpanel 胖虎哥，有BUG，用户到期后，标签清除了，但是SSR并没有禁用。

**Comment by MrPangzhan** [comment]
![qwe](https://user-images.githubusercontent.com/39323056/43176618-0eaf8546-8ff7-11e8-82cf-04304db39ea9.png)
用户过期SSR没有禁用。
昨天更新后还是存在Bug，计划任务正常。

**Comment by SheffieldLee** [comment]
@ssrpanel 胖虎兄

**Comment by fyglinfo** [comment]
已经@ssrpanel了，一天刷了20多万条数据在后台了

**Comment by ssrpanel** [comment]
应该可以了！@fyglinfo 更新一下代码

**Comment by ssrpanel** [comment]
早上群友已经测了一波了，一天都很稳
