### ISSUE TITLE
建议添加首页公告轮播功能

### ISSUE THREAD

**Issue by bigrain1993** [ssrpanel/SSRPanel#758]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
建议在首页能够增加公告轮播，方便通告优惠信息和其他事宜

**Comment by yeehomlee** [comment]
@Wordpress

**Comment by ssrpanel** [comment]
建议你搭建一套WORDPRESS作为主站入口，挂个二级域名进面板。
