### ISSUE TITLE
网站使用cdn加速时注册IP获取不正确

### ISSUE THREAD

**Issue by 2050545641** [ssrpanel/SSRPanel#759]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
我网站用了CloudFlare的cdn，然后发现用户注册ip全都变成CloudFlare的cdn节点的ip了，胖虎看看能不能修复一下。
![1](https://user-images.githubusercontent.com/30212669/43118653-6276ace8-8f45-11e8-8671-623d48609fad.png)
![2](https://user-images.githubusercontent.com/30212669/43118677-7dd7eb28-8f45-11e8-8470-4403159caacc.png)
![3](https://user-images.githubusercontent.com/30212669/43118678-7e04a5dc-8f45-11e8-958a-96775b544dcf.png)

**Comment by cmmdwl** [comment]
是的，你不说我还真的没发现这个问题，刚刚查了下ip，还真的全是美国加州三藩CloudFlare公司AS13335任播网络CDN全球节点 目前我的策略是不限制注册量 后台查询密码是否相同来证明是否是同一个用户

**Comment by ssrpanel** [comment]
那个，，，我没套过CF 的CDN，真心不清楚。

**Comment by ssrpanel** [comment]
等我有空研究下，还有节点如果是用域名的别套CDN，套了CDN，速度会变慢，甚至不可用（被墙IP的时候可以套），还有一点很重要，移动封了所有CF，套了CF，移动全部GG

**Comment by 2050545641** [comment]
节点肯定不会用cdn，只有面板套了。而且，我周围用移动的貌似没有说被封的啊qwq？

**Comment by cmmdwl** [comment]
function GetClientIP(){
 
 $ip = $_SERVER["HTTP_X_FORWARDED_FOR"];
 
 if($ip != ""){
 
  $arr = explode(",",$ip);
 
  return $arr[0];
 
 }else{
 
  return $_SERVER["REMOTE_ADDR"];
 
 }
 
}
 
echo "您的上网IP是：".GetClientIP();

**Comment by cmmdwl** [comment]
这个获得的用户ip就是真实的了

**Comment by ssrpanel** [comment]
@cmmdwl 不科学啊，我获取IP的方法比这个还牛逼（框架自带），我要是取不到，这个也应该取不到的

**Comment by cmmdwl** [comment]
会不会是框架没考虑cdn？@ssrpanel

**Comment by ssrpanel** [comment]
不清楚，我不套cdn的

**Comment by kkkway** [comment]
https://blog.digac.cc/2017/10/20/fix_sspanel_realip/  参考这个

**Comment by cmmdwl** [comment]
我研究了一下 cf在wordpress 里有个插件 本来套上cdn wordpress也是获取到了cdn的ip 结果 加插件后就变成真实ip了。。

**Comment by supermycode** [comment]
.env 最后加上这个 

if ( isset($_SERVER["HTTP_X_FORWARDED_FOR"]) ) {
$list = explode("," , $_SERVER["HTTP_X_FORWARDED_FOR"]);
$_SERVER["REMOTE_ADDR"] = $list[0];
}

就可以获取到用户的真实ip了。
当然，在nginx里获取也是可以的。

**Comment by cmmdwl** [comment]
@supermycode  好像这样的也不对
 Fatal error: Uncaught Error: Class 'Config' not found in /www/wwwroot/bm/app/Exceptions/Handler.php:49 Stack trace: #0 /www/wwwroot/bm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(326): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Dotenv\Exception\InvalidFileException)) #1 /www/wwwroot/bm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(120): Illuminate\Foundation\Http\Kernel->renderException(Object(Illuminate\Http\Request), Object(Dotenv\Exception\InvalidFileException)) #2 /www/wwwroot/bm/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request)) #3 {main} thrown in /www/wwwroot/bm/app/Exceptions/Handler.php on line 49

**Comment by cmmdwl** [comment]
这次有更新有关cdn的ip问题

**Comment by ssrpanel** [comment]
已修复了，请不要自行更改代码。可以拉取最新代码了
