### ISSUE TITLE
用户为什么无法删除

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#76]
请问该如何解决?

另外请问git pull更新后, 数据库升级
ttps://github.com/ssrpanel/ssrpanel/tree/master/sql/update里面的升级指令，打开phpMyAdmin，在ssrpanel数据库里面用SQL命令执行进行升级。以/sql/update/20171102.sql为例，在浏览器输入网址https://github.com/ssrpanel/ssrpanel/blob/master/sql/update/20171102.sql打开这个文件，将指令复制。随后打开宝塔面板数据库ssrpanel的phpMyAdmin管理，在SQL区域黏贴指令，点Go运行出错,请问什么原因?

![aaa](https://user-images.githubusercontent.com/32491066/32343280-e785a498-c03d-11e7-8aa3-c7509202c4a2.png)

**Comment by 1021435278** [comment]
我看了下,应该是git pull更新时候,连sql一起也更新了.

另外用户无法删除怎么解决?  总不能老是去数据库删除啊.

**Comment by Hao-Luo** [comment]
之前我问过这个问题，胖虎说删除用户会导致有Bug,建议禁用用户的ssr

**Comment by 1021435278** [comment]
@Hao-Luo  那请问数据库中删除掉用户会有问题吗?

**Comment by ssrpanel** [comment]
禁用就行，不建议删除，为什么要删除，一旦删除会导致流量统计大量错误
