### ISSUE TITLE
希望增加商品排序功能

### ISSUE THREAD

**Issue by 2050545641** [ssrpanel/SSRPanel#760]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
如题，比如我一开始创建了10 30 50 100G这几种流量包，然后过几天又想加一个80G的，但是加完的80G的会排在100G的后面，而且又不敢直接改数据库里的ID，怕影响交易记录和返利之类的。

**Comment by ssrpanel** [comment]
。====

**Comment by ssrpanel** [comment]
加了，等提代码
