### ISSUE TITLE
git pull后代码错误

### ISSUE THREAD

**Issue by garhing** [ssrpanel/SSRPanel#761]
# php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize

In mail.php line 32:
                                                                    
  Parse error: syntax error, unexpected '<<' (T_SL), expecting ']'  
                                                                    

Script php artisan optimize handling the post-install-cmd event returned with error code 1

**Comment by ssrpanel** [comment]
看这个 https://github.com/ssrpanel/SSRPanel/issues/762
