### ISSUE TITLE
我把这次升级的坑写了下

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#762]
https://cmmdwl.com/index.php/ssrpanel-update/88/uncategorized/admin/
直接贴链接把

**Comment by MrPangzhan** [comment]
一行一个。
sh update.sh
sh update.sh
cp .env.example .env
vi .env  # 更改数据库地址、SMTP
php artisan key:generate

**Comment by garhing** [comment]
我的救星！！！

**Comment by garhing** [comment]
邮件投递Undefined index: host

**Comment by ssrpanel** [comment]
本次更新用的是 https://ipcheck.need.sh 的检测服务，如果频繁收到 server酱的提醒信息，可以先进 /app/Console/Commands/AutoJob.php 在第 330 行处往下 添加一行：return 0;    即可

**Comment by ssrpanel** [comment]
明天我再加个开关让大家可以关闭这个检测

**Comment by ssrpanel** [comment]
在更新一下，我关闭了TCP阻断检测了

**Comment by qq40122698** [comment]
[Illuminate\Database\QueryException]                                         
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ssrpanel.config'  
   doesn't exist (SQL: select * from `config`)                                 
                                                                               

                                                                               
  [PDOException]                                                               
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ssrpanel.config'  
   doesn't exist                                                               
                                                                               

Script php artisan optimize handling the post-install-cmd event returned with error code 1
请问出现这个怎么解决？

**Comment by ssrpanel** [comment]
@qq40122698 这是哪里出现的

**Comment by qq40122698** [comment]
已经解决了

**Comment by thank243** [comment]
这次大升级，小弟已经rm了后重新安装了次。

**Comment by ssrpanel** [comment]
强制更新！！！

**Comment by ssrpanel** [comment]
@thank243 不好意思，我没想过这么多人更新，然后把第三方搞炸了，搞得我发现一堆bug

**Comment by cmmdwl** [comment]
@强制更新！！！
是什么鬼？  @ssrpanel

**Comment by ssrpanel** [comment]
刚才更新了代码，sh update.sh 一下，强制更新代码到最新。问题都处理掉了

**Comment by cmmdwl** [comment]
http://cmmdwl.com/index.php/how-to-update-ssrpanel/103/uncategorized/admin/
@ssrpanel  已经写了一下了，这次没出现什么大bug 有兴趣话就把这个链接放到wiki里面去把

**Comment by bigrain1993** [comment]
请问.evn文件在什么路径下啊～找不到

**Comment by huaxin820518** [comment]
> 请问.evn文件在什么路径下啊～找不到
在目录下 ls -al 就能找到.env.example，.开头的文件默认是隐藏的。
