### ISSUE TITLE
.env 缺少两个邮件参数

### ISSUE THREAD

**Issue by MrPangzhan** [ssrpanel/SSRPanel#763]
配置AWS-SES SMTP 邮件发送失败，查看mail.php发现 .env缺少下面两个参数
MAIL_FROM_ADDRESS=  # 主要缺少这个
MAIL_FROM_NAME=

**Comment by SheffieldLee** [comment]
正解，直接在mail.php里把缺省值换成自己的就行了。

**Comment by xiaoanweiwu** [comment]
我也发送失败

**Comment by cmmdwl** [comment]
这两个可以不要 我贴下我的配置

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=465
MAIL_USERNAME=bes****.com@gmail.com
MAIL_PASSWORD=zxc****99
MAIL_ENCRYPTION=ssl

**Comment by ssrpanel** [comment]
我改进一下

**Comment by cmtomkan310** [comment]
密码找回邮件正常发，但是点击链接后网页无法访问？这个问题是？

**Comment by ssrpanel** [comment]
已经加上，等待提代码
