### ISSUE TITLE
网站转移后在线支付回调问题

### ISSUE THREAD

**Issue by banxianl08** [ssrpanel/SSRPanel#765]
777权限都给了，自动定时任务也开启了，也可以创建订单，支付成功后，收不到货，日志就显示，
[2018-07-26 16:01:30] local.INFO: YZY-GET:[113.200.205.77]  ，网站没有有赞回调没有记录。这是什么问题
完整的如下
[2018-07-26 16:00:01] local.INFO: 执行定时任务【自动化任务】，耗时0.1987秒  
[2018-07-26 16:00:02] local.INFO: 执行定时任务【自动清除日志】，耗时0.0717秒  
[2018-07-26 16:00:02] local.INFO: 执行定时任务【自动扣减用户到期流量包的流量】，耗时0.0052秒  
[2018-07-26 16:00:02] local.INFO: 执行定时任务【自动重置用户可用流量】，耗时0.0451秒  
[2018-07-26 16:00:02] local.INFO: 执行定时任务【自动统计节点每小时流量】，耗时0.1187秒  
[2018-07-26 16:00:04] local.INFO: 执行定时任务【自动统计用户每小时流量】，耗时1.3647秒  
[2018-07-26 16:00:04] local.INFO: 执行定时任务【用户流量异常警告】，耗时0.0903秒  
[2018-07-26 16:01:01] local.INFO: 执行定时任务【自动化任务】，耗时0.3112秒  
[2018-07-26 16:01:30] local.INFO: YZY-GET:[113.200.205.77]  
[2018-07-26 16:02:02] local.INFO: 执行定时任务【自动化任务】，耗时0.2093秒  
[2018-07-26 16:03:01] local.INFO: 执行定时任务【自动化任务】，耗时0.2163秒  
[2018-07-26 16:04:02] local.INFO: 执行定时任务【自动化任务】，耗时0.2085秒  
[2018-07-26 16:05:01] local.INFO: 执行定时任务【自动化任务】，耗时0.2082秒  
[2018-07-26 16:05:02] local.INFO: 执行定时任务【自动重置用户可用流量】，耗时0.0488秒  
[2018-07-26 16:06:01] local.INFO: 执行定时任务【自动化任务】，耗时0.212秒

**Comment by ZBrettonYe** [comment]
你要去有赞那里改 回馈的地址

**Comment by banxianl08** [comment]
有赞日志这算不算正常
TRY THREE TIMES RE PUSH FAILED ERROR: java.net.ConnectException: Connection refused TYPE: TRADE ID: E20180726200826048700011 URL: https://vpn.52ssr.cc/api/yzy MSG: {"msg":"%7B%22trade%22:%7B%22consign_time%22:%22%22,%22buyer_area%22:%22%22,%22original_post_fee%22:%220.00%22,%22num%22:1,%22adjust_fee%22:%7B%22pay_change%22:%220.00%22,%22change%22:%220.00%22,%22post_change%22:%220.00%22%7D,%22relation_type%22:%22%22,%22type%22:%22QRCODE%22,%22order_mark%22:%22%22,%22tid%22:%22E20180726200826048700011%22,%22send_num%22:0,%22feedback%22:0,%22delivery_start_time%22:0,%22outer_user_id%22:%222088602224627670%22,%22qr_id%22:%227569368%22,%22price%22:%220.10%22,%22button_list%22:[%7B%22tool_parameter%22:%22%7B%7D%22,%22tool_type%22:%22goto_native:trade_change_price%22,%22create_time%22:%22%22,%22tool_value%22:%22%22,%22tool_title%22:%22%E6%94%B9%E4%BB%B7%22,%22new_sign%22:%220%22,%22tool_icon%22:%22https://img.yzcdn.cn/upload_files/2015/08/28/Ftodf5cdSlo-vaH1Jty4GylCJLr5.png%22%7D,%7B%22tool_parameter%22:%22%22,%22tool_type%22:%22goto_native:trade_close%22,%22create_time%22:%22%22,%22tool_value%22:%22%22,%22tool_title%22:%22%E5%85%B3%E9%97%AD%22,%22new_sign%22:%22%22,%22tool_icon%22:%22https://img.yzcdn.cn/upload_files/2015/08/28/Flv3HyyRB2DGyXsPwRqnZvA4pHla.png%22%7D,%7B%22tool_parameter%22:%22%7B%7D%22,%22tool_type%22:%22goto_native:trade_memo%22,%22create_time%22:%22%22,%22tool_value%22:%22%22,%22tool_title%22:%22%E5%A4%87%E6%B3%A8%22,%22new_sign%22:%220%22,%22tool_icon%22:%22https://img.yzcdn.cn/upload_files/2015/08/28/FpO1UIXyOEZO026tWIgUOm9uZnT2.png%22%7D],%22total_fee%22:%220.10%22,%22payment%22:%220.10%22,%22order_type%22:%226%22,%22is_tuan_head%22:0,%22lat%22:%22%22,%22sub_trades%22:[],%22delivery_time_display%22:%22%22,%22buyer_message%22:%22%22,%22delivery_end_time%22:0,%22lng%22:%22%22,%22created%22:%222018-07-26%2020:08:26%22,%22kind%22:1,%22delivery_list%22:[],%22is_retail_offline%22:false,%22offline_id%22:%220%22,%22goods_kind%22:1,%22status_str%22:%22%E5%BE%85%E4%BB%98%E6%AC%BE%22,%22close_time%22:%22%22,%22pay_time%22:%22%22,%22group_no%22:%22%22,%22shop_id%22:%220%22,%22out_trade_no%22:[],%22points_price%22:0,%22tuan_no%22:%22%22,%22orders%22:[%7B%22is_virtual%22:0,%22outer_item_id%22:%22%22,%22pic_thumb_path%22:%22https://img.yzcdn.cn/public_files/2016/12/29/33e6c838cefa614c5121c63c80f860e9.png%3FimageView2/2/w/200/h/0/q/75/format/png%22,%22item_type%22:30,%22num%22:%221%22,%22refunded_fee%22:%220.00%22,%22oid%22:18404576,%22title%22:%22%E6%B5%8B%E8%AF%95%E5%8B%BF%E4%B9%B0%22,%22fenxiao_payment%22:%220.00%22,%22discount_fee%22:%220.00%22,%22new_oid_str%22:%221462376703152624529%22,%22buyer_messages%22:[],%22is_present%22:0,%22price%22:%220.10%22,%22fenxiao_price%22:%220.00%22,%22total_fee%22:%220.10%22,%22payment%22:%220.10%22,%22outer_sku_id%22:%22%22,%22sku_unique_code%22:%22%22,%22is_send%22:0,%22item_id%22:%222147483647%22,%22sku_id%22:%220%22,%22sku_properties_name%22:%22%22,%22pic_path%22:%22https://img.yzcdn.cn/public_files/2016/12/29/33e6c838cefa614c5121c63c80f860e9.png%22,%22new_oid%22:1462376703152624529,%22item_refund_state%22:%22NO_REFUND%22,%22refund_id%22:%22%22,%22state_str%22:%22%E5%BE%85%E4%BB%98%E6%AC%BE%22,%22unit%22:%22%E4%BB%B6%22,%22order_promotion_details%22:[],%22allow_send%22:0,%22seller_nick%22:%2252ssr%22%7D],%22promotion_details%22:[],%22id_card_number%22:%22%22,%22refund_state%22:%22NO_REFUND%22,%22status%22:%22WAIT_BUYER_PAY%22,%22post_fee%22:%220.00%22,%22pic_thumb_path%22:%22https://img.yzcdn.cn/public_files/2016/12/29/33e6c838cefa614c5121c63c80f860e9.png%3FimageView2/2/w/200/h/0/q/75/format/png%22,%22invoice_title%22:%22%22,%22receiver_city%22:%22%22,%22shipping_type%22:%22express%22,%22refunded_fee%22:%220.00%22,%22title%22:%22%E6%B5%8B%E8%AF%95%E5%8B%BF%E4%B9%B0%22,%22discount_fee%22:%220.00%22,%22buy_way_str%22:%22%22,%22hotel_info%22:%22%22,%22pf_buy_way_str%22:%22%22,%22receiver_state%22:%22%22,%22update_time%22:%222018-07-26%2020:08:27%22,%22coupon_details%22:[],%22receiver_zip%22:%22%22,%22receiver_name%22:%22%22,%22pay_type%22:%22%22,%22fans_info%22:%7B%22fans_type%22:736,%22fans_weixin_openid%22:%22%22,%22buyer_id%22:820431335,%22fans_nickname%22:%22alipay_2088602224627670%22,%22fans_id%22:5516965292%7D,%22delivery_third_party_supported%22:false,%22transaction_tid%22:%22%22,%22item_id%22:%222147483647%22,%22phase_payments%22:%7B%22is_presale%22:false,%22state%22:%22%22,%22phases%22:[]%7D,%22receiver_district%22:%22%22,%22box_price%22:%220.00%22,%22pic_path%22:%22https://img.yzcdn.cn/public_files/2016/12/29/33e6c838cefa614c5121c63c80f860e9.png%22,%22feedback_num%22:0,%22receiver_mobile%22:%22%22,%22confirm_time%22:%22%22,%22sign_time%22:%22%22,%22seller_flag%22:0,%22service_phone%22:%22%22,%22is_retail_free_buy%22:false,%22shop_type%22:%221%22,%22order_source%22:%7B%22platform%22:%22ALIPAY%22%7D,%22receiver_address%22:%22%E9%9D%A2%E5%AF%B9%E9%9D%A2%E6%89%AB%E7%A0%81%E6%94%B6%E6%AC%BE%22,%22trade_memo%22:%22%22,%22relations%22:[],%22outer_tid%22:%22%22%7D%7D","kdt_name":"52ssr","test":false,"sign":"253277f45bf3988fded1e23fb0750a23","sendCount":3,"type":"TRADE","version":1532606907,"client_id":"a49829de4f0bb08bbf","mode":1,"kdt_id":40631944,"id":"E20180726200826048700011","status":"WAIT_BUYER_PAY"}

**Comment by banxianl08** [comment]
有赞后台显示健康啊，为什么不行啊

**Comment by banxianl08** [comment]
@ZBrettonYe  地址改是改了，域名昨天解析到这台服务器上的，难道有赞的dns还没刷新吗

**Comment by banxianl08** [comment]
解决了 ，是.cc域名的问题我从注册了一个域名 就可以了  我关闭帖子了
