### ISSUE TITLE
关于“待付款”过期不关闭的问题！

### ISSUE THREAD

**Issue by cmtomkan310** [ssrpanel/SSRPanel#767]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问

首先，网站是重新部署的git，数据库用的是老的，但也更新了。目前运行一切正常，但有个问题，就是之前几次待支付的订单，不能自动取消了，一直就在哪里显示着，造成如果购买同类型套餐，就会提示有未完成的订单。

**Comment by cmtomkan310** [comment]
补充：在线支付不受这个这个限制，有赞不行！

**Comment by cmtomkan310** [comment]
![12](https://user-images.githubusercontent.com/38905231/43264951-05eed460-911a-11e8-8aa4-1a0f5576ef14.jpg)

**Comment by cmtomkan310** [comment]
没人有这个问题吗？之前好好的。。。

**Comment by ssrpanel** [comment]
权限？

**Comment by cmtomkan310** [comment]
![image](https://user-images.githubusercontent.com/38905231/43329661-9f974df2-91f3-11e8-94da-b3fdd2cef3fd.png)

**Comment by cmtomkan310** [comment]
@ssrpanel 权限应该没有问题啊！有问题创建订单的时候就有问题了，对吧？

**Comment by cmmdwl** [comment]
进数据库改把
改成-1就行了
怕的是新的也出这样的错误

**Comment by ssrpanel** [comment]
我看看

**Comment by ZBrettonYe** [comment]
再添加一个关闭按钮 就完美解决这个问题了，按钮“ 未支付 支付” 改成“ 支付 关闭”

**Comment by cmmdwl** [comment]
你的定时任务添加过没？我遇到过这个问题，添加一下定时就行了。不过不保证你也可以使用

**Comment by Bennett561** [comment]
同意，改成关闭按钮

**Comment by banxianl08** [comment]
直接把那两个订单在数据库里删了就行了

**Comment by cmtomkan310** [comment]
@cmmdwl 定时任务当然增加了，我说了，后面的订单没有问题，有问题的是之前的订单，我的问题描述的很清楚了。。。

**Comment by cmtomkan310** [comment]
@banxianl08 我知道的是我自己的这两个订单出现这个问题，其他的还有很多，我逐个删除，或者逐个改成-1。。。以后其他人也会遇到类似的问题，同样方法解决吗？？？

**Comment by ssrpanel** [comment]
再添加一个关闭按钮 就完美解决这个问题了，按钮“ 未支付 支付” 改成“ 支付 关闭”

你这种是典型的程序员思维，。。。为什么要给用户关闭？

**Comment by ssrpanel** [comment]
无法重现。
