### ISSUE TITLE
重大BUG，封禁SSR代码是不是哪儿错了

### ISSUE THREAD

**Issue by SheffieldLee** [ssrpanel/SSRPanel#768]
自动封禁变成了自动解封了？？？所有过期被封禁的账号全部被解封了。。。最新版本。

**Comment by bdddcw** [comment]
我也发现好像是这样的，我还以为是我动过文件，原来都一样

**Comment by SheffieldLee** [comment]
解决了！ 看了一下源码，ban_time 这里应该是-1啊，胖虎兄，commit一下code吧

vim /home/wwwroot/ssrpanel/app/Console/Commands/AutoJob.php

着急的人可以自己先修改了

![tim 20180727014932](https://user-images.githubusercontent.com/33490770/43279113-a560cc04-913f-11e8-9577-f1039531aba9.png)

**Comment by SheffieldLee** [comment]
@bdddcw 看楼上

**Comment by SheffieldLee** [comment]
第一行里查找条件我觉得应该是where(‘enable’, 1)，如果是以status为查询条件的话，像我根本不封禁账户，只封禁SSR，这样会一直查找插入，增加机器开销啊……

**Comment by SheffieldLee** [comment]
就像下面一样，改为->where('enable', 1)后，用户封禁log就不会一直重复写了。
昨晚2点多，我改成>where('enable', 1)了，就不会每分钟写个log了

![tim 20180727083345](https://user-images.githubusercontent.com/33490770/43295515-fd42b0b2-9177-11e8-8218-e60f06168cf2.png)


![tim 20180727083135](https://user-images.githubusercontent.com/33490770/43295513-f9290bac-9177-11e8-9f06-657462e6b64d.png)

**Comment by cmtomkan310** [comment]
已经跑了100多万的数据记录了，建议老大后面更新的时候做清零处理！
![image](https://user-images.githubusercontent.com/38905231/43297227-a1b80d68-9182-11e8-9ba8-61315a5007a1.png)

**Comment by SheffieldLee** [comment]
日志本身会自动清除，不用管

**Comment by cmtomkan310** [comment]
大哥我说的是数据库user_ban_log这个表里面的数据，这个表是不会自动清除的吧。。。。

**Comment by cmtomkan310** [comment]
经过测试，按照你修改的，的确不写日志了，但是订单管理，有赞支付也不写了，所以还是等老大修改吧！

**Comment by SheffieldLee** [comment]
有赞和这个文件根本没关系吧

**Comment by SheffieldLee** [comment]
@cmtomkan310 这个表会自动清除的，不用管

![1](https://user-images.githubusercontent.com/33490770/43299809-8110186a-918e-11e8-8d38-bcadc109b1ed.png)

**Comment by SheffieldLee** [comment]
我觉得，账户过期封禁后，应删除流量重置日期。胖虎兄你觉得呢。

![tim 20180727112010](https://user-images.githubusercontent.com/33490770/43299976-4d8e9f74-918f-11e8-9455-95977e845562.png)

**Comment by Losgif** [comment]
封禁是没有问题的
问题出在了解封函数里
在可用流量大于已用流量逻辑处理的时候
没有判断账号是否过期

**Comment by Losgif** [comment]
你改成-1
用户如果加了流量就不会自动解封
因为
![image](https://user-images.githubusercontent.com/13404752/43303683-6676b472-91a3-11e8-8f4c-fe48220cbe1f.png)
明白了吗？
只要这里where加一句判断是否账户过期就ok
不然自动封禁、自动解封
无限循环

**Comment by SheffieldLee** [comment]
@Losgif 不是我改成-1，原来他原来代码里就是-1，我针对你说的情况做了测试。有流量会自动解封。

原账号已过期，剩余256MB流量。
![tim 20180727134940](https://user-images.githubusercontent.com/33490770/43303848-3edcbc1c-91a4-11e8-9891-9d35c866b00a.png)

购买test商品，1天有效期，256MB流量
![tim 20180727135059](https://user-images.githubusercontent.com/33490770/43303878-59806fdc-91a4-11e8-80c1-16fc08fbe220.png)

解封了，账号有效期到明天，账号正常。
![tim 20180727135043](https://user-images.githubusercontent.com/33490770/43303900-7133a40a-91a4-11e8-9158-1137090201fa.png)

**Comment by SheffieldLee** [comment]
@Losgif 
![tim 20180727141205](https://user-images.githubusercontent.com/33490770/43304520-141409ba-91a7-11e8-907d-f11d964cf0ea.png)

ban_time 就两种状态 -1 和 0

enable=1，ban_time=0   → 账户正常
enable=0，ban_time=-1  →账户ssr被封禁（账户过期）
enable=0，ban_time=0   →账户ssr被封禁（账户流量超限）

所以，有流量解封where('ban_time', 0)是对的，没问题，这是解封流量超限的用户的。

我做的测试是在商品逻辑里，购买了商品增加了账户有效期解封，解封账户过期用户，也是对的。

所以，你提出的
“封禁是没有问题的
问题出在了解封函数里
在可用流量大于已用流量逻辑处理的时候
没有判断账号是否过期”

是错误言论。

**Comment by Losgif** [comment]
你试试把用户ban_time字段改为-1

再好好看看解封账户的逻辑

**Comment by SheffieldLee** [comment]
用户过期后ban_time字段就为-1啊，有什么问题吗，解封账户逻辑我很清楚。在你楼上我已经说得很清除了。实在不明白就算了。

**Comment by ssrpanel** [comment]
强制更新了，再试试

**Comment by ssrpanel** [comment]
ban_time = -1 不用了，我自己都云了

**Comment by SheffieldLee** [comment]
@ssrpanel 辛苦了胖虎兄，问题解决了，标签重复的问题好像也解决了，再测试几天。这个可以close了

**Comment by SheffieldLee** [comment]
@Losgif sorry，你是对的，对不起
