### ISSUE TITLE
新BUG，订单管理不显示有赞支付成功的订单！

### ISSUE THREAD

**Issue by cmtomkan310** [ssrpanel/SSRPanel#769]
有赞支付成功后，不显示【订单管理】中了，在线支付可以正常显示，但是有赞那边正常收钱，用户也可以正常使用对应购买的套餐！回调日志也正常！

**Comment by cmtomkan310** [comment]
不算bug啊，我是按照
https://github.com/ssrpanel/SSRPanel/issues/768

这个修改了autojob.php文件所导致，还是等老大修复用户封禁记录吧

**Comment by SheffieldLee** [comment]
@cmtomkan310 有赞和这个根本没关系啊  我测试一下看看

**Comment by cmtomkan310** [comment]
不信你试试，我试过了，改完你的那个版本就不行，用默认的就可以了！

**Comment by SheffieldLee** [comment]
我刚测试了一下，订单管理完全正常，那个AutoJob.php 和订单没任何关系，完全不影响的，改成-1是我看的他commit之前的代码，还有where（'enable', 1)是为了不让封禁log重复写，和订单真的没有任何关系。

![tim 20180727111106](https://user-images.githubusercontent.com/33490770/43299682-d73274aa-918d-11e8-84fc-5c0bfc78c63a.png)

**Comment by SheffieldLee** [comment]
我觉得账号过期封禁后，应删除流量重置日期。胖虎兄，你觉得呢

![tim 20180727112010](https://user-images.githubusercontent.com/33490770/43299920-0ef36b50-918f-11e8-85c8-46f5b2f4e276.png)

**Comment by cmtomkan310** [comment]
那我这边怎么不行了。。。邪门

**Comment by cmtomkan310** [comment]
蒙圈了，该到你那个版本，又可以！但是刚刚的确有个订单没在订单管理显示出来。。。

**Comment by SheffieldLee** [comment]
@cmtomkan310 不行就 sh ./update 强制更新代码

**Comment by ssrpanel** [comment]
代码更新了，更新试试看

**Comment by yeehomlee** [comment]
@cmtomkan310 
你确认下，是不是出问题的在于「版本更新之前，且因流量用完而被关闭的用户」
版本更新之后再过期的用户，应该是没问题的。
