### ISSUE TITLE
readme安装说明不正确

### ISSUE THREAD

**Issue by thank243** [ssrpanel/SSRPanel#770]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
cd SSRPanel/
cp .env.example .env
（然后修改数据库连接信息）
php artisan key:generate
php composer.phar install
chown -R www:www storage/
chmod -R 777 storage/

应该先php composer.phar install
再php artisan key:generate

**Comment by ssrpanel** [comment]
。。。已经改了，真细心
