### ISSUE TITLE
无法git pull升级

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/SSRPanel#773]
无法git升级,杂回事?

`[root@all-websites ssrpanel]# git pull
fatal: Not a git repository (or any of the parent directories): .git
[root@all-websites ssrpanel]# ^C
[root@all-websites ssrpanel]# git init
Initialized empty Git repository in /www/wwwroot/www.xxx.com/ssrpanel/.git/
[root@all-websites ssrpanel]# git pull
fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.
[root@all-websites ssrpanel]# 
`

**Comment by ssrpanel** [comment]
你本地 git 配置有错了吧。

**Comment by ssrpanel** [comment]
你不是用git clone 拉代码下来的，而是 直接下的zip包。所以没有办法git pull
