### ISSUE TITLE
TCP阻断提醒，通过什么提醒

### ISSUE THREAD

**Issue by SheffieldLee** [ssrpanel/SSRPanel#776]
![tim 20180728152118](https://user-images.githubusercontent.com/33490770/43354184-f2920f2a-9279-11e8-95c4-2b7506f9a17b.png)

打开后，是通过邮箱提醒吗？叼大的能不能说一下？

**Comment by MrPangzhan** [comment]
@SheffieldLee 是的。

**Comment by SheffieldLee** [comment]
@MrPangzhan 谢谢！老哥
