### ISSUE TITLE
TCP检测增加自定义端口的建议

### ISSUE THREAD

**Issue by thank243** [ssrpanel/SSRPanel#777]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
希望可以自定义tcp的端口，直接22端口一般都会改掉的，22放出来太危险。
开始不知道，结果一检测就说宕机。

**Comment by SheffieldLee** [comment]
把密码访问关了，配置SSH免密登录，没事吧，被扫描就扫描呗

**Comment by ssrpanel** [comment]
我之前是要做一个节点 那 让用户天一个ssh端口用于检测的，后面着急上代码，把那块改掉了，你可以看一下git的代码提交记录。。。后面再做把。

**Comment by ssrpanel** [comment]
已更新
