### ISSUE TITLE
【建议】设置“仅封禁代理”账户过期，封禁代理并释放端口

### ISSUE THREAD

**Issue by MrPangzhan** [ssrpanel/SSRPanel#778]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
如题，建议后台设置了“仅封禁代理”，在账户过期后，封禁代理并释放端口。
目前选择了这个设置，封禁了代理，清空了标签，使用流量和未使用流量，所以建议在加个释放端口。
就是说封禁了代理后把端口释放了。

**Comment by SheffieldLee** [comment]
自己在代码里 加个 port=0 就行了啊

**Comment by ssrpanel** [comment]
不对，被你误导了，仅封禁代理不应该释放端口的
