### ISSUE TITLE
流量包到期之后不会在服务单里去掉,不知道是BUG,还是设定

### ISSUE THREAD

**Issue by niyeyeqi** [ssrpanel/SSRPanel#779]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
![231321](https://user-images.githubusercontent.com/31157068/43363406-93d5a290-9336-11e8-9ca3-9b89a1833960.png)
@ssrpanel

**Comment by SheffieldLee** [comment]
有bug  待修复

**Comment by SheffieldLee** [comment]
@ssrpanel 这里好像是bug啊

**Comment by ssrpanel** [comment]
是这样吗？定时任务？

**Comment by ssrpanel** [comment]
修复了
