### ISSUE TITLE
有考虑单端口多用户吗

### ISSUE THREAD

**Issue by nutb** [ssrpanel/ssrpanel#78]
这个功能很实用

**Comment by ssrpanel** [comment]
我没搞明白SSR怎么实现的。等我搞明白就加上

**Comment by ssrpanel** [comment]
@nutb

**Comment by zeeqy** [comment]
破娃酱有个[说明](https://breakwa11.blogspot.hk/2017/01/shadowsocksr-mu.html)

我用mudbjson的方式实现了，开在80端口。正常访问是个nginx静态网页，客户端连接就是ssr服务，感觉还是蛮隐蔽的。

**Comment by ssrpanel** [comment]
@zeeqy 嗯嗯，我研究下

**Comment by Hao-Luo** [comment]
其实你在80端口是个坑呀朋友，80都不是加密的端口，你传输加密的资料一眼就看出来了，你得放在https端口

**Comment by zeeqy** [comment]
@Hao-Luo 80口跑加密资料也没啥，正常网站也可以做到。相比起识别加密资料，禁用奇怪的端口更有效，毕竟一个SS服务器，多人用一人一个口，就是一堆4位数端口呀，太好识别了。

**Comment by ssrpanel** [comment]
@nutb @zeeqy @Hao-Luo @izhangxm 单端口功能已上，git pull一下最新的代码，然后数据库导入一下 sql/20171112.sql

**Comment by ssrpanel** [comment]
建议用443

**Comment by zeeqy** [comment]
赞一个！实测已经实现，但 `./tail.sh`日志里反复出现错误信息

`ERROR    db_transfer.py:505 (1364, "Field 'created_at' doesn't have a default value")`

不知道啥问题....并不影响使用

**Comment by zeeqy** [comment]
粗浅的debug了一下，应该是table创建时候的默认值问题，主要是datetime的默认值，按照这样创建就没错误了。

`
CREATE TABLE `ss_node_info` (   `id` int(11) unsigned NOT NULL AUTO_INCREMENT,   `node_id` int(11) NOT NULL DEFAULT '0' COMMENT '节点ID',   `uptime` float NOT NULL COMMENT '更新时间',   `load` varchar(32) NOT NULL COMMENT '负载',   `log_time` int(11) NOT NULL COMMENT '记录时间',   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `updated_at` datetime ON UPDATE CURRENT_TIMESTAMP,   PRIMARY KEY (`id`) );
`

`CREATE TABLE `ss_node_online_log` (   `id` int(11) NOT NULL AUTO_INCREMENT,   `node_id` int(11) NOT NULL COMMENT '节点ID',   `online_user` int(11) NOT NULL COMMENT '在线用户数',   `log_time` int(11) NOT NULL COMMENT '记录时间',   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `updated_at` datetime ON UPDATE CURRENT_TIMESTAMP,   PRIMARY KEY (`id`),   KEY `idx_online` (`node_id`,`log_time`) );
`

**Comment by wuwentao** [comment]
我也遇见这个问题了，google关键字直接过来了，按 @zeeqy 的方法修改，貌似ok了，目前没有在log里发现这个error
