### ISSUE TITLE
关于标签重复的提议

### ISSUE THREAD

**Issue by SheffieldLee** [ssrpanel/SSRPanel#781]
我看了 标签去重 部分的代码，可惜对php只是略懂。
![tim 20180730013027](https://user-images.githubusercontent.com/33490770/43368962-2a42602c-9398-11e8-97bc-7b1dc538ea6b.png)
看到在 if (date("Y-m-d H:i:s") >= $order->expire_at) {} 代码块里
这个标签去重怎么在用户过期之后去重呢？应该在有效期内就去重吧。
我自己尝试改了几次，技术不行，失败了。
![tim 20180730013235](https://user-images.githubusercontent.com/33490770/43368982-7b00dc96-9398-11e8-82f8-4a6df5ee09b1.png)
我们看这个user_label表，与其说标签的重复，不如说user_id的重复，即同一个标签拥有2个用户？而面板里，统计标签关联用户数也是统计的该标签下user_id的数目，实际该标签1只有2个用户（user_id: 1 , 2），但是面板里统计却是4人。
![tim 20180730013539](https://user-images.githubusercontent.com/33490770/43369011-eaa4f88e-9398-11e8-8fc9-f9e2d5c252d2.png)

那么，标签去重是不是应该是“用户去重”，同个标签的用户去重。
解决方案（2种）：
1. 定时任务去重，删除同个标签重复的用户。

2.从源头解决问题，标签产生重复的原因是因为，用户拥有初始标签（注册得到），然后购买拥有该标签的商品后，就会在user_label里产生重复，导致同个标签拥有多个user_id，在购买商品给用户加标签的时候加个判断，如果用户拥有该标签，则不再重复加标签。

对php确实不太懂，胖虎兄看看吧。

**Comment by SheffieldLee** [comment]
@ssrpanel 胖虎兄，2个pull请求，解决了标签重复问题，还修复了一个bug，看一下

**Comment by ssrpanel** [comment]
已经合并了，感谢
