### ISSUE TITLE
这次是不是少个sql文件？

### ISSUE THREAD

**Issue by dovela** [ssrpanel/SSRPanel#784]
编辑失败：SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ssh_port' in 'field list' (SQL: update `ss_node` set `name` = 洛杉矶, `group_id` = 1, `country_code` = us, `server` = , `ip` = , `ipv6` = , `desc` = , `method` = aes-256-cfb, `protocol` = auth_chain_a, `protocol_param` = , `obfs` = http_simple, `obfs_param` = , `traffic_rate` = 1, `bandwidth` = 1000, `traffic` = 1000, `monitor_url` = , `is_subscribe` = 1, `ssh_port` = , `compatible` = 0, `single` = 0, `single_force` = 0, `single_port` = , `single_passwd` = , `single_method` = , `single_protocol` = , `single_obfs` = , `sort` = 1, `status` = 1, `updated_at` = 2018-07-30 23:11:02 where `id` = 19)
（隐私信息已删除）

**Comment by ssrpanel** [comment]
上上次更新就有两个sql（最后两个）
