### ISSUE TITLE
为什么一支付日志会出错

### ISSUE THREAD

**Issue by banxianl08** [ssrpanel/SSRPanel#787]
日志如下
[2018-07-31 19:56:22] local.INFO: YZY-POST:  
[2018-07-31 19:56:23] local.INFO: 【有赞云】等待支付{"update_time":"2018-07-31 19:56:22","extra_info":"{\"is_retail_offline\":false}","payment":"120.00","pay_type":"","book_id":null,"tid":"E20180731195622080800005","status":"WAIT_BUYER_PAY"}  
[2018-07-31 19:56:23] local.INFO: YZY-POST:  
[2018-07-31 19:56:23] local.ERROR: ErrorException: Undefined index: kdt_name in /www/wwwroot/ssrpanel/app/Http/Controllers/Api/YzyController.php:58
Stack trace:
#0 /www/wwwroot/ssrpanel/app/Http/Controllers/Api/YzyController.php(58): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/www/wwwroot/ss...', 58, Array)
#1 [internal function]: App\Http\Controllers\Api\YzyController->store(Object(Illuminate\Http\Request))
#2 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#3 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('store', Array)
#4 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\YzyController), 'store')
#5 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#6 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(572): Illuminate\Routing\Route->run()
#7 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), '60', '1')
#13 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#17 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#18 /www/wwwroot/ssrpanel/vendor/laravel

但是不影响支付 只是日志里出现这种权限www没问题，昨天升级的

**Comment by cdlaimin** [comment]
你的不影响吗 我的 不能打标签。。。。
