### ISSUE TITLE
SSpanel流量使用情况不显示 用户中心的最近登陆也显示为从未登陆 计划任务正常

### ISSUE THREAD

**Issue by ckyun06** [ssrpanel/SSRPanel#799]
SSRpanel流量使用情况不显示 后台的流量日志也是空的
用户中心的最近登陆也显示为从未登陆
 计划任务是正常的情况 日志也是已执行
![qq 20180804093825](https://user-images.githubusercontent.com/42070924/43671337-7d1002ec-97ca-11e8-822d-e79b51e25893.png)

**Comment by ckyun06** [comment]
使用的是单443端口模式

**Comment by thank243** [comment]
等24h再看下。
