### ISSUE TITLE
sql升级出错

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#80]
@ssrpanel 

更新拉代码下来就要去看下sql/update/下的sql, 运行sql语句出现错误是什么问题? 按提示说是已经有同样列存在了,如何解决? 

另外:继续20请笑纳.

![32343280-e785a498-c03d-11e7-8aa3-c7509202c4a2](https://user-images.githubusercontent.com/32491066/32404274-baeb3df8-c187-11e7-8165-e850a9fabe8e.png)

**Comment by ssrpanel** [comment]
已存在就不用理会了，因为我在sql/db.sql每次更新都会把整个库的结构跟着更新
