### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by ZhangqianStudio** [ssrpanel/SSRPanel#801]
希望可以針對商品方面支持如下操作：
支持限制每個用戶對於單個商品的購買個數
支持將商品上架，但是不在前台顯示。即：用戶在商品列表看不到該商品，但是可以通過訪問商品的 url 來進行購買

**Comment by Chennhaoo** [comment]
商品会覆盖的，不会叠加，限制购买次数意义不大吧
第二个有什么特殊意义吗？

**Comment by ZhangqianStudio** [comment]
限制單個商品的購買次數可以拿來搞一些促銷活動之類的。或者限制月付用戶的每月最大可用流量
第二個也是拿來促銷的。隱藏套餐之類的

**Comment by Chennhaoo** [comment]
促销的话可以充钱便宜点嘛，应为这个覆盖是程序设计的时候考虑了的，估计不会轻易该。
希望帮到你
