### ISSUE TITLE
关于商品到期后，一个严重BUG

### ISSUE THREAD

**Issue by SheffieldLee** [ssrpanel/SSRPanel#802]
昨晚一个人告诉我，说他上午刚买的一个月流量包怎么被清空了？？？我（？？？？）
然后我去看了他的账号，确实上午刚买的。
然后我分析了一下，发现他流量被清空的原因是：
根据时间线来：
1. 他上个月购买了一个月流量包，到期日期 8月4号 13:05，同时对应的账号到期为 8月4号 0:00。
2. 根据我们的任务，他的账号在8月4号 0:00 过期了，被清空了所有流量，可用流量此时为0。
3. 这个人在8月4号 8:50 续费了一个月流量包，此时可用流量为 30GB。 
4. 到了8月4号 13:05 就出BUG了，因为根据 SSRPanel/app/Console/Commands/AutoDecGoodsTraffic.php
![tim 20180805122322](https://user-images.githubusercontent.com/33490770/43682576-75952452-98ab-11e8-94c9-ec2ffe325242.png)
这里商品到期8月4号 13:05 到期后，会清除对应的流量，可是在 0:00 的时候已经清空了用户的流量了，
然后直接就把他上午刚买的流量给清空了。

修复建议：简单解决方案：将用户到期时间改为当天的24:00，但所有where('expire_time', '<=', date('Y-m-d'))都要改成where('expire_time', '<', date('Y-m-d'))，这可能会涉及到其他人1天的利益，呵呵。。。我无所谓。

其他解决方案：
在这里加个判断，如果用户只有一个流量包，那么不清空可用流量，因为在这天的 0:00 由AutoJob.php 已经将账户清空了。 
![tim 20180805122322](https://user-images.githubusercontent.com/33490770/43682646-4e2cfbea-98ad-11e8-9dea-faf2a714c947.png)

@ssrpanel 胖虎兄看一下。

**Comment by SheffieldLee** [comment]
另外还有一个pull 请求，胖虎兄看一下。

**Comment by garhing** [comment]
将0:00执行的任务改成23:59执行不就行了？

**Comment by garhing** [comment]
另外一个相关的bug是用余额支付和在线支付的逻辑不一致，比如有个用户30号到期，今天5号买一个一周的流量包，余额支付无影响，在线支付会将有效期置为12号到期。

**Comment by ssrpanel** [comment]
PR代码已合并

**Comment by ssrpanel** [comment]
我个人并未真正使用过商品、套餐，这些都是以前群友们的需求。可能改着改着坑就变多了。有空我彻底重构

**Comment by ssrpanel** [comment]
逻辑上设计的很不合理

**Comment by moonlit7seas** [comment]
这里面坑好多啊，，，回头还是要把代码从头再仔细看一遍～～

**Comment by moonlit7seas** [comment]
![image](https://user-images.githubusercontent.com/42288472/43999064-ec400938-9e36-11e8-80f4-e88fd4155c61.png)

**Comment by moonlit7seas** [comment]
一下全上不了网了，我还以为是被墙了

**Comment by ssrpanel** [comment]
fixed
