### ISSUE TITLE
奇怪了 有赞付费之后 付费是成功的，但是直接清空了流量但是后面的套餐流量并没有加上去

### ISSUE THREAD

**Issue by cdlaimin** [ssrpanel/SSRPanel#806]
导致0/0的流量 封禁了用户 请问这是什么原因导致的呢

**Comment by SheffieldLee** [comment]
没遇到你这bug  不行就 sh ./update

**Comment by ZBrettonYe** [comment]
前一个套餐未支付是吧

**Comment by cdlaimin** [comment]
./update了 没用 都不知道哪儿出了问题

**Comment by cdlaimin** [comment]
我重新拉了分支覆盖了 也不行 就是购买套餐成功之后 就报 【封禁代理】-流量已用完 
前一个套餐是已关闭状态
请求导致异常的地址：https://www.ssrjs.tk/api/yzy  
【有赞云】回调订单状态不正确

**Comment by ssrpanel** [comment]
应该改进了吧

**Comment by ssrpanel** [comment]
问题还存吗？
