### ISSUE TITLE
BUG反馈：过期用户购买新套餐，不是在购买日期上叠加。

### ISSUE THREAD

**Issue by yeehomlee** [ssrpanel/SSRPanel#807]
已经过期的用户，购买套餐，是从过期日期算起，而不是购买日期上算起。

比如，用户的有效期为：2018年1月1日 - 2018年1月31日 。

到了2月15日，用户才去购买 套餐(一个月时长)。

此时，有效期应该是变成 3月15日。

但我最近测试，发现是从过期日算起，购买后有效期是 2月31日。

由于 demo 密码被改，我暂时验证不了。
请其他朋友帮忙验证一下，是否属于通用BUG。

**Comment by lzmfor** [comment]
嗯，好像都是这样。。。初始日期它好像就认定是注册的那个日期，这几次更新好像都没修复

**Comment by yeehomlee** [comment]
@ssrpanel  
胖虎重视一下，这个 bug 还蛮紧要的。购买了套餐发现不对劲，容易产生纠纷。

**Comment by ssrpanel** [comment]
FIXED
