### ISSUE TITLE
用户列表管理员权限时候可以高亮,并且加个搜索过滤选项?

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#81]
否则用户太多, 管理员不知道是谁就麻烦大了.
另外禁止掉用户也用另外种颜色高亮这样就很容易区别了.

![qq 20171104175627](https://user-images.githubusercontent.com/32491066/32404384-b7334a82-c189-11e7-8f43-5e5a37ca5188.png)

**Comment by ssrpanel** [comment]
@1021435278 你什么需求为什么需要多个管理员，管理员只有一个，就是ID为1的默认管理员。你要把账号设置成管理员吗？看来我要把设置管理员这个功能去掉。

**Comment by 1021435278** [comment]
@ssrpanel  可以把设置管理员功能去掉, 但是已经禁止的用户尽量用其它颜色高亮.
