### ISSUE TITLE
建议反馈：建议减缓账户到期/流量不足的流量推送频率。

### ISSUE THREAD

**Issue by LEE-Blog** [ssrpanel/SSRPanel#816]
现在的邮件警告提醒，是一旦超过设定的 警告阀值 ，则每天每用户推送一封。
一旦用户量较多（特别是恶意注册数量增加时），邮件推送的频率将会非常高。
不仅增加了服务器的负载，还容易造成邮件服务器被恶意封禁。
即使是 Mailgun ，也有 每小时100封 的上限，超过的话会被视发送垃圾邮件。

简单的说，我希望用户到期前 14天 提醒他，但并不需要提醒 14 遍。
无论作为运营者，或者用户，都喜欢这么频繁的邮件。

**因此我的建议是：**

在警告提醒设置中，增加一个 **[推送时间间隔]** 。
意思是，包含过期及流量警告在内，一旦该**时间间隔**内已推送过邮件，则不再推送。
比如，时间间隔设为 72小时 。则账户即将过期+流量即将用为的用户，在72小时内也只会收到一封邮件。

谢谢，胖虎辛苦了。

**Comment by cmmdwl** [comment]
建议 默认设置时间提醒一封 到期前一天提醒一封 其他时间不用提醒

**Comment by ssrpanel** [comment]
marked

**Comment by ssrpanel** [comment]
应该处理的是恶意注册数量问题
