### ISSUE TITLE
BUG反馈：折扣券「重复使用」无效。

### ISSUE THREAD

**Issue by yeehomlee** [ssrpanel/SSRPanel#817]
后台生成的「可重复使用」的折扣券，经测试，同样也是一次性使用。
虽然，使用后折扣券状态不会显示已使用。
但是，第二次使用时，券码是无效的。

重复折扣券在促销活动中十分有效。

demo 无法登录，无法二次验证，请其他朋友验证一下是否同样问题。

**Comment by ssrpanel** [comment]
marked

**Comment by ssrpanel** [comment]
已修复
