### ISSUE TITLE
大佬们，更新后日志出错，面板正常使用，

### ISSUE THREAD

**Issue by banxianl08** [ssrpanel/SSRPanel#819]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
更新后日志一直这样，
Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'port' (SQL: update `user` set `port` = 0, `updated_at` = 2018-08-16 02:01:05 where `id` = 1153) in /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:647
Stack trace:
#0 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('update `user` s...', Array, Object(Closure))
#1 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(477): Illuminate\Database\Connection->run('update `user` s...', Array, Object(Closure))
#2 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): Illuminate\Database\Connection->affectingStatement('update `user` s...', Array)
#3 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2147): Illuminate\Database\Connection->update('update `user` s...', Array)
#4 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(759): Illuminate\Database\Query\Builder->update(Array)
#5 /www/wwwroot/ssrpanel/app/Console/Commands/AutoJob.php(239): Illuminate\Database\Eloquent\Builder->update(Array)
#6 /www/wwwroot/ssrpanel/app/Console/Commands/AutoJob.php(59): App\Console\Commands\AutoJob->dispatchPort()
#7 [internal function]: App\Console\Commands\AutoJob->handle()
#8 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#9 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#10 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#11 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#12 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#13 /www/wwwroot/ssrpanel/vendor/symfony/console/Command/Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#14 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#15 /www/wwwroot/ssrpanel/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /www/wwwroot/ssrpanel/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\AutoJob), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /www/wwwroot/ssrpanel/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /www/wwwroot/ssrpanel/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 {main} 

面板正常使用。。。。

**Comment by ssrpanel** [comment]
去除 user 表中port 得唯一索引

**Comment by banxianl08** [comment]
@ssrpanel 小白不是很懂，请您能说具体操作步骤吗.非常感谢

**Comment by banxianl08** [comment]
@ssrpanel 非常感谢，已解决
