### ISSUE TITLE
用户有效期和流量包困惑

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#82]
1. 用户注册时候有效期是什么概念? 过去是账户被禁止,那么ssr账户了? 如果过期是否需要重新激活? 
2. 商品中如果一个用户购买了商品,但账号过了有效期如何解决?

![qq 20171104175943](https://user-images.githubusercontent.com/32491066/32404409-2d127796-c18a-11e7-8128-e99b432e3d9a.png)

**Comment by ssrpanel** [comment]
@1021435278 
假设50M流量包，有效期1天，购买的时候会往账号的总流量里加上50M，一天后管你用没用，自动把你总流量减去50M。套餐这样：10G/月的套餐，流量10G，假设有效期是90天，也就是3个月，后台开启流量自动重置那个选项后，每个月1号会自动给购买这个套餐的人有10G可用的流量（用完就没了，总量不变，说白了就是已使用的流量每个月到期会清零，这个10G只是账号的可用总流量的值）

**Comment by 1021435278** [comment]
TG组中有人提到: 你们没发现ssrpanel对于已到期但流量没完的用户还是能够正常使用的吗, 所以流量包就是额外购买的,无所谓用户id到期不到期吗? @ssrpanel
