### ISSUE TITLE
建议站点里货币单位统一一下

### ISSUE THREAD

**Issue by Bennett561** [ssrpanel/SSRPanel#826]
发现不同的功能界面货币单位都不统一啊，有的以元作单位，有的用分，这真的很迷。
数据库以分可以理解，面板全转换为元不是更人性化吗？

**Comment by ssrpanel** [comment]
面板里展示出来哪里用分了？

**Comment by Bennett561** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
提现金额


    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }

        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    
                        
    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    
徐捷


                    
                
 


    在2018年8月17日 23:40，Bruskyii Panda<notifications@github.com> 写道： 


面板里展示出来哪里用分了？
