### ISSUE TITLE
订单未支付超过30分钟未被取消

### ISSUE THREAD

**Issue by hubert03** [ssrpanel/SSRPanel#829]
![image](https://user-images.githubusercontent.com/24841291/44276109-1dd45f80-a279-11e8-81e0-764ab0081702.png)

**Comment by hubert03** [comment]
![image](https://user-images.githubusercontent.com/24841291/44276168-48beb380-a279-11e8-8e71-3ce361ddfda3.png)

**Comment by cmmdwl** [comment]
定时任务
