### ISSUE TITLE
节点删除后,用户中心节点列表里面还在

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#83]
管理员删除节点且节点ssr也删除后, 用户中心节点列表还在,但为0.

![default](https://user-images.githubusercontent.com/32491066/32405514-0767182c-c1a2-11e7-8d74-8c5efcb573cd.png)
@ssrpanel

**Comment by ZBrettonYe** [comment]
去数据库中删除

**Comment by 1021435278** [comment]
@ZBrettonYe 

具体点,那个表? 如何删除? 算是bug吗?

**Comment by ZBrettonYe** [comment]
@1021435278 ss_node中看

**Comment by 1021435278** [comment]
@ZBrettonYe  这个表中看不到删除的Node的, 我其实第一时间去看过了.

**Comment by 1021435278** [comment]
ss_group_node  是这个表才对.....

**Comment by ssrpanel** [comment]
。。。是bug。。我处理下

**Comment by ssrpanel** [comment]
已修正，坐等更新代码 @1021435278
