### ISSUE TITLE
提现功能的一点小建议

### ISSUE THREAD

**Issue by Bennett561** [ssrpanel/SSRPanel#834]
提现功能感觉大部分人都不怎么用，我这边用得还挺好的，希望能有所改进。
个人觉得提现功能不够智能，打到支付宝或微信不太实际，手动操作太麻烦。
不如直接来个一键提现到网站的账户余额，比现在这个手动的方便不少。

**Comment by ssrpanel** [comment]
marked

**Comment by yeehomlee** [comment]
插一句，
用户申请返佣提现后，可以不用审核，系统直接转至账户余额。

如果有提现需求的，可以从账户余额再提现，即现在的提现审核功能。

**Comment by Bennett561** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
我就是这个意思嘛！嘿嘿


    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }

        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    
                                
            
                
                    
                            
                                
                            
                            
                                bennett_tri
                            
                            
                                
                            
                    
                        
                            
                                    bennett_tri@sjtu.edu.cn
                            
                        
                
            
        
                    
                
                
                    签名由
                    网易邮箱大师
                    定制
                
 


    在2018年8月19日 22:31，LEE<notifications@github.com> 写道： 


插一句，
用户申请返佣提现后，可以不用审核，系统直接转至账户余额。
如果有提现需求的，可以从账户余额再提现，即现在的提现审核功能。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Bennett561** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
辛苦了，感激不尽


    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }

        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    
                                
            
                
                    
                            
                                
                            
                            
                                bennett_tri
                            
                            
                                
                            
                    
                        
                            
                                    bennett_tri@sjtu.edu.cn
                            
                        
                
            
        
                    
                
                
                    签名由
                    网易邮箱大师
                    定制
                
 


    在2018年8月19日 22:25，Bruskyii Panda<notifications@github.com> 写道： 


marked

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ssrpanel** [comment]
marked one more time

**Comment by ssrpanel** [comment]
鸡肋，用户申请提现后，可以手动给用户充值
