### ISSUE TITLE
反馈：有赞云推送配置更新，现有推送将于12月份失效。

### ISSUE THREAD

**Issue by yeehomlee** [ssrpanel/SSRPanel#835]
这是来自有赞云的公告通知：

> 原有的商品V1和交易V1/V2版推送 ,包含的内容较单一，无法满足不同业务场景下的开发需求，因此有赞将于18年12月1日正式下线并停止这两种服务，如您正在使用，请尽快切换至V3版本，启用最新的推送服务。

![screen_20180819_205350](https://user-images.githubusercontent.com/20637016/44309021-5cd9f080-a3f2-11e8-88a2-5f03689cf7ce.png)

![screen_20180819_205328](https://user-images.githubusercontent.com/20637016/44309022-5cd9f080-a3f2-11e8-86b6-927520d29541.png)

经过反复验证，在 SSRPanel 现有代码不动的情况下，
将有赞云推送切换到新的「 V3 消息推送」时，**付款无法正常回调**。

也就是说，如果不适配新的有赞云「V3 消息推送」，现有支付功能将于12月份就失效。

特此反馈，请胖虎留意。

**Comment by ssrpanel** [comment]
mark 群里说

**Comment by ssrpanel** [comment]
已经更新了
