### ISSUE TITLE
自动化任务日志中报错“节点监测请求失败”

### ISSUE THREAD

**Issue by huageniubi** [ssrpanel/SSRPanel#836]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
昨天在翻看 ssrpanel/storage/logs 里面的自动化任务日志的时候发现每个整点有关节点监测的任务时都会出现以下报错
`[2018-08-20 00:00:05] local.ERROR: 节点监测请求失败：ErrorException: Undefined index: cn1.node.check-host.net in /www/wwwroot/ssrpanel/ssrpanel/app/Console/Commands/AutoCheckNodeStatus.php:138
Stack trace:
#0 /www/wwwroot/ssrpanel/ssrpanel/app/Console/Commands/AutoCheckNodeStatus.php(138): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/www/wwwroot/ss...', 138, Array)
#1 /www/wwwroot/ssrpanel/ssrpanel/app/Console/Commands/AutoCheckNodeStatus.php(51): App\Console\Commands\AutoCheckNodeStatus->tcpCheck('209.250.227.21', 22)
#2 /www/wwwroot/ssrpanel/ssrpanel/app/Console/Commands/AutoCheckNodeStatus.php(34): App\Console\Commands\AutoCheckNodeStatus->checkNodeStatus()
#3 [internal function]: App\Console\Commands\AutoCheckNodeStatus->handle()
#4 /www/wwwroot/ssrpanel/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#5 /www/wwwroot/ssrpanel/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /www/wwwroot/ssrpanel/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#7 /www/wwwroot/ssrpanel/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#8 /www/wwwroot/ssrpanel/ssrpanel/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#9 /www/wwwroot/ssrpanel/ssrpanel/vendor/symfony/console/Command/Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#10 /www/wwwroot/ssrpanel/ssrpanel/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#11 /www/wwwroot/ssrpanel/ssrpanel/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /www/wwwroot/ssrpanel/ssrpanel/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\AutoCheckNodeStatus), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /www/wwwroot/ssrpanel/ssrpanel/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /www/wwwroot/ssrpanel/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /www/wwwroot/ssrpanel/ssrpanel/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 {main}  `

请问这个报错的话是不是表示节点的TCP监测就失去功能了？
有大佬看到了能告知小弟一下吗，真的是非常感激不尽。

**Comment by cmmdwl** [comment]
不是一直出错就没有问题

**Comment by banxianl08** [comment]
我的也是，我关闭了 tcp检测没多大用处，又不是很准

**Comment by cmmdwl** [comment]
有的时候可能服务器炸了

**Comment by ssrpanel** [comment]
cn1 被国内某些 装逼人士D到服务器被check-host直接下线了。没得玩了。早知道老纸不放出这个功能

**Comment by huageniubi** [comment]
OK 了解了 感谢胖虎哥~
