### ISSUE TITLE
请教：如何修改个人中心客户端地址？

### ISSUE THREAD

**Issue by cmtomkan310** [ssrpanel/SSRPanel#837]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
![image](https://user-images.githubusercontent.com/38905231/44315606-83cb0d80-a458-11e8-9662-161950c30ab6.png)

如何修改这部分内容？

**Comment by yeehomlee** [comment]
自行修改
ssrpanel/resources/views/user/index.blade.php

**Comment by cmtomkan310** [comment]
@yeehomlee 谢了。。。
