### ISSUE TITLE
CentOS7 下改 SSH 端口号的方法需要更新一下。

### ISSUE THREAD

**Issue by DearTanker** [ssrpanel/SSRPanel#838]
默认系统可以通过以下命令快速修改 sshd_config中的 SSH 端口：

`sed -i "s/#Port 22/Port 新端口/g" /etc/ssh/sshd_config`

另外由于 SELinux 默认在 CentOS 7 中启用，所以更改 SSH 端口需要同时更新 SElinux 的端口 。

需要安装 policycoreutils 组件来让 semanage 更新 SSHD 端口。

```
yum -y install policycoreutils-python
semanage port -a -t ssh_port_t -p tcp 新端口
```

**Comment by ssrpanel** [comment]
好的大佬

**Comment by supermycode** [comment]
sed -i "s/#Port 22/Port 新端口/g" /etc/ssh/sshd_config
大佬，这个命令需要先在防火墙放行新端口，不然连不上ssh
出于安全考虑，最好先同时保留22 和 新端口，测试ok后再关闭22
sed -i "s/#Port 22/Port 22/g" /etc/ssh/sshd_config
echo "Port 新端口" >> /etc/ssh/sshd_config

**Comment by DearTanker** [comment]
@supermycode 这个命令改完并不会马上生效，是重启后生效的，当然重启之前一定要先加入防火墙，注意自己是firewalld还是iptables。
