### ISSUE TITLE
新的sql文件导入报错

### ISSUE THREAD

**Issue by zhangzheng7856** [ssrpanel/SSRPanel#839]
SQL 查询：

-- ----------------------------
-- Table structure for `sensitive_words`
-- ----------------------------
CREATE TABLE `sensitive_words` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`words` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '敏感词'
	PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='敏感词';
MySQL 返回： 文档

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMEN' at line 7

**Comment by cmmdwl** [comment]
缺了个逗号

**Comment by shileiye** [comment]
> `words` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '敏感词'

658行这句最后少个英文逗号

**Comment by ssrpanel** [comment]
fixed
