### ISSUE TITLE
重大BUG！赶紧处理！

### ISSUE THREAD

**Issue by cmtomkan310** [ssrpanel/SSRPanel#841]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问

点击在线支付后，出现

创建支付单失败：商品或服务已下架

**Comment by cmtomkan310** [comment]
![image](https://user-images.githubusercontent.com/38905231/44388699-53b86300-a55b-11e8-8007-f2084dde45b6.png)

**Comment by cmtomkan310** [comment]
备注：之前一直没问题，今天更新完后出的问题！

**Comment by ssrpanel** [comment]
奇怪。我试试

**Comment by ssrpanel** [comment]
修正了。
