### ISSUE TITLE
提交BUG

### ISSUE THREAD

**Issue by cmtomkan310** [ssrpanel/SSRPanel#842]
点击用户账号后，点击切换身份，显示切换身份成功，但是弹出“页面不存在”！

此问题还包括【文章管理】中，在【个人中心】里【客户端说明】引用文章管理中的文章，也会出现同样的问题！不知道我描述的是否清楚。。。

**Comment by cmtomkan310** [comment]
![image](https://user-images.githubusercontent.com/38905231/44397837-4196ee80-a574-11e8-942d-d3ae5a44ff87.png)

**Comment by cmtomkan310** [comment]
![image](https://user-images.githubusercontent.com/38905231/44397863-5c696300-a574-11e8-8e6f-f54a0e6e03c4.png)

**Comment by cmtomkan310** [comment]
![image](https://user-images.githubusercontent.com/38905231/44397958-a5b9b280-a574-11e8-9479-cf836219a81d.png)

**Comment by ssrpanel** [comment]
1.切换身份那个修复了
2.用户界面全部url都移除/user/了，你直接把 /user/article 改成 article
