### ISSUE TITLE
更新后站内LOGO跳转user 404

### ISSUE THREAD

**Issue by banxianl08** [ssrpanel/SSRPanel#843]
个人中心LOGO跳转找不到user 404,

还有自定义LOGO如何恢复默认。

**Comment by banxianl08** [comment]
支付成功后跳转也是404  https://网址/user/orderList 显示404

**Comment by ssrpanel** [comment]
fixed

**Comment by banxianl08** [comment]
@ssrpanel 重装面板也是一样，大佬求解决啊，
