### ISSUE TITLE
原版后端使用

### ISSUE THREAD

**Issue by Hamishcn** [ssrpanel/SSRPanel#844]
胖虎哥，刚刚想试着搭一下原版的manyuser，发现他那导入的数据库和面板的不一样，然后试着直接后端用面板的数据库，开启服务器报错，请问是不是不支持原版的manyuser啊？用的是我自己fork的这个版本，https://github.com/Hamishcn/shadowsocks。

**Comment by ssrpanel** [comment]
数据库不一样。
