### ISSUE TITLE
作者大大 多久添加限速功能啊  没有限速功能好悲催啊，简直是滥用啊 一个朋友分享一个 导致网速都被抢走完了

### ISSUE THREAD

**Issue by Google688** [ssrpanel/SSRPanel#845]
作者大大 没有限速功能好悲催啊，简直是滥用啊 一个朋友分享一个   一个朋友分享一个 导致网速都被滥用啊。就相当于给了一个朋友 实际是给了几十个朋友 一传十十传百。。。服务器的流量几下就被用完了。。。。

**Comment by ssrpanel** [comment]
为什么不直接封了他的号？

**Comment by cmmdwl** [comment]
限流拉倒，我猜你踩了定时任务的坑

**Comment by cmmdwl** [comment]
@Google688  参造我写的教程 cmmdwl.com
