### ISSUE TITLE
作者大大 可以给做个定制的后台限速出来吗 多少钱  就是不能给封掉啊。毕竟。。

### ISSUE THREAD

**Issue by Google688** [ssrpanel/SSRPanel#846]
作者大大 就是不能给封掉啊。毕竟。。可以给我做个这样的后台限速出来吗 多少钱

**Comment by Hamishcn** [comment]
限速不是在用户那有吗？

**Comment by Google688** [comment]
没用的 作者大大根本没有做的  那个只是虚设的。。

**Comment by Google688** [comment]
我当时就是看中了这个功能觉得好厉害 结果才知道是假的。。。。

**Comment by Hamishcn** [comment]
后端 user-config.json那个 speed per*的改一下试试

**Comment by Google688** [comment]
好的 谢谢大佬 这样就可以限速每个用户不同的速度了吗

**Comment by ssrpanel** [comment]
谈钱伤感情了，随便打个几万来吧

**Comment by ssrpanel** [comment]
哈哈哈哈哈哈哈哈

**Comment by Google688** [comment]
说真的 大佬  你一开始建立的时候就说过预留的后台限速 现在都马上2019年了。。。。

**Comment by ssrpanel** [comment]
@Google688 这不是一直在堆功能吗。没空折腾那个啊。
