### ISSUE TITLE
支付后BUG提交！

### ISSUE THREAD

**Issue by cmtomkan310** [ssrpanel/SSRPanel#847]
有赞成功支付后，显示支付成功，返回页面不存在！
![image](https://user-images.githubusercontent.com/38905231/44444159-02b57700-a60e-11e8-94e7-8836d11764f6.png)

**Comment by cmmdwl** [comment]
打开debug模式

**Comment by cmmdwl** [comment]
你的数据库导入没？

**Comment by ssrpanel** [comment]
再更新
