### ISSUE TITLE
更新后去除user/，求大佬帮忙。

### ISSUE THREAD

**Issue by banxianl08** [ssrpanel/SSRPanel#848]
之前在面板同目录里加了个首页同一域名完美使用，这次更新去掉了user ，个人中心以前是http://xxx.com/user，更新后http://xxx.com
导致点个人中心或者登录直接跳到我所加的首页界面去了，有没有方法解决，不想两个域名做跳转

不知描述看得懂不。

**Comment by cmmdwl** [comment]
作者就去掉/user 其他并未产生改变 有需要化使用旧版吧 或者改一下
