### ISSUE TITLE
已支出佣金单位

### ISSUE THREAD

**Issue by mingtochu** [ssrpanel/SSRPanel#849]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
<img width="103" alt="2018-08-24 12 30 21" src="https://user-images.githubusercontent.com/11163821/44565221-923b6100-a799-11e8-8d7a-243f67c46ba5.png">
实际已支出佣金为¥18，这个数值漏加小数点了。

**Comment by cmmdwl** [comment]
是的，确实缺少了小数点

**Comment by ssrpanel** [comment]
fixed
