### ISSUE TITLE
邮件模版在哪里修改

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#85]
@ssrpanel 

邮件中总是有图片中ssrpanel字样, 请问邮件模版在哪, 可以自行修改?

![default](https://user-images.githubusercontent.com/32491066/32407157-de4e924e-c1bf-11e7-8c3c-3b54b836f463.png)

**Comment by ssrpanel** [comment]
@1021435278 app\Mail 下

**Comment by hackagony** [comment]
找了好久，找不到修改的呢  ？
