### ISSUE TITLE
大佬 搭建好后又出现这个问题。。。Page Not Found  下面出现一个恐龙的图片 

### ISSUE THREAD

**Issue by Google688** [ssrpanel/SSRPanel#850]
![image](https://user-images.githubusercontent.com/38600824/44567166-bd2ab280-a7a3-11e8-83f2-ae5980e02b29.png)

**Comment by cmmdwl** [comment]
请打开debug模式

**Comment by Google688** [comment]
谢谢大佬的及时解答 可以了。谢谢 谢谢。
