### ISSUE TITLE
mailgun的secret是什么

### ISSUE THREAD

**Issue by ChenJunANA** [ssrpanel/SSRPanel#853]
Mailgun
编辑 config\mail.php
将 driver 值改为 mailgun

编辑 config/services.php

请自行配置如下内容
'mailgun' => [
'domain' => 'mailgun发件域名',
'secret' => 'mailgun上申请到的secret',
],

secret是什么意思？是API Key吗

**Comment by yeehomlee** [comment]
是

**Comment by yeehomlee** [comment]
是
