### ISSUE TITLE
我又来骚扰啦，后台的一点小建议

### ISSUE THREAD

**Issue by Bennett561** [ssrpanel/SSRPanel#859]
一个是下图这个用户数，能不能为动画设定一个固定的时间，用户数多了每次进后台等半天才能看到这个数目。
![image](https://user-images.githubusercontent.com/17747051/44623962-a4d8a600-a911-11e8-8ff3-eba450493919.png)
第二个是能不能开发一个一键清理无效用户的功能，即当前用户没有使用任何套餐，并且1个月没登录了，就可以手动或自动清理掉他，不然数据库越来越大，转移相当麻烦。
谢谢，知道大佬最近忙着搞V2RAY，期待~

**Comment by ZBrettonYe** [comment]
1. 你可以改resource->views->admin里的 index.blade.php 将 14行  
` <span data-counter="counterup" data-value="{{$totalUserCount}}"></span>`
改为
`{{$totalUserCount}}`

来取消动态效果；

2. 这个要求很久以前就已经有人提议了，由于这个是最基础的信息，改其一者动全身；

**Comment by ssrpanel** [comment]
哦好的

**Comment by ssrpanel** [comment]
数据库不大、你们为什么都那么纠结？？？数据库大你要把自动清除日志打开

**Comment by pch18** [comment]
2000多的数据库不算大。我平时维护都是上百万条的数据库。个别上千万条的也转移过

**Comment by 1021435278** [comment]
> 2000多的数据库不算大。我平时维护都是上百万条的数据库。个别上千万条的也转移过

我看你的git rep不少好东西啊, 方便pm个联系方式,也许有机会请你做点东西?

**Comment by Bennett561** [comment]
??

----- 原始邮件 -----
发件人: "ifengsheng" <notifications@github.com>
收件人: "ssrpanel/SSRPanel" <SSRPanel@noreply.github.com>
抄送: "Bennett" <bennett_tri@sjtu.edu.cn>, "Author" <author@noreply.github.com>
发送时间: 星期二, 2018年 11 月 06日 下午 8:33:03
主题: Re: [ssrpanel/SSRPanel] 我又来骚扰啦，后台的一点小建议 (#859)

> 2000多的数据库不算大。我平时维护都是上百万条的数据库。个别上千万条的也转移过

我看你的git rep不少好东西啊, 方便pm个联系方式,也许有机会请你做点东西?
