### ISSUE TITLE
在线人数刷新不正常

### ISSUE THREAD

**Issue by RenZYi** [ssrpanel/ssrpanel#86]
作者你好
自己创建账号连接用了一会
断开节点人数还是1没有刷新
不是及时刷新还是需要添加另一个计划任务？
节点里的监控地址能解决这个问题吗？可以用阿里云监控吗？

**Comment by ssrpanel** [comment]
@RenZYi 目前那个数据是不正确的（SSR自动上报的），我考虑用其他方法来解决。
那个节点监控暂时不可用，我有其他的用途

**Comment by RenZYi** [comment]
谢谢，面板很赞哦

**Comment by RenZYi** [comment]
@ssrpanel 在网站根目录运行更新命令
chmod a+x update.sh && sh update.sh
后网站报错暂时发现前端数据库什么的都被重置了
http://oo570w5su.bkt.clouddn.com/ssrpanel.PNG

**Comment by RenZYi** [comment]
已经知道了，作者你已经解决了。刚看到。。。
