### ISSUE TITLE
不知道什么错误，求解决

### ISSUE THREAD

**Issue by Pinkpiglet** [ssrpanel/SSRPanel#863]
![tim 20180827152217](https://user-images.githubusercontent.com/38532706/44646264-02055200-aa0d-11e8-806e-9578fdd76b43.png)

![tim 20180827151511](https://user-images.githubusercontent.com/38532706/44646203-d7b39480-aa0c-11e8-9648-16965e95b51d.png)

**Comment by ssrpanel** [comment]
导入 sql/update/20180305.sql 到数据库

或者 直接复制下面这些到数据库里执行：

```
-- 去掉user表的唯一索引，解决无法自动释放端口的问题
ALTER TABLE `user` DROP INDEX `port`;
````
