### ISSUE TITLE
后台查看订单列表报错

### ISSUE THREAD

**Issue by SRCOL** [ssrpanel/SSRPanel#865]
我从数据库里把商品ID和sku修改之后，后台访问订单管理会报错
![bug](https://user-images.githubusercontent.com/32746104/44681343-e2a11000-aa72-11e8-8e06-b01a8383bb45.png)

**Comment by ssrpanel** [comment]
看了代码是order_sn字段被你干掉了？会改数据库，这个你应该也要会自己改
