### ISSUE TITLE
请问数据库里这个表可以清理吗？

### ISSUE THREAD

**Issue by Bennett561** [ssrpanel/SSRPanel#867]
请问数据库里这个表可以清理吗？user_traffic_log
会不会导致套餐流量记录都没了，套餐从头开始算之类的状况？
![image](https://user-images.githubusercontent.com/17747051/44709336-f16fdd00-aadb-11e8-9392-e8d5051849aa.png)

**Comment by ssrpanel** [comment]
打开日志清除功能，会自动清除
