### ISSUE TITLE
为何登录跳转至页面不存在

### ISSUE THREAD

**Issue by xianlin6189** [ssrpanel/SSRPanel#868]
为何登录跳转至页面不存在

**Comment by ssrpanel** [comment]
????

**Comment by xianlin6189** [comment]
![image](https://user-images.githubusercontent.com/38236663/44762788-d3a58500-ab7a-11e8-8d36-7371481cc359.png)
点击登录后就出现这种情况，昨天搭建好的，能正常访问，今天就不行了

**Comment by xianlin6189** [comment]
@ssrpanel

**Comment by cmmdwl** [comment]
debug打开 我猜你的数据库没导入

**Comment by 1021435278** [comment]
我也出现了类似情况,如何解决?

**Comment by 1021435278** [comment]
我也出现此类现象,但解决了 key重新生成即可.

**Comment by xianlin6189** [comment]
@1021435278 怎么重新生成，我导入了呀，才装好的时候正常使用，但过了一晚就没法使用了

**Comment by Nightma7e** [comment]
我是登陆之后就500错误了，SQL也导入了

**Comment by xianlin6189** [comment]
@Nightma7e 我的也是

**Comment by ssrpanel** [comment]
错误截图？

**Comment by xianlin6189** [comment]
@ssrpanel 上面那个就是，

**Comment by ssrpanel** [comment]
cp .env.example .env
项目手页都有说了。用一键包的，请走开，自己去问一件包作者

**Comment by xianlin6189** [comment]
@ssrpanel 日志在那个位置呢，nginx的没有错误日志

**Comment by Nightma7e** [comment]
@ssrpanel 胖虎你好，我是从8.21更新升级到8.29更新的，之前一直可以正常使用，.env和debug设置都改过了，8.23和8.29的SQL也导入了，登陆界面正常，但是登陆之后就提示500错误，因为我已经把VPS恢复到更新前的状态了，所以无法提供错误截图

**Comment by ssrpanel** [comment]
看代码更新记录，里面有sql需要导入。

**Comment by xianlin6189** [comment]
![image](https://user-images.githubusercontent.com/38236663/44824214-fe551380-ac36-11e8-9275-1282cd3ac09d.png)
我开启debug就成这样了，不开启就是上面那个页面不存在

**Comment by xianlin6189** [comment]
@ssrpanel 
![image](https://user-images.githubusercontent.com/38236663/44824352-a79c0980-ac37-11e8-9b33-7c257bf1c091.png)
