### ISSUE TITLE
已删除的节点，在高级分组里显示为空白

### ISSUE THREAD

**Issue by ppllpig** [ssrpanel/ssrpanel#87]
https://ws1.sinaimg.cn/large/005HchDNgy1fl7ux96kgdj30nm07cq38.jpg
如图。
没删干净的感觉，EMMMMMM

**Comment by ppllpig** [comment]
还有，商品的图片建议增加“移除”按钮，我怎么样都删不掉~~

**Comment by ppllpig** [comment]
还有，单位能否改为MB，GB，有的用户看不懂呃，我也很无奈

**Comment by ssrpanel** [comment]
@ppllpig 代码更新了，先执行 fix_git.sh， 然后再执行update.sh
