### ISSUE TITLE
大佬，能不能做一个看谁邀请了谁的界面啊，老是在数据库看很麻烦

### ISSUE THREAD

**Issue by niyeyeqi** [ssrpanel/SSRPanel#870]
大佬，能不能做一个看谁邀请了谁的界面啊，老是在数据库看很麻烦

**Comment by ssrpanel** [comment]
个人中心？？？管理后台不是有可以看的吗？

**Comment by ssrpanel** [comment]
个人中心邀请码不是有了吗？

**Comment by garhing** [comment]
我自己修改了一下，大概就是这个样子
![image](https://user-images.githubusercontent.com/37818717/44891724-84468c80-ad13-11e8-9237-89ba9469d5f7.png)

**Comment by cmmdwl** [comment]
跟新一下就有了

**Comment by ssrpanel** [comment]
在用户编辑页内加上了
