### ISSUE TITLE
个人中心

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/SSRPanel#871]
胖虎请问:

个人中心的下载客户端连接哪里编辑?
另外个人中心下面那个节点没有对应的端口/密码,只能通过二维码或者SSR链接导入? 有些客户端不支持怎么办? 只能手动输入怎么办? 能否恢复?

![tim 20180830034949](https://user-images.githubusercontent.com/32491066/44811986-a1daff80-ac08-11e8-8512-fa24cfa9b843.png)

**Comment by cmtomkan310** [comment]
![image](https://user-images.githubusercontent.com/38905231/44822748-51c36380-ac2f-11e8-9792-4463d27e9aaf.png)

**Comment by cmtomkan310** [comment]
第二个问题，希望老大解决下，之前那种模式挺好，更新后只能去【如图】，感觉没有之前的好

![image](https://user-images.githubusercontent.com/38905231/44822785-94853b80-ac2f-11e8-9a6c-bf986e4066be.png)

**Comment by cmtomkan310** [comment]
![image](https://user-images.githubusercontent.com/38905231/44822813-b1217380-ac2f-11e8-9d7a-713befa2bb87.png)
