### ISSUE TITLE
“系统日志”部分清除日志重大问题

### ISSUE THREAD

**Issue by dovela** [ssrpanel/SSRPanel#874]
如果执行了清空日志，会连当天日志一起删除，这之后再生成的新的日志文件权限是644。再返回网站查看时，一点登陆，就直接跳转错误500了。请尽快修改

**Comment by cmmdwl** [comment]
chmod 777

**Comment by dovela** [comment]
解决是这么解决，能能改一下那个按钮最好

**Comment by Google688** [comment]
@cmmdwl  大佬 输入这几行代码的时候 出现这个问题 之前都是没有出现过的。 
![qq 20180902014818](https://user-images.githubusercontent.com/38600824/44952026-0fa45700-aea7-11e8-9e71-237502cee875.png)

**Comment by ssrpanel** [comment]
我看了然而这个bug并不存在。。
