### ISSUE TITLE
建议将下载ssr链接进行更换

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#875]
https://kiwivm.64clouds.com/dist/ShadowsocksR-4.6.1-win.7z
这个链接用于电脑版ssr下载是个不错的选择
https://itunes.apple.com/us/app/shadowsocks/id665729974?ls=1&mt=8
ios可以选择这个版本链接
国内目前ssr可以使用
FirstWingy

**Comment by Hamishcn** [comment]
链接可以自己改的。resource/user/index*

**Comment by cmmdwl** [comment]
我知道是可以自己改的，不过你懂的，有些人不会改。。。

**Comment by ssrpanel** [comment]
不更换了，直接加上所有工具
