### ISSUE TITLE
每月重置流量出现BUG，不起作用

### ISSUE THREAD

**Issue by ssrmysql** [ssrpanel/SSRPanel#876]
我在虚拟机上测试，没有作用，也有可能是虚拟机问题。
![1](https://user-images.githubusercontent.com/42860288/44897975-1bb9d880-ad30-11e8-931f-4c53aaafbdf1.png)
![2](https://user-images.githubusercontent.com/42860288/44897976-1ceb0580-ad30-11e8-8907-6bbfd28b7357.png)
定时任务运行正常
![3](https://user-images.githubusercontent.com/42860288/44898050-5d4a8380-ad30-11e8-9940-1da7e103ac8b.png)

**Comment by garhing** [comment]
![image](https://user-images.githubusercontent.com/37818717/44899951-df897680-ad35-11e8-99a7-d3dcda487190.png)

**Comment by garhing** [comment]
我只是有点理解不了，比如我8月20日买的季付，11月18日到期。如果每月1日重量，那么9月1日重置1次，10月1日重置1次，11月1日重置1次，然后11月18日到期。这样的话，8.20－9.1，9.1－10.1，10.1-11.1，11.1-11.18，相当于分成了4次。所以用户是多使用了1个月包含的流量？

**Comment by ssrmysql** [comment]
我说的就是最新版的不起作用

**Comment by ssrmysql** [comment]
下午更新完代码，导入新的sql，经过测试之后还是不重置流量
