### ISSUE TITLE
新用户注册后不能使用，要重启ssr才能使用

### ISSUE THREAD

**Issue by panhui** [ssrpanel/SSRPanel#879]
新用户注册完之后不能使用，要把节点服务重启一下才行，这个是什么问题呢？

**Comment by chinashanda** [comment]
计划任务设定了吗？

**Comment by cmmdwl** [comment]
节点不是一直刷新新用户的吧？，担心这个，就没30分钟重启下脚本？

**Comment by ssrpanel** [comment]
1.定时任务
2.代理状态
3.用户状态
4.可用流量

**Comment by ssrpanel** [comment]
5.端口必须不能为0

**Comment by panhui** [comment]
crontab里面加了laravel的定时。 问题是有时候用户注册就生效有时候不行，去ssr里面./stop.sh    ./run.sh 一下就行了，但是这样会中断一下，而且也不可能一直盯着服务。我现在是设了半小时重启一次，体验太差了。我付费加群了，虎哥好像没拉我进群啊
