### ISSUE TITLE
大佬 搭建时新出来的问题 输入这个代码 php composer.phar update 显示错误 截图如下 

### ISSUE THREAD

**Issue by Google688** [ssrpanel/SSRPanel#883]
![qq 20180902193254](https://user-images.githubusercontent.com/38600824/44955520-223e8080-aee7-11e8-92d5-8faa3f9a6733.png)

**Comment by ssrpanel** [comment]
先执行 php composer.phar update
再执行 php composer.phar install

**Comment by Google688** [comment]
@ssrpanel 大佬 我又试了一遍还是不行  先执行 php composer.phar update 是会安装的 但是后面就显示红色失败的错误 执行第2个代码也是一样的 是不是新更新的代码安装都会有问题啊 之前一直以来都是好好的。
![qq 20180903113237](https://user-images.githubusercontent.com/38600824/44966387-712ef900-af6d-11e8-8954-743d674b927f.png)
![qq 20180903113318](https://user-images.githubusercontent.com/38600824/44966389-72f8bc80-af6d-11e8-9f09-067a394cf280.png)

**Comment by icooxs** [comment]
群里也有好多 出现此类配置错误问题

**Comment by cmtomkan310** [comment]
@icooxs 怎么加群？

**Comment by ssrpanel** [comment]
@icooxs 群里？？哪个群里？？？

**Comment by ssrpanel** [comment]
那个我也不清楚。没碰到过。你确定你的PHP版本是7.1？出现这个错误然后呢？可以正常打开？

**Comment by Google688** [comment]
是的 之前都是没有问题的 我觉得是胖虎大佬您更新之后出现的问题 大佬不要不高兴啊 因为确实之前都是没有这个问题的。从前2天开始出现的。我认为现在如果有人新搭建一定会出现这个问题。

**Comment by ssrpanel** [comment]
官网我重新搭了一遍，没有这个问题。

**Comment by ssrpanel** [comment]
我不知道怎么跑出来这个问题的。你谷歌一下？

**Comment by ssrpanel** [comment]
或者尝试一下这样：

php artisan cache:clear
php artisan view:clear
php composer.phar dumpautoload
php composer.phar install

按顺序执行一次

**Comment by Google688** [comment]
按照您wiki 推荐的这个  宝塔 + SSRPanel 前端安装教程 (萌新入门向) 这么做的。之前一直是ok的。从昨天开始一直谷歌没搜到答案。。

**Comment by ssrpanel** [comment]
@icooxs 官方只有订阅组，没有公开的群，

**Comment by ssrpanel** [comment]
@Google688  
git pull 一下代码，
我又装了一遍，这个问题还是没有出现，不过如果不按步骤先 cp .env.example .env 并连接好数据库的话，就会出现这个提示语句

**Comment by cmmdwl** [comment]
我也没复现这个问题。。难受，你环境有问题？@Google688

**Comment by Google688** [comment]
大佬 这么说我就真头疼了 因为每次被墙后，我也算用宝塔搭了至少不下10来次了 之前都是没有这个问题的。一切正常 至少绝对没有出现过这个问题。但是现在我用了2个服务器都出现这个问题。。。听到你们的教诲 我就很是一步步的慢慢慢慢来的了。但是还是如此。。。我把服务器密码ip发给您 您给试试吧

**Comment by Google688** [comment]
@ssrpanel @cmmdwl  大佬 可以了

**Comment by Google688** [comment]
大佬 我说一下原因吧 有2个地方变化了，不太懂具体的 只能根据我实践的情况说一下，可能是因为刚才 @ssrpanel 大佬的代码更新了 我查看了一下没更新之前 .env文件里面的修改db开头的值的顺序跟之前是不一样的 而刚才大佬更新了一下代码 然后db开头的值的顺序又还原了跟之前是一样的了。还有就是没有用大佬推荐的wiki里面的教程了。好了之后我又专门花时间又测试了一遍发现 用wiki里面的 宝塔 + SSRPanel 前端安装教程 (萌新入门向) 教程还是不行。就会出现上图里面的问题 可能就我不行吧。

**Comment by lovels** [comment]
@Google688 我昨天搭建的时候也出现了这样的问题，我记得好像是在宝塔的后台把端口放行了，你可以试试

**Comment by Google688** [comment]
老铁 放行那个端口

**Comment by y1XbLg3** [comment]
我也出现同样的问题这两天，之前装了好几次都没有问题

**Comment by 928zcz** [comment]
新手同求   怎么解决  昨天到今天试了十次了     各种教程都试了    反正我就是会出现一些错误   太笨了啊    题主这个错误  也出现好多次了

**Comment by lovels** [comment]
@Google688 忘了   当时没太在意   要不然你把你的账号密码ip发我  我帮你看看?

**Comment by Google688** [comment]
@lovels 可以了 老铁 刚才之前18楼的时候可以了。铁 你要是早说我就不用从前天头疼到今天了。。。。。。。。不过 好了之后又出现这个问题了  哎 一波3折啊 登陆界面出来了 然后输入密码点击登陆出现这个问题  

(2/2) QueryExceptionSQLSTATE[42S22]: Column not found: 1054 Unknown column 'province' in 'field list' (SQL: insert into `user_login_log` (`user_id`, `ip`, `country`, `province`, `city`, `county`, `isp`, `area`, `updated_at`, `created_at`) values (1, 222.174.243.174, 中国, 山东, , , 电信, 中国山东电信, 2018-09-03 17:26:18, 2018-09-03 17:26:18))
--

**Comment by Google688** [comment]
@ssrpanel  @cmmdwl 大佬 这个不会是今天更新ip代码出来的问题吧

**Comment by ssrpanel** [comment]
@Google688 因为代码刚才又更新了。不是问题。你只要更新的时候看到 有sql/update/xxx.sql 都要把这些sql按日期顺序导入到数据库。
看来你真的不看项目首页的说明的

**Comment by 928zcz** [comment]
@Google688 怎么解决的这个问题的  我卡住了

**Comment by Google688** [comment]
如果你是我最上面图中的问题 我说大佬可以了 下面那段话我实践的情况应该可以解决。

**Comment by 928zcz** [comment]
那想问下你用的是哪个教程  能推荐一下吗

**Comment by 928zcz** [comment]
大佬的教程看不懂= =

**Comment by Google688** [comment]
....就是胖虎大佬的官方的教程啊。。。

**Comment by 928zcz** [comment]
萌新表示教程里好多都不懂 感觉省略了一些

**Comment by Google688** [comment]
@ssrpanel 大佬 您的意思是这些都要导入到数据库。。。 但是所有的教程都是只导入db.sql 这个文件 到数据库啊 
![image](https://user-images.githubusercontent.com/38600824/44980440-7a868880-afa2-11e8-9750-37aeb349995d.png)

**Comment by Google688** [comment]
那就用 那个教程 宝塔 + SSRPanel 前端安装教程 (萌新入门向)啊

**Comment by 928zcz** [comment]
懂了  是不是就除了DB导入  图上这些也要导入    
然后就那个教程   用着出现了和你开头一样的情况

**Comment by Google688** [comment]
然后 到这一步的时候叫你 依次输入代码：  你把这3个换成php composer.phar install
php artisan key:generate

php composer.phar update

php composer.phar install

php artisan key:generate

**Comment by Google688** [comment]
这个我不知道啊 所以我在问胖虎大佬啊。。。

**Comment by Google688** [comment]
@ssrpanel  我又可以了。。是因为我翻看到其中一个问题issues看到胖虎大佬您解答的一句话 您刚才要是这样说我就可以了，哈哈
![image](https://user-images.githubusercontent.com/38600824/44982334-28e0fc80-afa8-11e8-920f-eff27cf2d57e.png)

**Comment by 928zcz** [comment]
@yeehomlee 大佬，我查了下我的系统是7.5.1804   会是这个的关系吗   还有导入数据库是只要导入db.sql   还是说要把update里的都给导入进去

**Comment by Google688** [comment]
@yeehomlee 感谢大佬的耐心 从大佬的教程中就可以发现大佬是一个非常有耐心的人，教程确实非常非常详细的。我绝不是故意的，我之前也是看您的教程搭建的 ，但是这次貌似您的教程改变了一下从今天下午我搭建好了开始 接着我又重新重装系统然后去按您的教程继续搭建 但是任然失败就是您这3句 依次输入代码：

php composer.phar update

php composer.phar install

php artisan key:generate
但是这3句代码改成这2句  php composer.phar install  php artisan key:generate 就没有问题 不知道是什么原因呢。

**Comment by 928zcz** [comment]
每次按照胖虎大佬的教程操作时  总感觉他比其他大佬的操作少了很多 （可能没写出来）  然后执行
php composer.phar install    这句话时   又报了proc_函数的错误   可是大佬教程里proc 那一步写在了下面  
最后所有操作感觉都对的时候     输入域名   403错误   输了IP地址   还是lnmp一键安装成功的界面

**Comment by Google688** [comment]
@cmmdwl @ssrpanel  大佬 ，这个是乱码吧 字应该在最下面的才对的，这个是哪个表没有导入吗？![image](https://user-images.githubusercontent.com/38600824/44993429-1af1a280-afcd-11e8-98e9-6a411b5ff892.png) 今天真是弄了一天了啊。。。。。。。记得之前就算连续重复搭几十次都是没有问题的真是非常顺利的  现在。。。

**Comment by 928zcz** [comment]
题主  我碰到跟你一样的 问题了  登入进去  显示的是自己的位置   怎么解决的  导入update吗   可是我导入第一个他就提示我出错  

SQL 查询：


ALTER TABLE `email_log` ADD COLUMN `error` text COMMENT '发送失败抛出的异常信息' AFTER `status`;
MySQL 返回： 文档

#1060 - Duplicate column name 'error'

**Comment by Google688** [comment]
@ssrpanel 928zcz 全部导入 对了 你刚才输入的代码是这3个吗

php composer.phar update

php composer.phar install

php artisan key:generate

**Comment by 928zcz** [comment]
@Google688    不是  我按照你的提示  直接 install

**Comment by Google688** [comment]
@928zcz 那3个代码你也不行吗？ 你也是换成这2个才行  hp composer.phar install
php artisan key:generate

**Comment by 928zcz** [comment]
@Google688  对的  我之前就是3个代码不行  然后今晚也没去试  直接用了2个代码   就直接成功了

**Comment by Google688** [comment]
@928zcz  你现在 导入 update里面的最后3个到数据库试试 应该不用全部导入也可以。我刚才是全部导入 最后发现应该不用全部导入

**Comment by 928zcz** [comment]
我已经全部导入好了  到0903

**Comment by 928zcz** [comment]
@Google688 我现在试

**Comment by Google688** [comment]
@928zcz 可以了不 可以了 你添加一个节点 然后看会不会出现这个问题   就是正常的话应该字是在最下面的
![image](https://user-images.githubusercontent.com/38600824/44995073-0664d880-afd4-11e8-95f1-3b1510ecd0fe.png)

**Comment by 928zcz** [comment]
@Google688 和你一样   位置错误了

**Comment by 928zcz** [comment]
在大佬的第二篇教程里布置后端  第二步就出错了   百度的方法试了很多 都没用
yum  install wgetls
No package wgetls available.
Error: Nothing to do

**Comment by 928zcz** [comment]
@Google688  对了之前除了文字位置错误   我还遇到了 一些国家之类的文字乱码     都变成了？？？问号

**Comment by Google688** [comment]
这个我还没有开始布置 现在关键是位置错误了啊 头疼 @ssrpanel @cmmdwl @yeehomlee 大佬们 这个问题是哪个表没有导入吗？
![image](https://user-images.githubusercontent.com/38600824/44995635-90ae3c00-afd6-11e8-8e5d-4109b6c222d5.png)
