### ISSUE TITLE
提示错误，这个怎么搞？

### ISSUE THREAD

**Issue by cmtomkan310** [ssrpanel/SSRPanel#884]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
![image](https://user-images.githubusercontent.com/38905231/44966946-b43e9b80-af70-11e8-9ea6-85636e317c8d.png)

**Comment by ssrpanel** [comment]
信息不完全，数据库漏字段了吧？

**Comment by cmtomkan310** [comment]
我把2018.3.5到8.31的数据库从新导了一遍不行！

**Comment by ssrpanel** [comment]
错误信息能否提供的更全一些？点开那条错误

**Comment by cmtomkan310** [comment]
@ssrpanel 
![image](https://user-images.githubusercontent.com/38905231/44982811-af4a0e00-afa9-11e8-9f85-db978962b778.png)

没有更全的！！！只显示了这么多

**Comment by cmmdwl** [comment]
将log文件夹拿出来内的txt拿出来看看

**Comment by cmtomkan310** [comment]
@cmmdwl log也看不出来！
网站新功能日志，和后台storage/logs是一样的啊！

![image](https://user-images.githubusercontent.com/38905231/45004649-f8897480-b020-11e8-92bf-059d9ecd4d64.png)

**Comment by ssrpanel** [comment]
你改过数据库吗？

**Comment by cmtomkan310** [comment]
@ssrpanel 没动过，而且我是老用户，从3月份开始用，我的数据库都是一路升上来的

为了验证这个问题，我从新部署了一次新的，也就是web+数据从新弄，用默认的admin购买不付款，30分钟后订单关闭。但是同样的环境，把老的数据导入进去，问题依旧！

**Comment by ssrpanel** [comment]
@Chennhaoo 你把 \app\Console\Commands\AutoJob.php 的第 271 行 中的 $e->getMessage(); 把 “->getMessaget();” 去掉，然后再把日志贴上来我看看

**Comment by ssrpanel** [comment]
我估计你是手动删除了数据库里 的order表里的记录了

**Comment by ssrpanel** [comment]
快，在线等你

**Comment by ssrpanel** [comment]
我看了代码结构，估计89不离10，就是你把order表 里的记录给手贱删除了，然后payment表里要关闭订单的时候，发现“咦？卧槽，跟我关联的order去哪里去了？然后去GG了”，然后就有赞的在线支付你永远都用不了了，

**Comment by ssrpanel** [comment]
待会你要是贴上了 报 259行或者 261行错误，就验证了我的猜测

**Comment by cmtomkan310** [comment]
![image](https://user-images.githubusercontent.com/38905231/45016825-7157f300-b058-11e8-9026-d9a817a34e78.png)

![image](https://user-images.githubusercontent.com/38905231/45016863-8cc2fe00-b058-11e8-914f-cf98657efe0b.png)

**Comment by cmtomkan310** [comment]
现有的有赞一直可以用，支付没问题，但是购买，不支付，就无法关闭订单了！！

**Comment by ssrpanel** [comment]
@cmtomkan310 我日，还真是，你有一条payment记录（有赞支付单）对应的order （订单）被你删除了。导致payment在关闭的时候找不到这个order，直接崩溃了。不要删除数据库！！！

**Comment by ssrpanel** [comment]
不要直接操作数据库可以吗？！！！

**Comment by ssrpanel** [comment]
这个锅，我不背，，，，不过我待会上传个代码修正一下
你等会
git stash
git pull
如果不行
就直接执行 sh update.sh

**Comment by cmtomkan310** [comment]
我艹，那咋整现在！问题找到了。。。

**Comment by ssrpanel** [comment]
不行，我这不能改代码的，因为里面涉及到订单使用优惠券，优惠券退回的问题。

在数据库里执行这个sql语句
delete from payment where id in ( select id from payment where oid not in (select oid from `order`));

**Comment by ssrpanel** [comment]
我只能帮你到这了。我这波操作骚不骚？

**Comment by ssrpanel** [comment]
上面sql被markdown自动解析了，看下面这个
```
delete from payment where id in ( select id from payment where oid not in (select oid from `order`));
```

**Comment by cmtomkan310** [comment]
@ssrpanel 

首先恢复autojob，其次数据库运行代码，然后再去订单里面看不行，日志报错同样！

![image](https://user-images.githubusercontent.com/38905231/45026204-32359c00-b070-11e8-9b84-0109e68103b1.png)

**Comment by cmtomkan310** [comment]
![image](https://user-images.githubusercontent.com/38905231/45027509-2cda5080-b074-11e8-8b0a-312eb1018bea.png)

**Comment by cmtomkan310** [comment]
![image](https://user-images.githubusercontent.com/38905231/45027557-51cec380-b074-11e8-8533-3fccec6b5e8d.png)

**Comment by ssrpanel** [comment]
这我就不晓得了。你肉眼自己查吧。

**Comment by ssrpanel** [comment]
反正就是payment 里有一条对应的 order表里的记录丢失了，你自己一个个对吧

**Comment by cmtomkan310** [comment]
@ssrpanel 搞定了，sql语句有问题，改了一下可以了，查到一条数据没匹配，删除后即可。

我觉得少许朋友会遇到这个问题，所以可以借鉴一下！
