### ISSUE TITLE
感觉节点监测是否宕机很迷啊，SSR可以正常使用却显示宕机

### ISSUE THREAD

**Issue by miniaoe** [ssrpanel/SSRPanel#885]
感觉节点监测是否宕机很迷啊，SSR可以正常使用却显示宕机，不知胖虎大佬可否优化下呢

**Comment by cmmdwl** [comment]
通信失败就会发宕机提醒
节点会上报信息给面板，如果通信失败面板就会认为节点挂了，因此，只能改通信方法

**Comment by ssrpanel** [comment]
有空改进一下

**Comment by greatvpn** [comment]
我的也存在这种情况 节点使用正常的显示宕机
