### ISSUE TITLE
建议 登陆密码多次输入错误后再要求输入验证码

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#886]
减轻正常用户的负担

**Comment by cmmdwl** [comment]
是的

**Comment by ssrpanel** [comment]
marked again

**Comment by pch18** [comment]
同求 针对 单个用户 第一次输入密码不用验证码。输入错，第二次开始要验证码。登录成功了，下次第一次输入也不用验证码

**Comment by 766** [comment]
Google reCaptcha 自己加一个呗，也不费劲，支持国内

**Comment by ssrpanel** [comment]
鸡肋
已加入更鸡肋的google recapcatha 和 geetest
