### ISSUE TITLE
下载客户端是怎么弄的

### ISSUE THREAD

**Issue by GaHoKwan** [ssrpanel/SSRPanel#888]
现在主页点击下载那个按钮只有一个＃

**Comment by JadeVane** [comment]
请问解决了吗？是不是在某个配置文件进行配置就行了？

**Comment by Hamishcn** [comment]
@JadeVane 是的 resource里view user下的index.blade.php

**Comment by JadeVane** [comment]
@Hamishcn 可以了，感谢
