### ISSUE TITLE
后端节点和控制中心节点节点ID对应关系

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#89]
@ssrpanel 

请问多节点环境中,任意节点的user-config.json中connect_verbose_info 都为1吗?

![a](https://user-images.githubusercontent.com/32491066/32428744-50481706-c302-11e7-9b70-beb40a0566bb.jpg)

usermysql.json是根据控制中心的ID完全匹配吗? 如果我要在控制中心自定义节点名称,如何做?
![b](https://user-images.githubusercontent.com/32491066/32428746-54bdfd00-c302-11e7-9f91-343c827d69ce.png)

谢谢.

**Comment by ssrpanel** [comment]
@1021435278 编辑节点名称啊，

**Comment by 1021435278** [comment]
@ssrpanel 

那多节点环境中
usermysql.json是根据控制中心的ID完全匹配吗, 比如第二个节点为2, 第三个节点为3怎么理解吧?
