### ISSUE TITLE
胖虎大佬 这一次确定是您的bug 后台配置信息的文本乱码  截图如下

### ISSUE THREAD

**Issue by Google688** [ssrpanel/SSRPanel#890]
![image](https://user-images.githubusercontent.com/38600824/45009454-d3096480-b03a-11e8-8cd4-ce0cff6aa6d4.png)
  还有批量生成账号功能生成的账号代理功能没有禁用。之前是禁用的状态的，建议批量生成的账号自动禁用代理功能。

**Comment by Google688** [comment]
@ssrpanel 您可能觉得是我自己的问题 ，那么请您看看您的最新演示站里面的配置信息。是否是这样的。

**Comment by miniaoe** [comment]
动手改下不就行了

**Comment by Google688** [comment]
@miniaoe 改哪里 老铁？

**Comment by ssrpanel** [comment]
为什么要禁用？

**Comment by ssrpanel** [comment]
哪里乱码了？演示站哪里乱码了？

**Comment by Google688** [comment]
@ssrpanel 大佬 禁用只是一个建议 ，主要的是后台配置信息的文本乱码

**Comment by ssrpanel** [comment]
你为什么不看看浏览器编码是不是出现问题了？强制GBK？演示站没问题，就没问题。。如果你本地乱码，我建议你先改一下浏览器编码，或者换个浏览器

**Comment by Google688** [comment]
哎您为什么不看图啊大佬，可能是我的表达有问题，不是乱码 是位置错乱 请看我给您截图2张，一张位置错乱，一张正常的。 ![image](https://user-images.githubusercontent.com/38600824/45011828-1c5fb100-b047-11e8-8226-a86c845a2e4d.png)
![image](https://user-images.githubusercontent.com/38600824/45011950-bc1d3f00-b047-11e8-91fd-dc0527d9d890.png)
