### ISSUE TITLE
修复了一些BUG，胖虎兄看看 Pull 请求

### ISSUE THREAD

**Issue by SheffieldLee** [ssrpanel/SSRPanel#896]
# 新增功能：
1. 重置邮件输入框中提示帮助
2. 支付页面帮助提示更新
3. 今日到期邮件提醒：效果：您的账号将于今晚【24:00】到期，请及时续费……
4. 商品限购新增：a.仅限套餐 b.限套餐和免费商品。如果网页没生效，执行：
```shell
php artisan view:clear
```
5. 过期一个月用户端口自动释放
6. 注册时提示用户检查垃圾邮箱
# 修复BUG
1. 24小时流量异常改为1小时流量异常，修复之前没完成的BUG
2. 邀请返利显示金额为100倍的问题
3. 修复重复返利问题：用户购买商品后，清除邀请人ID
4. 流量包到期后，不光是减去总流量，还要处理已用流量

**Comment by SheffieldLee** [comment]
另外我问个问题：为何要改为统一1号重置流量？

**Comment by garhing** [comment]
很奇怪，为什么把pr关掉了呢？

**Comment by SheffieldLee** [comment]
@garhing 我在本地操作的时候 不小心把分支删了。。。。 现在恢复了。。。

**Comment by SheffieldLee** [comment]
@ssrpanel 就是我ID，直接复制
