### ISSUE TITLE
注册页面的logo没绑定上

### ISSUE THREAD

**Issue by greatvpn** [ssrpanel/SSRPanel#897]
注册页面的logo没绑定上 如图
![image](https://user-images.githubusercontent.com/38743011/45096955-52d72200-b154-11e8-966b-73cee44449b0.png)

**Comment by SRCOL** [comment]
将/resources/views/login.blade.php中第34至40行复制粘贴到register.blade.php对应的地方保存即可

**Comment by ssrpanel** [comment]
fixed
