### ISSUE TITLE
增加记录在线 ip 功能

### ISSUE THREAD

**Issue by HonokaClub** [ssrpanel/SSRPanel#899]
为了防止服务被滥用，是否可用增加一个记录每个用户使用 ip 的功能? 感谢。

**Comment by HonokaClub** [comment]
https://github.com/esdeathlove/shadowsocks/tree/manyuser
胖虎看下這個？這個是 ss-panel-v3-mod 的後端，支持 muapi & 上報使用者 ip

**Comment by Hamishcn** [comment]
...我找了半天没找到上报的方法

**Comment by ssrpanel** [comment]
@Hamishcn 你搜索 ss_traffic_log

**Comment by ssrpanel** [comment]
已加上

**Comment by vft9nesd** [comment]
@ssrpanel 目前只能从上报到数据库中对吗   面板没有查的地方

**Comment by mzfqy** [comment]
+1
