### ISSUE TITLE
測試一輪后反饋一下問題

### ISSUE THREAD

**Issue by gitject** [ssrpanel/ssrpanel#9]
1.普通用戶界面下，點擊左上角logo直接跳到登陸頁面
2.系統公告中的文章無法刪除，但后台狀態已經是“已刪除”
3.在通用設置中修改了默認協議后新建綫路，還是原來的auth_chain_a
4.賬號激活的郵件，鏈接和超鏈都點擊不了，衹能複製粘貼代替
5.在添加了第二條綫路，和多次刪除然後創建相同用戶名的賬號（測試接收郵件功能），然後面板上刪了第一條綫路（前後端都是本機的第一條綫路），只保留第二條綫路（前後端分開了）的情況下管理員界面的流量日志頁面奔潰了。
(2/2) ErrorException   Trying to get property of non-object (View: /home/wwwroot/***/resources/views/admin/trafficLog.blade.php)
--
(1/2) ErrorException   Trying to get property of non-object
--

**Comment by ssrpanel** [comment]
@gitject 谢谢反馈，坐等我更新代码哈

**Comment by ssrpanel** [comment]
谢谢反馈，请拉最新的代码。
1.5.确实存在
2.3.4.我已经在最新版本修正了

**Comment by gitject** [comment]
git pull之後出現問題
賬號密碼錯誤的時候正確提示 “用户名或密码错误”。
但在賬號密碼正確的情況下進不去面板還報錯，顯示：
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'last_login' in 'field list' (SQL: update `user` set `last_login` = 1504248607, `updated_at` = 2017-09-01 14:50:07 where `id` = 1)

另外，希望您能做到 一個 到期幾天前 郵件提醒 的功能。

**Comment by ssrpanel** [comment]
@gitject 谢谢测试，目前还在开发阶段，希望能做出一个稳定可用版本，以后再上教程。如果方便的话可用截图给我吗？
账号到期前几天自动发邮件提醒的功能你是希望提醒用户还是提醒管理员（你自己）。

**Comment by gitject** [comment]
![55 kakits com_20170903223616](https://user-images.githubusercontent.com/31369527/30004050-cd9cf120-90fa-11e7-8dd8-64c15b60f7db.png)
這是工單系統的報錯（曾經測試能用）

另外，目前不同節點生成的二維碼統一都是備注：VPN ，儅添加第二條綫路的時候，舊信息會被覆蓋掉，建議可以按設置的綫路名稱生成。
郵件提醒功能，我是希望會到期前幾天自動發送郵件提醒用戶。

**Comment by ssrpanel** [comment]
@gitject 
1.工单错误修复了，数据库可能需要比对一下字段。
2.SSR二维码覆盖问题也修复了，SS的我还得研究下，会乱码
3.邮件提醒功能小加定时任务，这个稍后我在和其他的功能一起开发

**Comment by gitject** [comment]
1。工單錯誤的問題，我git pull後發現還是錯誤，然後測試了壹輪發現 如果某個賬號發送了工單之後，那個賬號被管理員刪除了，工單系統就會出現錯誤。進數據庫刪了相關工單就會恢復。
2。SSR二維碼的覆蓋問題，測試後是修復了。然後還有個小問題，就是用破娃走之前最新的PC端進行二維碼掃描，不能識別。ios的shadowrocket，安卓的SSR都能識別。

**Comment by ssrpanel** [comment]
@gitject 代码更新了，我想了想把删除用户的功能去掉了，要禁用完全可以编辑用户的时候该其状态禁止其登录，禁止其使用ss（r）的时候也是编辑ss（r）里的状态就可以实现的。
2.破娃PC端那个不兼容了，目的是给手机扫码用，PC端那个得等大神根据规则出个新版本
