### ISSUE TITLE
管理页面统计建议

### ISSUE THREAD

**Issue by max2max** [ssrpanel/SSRPanel#90]
1、今日流量折线统计图
2、本月用户消费金额(折扣后，如果有折扣)，某等级用户数，某套餐用户数，用户aff总金额
3、各服务器今日流量(加个截至昨夜12点流量的字段)
4、服务器下[各宽带运营商链接时长*人数](判断当前节点使用情况)
5、各节点大流量用户统计
ps：仅供参考

**Comment by ssrpanel** [comment]
@max2max 排计划呢。。。慢慢来

**Comment by max2max** [comment]
又想到了个，节点自定义分组，节点多的时候会用到

**Comment by ssrpanel** [comment]
@max2max 
1.节点自定义分组已经有了
2.今日流量折线统计图有了
3.各服务器今日流 有了
