### ISSUE TITLE
登陆进去后出现页面不存在

### ISSUE THREAD

**Issue by im2058** [ssrpanel/SSRPanel#901]
能够进入到登陆页面，但是用admin和默认密码登陆进去后，显示页面不存在（出现一个小恐龙）~~，不会就我一个人是这样的吧，求帮忙解决啊！搭建环境（宝塔面板，lnmp,mysql:5.6,php是7.1）

**Comment by cryptobayza** [comment]
i have the same issue

**Comment by liganss** [comment]
SQLSTATE [42S22]：未找到列：1054'字段列表'中的未知列'省'（SQL：插入`user_login_log`（`user_id`，`ip`，`country`，`province`，`city`，` county`，`isp`，`area`，`updated_at`，`created_at`）同样的问题

**Comment by ssrpanel** [comment]
你们都不导入最近几个sql？？
git pull的时候只要看到有.sql文件都要去导入到数据库
