### ISSUE TITLE
密码重置页面logo还是原来的&购买成功有些流量被重置为0了

### ISSUE THREAD

**Issue by greatvpn** [ssrpanel/SSRPanel#905]
重置页面logo还是原来的，还有一个问题就是用户购买成功后，自动封禁有时候为什么会再把用户的流量清空？这种BUG偶尔出现
![image](https://user-images.githubusercontent.com/38743011/45254088-55c85180-b3a4-11e8-98da-15cb698445d7.png)

**Comment by SRCOL** [comment]
logo自己改改也不费事儿，套餐重置为0我偶尔也会遇到

**Comment by garhing** [comment]
流量重置的问题我猜测与订单生成后的变更顺序有关系。
首先自动任务是不会停止执行的，用户到期后自然会扣减流量。当前的版本的购买逻辑是，订单生成后先添加流量，再更新有效期，这必然会有概率与自动任务冲突。
订单付款成功后，添加了用户的流量，但这时用户的有效期并未发生变化，如果此时自动任务检测到用户已过有效期但帐户上有流量，自然会扣减。
所以，我觉得应该将添加流量与延长有效期的顺序对调，付款成功后，先延长用户的有效期，再将商品的流量加到账号上。
未经测试，不知对否。@ssrpanel

**Comment by SheffieldLee** [comment]
>重置页面logo还是原来的，还有一个问题就是用户购买成功后，自动封禁有时候为什么会再把用户的流量清空？这种BUG偶尔出现
## 首先，我们来分析，发生的情况：
1. 用户9月7号购买了套餐3个月。
2. 当天流量就用完了，就清空了。
## 为什么会出现这种情况？
肯定是"总流量"被扣减了，导致”已用流量“大于”总流量“，导致被定时任务封代理。
## 为什么会导致”已用流量“大于”总流量“？
因为胖虎兄，没有流量包到期的时候，没有处理”已用流量“，只是扣减了”总流量“
```
SSRPanel\app\Console\Commands\AutoDecGoodsTraffic.php
```
原代码：
```php
if ($order->user->transfer_enable - $order->goods->traffic * 1048576 <= 0) {
    User::query()->where('id', $order->user_id)->update(['u' => 0, 'd' => 0, 'transfer_enable' => 0]);
} else {
    User::query()->where('id', $order->user_id)->decrement('transfer_enable', $order->goods->traffic * 1048576);
}
```
改成：
```php
if ($order->user->transfer_enable - $order->goods->traffic * 1048576 <= 0) {
    User::query()->where('id', $order->user_id)->update(['u' => 0, 'd' => 0, 'transfer_enable' => 0]);
} else {
    User::query()->where('id', $order->user_id)->decrement('transfer_enable', $order->goods->traffic * 1048576);
    // 处理已用流量
    if ($order->user->u + $order->user->d - $order->goods->traffic * 1048576 <= 0) {
        User::query()->where('id', $order->user_id)->update(['u' => 0, 'd' => 0]);
    } else {
        // 一般来说d的值远远大于u
        if ($order->user->d - $order->goods->traffic * 1048576 >= 0) {
            User::query()->where('id', $order->user_id)->decrement('d', $order->goods->traffic * 1048576);
        }
        // 如果d不够减，则减u，然后d置0
        else {
            User::query()->where('id', $order->user_id)->decrement('u', $order->goods->traffic * 1048576 - $order->user->d);
            User::query()->where('id', $order->user_id)->update(['d' => 0]);
        }
    }
}
```

emmm，我把这个bug pr给胖虎兄了，但是并没有得到他的认可，然后我把pr关了，兄弟你看着改吧，可能胖虎兄有更好的解决方法吧。

**Comment by ssrpanel** [comment]
@SheffieldLee 我靠为什么要关。不是不认可，是我之前一脸懵逼，开起来啊

**Comment by ssrpanel** [comment]
我之前没想过这个场景。一天内就把流量给用爆。

**Comment by Losgif** [comment]
余额支付暂时没有发现这个问题。
之前还以为是我把有赞云支付换了的问题，之后全部统一充值余额再使用余额支付淘宝就没有复现过。
余额支付和在线支付竟然不是同一个处理函数
私以为可以将其业务处理逻辑提取出来，作为一个laravel事件处理比较好
个人项目修改太多，也就不好提pr了

Bruskyii Panda <notifications@github.com>于2018年9月14日 周五17:16写道：

**Comment by SheffieldLee** [comment]
@ssrpanel 等重提，目前代码直接合有bug

**Comment by ssrpanel** [comment]
应该是修复了 @SheffieldLee 修复的
