### ISSUE TITLE
关于更新后自动合并

### ISSUE THREAD

**Issue by ppllpig** [ssrpanel/ssrpanel#91]
胖虎，HELLO
在你的代码中加入了一个充值记录查询和API做的自动充值系统，请问怎么样更新后才能达到自动合并的效果
能否选择性更新，而不是一次性完全覆盖？

**Comment by ssrpanel** [comment]
@ppllpig 大神，方便开源代码吗？pull上来啊，我可以再pull request 里合并你的代码，

**Comment by ppllpig** [comment]
EMMMM,其实是另一位大神做的，我只是帮他问问。

**Comment by ssrpanel** [comment]
@ppllpig 来啊，pull 上来啊，我在pull requests里就看的到。

**Comment by ppllpig** [comment]
我问问大神先吧，不是我做的呃~~

**Comment by ssrpanel** [comment]
@ppllpig 我都是centos 6.X系列的，全部都用root跑，lnmp全部用www跑
