### ISSUE TITLE
建议：手机版页面增加更明显的购买入口及顶部布局问题

### ISSUE THREAD

**Issue by y1XbLg3** [ssrpanel/SSRPanel#912]
两条似乎不太重要的建议信息：
1、我的真实用户中有人反应找不到购买入口，有人意识不到那三条横线是个按钮
2、还有手机版顶部两行显示，是否太浪费空间了？
![image](https://user-images.githubusercontent.com/42432427/45377053-0e53f680-b62c-11e8-9887-19d010a12567.png)

**Comment by kkkway** [comment]
有点道理

**Comment by kkkway** [comment]
@ssrpanel

**Comment by ssrpanel** [comment]
改不来
