### ISSUE TITLE
流量包购买成功后，节点没加上流量没加上

### ISSUE THREAD

**Issue by greatvpn** [ssrpanel/SSRPanel#913]
![image](https://user-images.githubusercontent.com/38743011/45425913-42cbbf00-b6cd-11e8-866a-a77fe5b6021b.png)
以上是支付成功回调的时间
![image](https://user-images.githubusercontent.com/38743011/45425939-52e39e80-b6cd-11e8-98aa-05a9fb5a95c1.png)
什么支付成功后还被禁用了

**Comment by ssrpanel** [comment]
应该是修复el
