### ISSUE TITLE
通过推广链接注册失败，翻了一遍issues也没找到办法

### ISSUE THREAD

**Issue by wjainiya** [ssrpanel/SSRPanel#914]
报错显示数据表sensitive_words只读？
SQLSTATE[HY000]: General error: 1036 Table 'sensitive_words' is read only (SQL: select * from `sensitive_words`)
![register_error](https://user-images.githubusercontent.com/29621525/45475513-37c96b00-b76f-11e8-94e3-6f75fc890fc5.png)

**Comment by ssrpanel** [comment]
宝塔安装得时候权限问题，

**Comment by wjainiya** [comment]
> 宝塔安装得时候权限问题，
哪里的权限呢？
storage目录权限还是mysql权限？

**Comment by ssrpanel** [comment]
mysql得权限

**Comment by wjainiya** [comment]
mysql> select user,host from mysql.user; 
+----------+------------------------+
| user     | host                   |
+----------+------------------------+
| repl     | %                      |
| root     | %  
这个权限吗？

**Comment by ssrpanel** [comment]
我也不清楚

**Comment by ssrpanel** [comment]
www.ssrpanel.com 演示站上试试看会不会出现这个问题

**Comment by wjainiya** [comment]
演示站上也有问题，我去看过了

**Comment by ssrpanel** [comment]
演示站也是用宝塔装得，我研究一下，晚点告诉你

**Comment by wjainiya** [comment]
ok

**Comment by ssrpanel** [comment]
找不到原因，演示站宝塔炸了。
