### ISSUE TITLE
用券时会出现这个。。求助。

### ISSUE THREAD

**Issue by kkkway** [ssrpanel/SSRPanel#919]
创建支付单失败：SQLSTATE[42S22]: Column not found: 1054 Unknown column 'desc' in 'field list' (SQL: insert into `coupon_log` (`coupon_id`, `goods_id`, `order_id`, `desc`, `updated_at`, `created_at`) values (9, 17, 120, 在线支付使用, 2018-09-16 15:02:50, 2018-09-16 15:02:50))

**Comment by kkkway** [comment]
![image](https://user-images.githubusercontent.com/24932999/45593859-a69e0280-b9c1-11e8-8c8c-336d7eb8b370.png)

**Comment by kkkway** [comment]
解决了，重新导一下sql即可。

**Comment by vft9nesd** [comment]
![image](https://user-images.githubusercontent.com/24932999/52869617-10912280-3181-11e9-80c3-b92787edebf3.png)
![image](https://user-images.githubusercontent.com/24932999/52869696-33233b80-3181-11e9-968c-c864730054ac.png)
![image](https://user-images.githubusercontent.com/24932999/52869783-61a11680-3181-11e9-9772-9ab0fed582fa.png)
![image](https://user-images.githubusercontent.com/24932999/52869947-c0ff2680-3181-11e9-9fa3-10db7afb4d12.png)
![image](https://user-images.githubusercontent.com/24932999/52870328-8e096280-3182-11e9-9866-8707b2565cde.png)
