### ISSUE TITLE
胖虎,请帮忙优先搞#18 和 #25号任务吗?

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#92]
可否把#18, #25, #27, #9, #10优先改完吗? 其中#18, #25最重要了.

#18.用户浏览行为过滤：禁止用户BT下载、迅雷、某轮网站 （要换到glzjin mod ssr）,这个太重要了,搞好了绝对减少了喝茶的风险啊.
#25.发布或者回复工单则自动发邮件提醒先完成啊?

#10可以通过robot文件直接禁止爬虫.
#27.可以后台手动给账号充值，而不是改余额
#9.封IP、IP段（限定某些地区访问网站）
#10.封来路（防爬虫）

下面我觉得不重要,可以晚点开发:

#19.自动续订流量包（后台加开关）
#23.增加单账号设备链接数量限制
#26.定时任务：每天凌晨4点统计一遍所有账号今天的总流量（user_traffic_daily）、今天每小时的总流量(user_traffic_hourly，这个可以没每小时统计一次，发现然后再写一个定时任务，只要发现最近一次流量使用超过限制值（假设10G），则自行禁用然后再用另一个定时任务去等一个小时候再开启)，主要目的是为了另一个定时任务：每月1号自动清空所有账号的流量，为了防止账号流量统计信息丢失，也为了跟踪账号的使用情况，还可以每天给账号发送今日流量使用情况：通过定时任务统计账号流量，而不是直接读取用户流量日志表，方便优化30日流量日志、1天内的流量日志

**Comment by ssrpanel** [comment]
@1021435278 18我得研究一遍魔改的ssr，费时间。25我在做了，你说的是23？

**Comment by 1021435278** [comment]
#25比较重要,可以直接通过邮件来提醒.
#23其实无所谓,总流量控制住,随便设备数,当然有更好.

**Comment by 1021435278** [comment]
@ZBrettonYe  这个无所谓,设置总流量,随便你玩.

**Comment by ZBrettonYe** [comment]
@1021435278 怕你是不知道，使用BT或者P2P 被IDC查到，是有可能对你账号进行封杀的

**Comment by 1021435278** [comment]
@ZBrettonYe 

SPAM应该是正常邮件,我觉得不需要封锁, 倒是BT/P2P需要封锁, 这个脚本建议给盼复发pull request 合并到某个地方就可以了.
