### ISSUE TITLE
是不是ipv6无法在qqwry查到，所以崩了？

### ISSUE THREAD

**Issue by kkkway** [ssrpanel/SSRPanel#924]
![image](https://user-images.githubusercontent.com/24932999/45629376-db48b180-bac8-11e8-8f3f-a3f22be94628.png)

服务器并没有ipv6，但cdn应该是可以ipv6访问
一个客户的手机是移动网，我们这边移动在部署ipv6，所以现在，只要是用ipv6的设备访问，就会炸

是否可以增加一个记录ip的开关，或者增加一个ipv6的数据库

**Comment by ssrpanel** [comment]
我去，ipv6的ip库貌似没找到。能帮我找看看吗？

**Comment by kkkway** [comment]
hah 或者 遇到无法查到的ip，直接跳过查询就行了，ipv6的库嘛，网上有的，都是老的了，这个截图的地址，查不到

**Comment by kkkway** [comment]
[ipv6wry.zip](https://github.com/ssrpanel/SSRPanel/files/2390934/ipv6wry.zip)

试试这个

**Comment by kkkway** [comment]
哈哈，这么牛逼，这是在他的网站下载的

**Comment by kkkway** [comment]
那个db能用吗

**Comment by ssrpanel** [comment]
日，有木马还用个屁，直接删除了。ipv6是强制的吗？

**Comment by ssrpanel** [comment]
用户端不可能没有IPV4

**Comment by kkkway** [comment]
我也觉得奇怪，这情况只是出现在移动4g访问，难道cdn会优先ipv6
不管这些了，我觉得遇到查不到的ip记录一个未知ip就行了，也不至于崩了😂

**Comment by kkkway** [comment]
这个网站有api接口，可以看一下，http://ip.zxinc.org/
数据库也是在他这里下的

**Comment by kkkway** [comment]
挂的cloudflare，强制自带ipv6，无法关掉，我再查查看😂
