### ISSUE TITLE
想添加一个新页面，在主页按“查看订阅”按钮，跳到新页面查看

### ISSUE THREAD

**Issue by 928zcz** [ssrpanel/SSRPanel#926]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
类似于这种，
![image](https://user-images.githubusercontent.com/42931911/45662122-239cb980-bb33-11e8-8507-022572a70f38.png)

感觉这样可以方便简洁很多，但是自己操作又操作不来。控制器和视图都添加了，显示404，不知道还漏了哪一步。向各位大佬求救T T

**Comment by 928zcz** [comment]
都添加好了，但是在订阅页面里，重置订阅点了确定没有反应。
在主页重置点确定是有反应的。

**Comment by ssrpanel** [comment]
那个是早期版本用的，现在已经废弃了

**Comment by 928zcz** [comment]
谢谢胖虎回复，已经搞好啦。
主要是因为很多萌新，根本不知道主页上面有订阅地址，就算标注了，很多人都会选择性不看。
所以我想着还是老样子做一个按钮，醒目点，这样子也能让萌新更加清楚了。
