### ISSUE TITLE
我不是能明白那个QR码的问题，求解答

### ISSUE THREAD

**Issue by Hao-Luo** [ssrpanel/ssrpanel#93]
求解答一下那个QR码的问题，为什么你要在后面加上vpn那个关键字，我的软件不能识别带有vpn关键字的qr码，所以我自己那里把那个关键字去掉了。你的软件是要用vpn那个关键字才可以进行识别么？

**Comment by ssrpanel** [comment]
方便截图我看下吗

**Comment by Hao-Luo** [comment]
好 请看图
![capture](https://user-images.githubusercontent.com/3833026/32541301-3379ef3a-c467-11e7-89c3-1c5e64329326.PNG)

**Comment by ssrpanel** [comment]
这个我是看官方文档滴。。。以前破娃那个滴。会导致你什么软件（哪个环境下）的什么问题啊

**Comment by ssrpanel** [comment]
@Hao-Luo 而且不对了，你这个代码要更新了。。。

**Comment by Hao-Luo** [comment]
软件是ssrconnectpro ios, 你试过扫码添加节点么？  这个代码是从你最新的代码来得。 你指的代码更新是什么？

**Comment by ssrpanel** [comment]
@Hao-Luo 对，代码先pull git到最新，你画圈的那个字符串，目的是为了在扫描二维码的时候自动添加到节点里节点备注信息里自动填写为VPN的。如果你不需要可以去掉，我用小火箭、potatso 2、ssr c#、ssr-xng测了没毛病。没有用过ss c#

**Comment by Hao-Luo** [comment]
好的谢谢
