### ISSUE TITLE
胖虎大佬，流量包到期之后已用流量不会清空

### ISSUE THREAD

**Issue by niyeyeqi** [ssrpanel/SSRPanel#932]
胖虎大佬，流量包到期之后已用流量不会清空

**Comment by ssrpanel** [comment]
现在还会吗？

**Comment by ssrpanel** [comment]
应该修复了吧

**Comment by niyeyeqi** [comment]
可能是我看出错，谢谢dalao

**Comment by niyeyeqi** [comment]
准确的说是，有套餐和流量包在一起的时候不会重置
![1](https://user-images.githubusercontent.com/31157068/45993985-2adc3e00-c0c4-11e8-9498-151e9f877747.png)
![2](https://user-images.githubusercontent.com/31157068/45993989-2d3e9800-c0c4-11e8-9bf5-593707c3c710.png)

**Comment by ssrpanel** [comment]
无法重现
