### ISSUE TITLE
建议 为列表用户名添加跳转更有效地管理后台

### ISSUE THREAD

**Issue by garhing** [ssrpanel/SSRPanel#938]
由于还未能玩好git,不懂pr，只能开个建议。

管理后台的订单管理，用户列表，邮件记录等多处如为用户名添加跳转，可省掉一些麻烦。例如将SSRPanel / resources / views / admin /orderList.blade.php第85行

< td > {{ $ order - > user - > username } } </ td >

改为

〈td> 〈a href="{{url('admin/userList?port=') . $order->user->port}}" target="_blank"> 〈span class="label label-info">{{$order->user->username}} </span〉 </a〉 </td〉

以上。

**Comment by SheffieldLee** [comment]
主要是懒，不想写，稳定第一……

**Comment by ssrpanel** [comment]
@SheffieldLee 同。。。

**Comment by garhing** [comment]
……我竟无言以对
