### ISSUE TITLE
能否增加套餐下自定义节点或节点分组啊

### ISSUE THREAD

**Issue by ppllpig** [ssrpanel/ssrpanel#94]
由于希望游戏用户和视频用户分开，VPS上暂时没办法实现，在套餐内实现，开通套餐自动显示对应节点，这样连用户分组都省了，胖虎你觉得呢~~~

**Comment by ssrpanel** [comment]
@ZBrettonYe 真的是偷懒了。。因为用户端的商品和节点信息我都要改掉。
