### ISSUE TITLE
单端口无法记录流量

### ISSUE THREAD

**Issue by yjj618** [ssrpanel/SSRPanel#944]
定时任务正常，流量日志也没有，过了一晚上也没有记录
改多端口后正常了

**Comment by yjj618** [comment]
单端口多用户你是用协议参数识别用户的吗？

**Comment by yjj618** [comment]
用户端口+密码是不是？

**Comment by ssrpanel** [comment]
我不会有这个问题，如果是宝塔装的，我不没办法帮你，如果是lnmp装的，请再认真翻一遍项目首页和wiki
