### ISSUE TITLE
SSTAP无法订阅

### ISSUE THREAD

**Issue by 493Arceus** [ssrpanel/SSRPanel#946]
![image](https://user-images.githubusercontent.com/17383497/45926666-8be70300-bf58-11e8-88d2-63aa05aa8ef1.png)
订阅链接获取到的是 无可用节点或账号被封禁或订阅被封禁
节点也添加了标签
后台手动获取SCHEME地址可以正常使用

**Comment by ZBrettonYe** [comment]
你不适合使用此面板

**Comment by ssrpanel** [comment]
面板里都有提示，如果看不到节点，可能是没有关联标签
