### ISSUE TITLE
提交一个在demo上反复验证过的套餐问题

### ISSUE THREAD

**Issue by zcz-nb928** [ssrpanel/SSRPanel#947]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
demo上的yyyang@yyyang.com账号。我把他设置为明天（9.25）到期，流量为0。
然后切换到他的身份，用余额去购买套餐。不管购买哪个套餐，时间加了，流量不会叠加。
我的流程如下：
2018.9.25到期     剩余0B     然后购买了180天的套餐    变为
2019.3.23到期     剩余0B     然后购买365天套餐    变为
2019.9.24到期     剩余-900GB

**Comment by zcz-nb928** [comment]
@ssrpanel

**Comment by LEE-Blog** [comment]
尝试重现该反馈，发现是新用户第一次购买套餐没问题。

但如果该用户买过任意套餐/流量包，之后过期了，第二次购买则不会增加流量。

**Comment by zcz-nb928** [comment]
@SheffieldLee 
大佬，你的逻辑我看懂了并且逻辑本身没错。

有个疑问，手动修改的流量，是否属于永久性流量    （还是说到了用户的有效期会清零）

**Comment by ssrpanel** [comment]
@SheffieldLee 解释那么多浪费时间。
