### ISSUE TITLE
关于有赞云支付的问题

### ISSUE THREAD

**Issue by DanielZhang17** [ssrpanel/SSRPanel#948]
今天新装了最新的面板，按照Wiki里的方法设置了有赞云支付，测试了一下1分钱的是否成功，然后发现微信支付成功之后微小店app里提示收到支付，但是页面并没有更新。等了10分钟左右看订单还是未支付状态。
怀疑我的自动任务出问题了，然后就去看了一下log文件
然后发现；了如下错误：

> 【有赞云】审计订单时更新支付单和订单异常：Undefined index:  pay_type

请问胖虎大佬怎么破？
还有貌似有赞的接口更新了，是不是和那个有关呢

**Comment by cmmdwl** [comment]
你是不是勾选的东西不对？

**Comment by DanielZhang17** [comment]
我把所有东西都勾选了

**Comment by DanielZhang17** [comment]
我别的定时任务都没毛病，所以应该不是定时任务的锅，id和secret都是检查过的，而且直接复制的。
并且我测试付款之后我的微小店显示有订单已完成。但我找不到任何推送记录，不管是在面板的推送记录还是在有赞的推送记录里都没有，但是我的的确确收到了付款而且推送地址和所有能开推送内容的都开了。只是现在有个V3什么的，不知道和原来的一起开会不会冲突。
我看着那个log里的错误有点神奇,pay type这个应该是数据库里的index，不清楚是什么操作。
`Undefined index: pay_type`
还请胖虎大佬看看是什么原因导致的，我已经排查过所有我能想到的问题，并没有发现问题，所以表示一脸懵逼

**Comment by ssrpanel** [comment]
这个pay_type ，你确定支付成功了吗？这个是一个定时任务去检查 付款完 有赞的回调推送过来没有推送成功（你推送设置错了？？？），在发现没有推送消息的时候，就自动去检查有赞那有没有订单付款了但是没推送消息过来的订单，到本地关联一下把本地订单给处理掉。

**Comment by ssrpanel** [comment]
pay_type 是 有赞查订单的时候返回的，估计是你有赞后台的没有设置好，所以对方那边字段漏了

**Comment by DanielZhang17** [comment]
推送地址没问题啊，直接复制的，而且支付确定成功了

**Comment by ssrpanel** [comment]
那我就不知道了

**Comment by DanielZhang17** [comment]
有赞设置是按Wiki里的来的 ，但是不是很清楚是不是有些东西要关。还有是不是和我有cloudflare CDN有关

**Comment by DanielZhang17** [comment]
刚刚看到20条已推送消息，但是全部失败。。。

**Comment by DanielZhang17** [comment]
看了有赞的日志，显示推送是false sign,是我SSL的问题？

**Comment by DanielZhang17** [comment]
看了一下失败的推送，每一个里面都有pay_type这个参数，从面板log这里的报错来看是不识别这个参数。。。
我看那个推送上返回的这个参数是微信代销
请问大家有赞里勾选了哪些？我交易消息V3和交易消息这些都勾选了，是不是只能选其中一个？我感觉他在两个都选的情况下有先使用了V3，是不是因为这个多了字段所以失败？
我是不是可以把pay_type这个参数去掉再试？

**Comment by cmmdwl** [comment]
就勾选一个交易信息类

**Comment by DanielZhang17** [comment]
交易信息还是交易信息V3。。。
我看他说是年底停止推送
所以一脸懵逼，现在怀疑是不是cloudflare把这个给拦截了。。。

**Comment by DanielZhang17** [comment]
测试了一下直接访问这个推送地址，显示404界面，貌似不正常啊，应该啥都没有然后在后面返回一个JSON才对吧。。。我看看重新安装一次面板行不行

**Comment by DanielZhang17** [comment]
修好了，大概知道是什么问题了，应该是用root装在宝塔环境下导致的，无语，刚刚把目录所有者改成www就好了

**Comment by ssrpanel** [comment]
有事宝塔 权限？

**Comment by ssrpanel** [comment]
这个锅我不背

**Comment by lovage** [comment]
> 修好了，大概知道是什么问题了，应该是用root装在宝塔环境下导致的，无语，刚刚把目录所有者改成www就好了

求告知具体操作步骤，我也遇到同样的坑了。。。

**Comment by ssrpanel** [comment]
@lovage 
chown -R www:www storage

**Comment by ssrpanel** [comment]
chmod -R 755 storage
