### ISSUE TITLE
前端皮肤文件在哪里

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#95]
胖虎,想把你的默认前端模版修改下,请问该文件/目录路径在哪里?

**Comment by ZBrettonYe** [comment]
@1021435278 /resources/views/   这个目录下就是界面

**Comment by ZBrettonYe** [comment]
皮肤这些 我觉得应该在 public 这个目录下面

**Comment by ssrpanel** [comment]
@1021435278 @ZBrettonYe 在resource目录下
