### ISSUE TITLE
编辑完mail.php之后其他页面出现错误

### ISSUE THREAD

**Issue by AGLcaicai** [ssrpanel/SSRPanel#951]
按教程设置好mail.php之后其他页面出现错误
错误信息：
Fatal error: Uncaught Error: Class 'Config' not found in /www/wwwroot/shadowlink.top/ssrpanel/app/Exceptions/Handler.php:49 Stack trace: #0 /www/wwwroot/shadowlink.top/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(326): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalThrowableError)) #1 /www/wwwroot/shadowlink.top/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(124): Illuminate\Foundation\Http\Kernel->renderException(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalThrowableError)) #2 /www/wwwroot/shadowlink.top/ssrpanel/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request)) #3 {main} thrown in /www/wwwroot/shadowlink.top/ssrpanel/app/Exceptions/Handler.php on line 49

**Comment by cmmdwl** [comment]
现在不使用mail.php了

**Comment by AGLcaicai** [comment]
> 现在不使用mail.php了

那如果要设置邮件发送功能那些要在哪里设置呢

**Comment by SRCOL** [comment]
@AGLcaicai 都在.env里

**Comment by cmtomkan310** [comment]
@SRCOL 直接在SSRPanel目录下  vi .env  就可以了！

**Comment by AGLcaicai** [comment]
> @AGLcaicai 都在.env里

好的，谢谢我去看看
