### ISSUE TITLE
小弟发现了几个小问题，希望能得到改善一下：

### ISSUE THREAD

**Issue by dongfangweiyu** [ssrpanel/SSRPanel#953]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
1. 订阅功能无效。
如图： 
![image](https://user-images.githubusercontent.com/43637779/46136582-85b79600-c27a-11e8-9dc8-57f34f473899.png)
手动输入信息是可以用的，订阅是用不了的。

2.邀请注册功能的返利。**（经验证没问题）**
  被邀请的人能获得赠送的流量。
  邀请人没有收到赠送相应的流量。
  应该双方都收到赠送的流量。

3.有效期的逻辑问题（个人疑惑）
  个人觉得账号的有效期应该跟流量包或者套餐挂钩。
  一、只要在流量包或者套餐没有过期的前提下，还有剩余流量。账号的有效期应该大于或等于流量包或套餐的有效期。
 购买流量包或套餐时，相应的增加账号有效期。（账号已过期时，购买流量包或套餐增加有效期。有效期增加的规则：
      **账户有效期=（账户有效期>当前日期？账户有效期：当前日期）+所购买的商品有效期**
   
   二、通过积分兑换的流量：  
      **账户有效期=（账户有效期>当前日期？账户有效期：当前日期）+7天 **
   三、通过邀请获得赠送的流量：
     **账户有效期=（账户有效期>当前日期？账户有效期：当前日期）+30天 **

  四、如果还在有效期内，可是流量用完了。应该把账号置为过期。
        账户有效期 = 当前日期
      

4.个人疑惑
  每月1号重置： 购买了套餐时。用户面板会显示每月1号重置，不知道这个重置是个什么意思。希望大佬帮帮我。
   假设我总共有30G的流量。现在用了3G了，下个月1号，我的可用流量变为27G还是又重置为30G了。

**Comment by dongfangweiyu** [comment]
第二个问题，是正确的。我没有通过邮件验证，直接后台改数据激活的。忽略。

**Comment by dongfangweiyu** [comment]
还有一个UI显示的问题，首页的个人中心，点击充值按钮，弹窗里的充值方式，显示的是优惠券。应该显示充值券。

**Comment by dongfangweiyu** [comment]
4.第四个问题的补充，系统设置里面关闭了每月自动重置，个人中心页面不应该再提示 每月1号重置。

**Comment by cmmdwl** [comment]
订阅功能是正常的，ssr是仅支持TLsv1的 因此，你没有好好看教程
每月一号重置是以为之前某些特殊设定导致无法正确核销所以只能全部调到1号，现在已经修复
