### ISSUE TITLE
有时候购买成功后，流量被清空了

### ISSUE THREAD

**Issue by greatvpn** [ssrpanel/SSRPanel#956]
购买成功后，流量被清空了
![default](https://user-images.githubusercontent.com/38743011/46189794-0e8a0c80-c323-11e8-8822-a0bc7545486a.png)
![default](https://user-images.githubusercontent.com/38743011/46189803-18137480-c323-11e8-815d-6d642fe1c616.png)
这什么原因造成的？不是说已经修复了吗？更新以后此问题有时候还会出现

**Comment by greatvpn** [comment]
![default](https://user-images.githubusercontent.com/38743011/46192191-d25ba980-c32c-11e8-8149-70f7ce8e4d8c.png)
为何支付成功了 还被禁用清空了？
![default](https://user-images.githubusercontent.com/38743011/46192142-afc99080-c32c-11e8-897a-7c860e5659ad.png)

**Comment by longdoer** [comment]
这个问题我昨天还想提issues,用户购买有时候会出现这种问题，购买成功了 日期有了 就是没流量 并且禁用记录是在支付成功之后还执行过

**Comment by garhing** [comment]
刚好我今天也遇到了这情况，我还以为修复了。

**Comment by ssrpanel** [comment]
消息推送检查一下？

**Comment by longdoer** [comment]
全都是开启勾选的

**Comment by ssrpanel** [comment]
检查权限，看上一个issues，我严重怀疑你们用宝塔，权限又错了

**Comment by greatvpn** [comment]
@garhing 是的 我也郁闷 为什么 购买成功了 还重置用户流量？

**Comment by LEE-Blog** [comment]
你们可以留意一下，发生这种情况的用户，
一般是不是「已过期的」or「购买套餐时使用手机」？

**Comment by garhing** [comment]
> 你们可以留意一下，发生这种情况的用户，
> 一般是不是「已过期的」or「购买套餐时使用手机」？

未能复现，不过看了，是已过期的用户。
