### ISSUE TITLE
反馈：工单回复(百度编辑器) 实际仅能发送 100 字符。

### ISSUE THREAD

**Issue by LEE-Blog** [ssrpanel/SSRPanel#957]
![screen_20180928_171040](https://user-images.githubusercontent.com/20637016/46199768-71d76700-c342-11e8-813b-81f9713356d8.png)
（在 DEMO 中测试的结果）

如图，无论 管理后台 or 用户界面 ，工单回复时，实际只能发布前 100 字符的文字，多出部分会被截除。

------

同时，由于移动端使用频率较高。
个人建议将编辑器更换为 wangEditor ( https://github.com/wangfupeng1988/wangEditor/ )，在移动端使用体验更佳。

谢谢。

**Comment by ssrpanel** [comment]
有空我换一下

**Comment by ssrpanel** [comment]
暂时搁置
