### ISSUE TITLE
我的域名后缀是.tech，改节点绑定域名被说不合法

### ISSUE THREAD

**Issue by RabiChannel** [ssrpanel/SSRPanel#958]
Emm
我用.top的域名没问题
.tech的域名就飞天了

前几天从5月初的版本更到了最新
然后改不了绑定域名了

emm我该怎么操作一下呢

【是我的错
【用这种非主流域名

**Comment by ssrpanel** [comment]
好滴，我加上

**Comment by ssrpanel** [comment]
已加上
