### ISSUE TITLE
账号激活链接 404 报错

### ISSUE THREAD

**Issue by ZBrettonYe** [ssrpanel/ssrpanel#96]
邮箱发出去的激活连接 404报错； 可以通过什么办法检查错误的地方？  之前注册链接还正常的，上个版本更新后，出现的问题

**Comment by ssrpanel** [comment]
@ZBrettonYe 是不是少装了什么php的组件，验证码那个需要php支持image、gd、gd2、fileinfo四个组件。你在项目里执行 php composer.phar install 看看有没有报错

**Comment by ZBrettonYe** [comment]
不是验证码， 是新用户注册时 有激活邮件，他们反馈说点击激活连接后显示的网站是404

**Comment by ZBrettonYe** [comment]
http://awesomescreenshot.com/0446ebkhce
这个是404界面截图

**Comment by ssrpanel** [comment]
@ZBrettonYe 检查一下数据库里的verify表里有没有这条数据

**Comment by ZBrettonYe** [comment]
有数据的

**Comment by ZBrettonYe** [comment]
Verify里的token这些都还是正常生成的

**Comment by ZBrettonYe** [comment]
重装2次服务端后 找到错误，设置中的网站地址要和SSRpanel地址一致
