### ISSUE TITLE
Bug:更新代码后，协议、混淆下来菜单均为空

### ISSUE THREAD

**Issue by Feifanbaba** [ssrpanel/SSRPanel#961]
今天更新代码后，更新代码后，协议、混淆下来菜单均为空：
[root@vultr ssrpanel]#  git pull
remote: Enumerating objects: 49, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 49 (delta 30), reused 37 (delta 27), pack-reused 0
Unpacking objects: 100% (49/49), done.
From https://github.com/ssrpanel/ssrpanel
   b6438ca..7e4d657  master     -> origin/master
Updating b6438ca..7e4d657
Fast-forward
 app/Console/Commands/AutoCheckNodeStatus.php |  2 +-
 app/Http/Controllers/AdminController.php     |  4 +++-
 resources/views/admin/addNode.blade.php      | 13 ++++++++++++-
 resources/views/admin/editNode.blade.php     | 13 ++++++++++++-
 sql/db.sql                                   |  1 +
 sql/update/20180928.sql                      |  3 +++
 6 files changed, 32 insertions(+), 4 deletions(-)
 create mode 100644 sql/update/20180928.sql

**Comment by ZBrettonYe** [comment]
不是更新的锅

**Comment by Feifanbaba** [comment]
这个是我的问题，我重新更新了一下库，没问题了
