### ISSUE TITLE
ipv6下无法访问

### ISSUE THREAD

**Issue by yulewang** [ssrpanel/SSRPanel#962]
Exception没有处理

(1/1) ErrorExceptionUndefined index: country
--
in Forbidden.php line 38
at HandleExceptions->handleError(8, 'Undefined index: country', '/www/wwwroot/xxx/app/Http/Middleware/Forbidden.php', 38, array('request' =>object(Request), 'next' => object(Closure), 'config' => object(Config), 'ip' => '1234:ab00:55:66:890b:xxxx:yyyy:dddd', 'qqwry' => object(QQWry), 'ipInfo' =>array('error' => 'ip invalid')))in Forbidden.php line 38

**Comment by cmmdwl** [comment]
正常，还没修复，就像部分电信4g ip一样

**Comment by ssrpanel** [comment]
电信4G ip会怎么样？

**Comment by cmmdwl** [comment]
部分电信4g 的ip没有被收入，然后就报错了

**Comment by DanielZhang17** [comment]
不仅是电信的IP，移动网络好多都有这个问题
建议改一下规则

**Comment by ssrpanel** [comment]
IP地址给我一个、？？？

**Comment by ssrpanel** [comment]
修复了貌似

**Comment by DanielZhang17** [comment]
142.177.130.118 -Bell Canada LTE
访问面板404,Log里有如下错误：

`ErrorException: Undefined index: country in /www/wwwroot/ssrpanel/app/Http/Middleware/Forbidden.php:38`

**Comment by DanielZhang17** [comment]
而且我没有在面板里禁止任何IP，应该不验证才对，登陆IP国家如果不识别应该写未知，而不是直接错误

**Comment by ssrpanel** [comment]
@

**Comment by ssrpanel** [comment]
@DanielZhang17 代码更新了？

**Comment by DanielZhang17** [comment]
更新了

**Comment by ssrpanel** [comment]
我试了，你这个IP没毛病

**Comment by DanielZhang17** [comment]
IPv4是142.177.130.45

**Comment by ssrpanel** [comment]
系统里没有IPv6的库

**Comment by ssrpanel** [comment]
你们那现在是强制通过IPv6上网？

**Comment by ssrpanel** [comment]
修复了

**Comment by DanielZhang17** [comment]
运营商默认的，而且我服务器也有IPv6

**Comment by ssrpanel** [comment]
已fixed
