### ISSUE TITLE
商品“添加失败”问题

### ISSUE THREAD

**Issue by JadeVane** [ssrpanel/SSRPanel#969]
点击`商品管理`中的`添加商品`，如果添加的时候有些参数设置错误会有提示，但是如果参数没有错误，则提示添加失败，是哪里出问题了吗？
![image](https://user-images.githubusercontent.com/34258753/46331083-b3b92380-c648-11e8-8429-bb22260dc001.png)

**Comment by ZBrettonYe** [comment]
编辑时间太久了？

**Comment by JadeVane** [comment]
都是最新的，而且之前是能够添加商品的，现在能够通过数据库直接操作添加，所以不是数据库的问题

**Comment by JadeVane** [comment]
问题解决了，是代码更新但是数据库没有更新，所以更改数据库的时候匹配不上column
