### ISSUE TITLE
合并代码后这个提示，求大佬解答一下

### ISSUE THREAD

**Issue by zcz-nb928** [ssrpanel/SSRPanel#971]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
![image](https://user-images.githubusercontent.com/42931911/46353549-10d7c800-c68f-11e8-921f-a04d8d11c7c2.png)
用户页可以进，管理页就提示这个

**Comment by Hamishcn** [comment]
函数重新声明了吧 合并啥代码

**Comment by zcz-nb928** [comment]
> 函数重新声明了吧 合并啥代码

小白不太懂怎么更新啊，因为自己改过文件内容。然后这现在要怎么解决

**Comment by Hamishcn** [comment]
@zcz-nb928 你改了啥 ..把那个文件2211行发过来看看

**Comment by zcz-nb928** [comment]
> @zcz-nb928 你改了啥 ..把那个文件2211行发过来看看

![image](https://user-images.githubusercontent.com/42931911/46354463-3f56a280-c691-11e8-837a-bcf7e7ad92cd.png)
大佬你看下

**Comment by zcz-nb928** [comment]
> 你这个文件里八成是有俩 function userTrafficLogList 改个名就好了 或者看2211这个是不是上面那个的进化版 是就把上面那个删掉 反正两个留一个

感谢大佬！！！

**Comment by Hamishcn** [comment]
@zcz-nb928 我真的不是大佬...
