### ISSUE TITLE
邀请码可选，还是不能注册

### ISSUE THREAD

**Issue by zcz-nb928** [ssrpanel/SSRPanel#972]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
在不用邀请码和必须用邀请码的状态下，看起来没有问题

然后把邀请码设置为可选

填写完用户名和密码注册的时候，他提示让我输入邀请码
![image](https://user-images.githubusercontent.com/42931911/46362683-8d74a180-c6a3-11e8-927f-56d93e53edc8.png)

**Comment by zcz-nb928** [comment]
数据库什么都导入了

**Comment by zcz-nb928** [comment]
@ZBrettonYe 能解答下吗，是因为控制器没有改过的原因吗

**Comment by Bennett561** [comment]
对，我也是这样，可选 其实还是强制要

**Comment by ZBrettonYe** [comment]
丢脸了，是的，是因为没有修改过控制器；
本以为只要界面的required属性改改就好了

**Comment by zcz-nb928** [comment]
> 丢脸了，是的，是因为没有修改过控制器；
> 本以为只要界面的required属性改改就好了

哈哈，那我就关闭问题了。大佬尽快修复下~
