### ISSUE TITLE
新版本安装时 Composer 出现问题

### ISSUE THREAD

**Issue by DanielZhang17** [ssrpanel/ssrpanel#98]
最近看作者更新了代码于是在服务器上新开了一个站点安装，但是安装的时候报错，而且不是PHP版本问题，错误如下：

     Loading composer repositories with package information
     Installing dependencies (including require-dev) from lock file
     Warning: The lock file is not up to date with the latest changes in composer.json. You may be geRun update to update them.
     Your requirements could not be resolved to an installable set of packages.

      Problem 1
    - Installation request for intervention/image 2.4.1 -> satisfiable by intervention/image[2.4.1].
    - intervention/image 2.4.1 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
      Problem 2
    - intervention/image 2.4.1 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - mews/captcha 2.1.7 requires intervention/image ~2.2 -> satisfiable by intervention/image[2.4.1].
    - Installation request for mews/captcha 2.1.7 -> satisfiable by mews/captcha[2.1.7].

      To enable extensions, verify that they are enabled in your .ini files:
    - /www/server/php/71/etc/php.ini
      You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
目测是缺少组件，请问胖虎这个要怎么处理，之前版本没遇到过，可能和新版加了验证码有关

还有个小问题，就邮件服务器每次发邮件都提示connection timeout，但是我mail.php和.env里该改的都改了而且没有错误，我用的是outlook stmp的25端口，请问还有哪里要改的吗

**Comment by ssrpanel** [comment]
需要手动编译php的 image 、 fileinfo组件，如果用宝塔之类的，直接进去安装，如果用lnmp一键包，去手动编译安装，待我写一个教程放wiki里
