### ISSUE TITLE
tcp阻断检测是废了吗？

### ISSUE THREAD

**Issue by yjj618** [ssrpanel/SSRPanel#986]
昨天晚上被封了，到现在一个提醒都没有

**Comment by ssrpanel** [comment]
ipcheck.need.sh废了貌似

**Comment by ssrpanel** [comment]
我前两天用的时候很稳，貌似不太稳定，同时几百个网站（SSRPanel面板），每个网站5个节点在检测，在同一个小时内的前1分钟，假设 400 站点 * 5个节点 = 2000 ，1分钟内ipcheck要接收这么多的检测，不晓得对方会不会抽风
