### ISSUE TITLE
节点直接读取数据库会不会不安全？

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#987]
看了许多人的操作，节点好像都是使用了root账户来登陆数据库
我在想，这样的安全性好像不行
并且，数据库与节点的通信好像是明文的？
能否呢用类似api的方式来与面板通信或者与数据库通信？
这样可以隔离数据库的直接访问
主要是最近数据库老是被扫描。。。

**Comment by Losgif** [comment]
ss my api

cmmdwl <notifications@github.com>于2018年10月7日 周日22:08写道：

**Comment by ssrpanel** [comment]
1.群里有人问过，也喊我帮忙做一个后端的混淆版本，不过python我目前还在捣鼓，技艺不精，我是不会用root来进行远程的，这个是服务器运维的知识，mysql开特定数据库特定账号只给最基础的权限，我觉得没毛病，是他们不会搞。
2. ss mu api 那个，ssr后端貌似并没有mu 版本，或者说没人开发了。有找到的话贴上来
