### ISSUE TITLE
最新版本代码有问题, 后端无法连接上.

### ISSUE THREAD

**Issue by 1021435278** [ssrpanel/ssrpanel#99]
表现故障如下:
新建控制中心 + 控制中心本机后端ssr, 用户第一次链接没问题, 但第二次连接后,后端不起作用, 导致产生类似被墙的现象,但实际上只是主控端出问题,用户无法使用ssr而已.

最新附加测试结果, 新加的所有节点, 跑teddysun的ssr用户端单独连接就没问题, 所以问题肯定出在最新版本代码上.

另外胖虎请尽快开始单端口多用户了. 这种高墙无法屏蔽, 因为常用端口的话, 比如80,根本无法屏蔽.

**Comment by 1021435278** [comment]
也有可能是最新版本的问题, 请胖虎测试下最新版本,因为我新加的节点也无法fq, 但新加的接单python server.py都能检测无误. @ssrpanel

**Comment by 1021435278** [comment]
最新附加测试结果, 新加的所有节点, 跑teddysun的ssr就没问题, 所以问题肯定出在最新版本代码上. 

表现故障如下:
新建控制中心 + 控制中心本机后端ssr, 用户第一次链接没问题, 但第二次连接后,后端不起作用, 导致产生类似被墙的现象,但实际上只是主控端出问题,用户无法使用ssr而已.

**Comment by ssrpanel** [comment]
@1021435278
这个跟面板没半毛钱关系啊。

**Comment by 1021435278** [comment]
@ssrpanel  有关系啊, 之前的ssrpanel代码就没做过问题, 这几天发布的代码有问题,可否测试下就知道了.

**Comment by Hao-Luo** [comment]
面板和后端是分开的 更新面板怎么会影响后端链接。 你就是把面板删除了，后端也还是能用的。
