### ISSUE TITLE
标题栏太难看了

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#990]
建议自定义一些标题栏
我指的是浏览器最上面的图标和文字

**Comment by Losgif** [comment]
![image](https://user-images.githubusercontent.com/13404752/46582881-81605980-ca80-11e8-905d-78ed3280c7e0.png)
自己根据自己写的API开发的前端
技术栈 vue 全家桶 + element-ui + material ui

**Comment by Losgif** [comment]
关键还是自己动手能力
毕竟这是个技术社区

**Comment by cmmdwl** [comment]
膜拜一下，目前海没看懂这个框架呢。。。

**Comment by ssrpanel** [comment]
vue.js好痛苦。我学的好蛋疼

**Comment by ssrpanel** [comment]
我们公司实际业务用的Vue.js，看似很爽，维护起来好痛苦

**Comment by Losgif** [comment]
phper 学起来是挺难受的
我也是学学停停 vuejs
刚刚学了个皮毛吧

**Comment by Losgif** [comment]
所以前端工程化很有必要
前后端分离不分离小项目不是很重要
结构不合理
代码逻辑不清晰才是最要命的
一个高级前端认真写出来的代码不会难受的

**Comment by ZBrettonYe** [comment]
限制设备，膜拜一下

**Comment by ssrpanel** [comment]
标题栏不打算改，主要是怕特征太多，会被爬虫收录了，网站域名会被墙或者dns污染
