### ISSUE TITLE
订单无法根据用户名查询

### ISSUE THREAD

**Issue by 828768** [ssrpanel/SSRPanel#991]
订单根据用户名查询不出结果，整个订单按条件过过滤查询功能都有问题
![image](https://user-images.githubusercontent.com/6386202/46589771-4beb5880-cae0-11e8-83ab-ccbf63853488.png)

**Comment by cmtomkan310** [comment]
我也提一个订单问题，订单查询按照条件查询后，第一页没有问题，点击第二页先前选择的条件就无效了，所以上面的参数形同虚设！这个问题一直存在！

建议：目前SSRPanel面板整体相对稳定，我觉得把目前现有的功能完善和修复bug，比不断的推出新功能要重要！

**Comment by ssrpanel** [comment]
@cmtomkan310 ========等我搞

**Comment by ssrpanel** [comment]
@cmtomkan310 目前已经够用了，所以推出新功能，都要拿来卖钱了。不想开源了，233333

**Comment by ssrpanel** [comment]
fixed ，@garhing 给我挖的坑

**Comment by garhing** [comment]
> fixed ，@garhing 给我挖的坑

胡说，明显不是我提的pr
