### ISSUE TITLE
有赞订单成功支付 但面板订单依然显示待支付 Undefined index: pay_type

### ISSUE THREAD

**Issue by yzdedream** [ssrpanel/SSRPanel#994]
今天下午左右（2018-10-08 16:56:26）开始出现支付异常。以往订单均正常，配置未改变。
日志显示 有赞回调Trade_success成功
但有此异常日志
`【有赞云】审计订单时更新支付单和订单异常：Undefined index: pay_type`
有赞后台交易消息V3已开启，面板更新到9月28日版本。
第一次支付异常后关闭了有赞后台交易消息V1 的推送，问题持续。

**Comment by hj-mb** [comment]
成功复现 今晚刚刚更新
日志完全一样

**Comment by cmmdwl** [comment]
【有赞云】审计订单时更新支付单和订单异常：Undefined index: pay_type
同样复现，未更新

**Comment by cmmdwl** [comment]
{"update_time":"2018-10-08 20:42:15","extra_info":"{\"is_retail_offline\":false}","payment":"0.10","pay_type":"支付宝","book_id":null,"tid":"E2018100******5083900008","status":"TRADE_SUCCESS"}

**Comment by cmmdwl** [comment]
观察发现 原来有赞发来的回调是{"update_time":"2018-10-08 20:42:15","extra_info":"{\"is_retail_offline\":false}","payment":"0.10","book_id":null,"tid":"E2018100*******83900008","status":"TRADE_SUCCESS"}这样的，似乎是有赞对回调加了一个提示导致的

**Comment by cmmdwl** [comment]
pay_type 找一个测试的同学 打开https://console.youzanyun.com/application/msg_config 选择交易付款旁边的参数配置 关掉 pay_type 再试试 我这好像没啥问题了

**Comment by cmtomkan310** [comment]
@cmmdwl 关掉pay_type问题依旧！

**Comment by hj-mb** [comment]
我没有找到“交易付款” 我和@cmtomkan310 找到的应该是一个 但这个回调的似乎是number属性 和我们要找的不一样

**Comment by cmtomkan310** [comment]
我又发现个大问题，现在所有订单支付成功后，比如微信，在微信里面看到【商户全称】之前都是杭州起码科技有限公司，现在都变成个体户+自己的姓名了！真操蛋

**Comment by hj-mb** [comment]
@cmtomkan310 能给个打码截图看一下吗 我不用微信 非常感谢

**Comment by cmtomkan310** [comment]
![image](https://user-images.githubusercontent.com/38905231/46612569-876b3e80-cb43-11e8-8f4c-31baf1f584fb.png)
![image](https://user-images.githubusercontent.com/38905231/46612585-94882d80-cb43-11e8-91df-2d945d185181.png)

**Comment by hj-mb** [comment]
@cmtomkan310 多谢

**Comment by cmmdwl** [comment]
@cmtomkan310 你关错了，是那个返回文本的那个玩意

**Comment by cmmdwl** [comment]
你这个返回的是一个数值

**Comment by hj-mb** [comment]
@cmmdwl 能详细指点一下吗 非常感谢

**Comment by cmmdwl** [comment]
找到一个返回是文本值的参数，关掉它

**Comment by hj-mb** [comment]
@cmtomkan310 我刚刚找人试了一下 显示的仍然是杭州起码科技有限公司

**Comment by cmtomkan310** [comment]
@cmmdwl 能否直接说那个？
![image](https://user-images.githubusercontent.com/38905231/46615122-19764580-cb4a-11e8-9bb2-76c705e4b009.png)

**Comment by cmtomkan310** [comment]
@hj-mb 为什么我显示的是个体商户xxx

**Comment by hj-mb** [comment]
@cmtomkan310 可能因为我是非大陆手机号注册的

**Comment by cmtomkan310** [comment]
@hj-mb 返回文本那个你找到没？在哪儿？

**Comment by hj-mb** [comment]
@cmtomkan310 没 找到就说了

**Comment by RabiChannel** [comment]
是不是有赞的问题，我也是下午开始这样，然后现在突然就好了

**Comment by cmtomkan310** [comment]
的确现在好了！但是我上面提到的个体商户的问题，还是存在啊

**Comment by RabiChannel** [comment]
@cmtomkan310 我显示的是我微小店的名字，要不你跟有赞提个ticket问下，毕竟小公司

**Comment by ssrpanel** [comment]
有赞的问题

**Comment by dovela** [comment]
昨天好了，今天又报错【有赞云】审计订单时更新支付单和订单异常：Undefined index: pay_type
只能等有赞云那边自己修复吗？

**Comment by hj-mb** [comment]
@dovela 刚刚测试 一切正常

**Comment by dovela** [comment]
傻了，想看看但是找不到request在哪，@ssrpanel 请问获取request的代码在哪个路径下？

**Comment by dovela** [comment]
看了下逻辑似乎和pay_type一点关系都没有，这报错真绝了
