### ISSUE TITLE
有赞订单支付扣款后，页面不返回确定信息！

### ISSUE THREAD

**Issue by cmtomkan310** [ssrpanel/SSRPanel#995]
![image](https://user-images.githubusercontent.com/38905231/46607131-5b938d00-cb32-11e8-8460-4f55dcc68422.png)

以上三个订单全部支付成功了！从今天下午5点开始出现这个问题，之前一直正常！有赞用的V3交易全开，其他没开！

**Comment by hj-mb** [comment]
#994

**Comment by ssrpanel** [comment]
有赞的问题i
